/sbin/init: Maintanance update through replace_commit.sh .

diff --git a/woof-code/rootfs-skeleton/sbin/init b/woof-code/rootfs-skeleton/sbin/init
--- a/woof-code/rootfs-skeleton/sbin/init
+++ b/woof-code/rootfs-skeleton/sbin/init
@@ -143,9 +143,9 @@ Res='\033[0;39m'
 
 status_func() {
  if [ $1 -eq 0 ]; then
-  /bin/echo -e "\\033[72G\\033[1;32mdone\\033[0;39m" >/dev/console #green [done] msg.
+  echo -e "\\033[72G\\033[1;32mdone\\033[0;39m" >/dev/console #green [done] msg.
  else
-  /bin/echo -e "\\033[70G\\033[1;31mfailed\\033[0;39m" >/dev/console #red [failed].
+  echo -e "\\033[70G\\033[1;31mfailed\\033[0;39m" >/dev/console #red [failed].
   STATUS=0
  fi
  return $1 #return with same status as entry param.
@@ -156,9 +156,9 @@ test -f /etc/rc.d/PUPSTATE && . /etc/rc.d/PUPSTATE || PUPMODE=2
 #if [ ! -d /initrd -o "`busybox df | grep 'initrd'`" = "" ]; then
 if [ "$PUPMODE" = 2 ]; then
 busybox mount -o remount,rw /dev/root /
-#sleep 1s;mkdir -p /root/my-documents/boot;cp -r /tmp /root/my-documents/boot/tmp.old  ###+++2011-12-04
+#sleep 1s;mkdir $VERB -p /root/my-documents/boot;cp $VERB -r /tmp /root/my-documents/boot/tmp.old  ###+++2011-12-04
 sleep 1s;rm -rf /tmp/*;rm -rf /tmp/.[a-zA-Z0-9]*  ##+++2011-11-08 moved here #+2011-11-17 added rm hidden files
- test -d /tmp || mkdir /tmp
+ test -d /tmp || mkdir $VERB /tmp
  chmod 1777 /tmp
 else
 STATUS=0
@@ -166,24 +166,26 @@ status_func $STATUS
 fi
 
 if [ -d /proc ]; then
-FINDPROC=`find /proc -maxdepth 1 -type f 2>/dev/null`
-[ -z "$FINDPROC" ] && busybox mount -t proc none /proc  ###KRG put here for additional df check (wary094 frugal had written /initrd into full install) ###KRG
+#FINDPROC=`find /proc -maxdepth 1 -type f 2>/dev/null`
+#[ -z "$FINDPROC" ] && busybox mount -t proc none /proc  ###KRG put here for additional df check (wary094 frugal had written /initrd into full install) ###KRG
+test -e /proc/mounts || busybox mount -t proc proc /proc
 else
-mkdir /proc
+mkdir $VERB /proc
 busybox mount -t proc proc /proc
 fi
 
 if [ -d /sys ]; then
-FINDSYS=`find /sys/* -maxdepth 0 -type d 2>/dev/null`
-[ -z "$FINDSYS" ] && busybox mount -t sysfs none /sys
+#FINDSYS=`find /sys/* -maxdepth 0 -type d 2>/dev/null`
+#[ -z "$FINDSYS" ] && busybox mount -t sysfs none /sys
+test -e /sys/bus || busybox mount -t sysfs sysfs /sys
 else
-mkdir /sys
+mkdir $VERB /sys
 busybox mount -t sysfs sysfs /sys
 fi
 
 mountpoint -q /dev || {
  test "`which mdev`" && {
- test -d /dev || mkdir /dev
+ test -d /dev || mkdir $VERB /dev
  mount -t ramfs devramfs /dev
         mdev -s; } ; } ###+++2014-06-25
 
@@ -220,9 +222,9 @@ do
 case $m in [0-9]*):;;*)continue;;esac
 
 rm -f "$1"/dev/$d
-STATUS=$(( $STATUS + $? ))
+STATUS=$(( STATUS + $? ))
 mknod "$1"/dev/$d b $m $n
-STATUS=$(( $STATUS + $? ))
+STATUS=$(( STATUS + $? ))
 echo -n '.' >/dev/console
 
 done<proc/partitions
@@ -388,51 +390,51 @@ else
 noDriversList=`echo "$nodrivers" | tr ',' '\n' | sed 's/^/blacklist /g'`
 fi
 fi
-[ $noalsa ] && safeBoot=10 && echo 'noalsa' >/tmp/alsa.flg
-[ $nographics ] && safeBoot=15 && echo 'nographics' >/tmp/graphics.flg
-[ $nofb ] && safeBoot=14 && echo 'nofb' >/tmp/framebuffer.flg
-[ $nofbcon ] && safeBoot=13 && echo 'nofbcon' >/tmp/fbcon.flg
-[ $userdrivers ] && safeBoot=2
-[ $kerneldrivers ]&& safeBoot=3
-[ $alldrivers ] && safeBoot=4
-[ ! "$safeBoot" ] && safeBoot=4
+[ $noalsa ]           && safeBoot=10 && echo 'noalsa'     >/tmp/alsa.flg
+[ $nographics ]       && safeBoot=15 && echo 'nographics' >/tmp/graphics.flg
+[ $nofb ]             && safeBoot=14 && echo 'nofb'       >/tmp/framebuffer.flg
+[ $nofbcon ]          && safeBoot=13 && echo 'nofbcon'    >/tmp/fbcon.flg
+[ $userdrivers ]      && safeBoot=2
+[ $kerneldrivers ]    && safeBoot=3
+[ $alldrivers ]       && safeBoot=4
+[ ! "$safeBoot" ]     && safeBoot=4
 [ "$safeBoot" = "0" ] && safeboot=9
 echo 'safeBoot='"$safeBoot"
 }
 failsafe_func
 
 modprobe_conf_func() {
-test -d /etc/mult_kernels || mkdir /etc/mult_kernels
+#test -d /etc/mult_kernels || mkdir $VERB /etc/mult_kernels
+#test -d /etc/mult_kernels/modprobe.d.$KERNVER || mkdir $VERB /etc/mult_kernels/modprobe.d.$KERNVER
 
-test -d /etc/mult_kernels/modprobe.d.$KERNVER || mkdir /etc/mult_kernels/modprobe.d.$KERNVER
-
-[ -d /etc/modprobe.d ] || mkdir /etc/modprobe.d
+test -d /etc/mult_kernels/modprobe.d.$KERNVER || mkdir $VERB -p /etc/mult_kernels/modprobe.d.$KERNVER
+[ -d /etc/modprobe.d ] || mkdir $VERB /etc/modprobe.d
 
 if test -f /etc/modprobe.conf; then #1
 if [ ! -f /etc/mult_kernels/modprobe.conf."$KERNVER" ]; then  ##&&
-cp -f "/etc/modprobe.conf" "/etc/mult_kernels/modprobe.conf.$KERNVER"
+cp $VERB -f "/etc/modprobe.conf" "/etc/mult_kernels/modprobe.conf.$KERNVER"
 else
-cp -f /etc/mult_kernels/modprobe.conf."$KERNVER" /etc/modprobe.conf
+cp $VERB -f /etc/mult_kernels/modprobe.conf."$KERNVER" /etc/modprobe.conf
 fi
 fi
 
 if test -d /etc/mult_kernels/modprobe.d."$KERNVER"; then #2
 rm -f -r /etc/modprobe.d
-cp -f -r /etc/mult_kernels/modprobe.d."$KERNVER" /etc/modprobe.d
+cp $VERB -f -r /etc/mult_kernels/modprobe.d."$KERNVER" /etc/modprobe.d
 elif test -d /etc/modprobe.d; then #2.1
-cp -r /etc/modprobe.d /etc/mult_kernels/modprobe.d."$KERNVER"
+cp $VERB -r /etc/modprobe.d /etc/mult_kernels/modprobe.d."$KERNVER"
 fi #2
 
-test -d /etc/mult_kernels/rc.d || mkdir /etc/mult_kernels/rc.d
+test -d /etc/mult_kernels/rc.d || mkdir $VERB /etc/mult_kernels/rc.d
 
 if test ! -f /etc/mult_kernels/rc.d/MODULESCONFIG."$KERNVER"; then
-cp /etc/rc.d/MODULESCONFIG /etc/mult_kernels/rc.d/MODULESCONFIG."$KERNVER"
+cp $VERB /etc/rc.d/MODULESCONFIG /etc/mult_kernels/rc.d/MODULESCONFIG."$KERNVER"
 else
 rm /etc/rc.d/MODULESCONFIG
-cp /etc/mult_kernels/rc.d/MODULESCONFIG."$KERNVER" /etc/rc.d/MODULESCONFIG
+cp $VERB /etc/mult_kernels/rc.d/MODULESCONFIG."$KERNVER" /etc/rc.d/MODULESCONFIG
 fi
 
-test -f /lib/modules/"$KERNVER"/DOTconfig* && cp /lib/modules/"$KERNVER"/DOTconfig* /etc/modules/
+test -f /lib/modules/"$KERNVER"/DOTconfig* && cp $VERB /lib/modules/"$KERNVER"/DOTconfig* /etc/modules/
 } #modprobe_conf_func inside update_modprobe_conf_func
 
 update_modprobe_conf_func(){
@@ -440,7 +442,7 @@ PATCH_EXE=`which patch`
 KERNVER=`uname -r`
 CONFFILE='/etc/modprobe.conf'
 [ -f /etc/modprobe.d/modprobe.conf ] && CONFFILE='/etc/modprobe.d/modprobe.conf'
-[ -f /etc/modprobe.d/puppy.conf ] && CONFFILE='/etc/modprobe.d/puppy.conf'
+[ -f /etc/modprobe.d/puppy.conf ]    && CONFFILE='/etc/modprobe.d/puppy.conf'
 basenameCONFFILE="${CONFFILE##*/}"
 
 modprobe_conf_func
@@ -460,7 +462,7 @@ WC=`echo "$SYSTEM" | wc -l`
 GREPpattern=$(echo "$SYSTEM" | head -n 1 | tr '\t' ' ' | tr -s ' ' | sed 's/\([[:punct:]]\)/\\\\\1/g; s/\\\\/\\/g')
 FIELD=`grep -B 1 -n "$GREPpattern" "$CONFFILE"`
 if [ -z "`echo "$FIELD" | grep "$GREPpattern"`" ] || [ -z "`echo "$FIELD" | grep "$KERNVER"`" ]; then
-cp "$CONFFILE" "$CONFFILE".`basename $0`."$KERNVER".sbin_init.bac
+cp $VERB "$CONFFILE" "$CONFFILE".`basename $0`."$KERNVER".sbin_init.bac
 echo >> "$CONFFILE"
 echo '#####  Updated modaliases for system  ###########' >> "$CONFFILE"
 echo '### RUNNING kernel '"$KERNVER" >> "$CONFFILE"
@@ -524,6 +526,14 @@ fi
 UDEVD_FUNC(){
 if [ -z "$HOTPLUGD" ]; then  ##=- BUG? why did i -z "$HOTPLUGD" ??? :S
 [ -f /etc/rc.d/PUPSTATE ] || echo 'PUPMODE=2' > /etc/rc.d/PUPSTATE
+
+
+
+
+if [ -x /sbin/photplug ] ; then
+echo '/sbin/photplug' >/proc/sys/kernel/hotplug
+
+elif [ -x /sbin/udevd ]; then
 . /etc/rc.d/MODULESCONFIG
 ##rm -rf /tmp/*  ##+++2011_10_29 -2011_10_31
 BLACKLISTVARS=`echo "$SKIPLIST" | tr '\-' '_' | tr ' ' '\n' | sed -e 's/^/blacklist /' | grep -v ' $'`
@@ -537,7 +547,7 @@ echo -n '0' > /tmp/pup_event_alsa_cnt
 if [ -x /sbin/pup_event_backend_modprobe_protect ]; then
 nice -n -3 /sbin/pup_event_backend_modprobe_protect --daemon &
 fi
-if [ -x /sbin/udevd ]; then
+
  rm -rf /dev/.udev/*/*
  HOTPLUGD='udevd'
  UDEVVER=`udevd --version`
@@ -575,10 +585,10 @@ for ONEMODALIAS in $MODALIASES
 do
  #ONEPATH="`dirname $ONEMODALIAS`"
  ONEPATH=${ONEMODALIAS%/*}
- [ -e ${ONEPATH}/uevent ] || continue
+ [ -e "${ONEPATH}/uevent" ] || continue
  #if [ -e ${ONEPATH}/uevent ];then
   echo "$ONEMODALIAS" >> /tmp/modaliases.loaded
-  echo 'add' > ${ONEPATH}/uevent #generates an 'add' uevent.
+  echo 'add' > "${ONEPATH}/uevent" #generates an 'add' uevent.
   echo -n '.'
   MODULECNT=$((MODULECNT+1))
   sleep 0.2
@@ -864,7 +874,7 @@ CURR_GLIBC_FUNC
 [ -z "`lsmod | grep 'squashfs'`" ] && modprobe squashfs
 for oneDRV in $DRIVES; do  ##for 0
 SIMPLEDRIVENAME="${oneDRV##*/}"
-mkdir -p /mnt/$SIMPLEDRIVENAME
+mkdir $VERB -p /mnt/$SIMPLEDRIVENAME
 [ "$DebugVal" -ge "1" ] && echo -e "$Ora"'Mounting '"$Res"$oneDRV' on '"$Res"/mnt/$SIMPLEDRIVENAME
 busybox mount -o ro $oneDRV /mnt/$SIMPLEDRIVENAME
 [ $? = 0 ] || { rmdir /mnt/$SIMPLEDRIVENAME;continue; }  ##2013-12-07
@@ -882,7 +892,7 @@ for oneSFS in $SFS; do ##for 1
 [ "$DebugVal" -ge "1" ] && echo -e "$YEL"'Found '"\\033[0;35m"$oneSFS"$Res"
 bneSFS="${oneSFS##*/}"
 [ "$DebugVal" -ge "1" ] && echo -e "$Ora"'Mounting now '"$Res""$oneSFS /mnt/$bneSFS"
-mkdir -p /mnt/$bneSFS
+mkdir $VERB -p /mnt/$bneSFS
 Err=0
 mount-FULL -o loop $oneSFS /mnt/$bneSFS
 Err=$?
@@ -974,7 +984,7 @@ CHECK_FOR_ALT_PART_FUNC
 CURR_GLIBC_FUNC
 for oneDRV in $DRIVES; do ##for 0
 SIMPLEDRIVENAME="${oneDRV##*/}"
-mkdir -p /mnt/$SIMPLEDRIVENAME
+mkdir $VERB -p /mnt/$SIMPLEDRIVENAME
 [ "$DebugVal" -ge "1" ] && echo -e "$Ora"'Mounting '"$Res""$oneDRV""$Ora"' on '"$Res""/mnt/$SIMPLEDRIVENAME""$Res"
 busybox mount -o rw $oneDRV /mnt/$SIMPLEDRIVENAME
 [ $? = 0 ] || { rmdir /mnt/$SIMPLEDRIVENAME;continue; }  ##2013-12-07
@@ -1214,13 +1224,13 @@ MAKE_RAM9_FUNC(){
   sleep $((SLEEP*2))s
 }
 MAKE_RAM9_FUNC
-  mkdir -p /mnt/ram0
-  mkdir -p /mnt/ram9  ###KRG
+  mkdir $VERB -p /mnt/ram0
+  mkdir $VERB -p /mnt/ram9  ###KRG
   busybox mount -t ext2 /dev/ram0 /mnt/ram0
   busybox mount -t ext2 /dev/ram9 /mnt/ram9  ###KRG
   sleep $((SLEEP*2))s  ###KRG
-  mkdir -p /mnt/ram0/old_root
-  mkdir /mnt/ram0/bin
+  mkdir $VERB -p /mnt/ram0/old_root
+  mkdir $VERB /mnt/ram0/bin
 BUSYBOX_FUNC(){
   echo
   echo -n -e "$BLU""Checking if $REPO/bin/busybox is a link to 'MyBusybox' : ""$Res"
@@ -1230,7 +1240,7 @@ BUSYBOX_FUNC(){
   echo -e "$GRE"'YES'"$Res"
   echo -e "$Res"'Copying '"$RLF"' into RamDisk'"$Res"
   RLBB="${RLF##*/}"
-  cp -a "$REPO"/bin/"$RLBB" /mnt/ram0/bin/"$RLBB"
+  cp $VERB -a "$REPO"/bin/"$RLBB" /mnt/ram0/bin/"$RLBB"
   else
   echo -e "$Gre"'No'
   fi
@@ -1255,11 +1265,11 @@ BUSYBOX_FUNC
   NEWBIN=`echo "$RLF" | sed 's#/usr## ; s#/local##'`
   [ "$DebugVal" = "2" ] && echo -n -e "$Red"' Link '"$Res""${REPO}${BINDIR}/$ONEBIN ""$Red"', '"$Res"
   [ "$DebugVal" = "2" ] && echo -n -e "$Red"' LinkTarget '"$Res""${REPO}${RLF} ""$Red"', '"$Res"
-  [ -x /mnt/ram0/${NEWBIN} ] || cp -a ${REPO}${RLF} /mnt/ram0/${NEWBIN}
-  [ -x /mnt/ram0/bin/$ONEBIN ] || cp -a ${REPO}${BINDIR}/$ONEBIN /mnt/ram0/bin/$ONEBIN
+  [ -x /mnt/ram0/${NEWBIN} ] || cp $VERB -a ${REPO}${RLF} /mnt/ram0/${NEWBIN}
+  [ -x /mnt/ram0/bin/$ONEBIN ] || cp $VERB -a ${REPO}${BINDIR}/$ONEBIN /mnt/ram0/bin/$ONEBIN
   else
    if [ -x ${REPO}${BINDIR}/$ONEBIN ] && [ ! -x /mnt/ram0/bin/$ONEBIN ]; then  ###KRG for symlink busybox
-    cp -a ${REPO}${BINDIR}/$ONEBIN /mnt/ram0/bin/
+    cp $VERB -a ${REPO}${BINDIR}/$ONEBIN /mnt/ram0/bin/
     [ "$DebugVal" = "2" ] && echo -e -n "$ONEBIN ""$Red"', '"$Res"
    else
     if [ "$ONEBIN" != "busybox" -a "`busybox | grep $ONEBIN`" ]; then  ###KRG
@@ -1282,7 +1292,7 @@ BUSYBOX_FUNC
   [ "$DebugVal" -ge "1" ] && echo -e "$Res" && echo
   echo -e "$BLU""Populating /mnt/ram0/sbin ...""$Res"
   [ "$DebugVal" = "2" ] && echo -e -n "$Red"'/mnt/ram0/sbin/'"$Res"
-  mkdir /mnt/ram0/sbin
+  mkdir $VERB /mnt/ram0/sbin
   for ONEBIN in depmod dumpe2fs e2fsck elspci fdisk freeramdisk fsck.ext2 fsck.ext3 fsck.ext4 getty guess_fstype halt hdparm hotplug2stdout hotplug2stdout_notimeout hwclock ifconfig ifplugstatus insmod klogd ldconfig loadkmap losetup lsmod mount.ntfs-3g pivot_root probedisk probedisk2 probepart swapon
   do
   if [ -x $REPO/sbin/$ONEBIN ]; then
@@ -1299,11 +1309,11 @@ BUSYBOX_FUNC
    NEWBIN=`echo "$RLF" | sed 's#/usr## ; s#/local##'`
    [ "$DebugVal" = "2" ] && echo -n -e "$Red"' Link '"$Res""${REPO}${BINDIR}/$ONEBIN ""$Red"', '"$Res"
    [ "$DebugVal" = "2" ] && echo -n -e "$Red"' LinkTarget '"$Res""${REPO}${RLF} ""$Red"', '"$Res"
-   [ -x /mnt/ram0/sbin/$ONEBIN ] || cp -a ${REPO}${BINDIR}/"$ONEBIN" /mnt/ram0/sbin/"$ONEBIN"
-   [ -x /mnt/ram0/${NEWBIN} ] || cp -a ${REPO}${RLF} /mnt/ram0/${NEWBIN}
+   [ -x /mnt/ram0/sbin/$ONEBIN ] || cp $VERB -a ${REPO}${BINDIR}/"$ONEBIN" /mnt/ram0/sbin/"$ONEBIN"
+   [ -x /mnt/ram0/${NEWBIN} ] || cp $VERB -a ${REPO}${RLF} /mnt/ram0/${NEWBIN}
    else
    if [ -x ${REPO}${BINDIR}/$ONEBIN ]; then  ###KRG -x for -e
-    cp -a ${REPO}${BINDIR}/$ONEBIN /mnt/ram0/sbin/
+    cp $VERB -a ${REPO}${BINDIR}/$ONEBIN /mnt/ram0/sbin/
     [ "$DebugVal" = "2" ] && echo -e -n "$ONEBIN "
     [ "$DebugVal" = "2" ] && [ "$ONEBIN" != "swapon" ] && echo -e -n "$Red"', '"$Res"
    else
@@ -1321,7 +1331,7 @@ PRESERVE_CHROOT_FUNC(){
   echo "$CHROOT is no link but executable ,
 creating backup of $CHROOT.bac
 Please restore manually for now"
-  mv $CHROOT "$CHROOT.bac"
+  mv $VERB $CHROOT "$CHROOT.bac"
   fi
 }
 PRESERVE_CHROOT_FUNC
@@ -1337,13 +1347,13 @@ PRESERVE_CHROOT_FUNC
   [ "$DebugVal" = "2" ] && echo -n 'link reboot '
   [ "$DebugVal" -ge "1" ] && echo -e "$Res" && echo
   echo -e "$BLU""Populating /mnt/ram0/etc  ...""$Res"
-  mkdir /mnt/ram0/etc
+  mkdir $VERB /mnt/ram0/etc
   [ "$DebugVal" = "2" ] && echo -n -e "$Red"'/mnt/ram0/etc/'"$Res"
   for ONEFILE in codepage DISTRO_SPECS eventmanager fdprm floppy fontmap group gshadow host.conf hostname hosts hosts.allow hosts.deny inittab inputrc issue keymap localtime mailcap mime.types mke2fs.conf modprobe.conf modules.conf mtab networks nscd.conf nsswitch.conf passwd printcap protocols services shadow
   do
-   [ "$DebugVal" = "0" ] && cp -a "$REPO"/etc/$ONEFILE /mnt/ram0/etc/ 2>/dev/null
+   [ "$DebugVal" = "0" ] && cp $VERB -a "$REPO"/etc/$ONEFILE /mnt/ram0/etc/ 2>/dev/null
    [ "$DebugVal" = "2" ] && echo -e -n "$ONEFILE "
-   [ "$DebugVal" -ge "1" ] && cp -a "$REPO"/etc/$ONEFILE /mnt/ram0/etc/
+   [ "$DebugVal" -ge "1" ] && cp $VERB -a "$REPO"/etc/$ONEFILE /mnt/ram0/etc/
    [ "$DebugVal" = "2" ] && [ "$ONEFILE" != "shadow" ] && echo -e -n "$Red"', '"$Res"
   done
    [ "$DebugVal" = "2" ] && echo -e "$Res" && echo
@@ -1359,7 +1369,7 @@ umask 022
 export USER=root
 export LOGNAME=root
 export TERM=linux' > /mnt/ram0/etc/profile
-  mkdir /mnt/ram0/etc/rc.d
+  mkdir $VERB /mnt/ram0/etc/rc.d
   echo '#!/bin/sh
 PDEV1=`cat /etc/fsckme.err | cut -f 1 -d ","`  ###KRG
 DEV1FS=`cat /etc/fsckme.err | cut -f 2 -d ","`  ###KRG
@@ -1519,37 +1529,37 @@ fi
   else
   LOCALTDIR="`dirname $LOCALTIME | sed 's#^/## ; s#//#/#g'`"
   fi
-  mkdir -p /mnt/ram0/$LOCALTDIR
-  cp -a $LOCALTIME /mnt/ram0/$LOCALTDIR/
-  mkdir -p /mnt/ram0/usr/share
-  cp -a "$REPO"/usr/share/terminfo /mnt/ram0/usr/share/
+  mkdir $VERB -p /mnt/ram0/$LOCALTDIR
+  cp $VERB -a $LOCALTIME /mnt/ram0/$LOCALTDIR/
+  mkdir $VERB -p /mnt/ram0/usr/share
+  cp $VERB -a "$REPO"/usr/share/terminfo /mnt/ram0/usr/share/
   echo -e "$BLU""Populating /mnt/ram0/dev  ...""$Res"
-  cp -a "$REPO"/dev /mnt/ram0/
+  cp $VERB -a "$REPO"/dev /mnt/ram0/
   UPDATINGDEV_FUNC "/mnt/ram0"
   [ "$DebugVal" = "2" ] && CONTINUE_FUNC
   echo -e "$BLU""Populating /mnt/ram9/lib  ...""$Res"
-  mkdir /mnt/ram9/lib
+  mkdir $VERB /mnt/ram9/lib
   for i in $LIBF; do  ###KRG to sort unneeded libs out , see further up ###KRG
   [ "$DebugVal" -ge "1" ] && echo -n -e "$Res""${i##*/}"
   [ "$DebugVal" -ge "1" ] && [ -z "`echo $i | grep 'libz\.so\..*\..*\..*'`" ] &&  echo -n -e "$Ora"', '"$Res"
-  cp -a $i /mnt/ram9/lib/
+  cp $VERB -a $i /mnt/ram9/lib/
   done
   if [ -f "$REPO"/lib/e2initrd_helper ]; then
-  [ "$DebugVal" = "0" ] && cp -a "$REPO"/lib/e2initrd_helper /mnt/ram9/lib/ 2>/dev/null #dunno what this is.  ###KRG me not either
+  [ "$DebugVal" = "0" ] && cp $VERB -a "$REPO"/lib/e2initrd_helper /mnt/ram9/lib/ 2>/dev/null #dunno what this is.  ###KRG me not either
   if [ "$DebugVal" -ge "1" ]; then
   echo -e "$Ora"' Copying also '"$Res"'/lib/e2initrd_helper'
-  cp -a "$REPO"/lib/e2initrd_helper /mnt/ram9/lib/
+  cp $VERB -a "$REPO"/lib/e2initrd_helper /mnt/ram9/lib/
   echo
   fi
   fi
   echo -e "$Res"
   busybox ln -s /mnt/ram9/lib /mnt/ram0/lib
-  mkdir /mnt/ram0/mnt
-  mkdir /mnt/ram0/mnt/ram9
-  mkdir /mnt/ram0/root
-  mkdir /mnt/ram0/tmp
-  mkdir -p /mnt/ram0/var/run
-  mkdir /mnt/ram0/proc
+  mkdir $VERB /mnt/ram0/mnt
+  mkdir $VERB /mnt/ram0/mnt/ram9
+  mkdir $VERB /mnt/ram0/root
+  mkdir $VERB /mnt/ram0/tmp
+  mkdir $VERB -p /mnt/ram0/var/run
+  mkdir $VERB /mnt/ram0/proc
   sleep $((SLEEP*3))s
   sync
   echo -e "\\033[0;35m"'Performing a pivot_root to the ramdisk...'
@@ -1564,9 +1574,9 @@ fi
   [ "$DebugVal" = "2" ] && sleep $((SLEEP*2))s  ###DBG
   [ "$DebugVal" = "2" ] && echo  -e "$Red"'ls ./sbin :'"$Res" && ls --color=auto ./sbin && echo  ###DBG
   [ "$DebugVal" = "2" ] && sleep $((SLEEP*2))s  ###DBG
-  [ ! -d ./mnt/ram9 ] && mkdir -p ./mnt/ram9
+  [ ! -d ./mnt/ram9 ] && mkdir $VERB -p ./mnt/ram9
   busybox mount -o move /mnt/ram9 ./mnt/ram9
-  [ ! -d ./sys ] && mkdir ./sys
+  [ ! -d ./sys ] && mkdir $VERB ./sys
   busybox mount -o move /sys ./sys
   busybox mount -o move /proc ./proc
   [ "$DebugVal" = "2" ] && CONTINUE_FUNC
