/sbin/init: Reworked several functions. Especially _find_install_frugal() and _find_install_full() to get rid of the many levels nested if blocks.

diff --git a/woof-code/rootfs-skeleton/sbin/init b/woof-code/rootfs-skeleton/sbin/init
--- a/woof-code/rootfs-skeleton/sbin/init
+++ b/woof-code/rootfs-skeleton/sbin/init
@@ -448,8 +448,14 @@ _check_puppy_kernel_parameter fsck  ##+++2012-02-02
 [ "$FSCK" = 'yes' ] || _get_errflg  ###KRG
 
 _leave_to_simple_console(){
-[ -n "$ERRMSG" ] && echo -e "\\033[0;31m""$ERRMSG""\\033[0;39m"
-echo "Now ramdiskshell without busybox init on top"
+#[ -n "$ERRMSG" ] && echo -e "\\033[0;31m""$ERRMSG""\\033[0;39m"
+[ "$*" ] && echo -e '\033[0;31m'"$*"'\033[0;39m'
+cd /
+sleep 2
+case `rdev` in *ram*)
+echo "Now ramdiskshell without busybox init on top.";;
+*) "Now simple init=/bin/sh kernel parameter console.";;
+esac
 echo -e "\\033[0;32m""Type 'busybox reboot -f' or press Cnt+Alt+Del to reboot""\\033[0;39m"
 exec chroot . sh
 }
@@ -690,28 +696,8 @@ sleep 1s
 #_load_kernel_drivers
 
 _update_partition_device_nodes(){
-__load_usb_drivers__(){
-if [ -z "`lsmod | grep 'usb'`" ] ; then
-echo -e "\\033[1;34m""Loading usb drivers ...""\\033[0;39m"
-DRIVERS=`modprobe -l | grep -E '[eoux]hci[-_]hcd|usbcore|usb[-_]storage' | sort -k4,8 -t '/'`
-for i in $DRIVERS ; do
-DRIVER=`basename "$i" | sed 's#\.ko.*$##'`
-DRVpattern=`echo "$DRIVER" | tr '-' '_'`
-echo -e -n "\\033[1;33m""$DRIVER ""\\033[1;34m"'.. '"\\033[0;39m"
-if [ "$DRVpattern" != "usb_storage" ] ; then
-[ -z "`lsmod | grep "$DRVpattern"`" ] && modprobe $DRIVER
-else
-[ -z "`lsmod | grep "$DRVpattern"`" ] && modprobe $DRIVER delay_use:1
-fi
-done
-echo -e "\\033[1;34m"'Waiting 15 sec. for kernel to register usb devices ...'"\\033[0;39m"
-sleep 15s
-echo
-fi
-}
-
 _start_uevent_program
-_load_kernel_drivers
+_load_kernel_drivers  # for usb drivers
 
 echo -n "Updating Device nodes " >/dev/console
 STATUS=0
@@ -926,9 +912,9 @@ _do_fsck(){
 [ "$DebugVal" -ge "2" ] && echo -e "\\033[0;33m"'_do_fsck called with param $1='"\\033[0;39m""$1""\\033[0;33m"' $2='"\\033[0;39m""$2"
 echo -e "\\033[0;39m"
 
-[ "$1" != "/dev/$PDEV1" ] && [ -n "`mount | grep "^$1"`" ] && busybox umount $VERB $VERB -lr "$1"
+[ "$1" != "/dev/$PDEV1" ] && [ -n "`mount | grep -w "^$1"`" ] && busybox umount $VERB $VERB -lr "$1"
 sleep 1s
-[ -n "`busybox mount | grep "^$1" | cut -f 6 -d ' ' | grep 'rw'`" ] && busybox mount $VERB $VERB -o remount,ro $1
+[ -n "`busybox mount | grep -w "^$1" | cut -f 6 -d ' ' | grep 'rw'`" ] && busybox mount $VERB $VERB -o remount,ro $1
 sleep 2s
 Err=''
 RETFSCK=''
@@ -1019,13 +1005,13 @@ DRIVES=`echo "$DRIVES" | grep -v "$PDEV1" | sed 's#^#/dev/#g' | tr '\n' ' '`
 fi
 
 if [ -z "$DRIVES" ] ; then
-ERRMSG="Could not find any useable drives in /proc/partitions"
-_leave_to_simple_console
+#ERRMSG="Could not find any usable drives in /proc/partitions"
+_leave_to_simple_console "Could not find any usable drives in /proc/partitions"
 fi
 }
 
 _check_alternate_repo(){
-_check_glibc_version(){
+_assign_glibc_version(){
 CURRGLIBC=`basename $(find /lib -maxdepth 1 -name "libc-*.so")`
 
 CURRCLMAJ=`echo "$CURRGLIBC" | cut -f 2 -d ' ' | cut -f 2 -d '.'`
@@ -1036,13 +1022,25 @@ CURRCLMin=`echo "$CURRGLIBC" | cut -f 2 -d ' ' | cut -f 3 -d '.'`
 if [ -z "$CLEAN" ] ; then  #0
 if [ -n "$Err" ] && [ "$Err" -ne 0 ] ; then #1
 
+_umount_with_msg(){
+MT="$1"
+shift
+MSG="$*"
+test "$MT" || return 2
+grep -w "$MT" /proc/mounts || return 1
+MSG=`gettext "$MSG"`
+echo "$MSG"
+[ "$DebugVal" -ge "1" ] && echo -e '\033[0;33m'"Unmounting again "'\033[0;39m'"$MT"
+busybox umount "$MT"; RV=$?
+test $RV = 0 && [ -d "$MT" ] && { sleep 1; rmdir $VERB "$MT"; }
+return $RV
+}
+
 _find_install_frugal(){
-##busybox mount $VERB $VERB -o remount,ro /dev/root /
 #_remount_root ro
 _get_partitions  #TODO simplfy ?
-##busybox mount $VERB $VERB -o remount,rw /dev/root /
 #_remount_root rw
-_check_glibc_version
+_assign_glibc_version
 modprobe squashfs
 
 for oneDRV in $DRIVES ; do  ##for 0
@@ -1056,19 +1054,15 @@ mkdir $VERB -p /mnt/$SIMPLEDRIVENAME
 
 busybox mount $VERB $VERB -o ro $oneDRV /mnt/$SIMPLEDRIVENAME
 [ $? = 0 ] || { rmdir $VERB /mnt/$SIMPLEDRIVENAME;continue; }  ##+++2013-12-07
-SFS=`find /mnt/$SIMPLEDRIVENAME -maxdepth 3 -type f -name "*.sfs" | grep -i -E 'luma|luci|lupu|pup|pu' | grep -v -E 'devx|\+mnt\+'`
+SFS=`find /mnt/$SIMPLEDRIVENAME -maxdepth 3 -type f -name "*.sfs" | grep -iE 'luma|luci|lupu|pup|pu' | grep -vE 'devx|[a-z]drv|[a-z]drive|[a-z]p[0-9]+|\+mnt\+'`
 
 ###check found sfs part
 if [ -z "$SFS" ] ; then  ##if 99
-echo  -e "\\033[0;33m"'No puppy.sfs found on '"\\033[0;39m"$oneDRV
-sleep 1s
-[ "$DebugVal" -ge "1" ] && echo -e "\\033[0;33m"'Unmounting again '"\\033[0;39m"$oneDRV
-busybox umount $VERB $VERB -lr $oneDRV
-sleep 1s
-rmdir $VERB /mnt/$SIMPLEDRIVENAME
+#echo  -e "\\033[0;33m"'No puppy.sfs found on '"\\033[0;39m"$oneDRV
+_umount_with_msg /mnt/$SIMPLEDRIVENAME "No puppy.sfs found on '$oneDRV'"
 continue  ##for 0
+fi #if 99
 
-else  ##if 99
 for oneSFS in $SFS ; do ##for 1
 [ "$oneSFS" ] || continue
 [ "${oneSFS//[[:blank:]]/}" ] || continue
@@ -1095,46 +1089,35 @@ if [ "$Err" -eq 0 ] ; then ##100
  [ -z "$REPOCLMin" ] && REPOCLMin='0'  ##+++2011-11-25
  fi
  if [ -z "$REPOGLIBC" ] ; then ##101
- echo -e "\\033[0;31m"'No libc found in '"\\033[0;39m""$bneSFS"
- busybox umount $VERB $VERB -ldr /mnt/$bneSFS
- sleep 1s
- rmdir $VERB /mnt/$bneSFS
+ #echo -e "\\033[0;31m"'No libc found in '"\\033[0;39m""$bneSFS"
+ _umount_with_msg /mnt/$bneSFS "No libc found in '$bneSFS'"
  FOUND=''
  continue
- else ##101
-  if [ "$REPOCLMAJ" -gt "$CURRCLMAJ" ] ; then #102
-  echo -e "\\033[0;31m""Major of libc in $bneSFS = '$REPOCLMAJ' and larger than actual '$CURRCLMAJ'""\\033[0;39m"
-  busybox umount $VERB $VERB -dlr /mnt/$bneSFS
-  sleep 1s
-  rmdir $VERB /mnt/$bneSFS
+ fi ##101
+ if [ "$REPOCLMAJ" -gt "$CURRCLMAJ" ] ; then #102
+  #echo -e "\\033[0;31m""Major of libc in $bneSFS = '$REPOCLMAJ' and larger than actual '$CURRCLMAJ'""\\033[0;39m"
+  _umount_with_msg /mnt/$bneSFS "Major of libc in $bneSFS = '$REPOCLMAJ' and larger than actual '$CURRCLMAJ'"
   FOUND=''
   continue
-  elif [ "$REPOCLMAJ" -eq "$CURRCLMAJ" ] && [ "$REPOCLMin" -gt "$CURRCLMin" ] ; then #102
-  echo -e "\\033[0;31m""Minor of libc in $bneSFS = '$REPOCLMin' and larger than actual '$CURRCLMin'""\\033[0;39m"
-  busybox umount $VERB $VERB -dlr /mnt/$bneSFS
-  sleep 1s
-  rmdir $VERB /mnt/$bneSFS
+ elif [ "$REPOCLMAJ" -eq "$CURRCLMAJ" ] && [ "$REPOCLMin" -gt "$CURRCLMin" ] ; then #102
+  #echo -e "\\033[0;31m""Minor of libc in $bneSFS = '$REPOCLMin' and larger than actual '$CURRCLMin'""\\033[0;39m"
+  _umount_with_msg /mnt/$bneSFS "Minor of libc in $bneSFS = '$REPOCLMin' and larger than actual '$CURRCLMin'"
   FOUND=''
   continue
-  else #102
+ else #102
   echo -e "\\033[0;32m""Found '$REPOGLIBC' and should match '$CURRGLIBC'""\\033[0;39m"
   FOUND='1'
   break ##for 1
  fi #102
-fi #101
 else #100
 Err=99999
-echo -e "\\033[0;31m""Mounting $oneSFS failed""\\033[0;39m"
-busybox umount $VERB $VERB -dlr /mnt/$bneSFS
-sleep 1s
-rmdir $VERB /mnt/$bneSFS
+#echo -e "\\033[0;31m""Mounting $oneSFS failed""\\033[0;39m"
+_umount_with_msg /mnt/$bneSFS "Mounting '$oneSFS' failed."
 FOUND=''
 continue
 fi #100
 unset bneSFS
 done  ##for 1
-
-fi  ##if 99
 ###end check sfs part
 [ -n "$FOUND" ] && [ "$Err" -eq 0 ] && break
 unset oneDRV
@@ -1146,7 +1129,7 @@ echo -e "\\033[0;39m"
 [ "$oneSFS" ] || oneSFS=NOTAVAIL
 [ "$oneDRV" ] || oneDRV=NOTAVAIL
 MOUNTLOOP=`busybox mount | grep -E "$oneDRV|$bneSFS" | cut -f 1 -d ' ' | tr ' ' '|'`
-MOUNT=`busybox mount | /bin/grep -v -E "$MOUNTLOOP|$devROOT" | grep '^/dev/' | grep -v -E  'initrd|none|*tmpfs|root|unionfs|aufs' | cut -f 1 -d ' '`
+MOUNT=`busybox mount | /bin/grep -vE "$MOUNTLOOP|$devROOT" | grep '^/dev/' | grep -vE  'initrd|none|*tmpfs|root|unionfs|aufs|pts|shm|usbfs' | cut -f 1 -d ' '`
 [ "$DebugVal" -ge "2" ] && echo -e "\\033[0;31m""$MOUNTLOOP : $MOUNT :""\\033[0;39m"
 [ "$DebugVal" -ge "1" ] && busybox mount
 
@@ -1159,6 +1142,7 @@ done
 [ "$DebugVal" -ge "1" ] && [ -n "$MOUNT" ] && busybox mount && echo -e "\\033[0;39m"
 sleep $((SLEEP*3))s
 
+#DEBUG
 busybox mount
 echo "'/mnt/'$bneSFS'"
 busybox mount | grep "/mnt/$bneSFS"
@@ -1185,7 +1169,7 @@ _find_install_frugal
 _find_install_full(){
 ###partitions full installs
 _get_partitions
-_check_glibc_version
+_assign_glibc_version
 
 for oneDRV in $DRIVES ; do ##for 0
 [ "$oneDRV" ] || continue
@@ -1199,87 +1183,69 @@ busybox mount $VERB $VERB -o rw $oneDRV /mnt/$SIMPLEDRIVENAME
 [ $? = 0 ] || { rmdir $VERB /mnt/$SIMPLEDRIVENAME;continue; }
 
 DS=
-[ -d /mnt/$SIMPLEDRIVENAME/etc ] && DS=`find /mnt/$SIMPLEDRIVENAME/etc -maxdepth 2 -name "DISTRO_SPECS"`
-sleep 2s
-
-if [ -n "$DS" ] ; then  ##3
-if [ -f "$DS" ] ; then  ##4
-. $DS
-if [ -n "$DISTRO_NAME" ] && [ -n "$DISTRO_VERSION" ] ; then  ##4.1
+[ -d /mnt/$SIMPLEDRIVENAME/etc ] || { _umount_with_msg /mnt/$SIMPLEDRIVENAME "No /etc folder."; continue; }
+DS=`find /mnt/$SIMPLEDRIVENAME/etc -maxdepth 2 -type f -name "DISTRO_SPECS"`
+   [ "$DS" ] || { _umount_with_msg /mnt/$SIMPLEDRIVENAME "No Puppy Linux DISTRO_SPECS file."; continue; }
+[ -f "$DS" ] || { _umount_with_msg /mnt/$SIMPLEDRIVENAME "DISTRO_SPECS is not a file."; continue; }
+[ -s "$DS" ] || { _umount_with_msg /mnt/$SIMPLEDRIVENAME "DISTRO_SPECS is empty file."; continue; }
+. "$DS"
+[ -n "$DISTRO_NAME" ] && [ -n "$DISTRO_VERSION" ] || { _umount_with_msg /mnt/$SIMPLEDRIVENAME "DISTRO_NAME DISTRO_VERSION not set in DISTRO_SPECS"; continue; }
 echo -e "\\033[1;32m""Found $DISTRO_NAME $DISTRO_VERSION"
+
 #REPOGLIBC=`basename $(find /mnt/$SIMPLEDRIVENAME/lib -maxdepth 1 -name "libc-*.so")`
 REPOGLIBC=$(find /mnt/$SIMPLEDRIVENAME/lib -maxdepth 1 -name "libc-*.so")
-if [ "$REPOGLIBC" ] ; then
+
+if [ -z "$REPOGLIBC" ] ; then #4.1.1
+#echo -e "\\033[0;31m"'No GLIBC found on '"\\033[0;39m"$oneDRV
+_umount_with_msg /mnt/$SIMPLEDRIVENAME "No GLIBC found on 'oneDRV'"
+continue
+fi  ##4.1.1
+
 REPOGLIBC=`basename "$REPOGLIBC"`
 REPOCLMAJ=`echo "$REPOGLIBC" | cut -f 2 -d '-' | cut -f 2 -d '.'`
 REPOCLMin=`echo "$REPOGLIBC" | cut -f 2 -d '-' | cut -f 3 -d '.'`
 [ "$REPOCLMin" ] || REPOCLMin=0
-fi
-if [ -n "$REPOGLIBC" ] ; then #4.1.1
-if [ "$REPOCLMAJ" -gt "$CURRCLMAJ" ] ; then ##4.2
-echo -e "\\033[0;31m""LIBC major = '$REPOCLMAJ' larger than '$CURRCLMAJ'""\\033[0;39m"
-busybox umount $VERB $VERB -lr $oneDRV
-sleep 1s
-rmdir $VERB /mnt/$SIMPLEDRIVENAME
-continue
-elif [ "$REPOCLMAJ" -eq "$CURRCLMAJ" ] && [ "$REPOCLMin" -gt "$CURRCLMin" ] ; then ##4.2
-echo -e "\\033[0;31m""LIBC minor = '$REPOCLMin' larger than '$CURRCLMin'""\\033[0;39m"
-busybox umount $VERB $VERB -lr $oneDRV
-sleep 1s
-rmdir $VERB /mnt/$SIMPLEDRIVENAME
-continue
-else ##4.2
-echo -e "\\033[0;32m""Found '$REPOGLIBC' and should match '$CURRGLIBC'""\\033[0;39m"
-echo -e "\\033[1;34m""Fscking $oneDRV just in case ....""\\033[0;39m"
-busybox umount $VERB $VERB -lr $oneDRV
-sleep 2s
-fi ##4.2
 
-_do_fsck "$oneDRV" "other_full_installs"
-if [ -n "$CLEAN" ] || [ -z "$Err" ] || [ "$Err" -eq "0" ] ; then  ##5
-echo -e "\\033[0;32m"'OK ,'"\\033[1;32m"" using REPO /mnt/$SIMPLEDRIVENAME""\\033[0;39m"
-echo
-busybox mount $VERB $VERB -o rw $oneDRV /mnt/$SIMPLEDRIVENAME
-[ $? = 0 ] || { rmdir $VERB /mnt/$SIMPLEDRIVENAME;continue; }
-sleep 1s
-REPO="/mnt/$SIMPLEDRIVENAME"
-break
-else  ##5
-echo
-echo -e "\\033[1;31m""No ,""\\033[0;31m"" $oneDRV seems to be not clean , too""\\033[0;39m"
-echo "Trying next if possible ...."
-echo
-REPO=''
-[ -n "`busybox mount | grep -Fw "$oneDRV"`" ] && busybox umount $VERB $VERB -lr $oneDRV
-sleep 1s
-rmdir $VERB /mnt/$SIMPLEDRIVENAME
-fi  ##5
-else
-echo -e "\\033[0;31m"'No GLIBC found on '"\\033[0;39m"$oneDRV
-busybox umount $VERB $VERB -lr $oneDRV
-sleep 1s
-rmdir $VERB /mnt/$SIMPLEDRIVENAME
-continue
-fi  ##4.1.1
-else ##4.1
-echo -e "\\033[1;31m"'No , $DISTRO_NAME or $DISTRO_VERSION not available'"\\033[0;39m"
-echo 'Trying next if possible ....'
-busybox umount $VERB $VERB -lr $oneDRV
-sleep 1s
-rmdir $VERB /mnt/$SIMPLEDRIVENAME
-fi  ##4.1
-fi  ##4
-else #3
-echo -e "\\033[0;33m"'Apparently no Puppy Linux full installation on '"\\033[0;39m""$oneDRV"
-busybox umount $VERB $VERB -lr $oneDRV
-sleep 1s
-rmdir $VERB /mnt/$SIMPLEDRIVENAME
-fi  ##3
+ if [ "$REPOCLMAJ" -gt "$CURRCLMAJ" ] ; then ##4.2
+  #echo -e "\\033[0;31m""LIBC major = '$REPOCLMAJ' larger than '$CURRCLMAJ'""\\033[0;39m"
+  _umount_with_msg /mnt/$SIMPLEDRIVENAME "LIBC major = '$REPOCLMAJ' larger than '$CURRCLMAJ'"
+  continue
+ elif [ "$REPOCLMAJ" -eq "$CURRCLMAJ" ] && [ "$REPOCLMin" -gt "$CURRCLMin" ] ; then ##4.2
+  #echo -e "\\033[0;31m""LIBC minor = '$REPOCLMin' larger than '$CURRCLMin'""\\033[0;39m"
+  _umount_with_msg /mnt/$SIMPLEDRIVENAME "LIBC minor = '$REPOCLMin' larger than '$CURRCLMin'"
+  continue
+ else ##4.2
+  echo -e "\\033[0;32m""Found '$REPOGLIBC' and should match '$CURRGLIBC'""\\033[0;39m"
+  echo -e "\\033[1;34m""Fscking $oneDRV just in case ....""\\033[0;39m"
+  busybox umount $VERB $VERB -lr $oneDRV
+  sleep 2s
+ fi ##4.2
+
+ _do_fsck "$oneDRV" "other_full_installs"
+	if [ -n "$CLEAN" ] || [ -z "$Err" ] || [ "$Err" -eq "0" ] ; then  ##5
+	echo -e "\\033[0;32m"'OK ,'"\\033[1;32m"" using REPO /mnt/$SIMPLEDRIVENAME""\\033[0;39m"
+	echo
+	busybox mount ${VERB:+'-vv'} -o rw $oneDRV /mnt/$SIMPLEDRIVENAME
+	[ $? = 0 ] || { rmdir $VERB /mnt/$SIMPLEDRIVENAME;continue; }
+	sleep 1s
+	REPO="/mnt/$SIMPLEDRIVENAME"
+	break
+	else  ##5
+	echo
+	echo -e "\\033[1;31m""No ,""\\033[0;31m"" $oneDRV seems to be not clean , too""\\033[0;39m"
+	echo "Trying next if possible ...."
+	echo
+	REPO=''
+	[ -n "`busybox mount | grep -Fw "$oneDRV"`" ] && busybox umount $VERB $VERB -lr $oneDRV
+	sleep 1s
+	rmdir $VERB /mnt/$SIMPLEDRIVENAME
+	fi  ##5
+
 done  ##for 0
 }
 [ -z "$REPO" ] && _find_install_full
 
-_found_no_repo(){
+_maybe_found_repo(){
 if [ -z "$REPO" ] ; then  #6
 echo
 echo -e "\\033[1;31m""No alternative useable repositories found .""\\033[0;39m"
@@ -1294,19 +1260,20 @@ read -t $TimeOut K
 echo
 Key=`echo "$K" | tr '[A-Z]' '[a-z]'`
 if [ "$Key" = "c" -o "$Key" = "k" ] ; then #7
-echo 'dropping to console now , partition still mounted !'
-cd /
-sleep 2
-exec chroot . sh
+#echo 'dropping to console now , partition still mounted !'
+#cd /
+#sleep 2
+#exec chroot . sh
+_leave_to_simple_console 'dropping to console now , partition still mounted !'
 
 elif [ "$Key" = "r" ] ; then  #7
 echo "Please do an 'e2fsck $devROOT' "
 echo "via console/terminal using a LiveCd ."
 echo "You may need to boot it with 'puppy pfix=ram' ."
 echo "Remember , the timeout is 5 sec to press 'F2' ."
-echo "Rebooting now in 25 seconds"
+echo "Rebooting now in approx. 25 seconds"
 sleep 22s
-[ "$DebugVal" = "0" ] && busybox umount $VERB $VERB -a -r 2>/dev/null
+[ "$DebugVal" = "0" ]   && busybox umount $VERB $VERB -a -r 2>/dev/null
 [ "$DebugVal" -ge "1" ] && busybox umount $VERB $VERB -a -r
 [ "$DebugVal" -ge "1" ] && sleep 10s
 sleep 2s
@@ -1318,7 +1285,7 @@ REPO=''
 fi  ##7
 fi  ##6
 }
-_found_no_repo
+_maybe_found_repo
 
 fi  ##1
 fi  #0
@@ -1337,7 +1304,7 @@ _check_partitions(){
 ROOTDRIVE=`basename $(busybox rdev | cut -f 1 -d ' ')`  ### | cut -f 1 -d ' ' | sed 's#/dev/##'`
 ROOTBLOCKDRIVE=${ROOTDRIVE:0:3}
 [ "$DebugVal" -ge "1" ] && echo -e "\\033[0;33m"'rootdrive='"\\033[0;39m""$ROOTDRIVE" && echo  ###DBG
-FS=`mount | grep -Fw '/' | grep '/dev' | tr -s ' ' | cut -f 5 -d ' '`
+FS=`mount | grep -Fw '/' | grep '^/dev/' | tr -s ' ' | cut -f 5 -d ' '`
 PDEV1="$ROOTDRIVE"
 DEV1FS="$FS"
 [ "$DebugVal" -eq "2" ] && echo -e "\\033[0;33m""$ROOTDRIVE $ROOTBLOCKDRIVE $FS "','" $PDEV1 $DEV1FS"
@@ -1389,13 +1356,13 @@ SPACElib=$((SPACElib + SiZElib))
 [ "$DebugVal" = "2" ] && echo -n -e "\\033[0;39m""$i"'='"\\033[0;31m""$SiZElib "  ###DBG
 [ "$DebugVal" = "1" ] && [ "$SiZElib" -ne "0" ] && echo -n -e "\\033[0;39m""$i"'='"\\033[0;33m""$SiZElib "
 done
-[ "$DebugVal" = "2" ] && echo && echo 'total /lib='"$SPACElib"  ###DBG
+[ "$DebugVal" = "2" ]   && echo && echo 'total /lib='"$SPACElib"  ###DBG
 [ "$DebugVal" -ge "1" ] && echo && echo -e "\\033[0;39m"
 }
 function_size_lib
 echo -e "\\033[1;34m"'Checking for available RAM ...'
 echo -e "\\033[0;39m"
-RAM=`free | grep -i 'mem' | sed 's#^[[:blank:]]*##' | tr -s ' ' | cut -f 2 -d ' '`
+    RAM=`free | grep -i 'mem' | sed 's#^[[:blank:]]*##' | tr -s ' ' | cut -f 2 -d ' '`
 FREERAM=`free | grep -i 'mem' | sed 's#^[[:blank:]]*##' | tr -s ' ' | cut -f 4 -d ' '`
 RAMLIMITdevRAM2=$((MAXSIZEdevRAM1 * 2))
 echo '                  free counted total RAM:'"$RAM"  ###DBG
