/sbin/init : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/sbin/init b/woof-code/rootfs-skeleton/sbin/init
--- a/woof-code/rootfs-skeleton/sbin/init
+++ b/woof-code/rootfs-skeleton/sbin/init
@@ -104,11 +104,13 @@ alias modprobe='/sbin/modprobe -b'  ##+++2012-01-30  ##+2013-07-13 PATH/
 test -f /etc/rc.d/f4puppy5 && source /etc/rc.d/f4puppy5
 test -f /etc/rc.d/PUPSTATE && source /etc/rc.d/PUPSTATE || PUPMODE=2
 
+TTY=`tty`
+test "$TTY" = 'not a tty' && TTY=/dev/console
 status_func() {
  if [ $1 -eq 0 ]; then
-  /bin/echo -e "\\033[72G\\033[1;32mdone\\033[0;39m" >/dev/console #green [done] msg.
+  /bin/echo -e "\\033[72G\\033[1;32mdone\\033[0;39m" >$TTY #green [done] msg.
  else
-  /bin/echo -e "\\033[70G\\033[1;31mfailed\\033[0;39m" >/dev/console #red [failed].
+  /bin/echo -e "\\033[70G\\033[1;31mfailed\\033[0;39m" >$TTY #red [failed].
   STATUS=0
  fi
  return $1 #return with same status as entry param.
@@ -153,7 +155,7 @@ grep -q ' /dev ' /proc/mounts || {
   test -e /dev/stderr || ln -snf fd/2 /dev/stderr
 
   test "`which mdev`" && mdev -s || {
-   _devFILES_=`find /sys -type f -name uevent`
+   _devFILES_=`find /sys -type f -name uevent -perm 644`
   oldIFS="$IFS"
   IFS=$'\n'
   for oneFILE in $_devFILES_
@@ -164,7 +166,8 @@ grep -q ' /dev ' /proc/mounts || {
    #MAJOR=13
    #MINOR=65
    #DEVNAME=input/event1
-  test -e /dev/$DEVNAME && continue
+  test "$MAJOR" -a "$MINOR" || continue
+  test "$DEVNAME" && { test -e /dev/$DEVNAME && continue; } || { DEVNAME=${oneFILE%/uevent*}; DEVNAME=${DEVNAME##*/}; test -e /dev/$DEVNAME && continue; }
   test "$DEVTYPE" && {
       mknod /dev/$DEVNAME b $MAJOR $MINOR; } || {
       mknod /dev/$DEVNAME c $MAJOR $MINOR; }
