/sbin/photplug: Add _message function from f4puppy5 . Add missing case move) online) offline) as stubs . Seems the kernel falls back to 'change' , if anything else written to an uevent file. Use $Q and $VERB for modprobe and mkdir .

diff --git a/woof-code/rootfs-skeleton/sbin/photplug b/woof-code/rootfs-skeleton/sbin/photplug
--- a/woof-code/rootfs-skeleton/sbin/photplug
+++ b/woof-code/rootfs-skeleton/sbin/photplug
@@ -27,26 +27,71 @@ _trap
  }
 }
 
-exec 1>>/tmp/photplug.log 2>&1
+Q=-q
+VERB=-v
+EMERGENCY=1
+ALERT=1
+CRIT=1
+ERROR=1
+WARN=1
+NOTICE=1
+INFO=1
+DEBUG=1
 
-echo
-env
+exec 1>>/tmp/photplug.log 2>&1
+[ "$DEBUG" ] && echo
+echo "$0:$*:$ACTION"
+[ "$DEBUG" ] && env
+
+_emerg(){
+test "$EMERGENCY" || return 1
+echo -e "$0:EMERGENGY:$*"   >&2
+}
+_alert(){
+test "$ALERT" || return 1
+echo -e "$0:ALERT:$*"  >&2
+}
+_crit(){
+test "$CRIT" || return 1
+echo -e "$0:CRITICAL:$*" >&2
+}
+_err(){
+test "$ERROR" || return 1
+echo -e "$0:ERROR:$*"  >&2
+}
+_warn(){
+test "$WARN" || return 1
+echo -e "$0:WARNING:$*"  >&2
+}
+_notice(){
+test "$NOTICE" || return 1
+echo -e "$0:NOTICE:$*"   >&2
+}
+_info(){
+test "$INFO" || return 1
+echo -e "$0:INFO:$*"  >&2
+}
+ _debug(){
+test "$DEBUG" || return 1
+echo "$0:DEBUG:$*"  >&2
+}
+
 
 case $ACTION in
 add)
 [ "$MODALIAS" -o "$DRIVER" ] && {
-        echo "'$MODALIAS' '$DRIVER'"
-        [ "$DRIVER" ] && modprobe -b -v "$DRIVER" || {
+        _info "'$MODALIAS' '$DRIVER'"
+        [ "$DRIVER" ] && modprobe -b $Q $VERB "$DRIVER" || {
         LIST=`modprobe -b -D "$MODALIAS" | grep -vE '^install|^blacklist|^options' | sed 's%.*\(/.*\)\.k.*%\1%'`
         for m in $LIST ; do
-        modprobe -b -v "${m##*/}"
+        modprobe -b $Q $VERB "${m##*/}"
         done
     }
          exit 0
 }
 
 [ "$MAJOR" -a "$MINOR" -a "$SUBSYSTEM" ] && { [ "$DEVNAME" -o "$DEVPATH" ] && {
-echo $MAJOR $MINOR $SUBSYSTEM $DEVNAME $DEVPATH
+_debug $MAJOR $MINOR $SUBSYSTEM $DEVNAME $DEVPATH
 
 [ "$DEVNAME" ] || {
     case $SUBSYSTEM in
@@ -60,16 +105,16 @@ echo $MAJOR $MINOR $SUBSYSTEM $DEVNAME $DEVPATH
 if [ "$DEVTYPE" = disk -o "$DEVTYPE" = partition ]; then
         [ -e /dev/$DEVNAME ] && exit
         DEV="/${DEVNAME}"
-        [ -e "/dev/${DEV%/*}" ] || mkdir -p "/dev/${DEV%/*}"
+        [ -e "/dev/${DEV%/*}" ] || mkdir $VERB -p "/dev/${DEV%/*}"
         mknod /dev/$DEVNAME b $MAJOR $MINOR
         exit $?
         #}
 else
-[ "$SUBSYSTEM" = sound ] && GPATTERN='alsa|sound' || GPATTERN="$SUBSYSTEM"
+#[ "$SUBSYSTEM" = sound ] && GPATTERN='alsa|sound' || GPATTERN="$SUBSYSTEM"
 #sed -n '/Character devices:/,/Block devices:/p' /proc/devices | grep -E "$GPATTERN" | awk '{print $1}' | grep -w "$MAJOR" && {
         [ -e /dev/$DEVNAME ] && exit
         DEV="/${DEVNAME}"
-        [ -e "/dev/${DEV%/*}" ] || mkdir -p "/dev/${DEV%/*}"
+        [ -e "/dev/${DEV%/*}" ] || mkdir $VERB -p "/dev/${DEV%/*}"
         mknod /dev/$DEVNAME c $MAJOR $MINOR
         exit $?
         #}
@@ -83,7 +128,7 @@ FIRMWAREBIN=`ls /lib/firmware/$FIRMWARE`
 test "$FIRMWAREBIN" || FIRMWAREBIN=`ls /lib/firmware/*/$FIRMWARE`
 test "$FIRMWAREBIN" || exit 1
 test -f "$FIRMWAREBIN" || exit 1
-echo "FIRMWAREBIN='$FIRMWAREBIN'"
+_notice "FIRMWAREBIN='$FIRMWAREBIN'"
 
 echo 1 > /sys/$DEVPATH/loading
 
@@ -91,16 +136,24 @@ cat "$FIRMWAREBIN" > /sys/$DEVPATH/data
 if [ $? = 0 ]; then
     echo 0 >/sys/$DEVPATH/loading
 else
-echo "ERROR loading '$FIRMWAREBIN'"
+_warn "ERROR loading '$FIRMWAREBIN'"
 fi
 }
 
 ;;
-
-remove)
-:;;
-change)
-:;;
+#kernel/lib/kobject_uevent.c:kobject_actions[] = {
+remove )
+_notice "remove:FIXME";;
+change )
+_notice "change:FIXME";;
+move   )
+_notice "move:FIXME";;
+online )
+_notice "online:FIXME";;
+offline)
+_notice "offline:FIXME";;
+*      )
+_warn "anything else:FIXME";;
 esac
 # Very End of this file 'sbin/photplug' #
 ###END###
