/sbin/photplug: First round of code cleanup. Removed unused __install_fw() functions and commented unused code.

diff --git a/woof-code/rootfs-skeleton/sbin/photplug b/woof-code/rootfs-skeleton/sbin/photplug
--- a/woof-code/rootfs-skeleton/sbin/photplug
+++ b/woof-code/rootfs-skeleton/sbin/photplug
@@ -83,19 +83,6 @@ return ${RV:-2}
 }
 
 test "$FIRMWARE" && {
-#echo -n 1 > /sys/$DEVPATH/loading
-__install_fw(){
-if test -d /lib/modules/all-firmware/; then
-FIRMWARETAR=`find /lib/modules/all-firmware/ -maxdepth 1 -type f -iname "*${FIRMWARE%.*}*.tar.gz"`
-for a in $FIRMWARETAR; do
-/bin/tar -C / --strip-components=1 -xzf ${a}
-done
-FIRMWAREBIN=`find /lib/modules/all-firmware/ -type f -ipath "*/lib/firmware/*${FIRMWARE%.*}*"`
-for a in $FIRMWAREBIN; do
-cp -a ${a} /lib/firmware/
-done
-fi
-}
 
 FIRMWAREBIN=`ls /lib/firmware/$FIRMWARE`
 test "$FIRMWAREBIN" || FIRMWAREBIN=`ls /lib/firmware/*/$FIRMWARE`
@@ -109,14 +96,14 @@ test -f "$FIRMWAREBIN" || exit 1
 echo "FIRMWAREBIN='$FIRMWAREBIN'"
 echo 1 > /sys/$DEVPATH/loading
 cat "$FIRMWAREBIN" > /sys/$DEVPATH/data
-if [ $? = 0 ]; then
-    #echo -n  1 > /sys/$DEVPATH/loading
-    #echo -n -1 > /sys/$DEVPATH/loading
-    #echo 0 >/sys/$DEVPATH/loading
-    :
-else
-echo "ERROR loading '$FIRMWAREBIN'"
-fi
+#if [ $? = 0 ]; then
+#    #echo -n  1 > /sys/$DEVPATH/loading
+#    #echo -n -1 > /sys/$DEVPATH/loading
+#    #echo 0 >/sys/$DEVPATH/loading
+#    :
+#else
+[ $? = 0 ] || echo "ERROR loading '$FIRMWAREBIN'"
+#fi
 echo 0 >/sys/$DEVPATH/loading
 }
 
@@ -150,20 +137,6 @@ done
 return ${RV:-2}
 }
 
-__install_fw(){
-if test -d /lib/modules/all-firmware/; then
-FIRMWARETAR=`find /lib/modules/all-firmware/ -maxdepth 1 -type f -iname "*${FIRMWARE%.*}*.tar.gz"`
-for a in $FIRMWARETAR; do
-/bin/tar -C / --strip-components=1 -xzf ${a}
-done
-
-FIRMWAREBIN=`find /lib/modules/all-firmware/ -type f -ipath "*/lib/firmware/*${FIRMWARE%.*}*"`
-for a in $FIRMWAREBIN; do
-cp -a ${a} /lib/firmware/
-done
-fi
-}
-
 FIRMWAREBIN=`ls /lib/firmware/$FIRMWARE`
 test "$FIRMWAREBIN" || FIRMWAREBIN=`ls /lib/firmware/*/$FIRMWARE`
 test "$FIRMWAREBIN" || {
@@ -176,14 +149,14 @@ test -f "$FIRMWAREBIN" || exit 1
 echo "FIRMWAREBIN='$FIRMWAREBIN'"
 echo 1 > /sys/$DEVPATH/loading
 cat "$FIRMWAREBIN" > /sys/$DEVPATH/data
-if [ $? = 0 ]; then
-    #echo -n  1 > /sys/$DEVPATH/loading
-    #echo -n -1 > /sys/$DEVPATH/loading
-    #echo 0 >/sys/$DEVPATH/loading
-    :
-else
-echo "ERROR loading '$FIRMWAREBIN'"
-fi
+#if [ $? = 0 ]; then
+#    #echo -n  1 > /sys/$DEVPATH/loading
+#    #echo -n -1 > /sys/$DEVPATH/loading
+#    #echo 0 >/sys/$DEVPATH/loading
+#    :
+#else
+[ $? = 0 ] || echo "ERROR loading '$FIRMWAREBIN'"
+#fi
 echo 0 >/sys/$DEVPATH/loading
 ;;
 *)
