/sbin/poweroff: Add header; clean up code.

diff --git a/woof-code/rootfs-skeleton/sbin/poweroff b/woof-code/rootfs-skeleton/sbin/poweroff
--- a/woof-code/rootfs-skeleton/sbin/poweroff
+++ b/woof-code/rootfs-skeleton/sbin/poweroff
@@ -1,33 +1,72 @@
 #!/bin/ash
 
+  _TITLE_=pup_wmpoweroff
+_VERSION_=1.0omega
+_COMMENT_="$_TITLE_:Script to run /etc/rc.d/rc.shutdown
+and finally /bin/busybox poweroff"
+
+MY_SELF="$0"
+MY_PID=$$
+
 Version='1.1-simple Macpup_O2-Puppy_Linux_431 KRG'
 
-ERR=/dev/null;OUT=$ERR;VERB='';L_VERB='';A_VERB='';QUIET='-q'; ##+++2012-03-10
-[ "$DEBUG" ] && { ERR=/dev/stderr;OUT=/dev/stdout;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;QUIET=''; }
+#ERR=/dev/null;OUT=$ERR;VERB='';L_VERB='';A_VERB='';QUIET='-q'; ##+++2012-03-10
+#[ "$DEBUG" ] && { ERR=/dev/stderr;OUT=/dev/stdout;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;QUIET=''; }
 #pidof X 1>$OUT 2>$ERR && { echo "X is still running. Please run wm${0##*/}. Exiting script.";exit 1; }
+
+. /etc/rc.d/f4puppy5
+TWO_HELP='1'; TWO_VERSION='1'; TWO_VERBOSE='1'; TWO_DEBUG='1';
+ADD_PARAMETER_LIST="quiet|silent"
+ADD_PARAMETERS="
+-q|quiet  :
+-s|silent :
+"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+    for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+_trap
 
 usage(){ echo "help for $0:
 When run , checks if X not running .
 If X is running executing `which wmpoweroff` .
 wmpoweroff and $0
 do run /etc/rc.d/rc.shutdown
-and are finally executing /bin/busybox poweroff ." ; }
+and are finally executing /bin/busybox poweroff .
 
-test -f /etc/rc.d/f4puppy5 && source /etc/rc.d/f4puppy5
+Options:
+
+h|-h|*help|*usage) Show this usage
+D|-D|*debug)     DEBUG=1
+v|-v|*verbose) VERBOSE=1
+q|-q|*quiet)     QUIET=1
+s|-s|*silent)   SILENT=1
+
+busybox poweroff options:
+`busybox poweroff --help 2>&1`
+"
+
+/etc/rc.d/rc.shutdown --help ; }
+
+#test -f /etc/rc.d/f4puppy5 && source /etc/rc.d/f4puppy5
 
 PARAMETERS="$@"
 #PARAMETERS=`echo "$PARAMETERS" | tr '[[:upper:]]' '[[:lower:]]'`
 for param in $PARAMETERS; do
 echo $param
 case $param in
-h|-h|help|-help|--help) usage;exit 1;;
-D|-D|debug|-debug|--debug) DEBUG=1;;
-v|-v|verbose|-verbose|--verbose) VERBOSE=1;;
-q|-q|quiet|-quiet|--quiet) QUIET=1;;
-s|-s|silent|-silent|--silent) SILENT=1;;
+h|-h|*help|*usage) usage;exit 1;;
+D|-D|*debug)     DEBUG=1;;
+v|-v|*verbose) VERBOSE=1;;
+q|-q|*quiet)     QUIET=1;;
+s|-s|*silent)   SILENT=1;;
 *) BB_PARAMS="$BB_PARAMS $param";;
 esac
 done
+
+#exit
 
 #if [ -n "`ps | grep 'X :' | grep -v 'grep'`" ]; then
 if [ "`pidof X`" ]; then
@@ -35,17 +74,27 @@ exec wmpoweroff $PARAMETERS
 exit
 fi
 
-RETval=''
-/etc/rc.d/rc.shutdown $PARAMETERS || RETval=$?
-if [ "$RETval" ];then
-case $RETval in
+retVAL=''
+/etc/rc.d/rc.shutdown $PARAMETERS || retVAL=$?
+if [ "$retVAL" ];then
+case $retVAL in
 199) echo;return 0 2>$ERR || exit 0;;
 *)
-echo -e "\n\e[1;31m""$0:ERROR: < $RETval > canceling rc.shutdown""\e[0;39m"
-return $RETval 2>$ERR || exit $RETval
+echo -e "\n\e[1;31m""$0:ERROR: < $retVAL > canceling rc.shutdown""\e[0;39m"
+return $retVAL 2>$ERR || exit $retVAL
 ;;
 esac
 fi
+
+#BusyBox v1.22.0Dell755-Opera2 (2014-01-18 04:29:48 GMT+1) multi-call binary.
+#
+#Usage: poweroff [-d DELAY] [-n] [-f]
+#
+#Halt and shut off power
+#
+#   -d SEC  Delay interval
+#   -n  Do not sync
+#   -f  Force (don't go through init)
 
 type -t _kernel_version5 && _kernel_version5
 case $KERNVER in
@@ -53,5 +102,7 @@ case $KERNVER in
 BB_PARAMS="$BB_PARAMS -f -n";;
 esac
 
-echo "Executing /bin/busybox poweroff '$BB_PARAMS'"
+echo -e "\\033[1;33m
+Executing /bin/busybox poweroff '$BB_PARAMS'
+:\\033[0;39m"
 exec /bin/busybox poweroff $BB_PARAMS
