/sbin/poweroff: Some Bugfixes while renaming variables, echo busybox poweroff commandline

diff --git a/woof-code/rootfs-skeleton/sbin/poweroff b/woof-code/rootfs-skeleton/sbin/poweroff
--- a/woof-code/rootfs-skeleton/sbin/poweroff
+++ b/woof-code/rootfs-skeleton/sbin/poweroff
@@ -62,13 +62,13 @@ echo "$MSG"
 exit $1
 }
 
-for p_ in $@;do
+for p_ in $@; do
 case $p_ in
 *help|-h|*usage)
-/etc/rc.d/rc.shutdown $i
+/etc/rc.d/rc.shutdown $p_
 usage 0 ;;
-*force|*debug|*verbose) RC="$RC $i" ;;
-*) POFF="$POFF $i" ;;
+*force|*debug|*verbose) RC="$RC $p_" ;;
+*) POFF="$POFF $p_" ;;
 esac;done
 
 pidof X 1>$OUT 2>$ERR && { echo "X is still running. Please run wm${0##*/}. Exiting script.";exit 1; }
@@ -89,14 +89,16 @@ fi
 Err=$?
 [ "$Err" = 199 ] && exit 0
 if [ "$Err" -ne 0 ] ; then
-if [ -n "`mount | grep /proc`" ] ; then
-echo -e "\\033[0;31m""Something went wrong running /etc/rc.d/rc.shutdown""\\033[0;39m"
-echo -e "\\033[1;31m""Error returncode is '$Err'""\\033[0;39m"
-echo
-exit $Err
+        if [ -n "`mount | grep /proc`" ] ; then
+        echo -e "\\033[0;31m""Something went wrong running /etc/rc.d/rc.shutdown""\\033[0;39m"
+        echo -e "\\033[1;31m""Error returncode is '$Err'""\\033[0;39m"
+        echo
 fi
+  exit $Err
 fi
 
-exec /bin/busybox poweroff "$@"
+echo "Executing busybox poweroff $POFF
+:"
+exec /bin/busybox poweroff $POFF
 # Very End of this file 'sbin/poweroff' #
 ###END###
