poweroff : Bulk Maintanance Replacement of today by Update_from_current_system .

diff --git a/woof-code/rootfs-skeleton/sbin/poweroff b/woof-code/rootfs-skeleton/sbin/poweroff
--- a/woof-code/rootfs-skeleton/sbin/poweroff
+++ b/woof-code/rootfs-skeleton/sbin/poweroff
@@ -1,7 +1,22 @@
-#!/bin/sh
+#!/bin/ash
 . /etc/rc.d/f4puppy5
 # BATCHMARKER01 - Marker for Line-Position to bulk insert code into.
 
+TTY=`tty`
+test -c "$TTY" || TTY=/dev/console
+
 /etc/rc.d/rc.shutdown
 
-exec /bin/busybox poweroff
+case $? in
+0) exec /bin/busybox poweroff "$@";;
+*) #non-zero: an error occured
+   #maybe killed by fuser or killzombies
+   echo -e "$COLOR_RED""An Error Occurred." >"$TTY"
+   echo -e "$COLOR_red""Will return to X desktop." >"$TTY"
+   sleep 5s
+   mountpoint $Q /dev/pts || mount -t devpts devpts /dev/pts
+   mountpoint $Q /sys     || mount -t sysfs sysfs /sys
+   mountpoint $Q /proc    || mount -t proc proc /proc
+   exec xwin
+   ;;
+esac
