poweroff : Bulk Maintanance Replacement of today.

diff --git a/woof-code/rootfs-skeleton/sbin/poweroff b/woof-code/rootfs-skeleton/sbin/poweroff
--- a/woof-code/rootfs-skeleton/sbin/poweroff
+++ b/woof-code/rootfs-skeleton/sbin/poweroff
@@ -1,13 +1,27 @@
 #!/bin/sh
-#110505 support sudo for non-root user.
-#120408 support minit
 
-[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505
+
+PROG='/sbin/poweroff'
+
+sleep 5
+echo "Really want to poweroff ? [Yy] :"
+read -t 60 K
+[ "$K" ] || K=Y
+if [  ! "$K" = "y" -a ! "$K" = "Y" ] ; then
+echo -e "\\033[1;34m""OK , stopping $PROG""\\033[0;39m"
+echo
+exit
+fi
 
 /etc/rc.d/rc.shutdown
+Err=$?
+if [ "$Err" -ne 0 ] ; then
+if [ -n "`mount | grep '/proc`" ] ; then
+echo -e "\\033[0;31m""Something went wrong running /etc/rc.d/rc.shutdown""\\033[0;39m"
+echo -e "\\033[1;31m""Error returncode is '$Err'""\\033[0;39m"
+echo
+exit
+fi
+fi
 
-POWEROFFEXE='/bin/busybox poweroff'
-#[ -f /sbin/minit ] && POWEROFFEXE='/sbin/shutdown -o' #-o means poweroff. note: shutdown is part of minit pkg.
-[ -f /sbin/minit ] && POWEROFFEXE='hard-reboot POWER_OFF' #note: hard-reboot is part of minit pkg.
-
-exec ${POWEROFFEXE} #>/dev/null 2>&1
+exec /bin/busybox poweroff
