this_branch : Replaced BK scripts by mine as
#!/bin/bash

REPO=""
[ "$1" = "-r" ] && REPO="."

GOAL="/root/GitHub.d/KarlGodt_ForkWoof/woof-code/rootfs-skeleton"
[ -d "$GOAL" ] || { echo "$GOAL not a directory.";exit 1; }

rm -f /root/PUPPYscripts.list
for i in $REPO/bin $REPO/sbin $REPO/usr/bin $REPO/usr/sbin $REPO/usr/local/bin $REPO/usr/X11/bin;
do grep -I -H -m1 -i -E "BK|Kauler|Barry|B\.K\.|T2 |t\-2|rxvt" $i/* | grep "#"  >>  /root/PUPPYscripts.list
done

OldIFS="
"
IFS=":"
while read filename rest
do

dn="${filename%/*}"
echo "$filename" "${GOAL}/${dn}/"
cp -a --remove-destination "$filename" "${GOAL}/${dn}/"

done</root/PUPPYscripts.list

IFS="$OldIFS"

STILL MISSING : /root/.dot, /etc, /usr/local/apps .

diff --git a/woof-code/rootfs-skeleton/sbin/probedisk2 b/woof-code/rootfs-skeleton/sbin/probedisk2
--- a/woof-code/rootfs-skeleton/sbin/probedisk2
+++ b/woof-code/rootfs-skeleton/sbin/probedisk2
@@ -1,4 +1,12 @@
-#!/bin/sh
+#!/bin/busybox-1.18.5-ST-98all-1379KB ash
+#/root/my-applications/bin/kash
+#/bin/bash
+#bash-3.00.16-orig bash_3.2
+#/bin/ash
+#busybox-1.20.0-ST
+#busybox-1.18.5-ST-98all-1379KB    busybox-1.21.1_upx9
+#busybox-1.19.4-ST-98all-1388KB    busybox_1.18.3_STATIC_upx9_648KB
+#
 #LGPL 2007 Puppy Linux www.puppyos.com
 #based on probedisk3 written by Dougal.
 #small mods by BK 16 june 2007
@@ -12,51 +20,79 @@
 #v403 fixed excessive spaces in description field.
 #v406 support for old kernel, /proc/ide, /dev/hd*.
 
-########################################################################
-#
-# CHANGES by Karl Reimer Godt
-# 01.0 : ATA+SATADRIVES var new ( still to observe )
-# 02.0 : fallback if info in files contain nothing
-#
-# /dev/hda8:
-# LABEL="MacPup431_O2"
-# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
-# TYPE="ext3"
-# DISTRO_NAME='Puppy'
-# DISTRO_VERSION=431
-# DISTRO_BINARY_COMPAT='puppy'
-# DISTRO_FILE_PREFIX='pup'
-# DISTRO_COMPAT_VERSION='4'
-# PUPMODE=2
-# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
-# PUP_HOME='/'
-# SATADRIVES='·'
-# USBDRIVES='·sda·'
-# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
-# Xserver=/usr/X11R7/bin/Xorg
-# $LANG=de_DE@euro
-# today=Fr·28.·Okt·09:04:43·GMT-1·2011
-#
-#
-#
-#
-#
-########################################################################
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+
+
+trap "exit 1" HUP INT QUIT KILL TERM
+
 
 OUT=/dev/null;ERR=$OUT
 [ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
+[ "$DEBUG" = "2" ] && set -x
+
+
+Version='1.1' ##added partitions
+Version='1.2' ##added function_size, moved code
+
+usage(){
+USAGE_MSG="
+$0 [ PARAMETERS ]
+
+-V|--version : showing version information
+-H|--help : show this usage information
+
+*******  *******  *******  *******  *******  *******  *******  *******  *******
+$2
+"
+exit $1
+}
+
+[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
+[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+
+###KRG Mon Jul  8 22:35:19 GMT+1 2013
+
+function_size(){
+  if [ -f /sys/block/$ONEDRV/size ] ; then
+  read blocks_512 </sys/block/$ONEDRV/size
+  blocks_1024=$(($blocks_512/2))
+  blocks_1000=$(($blocks_512 * 512 / 1000 ))
+   if [ "$blocks_1024" -gt $((1024*1024)) ] ; then
+   #GB
+   SIZE_I=$(( $blocks_1024 / 1024 / 1024 ))
+   SIZE_K=$(( $blocks_1000 / 1000 / 1000 ))
+   SIZES="${SIZE_K}/${SIZE_I} G"
+   elif [ "$blocks_1024" -gt 1024 ] ; then
+   SIZE_I=$(( $blocks_1024 / 1024 ))
+   SIZE_K=$(( $blocks_1000 / 1000 ))
+   SIZES="${SIZE_K}/${SIZE_I} M"
+   else
+   SIZE_I=$blocks_1024
+   SIZE_K=$blocks_1000
+   SIZES="${SIZE_K}/${SIZE_I} K"
+   fi
+  else
+  SIZES='not available'
+  fi
+}
+
+function_partitions(){
+  PARTITIONS=`ls -1 /sys/class/block/$ONEDRV |grep -o -e '[[:digit:]]*' |sort -n |tr '\n' ' '`
+}
+
+###KRGMon Jul  8 22:35:19 GMT+1 2013
 
 . /etc/rc.d/PUPSTATE
 #ATADRIVES is all ide/sata drives (not usb) (which all have /dev/sd notation).
 #if old kernel supporting /dev/hd* then using SATADRIVES variable...
-
-###<KRG+2011_10_28>
-INTERNAL_SD_DRIVES1="$SATADRIVES
-$ATADRIVES"                       ##+++2011_10_28
-INTERNAL_SD_DRIVES=`echo "$INTERNAL_SD_DRIVES1" | sort -u | sort -d`  ##+++2011_10_28
-#[ "$ATADRIVES" != "" ] && INTERNAL_SD_DRIVES="$ATADRIVES"  ##+-+2011_10_28
-###</KRG+2011_10_28>
-
+INTERNAL_SD_DRIVES="$SATADRIVES"
+[ "$ATADRIVES" != "" ] && INTERNAL_SD_DRIVES="$ATADRIVES"
+echo "DBG: intSDdrv=$INTERNAL_SD_DRIVES , usb=$USB_SATAD , ATA=$SATADRIVES , SATA=$ATADRIVES"
 if [ -f /root/.usb-drive-log-probedisk ];then #force /proc upate mechanism
  for ONEUSBDRV in `cat /root/.usb-drive-log-probedisk | tr '\n' ' '`
  do
@@ -66,65 +102,50 @@ if [ -f /root/.usb-drive-log-probedisk ];then #force /proc upate mechanism
 fi
 
 #mounted drives/partitions...
-#MNTDDEVS="`mount | cut -f 1 -d ' ' | cut -f 3 -d '/' | grep -E '^hd|^sd|^scd|^sr|^mmc' | tr '\n' ' '`"
+MNTDDEVS=`mount | cut -f 1 -d ' ' | cut -f 3 -d '/' | grep -E '^hd|^sd|^scd|^sr|^mmc|^fd' | tr '\n' ' '`
 
 #crap, right now, /sys/block does not show my hdb cd/dvd drive, but it is in
 #/proc/ide. pathetic kernel! oh well...
-#if [ ! -e /proc/ide ];then #v3.97
- #ALLDRVS="`ls -1 /sys/block | grep -E '^scd|^sd|^mmc|^sr|^fd' | tr '\n' ' '`"
- ALLDRVS="`ls -1 /sys/block | grep -E '^scd|^sd|^mmc|^sr|^fd|^hd*'`"
-  FDD=`ls -d /sys/block/fd* 2>$ERR`
-  HDD=`ls -d /sys/block/hd* 2>$ERR`
-  MDD=`ls -d /sys/block/mmc* 2>$ERR`
-  SDD=`ls -d /sys/block/sd* 2>$ERR`
-  SCD=`ls -d /sys/block/scd* 2>$ERR`
-  SRD=`ls -d /sys/block/sr* 2>$ERR`
-#else
-if [ -e /proc/ide ];then
- #ALLDRVS="`ls -1 /sys/block | grep -E '^scd|^sd|^mmc|^sr|^fd' | tr '\n' ' '``ls -1 /proc/ide | grep '^hd' | tr '\n' ' '`"
- [ "`echo "$ALLDRVS" | grep '^hd'`" ] || { ALLDRVS="${ALLDRVS}
-`ls -1 /proc/ide | grep '^hd'`"; }
- ##ALLDRVS=`echo "$ALLDRVS" |sort -u`
+if [ ! -e /proc/ide ];then #v3.97
+ ALLDRVS=`ls -1 /sys/block | grep -E '^scd|^sd|^mmc|^sr|^fd' | tr '\n' ' '`
+else
+ ALLDRVS=`ls -1 /sys/block | grep -E '^scd|^sd|^mmc|^sr|^fd' | tr '\n' ' '``ls -1 /proc/ide | grep '^hd' | tr '\n' ' '`
 fi
 #note: after further testing, the 2.6.21.5 kernel exhibits inconsistent behaviour for hd devices, best to avoid.
 
-#for ONEDRV in $ALLDRVS
-while read ONEDRV
+for ONEDRV in $ALLDRVS
 do
-#echo $ONEDRV
   case $ONEDRV in
    hd*) # ide device, look in /proc/ide for info
-     MEDIA="`cat /proc/ide/$ONEDRV/media`"
+     MEDIA=`cat /proc/ide/$ONEDRV/media`
      [ "$MEDIA" = "disk" ] && MEDIA="drive"
      [ "$MEDIA" = "cdrom" ] && MEDIA="optical"
-     [ "$MEDIA" = "" ] && MEDIA='noInfo@procIde'  ##+++2011_10_28
-     INFO="`cat /proc/ide/$ONEDRV/model`"
+     INFO=`cat /proc/ide/$ONEDRV/model`
    ;;
    sd*) # scsi devices, look in /sys/block (all appear as Direct-Access)
      MEDIA="drive"
-     VENDOR="`cat /sys/block/$ONEDRV/device/vendor | tr -s ' '`"
-     [ -z "$VENDOR" ] && VENDOR='noInfo@sysBlock'  ##+++2011_10_28
-     MODEL="`cat /sys/block/$ONEDRV/device/model | tr -s ' '`"
-     [ -z "$MODEL" ] && MODEL='-noInfo@sysBlock'   ##+++2011_10_28
+     VENDOR=`cat /sys/block/$ONEDRV/device/vendor | tr -s ' '`
+     MODEL=`cat /sys/block/$ONEDRV/device/model | tr -s ' '`
      INFO="$VENDOR$MODEL"
      DRVNAMES="$DRVNAMES `echo -n "$ONEDRV" | cut -b 1-3` "
 
      #log if usb drive (not a sata drive)... v4.01...
-     if [ "`echo "$INTERNAL_SD_DRIVES" | grep "$ONEDRV"`" = "" ];then
+     #if [ "`echo "$INTERNAL_SD_DRIVES" | grep "$ONEDRV"`" = "" ];then
+      if [ "`find /sys -name $ONEDRV | grep 'usb' | grep 'block'`" != "" ] ; then
       MEDIA="usbdrv" #v4.01
       echo "$ONEDRV" >> /root/.usb-drive-log-probedisk
       sort -u /root/.usb-drive-log-probedisk > /tmp/usb-drive-log-probedisk-tmp
       mv -f /tmp/usb-drive-log-probedisk-tmp /root/.usb-drive-log-probedisk
       #find out if a usb floppy drive...
+
       if [ -e /sys/block/${ONEDRV}/size ];then
        [ "`cat /sys/block/${ONEDRV}/size`" = "2880" ] && MEDIA="floppy"
       fi
-      #if the floppy diskette not inserted, try this fallback test...
-      #some examples: Vendor: NEC Model: USB UF000x Rev: 1.50, Sony USB Floppy Drive, rev 1.10/5.01,
-      # MITUMI USB FDD, VenDor: TEAC Model: FD-05PUB, Vendor: COMPAQ Model: USB EXT FLOPPY
+
       if [ -e /sys/block/${ONEDRV}/device/model ];then
        [ "`grep -E ' FDD| UF000x|Floppy|USB\-FDU|^FD\-|FLOPPY' /sys/block/${ONEDRV}/device/model`" != "" ] && MEDIA="floppy"
       fi
+
      else
       #find out if it is a removable internal drive (zip, ls120, etc)...
       if [ -e /sys/block/${ONEDRV}/removable ];then
@@ -135,63 +156,75 @@ do
    ;;
    scd*|sr*) #  scsi cdroms
      MEDIA="optical"
-     VENDOR="`cat /sys/block/$ONEDRV/device/vendor | tr -s ' '`"
-     MODEL="`cat /sys/block/$ONEDRV/device/model | tr -s ' '`"
-     [ -z "$VENDOR" ] && VENDOR='noInfo@sysBlock'  ##+++2011_10_28
-     [ -z "$MODEL" ] && MODEL='-noInfo@sysBlock'   ##+++2011_10_28
+     VENDOR=`cat /sys/block/$ONEDRV/device/vendor | tr -s ' '`
+     MODEL=`cat /sys/block/$ONEDRV/device/model | tr -s ' '`
      INFO="$VENDOR$MODEL"
    ;;
    mmc*) #/dev/mmcblk0
      MEDIA="card"
-     NAME="`cat /sys/block/$ONEDRV/device/name`"
-     [ -z "$NAME" ] && NAME='-noInfo@sysBlock'   ##+++2011_10_28
-     #INFO="MMC/SD: `cat /sys/block/$ONEDRV/device/name`"
-     INFO="MMC/SD: $NAME"
+     INFO="MMC/SD: `cat /sys/block/$ONEDRV/device/name`"
    ;;
-   fd*)
+    fd*)
      MEDIA='floppy'
-     NAME='generic'
-     INFO='Attached generic floppy'
-     ;;
+     INFO='Generic 1440KB'
+   ;;
    *)
      continue
    ;;
   esac
-  echo "/dev/$ONEDRV|$MEDIA|$INFO"
+  function_size(){
+  if [ -f /sys/block/$ONEDRV/size ] ; then
+  read blocks_512 </sys/block/$ONEDRV/size
+  blocks_1024=$(($blocks_512/2))
+  blocks_1000=$(($blocks_512 * 512 / 1000 ))
+   if [ "$blocks_1024" -gt $((1024*1024)) ] ; then
+   #GB
+   SIZE_I=$(( $blocks_1024 / 1024 / 1024 ))
+   SIZE_K=$(( $blocks_1000 / 1000 / 1000 ))
+   SIZES="${SIZE_K}/${SIZE_I} G"
+   elif [ "$blocks_1024" -gt 1024 ] ; then
+   SIZE_I=$(( $blocks_1024 / 1024 ))
+   SIZE_K=$(( $blocks_1000 / 1000 ))
+   SIZES="${SIZE_K}/${SIZE_I} M"
+   else
+   SIZE_I=$blocks_1024
+   SIZE_K=$blocks_1000
+   SIZES="${SIZE_K}/${SIZE_I} K"
+   fi
+  else
+  SIZES='not available'
+  fi
+  }
+  function_partitions(){
+  PARTITIONS=`ls -1 /sys/class/block/$ONEDRV |grep -o -e '[[:digit:]]*' |sort -n |tr '\n' ' '`
+  }
+  INFO=`echo $INFO | sed '/^$/d'`
+  [[ -z "$INFO" ]] && INFO="SorryDevWontTell"
 
-done<<EOI
-$(echo "$ALLDRVS")
-EOI
+  #echo -e "/dev/$ONEDRV|$MEDIA|$INFO|$SIZES|$PARTITIONS"
+   echo "/dev/$ONEDRV|$MEDIA|$INFO|$SIZES|$PARTITIONS"
+
+done
 
 #find out if a mounted device has been unplugged...
 #for hotplug drives, remove it and it will disappear from /sys/block, however
 #still shows up in 'mount' if hasn't been unmounted.
-#mounted drives/partitions...
-MNTDDEVS="`mount | cut -f 1 -d ' ' | cut -f 3 -d '/' | grep -E '^hd|^sd|^scd|^sr|^mmc|^fd'`"
-#for ONEMNTD in $MNTDDEVS
-while read ONEMNTD
+for ONEMNTD in $MNTDDEVS
 do
-#echo $ONEMNTD
  case $ONEMNTD in
-  fd*|hd*|sd*|sr*)
-   #MNTDDRVs="`echo -n "$ONEMNTD" | cut -b 1-3` "
-   MNTDDRVs="${ONEMNTD:0:3}"
+  hd*|sd*|sr*)
+   MNTDDRVs="`echo -n "$ONEMNTD" | cut -b 1-3` "
    ;;
   scd*)
-   #MNTDDRVs="`echo -n "$ONEMNTD" | cut -b 1-4` "
-   MNTDDRVs="${ONEMNTD:0:4}"
+   MNTDDRVs="`echo -n "$ONEMNTD" | cut -b 1-4` "
    ;;
   mmc*)
-   #MNTDDRVs="`echo -n "$ONEMNTD" | cut -b 1-7` "
-   MNTDDRVs="${ONEMNTD:0:7}"
+   MNTDDRVs="`echo -n "$ONEMNTD" | cut -b 1-7` "
    ;;
  esac
- #echo $MAINDRIVE
- #echo $MNTDDRVs
  #prints to system log and to stderr...
- [ "`echo "$ALLDRVS" | grep "$MNTDDRV"`" ] || logger -s "PROBEDISK INFO: UNPLUGGED $ONEMNTD still listed mounted."
-done<<EOI
-$(echo "$MNTDDEVS")
-EOI
+ [ "`echo "$ALLDRVS" | grep "$MNTDDRVs"`" = "" ] && logger -s "PROBEDISK ERROR: MOUNTED UNPLUGGED $ONEMNTD"
+done
 
 ###END###
+exit 0
diff --git a/woof-code/rootfs-skeleton/usr/sbin/burniso2cd b/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
--- a/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
+++ b/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
@@ -6,38 +6,68 @@
 #v3.02 2Nov2007 BK: bugfix. v3.94 24dec2007: no /dev/hd*
 #w482 change -pad to padsize=300k, recommended by xorriso developer.
 #w482 migrate to using xorriso.
-#v431 rerwin: Add wait for drive lights to stop flashing before verifying and log the verify dd messages.
+
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+trap "exit 1" HUP INT QUIT KILL TERM
+
+OUT=/dev/null;ERR=$OUT
+[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
+[ "$DEBUG" = "2" ] && set -x
+
+Version='1.1'
+
+usage(){
+USAGE_MSG="
+$0 [ PARAMETERS ]
+
+-V|--version : showing version information
+-H|--help : show this usage information
+
+*******  *******  *******  *******  *******  *******  *******  *******  *******
+$2
+"
+echo "$USAGE_MSG"
+exit $1
+}
+
+[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
+[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
 
 CDRECORD='cdrecord'
-if [ "`which xorriso`" != "" ];then
- CDRECORD='xorrecord'
- export MKISOFS='xorrisofs' #growisofs reads this variable.
-fi
+#if [ "`which xorriso`" != "" ];then
+# CDRECORD='xorrecord'
+# export MKISOFS='xorrisofs' #growisofs reads this variable.
+#fi
 
-MEDIATYPE="`Xdialog --wmclass "mini-cd" --title "Burniso2cd" --stdout --menubox "Welcome to our little CD/DVD burner program!\nPlease choose whether you want to burn to a CD or DVD media.\nNote that DVDs are always burnt 'open' so can be used by Puppy\nas normal or multisession, whereas for CD you will be given\nthe choice further on whether to burn as closed or open." 0 0 5 CD "CD-R or CD-RW (must be blank)" DVD "DVD-R or DVD-RW (must be blank)"`"
+MEDIATYPE=`Xdialog --wmclass "mini-cd" --title "Burniso2cd" --stdout --menubox "Welcome to our little CD/DVD burner program!\nPlease choose whether you want to burn to a CD or DVD media.\nNote that DVDs are always burnt 'open' so can be used by Puppy\nas normal or multisession, whereas for CD you will be given\nthe choice further on whether to burn as closed or open." 0 0 5 CD "CD-R or CD-RW (must be blank)" DVD "DVD-R or DVD-RW (must be blank)"`
 [ ! $? -eq 0 ] && exit
-
-SELECTIONS="`probedisk | grep '|cdrom|' | grep '/dev/' | cut -f 1,3 -d '|' | tr " " '_' | tr -s '_'`"
-SELECTIONX="`echo "$SELECTIONS" | tr '|' " " | tr "\n" " "`"
-
+echo "MEDIATYPE='$MEDIATYPE'"
+SELECTIONS=`probedisk | grep '|cdrom|' | grep '/dev/' | cut -f 1,3 -d '|' | tr " " '_' | tr -s '_'`
+echo "SELECTIONS='$SELECTIONS'"
+SELECTIONX=`echo "$SELECTIONS" | tr '|' " " | tr "\n" " "`
+echo "SELECTIONX='$SELECTIONX'"
 if [ "$SELECTIONX" = "" ];then
  xmessage "Sorry, no CD/DVD drive detected"
  exit
 fi
 
-BURNERDRIVE="`Xdialog --wmclass "mini-cd" --title "Burniso2cd: Choose burner drive" --stdout --menubox "Choose the CD/DVD drive to burn to" 400x200 5 $SELECTIONX 2> /dev/null`"
+BURNERDRIVE=`Xdialog --wmclass "mini-cd" --title "Burniso2cd: Choose burner drive" --stdout --menubox "Choose the CD/DVD drive to burn to" 400x200 5 $SELECTIONX 2> /dev/null`
 [ ! $? -eq 0 ] && exit
-
+echo "BURNERDRIVE='$BURNERDRIVE'"
 [ ! -f /etc/cdburnerdevice ] && echo -n "$BURNERDRIVE" | sed -e 's/\/dev\///g' > /etc/cdburnerdevice
 
-ISOFILE="`Xdialog --wmclass "mini-cd" --backtitle "Please choose the iso file..." --title "Burniso2cd: Choose iso file" --stdout --no-buttons --fselect "*.iso" 0 0`"
+ISOFILE=`Xdialog --wmclass "mini-cd" --backtitle "Please choose the iso file..." --title "Burniso2cd: Choose iso file" --stdout --no-buttons --fselect "*.iso" 0 0`
 if [ ! $? -eq 0 ];then
  exit
 fi
-
+echo "ISOFILE='$ISOFILE'"
 CDR="$BURNERDRIVE"
-CDDESCR="`echo "$SELECTIONS" | grep "$CDR" | cut -f 2 -d '|'`"
-
+CDDESCR=`echo "$SELECTIONS" | grep "$CDR" | cut -f 2 -d '|'`
+echo "CDDESCR='$CDDESCR'"
 while [ ! "`mount | grep "$CDR"`" = "" ];do
  xmessage -bg "#ff8080" -center -name "burniso2cd" -title "Burniso2cd: ERROR" "The $CDR CD/DVD drive, described as:
  $CDDESCR
@@ -102,41 +132,60 @@ Then click 'OK' button..." 0 0 4 32 $BURNSPEED "Set burn speed"`"
  [ ! $? -eq 0 ] && exit
 
  sync
+echo "BURNSPEED='$BURNSPEED'"
  if [ "$MEDIATYPE" = "CD" ];then
- 
+
   #if [ ! "`echo "$CDR" | grep '/dev/hd'`" = "" ];then
   # DEVDEV="ATAPI:$CDR"
   #else
   # DEVDEV="$CDR"
   #fi
   DEVDEV="$CDR" #w482
-  
+
   echo "Now executing:"
   echo " $CDRECORD $BURNMULTI -data -eject -v speed=$BURNSPEED dev=$DEVDEV $ISOFILE"
-  rxvt -name burniso2cd -bg orange -geometry 80x10 -e $CDRECORD $BURNMULTI -data -eject -v speed=$BURNSPEED dev=$DEVDEV "$ISOFILE"
+  #rxvt -name burniso2cd -bg orange -geometry 80x10 -e $CDRECORD $BURNMULTI -data -eject -v speed=$BURNSPEED dev=$DEVDEV "$ISOFILE"
+  echo '#!/bin/sh' >/tmp/burniso2cd
+  echo "
+$CDRECORD $BURNMULTI -data -eject -v speed=$BURNSPEED dev=$DEVDEV \"$ISOFILE\"
+RETVAL=$?
+read -n1 -p \"Press Enter\" EK
+exit $RETVAL
+" >>/tmp/burniso2cd
+chmod +x /tmp/burniso2cd
+rxvt -name burniso2cd -bg orange -geometry 80x10 -e /tmp/burniso2cd
+BURNOK=$?
  else #dvd
   echo "Now executing:"
   echo " growisofs -speed=$BURNSPEED -Z $CDR=$ISOFILE"
-  rxvt -name burniso2cd -bg orange -geometry 80x10 -e growisofs -speed=$BURNSPEED -Z $CDR="$ISOFILE"
+  #rxvt -name burniso2cd -bg orange -geometry 80x10 -e growisofs -speed=$BURNSPEED -Z $CDR="$ISOFILE"
+  echo '#!/bin/sh' >/tmp/burniso2cd
+  echo "
+growisofs -speed=$BURNSPEED -Z $CDR=\"$ISOFILE\"
+RETVAL=$?
+read -n1 -p \"Press Enter\" EK
+exit $RETVAL
+" >>/tmp/burniso2cd
+chmod +x /tmp/burniso2cd
+rxvt -name burniso2cd -bg orange -geometry 80x10 -e /tmp/burniso2cd
+BURNOK=$?
  fi
  sync
- echo "...done"
+[ "$BURNOK" = 0 ] && echo "...done." || echo "...failure..."
 
  #v2.10 kirk contributed this...
  # ******Verify burn******
- DEVNAME="`echo -n "$CDR" | grep '/dev' | cut -f 3 -d '/'`"
+ DEVNAME=`echo -n "$CDR" | grep '/dev' | cut -f 3 -d '/'`
  if [ ! "$DEVNAME" = "" -a "$RECHECK" = "yes" ];then
-  Xdialog --wmclass "mini-cd" --title "Burniso2cd: Finished" --stdout --yesno "Would you like to verify that the burn was successful? 
+  Xdialog --wmclass "mini-cd" --title "Burniso2cd: Finished" --stdout --yesno "Would you like to verify that the burn was successful?
 This may take a while depending on the size of the iso file." 0 0
-  if  [ "$?" = "0" ] ;then  
+  if  [ "$?" = "0" ] ;then
    xmessage -bg "#80ff80" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "Make sure the CD/DVD drive is closed,
 then click OK"
-   echo "Waiting 15 seconds to allow drive lights to finish blinking" > /tmp/burniso2cd.log #v431
-   sleep 15 #v431
-   if [ "$( md5sum $ISOFILE | cut -f 1 -d " " )" = "$(dd if=$CDR 2>> /tmp/burniso2cd.log | head -c `stat --format=%s $ISOFILE` | md5sum | cut -f 1 -d " " )" ] ;then #v431
+   if [ "$( md5sum $ISOFILE | cut -f 1 -d " " )" = "$(dd if=$CDR | head -c `stat --format=%s $ISOFILE` | md5sum | cut -f 1 -d " " )" ] ;then
     xmessage -bg "#80ff80" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "The burn has been verified as good!"
    else
-    xmessage -bg "#ffc0c0" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "The burn was not verified. See details in /tmp/burniso2cd.log. You should start over."
+    xmessage -bg "#ffc0c0" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "The burn was not verified. You should start over"
    fi
   else
    RECHECK="no" #do not check if doing repeat burns.
diff --git a/woof-code/rootfs-skeleton/usr/sbin/filemnt b/woof-code/rootfs-skeleton/usr/sbin/filemnt
--- a/woof-code/rootfs-skeleton/usr/sbin/filemnt
+++ b/woof-code/rootfs-skeleton/usr/sbin/filemnt
@@ -1,38 +1,185 @@
 #!/bin/bash
-##############  ROX app.: Click image files to mount & unmount. by: Terry Becker    aka: SunBurnt
-##############  File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
+##############  ROX app.: Click image files to mount & unmount.	by: Terry Becker	aka: SunBurnt
+##############	File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
 #v423 detect wrong squashfs version 3.x or 4.x.
 #v424 advise of sfs-version-converter.
 
-exec 1>>/tmp/filemnt.log 2>&1
 
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+trap "exit 1" HUP INT QUIT KILL TERM
+
+deprecated(){
+OUT=/dev/null;ERR=$OUT
+[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
+[ "$DEBUG" = "2" ] && set -x
+
+Version='1.1'
+
+usage(){
+USAGE_MSG="
+$0 [ PARAMETERS ]
+
+-V|--version : showing version information
+-H|--help : show this usage information
+
+*******  *******  *******  *******  *******  *******  *******  *******  *******
+$2
+"
+echo "$USAGE_MSG"
+exit $1
+}
+
+[ "`echo "$1" | grep -wE "\-help|\-H"`" ] && usage 0
+[ "`echo "$1" | grep -wE "\-version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
+}
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+########################################################################
+#
+# CHANGES by Karl Reimer Godt
+# 01.0 : added xmessage dialog if already mounted to choose actions :
+#        Quit,ROX-Filer,console,Unmount,Unmountall,MountAnotherTime
+# 02.0 : position of removal of $MntPt changed in code
+# 03.0 : double quoted all $imgFile AND $MntPt in case of spaces
+# 04.0 : added support for these extensions :
+#        .squashfs, .sqfs, .squashfs.img -> .sfs
+#        .ext3fs.img -> ext3
+#        .iso -> iso9660 || udf || * ( using 'disktype' command )
+#
+# /dev/sda5:
+# LABEL="MacPup430_F3"
+# UUID="07443de5-1fab-4656-a3ab-7b1c14ccc8c8"
+# TYPE="ext3"
+# DISTRO_VERSION=430            #481·#416·#218·#478······#####change·this·as·required#####
+# DISTRO_BINARY_COMPAT="puppy"  #"ubuntu"·#"puppy"·#####change·this·as·required#####
+# case·$DISTRO_BINARY_COMPAT·in
+# puppy)·#built·entirely·from·Puppy·v2.x·or·v3.x·or·4.x·pet·pkgs.
+# DISTRO_NAME="Puppy"
+# DISTRO_FILE_PREFIX="pup"      #"ppa"·#"ppa4"·#"pup2"··#pup4··###CHANGE·AS·REQUIRED,·recommend·limit·four·characters###
+# DISTRO_COMPAT_VERSION="4"     #"2"··#4·····###CHANGE·AS·REQUIRED,·recommend·single·digit·5,·4,·3,·or·2###
+# ;;
+# esac
+# PUPMODE=2
+# KERNVER=2.6.30.7-KRG-i586
+# ATADRIVES='·sda'
+# USB_SATAD=''
+# PUP_HOME='/'
+# Linux·puppypc·2.6.30.7-KRG-i586·#2·SMP·Tue·Jan·4·15:42:45·CET·2011·i686·GNU/Linux
+# Xserver=/usr/X11R7/bin/Xvesa_stripped_upx9
+# $LANG=en_US
+# today=Thu·Oct·27·11:44:41·CEST·2011
+# TODO1 : cleanup my code
+# TODO2 : cleanup original code
+# TODO3 : observe fuser -c and fuser -m
+# TODO4 : Kernel 3.x.x ready ~FIXED
+# TODO5 : create grepPatternMntPt
+# TODO6 : both fuser parts into one func
+# TODO7 : adopt the code from npierce
+#
+########################################################################
+
+Version='1.1-getopts Macpup_Foxy_3-Puppy-Linux-430/2 KRG'
+usage (){
+MSG="
+$0 [-V|-v|-d|-h|-l] FILENAME.sfs
+Script to mount and unmount
+loop image, iso and squashfs files
+[ by simple left click ] .
+
+-V) show version
+-v) verbose
+-d) debug
+-h) show this usage
+-l) log to /tmp/filemnt.log
+"
+echo "$MSG"
+[ "$DISPLAY" ] && xmessage -bg lightgreen "$MSG"
+exit $1
+}
+[[ "$1" =~ 'help' ]] && usage 0
+[[ "$1" =~ 'version' ]] && { echo -e "\n$0: Version '$Version'\n";exit 0; }
+OUT=/dev/null;ERR=$OUT
+while getopts Vvdhl opt;do
+case $opt in
+V) echo -e "\n$0: Version '$Version'\n";exit 0;;
+v) VERBOSE=1;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;ERR=/dev/stderr;OUT=/dev/stdout;;
+d) DEBUG=1;set -x;;
+h) usage 0;;
+l) exec 1>>/tmp/filemnt.log 2>&1;;
+*) :;;
+esac;done
+
+echo
+echo '----------------------------------------------------------------------'
 #v423...
-KERNELVER="`uname -r`"
+KERNELVER=`uname -r`
+KERNEL_MAJ=${KERNELVER:0:1}
 KERNELSUBVER=`echo -n "$KERNELVER" | cut -f 3 -d '.' | cut -f 1 -d '-'`
-SFSSTR='squashfs, version 3'
-[ $KERNELSUBVER -gt 28 ] && SFSSTR='squashfs, version 4'
+SFSSTR='squashfs, version 4'
+if [ "$KERNEL_MAJ" -lt 3 ] ; then
+[ "$KERNELSUBVER" -lt 29 ] && SFSSTR='squashfs, version 3'
+fi
 
- imgFile="$1"
- if [ -z "$imgFile" ] ;then exit 1 ;fi #1
+imgFile="$1"
+if [ -z "$imgFile" ];then usage 1 ;fi
+[ -f "$imgFile" ] || { echo "'$imgFile' seems not to be here . Exit .";exit 1; }
 
- if [ "`basename $imgFile`" = 'initrd' ] ;then gzip -9 $imgFile ;fi # 11
- if [ "`basename $imgFile`" = 'initrd.gz' ] ;then gzip -9 $imgFile ;fi # 111
+if [ "`basename "$imgFile"`" = 'initrd' ] ; then
+ if [ "`file "$imgFile" | grep -i 'cpio'`" ] ; then
+  cd `dirname "$imgFile"`
+  rm -rf initrd-tree
+  mkdir initrd-tree
+  cd initrd-tree
+  cat ../initrd |cpio -i -d
+  exit $?
+ else
+  gzip -9 "$imgFile" ;fi
+  exit $?
+fi
+
+if [ "`basename "$imgFile"`" = 'initrd.gz' ] ; then
+ if [ "`file "$imgFile" | grep -i 'cpio'`" ] ; then
+  cd `dirname "$imgFile"`
+  rm -rf initrd-tree
+  mkdir initrd-tree
+  cd initrd-tree
+  zcat ../initrd.gz |cpio -i -d
+  exit $?
+ else
+  gunzip "$imgFile" ;fi
+  exit $?
+fi
+
+if [ "`basename "$imgFile"`" = 'initrd.xz' ] ; then
+ if [ "`file "$imgFile" | grep -i 'cpio'`" ] ; then
+  cd `dirname "$imgFile"`
+  rm -rf initrd-tree
+  mkdir initrd-tree
+  cd initrd-tree
+  xzcat ../initrd.xz |cpio -i -d
+  exit $?
+ else
+   xz -d  "$imgFile" ;fi
+   exit $?
+fi
+
+if [ "`dirname "$imgFile"`" = '\.' ] ;then # 2
+      imgFile=`pwd``echo "$imgFile" |sed 's/^\.//'`
+fi # 2
 
 
- if [ "`dirname $imgFile`" = '\.' ] ;then # 2
-  imgFile="`pwd``echo $imgFile |sed 's/^\.//'`"
- fi # 2
+#MntPt='/mnt/'`echo "$imgFile" |sed "s#^\.##g" |sed "s#/#+#g"`
+MntPt='/mnt/'`basename "$imgFile"`.$$  ##my change
+grepPatternMntPt=`echo "$MntPt" | sed 's#\([[:punct:]]\)#\\\1#g'`
+grepPatternImgFile=`echo "$imgFile" | sed 's#\([[:punct:]]\)#\\\1#g'`
 
+if [ 1 -eq 2 ] ;then	##############################################	JUMP OVER this SECTION.
 
- MntPt='/mnt/'`echo "$imgFile" |sed "s#^\.##g" |sed "s#/#+#g"`
- MntPt='/mnt/'`basename "$imgFile"`.$$
-
-if [ 1 -eq 2 ] ;then    ##############################################  JUMP OVER this SECTION.
-
- loMnts="`mount |grep '/dev/loop' |awk '{print $1}'`"
- echo "$loMnts" |while read LOOP                    ### test if file's mounted
+ loMnts=`mount |grep '/dev/loop' |awk '{print $1}'`
+ echo "$loMnts" |while read LOOP					### test if file's mounted
  do
-   loFile="`losetup-FULL $LOOP |sed 's/^.*(//' |sed 's/).*$//'`"
+   loFile=`losetup-FULL $LOOP |sed 's/^.*(//' |sed 's/).*$//'`
    if [ "$loFile" = "$imgFile" ] ;then
     echo -e "\n ### Loop File: $loFile"
     break
@@ -40,13 +187,13 @@ if [ 1 -eq 2 ] ;then    ##############################################  JUMP OVE
    i=`expr $i + 1`
  done
 
-fi          ##############################################  END of JUMP SECTION.
+fi			##############################################	END of JUMP SECTION.
 
 
-                            ### file's not mounted, mount it
+							### file's not mounted, mount it
 # if [ $i -eq 16 ] ;then
 
-imgFileBASE="`basename "$imgFile"`" #BK
+imgFileBASE=`basename "$imgFile"` #BK  ##only for yaf/xmessage message not too long
 
 if [ ! -d "$MntPt" ] ;then # 5
 
@@ -56,10 +203,14 @@ check_already_mounted_func(){
   for ONELOOP in `mount | grep '^/dev/loop' | cut -f 1 -d ' ' | tr '\n' ' '`
   do
 
-   MNTDIMG="`losetup-FULL $ONELOOP | cut -f 2 -d '(' | cut -f 1 -d ')'`"
-   IMGBASE="`basename "$MNTDIMG"`"
+   MNTDIMG=`losetup-FULL $ONELOOP | cut -f 2 -d '(' | cut -f 1 -d ')'`
+   IMGBASE=`basename "$MNTDIMG"`
+    #TODO 64 chars
+    #bash-3.2# losetup-FULL /dev/loop1
+    #/dev/loop1: [0700]:2579 (/mnt/xubuntu-11.10-desktop-i386.iso.29782/casper/filesystem.sq*)
+                            #1234567890123456789012345678901234567890123456789012345678901234
 
-    #echo "IMGBASE=$IMGBASE imgFileBASE=$imgFileBASE" #TEST
+    echo "IMGBASE='$IMGBASE' imgFileBASE='$imgFileBASE'" #TEST
     #not perfect, but paths may be symlinks...
 
     if [ "$IMGBASE" = "$imgFileBASE" ];then #if [ "$MNTDIMG" = "$imgFile" ];then #6
@@ -69,38 +220,39 @@ xmessage -buttons "Quit:190,ROX-Filer:191,console:192,Unmount:193,Unmount all $I
 is already mounted and in-use by Puppy .
 Do you want to unmount it or mount it to another mount point ?"
 RETVAL=$?
-if [ "$RETVAL" = "190" ] ; then #666
+if [ "$RETVAL" = "190" ] ; then #666  ##Quit
      exit
 
- elif [ "$RETVAL" = "191" ] ; then #666
-     MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
-     rox $MntPt
-     exit
+elif [ "$RETVAL" = "191" ] ; then #666  ##ROX-Filer
+       MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
+       rox "$MntPt"
+       exit
 
-elif [ "$RETVAL" = "192" ] ; then #666
-     MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
-     cd $MntPt
-     pwd
-     rxvt &
-     exit
+elif [ "$RETVAL" = "192" ] ; then #666  ##console
+       MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
+       cd "$MntPt"
+       pwd
+       rxvt &
+       exit
 
-elif [ "$RETVAL" = "193" ] ; then #666
+elif [ "$RETVAL" = "193" ] ; then #666  ##umount
        UNMOUNT='yes'
        MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
        return
 
-elif [ "$RETVAL" = "194" ] ; then #666
+elif [ "$RETVAL" = "194" ] ; then #666  ##umount ALL $IMGBASE
        UNMOUNT='yes'
        MntPt=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
        echo 1 "$MntPt"
-       MntPt2=`echo "$MntPt" | sed "1 d"`
+       MntPt2=`echo "$MntPt" | sed "1 d"` ##only umount all others exect one
        echo 2 "$MntPt2"
        for i in $MntPt2 ; do
        GREP=`echo "$i" | sed 's#\.#\\\.#g;s#\+#\\\+#g;s#-#\\\-#g'`
        echo "$GREP"
        LOOPD=$(busybox mount | grep "$GREP" | cut -f 1 -d ' ')
        echo "$LOOPD"
-       USEapps=`fuser -c $LOOPD`
+       #USEapps=`fuser -c $LOOPD`    ##---2011_10_27
+       USEapps=`fuser -m "$MntPt2"`   ##+++2011_10_27
        echo 3 "$USEapps"
        USEapps=`echo "$USEapps" | sed 's/[[:alpha:]]//g'`
        echo 4 "$USEapps"
@@ -119,9 +271,10 @@ elif [ "$RETVAL" = "194" ] ; then #666
 else #666
      MOUNT='again'
      return
-fi ###666
-
-fi ##6
+fi   ###666
+else ##66      ##+++2011_10_27 to fix call from without X running
+UNMOUNT='yes'  ##+++2011_10_27
+fi ##66
 fi #6
 done
 
@@ -130,31 +283,46 @@ check_already_mounted_func
 
 fi # 5
 
-if [ -z "$UNMOUNT" ] ; then #55
+if [ -z "$UNMOUNT" ] ; then #55 == yes || [ -n "$MOUNT" ] == again
 
-  Ext=`echo "$imgFile" |sed 's/^.*\.//'`    # get file type from extention
+  Ext=`echo "$imgFile" |sed 's/^.*\.//'`	# get file type from extention
   if [ "$Ext" = '2fs' ] ;then #7
    Type='ext2'
   elif [ "$Ext" = '3fs' ] ;then
    Type='ext3'
+  elif [  "$imgFileBASE" = 'ext3fs.img' ];then
+   Type='ext3'
   elif [ "$Ext" = '4fs' ] ;then #v423 planning for the future!
    Type='ext4'
-  elif [ "$Ext" = 'sfs' -o "$Ext" = 'sqfs' -o "$Ext" = 'squashfs' ] ;then
+  elif [ "$Ext" = 'sfs' -o "$Ext" = 'squashfs' -o "$Ext" = 'sqfs' ] ;then
+   Type='squashfs'
+  elif [ "$imgFileBASE" = 'squashfs.img' ];then
    Type='squashfs'
   elif [ "$Ext" = 'iso' ] ;then
-   Type='iso9660'
+   #Fatdog fat16 first and iso9660 second  ###+++2013-03-02
+   TYPES=`disktype "$imgFile" |grep 'file system'`
+   if [ "`echo "$TYPES" |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]' | grep -i 'UDF'`" ];then
+    Type=udf
+   else
+    Type=iso9660
+   fi
+   else
+   Type=`disktype "$imgFile" |grep 'file system' |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]'` ##+++2012-06-04 udf or iso9660
+   #Type='iso9660' ##---2012-06-04
   # BK
   #elif [ "$imgFile" = 'initrd.gz' ] ;then
   # Type='ext2'
-  # gunzip $imgFile             # handle gzip image file
+  # gunzip $imgFile				# handle gzip image file
   # imgFile="echo "$imgFile" |sed 's/.gz$//'"
   fi #7
 
   #v423 detect wrong squashfs version...
   if [ "$Type" = "squashfs" ];then #8
-   if [ "`disktype "${imgFile}" | grep "$SFSSTR"`" = "" ];then #8.1
+   DISK_TYPE=`disktype "${imgFile}"`
+   if [ "`echo "${DISK_TYPE}" | grep "$SFSSTR"`" = "" ];then #8.1
+    xmessage -bg orange1 "$DISK_TYPE"
     if [ $KERNELSUBVER -gt 28 ];then #8.1.1
-     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This is an older version 3.x squashfs file, not usable.
+     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This may be an older version 3.x squashfs file, not usable.
 All Linux kernels 2.6.29 or later require version 4.x squashfs files.
 Note, there is an SFS-version-converter in the Utility menu, run that first."
     else #8.1.1
@@ -168,22 +336,23 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
 
 #  echo -e "\nimgFile = $imgFile\t\tExt  = $Ext"
 #  echo -e "MntPt   = $MntPt\t\tType = $Type\n"
-  echo -e "\n ### Mount: $imgFile\n"
+  echo -e "\n$0 : Mount: $imgFile\n"
   mkdir -p "$MntPt"
+  echo '-------------'
   mount -t $Type -o loop "$imgFile" "$MntPt"
-  Err=$?
+  Err=$?     ##+++2011_10_27
+  echo '-------------'
   sleep 2s
-  if [ $Err -eq 0 ] && [ -n "`mount | grep "$MntPt"`" ];then #9
+  #Err=$?    ##---2011_10_27
+  if [ $Err -eq 0 ] || [ -n "`mount | grep "$MntPt"`" ];then #9
    if [ -n "$DISPLAY" ] ; then #99
     rox -d "$MntPt" # mount good, run rox filer
    ##[ -n "$DISPLAY" ] && yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
     yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
    fi #99
-  else
-  rmdir "$MntPt"
   fi #9
 
- else #55                       ### file's mounted, unmount it
+ else #55	[ -n "$UNMOUNT" ]					### file's mounted, unmount it
 
    [ -n "$DISPLAY" ] && rox -D "$MntPt" #BK
 
@@ -191,7 +360,8 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
        echo 1 "$GREP"
        LOOPD=$(busybox mount | grep "$GREP" | cut -f 1 -d ' ')
        echo 2 "$LOOPD"
-       USEapps=`fuser -c $LOOPD`
+       #USEapps=`fuser -c $LOOPD`  ##---2011_10_27
+       USEapps=`fuser -m "$MntPt"`  ##---2011_10_27
        echo 3 "$USEapps"
        USEapps=`echo "$USEapps" | sed 's/[[:alpha:]]//g;s/[[:punct:]]//g'`
        echo 4 "$USEapps"
@@ -200,33 +370,34 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
        kill -1 $j
        done
 
-   sleep 2s
+  sleep 2s
+  echo '------------'
   umount "$MntPt"
   Err=$?
-
+  echo '------------'
   #yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg orange -text "$Err"
-  sleep 2s
+  #sleep 2s  ##+-2011_10_27
   #rmdir $MntPt
   #yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg orange -text "$MntPt"
 
 
   [ -n "$DISPLAY" ] && yaf-splash -timeout 3 -font "8x16" -outline 0 -margin 4 -bg orange -text "Unmounting $imgFileBASE" #BK
-
+   sleep 2s  ##+++2011_10_27
   #Xdialog --title " Notice..." --no-button \
   #        --infobox "
   #UnMounting: $imgFile
   #" 0 0 2000
 
-  echo -e "\n ### UnMount: $imgFile\n"
+  echo -e "\n$0 UnMount: $imgFile\n"
 
-  [ -d "$MntPt" -a "`busybox mount | grep "$MntPt"`" = "" ] && rmdir "$MntPt"
-
+  #[ -d "$MntPt" -a "`busybox mount | grep "$MntPt"`" = "" ] && rmdir "$MntPt"  #=-2011_10_27
+   [ -d "$MntPt" ] && [ -z "`ls "$MntPt" 2>/dev/null`" ] && rmdir "$MntPt"
  fi #55
 
- if [ "$Err" -gt 0 ] ;then          # ERROR: mount/unmount # 9999
-  [ -n "$DISPLAY" ] && xmessage -bg red -title "ERROR..." "Returned $Err ... mounting or unmounting $MntPt"
+ if [ "$Err" -gt 0 ] ;then			# ERROR: mount/unmount # 9999
+  [ -n "$DISPLAY" ] && xmessage -bg red -title "ERROR..." "Returned <$Err> ... mounting or unmounting $MntPt"
+  [ -d "$MntPt" ] && [ -z "`ls "$MntPt" 2>/dev/null`" ] && rmdir "$MntPt"  ##+++2011_10_27
  fi # 9999
 
-echo "$0:Exiting with '$Err'"
-exit $Err
+
 
diff --git a/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd b/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd
--- a/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd
+++ b/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd
@@ -8,6 +8,36 @@
 #v555 pup files renamed to woofr555.sfs, woofsave.2fs.
 #w482 use xorriso instead of cdrtools/cdrkit if installed.
 
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+trap "exit 1" HUP INT QUIT KILL TERM
+
+OUT=/dev/null;ERR=$OUT
+[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
+[ "$DEBUG" = "2" ] && set -x
+
+Version='1.1'
+
+usage(){
+USAGE_MSG="
+$0 [ PARAMETERS ]
+
+-V|--version : showing version information
+-H|--help : show this usage information
+
+*******  *******  *******  *******  *******  *******  *******  *******  *******
+$2
+"
+echo "$USAGE_MSG"
+exit $1
+}
+
+[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
+[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
 #/etc/rc.d/rc.shutdown saves session at shutdown, savesession-dvd is called
 #from desktop icon to do an immediate save to multisession-cd.
 
@@ -24,7 +54,7 @@ export CDRECORD MKISOFS
 . /etc/rc.d/PUPSTATE #v2.02
 . /etc/DISTRO_SPECS #v412
 ORIGPUPMODE=$PUPMODE #v2.22
-#PUPPYVERSION="`cat /etc/puppyversion`"
+#PUPPYVERSION=`cat /etc/puppyversion`
 
 . /etc/rc.d/functions4puppy #v3.01 has multisavefunc.
 
@@ -35,9 +65,9 @@ CONSRUN="$1" #will execute multisavefunc from a rxvt console.
 [ "`pidof X | grep '[0-9]'`" = "" ] && CONSRUN="yes"
 
 if [ ! "$PUPSAVE" = "" ];then
- SAVEFS="`echo -n "$PUPSAVE" | cut -f 2 -d ','`"   #f.s. and partition where ${DISTRO_FILE_PREFIX}save.2fs is located.
- SAVEPART="`echo -n "$PUPSAVE" | cut -f 1 -d ','`" # "
- SAVEFILE="`echo -n "$PUPSAVE" | cut -f 3 -d ','`"
+ SAVEFS=`echo -n "$PUPSAVE" | cut -f 2 -d ','`   #f.s. and partition where ${DISTRO_FILE_PREFIX}save.2fs is located.
+ SAVEPART=`echo -n "$PUPSAVE" | cut -f 1 -d ','` # "
+ SAVEFILE=`echo -n "$PUPSAVE" | cut -f 3 -d ','`
 else
  exit #v2.22
 fi
@@ -46,17 +76,17 @@ CDR="/dev/$SAVEPART"
 
 if [ ! "$CONSRUN" = "" ];then
  multisavefunc
- exit
+ exit $?
 fi
 
 
 if [ "$PUPMODE" != "77" ];then
  xmessage -bg "indian red" -center -title "SaveSession-DVD" "Sorry, this is not a multisession live-CD/DVD"
- exit
+ exit 1
 fi
 if [ "$CDR" = "" ];then
  xmessage -bg "indian red" -center -title "SaveSession-DVD" "Sorry, this is not a multisession live-CD/DVD"
- exit
+ exit 1
 fi
 
 
@@ -68,7 +98,7 @@ if [ "`mount | grep "$CDR"`" != "" ];then
  sync
  umount $CDR
  if [ ! $? -eq 0 ];then
-  xmessage -bg "indian red" -center -title "SaveSession: ERROR" "Sorry, $CDR is currently mounted and cannot be automatically
+  xmessage -bg "indian red" -center -title "SaveSession: ERROR" "Sorry, '$CDR' is currently mounted and cannot be automatically
 unmounted. You will need to unmount it manually.
 
 Click OK button to quit..."
diff --git a/woof-code/rootfs-skeleton/usr/sbin/snapmergepuppy b/woof-code/rootfs-skeleton/usr/sbin/snapmergepuppy
--- a/woof-code/rootfs-skeleton/usr/sbin/snapmergepuppy
+++ b/woof-code/rootfs-skeleton/usr/sbin/snapmergepuppy
@@ -16,23 +16,55 @@
 #w003 screened out some dirs in /dev that should not be saved.
 #v424 fix for more layers in unionfs/aufs.
 
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+trap "exit 1" HUP INT QUIT KILL TERM
+
+OUT=/dev/null;ERR=$OUT
+[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
+[ "$DEBUG" = "2" ] && set -x
+
+Version='1.1'
+
+usage(){
+USAGE_MSG="
+$0 [ PARAMETERS ]
+
+-V|--version : showing version information
+-H|--help : show this usage information
+
+*******  *******  *******  *******  *******  *******  *******  *******  *******
+$2
+"
+exit $1
+}
+
+[ "`echo "$1" | grep -wE "\-help|\-H"`" ] && usage 0
+[ "`echo "$1" | grep -wE "\-version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
 #variables created at bootup by 'init' script in initramfs...
 . /etc/rc.d/PUPSTATE
 . /etc/DISTRO_SPECS #v412
-SAVEPART="`echo -n "$PUPSAVE" | cut -f 1 -d ','`"
+SAVEPART=`echo -n "$PUPSAVE" | cut -f 1 -d ','`
 
 #v3.02 first time, do not use '-u' option when saving, save everything...
 NEXTPASSTHRU=""
 [ -e /tmp/flagnextpassthru ] && NEXTPASSTHRU="yes"
 
-RUNPS="`ps`"
+RUNPS=`ps`
 SHUTDOWN="no"
 XRUNNING="no"
 [ "`echo "$RUNPS" | grep 'rc.shutdown'`" != "" ] && SHUTDOWN="yes"
 [ "`echo "$RUNPS" | grep 'pup_event_frontend_d'`" != "" ] && XRUNNING="yes" #v4.01 v409
 
 PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin"
-WD="`pwd`"
+WD=`pwd`
+
+TTY=`tty`
+[ "$TTY" = 'unknown' -o "$TTY" = '?' ] && TTY=/dev/console
 
 SNAP="/initrd/pup_rw"
 cd $SNAP || exit 1
@@ -49,15 +81,15 @@ echo "Merging $SNAP onto $BASE..."
 find . -mount \( -regex '.*/\.wh\.[^/]*' -type f \) | sed -e 's/\.\///;s/\.wh\.//' |
 while read N
 do
- BN="`basename "$N"`"
- DN="`dirname "$N"`"
+ BN=`basename "$N"`
+ DN=`dirname "$N"`
  [ "$BN" = ".wh.aufs" ] && continue #w003 aufs has file .wh..wh.aufs in /initrd/pup_rw.
  [ "$DN" = "." ] && continue
  if [ "$BN" = "__dir_opaque" ];then #w003
   #'.wh.__dir_opaque' marks ignore all contents in lower layers...
-  rm -rf "${BASE}/${DN}/*" 2>/dev/null #wipe anything in save layer.
+  rm -rf "${BASE}/${DN}/*" 2>$ERR #wipe anything in save layer.
   #also need to save the whiteout file to block all lower layers (may be readonly)...
-  touch "${BASE}/${DN}/.wh.__dir_opaque" 2>/dev/null
+  touch "${BASE}/${DN}/.wh.__dir_opaque" 2>$ERR
   rm -f "$SNAP/$DN/.wh.__dir_opaque" #should force aufs layer "reval".
   continue
  fi
@@ -87,20 +119,66 @@ do
  [ "$XRUNNING" = "yes" ] && [ -f /tmp/wmexitmode.txt ] && exit
  mkdir -p "$BASE/$N"
  chmod "$BASE/$N" --reference="$N"
- OWNER="`stat --format=%U "$N"`"
+ OWNER=`stat --format=%U "$N"`
  chown $OWNER "$BASE/$N"
- GRP="`stat --format=%G "$N"`"
+ GRP=`stat --format=%G "$N"`
  chgrp $GRP "$BASE/$N"
  touch "$BASE/$N" --reference="$N"
-done 
+done
 
 #Copy Files... v409 remove '^var'. w003 screen out some /dev files.
-find . -mount -not \( -regex '.*/\.wh\.[^/]*' -type f \) -not -type d |  sed -e 's/\.\///' | grep -v -E '^mnt|^initrd|^proc|^sys|^tmp|^pup_|^zdrv_|^root/tmp|_zdrv_|^dev/\.|^dev/fd|^dev/pts|^dev/shm' | grep -v -E -i '\.thumbnails|trash|\.part$'  |
+#find . -mount -not \( -regex '.*/\.wh\.[^/]*' -type f \) -not -type d |  sed -e 's/\.\///' | grep -v -E '^mnt|^initrd|^proc|^sys|^tmp|^pup_|^zdrv_|^root/tmp|_zdrv_|^dev/\.|^dev/fd|^dev/pts|^dev/shm' | grep -v -E -i '\.thumbnails|trash|\.part$'  |
+#while read N
+#do
+
+FILES=`find . -mount -not \( -regex '.*/\.wh\.[^/]*' -type f \) -not -type d |  sed -e 's/^\.\///' | grep -v -E '^mnt|^initrd|^proc|^sys|^tmp|^pup_|^zdrv_|^root/tmp|_zdrv_|^dev/\.|^dev/fd|^dev/pts|^dev/shm' | grep -v -E -i '\.thumbnails|trash|\.part$' |sort -d`
+
+if [ "$DISPLAY" ]; then
+    yaf-splash -display :0 -font "8x16" -outline 0 -margin 4 -bg green -text "Calculating...
+Please wait ..." &
+else
+    echo -e "\\033[0;31m"'Calculating...'\
+"\nPlease wait ...\\033[0;39m" >$TTY
+fi
+
+SIZE_OLD=0
+#for file in $FILES; do  ##--- filename with spaces
+while read file
+do
+[ -d "$file" ] && continue
+SIZE=`ls -1 -s --block-size=K "$file" |awk -F 'K' '{print $1}'`; [ "$SIZE" ] || SIZE=0
+SIZE_ALL=$((SIZE_ALL+SIZE))
+[ "$SIZE" -ge "$SIZE_OLD" ] && { BIGGEST_SIZE=$SIZE;biggest_file="$file"; }
+SIZE_OLD=$SIZE;
+done<<EOI
+$(echo "$FILES")  ##+++ filename with spaces
+EOI
+
+kill -s HUP `jobs -p yaf-splash` >$OUT 2>$ERR
+
+FREEBASEK=`df -k | grep "$BASE" | tr -s ' ' | cut -f 4 -d ' '`
+
+if [ "$SIZE_ALL" -ge $((FREEBASEK-2048)) ] ; then
+    if [ "$DISPLAY" ]; then
+    yaf-splash -display :0 -timeout 9 -font "8x16" -outline 0 -margin 4 -bg red -text "WARNING!
+Unable to save all files. You need to delete or move some.
+The biggest file with ${BIGGEST_SIZE}KiB is
+$biggest_file" &
+    exit 1
+    else
+    echo -e "\\033[0;31m"'WARNING! Unable to save all files. Biggest is '\
+"\n$biggest_file with ${BIGGEST_SIZE}KiB\\033[0;39m" >$TTY
+    echo -e "Returning back into $TTY or X." >$TTY
+    sleep 2
+    killall poweroff 2>/dev/null || killall reboot
+    exit 1
+    fi
+fi
+
 while read N
 do
-
  #v4.01 graceful exit if shutdown X (see /usr/X11R7/bin/restartwm,wmreboot,wmpoweroff)...
- [ "$XRUNNING" = "yes" ] && [ -f /tmp/wmexitmode.txt ] && exit
+ [ "$XRUNNING" = "yes" ] && { [ -f /tmp/wmexitmode.txt ] && exit $?; }
 
  if [ "$SAVEPART" = "fd0" ];then
   #not much space, so screen out more files...
@@ -108,20 +186,20 @@ do
   [ "`echo -n "$N" | grep -v -E 'mozilla|printjobs|archive|cache'`" = "" ] && continue
  fi
 
- #stop saving if not enough room left in ${DISTRO_FILE_PREFIX}save file...
- FREEBASEK=`df -k | grep "$BASE" | tr -s ' ' | cut -f 4 -d ' '`
- FILESIZEB=`stat --format=%s "/${N}"`
- [ ! $FILESIZEB ] && break #w003 precaution.
- FILESIZEK=`expr $FILESIZEB \/ 1024`
- FILESIZEK=`expr $FILESIZEK + 200` #200K slack space.
- if [ $FILESIZEK -gt $FREEBASEK ];then
-  #also the taskbar freemem-applet lets the user know when low.
-  if [ "$SHUTDOWN" = "no" -a "$XRUNNING" = "yes" ];then
-   yaf-splash -display :0 -timeout 4 -font "8x16" -outline 0 -margin 4 -bg red -text "WARNING!
-Unable to save all files. You need to delete some." &
-  fi
-  break
- fi
+ ##stop saving if not enough room left in ${DISTRO_FILE_PREFIX}save file...
+ #FREEBASEK=`df -k | grep "$BASE" | tr -s ' ' | cut -f 4 -d ' '`
+ #FILESIZEB=`stat --format=%s "/${N}"`
+ #[ ! $FILESIZEB ] && break #w003 precaution.
+ #FILESIZEK=`expr $FILESIZEB \/ 1024`
+ #FILESIZEK=`expr $FILESIZEK + 200` #200K slack space.
+ #if [ $FILESIZEK -ge $FREEBASEK ];then
+  ##also the taskbar freemem-applet lets the user know when low.
+  #if [ "$SHUTDOWN" = "no" -a "$XRUNNING" = "yes" ];then
+   #yaf-splash -display :0 -timeout 4 -font "8x16" -outline 0 -margin 4 -bg red -text "WARNING!
+#Unable to save all files. You need to delete some." &
+  #fi
+  #break
+ #fi
 
  ##v2.21 -u causes trouble if timezone malconfigured...
  ##[ -L "$BASE/$N" ] && rm -f "$BASE/$N"
@@ -130,19 +208,21 @@ Unable to save all files. You need to delete some." &
  [ -L "$BASE/$N" ] && rm -f "$BASE/$N"
  if [ -L "$N" -o "$NEXTPASSTHRU" = "" ];then
   #link, or first run of snapmergepuppy. no '-u' (update) option.
-  cp -a -f "$N" "$BASE/$N"
+  cp -a --remove-destination "$N" "$BASE/$N"
  else
-  cp -a -u -f "$N" "$BASE/$N" #v3.02
+  cp -a -u --remove-destination "$N" "$BASE/$N" #v3.02
  fi
- 
+
  #if [ "$NEXTPASSTHRU" != "" ];then
  # cp -a -u -f "$N" "$BASE/$N"
  #else
  # cp -a -f "$N" "$BASE/$N" #no update option.
  #fi
  #flock -x -n "$N" -c rm -f "$N" #remove if file not in use
-
-done
+sleep 0.2
+done<<EOI
+$(echo "$FILES")
+EOI
 
 touch /tmp/flagnextpassthru
 
