/sbin/pup_event_backend_modprobe : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
--- a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
+++ b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
@@ -68,7 +68,7 @@
 # Xserver=/usr/X11R7/bin/Xvesa_stripped_upx9
 # $LANG=en_US
 # today=Mon·Oct·24·22:53:09·CEST·2011
-# TODO1 : modpobe -l | grep $MODULE : create a realName and lsmodName ~FIXED
+# TODO1 : modpobe -l | grep $MODULE : create a moduleNAME and lsmodNAME ~FIXED
 # TODO2 : if MODALIAS=platform:it87 does not work but it87 :: ~FIXED
 # TODO3 : check for ehci loaded before [uo]hci :: ~FIXED
 # TODO4 : debugging the firmware func ::~FIXED 2011-11-10 for pl2303 driver
@@ -136,25 +136,25 @@ touch /tmp/puppy_udev_helper_module_devpath.log
 
 setup_alsa_func() { #uses MODULE.
  #if a sound module, preconfigure alsa (/etc/init.d/alsa will start it)...
- if [ "`echo -n "$lsmodName" | grep '^snd_'`" != "" ];then
+ if [ "`echo -n "$lsmodNAME" | grep '^snd_'`" != "" ];then
   echo $$ 8.0 `$TIME` "calling setup_alsa_func" #>> $LocalLOG
   read CNTSND </tmp/puppy_udev_helper_alsa_cnt ||  CNTSND=0
   [ "$CNTSND" = 'noalsa' ] && return 1
   grepPATTERN="alias snd\\-card\\-$CNTSND"
-  #dMODULE=`echo -n "$lsmodName" | tr '_' '-'` #v407  ##+-+2011_10_26 dMODULE replaced by realName
+  #dMODULE=`echo -n "$lsmodNAME" | tr '_' '-'` #v407  ##+-+2011-10-26 dMODULE replaced by moduleNAME
   if [ "`grep "$grepPATTERN" "$ALSACONF"`" = "" ]; then
-  echo "Adding 'alias snd-card-$CNTSND $realName' to '$ALSACONF' because entry is missing." #>> $LocalLOG
+  echo "Adding 'alias snd-card-$CNTSND $moduleNAME' to '$ALSACONF' because entry is missing." #>> $LocalLOG
    echo >> "$ALSACONF"
    echo '##### Added by /sbin/puppy_udev_helper #####' >> "$ALSACONF"
    echo '### Running kernel '"$KERNEL_RELEASE" >> "$ALSACONF"
    echo '### Because alias entry is missing in this'  >> "$ALSACONF"
    echo '### Configuration-file '"$CONFFILE" >> "$ALSACONF"
-   echo "alias snd-card-$CNTSND $realName" >> "$ALSACONF"
-   echo "alias sound-slot-$CNTSND $realName" >> "$ALSACONF"
+   echo "alias snd-card-$CNTSND $moduleNAME" >> "$ALSACONF"
+   echo "alias sound-slot-$CNTSND $moduleNAME" >> "$ALSACONF"
    echo '##### '`date`' #####' >> "$ALSACONF"
   else
    #for portability, check if correct sound card...
-   grepPATTERN2="alias snd\\-card\\-$CNTSND $realNameGrepPattern" #v408
+   grepPATTERN2="alias snd\\-card\\-$CNTSND $moduleNAMEGrepPattern" #v408
    if [ "`grep "$grepPATTERN2" "$CONFFILE"`" = "" ];then
    echo 'Creating new /tmp/modprobe.conf file because of '"$grepPATTERN2"' had changed' #>> $LocalLOG
     grep -v "$grepPATTERN" "$CONFFILE" > /tmp/modprobe.conf  ##leaves sound-slot-nr in modprobe.conf
@@ -164,8 +164,8 @@ setup_alsa_func() { #uses MODULE.
     echo '### Running kernel '"$KERNEL_RELEASE" >> "$CONFFILE"
     echo '### Because modulename or harware had changed' >> "$CONFFILE"
     echo '### Configuration-file is '"$CONFFILE" >> "$CONFFILE"
-    echo "alias snd-card-$CNTSND $realName" >> "$CONFFILE"
-    echo "alias sound-slot-$CNTSND $realName" >> "$CONFFILE"
+    echo "alias snd-card-$CNTSND $moduleNAME" >> "$CONFFILE"
+    echo "alias sound-slot-$CNTSND $moduleNAME" >> "$CONFFILE"
     echo '##### '`date`' #####' >> "$CONFFILE"
    fi
   fi
@@ -188,27 +188,27 @@ pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
  REPLACEMENT=`echo "$PCI_OVERRIDES" | grep "$grepPATTERN"`
  #w463 replace only if not already forced by udev rule...
  #[ "$REPLACEMENT" != "" ] && MODULE="$REPLACEMENT"
- [ "$REPLACEMENT" != "" ] && [ "$RULEMODULE" = "" ] && lsmodName=`echo "$REPLACEMENT" | cut -f 1 -d ' '`
+ [ "$REPLACEMENT" != "" ] && [ "$RULEMODULE" = "" ] && lsmodNAME=`echo "$REPLACEMENT" | cut -f 1 -d ' '`
  #######END MODULESCONFIG OVERRIDES#######
  ######HACKS SECTION#######
  #in some cases a special hack is required, hardcoded in here...
  #8139cp is buggy...
- [ "$lsmodName" = "8139cp" ] && lsmodName="8139too"
+ [ "$lsmodNAME" = "8139cp" ] && lsmodNAME="8139too"
  #v2.17 another hack, mwave.ko (modem), do not load module, just the firmware,
  #as /etc/init.d/ in firmware has script that correctly loads mwave.ko...
- if [ "$lsmodName" = "mwave" ];then
+ if [ "$lsmodNAME" = "mwave" ];then
   firmware_module_func #modprobe -n mwave #pretend load.
   return 1
  fi
  #v2.17 intel pci numbering is peculiar, need this hack....
- if [ "$lsmodName" = "ipw2200" ];then
-  [ "`/sbin/lspci -m -n -d 8086:1043 | cut -f 10 -d '"' | cut -b 1,2`" = "25" ] && lsmodName="ipw2100" #'geany
+ if [ "$lsmodNAME" = "ipw2200" ];then
+  [ "`/sbin/lspci -m -n -d 8086:1043 | cut -f 10 -d '"' | cut -b 1,2`" = "25" ] && lsmodNAME="ipw2100" #'geany
  fi
  #v408 pup 4.1retro, k2.6.21.7, madwifi wireless, ath_pci.ko loads then
  #my pcmcia and sd-card no longer work -- no uevents from kernel. yet, if
  #I blacklist ath_pci then load it later, all is ok. So, perhaps ath_pci
  #is grabbing control of too much hardware? try a delay...
- [ "$lsmodName" = "ath_pci" ] && sleep 5
+ [ "$lsmodNAME" = "ath_pci" ] && sleep 5
  #######END HACKS SECTION#######
  return 0
 }
@@ -216,8 +216,8 @@ pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
 firmware_module_func() {
  echo $$ 7.0 `$TIME` "starting firmware_module_func ..." #>> $LocalLOG
  #global MODULE is name of module, global KERNEL_RELEASE.
- altMODULE=`echo -n "$lsmodName" | tr '_' '-'`
- FPATTERN='[:,]'"${lsmodName}"'\.ko|[:,]'"${altMODULE}"'\.ko'
+ altMODULE=`echo -n "$lsmodNAME" | tr '_' '-'`
+ FPATTERN='[:,]'"${lsmodNAME}"'\.ko|[:,]'"${altMODULE}"'\.ko'
 
  FIRMPKG=`cat /etc/modules/firmware.dep.$KERNEL_RELEASE | grep -v '^#' | grep ':' | grep -E "$FPATTERN" | cut -f 1 -d ':' | head -n 1`
 
@@ -283,60 +283,60 @@ echo $$ 2.0 `$TIME` "MODALIAS='$MODALIAS'" #>> $LocalLOG
 #find a matching module... (/etc/pup_event_modprobe.conf created in rc.sysinit)
 #MODULES=`/sbin/modprobe --config /tmp/pup_event_skiplist.conf --show-depends $MODALIAS 2>$ERR | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.'` #v424  ##+-2011_10_26 rm tr - _
 MODULES=`/sbin/modprobe --config /tmp/puppy_udev_helper_modprobe.conf --show-depends $MODALIAS 2>$ERR | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.'`
-realName=`echo "$MODULES" | tail -n 1` #v424
-lsmodName=`echo "$realName" | tr '\-' '_'`  ##+++2011_20_26
+moduleNAME=`echo "$MODULES" | tail -n 1` #v424
+lsmodNAME=`echo "$moduleNAME" | tr '\-' '_'`  ##+++2011-10-26
 #[ "$MODULE" = "usb_storage" ] && [ "`echo "$MODULES" | grep '^usbserial$'`" != "" ] && MODULE=`echo "$MODULES" | grep -v -E '^usb_storage$|^usbcore$' | tail -n 1` #v424
-echo $$ 3.0 `$TIME` "lsmodName='$lsmodName'" #>> $LocalLOG
+echo $$ 3.0 `$TIME` "lsmodNAME='$lsmodNAME'" #>> $LocalLOG
 
-if [ -z "$realName" ] ; then  ##+++2011_20_26
+if [ -z "$moduleNAME" ] ; then  ##+++2011-10-26
 MODALIAS2="${MODALIAS#*\:}"  ##deletes preceding pci: or platform:
 #MODULES=`/sbin/modprobe --config /tmp/pup_event_skiplist.conf --show-depends $MODALIAS2 2>$ERR | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.'`
 MODULES=`/sbin/modprobe --config /tmp/puppy_udev_helper_modprobe.conf --show-depends $MODALIAS2 2>$ERR | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.'`
-realName=`echo "$MODULES" | tail -n 1` #v424
-lsmodName=`echo "$realName" | tr '\-' '_'`
-fi  ##+++2011_20_26
+moduleNAME=`echo "$MODULES" | tail -n 1` #v424
+lsmodNAME=`echo "$moduleNAME" | tr '\-' '_'`
+fi  ##+++2011-10-26
 
-[ "$lsmodName" = "" -a "$RULEMODULE" != "" ] && lsmodName="$RULEMODULE" #w463 Use module from argument
+[ "$lsmodNAME" = "" -a "$RULEMODULE" != "" ] && lsmodNAME="$RULEMODULE" #w463 Use module from argument
 
-[ "$lsmodName" = "" ] && { echo $$ 3.5 `$TIME` 'Still no lsmodName . Exit.'; exit 1; }
-[ "$lsmodName" = "usb_storage" ] && { echo $$ 3.6 `$TIME` "'$lsmodName' omitted by '$0'"; exit 1; } #loaded explicitly in boot scripts.
+[ "$lsmodNAME" ] || { echo $$ 3.5 `$TIME` 'Still no lsmodNAME . Exit.'; exit 1; }
+[ "$lsmodNAME" = "usb_storage" ] && { echo $$ 3.6 `$TIME` "'$lsmodNAME' omitted by '$0'"; exit 1; } #loaded explicitly in boot scripts.
 
 ###<2011-11-10>
-#if [ -n "`echo "$lsmodName" | grep '[ou]hci_hcd'`" ] ; then
-if [ "$lsmodName" = 'ohci_hcd' -o "$lsmodName" = 'uhci_hcd' ]; then
-if [ -z "`lsmod | grep 'ehci_hcd'`" ] ; then
+#if [ -n "`echo "$lsmodNAME" | grep '[ou]hci_hcd'`" ] ; then
+if [ "$lsmodNAME" = 'ohci_hcd' -o "$lsmodNAME" = 'uhci_hcd' ]; then
+if [ -z "`grep 'ehci_hcd' /proc/modules`" ] ; then
 if [ -n "`elspci -l | grep -w '0C0320'`" ]; then
-echo $$ 3.7 `$TIME` "'$lsmodName' detected AND port:ehci-hcd but ehci-hcd not loaded yet." #>> $LocalLOG
+echo $$ 3.7 `$TIME` "'$lsmodNAME' detected AND port:ehci-hcd but ehci-hcd not loaded yet." #>> $LocalLOG
 MODALIAS='' $0 "ehci-hcd"
 sleep 1s;c=0
-while [ -z "`lsmod | grep 'ehci_hcd'`" ]; do
+while [ -z "`grep 'ehci_hcd' /proc/modules`" ]; do
 c=$((c+1))
 sleep 1s
 [ "$c" == 10 ] && break
 done
-if [ -z "`lsmod | grep 'ehci_hcd'`" ] ; then
-echo $$ 3.8 `$TIME` "MODULE ehci-hcd still not loaded yet. Continuing loading '$lsmodName' anyway." #>> $LocalLog
+if [ -z "`grep 'ehci_hcd' /proc/modules`" ] ; then
+echo $$ 3.8 `$TIME` "MODULE ehci-hcd still not loaded yet. Continuing loading '$lsmodNAME' anyway." #>> $LocalLog
 else
-echo $$ 3.8 `$TIME` "MODULE ehci-hcd loaded. Continuing loading '$lsmodName'" #>> $LocalLog
+echo $$ 3.8 `$TIME` "MODULE ehci-hcd loaded. Continuing loading '$lsmodNAME'" #>> $LocalLog
 fi
 fi
 fi
 fi
 ###</2011-11-10>
 
-realNameGrepPattern="${realName//-/\\-}"     ##+++2011-10-26
-realNameGrepPattern2="${realName//-/\\\\-}"  ##+++2011-10-26 for setup_alsa_func #2011-10-27 :alias snd\-card\-0 snd\\-wavefront not as wanted , changed to $realNameGrepPattern
-[ -z "`modprobe -l | grep "$realNameGrepPattern"`" ] && { echo $$ 3.5 `$TIME` "cannot find '$realName' in modprobe -l"; exit 2; }
-lsmodNameGrepPattern='^'"${lsmodName}"'$'
-echo $$ 4.0 `$TIME` "modPATTERN 1 ='$lsmodNameGrepPattern'" #>> $LocalLOG
+moduleNAMEGrepPattern="${moduleNAME//-/\\-}"     ##+++2011-10-26
+moduleNAMEGrepPattern2="${moduleNAME//-/\\\\-}"  ##+++2011-10-26 for setup_alsa_func #2011-10-27 :alias snd\-card\-0 snd\\-wavefront not as wanted , changed to $moduleNAMEGrepPattern
+[ -z "`modprobe -l | grep "$moduleNAMEGrepPattern"`" ] && { echo $$ 3.5 `$TIME` "cannot find '$moduleNAME' in modprobe -l"; exit 2; }
+lsmodNAMEGrepPattern='^'"${lsmodNAME}"'$'
+echo $$ 4.0 `$TIME` "modPATTERN 1 ='$lsmodNAMEGrepPattern'" #>> $LocalLOG
 
 #[ "`cat /tmp/pup_event_module_devpath.log | cut -f 1 -d ' ' | cut -f 2 -d '=' | grep "$modPATTERN"`" != "" ] && echo 'Duplicate module ..exit ..' >> $LocalLOG && exit 0 #duplicate module.
-if [ "`grep "$lsmodNameGrepPattern" /tmp/puppy_udev_helper_module_devpath.log | cut -f 1 -d ' ' | cut -f 2 -d '='`" ] ; then
-FM=`find /dev/.udev/failed | grep "$lsmodNameGrepPattern"`
+if [ "`grep "$lsmodNAMEGrepPattern" /tmp/puppy_udev_helper_module_devpath.log | cut -f 1 -d ' ' | cut -f 2 -d '='`" ] ; then
+FM=`find /dev/.udev/failed | grep "$lsmodNAMEGrepPattern"`
 if [ -z "$FM" ] ; then
 echo $$ 4.5 `$TIME` 'Duplicate module. Exit.'; exit 0 #duplicate module.
 else
-echo -e $$ 4.5 `$TIME` "udevd seems to have failed already loading '$lsmodNameGrepPattern'" #>> $LocalLOG
+echo -e $$ 4.5 `$TIME` "udevd seems to have failed already loading '$lsmodNAMEGrepPattern'" #>> $LocalLOG
 fi
 fi
 
@@ -349,17 +349,17 @@ case $MODALIAS in
 esac
 
 #v404 preferences list, ex rt2500usb and rt73usb both hits, then choose latter...
-modPATTERN='^'"$lsmodName"':'
+modPATTERN='^'"$lsmodNAME"':'
 echo $$ 6.0 `$TIME` "modPATTERN 2 ='$modPATTERN'" #>> $LocalLOG
 PREFHIT=`echo -n "$PREFLIST" | tr ' ' '\n' | grep "$modPATTERN"`
 echo $$ 6.1 `$TIME` "PREFHIT='$PREFHIT'" #>> $LocalLOG
 
-if [ "$PREFHIT" != "" ];then
+if [ "$PREFHIT" ]; then
  PREFMOD=`echo -n "$PREFHIT" | cut -f 2 -d ':'`
- echo "blacklist $lsmodName" > /tmp/puppy_udev_helper_prefhit_blacklist.conf
+ echo "blacklist $lsmodNAME" > /tmp/puppy_udev_helper_prefhit_blacklist.conf
  replaceMODULE=`/sbin/modprobe --config /tmp/puppy_udev_helper_prefhit_blacklist.conf --show-depends $MODALIAS 2>$ERR | tail -n 1 | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`
- [ "$replaceMODULE" -a "$replaceMODULE" != "$lsmodName" ] && lsmodName="$replaceMODULE"
- echo $$ 6.5 `$TIME` "lsmodName='$lsmodName'" #>> $LocalLOG
+ [ "$replaceMODULE" -a "$replaceMODULE" != "$lsmodNAME" ] && lsmodNAME="$replaceMODULE"
+ echo $$ 6.5 `$TIME` "lsmodNAME='$lsmodNAME'" #>> $LocalLOG
 fi
 
 #installs a firmware tarball (once only. loading firmware is something else)...
@@ -370,12 +370,12 @@ setup_alsa_func #MODULE and CNTSND are used in this func.
 usleep $(( $$ * 10 ))
 #log to file. rc.modules2 needs this info to find out if any modaliases missed (also above)...
 cd /sbin #v408 rerwin thinks this is needed for slamr module.
-if [ -z "`lsmod | grep "$lsmodName"`" ] ; then
-echo "MODULE=$lsmodName DEVPATH=$DEVPATH" >> /tmp/puppy_udev_helper_module_devpath.log
-echo -e $$ 9.0 `$TIME` "Finally modprobing '$lsmodName'" #>> $LocalLOG
- exec /sbin/modprobe -vb $lsmodName
+if [ -z "`grep -w "$lsmodNAME" /proc/modules`" ]; then
+echo "MODULE=$lsmodNAME DEVPATH=$DEVPATH" >> /tmp/puppy_udev_helper_module_devpath.log
+echo -ne $$ 9.0 `$TIME` "Finally modprobing '$lsmodNAME' " #>> $LocalLOG
+ exec /sbin/modprobe -vb $lsmodNAME
 else
-echo -e $$ 9.0 `$TIME` "lsmodName '$lsmodName' already loaded." #>> $LocalLOG
+echo -e $$ 9.0 `$TIME` "lsmodNAME '$lsmodNAME' already loaded." #>> $LocalLOG
 fi
 ###END###
 exit
