/sbin/pup_event_backend_modprobe : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
--- a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
+++ b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
@@ -8,22 +8,22 @@ _COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"
 MY_SELF="/sbin/pup_event_backend_modprobe"
 MY_PID=$$
 
-test -f /etc/rc.d/f4puppy5 && {
-[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5
-
-ADD_PARAMETER_LIST=""
-ADD_PARAMETERS=""
-_provide_basic_parameters
-
-TWO_HELP=1
-ADD_HELP_MSG="$_COMMENT_"
-_parse_basic_parameters "$@"
-[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
-  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
-
-_trap
-
-}
+#test -f /etc/rc.d/f4puppy5 && {
+#[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5
+#
+#ADD_PARAMETER_LIST=""
+#ADD_PARAMETERS=""
+#_provide_basic_parameters
+#
+#TWO_HELP=1
+#ADD_HELP_MSG="$_COMMENT_"
+#_parse_basic_parameters "$@"
+#[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+#  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
+#
+#_trap
+#
+#}
 # End new header
 #
 #(c) Copyright 2008 Barry Kauler puppylinux.com
@@ -97,12 +97,12 @@ _trap
 PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin"
 
 LocalLOG='/tmp/pup_event_backend_modprobe.log'
-out="$LocalLOG";err="$LocalLOG"
+OUT="$LocalLOG";ERR="$LocalLOG"
 #echo LocalLOG="$LocalLOG"_EOS
 
 debug(){
 #echo "$@"
-echo "$@" >> $out #2>>$err
+echo "$@" >> $OUT #2>>$ERR
 [ "$do" ] && echo "$@"
 [ "$dx" ] && echo "$@" >>/dev/console
 return 0  ##force returnvalue in case of following && [TEST]
@@ -191,24 +191,26 @@ fi
 #[ "$MODULE" = "usb_storage" ] && exit 1 #loaded explicitly in boot scripts.
 
 touch /tmp/pup_event_module_devpath.log
-if [ "`grep 'pup_event_backend_modprobe_protect \-\-module' $0`" ]; then
-ps -o pid,args | grep pup_event_backend_modprobe_protect | grep $Q -e --daemon || {
-exec pup_event_backend_modprobe_protect --daemon >>$out 2>>$err &
+if [ "`grep -e 'pup_event_backend_modprobe_protect --module' "$0"`" ]; then
+ps -o pid,args | grep pup_event_backend_modprobe_protect | grep $Q -e '--daemon' || {
+exec pup_event_backend_modprobe_protect --daemon >>$OUT 2>>$ERR & dPID=$!
+echo "NEED to trigger pup_event_backend_modprobe_protect --daemon with $dPID" >>$LocalLOG
 sleep 2
 START_PROTECT_DAEMON=1
 }
 fi
+
 #echo 06
 #v432 Ensure module procesing done only once, except for usb-storage (needed to find hybrid-device co-driver).
 #[ "$MODULE" != "usb_storage" ] \
  #&& ! pup_event_backend_modprobe_protect --module=$MODULE \
- #|| echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned errornoise" $LocalLOG && exit 0
- ##|| echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned errornoise" $LocalLOG \
+ #|| echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned ERRornoise" $LocalLOG && exit 0
+ ##|| echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned ERRornoise" $LocalLOG \
  ##&& exit 0
- ##&& echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned errornoise" $LocalLOG #\#
+ ##&& echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned ERRornoise" $LocalLOG #\#
 
 if [ "$MODULE" != "usb_storage" ] ; then
-pup_event_backend_modprobe_protect --module=$MODULE >>$out 2>>$err
+timeout -t10 /sbin/pup_event_backend_modprobe_protect --module=$MODULE >>$OUT 2>>$ERR
 retVal=$?
 if [ "$retVal" -ne 0 ] ; then
 debug "$(echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned $retVal")"
@@ -222,7 +224,7 @@ KERNVER=`uname -r`
 
 CONFFILE='/etc/modprobe.conf'
 [ -f /etc/modprobe.d/modprobe.conf ] && CONFFILE='/etc/modprobe.d/modprobe.conf'
-[ -f /etc/modprobe.d/puppy.conf ]     && CONFFILE='/etc/modprobe.d/puppy.conf'
+[ -f /etc/modprobe.d/puppy.conf ]    && CONFFILE='/etc/modprobe.d/puppy.conf'
 ALSACONF="$CONFFILE"
 [ -f /etc/modprobe.d/alsa-base.conf ] && ALSACONF='/etc/modprobe.d/alsa-base.conf'
 #echo 08
@@ -234,13 +236,13 @@ setup_alsa_func() { #uses MODULE.
  case $MODULE in snd_*) :;; *) return 0;; esac
 
   CNTSND=0 #v432 Reserve first available card number
-  while ! pup_event_backend_modprobe_protect --snd_card_number=$CNTSND >>$out 2>>$err;do
+  while ! timeout -t10 /sbin/pup_event_backend_modprobe_protect --snd_card_number=$CNTSND >>$OUT 2>>$ERR;do
    CNTSND=$(( CNTSND + 1 ))
-   [ $CNTSND -gt 10 ] && return 1
+   [ "$CNTSND" -gt 10 ] && return 1
   done
   echo CNTSND=$CNTSND
 
-  pup_event_backend_modprobe_protect --lock=modprobeconf >>$out 2>>$err #v432 end
+  timeout -t10 /sbin/pup_event_backend_modprobe_protect --lock=modprobeconf >>$OUT 2>>$ERR #v432 end
 
   DPATTERN="alias snd\\-card\\-$CNTSND"
   dMODULE="`echo -n "$MODULE" | tr '_' '-'`" #v407
@@ -284,7 +286,7 @@ setup_alsa_func() { #uses MODULE.
     echo '##### '"$DateS"' #####' >> $CONFFILE
    fi
   fi
-  pup_event_backend_modprobe_protect --unlock=modprobeconf >>$out 2>>$err #v432
+  timeout -t10 /sbin/pup_event_backend_modprobe_protect --unlock=modprobeconf >>$OUT 2>>$ERR #v432
  #fi
 }
 #echo 09
@@ -316,7 +318,7 @@ pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
  #8139cp is buggy...
  if [ "$MODULE" = "8139cp" ];then
   MODULE="8139too"
-  if ! pup_event_backend_modprobe_protect --module=$MODULE >>$out 2>>$err;then
+  if ! pup_event_backend_modprobe_protect --module=$MODULE >>$OUT 2>>$ERR;then
   return 1 #v432
   fi
  fi
@@ -332,7 +334,7 @@ pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
  if [ "$MODULE" = "ipw2200" ];then
   if [ "`lspci -m -n -d 8086:1043 | cut -f 10 -d '"' | cut -b 1,2`" = "25" ];then #'geany #v432
   MODULE="ipw2100"
-   if ! pup_event_backend_modprobe_protect --module=$MODULE >>$out 2>>$err ;then
+   if ! pup_event_backend_modprobe_protect --module=$MODULE >>$OUT 2>>$ERR ;then
     return 1
    fi
   fi
@@ -365,30 +367,30 @@ firmware_module_func() {
  fi #v433 end
  if [ "$FIRMPKG" != "" ];then
   #v432 Ensure firmware installed only once.
-  pup_event_backend_modprobe_protect --firmware=$FIRMPKG || return 0
+  timeout -t10 /sbin/pup_event_backend_modprobe_protect --firmware=$FIRMPKG || return 0
 
   if [ -f /lib/modules/all-firmware/${FIRMPKG}.tar.gz ];then
-   cp $VERB -af /lib/modules/all-firmware/${FIRMPKG}.tar.gz /tmp >>$out 2>&1
+   cp $VERB -af /lib/modules/all-firmware/${FIRMPKG}.tar.gz /tmp >>$OUT 2>&1
    cd /tmp
-   tar -zxf ${FIRMPKG}.tar.gz >>$out 2>&1
+   tar -zxf ${FIRMPKG}.tar.gz >>$OUT 2>&1
   fi
 
-  if [ -d /tmp/${FIRMPKG} ];then
-   /bin/cp $VERB -a --remove-destination /tmp/${FIRMPKG}/* / 2>>$err
+  if [ -d /tmp/"${FIRMPKG}" ];then
+   /bin/cp $VERB -a --remove-destination /tmp/${FIRMPKG}/* / 2>>$ERR
   fi
   #in case firmware is not a .tar.gz tarball...
 
-  if [ -d /lib/modules/all-firmware/${FIRMPKG} ];then #w478
-   /bin/cp $VEBR -a --remove-destination /lib/modules/all-firmware/${FIRMPKG}/* / 2>>$err
+  if [ -d /lib/modules/all-firmware/"${FIRMPKG}" ];then #w478
+   /bin/cp $VEBR -a --remove-destination /lib/modules/all-firmware/${FIRMPKG}/* / 2>>$ERR
   fi
 
-  if [ -f /pinstall.${FIRMPKG}.sh ];then
+  if [ -f /pinstall."${FIRMPKG}".sh ];then
    cd /
-   /pinstall.${FIRMPKG}.sh >>$out 2>&1 #execute script.
-   #rm -f /pinstall.${FIRMPKG}.sh >>$out 2>&1
+   /pinstall.${FIRMPKG}.sh >>$OUT 2>&1 #execute script.
+   #rm -f /pinstall.${FIRMPKG}.sh >>$OUT 2>&1
    chmod $VERB 0444 /pinstall.${FIRMPKG}.sh
   fi
-  pup_event_backend_modprobe_protect --fwdone
+  timeout -t10 /sbin/pup_event_backend_modprobe_protect --fwdone
 
  fi
 }
@@ -425,7 +427,7 @@ if [ "$PREFHIT" != "" ];then
  echo "blacklist $MODULE" > /tmp/pup_event_prefhit_blacklist-$$ #v432 begin
 
  RETRIES=0
- while [ $RETRIES -le 10 ];do
+ while [ "$RETRIES" -le 10 ];do
   xMODULE="`/sbin/modprobe --config /tmp/pup_event_prefhit_blacklist-$$ --show-depends $MODALIAS 2>/dev/null | tail -n 1 | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`"
   debug "$(echo $$ 8.1 `$TIME` "xMODULE='$xMODULE'")"
   debug "$(echo $$ 8.1 `$TIME` "RETIES='$RETRIES'")"
@@ -444,10 +446,10 @@ if [ "$PREFHIT" != "" ];then
 
   if [ "$xMODULE" != "" -a "$xMODULE" != "$MODULE" ] ; then
 
- pup_event_backend_modprobe_protect --replacedmod=$MODULE >>$out 2>>$err
+ timeout -t10 /sbin/pup_event_backend_modprobe_protect --replacedmod=$MODULE >>$OUT 2>>$ERR
  MODULE="$xMODULE"
    debug "$(echo $$ 8.3 `$TIME` "MODULE='$MODULE'")"
-    if pup_event_backend_modprobe_protect --module=$MODULE ; then
+    if timeout -t10 /sbin/pup_event_backend_modprobe_protect --module=$MODULE ; then
     #echo $$ 8.3.5 `$TIME` "pup_event_backend_modprobe_protect returned errornoise '0?'" $LocalLOG
     #exit 0 #v433 v432 end
     debug "$(echo $$ 8.3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE'")"
@@ -466,9 +468,9 @@ firmware_module_func
 
 setup_alsa_func #MODULE and CNTSND are used in this func.
 
-[ "$START_PROTECT_DAEMON" ] && pup_event_backend_modprobe_protect --stop >>$out 2>>$err &
+[ "$START_PROTECT_DAEMON" ] && timeout -t10 /sbin/pup_event_backend_modprobe_protect --stop >>$OUT 2>>$ERR &
 
-sed -i "s|^\(DBG .*\)|$$ 8\.9 \1|" $out
+sed -i'.sed' "s|^\(DBG .*\)|$$ 8\.9 \1|" $OUT
 #echo 5
 if [ -z "`lsmod | grep "$MODULE"`" ] ; then
 #log to file. rc.modules2 needs this info to find out if any modaliases missed (also above)...
@@ -477,10 +479,10 @@ debug "$(echo -e $$ 9.0 `$TIME` "\e[32m"'Finally modprobing '"$MODULE""\e[39m")"
 debug "$(echo $$ 0.0.8 `$TIME` `cat /proc/loadavg` )"
 debug "$(echo $$ 9.1 `$TIME` `cat /proc/loadavg` )"
 cd /sbin #v408 rerwin thinks this is needed for slamr module.
- #exec /sbin/modprobe -v $MODULE 1>>$out 2>&1
- /sbin/modprobe -v -b $MODULE 1>>$out 2>&1
-  sed -i "s|^\(insmod .*\)|$$ 9\.9 \1|" $out
-  sed -i "s|^\(install .*\)|$$ 9\.9 \1|" $out
+ #exec /sbin/modprobe -v $MODULE 1>>$OUT 2>&1
+ /sbin/modprobe $Q $VERB -b $MODULE 1>>$OUT 2>&1
+  sed -i'.sed' "s|^\(insmod .*\)|$$ 9\.9 \1|" $OUT
+  sed -i'.sed' "s|^\(install .*\)|$$ 9\.9 \1|" $OUT
   exit 0
 else
 
