/sbin/pup_event_frontend_d: Code cleanup. Added a cd /tmp before daemon loop. This probably will go further to set a user id for pup_event_frontend_d and a home directory, probably /var/local/Puppy/pup_event with a tmpfs mount at /var/local/Puppy/pup_event/tmp .

diff --git a/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d b/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
--- a/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
+++ b/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
@@ -103,24 +103,24 @@ get_lineno(){  #workaround to grep line number in ash script since ash has no LI
     echo 'UNKNOWN'
     fi
 }
-_get_home_var(){
-#KRG
-test "$HOME" = '/' && export HOME=/root
-}
-_get_home_var
+
+#_get_home_var(){
+#test "$HOME" = '/' && export HOME=/root
+#}
+#_get_home_var
 
 ########### check program ##############
 ###++2012-01-21
 programname='/sbin/pup_event_frontend_d'
 if [ "$0" != "$programname" ];then
 if [ ! -f "$programname" ];then
-echo "ERROR : `basename $programname` should be installed into /sbin
-exiting now "
+echo "ERROR : `basename $programname` should be installed into /sbin .
+Exiting now."
 #define ENOENT       2  /* No such file or directory */
 return 2 || exit 2
 else
 echo "ERROR : $programname is not $0 ..
-Maybe sourced ?? exiting ."
+Maybe sourced ?? Exiting."
 #define EPERM        1  /* Operation not permitted */
 return 1 || exit 1
 fi;fi
@@ -144,11 +144,9 @@ fi;fi
 [ "$POLL_ZIPCDROM" -le 9 ]    || POLL_ZIPCDROM=9
 #POLL_REMOVABLE=3   # seconds to poll for CD/Floppy insertitons ZCDPOLL=true
 
-#TOGGLE=1
 SAVECNT=0
 MOUSECNT=0  #w007
 MINUTECNT=0 #w007
-#CURPOS1="" #w007
 CURRPOS1='-1 -1' ##+++2012-01-18 moved here for not testing it inside DAEMON all the time
 
 ZDRV='';ZDRVINIT='no' #these usually set in PUPSTATE.
@@ -160,7 +158,7 @@ test -f "$CONFFILE" && . "$CONFFILE" #has RAMSAVEINTERVAL, ICONDESK, HOTPLUGNOIS
 SIZE_MODS_MB=0
 if [ "$ZDRVINIT" = "yes" ];then
  #all mods were in initrd at bootup, then moved to main f.s.
- SIZE_MODS_MB=`du -m -s /lib/modules | cut -f 1`
+ SIZE_MODS_MB=`du -m -s /lib/modules/`uname -r` | cut -f 1`
 fi
 RETVALm=1
 PREVSIZETMPM=0
@@ -293,7 +291,7 @@ _stop_frontends(){
  _debug "\$\$='$$'"
  MY_PIDS=`pidof -o $$ -o %PPID ${0##*/}`
  for aPID in $MY_PIDS; do
- [ $aPID = 1 ] && continue
+ [ "$aPID" = 1 ] && continue
  c=$((c+1))
  kill -15 $aPID # needs 15 to kill functions in ash
  done
@@ -410,7 +408,7 @@ DELAYFACTOR=0
 #CPUMHZ=`grep -m 1 -i '^cpu MHz' /proc/cpuinfo | tr -d ' ' | cut -f 2 -d ':' | cut -f 1 -d '.'`
  CPUMHZ=`grep -m 1 -i '^cpu MHz' /proc/cpuinfo | tr -d '[:blank:]' | cut -f 2 -d ':' | cut -f 1 -d '.'`
  [ "$CPUMHZ" -a $CPUMHZ -gt 100 ] && DELAYFACTOR=$(( 1100 / CPUMHZ ))
- [ $DELAYFACTOR -gt 0 ] && sleep $DELAYFACTOR
+ [ "$DELAYFACTOR" -gt 0 ] && sleep $DELAYFACTOR
 fi
 
 ################# ORIG ######################################
@@ -476,8 +474,8 @@ _free(){  # _free_savefile _free_rootfs
  WARNMSG=""
  [ "$SIZEFREESAVE_MB" ] || WARNMSG="Could not determine free space using df plus filters"
  [ -s /tmp/pup_event_sizefreem ] && read PREVSIZEFREEM </tmp/pup_event_sizefreem
- [ $PREVSIZEFREEM -eq $SIZEFREESAVE_MB ] && return
- if [ $SIZEFREESAVE_MB -lt 10 ];then
+ [ "$PREVSIZEFREEM" -eq $SIZEFREESAVE_MB ] && return
+ if [ "$SIZEFREESAVE_MB" -lt 10 ];then
   WARNMSG="$WARNMSG
    WARNING: Personal storage getting full, strongly recommend you resize it or delete files!"
   if [ -d /initrd/pup_rw/lib/modules/all-firmware -a "$ZDRVINIT" = "yes" ];then
@@ -512,7 +510,7 @@ _free(){  # _free_savefile _free_rootfs
 
  #save to a file, freememapplet can read this...
  echo "$VIRTUALFREEM" >/tmp/pup_event_sizefreem
- #[ $PUPMODE -eq 5 -o $PUPMODE -eq 2 ] && return 0 #5=first boot, no msgs at top of screen. 2=full install
+ #[ "$PUPMODE" -eq 5 -o "$PUPMODE" -eq 2 ] && return 0 #5=first boot, no msgs at top of screen. 2=full install
 
 }
 
@@ -533,7 +531,7 @@ Could not determine free space in /tmp layer"
  [ -s /tmp/pup_event_sizetmpm ]  && read PREVSIZETMPM  </tmp/pup_event_sizetmpm
  [ "$PREVSIZEFREEM" = $SIZEFREESAVE_MB -a "$PREVSIZETMPM" = $SIZEFREETMP_MB ] && return
 
- if [ $SIZEFREESAVE_MB -lt 10 ]; then
+ if [ "$SIZEFREESAVE_MB" -lt 10 ]; then
   WARNMSG="$WARNMSG
    WARNING: Personal storage file getting full, strongly recommend you resize it and reboot or delete files!"
   if [ -d /initrd/pup_ro1/lib/modules/all-firmware -a "$ZDRVINIT" = "yes" ];then
@@ -550,14 +548,14 @@ Could not determine free space in /tmp layer"
  fi
 
  # REM: try freeing ^unused^ RAM
- if [ $SIZEFREETMP_MB -lt 5 ]; then
+ if [ "$SIZEFREETMP_MB" -lt 5 ]; then
   echo '3' >/proc/sys/vm/drop_caches && {
   sleep 2;
   SIZEFREETMP_MB=`/bin/df -m | awk '{if ($NF == "/initrd/pup_rw") print $4}' | tail -n1`
   }
  fi
 
- if [ $SIZEFREETMP_MB -lt 5 ]; then
+ if [ "$SIZEFREETMP_MB" -lt 5 ]; then
   WARNMSG="$WARNMSG
    WARNING: RAM working space only ${SIZETMPM}MB, recommend a reboot which will flush the RAM"
   if [ -d /initrd/pup_rw/lib/modules/all-firmware -a "$ZDRVINIT" = "yes" ];then
@@ -628,7 +626,7 @@ _delete_drivers(){
  if [ "$DEL_LAYER" ];then
   rm $VERB -rf ${DEL_LAYER}/lib/modules
  else
-  if [ $PUPMODE -eq 3 -o $PUPMODE -eq 7 -o $PUPMODE -eq 13 ];then  #flash
+  if [ "$PUPMODE" -eq 3 -o "$PUPMODE" -eq 7 -o "$PUPMODE" -eq 13 ];then  #flash
    rm $VERB -rf ${SAVE_LAYER}/lib/modules
   fi
   rm $VERB -rf /lib/modules
@@ -764,11 +762,11 @@ _get_ram_power_vars
 
 _format_size(){
  SIZE="$1"
- [ $SIZE ] || SIZE=0
- if [ $SIZE -gt 1048576 ];then #1024*1024
+ [ "$SIZE" ] || SIZE=0
+ if [ "$SIZE" -gt 1048576 ];then #1024*1024
   SIZE=`LANG=$OLDLANG dc $SIZE 1048576 \/ p` #100613 dc o/p '.' if LANG=C.
   SIZE="`LANG=$OLDLANG printf "%.1f" $SIZE`GB" #100613
- elif [ $SIZE -gt 1024 ];then
+ elif [ "$SIZE" -gt 1024 ];then
   SIZE="$(( SIZE / 1024 ))"'MB'
  else
    SIZE=`LANG=$OLDLANG dc $SIZE 1024 \/ p` #100613
@@ -860,9 +858,6 @@ DriveIconsize=`grep -o 'DRVICON=.*' /etc/rc.d/functions4puppy4  | grep -o '[[:di
 ICON_PLACE_SPACING=$(( (( DriveIconsize + 1 ) / PIN_GRID_STEP ) * PIN_GRID_STEP ))
 fi
 
-#ICON_PLACE_START_X_GAP=32;ICON_PLACE_START_Y_GAP=32;
-##ICON_PLACE_START_X_GAP=2;ICON_PLACE_START_Y_GAP=2; #x gets half off screen @right)
-
 ICON_PLACE_SPACING=$(( ((ICON_PLACE_SPACING + 1) / PIN_GRID_STEP ) * PIN_GRID_STEP ))
 }
 _get_rox_vars
@@ -872,18 +867,6 @@ _get_rox_vars
 _get_max_xy(){
 
 _get_screen_vars
-
-##CONFFILEROX="$HOME/.config/rox.sourceforge.net/ROX-Filer/Options"  #also deeper down in script
-#FONT_SIZE=`grep 'name="label_font">.*<' "$CONFFILEROX" |sed 's|\(.*\)>\(.*\)<\(.*\)|\2|' |rev |awk '{print $1}' |rev`
-#_debug "FONTSIZE='$FONT_SIZE'"
-
-## REM: ROX-Filer handles icons from middle of icon, not start of icon ( or end of icon )
-#ICON_X=48;icon_x=$((ICON_X/2))
-#ICON_Y=$((FONT_SIZE+48));icon_y=$((ICON_Y/2))
-
-##+++2012-01-19
-#MAX_X=$((SCRN_X-icon_x))  #24 half icon size of 48
-#MAX_Y=$((SCRN_Y-icon_y))  #49 full iconsize, 24 label
 
 MAX_X=$SCRN_X
 MAX_Y=$SCRN_Y
@@ -931,7 +914,7 @@ case $ICON_PLACE_ORIENTATION in #see "$CONFFILE"
 
     COORD_Y=$(( 0 + jwmT_Yvar ))
     COORD_Y=$(( COORD_Y + (ICON_PLACE_SPACING/2) ))
-    test $COORD_Y -lt 48 && COORD_Y=48
+    test "$COORD_Y" -lt 48 && COORD_Y=48
     COORD_Y=$(( ((COORD_Y + 1) / PIN_GRID_STEP) * PIN_GRID_STEP ))
 
    [ "$DEBUG" ] && { LINEP=D0512;echo "`[ $LINENO ] && echo $LINENO || get_lineno $LINEP`"; }
@@ -953,7 +936,7 @@ case $ICON_PLACE_ORIENTATION in #see "$CONFFILE"
 
     COORD_Y=$(( 0 + jwmT_Yvar ))
     COORD_Y=$(( COORD_Y + (ICON_PLACE_SPACING/2) ))
-    test $COORD_Y -lt 64 && COORD_Y=64 #min 48@16, 64@32
+    test "$COORD_Y" -lt 64 && COORD_Y=64 #min 48@16, 64@32
     COORD_Y=$(( ((COORD_Y + 1) / PIN_GRID_STEP) * PIN_GRID_STEP ))
     COORD_Y=$(( COORD_Y - ICON_PLACE_SPACING )) # gets ICON_PLACE_SPACING added again in free_coord
 
@@ -975,7 +958,7 @@ case $ICON_PLACE_ORIENTATION in #see "$CONFFILE"
 
    COORD_Y=$(( 0 + jwmT_Yvar ))
    COORD_Y=$(( COORD_Y + (ICON_PLACE_SPACING/2) ))
-   test $COORD_Y -lt 64 && COORD_Y=64  # 48/16=3*16=48 | 48/32=1*32=32
+   test "$COORD_Y" -lt 64 && COORD_Y=64  # 48/16=3*16=48 | 48/32=1*32=32
    COORD_Y=$(( ((COORD_Y + 1) / PIN_GRID_STEP) * PIN_GRID_STEP ))
    COORD_Y=$(( COORD_Y - ICON_PLACE_SPACING )) # gets ICON_PLACE_SPACING added again in free_coord
    _debug "_get_icon_xy_values:right: COORD_Y='$COORD_Y'"
@@ -1018,7 +1001,7 @@ _free_coord() {
     _debug "top:COORD_X='$COORD_X' COORD_Y='$COORD_Y'"
     COORD_X=$((COORD_X + ICON_PLACE_SPACING))
 
-    if [ $COORD_X -gt $MAX_X ];then #start next line down.
+    if [ "$COORD_X" -gt $MAX_X ];then #start next line down.
     _notice "new X Y coordinates"
 
     COORD_Y=$((COORD_Y + ICON_PLACE_SPACING))
@@ -1035,14 +1018,14 @@ _free_coord() {
     _debug "left:COORD_X=\"${COORD_X}\" COORD_Y=\"${COORD_Y}\""
     COORD_Y=$((COORD_Y + ICON_PLACE_SPACING))
 
-    if [ $COORD_Y -ge $MAX_Y ];then #start next row.
+    if [ "$COORD_Y" -ge $MAX_Y ];then #start next row.
      _notice "new X Y coordinates"
 
      COORD_X=$((COORD_X + ICON_PLACE_SPACING))
 
      COORD_Y=$(( 0 + jwmT_Yvar ))
      COORD_Y=$(( COORD_Y + (ICON_PLACE_SPACING/2) ))
-     test $COORD_Y -lt 64 && COORD_Y=64
+     test "$COORD_Y" -lt 64 && COORD_Y=64
      COORD_Y=$(( ((COORD_Y + 1) / PIN_GRID_STEP) * PIN_GRID_STEP ))
 
     fi
@@ -1061,7 +1044,7 @@ _free_coord() {
     COORD_Y=$(( 0 + jwmT_Yvar ))
     COORD_Y=$(( COORD_Y + (ICON_PLACE_SPACING/2) )) # 32 too low
    #COORD_Y=$(( COORD_Y + ICON_PLACE_SPACING ))    # 64 too much
-    test $COORD_Y -lt 64 && COORD_Y=64
+    test "$COORD_Y" -lt 64 && COORD_Y=64
     COORD_Y=$(( ((COORD_Y + 1) / PIN_GRID_STEP) * PIN_GRID_STEP ))
 
     fi
@@ -1103,7 +1086,7 @@ _free_coord_rem() {
     _debug "top:COORD_X='$COORD_X' COORD_Y='$COORD_Y'"
     COORD_X=$((COORD_X - ICON_PLACE_SPACING))
 
-    if [ $COORD_X -lt 64 ];then #start next line down.
+    if [ "$COORD_X" -lt 64 ];then #start next line down.
     _notice "New X and Y coordinates.."
 
     COORD_Y=$((COORD_Y - ICON_PLACE_SPACING))
@@ -1120,14 +1103,14 @@ _free_coord_rem() {
     _debug "left: COORD_X=${COORD_X} COORD_Y=${COORD_Y}"
     COORD_Y=$((COORD_Y - ICON_PLACE_SPACING))
 
-    if [ $COORD_Y -lt 64 ];then #start next row.
+    if [ "$COORD_Y" -lt 64 ];then #start next row.
      _notice "New X and Y coordinates.."
 
      COORD_X=$((COORD_X - ICON_PLACE_SPACING))
 
      COORD_Y=$(( MAX_Y - jwmT_Yvar ))
      COORD_Y=$(( COORD_Y - (ICON_PLACE_SPACING/2) ))
-     test $COORD_Y -lt 64 && COORD_Y=64
+     test "$COORD_Y" -lt 64 && COORD_Y=64
      COORD_Y=$(( ((COORD_Y + 1) / PIN_GRID_STEP) * PIN_GRID_STEP ))
 
     fi
@@ -1146,9 +1129,9 @@ _free_coord_rem() {
     COORD_X=$(( COORD_X + ICON_PLACE_SPACING ))
 
     COORD_Y=$(( MAX_Y - jwmT_Yvar ))
-    COORD_Y=$(( COORD_Y - (ICON_PLACE_SPACING/2) )) # 32 too low
-   #COORD_Y=$(( COORD_Y - ICON_PLACE_SPACING ))    # 64 too much
-    test $COORD_Y -lt 64 && COORD_Y=64
+    COORD_Y=$(( COORD_Y - (ICON_PLACE_SPACING/2) )) # 32 too little
+   #COORD_Y=$(( COORD_Y - ICON_PLACE_SPACING ))     # 64 too much
+    test "$COORD_Y" -lt 64 && COORD_Y=64
     COORD_Y=$(( ((COORD_Y + 1) / PIN_GRID_STEP) * PIN_GRID_STEP ))
 
     fi
@@ -1208,8 +1191,7 @@ done << _EOI
 $(grep -o "/$EXE_DIR/drive.*" "$PUPPY_PIN" |sed -r 's,(.*)(drives)(.*),\2,;s,(.*drive_)(.*)(<.*),\2,')
 _EOI
 #rm $VERB -rf "$PUP_EVENT_DIR"/*
-rm $VERB -f /tmp/pup_event_change_icons.flg
-rm $VERB -f /tmp/pup_event_manager.flg
+rm $VERB -f /tmp/pup_event_change_icons.flg /tmp/pup_event_manager.flg
 unset DRV_NAME part
 }
 sleep 2; _clean_desk_icons
@@ -1221,6 +1203,7 @@ _add_pinboard(){
 #needs oneDRVNAME, DRV_CATEGORY, FSTYPE
 _debug "_add_pinboard:$@"
 test "$*" || return
+
 oneDRVNAME="$1"
 DRV_CATEGORY="$2"
 FSTYPE="$3"
@@ -1257,19 +1240,17 @@ sleep 0.1
 aENTRY=`grep "/drive_${oneDRVNAME}</icon>" "$PUPPY_PIN" | tail -n1`
 aX=`echo "$aENTRY" | cut -f2 -d'"'`
 aY=`echo "$aENTRY" | cut -f4 -d'"'`
-test $aX = $COORD_X || _warn "ROX-Filer ignored '$COORD_X' passed, uses '$aX' instead.."
-test $aY = $COORD_Y || _warn "ROX-Filer ignored '$COORD_Y' passed, uses '$aY' instead.."
+test "$aX" = $COORD_X || _warn "ROX-Filer ignored '$COORD_X' passed, uses '$aX' instead.."
+test "$aY" = $COORD_Y || _warn "ROX-Filer ignored '$COORD_Y' passed, uses '$aY' instead.."
 
 unset oneDRVNAME DRV_CATEGORY FSTYPE aENTRY aX aY
 }
-
 
 _create_icon(){
 
     #_store_program_logging_level
     #DEBUG=
     _debug  "_create_icon:$@"
-    #echo "DRV_NAME='$DRV_NAME' DRV_CATEGORY='$DRV_CATEGORY' DRV_DESCRIPTION='$DRV_DESCRIPTION'"
     _debug  "DISK_NAME='$DISK_NAME' DISK_CATEGORY='$DISK_CATEGORY' DISK_DESCRIPTION='$DISK_DESCRIPTION'"
     test "$1" -a "$2" -a "$3" || {
         #_reset_program_logging_level;
@@ -1331,10 +1312,12 @@ _create_icon(){
       FSTYPE=`echo "$onePART" | cut -f 2 -d '|'`
         SIZE=`echo "$onePART" | cut -f 3 -d '|'`
   partPATTERN='^/dev/'"${oneDRVNAME}"' ' #important, a space on end!
-  if [ ! -d "$PUP_EVENT_DIR"/drive_${oneDRVNAME} ];then
-      mkdir $VERB "$PUP_EVENT_DIR"/drive_${oneDRVNAME}
+
+  if    [ ! -d "$PUP_EVENT_DIR"/drive_${oneDRVNAME} ];then
+   mkdir $VERB "$PUP_EVENT_DIR"/drive_${oneDRVNAME}
    cp $VERB -af /usr/local/bin/drive_all "$PUP_EVENT_DIR"/drive_${oneDRVNAME}/AppRun
-   if [ -e /sys/block/${oneDRVNAME}/size ];then
+
+   if [ -s /sys/block/${oneDRVNAME}/size ];then
     #device is an entire drive.
     read SIZE </sys/block/${oneDRVNAME}/size
     SIZE=$((SIZE/2)) #get KB.
@@ -1388,14 +1371,13 @@ _create_icon(){
  #always create a handler for entire Drive and Partition1, even if no icon displayed...
  for aP in "" 1 2 3 4;
  do
- #if [ ! -d "$PUP_EVENT_DIR"/drive_${DISK_NAME}$aP ];then
      [ -d "$PUP_EVENT_DIR"/drive_${DISK_NAME}$aP ] && continue
-  if [ -e /sys/block/${DISK_NAME}$aP/size ]; then
+  if [ -s /sys/block/${DISK_NAME}$aP/size ]; then
 
    read SIZE </sys/block/${DISK_NAME}$aP/size
    SIZE=$((SIZE/2))     #get KB.
 
-  elif   [ -e /sys/block/${DISK_NAME}/${DISK_NAME}$aP/size ]; then
+  elif   [ -s /sys/block/${DISK_NAME}/${DISK_NAME}$aP/size ]; then
    read SIZE </sys/block/${DISK_NAME}/${DISK_NAME}$aP/size
    SIZE=$((SIZE/2))     #get KB.
 
@@ -1412,7 +1394,6 @@ _create_icon(){
    MOREITEMS="<Item option=\"unmountall\" icon=\"gtk-harddisk\"><Label>Unmount ALL mounted partitions</Label></Item>"
    oneDRVNAME="${DISK_NAME}$aP"
    _create_appinfo "$dINFO" "$DISK_CATEGORY" "$MOREITEMS" "$oneDRVNAME" #needs dINFO, DRV_CATEGORY, MOREITEMS, oneDRVNAME
- #fi
  done
 unset DISK_PARTITIONS diskPATTERN onePART MNTSTATUS
 unset oneDRVNAME DISK_NAME DISK_CATEGORY partPATTERN FSTYPE dINFO SIZE MOREITEMS
@@ -1463,9 +1444,9 @@ else
 
  for oneDISK in `echo "$_PROBEDISK_"   | cut -f 1,2,3 -d '|' | tr ' ' '_'`
  do
-  DISK_NAME=`echo -n "$oneDISK"        | cut -f 1 -d '|' | cut -f 3 -d '/'`
-  DISK_CATEGORY=`echo -n "$oneDISK"    | cut -f 2 -d '|'`
-  DISK_DESCRIPTION=`echo -n "$oneDISK" | cut -f 3 -d '|' | tr '_' ' '`
+  DISK_NAME=`echo "$oneDISK"        | cut -f 1 -d '|' | cut -f 3 -d '/'`
+  DISK_CATEGORY=`echo "$oneDISK"    | cut -f 2 -d '|'`
+  DISK_DESCRIPTION=`echo "$oneDISK" | cut -f 3 -d '|' | tr '_' ' '`
   _debug  "DISK_NAME=$DISK_NAME DISK_CATEGORY=$DISK_CATEGORY DISK_DESCRIPTION=$DISK_DESCRIPTION"
   [ "`echo "$_PROBEPART_" | grep "$DISK_NAME"`" ] || continue #precaution (such as CD not inserted).
   _debug  "'$DISK_NAME' in _PROBEDISK_ and _PROBEPART_"
@@ -1507,7 +1488,7 @@ _check_battery(){
 
   BAT_0_CURRENT=`grep 'remaining capacity:' "$BAT_0_state_file"`
   BAT_0_CURRENT="${BAT_0_CURRENT//[^[:digit:]]/}"
-    if [ $BAT_0_CURRENT -le $BAT_0_WARN ];then
+    if [ "$BAT_0_CURRENT" -le $BAT_0_WARN ];then
     aplay /usr/share/audio/2barks.au;aplay /usr/share/audio/2barks.au
     pupmessage -bg red -timeout 30 "Battery State is: $BAT_0_CURRENT
 better to plug in ac adapter or poweroff the laptop "
@@ -1544,13 +1525,13 @@ _powertimeout(){
 if [ "$POWERTIMEOUT" != '0' ]; then
 __powertimeout(){
    MINUTECNT=$((MINUTECNT + POLL_PLUG_DEVICE))
-  [ $MINUTECNT -ge 60 ] || return 0 #come in here every minute...
+  [ "$MINUTECNT" -ge 60 ] || return 0 #come in here every minute...
     MINUTECNT=0
   # BATTERY
    if [ "$BAT_0" = '1' ];then
   BAT_0_CURRENT=`grep 'remaining capacity:' "$BAT_0_state_file"`
   BAT_0_CURRENT="${BAT_0_CURRENT//[^[:digit:]]/}"
-    if [ $BAT_0_CURRENT -le $BAT_0_WARN ];then
+    if [ "$BAT_0_CURRENT" -le $BAT_0_WARN ];then
     aplay /usr/share/audio/2barks.au;aplay /usr/share/audio/2barks.au
     pupmessage -bg red -timeout 30 "Battery State is: $BAT_0_CURRENT
 better to plug in ac adapter or poweroff the laptop "
@@ -1563,9 +1544,9 @@ better to plug in ac adapter or poweroff the laptop "
    MOUSECNT=$((MOUSECNT+60))
    CURPOS2=`getcurpos`
    #just a log file without any further purpose :
-   [ "$CURPOS1" != "$CURPOS2" ] && MOUSECNT=0
+   [ "$CURPOS1" = "$CURPOS2" ] || MOUSECNT=0
    CURPOS1="$CURPOS2"
-    #[ $MOUSECNT -gt $POWERTIMEOUT ] && wmpoweroff &
+    #[ "$MOUSECNT" -gt $POWERTIMEOUT ] && wmpoweroff &
     if [ "$MOUSECNT" -gt $POWERTIMEOUT ];then
      aplay /usr/share/audio/2barks.au
      sleep 1
@@ -1588,15 +1569,15 @@ and change this value .
 
 _powertimeout(){
    MINUTECNT=$((MINUTECNT + POLL_PLUG_DEVICE))
-   [ $MINUTECNT -ge 60 ] || return 0 #come in here every minute...
+   [ "$MINUTECNT" -ge 60 ] || return 0 #come in here every minute...
    MINUTECNT=0
    if [ "$POWERTIMEOUT" -gt '0' ];then
    MOUSECNT=$((MOUSECNT+60))
    CURPOS2=`getcurpos`
    #just a log file without any further purpose :
-   [ "$CURPOS1" != "$CURPOS2" ] && MOUSECNT=0
+   [ "$CURPOS1" = "$CURPOS2" ] || MOUSECNT=0
    CURPOS1="$CURPOS2"
-    #[ $MOUSECNT -gt $POWERTIMEOUT ] && wmpoweroff &
+    #[ "$MOUSECNT" -gt $POWERTIMEOUT ] && wmpoweroff &
     if [ "$MOUSECNT" -gt $POWERTIMEOUT ];then
      aplay /usr/share/audio/2barks.au
      sleep 1
@@ -1764,7 +1745,7 @@ fi;fi
 _reset_program_logging_level
 }
 
-DEBUG=1
+#DEBUG=1
 _pup_event_daemon(){
 
 _check_writable_tmp(){
@@ -1787,6 +1768,7 @@ return 0
 #_store_program_logging_level
 ###################################################################
 #now go into a two-second two-second loop...
+cd /tmp || return 1
 while :
 do
  sleep $POLL_PLUG_DEVICE
@@ -1795,6 +1777,7 @@ do
 
  #test for any change in /sys/block...
  ls -1 /sys/block | grep -vE '^loop|^md|^mtd|^nbd|^*ram' > /tmp/pup_event_frontend_block2
+
  if [ -f /tmp/pup_event_frontend_block_request ];then #w015 (see gparted_shell, puppyinstaller, bootflash)
   sleep 0.1
   REMOVEBLOCK='^'"`cat /tmp/pup_event_frontend_block_request`"'$'
@@ -1817,12 +1800,11 @@ do
    _debug "about to check $oneTESTDRV:"
    [ -d /sys/block/${oneTESTDRV} ] || continue
    [ -b /dev/$oneTESTDRV ]         || continue
-   #[ "`echo "$ATADRIVES" | grep -w "$oneTESTDRV"`" ] && continue
-    realpath /sys/block/${oneTESTDRV} | grep $Q 'usb' || continue
-    grep $Q -w '0' /sys/block/${oneTESTDRV}/removable && continue
+   realpath /sys/block/${oneTESTDRV} | grep $Q 'usb' || continue
+   grep $Q -w '0' /sys/block/${oneTESTDRV}/removable && continue
+   #try force kernel to update:
+   (true </dev/$oneTESTDRV) >>$OUT 2>>$ERR
 
-       #try force kernel to update:
-       (true </dev/$oneTESTDRV) >>$OUT 2>>$ERR
    _debug "Checking $oneTESTDRV for primary partitions:"
    for p in 1 2 3 4; do #check all possible primary partitions, since at least one primary must exist
    if [ -e /sys/block/${oneTESTDRV}/${oneTESTDRV}$p ]; then #drive exists, but no partition (no card plugged in).
@@ -1887,7 +1869,7 @@ _EOI
     LANG=$OLDLANG pmount & #100613 fix from shinobar.
    fi
    _remove_pinboard "$oneDISK_NAME"   #needs DRV_NAME
-   rm $VERB -rf "$PUP_EVENT_DIR"/drive_${oneDISK_NAME}*
+   rm $VERB -rf "$PUP_EVENT_DIR"/drive_${oneDISK_NAME}
   done
 
  fi
@@ -1897,7 +1879,7 @@ _EOI
 
  #monitor free memory, periodic save of tmpfs top layer...
  FREE_COUNT=$((FREE_COUNT + POLL_PLUG_DEVICE))
- if test $FREE_COUNT -gt $POLL_FREE_MEMORY; then
+ if test "$FREE_COUNT" -gt $POLL_FREE_MEMORY; then
  FREE_COUNT=0
  case $PUPMODE in
   3|7|13)  #flash
@@ -1917,7 +1899,7 @@ __poll_cd_fd__(){ # since driveicons stay on desktop, only usefull for AUTOHANDL
 
 [ "$ZCDPOLL" = true ] || return 0
 POLL_COUNT=$((POLL_COUNT + POLL_PLUG_DEVICE))
-[ $POLL_COUNT -gt $POLL_ZIPCDROM ] || return 0
+[ "$POLL_COUNT" -gt $POLL_ZIPCDROM ] || return 0
 POLL_COUNT=0
 
 #if [ "$ZCDPOLL" != "false" ];then
