pup_event_backend_modprobe : Bulk Maintanance Replacement of today.

diff --git a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
--- a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
+++ b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
@@ -14,7 +14,7 @@
 #
 # CHANGES by Karl Reimer Godt
 # 01.0 : support for different modprobe.conf files
-# 02.0 : logging to separate $LocalLOG 
+# 02.0 : logging to separate $LocalLOG
 # 03.0 : leaving note in modprobe.conf or alsa.conf file if entries added or changed
 # 04.0 : check if module contained in modprobe -l
 # 05.0 : check /dev/.udev/failed
@@ -106,7 +106,7 @@ TIME="date +%M.%S.%N"
 
 echo $$ 1.0 `$TIME` '$1='"$1" >> $LocalLOG
 
-[ $1 ] && RULEMODULE="$1"
+[ "$1" ] && RULEMODULE="$1"
 touch /tmp/pup_event_module_devpath_log
 
 [ "$FASTBOOTMODULESLIST" != "" ] && echo $$ 1.5 'FASTMODLST .. exit ..' >> $LocalLOG && exit 1 #fastboot, see /etc/rc.d/MODULESCONFIG.
@@ -136,7 +136,7 @@ setup_alsa_func() { #uses MODULE.
     grep -v "$DPATTERN" $CONFFILE > /tmp/modprobe.conf  ##leaves sound-slot-nr in modprobe.conf
     cp -f /tmp/modprobe.conf $CONFFILE
     echo >> $CONFFILE
-    echo '##### Changed by /sbin/pup_event_backend_modprobe #####' >> $CONFFILE 
+    echo '##### Changed by /sbin/pup_event_backend_modprobe #####' >> $CONFFILE
     echo '### Running kernel '"$KERNVER" >> $CONFFILE
     echo '### Because modulename or harware had changed' >> $CONFFILE
     echo '### Configuration-file is '"$CONFFILE" >> $CONFFILE
@@ -152,9 +152,9 @@ setup_alsa_func() { #uses MODULE.
 
 pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
  #returns 0 if ok to load module, changes MODULE if required.
- 
+
  echo $$ 5.0 `$TIME` "Starting pci_fixup_func ..." >> $LocalLOG
- 
+
  VENDOR='0x'"`echo -n "$MODALIAS" | cut -f 2 -d 'v' | cut -b 1-8 | tr [A-Z] [a-z]`"
  DEVICE='0x'"`echo -n "$MODALIAS" | cut -f 2 -d 'v' | cut -b 10-17 | tr [A-Z] [a-z]`"
  #######/etc/rc.d/MODULESCONFIG overrides######
@@ -193,41 +193,41 @@ firmware_module_func() {
  #global MODULE is name of module, global KERNVER.
  altMODULE="`echo -n "$lsmodName" | tr '_' '-'`"
  FPATTERN='[:,]'"${lsmodName}"'\.ko|[:,]'"${altMODULE}"'\.ko'
- 
+
  FIRMPKG="`cat /etc/modules/firmware.dep.$KERNVER  | grep -v '^#' | grep ':' | grep -E "$FPATTERN" | cut -f 1 -d ':' | head -n 1`"
- 
+
  if [ "$FIRMPKG" != "" ];then
   echo $$ 7.3 `$TIME` "found FIRMPKG='$FIRMPKG' in /etc/modules/firmware.dep.$KERNVER" >> $LocalLOG
-  
+
   if [ -f /lib/modules/all-firmware/${FIRMPKG}.tar.gz ];then
    echo $$ 7.4 `$TIME` "found /lib/modules/all-firmware/${FIRMPKG}.tar.gz" >> $LocalLOG
-   
+
    cp -af /lib/modules/all-firmware/${FIRMPKG}.tar.gz /tmp ##>/dev/null 2>&1
    cd /tmp
    tar -zxf ${FIRMPKG}.tar.gz ##>/dev/null 2>&1
   fi
   if [ -d /tmp/${FIRMPKG} ];then
   echo $$ 7.5 `$TIME` "OK , extracted to /tmp/${FIRMPKG}" >> $LocalLOG
-   
-   cp -a --remove-destination /tmp/${FIRMPKG}/* / ##2>/dev/null
+
+   /bin/cp -a --remove-destination /tmp/${FIRMPKG}/* / ##2>/dev/null
    retVal=$?
    if [ "$retVal" == '0' ] ; then
     echo $$ 7.5 `$TIME` "OK , successfully installed ..." >>$LocalLOG
    else
-    echo $$ 7.5 `$TIME` "NOPE or what ..? Installing returned $retVal . PLEASE look into /tmp/${FIRMPKG} for the files that should have been installed ..." >> $LocalLOG
-   fi 
+    echo $$ 7.5 `$TIME` "NOPE or what ..? Installing returned '$retVal' . PLEASE look into /tmp/${FIRMPKG} for the files that should have been installed ..." >> $LocalLOG
+   fi
   fi
   #in case firmware is not a .tar.gz tarball...
   if [ -d /lib/modules/all-firmware/${FIRMPKG} ];then #w478
   echo $$ 7.6 `$TIME` "OK , copying /lib/modules/all-firmware/${FIRMPKG}/\* to / , overriding evtl. the tar.gz" >> $LocalLOG
-   
-   cp -a --remove-destination /lib/modules/all-firmware/${FIRMPKG}/* / ##2>/dev/null
+
+   /bin/cp -a --remove-destination /lib/modules/all-firmware/${FIRMPKG}/* / ##2>/dev/null
    retVal=$?
    if [ "$retVal" == '0' ] ; then
     echo $$ 7.6 `$TIME` "OK , successfully installed ..." >>$LocalLOG
    else
-    echo $$ 7.6 `$TIME` "NOPE or what ..? Installing returned $retVal . PLEASE look into /tmp/${FIRMPKG} for the files that should have been installed ..." >> $LocalLOG
-   fi 
+    echo $$ 7.6 `$TIME` "NOPE or what ..? Installing returned '$retVal' . PLEASE look into /tmp/${FIRMPKG} for the files that should have been installed ..." >> $LocalLOG
+   fi
   fi
   #comment-out the firmware pkg entry, so it only installs once...
   if [ "$retVal" == '0' ] ; then
@@ -237,7 +237,7 @@ firmware_module_func() {
   #execute any post-install script...
    if [ -f /pinstall.${FIRMPKG}.sh ];then
     echo $$ 7.7 `$TIME` "OK , /pinstall.${FIRMPKG}.sh exists , executing now ..." >> $LocalLOG
-   
+
     cd /
     /pinstall.${FIRMPKG}.sh ##>/dev/null 2>&1 #execute script.
     rm -f /pinstall.${FIRMPKG}.sh ##>/dev/null 2>&1
@@ -250,14 +250,14 @@ firmware_module_func() {
  echo $$ 7.9 `$TIME` "ending firmware_module_func ..." >> $LocalLOG
 }
 
-echo $$ 2.0 `$TIME` 'MODALIAS='"$MODALIAS" >> $LocalLOG
+echo $$ 2.0 `$TIME` "MODALIAS='$MODALIAS'" >> $LocalLOG
 
 #find a matching module... (/etc/pup_event_modprobe.conf created in rc.sysinit)
 MODULES="`/sbin/modprobe --config /tmp/pup_event_skiplist.conf --show-depends $MODALIAS 2>/dev/null | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.'`" #v424  ##+-2011_10_26 rm tr - _
 realName="`echo "$MODULES" | tail -n 1`" #v424
 lsmodName="`echo "$realName" | tr '\-' '_'`"  ##+++2011_20_26
 #[ "$MODULE" = "usb_storage" ] && [ "`echo "$MODULES" | grep '^usbserial$'`" != "" ] && MODULE="`echo "$MODULES" | grep -v -E '^usb_storage$|^usbcore$' | tail -n 1`" #v424
-echo $$ 3.0 `$TIME` 'lsmodName='"$lsmodName" >> $LocalLOG
+echo $$ 3.0 `$TIME` "lsmodName='$lsmodName'" >> $LocalLOG
 
 if [ -z "$realName" ] ; then  ##+++2011_20_26
 MODALIAS2="${MODALIAS#*:}"  ##deletes preceding pci: or platform:
@@ -269,14 +269,14 @@ fi  ##+++2011_20_26
 [ "$lsmodName" = "" ] && [ "$RULEMODULE" != "" ] && lsmodName="$RULEMODULE" #w463 Use module from argument
 
 [ "$lsmodName" = "" ] && echo $$ 3.5 `$TIME` 'Still no lsmodName .. exit ..' >> $LocalLOG && exit 1
-[ "$lsmodName" = "usb_storage" ] && echo $$ 3.6 `$TIME` "$lsmodName omitted by $0" >> $LocalLOG  && exit 1 #loaded explicitly in boot scripts.
+[ "$lsmodName" = "usb_storage" ] && echo $$ 3.6 `$TIME` "'$lsmodName' omitted by '$0'" >> $LocalLOG  && exit 1 #loaded explicitly in boot scripts.
 
 ###<2011-11-10>
 #if [ -n "`echo "$lsmodName" | grep '[ou]hci_hcd'`" ] ; then
 if [ "$lsmodName" = 'ohci_hcd' -o "$lsmodName" = 'uhci_hcd' ] ; then
 if [ -z "`lsmod | grep 'ehci_hcd'`" ] ; then
 if [ -n "`elspci -l | grep -w '0C0320'`" ] ; then
-echo $$ 3.7 `$TIME` "$lsmodName detected AND port:ehci-hcd but ehci-hcd not loaded yet" >> $LocalLOG
+echo $$ 3.7 `$TIME` "'$lsmodName' detected AND bus:ehci-hcd, but ehci-hcd not loaded yet" >> $LocalLOG
 MODALIAS='' $0 "ehci-hcd"
 sleep 1s;c=0
 while [ -z "`lsmod | grep 'ehci_hcd'`" ] ; do
@@ -285,9 +285,9 @@ sleep 1s
 [ "$c" == 10 ] && break
 done
 if [ -z "`lsmod | grep 'ehci_hcd'`" ] ; then
-echo $$ 3.8 `$TIME` "MODULE ehci-hcd still not loaded yet . Continuing loading $lsmodName anyway" >> $LocalLog
+echo $$ 3.8 `$TIME` "MODULE ehci-hcd still not loaded yet . Continuing loading '$lsmodName' anyway" >> $LocalLog
 else
-echo $$ 3.8 `$TIME` "MODULE ehci-hcd loaded . Continuing loading $lsmodName" >> $LocalLog
+echo $$ 3.8 `$TIME` "MODULE ehci-hcd loaded . Continuing loading '$lsmodName'" >> $LocalLog
 fi
 fi
 fi
@@ -296,9 +296,9 @@ fi
 
 realNameGrepPattern="${realName//-/\\-}"     ##+++2011_10_26
 realNameGrepPattern2="${realName//-/\\\\-}"  ##+++2011_10_26 for setup_alsa_func #2011_10_27 :alias snd\-card\-0 snd\\-wavefront not as wanted , changed to $realNameGrepPattern
-[ -z "`modprobe -l | grep "$realNameGrepPattern"`" ] && echo $$ 3.5 `$TIME` "cannot find $realName in modprobe -l" >> $LocalLOG  && exit 2
+[ -z "`modprobe -l | grep "$realNameGrepPattern"`" ] && echo $$ 3.5 `$TIME` "cannot find '$realName' in modprobe -l" >> $LocalLOG  && exit 2
 lsmodNameGrepPattern='^'"${lsmodName}"'$'
-echo $$ 4.0 `$TIME` 'modPATTERN 1 ='"$lsmodNameGrepPattern" >> $LocalLOG
+echo $$ 4.0 `$TIME` "modPATTERN 1 ='$lsmodNameGrepPattern'" >> $LocalLOG
 
 #[ "`cat /tmp/pup_event_module_devpath_log | cut -f 1 -d ' ' | cut -f 2 -d '=' | grep "$modPATTERN"`" != "" ] && echo 'Duplicate module ..exit ..' >> $LocalLOG && exit 0 #duplicate module.
 if [ "`cat /tmp/pup_event_module_devpath_log | cut -f 1 -d ' ' | cut -f 2 -d '=' | grep "$lsmodNameGrepPattern"`" != "" ] ; then
@@ -306,7 +306,7 @@ FM=`find /dev/.udev/failed | grep "$lsmodNameGrepPattern"`
 if [ -z "$FM" ] ; then
 echo $$ 4.5 `$TIME` 'Duplicate module ..exit ..' >> $LocalLOG && exit 0 #duplicate module.
 else
-echo -e $$ 4.5 `$TIME` "\e[31m"'udevd seems to have failed already loading '"$lsmodNameGrepPattern""\e[39m" >> $LocalLOG
+echo -e $$ 4.5 `$TIME` "\e[31m""udevd seems to have failed already loading '$lsmodNameGrepPattern'""\e[39m" >> $LocalLOG
 fi
 fi
 
@@ -320,16 +320,16 @@ esac
 
 #v404 preferences list, ex rt2500usb and rt73usb both hits, then choose latter...
 modPATTERN='^'"$lsmodName"':'
-echo $$ 6.0 `$TIME` 'modPATTERN 2 ='"$modPATTERN" >> $LocalLOG
+echo $$ 6.0 `$TIME` "modPATTERN 2 ='$modPATTERN'" >> $LocalLOG
 PREFHIT="`echo -n "$PREFLIST" | tr ' ' '\n' | grep "$modPATTERN"`"
-echo $$ 6.1 `$TIME` 'PREFHIT='"$PREFHIT" >> $LocalLOG
+echo $$ 6.1 `$TIME` "PREFHIT='$PREFHIT'" >> $LocalLOG
 
 if [ "$PREFHIT" != "" ];then
  PREFMOD="`echo -n "$PREFHIT" | cut -f 2 -d ':'`"
  echo "blacklist $lsmodName" > /tmp/pup_event_prefhit_blacklist
  xMODULE="`/sbin/modprobe --config /tmp/pup_event_prefhit_blacklist --show-depends $MODALIAS 2>/dev/null | tail -n 1 | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`"
  [ "$xMODULE" != "" ] && [ "$xMODULE" != "$lsmodName" ] && lsmodName="$xMODULE"
- echo $$ 6.5 `$TIME` lsmodName=$lsmodName >> $LocalLOG
+ echo $$ 6.5 `$TIME` "lsmodName='$lsmodName'" >> $LocalLOG
 fi
 
 #installs a firmware tarball (once only. loading firmware is something else)...
@@ -341,10 +341,10 @@ usleep $(( $$ * 10 ))
 cd /sbin #v408 rerwin thinks this is needed for slamr module.
 if [ -z "`lsmod | grep "$lsmodName"`" ] ; then
 echo "MODULE=$MODULE DEVPATH=$DEVPATH" >> /tmp/pup_event_module_devpath_log
-echo -e $$ 9.0 `$TIME` "\e[32m"'Finally modprobing '"$lsmodName""\e[39m" >> $LocalLOG
+echo -e $$ 9.0 `$TIME` "\e[32m""Finally modprobing '$lsmodName'""\e[39m" >> $LocalLOG
  exec /sbin/modprobe -v $lsmodName
 else
-echo -e $$ 9.0 `$TIME` "\e[31m"'lsmodName '"$lsmodName"' already inserted'"\e[39m" >> $LocalLOG
+echo -e $$ 9.0 `$TIME` "\e[31m""lsmodName '$lsmodName' already inserted""\e[39m" >> $LocalLOG
 fi
 ###END###
 exit
