pup_event: /sbin/ pup_event_frontend_d, pup_event_backend_modprobe_protect /usr/sbin/ eventmanager : Various code reorderings. Especially pup_event_backend_modprobe_protect ensure code runs by forking echo to pipe ( echo xyz >/tmp/pipe & sleep 0.4 ) since echo would hang forever if targetpipe does not get read currently. Also timeout for read ( read -t 62 <mypipe ).

diff --git a/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d b/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
--- a/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
+++ b/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
@@ -132,60 +132,76 @@ fi;fi
 #in two USB drives at once can cause this. So, dropping that, going back to primitive,
 #simple polling loop.
 
+#[ "$CONFFILE" ] || CONFFILE=/etc/eventmanager.cfg
+#test -f "$CONFFILE" && . "$CONFFILE" #has RAMSAVEINTERVAL, ICONDESK, HOTPLUGNOISY, ICONPARTITIONS, BACKENDON, POWERTIMEOUT
+CONFFILE=${CONFFILE:-/etc/eventmanager.cfg}
+test -s "$CONFFILE" && . "$CONFFILE"
+
 # Polling. The lesser , the more CPU usage
-[ "$POLL_FREE_MEMORY" ]       || POLL_FREE_MEMORY=6  # seconds to check free space in /
+#[ "$POLL_FREE_MEMORY" ]       || POLL_FREE_MEMORY=6  # seconds to check free space in /
+POLL_FREE_MEMORY=${POLL_FREE_MEMORY:-6}
 [ "$POLL_FREE_MEMORY" -ge 2 ] || POLL_FREE_MEMORY=2
 [ "$POLL_FREE_MEMORY" -le 9 ] || POLL_FREE_MEMORY=9
-[ "$POLL_PLUG_DEVICE" ]       || POLL_PLUG_DEVICE=2  # seconds to check for plugged USB drives if DESKDAEMON=true
+#[ "$POLL_PLUG_DEVICE" ]       || POLL_PLUG_DEVICE=2  # seconds to check for plugged USB drives if DESKDAEMON=true
+POLL_PLUG_DEVICE=${POLL_PLUG_DEVICE:-2}
 [ "$POLL_PLUG_DEVICE" -ge 1 ] || POLL_PLUG_DEVICE=1
 [ "$POLL_PLUG_DEVICE" -le 9 ] || POLL_PLUG_DEVICE=9
-[ "$POLL_ZIPCDROM" ]          || POLL_ZIPCDROM=6     # seconds to poll for CD/Floppy insertitons if ZCDPOLL=true
+#[ "$POLL_ZIPCDROM" ]          || POLL_ZIPCDROM=6     # seconds to poll for CD/Floppy insertitons if ZCDPOLL=true
+POLL_ZIPCDROM=${POLL_ZIPCDROM:-6}
 [ "$POLL_ZIPCDROM" -ge 4 ]    || POLL_ZIPCDROM=4
 [ "$POLL_ZIPCDROM" -le 9 ]    || POLL_ZIPCDROM=9
 #POLL_REMOVABLE=3   # seconds to poll for CD/Floppy insertitons ZCDPOLL=true
 
-SAVECNT=0
-MOUSECNT=0  #w007
-MINUTECNT=0 #w007
-CURRPOS1='-1 -1' ##+++2012-01-18 moved here for not testing it inside DAEMON all the time
-
-ZDRV='';ZDRVINIT='no' #these usually set in PUPSTATE.
-. /etc/rc.d/PUPSTATE
-KERNEL_RELEASE=`uname -r`
-CONFFILE=${CONFFILE:-/etc/eventmanager.cfg}
-test -f "$CONFFILE" && . "$CONFFILE" #has RAMSAVEINTERVAL, ICONDESK, HOTPLUGNOISY, ICONPARTITIONS, BACKENDON, POWERTIMEOUT
-. /etc/rc.d/functions4puppy4
-SIZE_MODS_MB=0
-if [ "$ZDRVINIT" = "yes" ];then
- #all mods were in initrd at bootup, then moved to main f.s.
- SIZE_MODS_MB=$(du -m -s /lib/modules/`uname -r` | cut -f 1)
-fi
-RETVALm=1
-PREVSIZETMPM=0
-PREVSIZEFREEM=0
-
-### *** ROX-Filer Pinboard *** ###
-STATE_DIR="$HOME/Choices/Puppy"
-EXE_DIR='pup_event'
-PUP_EVENT_DIR="$STATE_DIR/$EXE_DIR"
-#PUP_EVENT_DIR="$HOME/Choices/Puppy/pup_event"
-#PUP_EVENT_DIR="$HOME/.pup_event"
-DRIVE_ICON_DIR="/usr/local/lib/X11/pixmaps"
-CONFFILEROX="$HOME/.config/rox.sourceforge.net/ROX-Filer/Options"
-  PUPPY_PIN="$HOME/Choices/ROX-Filer/PuppyPin"
-
-MY_HOME=/var/local/PuppyLinux/pup_event
-MY_CFG="$MY_HOME"/etc
-MY_LOG="$MY_HOME"/log
-MY_TMP="$MY_HOME"/tmp
+MY_HOME=${MY_HOME:-/var/local/PuppyLinux/pup_event}
+MY_CFG=${MY_CFG:-"$MY_HOME"/etc}
+MY_LOG=${MY_LOG:-"$MY_HOME"/log}
+MY_TMP=${MY_TMP:-"$MY_HOME"/tmp}
 mkdir $VERB -p "$MY_CFG" "$MY_LOG" "$MY_TMP"
 chown $VERB pup_event:pup_event "$MY_HOME"
 chown $VERB pup_event:pup_event "$MY_CFG" "$MY_LOG" "$MY_TMP"
 chmod $VERB 1774 "$MY_CFG" "$MY_LOG"
 chmod $VERB 1770 "$MY_TMP"
-ls -ld "$MY_HOME"
-ls -l  "$MY_HOME"
-cd "$MY_HOME" || exit 2
+[ "$DEBUG" ] && ls -ld "$MY_HOME"
+[ "$DEBUG" ] && ls -l  "$MY_HOME"
+cd "$MY_HOME" || { echo "Could not change into directory $MY_HOME ."; exit 2; }
+
+### *** ROX-Filer Pinboard *** ###
+STATE_DIR=${STATE_DIR:-"$HOME/Choices/Puppy"}
+EXE_DIR=${EXE_DIR:-'pup_event'}
+PUP_EVENT_DIR=${PUP_EVENT_DIR:-"$STATE_DIR"/"$EXE_DIR"}
+#PUP_EVENT_DIR="$HOME/Choices/Puppy/pup_event"
+#PUP_EVENT_DIR="$HOME/.pup_event"
+DRIVE_ICON_DIR=${DRIVE_ICON_DIR:-"/usr/local/lib/X11/pixmaps"}
+CONFFILEROX=${CONFFILEROX:-"$HOME/.config/rox.sourceforge.net/ROX-Filer/Options"}
+  PUPPY_PIN=${PUPPY_PIN:-"$HOME/Choices/ROX-Filer/PuppyPin"}
+
+_debug "
+STATE_DIR='$STATE_DIR'
+EXE_DIR='$EXE_DIR'
+PUP_EVENT_DIR='$PUP_EVENT_DIR'
+DRIVE_ICON_DIR='$DRIVE_ICON_DIR'
+CONFFILEROX='$CONFFILEROX'
+PUPPY_PIN='$PUPPY_PIN'
+"
+
+ZDRV='';ZDRVINIT='no' #these usually set in PUPSTATE.
+. /etc/rc.d/PUPSTATE
+KERNEL_RELEASE=${KERNEL_RELEASE:-`uname -r`}
+. /etc/rc.d/functions4puppy4
+SIZE_MODS_MB=0
+if [ "$ZDRVINIT" = "yes" ];then
+ #all mods were in initrd at bootup, then moved to main f.s.
+ SIZE_MODS_MB=$(du -m -s /lib/modules/`uname -r` | cut -f 1)
+ SIZE_MODS_MB=${SIZE_MODS_MB:-0}
+fi
+RETVALm=1
+PREVSIZETMPM=0
+PREVSIZEFREEM=0
+
+SAVECNT=0
+MOUSECNT=0  #w007
+MINUTECNT=0 #w007
+CURRPOS1='-1 -1' ##+++2012-01-18 moved here for not testing it inside DAEMON all the time
 
 _get_skip_names(){
 ### *** do not check for saveinterval if these apps are running *** #
@@ -291,7 +307,6 @@ configuration file $CONFFILE, which is read
 by this script. Other configuration files used :
 /etc/rc.d/PUPSTATE /etc/rc.d/functions4puppy4
 "
-MSG=`gettext "$MSG"`
 echo "$MSG"
 [ "$DISPLAY" ] && exec xmessage -title "FRONTEND_D HELP" -bg blue3 "$MSG" &
 exit $1
@@ -861,21 +876,23 @@ PIN_GRID_STEP=`sed -n '/<!--/,/-->/!p' "$CONFFILEROX" | grep -m1 "pinboard_grid_
 case $PIN_GRID_STEP in 2|16|32) :;;
 *) PIN_GRID_STEP=32;;
 esac
-[ -z "$PIN_GRID_STEP" ]    && PIN_GRID_STEP=32 #2=fine 16=medium 32=coarse.
+PIN_GRID_STEP=${PIN_GRID_STEP:-32} #2=fine 16=medium 32=coarse.
 [ "$PIN_GRID_STEP" -le 0 ] && PIN_GRID_STEP=32 #precaution.
-
 _debug "PIN_GRID_STEP='$PIN_GRID_STEP'"
-#[ -z "$ICON_PLACE_START_X_GAP" ] && ICON_PLACE_START_X_GAP=32
-[ -z "$ICON_PLACE_ORIENTATION" ] && ICON_PLACE_ORIENTATION='bottom'
 
+#[ -z "$ICON_PLACE_START_X_GAP" ] && ICON_PLACE_START_X_GAP=32
+ICON_PLACE_ORIENTATION=${ICON_PLACE_ORIENTATION:-'bottom'}
+
+test "${ICON_PLACE_SPACING//[0-9]/}" && unset ICON_PLACE_SPACING
 if [ -z "$ICON_PLACE_SPACING" ] ; then
 #DriveIconsize=`grep -o 'DRVICON=.*' /etc/rc.d/functions4puppy4  | grep -o -e '[[:digit:]]*' | head -n 1`  ##+2012-11-05 added -e to grep -o
 # REM: was under the impression, that --regex would mean someting special, but is not...
 #      * is short for {0,}
 #      + is short for {1,}
-DriveIconsize=`grep -o 'DRVICON=.*' /etc/rc.d/functions4puppy4  | grep -o '[[:digit:]]\+' | head -n 1`
-
-ICON_PLACE_SPACING=$(( (( DriveIconsize + 1 ) / PIN_GRID_STEP ) * PIN_GRID_STEP ))
+DriveIconSize=`grep -o 'DRVICON=.*' /etc/rc.d/functions4puppy4  | grep -o '[[:digit:]]\+' | head -n 1`
+test "${DriveIconSize//[0-9]/}" && unset DriveIconSize
+DriveIconSize=${DriveIconsize:-48}
+ICON_PLACE_SPACING=$(( (( DriveIconSize + 1 ) / PIN_GRID_STEP ) * PIN_GRID_STEP ))
 fi
 
 ICON_PLACE_SPACING=$(( ((ICON_PLACE_SPACING + 1) / PIN_GRID_STEP ) * PIN_GRID_STEP ))
@@ -895,7 +912,7 @@ _get_max_xy
 
 
 _get_icon_xy_values(){
-#KRG
+_debug "_get_icon_xy_values: ICON_PLACE_ORIENTATION='$ICON_PLACE_ORIENTATION'"
 case $ICON_PLACE_ORIENTATION in #see "$CONFFILE"
 
   bottom)
