this_branch : Replaced scripts by mine.

diff --git a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
--- a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
+++ b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
@@ -14,7 +14,105 @@
 #v432 For HSF/ALSA and hybrid modems, append appropriate preferences to ensure correct driver selected; a substitution flag is set by HSF init script.
 #433 Consolidate usbserial modem scripts, using modules.dep for associations; track preference-replaced module.
 
+########################################################################
+#
+# CHANGES by Karl Reimer Godt
+# 01.0 : logging to file LocalLOG='/tmp/pup_event_backend_modmodprobe.log'
+# 02.0 : support for multiple modprobe.conf AND alsa.conf files
+# 03.0 : leaving a note in .conf if alsa-card-nr had changed
+# 04.0 : if module not found in --show-depends , try again with
+#        modalias without pci:|platform:|etc:
+#        example modalias 'platform:it87' becomes 'it87'
+#        2.6.34-KRG-i486-compiled-AcerLaptop-rev5 with 5 modules.* files in
+#        /lib/modules/`uname -r` without depmod-FULL [ bustbox depmod , too?? ]
+#        does not load the it87 driver automatically @boot
+#        modprobe -c | grep it87 = ''
+#
+# 06.0 : finally checking lsmod before modprobing
+#        because updates in /tmp/pup_event_module_devpath_log
+#        can be too slow (older Puppy4 series)
+#
+# 07.0 : added usage and debug func
+#
+# /dev/hda7
+# /dev/hda7:
+# LABEL="/"
+# UUID="429ee1ed-70a4-43a5-89f8-33496c489260"
+# TYPE="ext4"
+# DISTRO_NAME='LucidÂPuppy'
+# DISTRO_VERSION=218
+# DISTRO_MINOR_VERSION=00
+# DISTRO_BINARY_COMPAT='ubuntu'
+# DISTRO_FILE_PREFIX='luci'
+# DISTRO_COMPAT_VERSION='lucid'
+# DISTRO_KERNEL_PET='linux_kernel-2.6.33.2-tickless_smp_patched-L3.pet'
+# PUPMODE=2
+# SATADRIVES=''
+# PUP_HOME='/'
+# PDEV1='hda7'
+# DEV1FS='ext4'
+# LinuxÂpuppypcÂ2.6.31.14Â#1ÂMonÂJanÂ24Â21:03:21ÂGMT-8Â2011Âi686ÂGNU/Linux
+# Xserver=/usr/bin/Xorg
+# $LANG=en_US
+# today=TueÂOctÂ25Â15:38:22ÂGMT+1Â2011
+# TODO1 : usleep $(( $$ * 10 ))
+# TODO2 : $2 = -V|--verbose --stdout --xcon ~FIXED by changing
+# LocalLOG= from '/filename' to '>>/filename'
+# TODO3 : filter "buitin $MODULE"
+# TODO4 : add check for load >=2.0
+#
+########################################################################
+
+LocalLOG='/tmp/pup_event_backend_modprobe.log'
+out="$LocalLOG";err="$LocalLOG"
+#echo LocalLOG="$LocalLOG"_EOS
+
+debug(){
+#echo "$@"
+echo "$@" >> $out #2>>$err
+[ "$do" ] && echo "$@"
+[ "$dx" ] && echo "$@" >>/dev/console
+return 0  ##force returnvalue in case of following && [TEST]
+}
+
+usage(){
+echo "
+$0 [KERNEL-MODULE] [--stdout|--xcon|--help]
+
+PROGRAM gets passed MODALIAS by udevd at boottime .
+Alternatively KERNEL_MODULE to load from CLI .
+
+--stdout log to terminal
+--xcon   log to xconsole
+--help   this usage message
+"
+exit 1
+}
+
+RULEMODULE=''
+
+for content in $@ ; do
+case $content in
+--stdout) do='yes' ;;
+--xcon)   dx='yes' ;;
+--help) usage;;
+-*|--*) usage;;
+*) RULEMODULE="$content";;
+esac
+done
+
+[ -z "`echo "$@"`" -a "$MODALIAS" == "" ] && usage
+#echo "RULEMODULE='$RULEMODULE'"
+
 export LANG=C #w004
+
+until [ "`cat /proc/loadavg | cut -f 1 -d '.'`" -lt '3' ] ; do sleep 2s;done  ###+++2011-11-30
+
+if [ "`grep 'pup_event_backend_modprobe_protect \-\-module' $0`" ]; then
+pidof pup_event_backend_modprobe_protect >/dev/null || START_PROTECT_DAEMON='yes'
+#[ "$START_PROTECT_DAEMON" ] && pup_event_backend_modprobe_protect --daemon >>$out 2>>$err &
+[ "$START_PROTECT_DAEMON" ] && pup_event_backend_modprobe_protect --daemon &
+fi
 
 #NOTICE: If the full 'udev' package, with utility 'udevd' is installed, rc.sysinit
 #   will run 'udevd' instead of 'pup_event_backend_d' and this script will be used.
@@ -25,36 +123,64 @@ PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/X11R7/bin"
 KERNVER="`uname -r`"
 
 #w463 optional $1 supplied by triggered udev rule, see /etc/udev/rules.d/60-udev-modem.rules
-RULEMODULE=""
-[ $1 ] && RULEMODULE="$1"
+#RULEMODULE=""
+#[ $1 ] && RULEMODULE="$1"
 touch /tmp/pup_event_module_devpath_log
+touch /tmp/pup_event_modprobe.conf  ##+++2011-11-09 #11-22 was /tm/pup_event_modprobe.conf
+#should be done only once in rc.sysinit
+#[ "$FASTBOOTMODULESLIST" != "" ] && exit 1 #fastboot, see /etc/rc.d/MODULESCONFIG.
 
-[ "$FASTBOOTMODULESLIST" != "" ] && exit 1 #fastboot, see /etc/rc.d/MODULESCONFIG.
+TIME="date +%M.%S.%N"
+
+CONFFILE='/etc/modprobe.conf'
+[ -f /etc/modprobe.d/modprobe.conf ] && CONFFILE='/etc/modprobe.d/modprobe.conf'
+[ -f /etc/modprobe.d/puppy.conf ] && CONFFILE='/etc/modprobe.d/puppy.conf'
+ALSACONF="$CONFFILE"
+[ -f /etc/modprobe.d/alsa-base.conf ] && ALSACONF='/etc/modprobe.d/alsa-base.conf'
 
 setup_alsa_func() { #uses MODULE.
  #if a sound module, preconfigure alsa (/etc/init.d/alsa will start it)...
  if [ "`echo -n "$MODULE" | grep '^snd_'`" != "" ];then
   CNTSND=0 #v432 Reserve first available card number
-  while ! pup_event_backend_modprobe_protect --snd_card_number=$CNTSND;do
+  while ! pup_event_backend_modprobe_protect --snd_card_number=$CNTSND >>$out 2>>$err;do
    CNTSND=`expr $CNTSND + 1`
    [ $CNTSND -gt 10 ] && return 1
   done
-  pup_event_backend_modprobe_protect --lock=modprobeconf #v432 end
+  pup_event_backend_modprobe_protect --lock=modprobeconf >>$out 2>>$err #v432 end
   DPATTERN="alias snd\\-card\\-$CNTSND"
   dMODULE="`echo -n "$MODULE" | tr '_' '-'`" #v407
-  if [ "`grep "$DPATTERN" /etc/modprobe.conf`" = "" ];then
-   echo "alias snd-card-$CNTSND $dMODULE" >> /etc/modprobe.conf
-   echo "alias sound-slot-$CNTSND $dMODULE" >> /etc/modprobe.conf
+  if [ "`grep "$DPATTERN" $ALSACONF`" = "" ];then
+   echo >> $ALSACONF
+   echo '##### Added by /sbin/pup_event_backend_modprobe #####' >> $ALSACONF
+   echo '### Running kernel '"$KERNVER" >> $ALSACONF
+   echo '### Because alias entry is missing in this'  >> $ALSACONF
+   echo '### Configuration-file '"$CONFFILE" >> $ALSACONF
+   echo "alias snd-card-$CNTSND $dMODULE" >> $ALSACONF
+   echo "alias sound-slot-$CNTSND $dMODULE" >> $ALSACONF
+   echo '##### '`date`' #####' >> $ALSACONF
   else
    #for portability, check if correct sound card...
    BPATTERN="alias snd\\-card\\-$CNTSND $dMODULE" #v408
-   if [ "`grep "$BPATTERN" /etc/modprobe.conf`" = "" ];then
+   if [ "`grep "$BPATTERN" $CONFFILE`" = "" ];then
+    DateS=`date`
+    echo '##### Changed by /sbin/pup_event_backend_modprobe #####' >> $CONFFILE
+    echo '### Running kernel '"$KERNVER" >> $CONFFILE
+    echo '### Because modulename or harware had changed' >> $CONFFILE
+    echo '### Configuration-file is '"$CONFFILE" >> $CONFFILE
+    #echo '##### '`date`' #####' >> $CONFFILE
     SEDSCRIPT1="s/^\\(alias\\ snd\\-card\\-$CNTSND\\ \\).*/\\1${dMODULE}/" #v432
     SEDSCRIPT2="s/^\\(alias\\ sound\\-slot\\-$CNTSND\\ \\).*/\\1${dMODULE}/" #v432
-    sed -i -e "$SEDSCRIPT1" -e "$SEDSCRIPT2" /etc/modprobe.conf #v432
+    #sed -i -e "$SEDSCRIPT1" -e "$SEDSCRIPT2" $CONFFILE #v432
+    sed -e "$SEDSCRIPT1" -e "$SEDSCRIPT2" $CONFFILE >/tmp/$CONFFILE.2.txt
+    SEDSCRIPT3="s/^\\(alias\\ snd\\-card\\-$CNTSND\\ \\).*/\#${DateS}\\1${dMODULE}/"
+    SEDSCRIPT4="s/^\\(alias\\ sound\\-slot\\-$CNTSND\\ \\).*/\#${DateS}\\1${dMODULE}/"
+    sed -i -e "$SEDSCRIPT3" -e "$SEDSCRIPT4" $CONFFILE
+    cat /tmp/$CONFFILE.2.txt >> $CONFFILE
+    #rm /tmp/$CONFFILE.2.txt
+    echo '##### '"$DateS"' #####' >> $CONFFILE
    fi
   fi
-  pup_event_backend_modprobe_protect --unlock=modprobeconf #v432
+  pup_event_backend_modprobe_protect --unlock=modprobeconf >>$out 2>>$err #v432
  fi
 }
 
@@ -80,7 +206,7 @@ pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
  #in some cases a special hack is required, hardcoded in here...
  #8139cp is buggy...
  [ "$MODULE" = "8139cp" ] && MODULE="8139too" \
-  && ! pup_event_backend_modprobe_protect --module=$MODULE \
+  && ! pup_event_backend_modprobe_protect --module=$MODULE >>$out 2>>$err \
   && return 1 #v432
  #v2.17 another hack, mwave.ko (modem), do not load module, just the firmware,
  #as /etc/init.d/ in firmware has script that correctly loads mwave.ko...
@@ -91,7 +217,7 @@ pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
  #v2.17 intel pci numbering is peculiar, need this hack....
  if [ "$MODULE" = "ipw2200" ];then
   [ "`lspci -m -n -d 8086:1043 | cut -f 10 -d '"' | cut -b 1,2`" = "25" ] && MODULE="ipw2100" \
-   && ! pup_event_backend_modprobe_protect --module=$MODULE \
+   && ! pup_event_backend_modprobe_protect --module=$MODULE >>$out 2>>$err \
    && return 1 #'geany #v432
  fi
  #v408 pup 4.1retro, k2.6.21.7, madwifi wireless, ath_pci.ko loads then
@@ -121,7 +247,7 @@ firmware_module_func() {
   #v432 Ensure firmware installed only once.
   pup_event_backend_modprobe_protect --firmware=$FIRMPKG \
    || return 0
-   
+
   if [ -f /lib/modules/all-firmware/${FIRMPKG}.tar.gz ];then
    cp -af /lib/modules/all-firmware/${FIRMPKG}.tar.gz /tmp >/dev/null 2>&1
    cd /tmp
@@ -143,23 +269,65 @@ firmware_module_func() {
  fi
 }
 
+#echo $$ 2.0 `$TIME` 'MODALIAS='"$MODALIAS" $LocalLOG
+#echo $$ 2.0 `$TIME` 'MODALIAS='"$MODALIAS" $($LocalLOG) #does also not work with backticks
+debug "$(echo $$ 2.0 `$TIME` 'MODALIAS='"$MODALIAS")"
+
 #v432 Provide for optional preferences for internal use...
 PREFEXTRAS=""
+
 #find a matching module... (/etc/pup_event_modprobe.conf created in rc.sysinit)
 MODULE="`/sbin/modprobe --config /tmp/pup_event_modprobe.conf --show-depends $MODALIAS 2>/dev/null | tail -n 1 | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`"
+debug "$(echo $$ 3.0 `$TIME` 'MODULE='"$MODULE")"
+
+if [ "$MODULE" = "" ] ; then
+if [ "$MODALIAS" ] ; then
+MODALIAS="${MODALIAS#*:}"
+MODULE="`/sbin/modprobe --config /tmp/pup_event_modprobe.conf --show-depends $MODALIAS 2>/dev/null | tail -n 1 | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`"
+debug "$(echo $$ 3.1 `$TIME` 'MODULE='"$MODULE")" #+++changed here 2011-11-09
+###+++2011-11-27
+if [ -n "`echo "$MODULE" | grep -w '^builtin '`" ] ; then
+debug "$(echo $$ 3.2 `$TIME` Module built into the kernel .. exit 1 ..)"  ##-2011-11-30 was 'MODULE
+exit 1
+fi
+###+++2011-11-27
+fi
+fi
+#debug "$(echo $$ 3.1 `$TIME` 'MODULE='"$MODULE")"
+
 [ "$RULEMODULE" != "" ] && [ "$MODULE" = "" -o "$MODULE" = "usb_storage" ] && MODULE="$RULEMODULE" #w463 Use module from argument
-[ "$MODULE" = "" ] && exit 1
+debug "$(echo $$ 3.2 `$TIME` 'MODULE='"$MODULE")"
+
+###+++2011-11-09
+if [ -n "`echo "$FASTBOOTMODULESLIST" | grep "$MODULE"`" ] ; then
+debug "$(echo $$ 3.3 `$TIME` $MODULE in FASTBOOTMODULESLIST .. exit 1 ..)"
+exit 1
+fi
+###+++2011-11-09
+
+[ "$MODULE" = "" ] && debug "$(echo $$ 3.5 `$TIME` 'Still no MODULE .. exit 1 ..')" && exit 1
 #[ "$MODULE" = "usb_storage" ] && exit 1 #loaded explicitly in boot scripts.
 
 #v432 Ensure module procesing done only once, except for usb-storage (needed to find hybrid-device co-driver).
-[ "$MODULE" != "usb_storage" ] \
- && ! pup_event_backend_modprobe_protect --module=$MODULE \
- && exit 0
+#[ "$MODULE" != "usb_storage" ] \
+ #&& ! pup_event_backend_modprobe_protect --module=$MODULE \
+ #|| echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned errornoise" $LocalLOG && exit 0
+ ##|| echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned errornoise" $LocalLOG \
+ ##&& exit 0
+ ##&& echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned errornoise" $LocalLOG #\#
+if [ "$MODULE" != "usb_storage" ] ; then
+pup_event_backend_modprobe_protect --module=$MODULE >>$out 2>>$err
+retVal=$?
+if [ "$retVal" -ne 0 ] ; then
+debug "$(echo $$ 3.5 `$TIME` "pup_event_backend_modprobe_protect --module='$MODULE' returned $retVal")"
+exit 0
+fi
+fi
 
-case $MODALIAS in
+case "$MODALIAS" in
  pci:*)
   pci_fixup_func #w463 needs MODALIAS, MODULE, RULEMODULE
-  [ $? -ne 0 ] && exit 1
+  [ $? -ne 0 ] && debug "$(echo -e $$ 5.0 `$TIME` "\e[33m"'Error in pci_fixup_func .. exit ..'"\e[39m")" && exit 1
  ;;
  usb:*) #v432
   #v432 For USB hybrid storage/modem devices, ensure storage driver loaded, then modem driver (on repeated event, if necessary).
@@ -173,25 +341,53 @@ esac
 
 #v404 preferences list, ex rt2500usb and rt73usb both hits, then choose latter...
 modPATTERN='^'"$MODULE"':'
+
+debug "$(echo $$ 6.0 `$TIME` 'modPATTERN 2 ='"$modPATTERN")"
+
 PREFHIT="`echo -n "${PREFLIST}${PREFEXTRAS}" | tr -s ' ' | tr ' ' '\n' | grep "$modPATTERN"`" #v432
+
+debug "$(echo $$ 7.0 `$TIME` 'PREFHIT='"$PREFHIT")"
+
+
 if [ "$PREFHIT" != "" ];then
+ debug "$(echo $$ 8.0 `$TIME` 'PREFHIT='"$PREFHIT")"
  prefMODULES="`echo -e -n "$PREFHIT" | cut -f 2 -d ':' | tr '|' '\n'`"
+ debug "$(echo $$ 8.0 `$TIME` 'prefMODULES='$prefMODULES)"
  echo "blacklist $MODULE" > /tmp/pup_event_prefhit_blacklist-$$ #v432 begin
  RETRIES=0
  while [ $RETRIES -le 10 ];do
   xMODULE="`/sbin/modprobe --config /tmp/pup_event_prefhit_blacklist-$$ --show-depends $MODALIAS 2>/dev/null | tail -n 1 | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`"
-  [ "$xMODULE" = "" ] && break
+  debug "$(echo $$ 8.1 `$TIME` 'xMODULE'="$xMODULE")"
+  debug "$(echo $$ 8.1 `$TIME` 'RETIES='$RETRIES)"
+  [ "$xMODULE" = "" ] && debug "$(echo $$ 8.1.5 `$TIME` 'no xMODULE')" && break
+
   echo "blacklist $xMODULE" >> /tmp/pup_event_prefhit_blacklist-$$
   RETRIES=`expr $RETRIES + 1`
  done
+
  modPATTERN="`cat /tmp/pup_event_prefhit_blacklist-$$ | sed -e s/blacklist\ /\^/ -e s/$/\$/ | tr '\n' '|' | sed -e s/\|$//`"
+ debug "$(echo $$ 8.2 `$TIME` 'modPATTERN='"$modPATTERN")"
  xMODULE="`echo "$prefMODULES" | grep -m 1 -E "$modPATTERN"`"
+ debug "$(echo $$ 8.2 `$TIME` 'xMODULE'="$xMODULE")"
  rm /tmp/pup_event_prefhit_blacklist-$$
- [ "$xMODULE" != "" -a "$xMODULE" != "$MODULE" ] \
-  && pup_event_backend_modprobe_protect --replacedmod=$MODULE \
-  && MODULE="$xMODULE" \
-  && ! pup_event_backend_modprobe_protect --module=$MODULE \
-  && exit 0 #v433 v432 end
+
+  if [ "$xMODULE" != "" -a "$xMODULE" != "$MODULE" ] ; then
+
+ pup_event_backend_modprobe_protect --replacedmod=$MODULE >>$out 2>>$err
+ MODULE="$xMODULE"
+   debug "$(echo $$ 8.3 `$TIME` 'MODULE'="$MODULE")"
+    if ! pup_event_backend_modprobe_protect --module=$MODULE ; then
+    #echo $$ 8.3.5 `$TIME` "pup_event_backend_modprobe_protect returned errornoise '0?'" $LocalLOG
+    #exit 0 #v433 v432 end
+    debug "$(echo $$ 8.3.5 `$TIME` 'pup_event_backend_modprobe_protect --module='$MODULE)"
+    else
+    #echo $$ 8.4 `$TIME` 'pup_event_backend_modprobe_protect --module='$MODULE $LocalLOG
+    debug "$(echo $$ 8.4 `$TIME` "pup_event_backend_modprobe_protect returned errornoise '0?'")"
+    exit 0
+    fi
+  fi
+else
+debug "$(echo $$ 8.0 `$TIME` 'no preflist defined')"
 fi
 
 #installs a firmware tarball (once only. loading firmware is something else)...
@@ -199,9 +395,18 @@ firmware_module_func
 
 setup_alsa_func #MODULE and CNTSND are used in this func.
 
+[ "$START_PROTECT_DAEMON" ] && pup_event_backend_modprobe_protect --stop >>$out 2>>$err &
+
+if [ -z "`lsmod | grep "$MODULE"`" ] ; then
 #log to file. rc.modules2 needs this info to find out if any modaliases missed (also above)...
 echo "MODULE=$MODULE DEVPATH=$DEVPATH" >> /tmp/pup_event_module_devpath_log
+debug "$(echo -e $$ 9.0 `$TIME` "\e[32m"'Finally modprobing '"$MODULE""\e[39m")"
 cd /sbin #v408 rerwin thinks this is needed for slamr module.
-exec /sbin/modprobe $MODULE
+ exec /sbin/modprobe -v $MODULE
+else
 
+debug "$(echo -e $$ 9.0 `$TIME` "\e[31m"'Module '"$MODULE"' already inserted'"\e[39m")"
+exit 1
+fi
 ###END###
+#[ "$START_PROTECT_DAEMON" ] && pup_event_backend_modprobe_protect --daemon &
diff --git a/woof-code/rootfs-skeleton/usr/bin/xwin b/woof-code/rootfs-skeleton/usr/bin/xwin
--- a/woof-code/rootfs-skeleton/usr/bin/xwin
+++ b/woof-code/rootfs-skeleton/usr/bin/xwin
@@ -22,11 +22,29 @@
 #100520 attempt fix keyboard layout not getting updated.
 #100608 jemimah: added 1366x768.
 
+until [ "`cat /proc/loadavg | cut -f 1 -d '.'`" -lt '3' ] ; do sleep 2s;done  ###+++2011-11-30
+exec 2>/tmp/xwin.log.$$
+
 #NUMXWINS=`pidof xwin | wc -w` #w478
 #[ $NUMXWINS -gt 1 ] && exit   #w478
 
-[ -z $DISPLAY ] || exit #v2.11 from GuestToo.
-#echo "This script will run X windows for you..."
+XWINS=`ps -C xwin`
+NUMXWINS=$(( $(echo "$XWINS" | wc -l) -1))
+PROGPID=$$
+PROGTTY=`basename $(tty)`
+
+#[ -z $DISPLAY ] || exit #v2.11 from GuestToo.
+
+if [ -z "`echo "$XWINS" | head -n2 | tail -n 1 | grep "$PROGTTY"`" ] || [ -z "`echo "$XWINS" | head -n 2 | tail -n 1 | grep "$PROGPID"`" ] ; then
+ echo -e "\\033[0;31m""More than one instance of xwin running : $NUMXWINS -- exit""\\033[0;39m"
+ exit
+elif [ -n "$DISPLAY" ] ; then
+ echo -e "\\033[1;31m""More than one instance of X running : $DISPLAY ; exit""\\033[0;39m"
+ xmessage -bg red "More than one instance of X running : $DISPLAY -- exit"
+ exit
+else
+echo -e "\\033[1;33m""This script will run X windows for you...""\\033[0;39m"
+fi
 
 cd ~/   #v3.98 Ensure current directory is root, in case changed at command prompt, so rox icon and menu item open only at home directory. rerwin
 
@@ -46,7 +64,8 @@ if [ $1 ];then
 fi
 
 #v1.0.7
-HAVEX="`readlink /usr/bin/X`"
+HAVEX="`basename $(readlink $(which X))`"
+echo '$HAVEX='"$HAVEX"
 if [ "$HAVEX" = "XF86_SVGA" ];then
  #xf86config v3.3.6 creates config file at /etc, wrong place...
  [ -f /etc/XF86Config ] && mv -f /etc/XF86Config /etc/X11/XF86Config
@@ -55,7 +74,7 @@ fi
 #v3.90 expanded to auto run best video mode...
 if [ "$HAVEX" = "Xvesa" ];then #0.9.9
 
- if [ ! -f /tmp/videomode -a ! -f /etc/videomode ];then #v2.21
+ if [ ! -f /tmp/videomode ] ; then ###-a ! -f /etc/videomode ];then #v2.21
   ddcprobe >/tmp/ddcprobe.txt
   #weird (ddcprobe is very weird), on some hardware, edid monitor probe fails
   #every alternate run of ddcprobe...
@@ -66,10 +85,13 @@ if [ "$HAVEX" = "Xvesa" ];then #0.9.9
   esac
 
 #v3.99 begin
-  if [ -f /etc/xorgoverrides ] && grep -q -f /etc/xorgoverrides /tmp/ddcprobe.txt;then
+  if [ -f /etc/xorgoverrides ] && grep -f /etc/xorgoverrides /tmp/ddcprobe.txt;then
+   echo -e "\\033[1;34m""Starting now xorgwizard because of /etc/xorgoverrides"
+   sleep 5s
    rm -f /etc/.XLOADED 2> /dev/null #not necessary, precaution.
    #1st dialog offers to use Xvesa...
    /usr/sbin/xorgwizard
+   echo -e "\\033[1;34m""Finished xorgwizard because of xorgoverrides""\\033[0;39m"
    HAVEX="`readlink /usr/bin/X`"
    [ "$HAVEX" != "Xorg" ] && exit   #go to command line if not Xorg
   fi
@@ -78,9 +100,9 @@ fi
 #Repeat earlier tests in case Xserver now Xorg and to retain indentation levels.
 if [ "$HAVEX" = "Xvesa" ];then #0.9.9
  BASEMODE=""
- if [ ! -f /tmp/videomode -a ! -f /etc/videomode ];then #v2.21
+ if [ ! -f /tmp/videomode ];then #v2.21
 #v3.99 end
-
+ [ -f /etc/videomode ] && cp /etc/videomode /tmp/
   #v3.95 note code duplicated in xorgwizard, not efficient...
   #v3.94 detect if a Classmate PC laptop with 800x480 screen...
   #if [ "`grep 'edidfail' /tmp/ddcprobe.txt`" != "" ];then
@@ -102,29 +124,32 @@ if [ "$HAVEX" = "Xvesa" ];then #0.9.9
 
   echo -e '\nIf initialization freezes here, press ctrl-c and type "xorgwizard",\nselect "Xorg", choose monitor type and choose video mode.'   #v3.99
   grep '^oem:' /tmp/ddcprobe.txt > /tmp/ddcprobeoem.txt   #v3.99 current adapter signature
-
+  sleep 5s
   #get too many weird resolutions, maybe better just only allow these...
   #want widescreen/non-vesa resolutions only...
   VESAMODES="`Xvesa -listmodes 2>&1 | grep '^0x' | tr ':' ' ' | tr -s ' ' | cut -f 1,2 -d ' '`"
   rm /tmp/ddcprobeoem.txt  #v3.99 didn't hang in Xvesa, so delete signature
   #100608 jemimah: added 1366x768...
-  MONCHOICES="`grep -F 'timing:' /tmp/ddcprobe.txt | grep -E -v 'Apple|8514A|Mac II|\(XGA2\)' | grep -E ' 800x480@| 1024x600@| 1280x768@| 1280x800@| 1280x1024@| 1360x768@| 1366x768@| 1400x1050@| 1440x900@| 1600x1200@| 1680x1050@| 1920x1080@| 1920x1200@' | cut -f 2 -d ' ' | sort -u`"
-
+  ##MONCHOICES="`grep -F 'timing:' /tmp/ddcprobe.txt | grep -E -v 'Apple|8514A|Mac II|\(XGA2\)' | grep -E ' 800x480@| 800x600@| 1024x600@| 1024x768@| 1280x768@| 1280x800@| 1280x1024@| 1360x768@| 1366x768@| 1400x1050@| 1440x900@| 1600x1200@| 1680x1050@| 1920x1080@| 1920x1200@' | cut -f 2 -d ' ' | sort -u`"
+  MONCHOICES="`grep -F 'timing:' /tmp/ddcprobe.txt | grep -E -v 'Apple|8514A|Mac II|\(XGA2\)' |cut -f 2 -d ' ' | sort -u`"
   if [ "$MONCHOICES" != "" ];then
    MONCUTXY="`echo "$MONCHOICES" | cut -f 1 -d '@' | tr '\n' ' '`"
-
-   #v2.21 code to handle widescreen with intel video chips...
+    echo 'DBG 1 MONCHOICES: '"$MONCHOICES"
+    sleep 9s
+    #v2.21 code to handle widescreen with intel video chips...
    if [ ! -f /etc/resolutionfix ];then
-    if grep -F 'oem:' /tmp/ddcprobe.txt | grep -F -q 'Intel' ;then
+    if grep -F 'oem:' /tmp/ddcprobe.txt | grep -F 'Intel' ;then
      MISSINGXY=""
      for ONECUTXY in $MONCUTXY #ex: each field 1024x768
      do
       OPATTERN=" ${ONECUTXY}x"
       [ "`echo "$VESAMODES" | grep "$ONECUTXY"`" = "" ] && MISSINGXY="$ONECUTXY"
      done
+     echo 'DBG 2 MISSINGXY:'"$MISSINGXY"
+     sleep 9s
      if [ "$MISSINGXY" != "" ];then
-      MYXRES="`echo -n "$MISSINGXY" | cut -f 1 -d 'x'`" 
-      MYYRES="`echo -n "$MISSINGXY" | cut -f 2 -d 'x'`" 
+      MYXRES="`echo -n "$MISSINGXY" | cut -f 1 -d 'x'`"
+      MYYRES="`echo -n "$MISSINGXY" | cut -f 2 -d 'x'`"
       915resolution 38 $MYXRES $MYYRES
       #...replaces mode 38 (1024x768).
       #create something for /etc/profile to execute at bootup...
@@ -133,30 +158,42 @@ if [ "$HAVEX" = "Xvesa" ];then #0.9.9
       PPATTERN=" ${MYXRES}x${MYYRES}x"
       #BASEMOD is res that we are going to start X with...
       BASEMODE="`echo "$VESAMODES" | grep "$PPATTERN" | grep -E 'x16$|x24$|x32$' | head -n 1`"
+      echo 'DBG 3 VESAMODES:'"$VESAMODES"
+      echo 'DBG 4 PPATTERN:'"$PPATTERN"
+      echo 'DBG 5 BASEMODE:'"$BASEMODE"
+      sleep 9s
      fi
     fi
    fi
-  
+
    #find out if there is just one native mode...
    if [ "$BASEMODE" = "" ];then
-    if [ "`echo "$MONCUTXY" | wc -l`" = "1" ];then
-     QPATTERN=" ${MONCUTXY}x"
-     BASEMODE="`echo "$VESAMODES" | grep "$QPATTERN" | grep -E 'x16$|x24$|x32$' | head -n 1`"
-    fi
+    #if [ "`echo "$MONCUTXY" | wc -l`" = "1" ];then
+     QPATTERN=`echo "$MONCHOICES" | cut -f 1 -d '@' | sed 's#$#x#g' | tr '\n' '|' | sed 's#|$##'`
+     echo 'DBG 6 $QPATTERN='"$QPATTERN"
+     BASEMODE="`echo "$VESAMODES" | grep -E "$QPATTERN" | grep -E 'x16$|x24$|x32$' | head -n 1`"
+    echo 'DBG 7 $BASEMODE='"$BASEMODE"
+    sleep 9s
+    #fi
    fi
-    
+   echo 'DBG 8 BASEMODE :'"$BASEMODE"
+   sleep 9s
    if [ "$BASEMODE" != "" ];then
     echo "$BASEMODE" > /etc/videomode #no need for wizard after startup!
-	rm -f /tmp/videomode 2>/dev/null #w460 make sure can exit from X.
+	##rm -f /tmp/videomode 2>/dev/null #w460 make sure can exit from X.
    fi
   fi
 
   if [ "$BASEMODE" = "" ];then
    BASEMODE="`echo "$VESAMODES" | grep ' 800x600x16' | head -n 1`"
+   echo 'DBG 9 BASEMODE :'"$BASEMODE"
+   sleep 9s
    if [ "$BASEMODE" != "" ];then
     echo "$BASEMODE" > /tmp/videomode
    else
-    echo -n "0x0111 640x480x16" > /tmp/videomode
+   echo 'DBG 10 last resort 0x0111'
+   sleep 10s
+   echo -n "0x0111 640x480x16" > /tmp/videomode
     #...desparate, not a practical mode.
    fi
   fi
@@ -164,9 +201,10 @@ if [ "$HAVEX" = "Xvesa" ];then #0.9.9
   rm -f /tmp/Xflag #precaution.
   #...if /tmp/videomode exists, video-wizard is started in ~/.xinitrc
   #...note, if /etc/videomode exists instead, normal X startup.
-  
+ ##[ "$PUPMODE" != "5" ] &&
+ ## rm /tmp/videomode
  fi
- 
+
 fi
 
 #v411 restored after removal in v407...
@@ -241,33 +279,45 @@ fi
 ##note, could write $AGPDRIVER to /etc/modprobe.preload to load it at kernel boot.
 ##note, it also loads agpgart.ko.
 
+
 #v2.11 find out if xorg video drvr exists, else use xorg vesa...
 if [ -f /usr/bin/Xorg ];then
+
  if [ -f /etc/X11/xorg.conf ];then
   #find location of video chip drivers...
-  SPECVESA="`find /usr/lib -noleaf -mount -type f -name vesa_drv.so`"
+  SPECVESA="`find /usr/lib -noleaf -mount -type f -name vesa_drv.so | head -n1`"
+
   if [ "$SPECVESA" ];then
    DRVRSPATH="`dirname $SPECVESA`"
    #get current driver...
    DRVRCURR="`cat /etc/X11/xorg.conf | grep '#card0driver' | cut -f 2 -d '"'`" #'
+
    if [ "$DRVRCURR" ];then
     #if [ ! -f $DRVRSPATH/${DRVRCURR}_drv.so ];then
     #one driver is mtx_drv.o hmmm, okay do it this way (pakt)...
     ls -1 $DRVRSPATH/* | grep $DRVRCURR >/dev/null
+
     if [ $? -ne 0 ];then
      APATTERN="s/.*#card0driver/	Driver      \"vesa\" #card0driver/g"
+     echo "defaulting to Xorgs simple vesa driver"
      cat /etc/X11/xorg.conf | sed -e "$APATTERN" > /tmp/xorg.conf.tmp2
      sync
      cp -f /tmp/xorg.conf.tmp2 /etc/X11/xorg.conf
     fi
+
    fi
+
   fi
+
  fi
+
 fi
 
 #Puppy Xorg Video Wizard...
 if [ -f /usr/bin/Xorg ];then
+
  if [ -f /etc/X11/xorg.conf ];then
+
   if [ "`readlink /usr/bin/X`" = "Xorg" ];then
    #v2.13 video hardware profile (must be same as in xorgwizard)...
    DDCPROBE="`ddcprobe`"
@@ -292,22 +342,31 @@ PROFILEMONITOR="`echo "$DDCPROBE" | grep '^monitorid: ' | head -n 1 | cut -f 2 -
    HARDWAREPROFILE="${PROFILECHIP}${PROFILEMONITOR}"
    #find out if current xorg.conf matches this profile...
    CURRENTPROFILE="`cat /etc/X11/xorg.conf | grep '^#PuppyHardwareProfile' | cut -f 2 -d '=' | cut -f 1 -d ' '`"
+
    if [ ! "$CURRENTPROFILE" = "$HARDWAREPROFILE" ];then
     #video hardware has changed. either changed monitor or booting different PC.
     #same current xorg.conf as a profiled filename...
-    mv -f /etc/X11/xorg.conf /etc/X11/xorg.conf.${CURRENTPROFILE}
+    mv -f /etc/X11/xorg.conf /etc/X11/xorg.conf.${CURRENTPROFILE}  ##xorg.conf does not exists anymore
     #if a previous profiled filename for new hardware, use that...
     [ -f /etc/X11/xorg.conf.${HARDWAREPROFILE} ] && cp -af /etc/X11/xorg.conf.${HARDWAREPROFILE} /etc/X11/xorg.conf
    fi
-  fi
- fi
+
+  fi ##readlink=Xorg
+
+ fi ##-f /etc/X11/Xorg.conf
+
  if [ ! -f /etc/X11/xorg.conf ];then
+  echo "Starting now xorgwizard because /etc/X11/xorg.conf does not exists"
+  sleep 5s
   rm -f /etc/.XLOADED 2> /dev/null #not necessary, precaution.
   #1st dialog offers to use Xvesa...
   /usr/sbin/xorgwizard
+  echo "Finished running xorgwizard through xwin"
+  sleep 5s
   HAVEX="`readlink /usr/bin/X`"
   [ "$HAVEX" = "Xvesa" ] && exec xwin #w482 need to restart xwin.
  fi
+
 fi
 
 #v1.0.7 J_Reys idea (see note further down)...
@@ -415,7 +474,7 @@ fi
 #fi
 
 #v424 bad hack, i somehow get /dev/mouse pointing to psaux when chose a serial mouse, don't know why...
-[ "`grep 'ttyS' /etc/mousedevice`" != "" ] && ln -snf $MOUSEDEV /dev/mouse
+##[ "`grep 'ttyS' /etc/mousedevice`" != "" ] && ln -snf $MOUSEDEV /dev/mouse
 
 #100520 attempt fix keyboard layout not getting updated...
 [ ! -f /etc/keymap ] && echo -n "us" > /etc/keymap #maybe lupu needs this.
@@ -474,12 +533,17 @@ case $HAVEX in
   #Puppy 0.8.4 no need for startx script...
   VIDFREQ="`echo -n "$VIDSCRN" | cut -f 4 -d "x"`"
   if [ ! "$VIDFREQ" ];then
+   echo -e "\\033[0;32m""Xvesa VIDFREQ=$VIDFREQ : VIDMODE=$VIDMODE VIDSCRN=$VIDSCRN""\e[0;39m"
+   sleep 5s
    echo "$VIDMODE" > /tmp/currentvideomode
    #w460 added -fp and -sp options...
+   ##/usr/bin/xinit /root/.xinitrc -- -mode $VIDMODE $XEXTRAOPTIONS -fp /usr/share/X11/fonts/misc/,/usr/share/X11/fonts/TTF/,/usr/share/X11/fonts/Type1/ $SPOPTION > /tmp/xerrs.log 2>&1
    /usr/bin/xinit /root/.xinitrc -- -mode $VIDMODE $XEXTRAOPTIONS -mouse /dev/mouse,$MOUSEBUTTONS -fp /usr/share/X11/fonts/misc/,/usr/share/X11/fonts/TTF/,/usr/share/X11/fonts/Type1/ $SPOPTION > /tmp/xerrs.log 2>&1
   else
    #also, want to have adjustable frequency, VIDSCRN=widthxheightxdepthxfreq...
+   echo -e "\\033[0;31m""Xvesa VIDSCRN=$VIDSCRN VIDMODE=$VIDMODE VIDFREQ=$VIDFREQ""\e[0;39m"
    echo "$VIDSCRN" > /tmp/currentvideomode
+   ##/usr/bin/xinit /root/.xinitrc -- -screen $VIDSCRN $XEXTRAOPTIONS -fp /usr/share/X11/fonts/misc/,/usr/share/X11/fonts/TTF/,/usr/share/X11/fonts/Type1/ $SPOPTION > /tmp/xerrs.log 2>&1
    /usr/bin/xinit /root/.xinitrc -- -screen $VIDSCRN $XEXTRAOPTIONS -mouse /dev/mouse,$MOUSEBUTTONS -fp /usr/share/X11/fonts/misc/,/usr/share/X11/fonts/TTF/,/usr/share/X11/fonts/Type1/ $SPOPTION > /tmp/xerrs.log 2>&1
   fi
   ;;
@@ -511,8 +575,14 @@ case $HAVEX in
   /usr/bin/xinit /root/.xinitrc --  > /tmp/xerrs.log 2>&1
   ;;
 esac
+
+if [ -z "`ps | grep 'X' | grep -v 'grep'`" ] ; then
 echo -n "false" > /etc/.XLOADED #see note above.
+fi
+
 #...if PC hung, run xorgwizard at next bootup (see further up).
+
+XWINCOUNT=$((XWINCOUNT-1))
 
 echo 'Exited from X. Type "xwin [fvwm95|jwm]" to restart X ([ ] mean optional).'
 echo '(To shutdown PC type "poweroff", to reboot PC type "reboot")'
@@ -540,11 +610,12 @@ fi
 ##not the best, but here is a workaround...
 #NUMXWINS=`pidof xwin | wc -w` #see above and below...
 
-if [ "$HAVEX" = "Xvesa" ];then
- if [ -e /tmp/videomode ];then
-  exec xwin #restart X.
- fi
-fi
+##if [ "$HAVEX" = "Xvesa" ];then
+ ##if [ -e /tmp/videomode ];then
+ ##### echo '/tmp/videomode exists'
+ #### ##exec xwin #restart X.
+## fi
+##fi
 
 #Shutdown menu calls wmreboot, wmpoweroff, wmexit or restartwm, which create this file...
 if [ -f /tmp/wmexitmode.txt ];then
@@ -569,6 +640,8 @@ if [ -f /tmp/wmexitmode.txt ];then
     export LANG=$NEWLANG
    fi
   fi
+ wmexit
+ sleep 2s
  exec xwin
 fi
 
