this_branch : Replaced scripts by #!/bin/bash
GOAL='/root/GitHub.d/KarlGodt_ForkWoof/woof-code/rootfs-skeleton'

rm -f /root/PUPPYscripts.list
for i in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/X11/bin;
do grep -I -H -m1 -i -E 'BK|Kauler|Barry|B\.K\.|T2 |t\-2|rxvt' /* | grep '#' >>/root/PUPPYscripts.list;
done

OldIFS="
"
IFS=':'
while read filename rest
do

dn=""
echo "" "//"
cp -a --remove-destination "" "//"

done</root/PUPPYscripts.list

IFS=""

from the current system . A few outsiders are in here
like /usr/local/bin/asciidoc and similar . Also quite
a few too many backup files.
TODO : Add /etc .

diff --git a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
--- a/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
+++ b/woof-code/rootfs-skeleton/sbin/pup_event_backend_modprobe
@@ -7,48 +7,162 @@
 #v408 hack for madwifi ath_pci in 4.1retro. Alsa fix.
 #w004 LANG=C, faster. /bin/ash, even faster.
 #w463 rerwin: Correct override extraction of module name. Add use of optional first argument as MODULE, to support special udev rules added for hardware (modems) not automatically detected by the kernel.
-#w478 support firmware in dirs, not .tar.gz tarballs.
+#w478 support firmware in LocalLOGs, not .tar.gz tarballs.
 #v424 For hybrid modem devices, select modem driver instead of storage driver when both are found by modprobe.
 
+########################################################################
+#
+# CHANGES by Karl Reimer Godt
+# 01.0 : support for more modprobe||alsa.conf files
+# 02.0 : checks if files are existant &&|| readable
+# 03.0 : added logfile $LocalLOG
+# 04.0 : support for more bootparameters : /tmp/alsa.flg created ?
+#        params=all , boot_sound_cards
+# 05.0 : changed pup_event_modprobe.conf -> pup_event_skiplist.conf in /tmp
+#        also in /sbin/init AND /etc/rc.d/rc.sysinit
+# 06.0 : changed the nameing of vars in setup_alsa_func a little
+# 07.0 : added fake pup_event_skiplist.conf
+#
+# 10.0 : added logging of modprobe -v output
+#
+# /dev/hda8:
+# LABEL="MacPup431_O2"
+# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
+# TYPE="ext3"
+# DISTRO_NAME='Puppy'
+# DISTRO_VERSION=431
+# DISTRO_BINARY_COMPAT='puppy'
+# DISTRO_FILE_PREFIX='pup'
+# DISTRO_COMPAT_VERSION='4'
+# PUPMODE=2
+# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
+# PUP_HOME='/'
+# SATADRIVES='·'
+# USBDRIVES='·sda·'
+# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
+# X·Window·System·Version·1.3.0
+# Release·Date:·19·April·2007
+# X·Protocol·Version·11,·Revision·0,·Release·1.3
+# Build·Operating·System:·UNKNOWN·
+# Current·Operating·System:·Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686
+# Build·Date:·28·November·2007
+# $LANG=de_DE@euro
+# today=Fr·28.·Okt·14:04:35·GMT+1·2011
+# TODO1 : cat /tmp/pup_event_alsa_cnt was empty should default to 0 if empty ~FIXED
+# TODO2 : make grep '-pattern' more reliable ~FIXED
+# TODO3 : check what makes logfile dissapearing @/sbin/init->rc.sysinit
+# TODO4 : debug firmware func
+#
+########################################################################
+
+
 export LANG=C #w004
+
+CONFFILE='/etc/modprobe.conf'
+[ -f /etc/modprobe.d/modprobe.conf ] && CONFFILE='/etc/modprobe.d/modprobe.conf'
+[ -f /etc/modprobe.d/puppy.conf ] && CONFFILE='/etc/modprobe.d/puppy.conf'
+ALSACONF="$CONFFILE"
+[ -f /etc/modprobe.d/alsa-base.conf ] && ALSACONF='/etc/modprobe.d/alsa-base.conf'
 
 #NOTICE: If the full 'udev' package, with utility 'udevd' is installed, rc.sysinit
 #   will run 'udevd' instead of 'pup_event_backend_d' and this script will be used.
 
-. /etc/rc.d/PUPSTATE
-. /etc/rc.d/MODULESCONFIG
+[ -r /etc/rc.d/PUPSTATE ] && . /etc/rc.d/PUPSTATE
+[ -r /etc/rc.d/MODULESCONFIG ] && . /etc/rc.d/MODULESCONFIG
 PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/X11R7/bin"
 KERNVER="`uname -r`"
 CNTSND=0 #v405
 #w463 optional $1 supplied by triggered udev rule, see /etc/udev/rules.d/60-udev-modem.rules
 RULEMODULE=""
+
+LocalLOG=''
+#[ -n "`pidof /sbin/init`" ] && LocalLOG='> /dev/console'
+#[ -n "`ps | grep '/sbin/init' | grep -v 'grep'`" ] && LocalLOG='> /dev/console'
+#LocalLOG='>> /tmp/p_e_b_m.log.1'
+LocalLOG='/tmp/pup_eve_bac_mod.log'
+TIME="date +%M.%S.%N"
+
+
+echo $$ 01.0 `$TIME` '$1='"$1" >> $LocalLOG
+
 [ $1 ] && RULEMODULE="$1"
+RULEMODULE=`echo "$RULEMODULE" | tr '-' '_'`
 touch /tmp/pup_event_module_devpath_log
 
-[ "$FASTBOOTMODULESLIST" != "" ] && exit 1 #fastboot, see /etc/rc.d/MODULESCONFIG.
+###+++2011_10_28
+[ ! -f /tmp/pup_event_modprobe.conf ] && echo 'blacklist damn-module' > /tmp/pup_event_modprobe.conf
+[ ! -f /tmp/pup_event_skiplist.conf ] && echo 'blacklist damn-module' > /tmp/pup_event_skiplist.conf  #+-+2011-11-13 BUG was > /tmp/pup_event_modprobe.conf
+[ ! -f /tmp/pup_event_blacklist.conf ] && echo 'blacklist damn-module' > /tmp/pup_event_blacklist.conf #+-+2011-11-13 BUG was > /tmp/pup_event_modprobe.conf
+###+++2011_10_28
+
+
+
+[ "$FASTBOOTMODULESLIST" != "" ] && echo $$ 01.5 `$TIME` 'FASTMODLST .. exit ..' >> $LocalLOG && exit 1 #fastboot, see /etc/rc.d/MODULESCONFIG.
 
 setup_alsa_func() { #uses MODULE.
  #if a sound module, preconfigure alsa (/etc/init.d/alsa will start it)...
- if [ "`echo -n "$MODULE" | grep '^snd_'`" != "" ];then
-  CNTSND="`cat /tmp/pup_event_alsa_cnt`"
-  DPATTERN="alias snd\\-card\\-$CNTSND"
-  dMODULE="`echo -n "$MODULE" | tr '_' '-'`" #v407
-  if [ "`grep "$DPATTERN" /etc/modprobe.conf`" = "" ];then
-   echo "alias snd-card-$CNTSND $dMODULE" >> /etc/modprobe.conf
-   echo "alias sound-slot-$CNTSND $dMODULE" >> /etc/modprobe.conf
+ #if [ "`echo -n "$MODULE" | grep '^snd_'`" != "" ];then
+  CNTSND="`cat /tmp/pup_event_alsa_cnt 2>/dev/null | sed 's/[^0-9]//g`"  ##+2011_10_28 added sed part 2011_10_31 added 2>/dev/null
+  [ -z "$CNTSND" ] && CNTSND=0  ##+++2011_10_28
+
+  if [ -f /tmp/alsa.flg ] ; then
+   if [ -z "`grep 'all' /tmp/alsa.flg`" ] ; then
+    . /tmp/alsa.flg
+    if [ "$boot_sound_cards" ] ; then
+     if [ -z "`echo "$boot_sound_cards" | grep "$CNTSND"`" ] ; then
+      echo $$ 9.0 `$TIME` "snd-card-$CNTSND disabled on kernel line .. exit .." >> $LocalLOG
+      exit
+     fi
+    fi
+   fi
+  fi
+
+  #DPATTERN="alias snd\\-card\\-$CNTSND"
+  grepNrPATTERN="alias snd\\-card\\-$CNTSND"
+  #dMODULE="`echo -n "$MODULE" | tr '_' '-'`" #v407  ##+-+2011_10_28
+  #dMODULE=${MODULE//_/\\-}  ##+++2011_10_28 to make grep more reliable
+  grepPattern=${MODULE//_/\\-}
+  realModuleName=${MODULE//_/-}
+  #echo $$ 09.0 `$TIME` 'CNTSND='"$CNTSND"' dMODULE='"$dMODULE"'_EOS' >> $LocalLOG
+  echo $$ 09.0 `$TIME` 'CNTSND='"$CNTSND"' grepPattern='"$grepPattern"'_EOS'
+
+  if [ "`grep "$grepNrPATTERN" $ALSACONF`" = "" ];then
+   echo 'Adding '"alias snd-card-$CNTSND $realModuleName"' to '"$ALSACONF"' because entry is missing' >> $LocalLOG
+   echo >> $ALSACONF
+   echo '##### Added by /sbin/pup_event_backend_modprobe #####' >> $ALSACONF
+   echo '### Running kernel '"$KERNVER" >> $ALSACONF
+   echo '### Because alias entry is missing in this'  >> $ALSACONF
+   echo '### Configuration-file '"$CONFFILE" >> $CONFFILE
+   echo "alias snd-card-$CNTSND $realModuleName" >> $ALSACONF
+   echo "alias sound-slot-$CNTSND $realModuleName" >> $ALSACONF
+   echo '##### '`date`' #####' >> $ALSACONF
+
   else
+
    #for portability, check if correct sound card...
-   BPATTERN="alias snd\\-card\\-$CNTSND $dMODULE" #v408
-   if [ "`grep "$BPATTERN" /etc/modprobe.conf`" = "" ];then
-    grep -v "$DPATTERN" /etc/modprobe.conf > /tmp/modprobe.conf
-    cp -f /tmp/modprobe.conf /etc/modprobe.conf
-    echo "alias snd-card-$CNTSND $dMODULE" >> /etc/modprobe.conf
-    echo "alias sound-slot-$CNTSND $dMODULE" >> /etc/modprobe.conf
+   BPATTERN="alias snd\\-card\\-$CNTSND $grepPattern" #v408
+   CPATTERN='alias snd-card-'"$CNTSND $realModuleName"
+
+   if [ "`grep "$BPATTERN" $CONFFILE`" = "" ];then
+
+    echo 'Creating new /tmp/modprobe.conf.setup_alsa_func file because of '"$CPATTERN"' had changed' >> $LocalLOG
+    grep -v "$grepNrPATTERN" "$CONFFILE" > /tmp/modprobe.conf.setup_alsa_func
+    cp -f /tmp/modprobe.conf.setup_alsa_func $CONFFILE
+    #rm -f /tmp/modprobe.conf.setup_alsa_func
+
+    echo >> $CONFFILE
+    echo '##### Changed by /sbin/pup_event_backend_modprobe #####' >> $CONFFILE
+    echo '### Running kernel '"$KERNVER" >> $ALSACONF
+    echo '### Because modulename or harware had changed' >> $CONFFILE
+    echo '### Configuration-file is '"$CONFFILE" >> $CONFFILE
+    echo "alias snd-card-$CNTSND $realModuleName" >> $CONFFILE
+    echo "alias sound-slot-$CNTSND $realModuleName" >> $CONFFILE
+    echo '##### '`date`' #####' >> $CONFFILE
    fi
   fi
   CNTSND=`expr $CNTSND + 1`
   echo -n "$CNTSND" > /tmp/pup_event_alsa_cnt
- fi
+ #fi
 }
 
 pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
@@ -87,73 +201,170 @@ pci_fixup_func() { #w463 needs MODALIAS, MODULE, RULEMODULE
 }
 
 firmware_module_func() {
+echo $$ 07.0 `$TIME` 'STARTING firmware_module_func' >> $LocalLOG
  #global MODULE is name of module, global KERNVER.
  altMODULE="`echo -n "$MODULE" | tr '_' '-'`"
  FPATTERN='[:,]'"${MODULE}"'\.ko|[:,]'"${altMODULE}"'\.ko'
  FIRMPKG="`cat /etc/modules/firmware.dep.$KERNVER  | grep -v '^#' | grep ':' | grep -E "$FPATTERN" | cut -f 1 -d ':' | head -n 1`"
  if [ "$FIRMPKG" != "" ];then
+ echo $$ 07.1 `$TIME` "FOUND FIRMPKG=$FIRMPKG" >> $LocalLOG
   if [ -f /lib/modules/all-firmware/${FIRMPKG}.tar.gz ];then
-   cp -af /lib/modules/all-firmware/${FIRMPKG}.tar.gz /tmp >/dev/null 2>&1
+   cp -af /lib/modules/all-firmware/${FIRMPKG}.tar.gz /tmp >/dev/null #2>&1
    cd /tmp
-   tar -zxf ${FIRMPKG}.tar.gz >/dev/null 2>&1
+   tar -zxf ${FIRMPKG}.tar.gz >/dev/null #2>&1
   fi
   if [ -d /tmp/${FIRMPKG} ];then
-   cp -a --remove-destination /tmp/${FIRMPKG}/* / 2>/dev/null
+   cp -a --remove-destination /tmp/${FIRMPKG}/* / #2>/dev/null
   fi
   #in case firmware is not a .tar.gz tarball...
   if [ -d /lib/modules/all-firmware/${FIRMPKG} ];then #w478
-   cp -a --remove-destination /lib/modules/all-firmware/${FIRMPKG}/* / 2>/dev/null
+   cp -a --remove-destination /lib/modules/all-firmware/${FIRMPKG}/* / #2>/dev/null
   fi
   #comment-out the firmware pkg entry, so it only installs once...
   R1PATTERN="s/^${FIRMPKG}:/#${FIRMPKG}:/"
   DEPUPDATED="`sed -e "$R1PATTERN" /etc/modules/firmware.dep.$KERNVER`"
-  echo "$DEPUPDATED" > /etc/modules/firmware.dep.$KERNVER
+  echo "$DEPUPDATED" > /etc/modules/firmware.dep.$KERNVER  #>
+  ###+++2011-11-12
+  ##SIMPLE:
+  if [ -f /etc/init.d/${FIRMPKG} ] ; then
+  chmod 0755 /etc/init.d/${FIRMPKG}  #would need rename of file(s) to match
+  fi
+  ##TRUE:)
+  find /etc/init.d -type f -iname "*$FIRMPKG*" -exec chmod 0755 {} \;  ##+2011-12-18 added -type f
+  if [ -f /lib/firmware/${FIRMPKG}/pinstall.${FIRMPKG}.sh ] ; then
+  cp /lib/firmware/${FIRMPKG}/pinstall.${FIRMPKG}.sh /
+  fi
+  ###+++2011-11-12
   #execute any post-install script...
   if [ -f /pinstall.${FIRMPKG}.sh ];then
    cd /
-   /pinstall.${FIRMPKG}.sh >/dev/null 2>&1 #execute script.
-   rm -f /pinstall.${FIRMPKG}.sh >/dev/null 2>&1
+   chmod +x /pinstall.${FIRMPKG}.sh  ##+++2011-12
+   /pinstall.${FIRMPKG}.sh >/dev/null #2>&1 #execute script.
+   rm -f /pinstall.${FIRMPKG}.sh #>/dev/null 2>&1
   fi
+
  fi
+echo $$ 07.9 `$TIME` 'FINISHIED firmware_module_func' >> $LocalLOG
 }
 
+echo $$ 02.0 `$TIME` 'MODALIAS='"$MODALIAS" >> $LocalLOG
+
 #find a matching module... (/etc/pup_event_modprobe.conf created in rc.sysinit)
-MODULES="`/sbin/modprobe --config /tmp/pup_event_modprobe.conf --show-depends $MODALIAS 2>/dev/null | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`" #v424
+MODULES="`/sbin/modprobe --config /tmp/pup_event_skiplist.conf --show-depends $MODALIAS 2>/dev/null | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`" #v424
 MODULE="`echo "$MODULES" | tail -n 1`" #v424
-[ "$MODULE" = "usb_storage" ] && [ "`echo "$MODULES" | grep '^usbserial$'`" != "" ] && MODULE="`echo "$MODULES" | grep -v -E '^usb_storage$|^usbcore$' | tail -n 1`" #v424
+#[ "$MODULE" = "usb_storage" ] && [ "`echo "$MODULES" | grep '^usbserial$'`" != "" ] && MODULE="`echo "$MODULES" | grep -v -E '^usb_storage$|^usbcore$' | tail -n 1`" #v424
+echo $$ 03.0 `$TIME` 'MODULE='"$MODULE" >> $LocalLOG
+
 [ "$MODULE" = "" ] && [ "$RULEMODULE" != "" ] && MODULE="$RULEMODULE" #w463 Use module from argument
 
-[ "$MODULE" = "" ] && exit 1
+echo $$ 03.0 `$TIME` 'MODULE='"$MODULE" >> $LocalLOG
+
+if [ -z "$MODULE" ] ; then
+grepPAT=${MODALIAS#*:} ## ${MODALIAS/*:/}
+MODULES="`/sbin/modprobe --config /tmp/pup_event_skiplist.conf --show-depends $grepPAT 2>/dev/null | rev | cut -f 1 -d '/' | rev | sed 's/\.ko//g' | tr '-' '_'`"
+MODULE="`echo "$MODULES" | tail -n 1 | sed 's/^[[:blank:]]*// ; s/[[:blank:]]*$//'`"
+echo $$ 03.5 `$TIME` 'MODULE='"$MODULE" >> $LocalLOG
+fi
+
+[ -n "`echo "$MODULE" | grep -i 'builtin'`" ] && echo $$ 03.5 `$TIME` 'Module builtin .. exit ..' >> $LocalLOG && exit 1
+[ "$MODULE" = "" ] && echo $$ 03.5 `$TIME` 'Still no MODULE .. exit ..' >> $LocalLOG && exit 1
+
 #[ "$MODULE" = "usb_storage" ] && exit 1 #loaded explicitly in boot scripts.
 modPATTERN='^'"${MODULE}"'$'
-[ "`cat /tmp/pup_event_module_devpath_log | cut -f 1 -d ' ' | cut -f 2 -d '=' | grep "$modPATTERN"`" != "" ] && exit 0 #duplicate module.
+echo $$ 04.0 `$TIME` 'modPATTERN 1 ='"$modPATTERN" >> $LocalLOG
+
+usleep $(( $$ * 10 ))
+
+#[ "`cat /tmp/pup_event_module_devpath_log | cut -f 1 -d ' ' | cut -f 2 -d '=' | grep "$modPATTERN"`" != "" ] && echo 'Duplicate module ..exit ..' >> $LocalLOG && exit 0 #duplicate module.
+if [ "`cat /tmp/pup_event_module_devpath_log | cut -f 1 -d ' ' | cut -f 2 -d '=' | grep "$modPATTERN"`" != "" ] ; then
+
+FM=`find /dev/.udev/failed | grep "$modPATTERN"`  #2>dev/null 30.6 kernel no failed directory ???
+
+if [ -z "$FM" ] ; then
+echo $$ 04.5 `$TIME` 'Duplicate module ..  exit ..' >> $LocalLOG && exit 0 #duplicate module.
+
+else
+
+echo $$ 04.5 `$TIME` "\e[31m"'udevd seems to have failed loading '"$modPATTERN""\e[39m" >> $LocalLOG
+fi
+
+fi
+
 
 case $MODALIAS in
  pci:*)
   pci_fixup_func #w463 needs MODALIAS, MODULE, RULEMODULE
-  [ $? -ne 0 ] && exit 1
+  [ $? -ne 0 ] && echo -e $$ 5.0 `$TIME` "\e[33m"'Error in pci_fixup_func .. exit ..'"\e[39m" >> $LocalLOG && exit 1
  ;;
 esac
 
 #v404 preferences list, ex rt2500usb and rt73usb both hits, then choose latter...
 modPATTERN='^'"$MODULE"':'
+echo $$ 06.0 `$TIME` 'modPATTERN 2 ='"$modPATTERN" >> $LocalLOG
 PREFHIT="`echo -n "$PREFLIST" | tr ' ' '\n' | grep "$modPATTERN"`"
+echo $$ 06.1 `$TIME` 'PREFHIT='"$PREFHIT" >> $LocalLOG
+
 if [ "$PREFHIT" != "" ];then
  PREFMOD="`echo -n "$PREFHIT" | cut -f 2 -d ':'`"
  echo "blacklist $MODULE" > /tmp/pup_event_prefhit_blacklist
  xMODULE="`/sbin/modprobe --config /tmp/pup_event_prefhit_blacklist --show-depends $MODALIAS 2>/dev/null | tail -n 1 | rev | cut -f 1 -d '/' | rev | cut -f 1 -d '.' | tr '\-' '_'`"
  [ "$xMODULE" != "" ] && [ "$xMODULE" != "$MODULE" ] && MODULE="$xMODULE"
+ echo $$ 06.5 `$TIME` MODULE=$MODULE >> $LocalLOG
 fi
 
 #installs a firmware tarball (once only. loading firmware is something else)...
 firmware_module_func
 
+if [ "`echo -n "$MODULE" | grep -E '^snd[-_]|^snd[-_]pcsp|^pcspkr'`" != "" ] ; then
+if [ -f /tmp/alsa.flg ] ; then
+if [ -n "`grep 'noalsa' /tmp/alsa.flg`" ] ; then
+echo $$ 08.0 `$TIME` "Detected $MODULE , but booted with 'noalsa' .. exit .." >> $LocalLOG
+exit
+#else
+#echo $$ 08.0 `$TIME` "Starting setup_alsa_func ..." >> $LocalLOG
+#setup_alsa_func
+fi
+#else
+#echo $$ 08.0 `$TIME` "Starting setup_alsa_func ..." >> $LocalLOG
+#setup_alsa_func #MODULE and CNTSND are used in this func.
+fi
+echo $$ 08.0 `$TIME` "Starting setup_alsa_func ..." >> $LocalLOG
 setup_alsa_func #MODULE and CNTSND are used in this func.
+fi
+
+if [ "`echo -n "$MODULE" | grep -E 'fb$|nouveau'`" != "" ] ; then
+if [ -f /tmp/framebuffer.flg ] && [ -n "`grep 'nofb' /tmp/framebuffer.flg`" ] ; then
+echo $$ 10.0 `$TIME` "Bootparameter 'nofb' .. exit .." >> $LocalLOG
+exit
+fi
+fi
+
+if [ "$MODULE" = "fbcon" ] ; then
+if [ -f /tmp/fbcon.flg ] && [ -n "`grep 'nofbcon' /tmp/fbcon.flg`" ] ; then
+echo $$ 10.0 `$TIME` "Bootparameter 'nofbcon' .. exit .." >> $LocalLOG
+exit
+fi
+fi
 
 #log to file. rc.modules2 needs this info to find out if any modaliases missed (also above)...
-echo "MODULE=$MODULE DEVPATH=$DEVPATH" >> /tmp/pup_event_module_devpath_log
-
 cd /sbin #v408 rerwin thinks this is needed for slamr module.
-exec /sbin/modprobe $MODULE
-
+if [ -z "`lsmod | grep "$MODULE"`" ] ; then
+echo "MODULE=$MODULE DEVPATH=$DEVPATH" >> /tmp/pup_event_module_devpath_log
+echo $$ 10.0 `$TIME` "\e[32m"'Finally modprobing '"$MODULE""\e[39m" >> $LocalLOG
+ ###+++2011_10_28
+ #exec /sbin/modprobe -v $MODULE >/tmp/$MODULE.txt.$$ 2>&1
+ #/sbin/modprobe -v $MODULE >/tmp/pup-$MODULE.txt.$$ 2>&1
+ /sbin/modprobe -v --first-time $MODULE >/tmp/pup-$MODULE.txt.$$ 2>&1  ##2011_10_31 added --first-time
+ lines=`cat /tmp/pup-$MODULE.txt.$$| wc -l`
+ for i in `seq 1 $lines` ; do
+ paTTern="$$ 10.$i `$TIME`"
+ sed -i "$i s/\(.*\)/$paTTern \1/" /tmp/pup-$MODULE.txt.$$
+ done
+ cat /tmp/pup-$MODULE.txt.$$ >> $LocalLOG
+ rm -f /tmp/pup-$MODULE.txt.$$
+ ###+++2011_10_28
+else
+echo $$ 10.0 `$TIME` "\e[31m"'Module '"$MODULE"' already inserted'"\e[39m" >> $LocalLOG
+fi
 ###END###
+exit
diff --git a/woof-code/rootfs-skeleton/usr/sbin/alsaconf b/woof-code/rootfs-skeleton/usr/sbin/alsaconf
--- a/woof-code/rootfs-skeleton/usr/sbin/alsaconf
+++ b/woof-code/rootfs-skeleton/usr/sbin/alsaconf
@@ -18,7 +18,7 @@
 #
 #BK hacked for puppy linux 4.02, may 2008.
 #v425 fix for busybox depmod.
-
+exec 2>/tmp/alsawizard.err.log
 #v425 BK
 #this script requires the full depmod...
 if [ "`which depmod-FULL`" != "" ];then
@@ -482,8 +482,8 @@ Technical: \"/etc/init.d/alsa start\" will be used to
 
 # Exit function
 acex() {
-  cleanup
-  clear
+  #cleanup
+  #clear
   exit $1
 }
 
@@ -507,9 +507,9 @@ cleanup () {
     killall -9 aplay arecord >/dev/null 2>&1
     /sbin/modprobe -r isapnp >/dev/null 2>&1
     /sbin/modprobe -r isa-pnp >/dev/null 2>&1
-    rm -f "$TMP" "$addcfg" "$FOUND" "$DUMP"
+    # rm -f "$TMP" "$addcfg" "$FOUND" "$DUMP"
 }
-trap cleanup 0 
+#trap cleanup 0 
 
 TMP=`mktemp -q /tmp/alsaconf.XXXXXX`
 if [ $? -ne 0 ]; then
@@ -925,7 +925,7 @@ If you have a big amplifier, lower your volumes or say no.
 ")
       if $DIALOG --yesno "$msg" 13 65 
       then
-          clear
+          #clear
 	  echo
 	  #aplay -N $TESTSOUND
       #BK two-barks gets truncated, -N option causes it...
@@ -937,7 +937,7 @@ If you have a big amplifier, lower your volumes or say no.
 	xecho "Saving the mixer setup used for this in /etc/asound.state."
 	$sbindir/alsactl store
     fi
-    clear
+   # clear
     xecho "
 ===============================================================================
 
@@ -1425,5 +1425,5 @@ else
     fi
 fi
 
-rm -f "$FOUND" "$DUMP"
+#rm -f "$FOUND" "$DUMP"
 exit 0
diff --git a/woof-code/rootfs-skeleton/usr/sbin/filemnt b/woof-code/rootfs-skeleton/usr/sbin/filemnt
--- a/woof-code/rootfs-skeleton/usr/sbin/filemnt
+++ b/woof-code/rootfs-skeleton/usr/sbin/filemnt
@@ -1,8 +1,10 @@
 #!/bin/bash
-##############  ROX app.: Click image files to mount & unmount.	by: Terry Becker	aka: SunBurnt
-##############	File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
+##############  ROX app.: Click image files to mount & unmount. by: Terry Becker    aka: SunBurnt
+##############  File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
 #v423 detect wrong squashfs version 3.x or 4.x.
 #v424 advise of sfs-version-converter.
+
+exec 1>>/tmp/filemnt.log 2>&1
 
 #v423...
 KERNELVER="`uname -r`"
@@ -11,17 +13,24 @@ SFSSTR='squashfs, version 3'
 [ $KERNELSUBVER -gt 28 ] && SFSSTR='squashfs, version 4'
 
  imgFile="$1"
- if [ -z "$imgFile" ] ;then exit 1 ;fi
- if [ "`dirname $imgFile`" = '\.' ] ;then
-  imgFile="`pwd``echo $imgFile |sed 's/^\.//'`"
- fi
- MntPt='/mnt/'`echo "$imgFile" |sed "s#^\.##g" |sed "s#/#+#g"`
- 
+ if [ -z "$imgFile" ] ;then exit 1 ;fi #1
 
-if [ 1 -eq 2 ] ;then	##############################################	JUMP OVER this SECTION.
+ if [ "`basename $imgFile`" = 'initrd' ] ;then gzip -9 $imgFile ;fi # 11
+ if [ "`basename $imgFile`" = 'initrd.gz' ] ;then gzip -9 $imgFile ;fi # 111
+
+
+ if [ "`dirname $imgFile`" = '\.' ] ;then # 2
+  imgFile="`pwd``echo $imgFile |sed 's/^\.//'`"
+ fi # 2
+
+
+ MntPt='/mnt/'`echo "$imgFile" |sed "s#^\.##g" |sed "s#/#+#g"`
+ MntPt='/mnt/'`basename "$imgFile"`.$$
+
+if [ 1 -eq 2 ] ;then    ##############################################  JUMP OVER this SECTION.
 
  loMnts="`mount |grep '/dev/loop' |awk '{print $1}'`"
- echo "$loMnts" |while read LOOP					### test if file's mounted
+ echo "$loMnts" |while read LOOP                    ### test if file's mounted
  do
    loFile="`losetup-FULL $LOOP |sed 's/^.*(//' |sed 's/).*$//'`"
    if [ "$loFile" = "$imgFile" ] ;then
@@ -31,87 +40,193 @@ if [ 1 -eq 2 ] ;then	##############################################	JUMP OVER th
    i=`expr $i + 1`
  done
 
-fi			##############################################	END of JUMP SECTION.
+fi          ##############################################  END of JUMP SECTION.
 
 
-							### file's not mounted, mount it
+                            ### file's not mounted, mount it
 # if [ $i -eq 16 ] ;then
 
- imgFileBASE="`basename "$imgFile"`" #BK
+imgFileBASE="`basename "$imgFile"`" #BK
 
- if [ ! -d "$MntPt" ] ;then
- 
+if [ ! -d "$MntPt" ] ;then # 5
+
+check_already_mounted_func(){
+
   #BK check if already mounted elsewhere...
   for ONELOOP in `mount | grep '^/dev/loop' | cut -f 1 -d ' ' | tr '\n' ' '`
   do
+
    MNTDIMG="`losetup-FULL $ONELOOP | cut -f 2 -d '(' | cut -f 1 -d ')'`"
-    IMGBASE="`basename "$MNTDIMG"`"
+   IMGBASE="`basename "$MNTDIMG"`"
+
     #echo "IMGBASE=$IMGBASE imgFileBASE=$imgFileBASE" #TEST
     #not perfect, but paths may be symlinks...
-    if [ "$IMGBASE" = "$imgFileBASE" ];then #if [ "$MNTDIMG" = "$imgFile" ];then
-     xmessage "Sorry $imgFile is already mounted and in-use by Puppy"
+
+    if [ "$IMGBASE" = "$imgFileBASE" ];then #if [ "$MNTDIMG" = "$imgFile" ];then #6
+
+     if [ -n "$DISPLAY" ] ; then #66
+xmessage -buttons "Quit:190,ROX-Filer:191,console:192,Unmount:193,Unmount all $IMGBASE:194,Mount another time:199" "$imgFile
+is already mounted and in-use by Puppy .
+Do you want to unmount it or mount it to another mount point ?"
+RETVAL=$?
+if [ "$RETVAL" = "190" ] ; then #666
      exit
-    fi
-  done
-   
-  Ext=`echo "$imgFile" |sed 's/^.*\.//'`	# get file type from extention
-  if [ "$Ext" = '2fs' ] ;then
+
+ elif [ "$RETVAL" = "191" ] ; then #666
+     MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
+     rox $MntPt
+     exit
+
+elif [ "$RETVAL" = "192" ] ; then #666
+     MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
+     cd $MntPt
+     pwd
+     rxvt &
+     exit
+
+elif [ "$RETVAL" = "193" ] ; then #666
+       UNMOUNT='yes'
+       MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
+       return
+
+elif [ "$RETVAL" = "194" ] ; then #666
+       UNMOUNT='yes'
+       MntPt=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
+       echo 1 "$MntPt"
+       MntPt2=`echo "$MntPt" | sed "1 d"`
+       echo 2 "$MntPt2"
+       for i in $MntPt2 ; do
+       GREP=`echo "$i" | sed 's#\.#\\\.#g;s#\+#\\\+#g;s#-#\\\-#g'`
+       echo "$GREP"
+       LOOPD=$(busybox mount | grep "$GREP" | cut -f 1 -d ' ')
+       echo "$LOOPD"
+       USEapps=`fuser -c $LOOPD`
+       echo 3 "$USEapps"
+       USEapps=`echo "$USEapps" | sed 's/[[:alpha:]]//g'`
+       echo 4 "$USEapps"
+       for j in $USEapps ; do
+       echo $i
+       kill -1 $j
+       done
+       [ -n "$DISPLAY" ] && rox -D $i
+       umount $i
+       sleep 2
+       rmdir $i
+       done
+       MntPt=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
+       return
+
+else #666
+     MOUNT='again'
+     return
+fi ###666
+
+fi ##6
+fi #6
+done
+
+}
+check_already_mounted_func
+
+fi # 5
+
+if [ -z "$UNMOUNT" ] ; then #55
+
+  Ext=`echo "$imgFile" |sed 's/^.*\.//'`    # get file type from extention
+  if [ "$Ext" = '2fs' ] ;then #7
    Type='ext2'
   elif [ "$Ext" = '3fs' ] ;then
    Type='ext3'
   elif [ "$Ext" = '4fs' ] ;then #v423 planning for the future!
    Type='ext4'
-  elif [ "$Ext" = 'sfs' ] ;then
+  elif [ "$Ext" = 'sfs' -o "$Ext" = 'sqfs' -o "$Ext" = 'squashfs' ] ;then
    Type='squashfs'
   elif [ "$Ext" = 'iso' ] ;then
    Type='iso9660'
   # BK
   #elif [ "$imgFile" = 'initrd.gz' ] ;then
   # Type='ext2'
-  # gunzip $imgFile				# handle gzip image file
+  # gunzip $imgFile             # handle gzip image file
   # imgFile="echo "$imgFile" |sed 's/.gz$//'"
-  fi
-  
+  fi #7
+
   #v423 detect wrong squashfs version...
-  if [ "$Type" = "squashfs" ];then
-   if [ "`disktype "${imgFile}" | grep "$SFSSTR"`" = "" ];then
-    if [ $KERNELSUBVER -gt 28 ];then
-     xmessage -center -bg '#FFC0C0' "NOTICE: This is an older version 3.x squashfs file, not usable.
+  if [ "$Type" = "squashfs" ];then #8
+   if [ "`disktype "${imgFile}" | grep "$SFSSTR"`" = "" ];then #8.1
+    if [ $KERNELSUBVER -gt 28 ];then #8.1.1
+     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This is an older version 3.x squashfs file, not usable.
 All Linux kernels 2.6.29 or later require version 4.x squashfs files.
 Note, there is an SFS-version-converter in the Utility menu, run that first."
-    else
-     xmessage -center -bg '#FFC0C0' "NOTICE: This is a newer version 4.x squashfs file, not usable.
+    else #8.1.1
+     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This is a newer version 4.x squashfs file, not usable.
 All Linux kernels 2.6.28 or earlier require version 3.x squashfs files.
 Note, there is an SFS-version-converter in the Utility menu, run that first."
-    fi
+    fi #8.1.1
     exit
-   fi
-  fi
-  
+   fi #8.1
+  fi #8
+
 #  echo -e "\nimgFile = $imgFile\t\tExt  = $Ext"
 #  echo -e "MntPt   = $MntPt\t\tType = $Type\n"
   echo -e "\n ### Mount: $imgFile\n"
-  mkdir -p $MntPt
-  mount -t $Type -o loop $imgFile $MntPt
+  mkdir -p "$MntPt"
+  mount -t $Type -o loop "$imgFile" "$MntPt"
   Err=$?
-  if [ $Err -eq 0 ] ;then
-   rox -d $MntPt # mount good, run rox filer
-   yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
-  fi	
+  sleep 2s
+  if [ $Err -eq 0 ] && [ -n "`mount | grep "$MntPt"`" ];then #9
+   if [ -n "$DISPLAY" ] ; then #99
+    rox -d "$MntPt" # mount good, run rox filer
+   ##[ -n "$DISPLAY" ] && yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
+    yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
+   fi #99
+  else
+  rmdir "$MntPt"
+  fi #9
 
- else							### file's mounted, unmount it
-  rox -D $MntPt #BK
-  umount $MntPt
+ else #55                       ### file's mounted, unmount it
+
+   [ -n "$DISPLAY" ] && rox -D "$MntPt" #BK
+
+       GREP=`echo "$MntPt" | sed 's#\.#\\\.#g;s#\+#\\\+#g;s#-#\\\-#g'`
+       echo 1 "$GREP"
+       LOOPD=$(busybox mount | grep "$GREP" | cut -f 1 -d ' ')
+       echo 2 "$LOOPD"
+       USEapps=`fuser -c $LOOPD`
+       echo 3 "$USEapps"
+       USEapps=`echo "$USEapps" | sed 's/[[:alpha:]]//g;s/[[:punct:]]//g'`
+       echo 4 "$USEapps"
+       for j in $USEapps ; do
+       echo $i
+       kill -1 $j
+       done
+
+   sleep 2s
+  umount "$MntPt"
   Err=$?
-  rmdir $MntPt
-  if [ "basename $imgFile" = 'initrd' ] ;then gzip -9 $imgFile ;fi
-  yaf-splash -timeout 3 -font "8x16" -outline 0 -margin 4 -bg orange -text "Unmounting $imgFileBASE" #BK
+
+  #yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg orange -text "$Err"
+  sleep 2s
+  #rmdir $MntPt
+  #yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg orange -text "$MntPt"
+
+
+  [ -n "$DISPLAY" ] && yaf-splash -timeout 3 -font "8x16" -outline 0 -margin 4 -bg orange -text "Unmounting $imgFileBASE" #BK
+
   #Xdialog --title " Notice..." --no-button \
   #        --infobox "
-  #UnMounting: $imgFile  
+  #UnMounting: $imgFile
   #" 0 0 2000
+
   echo -e "\n ### UnMount: $imgFile\n"
- fi
- if [ $Err -gt 0 ] ;then			# ERROR: mount/unmount
-  xmessage -title " ERROR..." "  Failed mounting or unmounting.  "
- fi
+
+  [ -d "$MntPt" -a "`busybox mount | grep "$MntPt"`" = "" ] && rmdir "$MntPt"
+
+ fi #55
+
+ if [ "$Err" -gt 0 ] ;then          # ERROR: mount/unmount # 9999
+  [ -n "$DISPLAY" ] && xmessage -bg red -title "ERROR..." "Returned $Err ... mounting or unmounting $MntPt"
+ fi # 9999
+
+echo "$0:Exiting with '$Err'"
+exit $Err
+
diff --git a/woof-code/rootfs-skeleton/usr/sbin/pupdial b/woof-code/rootfs-skeleton/usr/sbin/pupdial
--- a/woof-code/rootfs-skeleton/usr/sbin/pupdial
+++ b/woof-code/rootfs-skeleton/usr/sbin/pupdial
@@ -9,15 +9,15 @@
 #BK v3.99: added Stupid Mode and Auto reconnect checkboxes for each isp.
 #BK v4.00: crash bugfix.
 #HairyWill v4.00: handle init string with quotes, prevent gtkdialog crash.
-#v405 updated. 
+#v405 updated.
 #v408 old pap-secrets, chap-secrets problem has returned, workaround applied.
-#v408 rerwin: Make modem startup after 'erase' same as for first time with no conf file. 
+#v408 rerwin: Make modem startup after 'erase' same as for first time with no conf file.
 #v409 rerwin: bugfix, need a delay for fast machines.
 #v412 rerwin: increase sleep from 0.3 to 1.
 #v465 rerwin: v413 add init strings for wireless modems
 #v477 rerwin: v413 add 'Reading...' splash message during sleep.
 #v424 rerwin: send PIN only on first wireless connection; move APNs to accounts; associate APN with dial accounts; retain dial type (DT/DP)
-#v431 rerwin: retain account checkbox changes; ensure optional lines associated with an account; add APN-specific commands; handle Idle Seconds lines 
+#v431 rerwin: retain account checkbox changes; ensure optional lines associated with an account; add APN-specific commands; handle Idle Seconds lines
 
 KERNVER="`uname -r`"
 
@@ -32,9 +32,9 @@ if [ ! -s /etc/wvdial.conf ] || [ "`grep '/dev/MYDEVM' /etc/wvdial.conf`" != "" 
   echo "[Dialer Defaults]
 Modem = ${MYDEVM}
 Baud = 57600
-Init1 = 
+Init1 =
 Init2 = ATZ
-Init3 = 
+Init3 =
 Carrier Check = no
 Dial Command = ATDT
 
@@ -45,6 +45,8 @@ Password = MYPASSWORD
 
 [Dialer isp1apn]
 Init5 = AT+CGDCONT=1,\"IP\",\"\"
+[Dialer isp1pin]
+Init1 = AT+CPIN=
 
 [Dialer isp2]
 Phone = MY2ISPPHONENUM
@@ -53,8 +55,7 @@ Password = MY2PASSWORD
 
 [Dialer isp2apn]
 Init5 = AT+CGDCONT=1,\"IP\",\"\"
-
-[Dialer pin]
+[Dialer isp2pin]
 Init1 = AT+CPIN=" > /etc/wvdial.conf
 #v408 Treat erased modem device name same as for absent wvdial.conf.
  else #wvdial.conf indicates modem field has been erased
@@ -167,15 +168,25 @@ NEED TO CLICK THE 'probe' BUTTON. DO THIS NOW!
 fi
 
  BAUDM="`cat /etc/wvdial.conf | grep '^Baud = ' | cut -f 3 -d ' '`"
- 
+
  #v4.00 HairyWill fixes for embedded $ " characters...
  INIT1M="`cat /etc/wvdial.conf | grep '^Init1 =' | head -n 1 | cut -f 3-12 -d ' ' | grep -v 'AT+CPIN=' | sed 's/"/\\\\"/g;s/\\$/\\\\$/g;'`" #v413
  INIT2M="`cat /etc/wvdial.conf | grep '^Init2 = ' | cut -f 3-12 -d ' '| sed 's/"/\\\\"/g;s/\\$/\\\\$/g;'`"
  INIT3M="`cat /etc/wvdial.conf | grep '^Init3 = ' | cut -f 3-12 -d ' '| sed 's/"/\\\\"/g;s/\\$/\\\\$/g;'`" #v413
+ if [ "$INIT1M" = "ATZ" ];then
+ INIT1M=''
+ INIT2M="$INIT3M"
+ INIT3M=""
+ fi
+ if [ "$INIT2M" = "ATZ" ];then
+ INIT2M="$INIT3M"
+ INIT3M=""
+ fi
  #v413 If first Init1 not null, move contents to Init2, and Init2 to Init3, to reserve Init1 for wireless PIN.
  [ "$INIT1M" != "" ] && INIT3M="$INIT2M" && INIT2M="$INIT1M" && INIT1M="" #v413
  #v413 Get values for Init1, 4, 6-9.
- WPINM="`cat /etc/wvdial.conf | grep '^Init1 = ' | tail -n 1 | cut -f 3 -d '='`"
+ WPINM1="`cat /etc/wvdial.conf | grep -A1 '\[Dialer isp1pin\]' | grep '^Init1 = ' | tail -n 1 | cut -f 3 -d '='`"
+ WPINM2="`cat /etc/wvdial.conf | grep -A1 '\[Dialer isp2pin\]' | grep '^Init1 = ' | tail -n 1 | cut -f 3 -d '='`"
  INIT4M="`cat /etc/wvdial.conf | grep '^#*Init4 =' | sed 's/"/\\"/g;;s/\$/\\$/g;s/$$//g;'`"
  [ "$INIT4M" = "" ] && INIT4M="#Init4 = AT+COPS=0,0,\"MYOPS\","
  INIT69M="`cat /etc/wvdial.conf | grep '^#*Init[6-9] =' | sed -e 's/"/\\"/g' -e 's/\$/\\$/g' -e 's/$$//'`"
@@ -184,14 +195,14 @@ fi
 #Init8 = AT+CGDCONT?
 #Init9 = AT+COPS?"
  #v413 end
- 
+
  DIALM="`cat /etc/wvdial.conf | grep '^Dial Command = ' | cut -f 4 -d ' '`"
  [ "`echo "$DIALM" | grep -E 'X3|X1'`" != "" ] && STATEDTM="no"
  [ "`echo "$DIALM" | grep -E 'X2|X1'`" != "" ] && STATEBCM="no"
  CCM="`cat /etc/wvdial.conf | grep '^Carrier Check = ' | cut -f 4 -d ' '`"
  [ "$CCM" = "no" ] && STATECCM="no"
  [ "`echo "$DIALM" | grep 'DP'`" = "" ] && DIALTYPE="DT" || DIALTYPE="DP" #v424
- 
+
  #v3.99 there may be up to two of each of the above...
  ISPCNT=0 #v431
  echo -n "" > /tmp/pupdial_read
@@ -209,8 +220,8 @@ fi
   esac
   [ $ISPCNT -eq 0 ] && continue
 #v431 end
-  ONEPARAM="`echo -n "$ONELINE" | cut -f 1 -d '=' | sed -e 's/ $//'`"
-  ONEVALUE="`echo -n "$ONELINE" | cut -f 2 -d '=' | sed -e 's/^ //'`"
+  ONEPARAM="`echo -n "$ONELINE" | cut -f 1 -d '=' | sed -e 's/[[:blank:]]*$//'`"
+  ONEVALUE="`echo -n "$ONELINE" | cut -f 2 -d '=' | sed -e 's/^[[:blank:]]*//'`"
   if [ "$ONEVALUE" != "" ];then
    case $ONEPARAM in
     "Dial Prefix") echo "DIAL_PREFIX${ISPCNT}='${ONEVALUE}'" >> /tmp/pupdial_read ;;
@@ -224,7 +235,7 @@ fi
   fi
  done
  eval "`cat /tmp/pupdial_read`"
- 
+
  #v3.99
  ynSTUPID_MODE1=no
  [ "$STUPID_MODE1" = "1" -o "$STUPID_MODE1" = "yes" ] && ynSTUPID_MODE1=yes
@@ -265,7 +276,7 @@ fi
   </vbox>
  </frame>
  <vbox>
-  <hbox>
+  <hbox width-request=\"400\">
    <text><label>Initialisation string 2:</label></text>
    <entry>
     <input>echo \"${INIT2M}\"</input>
@@ -284,11 +295,6 @@ fi
    <entry>
     <default>\"${BAUDM}\"</default>
     <variable>ENTRYBAUDM</variable>
-   </entry>
-   <text><label>SIM PIN:</label></text>
-   <entry invisible_char=\"x\" visibility=\"false\">
-    <input>echo \"${WPINM}\"</input>
-    <variable>ENTRYWPINM</variable>
    </entry>
   </hbox>
  </vbox>
@@ -349,6 +355,13 @@ export MAINDIALOG="
        <variable>ENTRYACC1APN</variable>
       </entry>
      </hbox>
+     <hbox>
+      <text><label>SIM PIN:</label></text>
+      <entry invisible_char=\"x\" visibility=\"false\">
+       <input>echo \"${WPINM1}\"</input>
+       <variable>ENTRYWPINM1</variable>
+      </entry>
+     </hbox>
 
      <hbox>
      <checkbox>
@@ -362,7 +375,7 @@ export MAINDIALOG="
        <default>${ynAUTO_RECONNECT1}</default>
       </checkbox>
       </hbox>
-     
+
       <button>
        <label>Connect to Internet</label>
        <visible>${STATECONa}</visible>
@@ -400,6 +413,13 @@ export MAINDIALOG="
        <variable>ENTRYACC2APN</variable>
       </entry>
      </hbox>
+      <hbox>
+      <text><label>SIM PIN:</label></text>
+      <entry invisible_char=\"x\" visibility=\"false\">
+       <input>echo \"${WPINM2}\"</input>
+       <variable>ENTRYWPINM2</variable>
+      </entry>
+     </hbox>
 
      <hbox>
       <checkbox>
@@ -413,7 +433,7 @@ export MAINDIALOG="
        <default>${ynAUTO_RECONNECT2}</default>
       </checkbox>
      </hbox>
-    
+
       <button>
        <label>Connect to Internet</label>
        <visible>${STATECONa}</visible>
@@ -484,8 +504,9 @@ RETSTRING="`gtkdialog3 --program=MAINDIALOG`"
 #v4.00 to handle embedded quote, extract ENTRYINIT2M and ENTRYINIT3M separately...
 ENTRYINIT2M="`echo "$RETSTRING" | grep '^ENTRYINIT2M=' | cut -f 2-9 -d '"' | sed -e 's/"$//'`" #'geany
 ENTRYINIT3M="`echo "$RETSTRING" | grep '^ENTRYINIT3M=' | cut -f 2-9 -d '"' | sed -e 's/"$//'`" #'geany
-ENTRYWPINM="`echo "$RETSTRING" | grep '^ENTRYWPINM=' | cut -f 2-9 -d '"' | sed -e 's/"$//' | tr -d ' '`" #no spaces
-RETSTRING="`echo "$RETSTRING" | grep -v '^ENTRYINIT3M=' | grep -v '^ENTRYINIT2M=' | grep -v '^ENTRYWPINM='`"
+ENTRYWPINM1="`echo "$RETSTRING" | grep '^ENTRYWPINM1=' | cut -f 2-9 -d '"' | sed -e 's/"$//' | tr -d ' '`" #no spaces
+ENTRYWPINM2="`echo "$RETSTRING" | grep '^ENTRYWPINM2=' | cut -f 2-9 -d '"' | sed -e 's/"$//' | tr -d ' '`" #no spaces
+RETSTRING="`echo "$RETSTRING" | grep -v -E '^ENTRYINIT3M=|^ENTRYINIT2M=|^ENTRYWPINM1=|^ENTRYWPINM2='`"
 
 #v405 getting some weird stuff on stdout from gtkdialog3, fix...
 #all lines must have format variable="value"... v406 add '_'...
@@ -559,7 +580,7 @@ DIALSTR="${DIALSTR}${DIALTYPE}"
 echo '[Dialer Defaults]' > /etc/wvdial.conf
 echo -n "Modem = /dev/${DEVM}
 Baud = ${ENTRYBAUDM}
-Init1 = 
+Init1 =
 Init2 = ${ENTRYINIT2M}
 Init3 = ${ENTRYINIT3M}
 Carrier Check = ${CHECKCC}
@@ -572,6 +593,8 @@ Password = ${ENTRYACC1PASS}
 ${USEREXTRA1}
 [Dialer isp1apn]
 Init5 = AT+CGDCONT=${ACC1PRFL},\"IP\",\"${ENTRYACC1APN}\"
+[Dialer isp1pin]
+Init1 = AT+CPIN=${ENTRYWPINM1}
 
 [Dialer isp2]
 Phone = ${ENTRYACC2ISP}
@@ -580,9 +603,8 @@ Password = ${ENTRYACC2PASS}
 ${USEREXTRA2}
 [Dialer isp2apn]
 Init5 = AT+CGDCONT=${ACC2PRFL},\"IP\",\"${ENTRYACC2APN}\"
-
-[Dialer pin]
-Init1 = AT+CPIN=${ENTRYWPINM}
+[Dialer isp2pin]
+Init1 = AT+CPIN=${ENTRYWPINM2}
 
 [Dialer wireless]
 #To force only 2G or 3G, uncomment the Init4 line and append 0 (2G) or 2 (3G), and substitute your operator's name for MYOPS.
@@ -615,11 +637,13 @@ if [ "$EXIT" = "CONNECT1" -o "$EXIT" = "CONNECT2" ];then
    WVWRLS="wireless" #Include optional user-edited init strings
    if [ "$WVISP" = "isp1" ];then
     [ "$ENTRYACC1APN" != "" ] && WVAPN="${WVISP}apn" && APNSTRING="$ENTRYACC1APN" #v431
+    [ "$ENTRYWPINM1" ] && WVPIN="${WVISP}pin"
    else
     [ "$ENTRYACC2APN" != "" ] && WVAPN="${WVISP}apn" && APNSTRING="$ENTRYACC2APN" #v431
+     [ "$ENTRYWPINM2" ] && WVPIN="${WVISP}pin"
    fi
-   if [ "$ENTRYWPINM" != "" ] && [ ! -e /tmp/.pupdial_pin_sent ];then
-    WVPIN="pin"
+   if [ "$ENTRYWPINM1" -o "$ENTRYWPINM2" ] && [ ! -e /tmp/.pupdial_pin_sent ];then
+    #WVPIN="pin"
     touch /tmp/.pupdial_pin_sent
    fi
   fi
@@ -627,7 +651,7 @@ if [ "$EXIT" = "CONNECT1" -o "$EXIT" = "CONNECT2" ];then
  rm -f /tmp/pupdial.log
 
 #v3.98 put this in, now remove...
- #v3.98 /etc/ppp/options can cause conflict for wvdial. 
+ #v3.98 /etc/ppp/options can cause conflict for wvdial.
  #(i think 'options' is used by roaring penguin) hide it...
 # mv -f /etc/ppp/options /etc/ppp/optionsHIDE
 
@@ -637,25 +661,84 @@ if [ "$EXIT" = "CONNECT1" -o "$EXIT" = "CONNECT2" ];then
  cp -f /etc/ppp/wvdial /etc/ppp/peers/
  [ "${WVAPN}" != "" ] && [ -f /etc/wvdial_options/APN-${APNSTRING} ] && echo "`cat /etc/wvdial_options/APN-${APNSTRING}`" >> /etc/ppp/peers/wvdial #431
  [ -f /etc/ppp/wvdial-pipe ] && cp -f /etc/ppp/wvdial-pipe /etc/ppp/peers/ #v3.98
- wvdial ${WVISP} ${WVPIN} ${WVAPN} ${WVWRLS} &> /tmp/pupdial.log & #v413
- [ ! -f /tmp/pupdial.log ] && sleep 1 
- [ ! -f /tmp/pupdial.log ] && sleep 1 
+ /etc/ppp/local/pgprs-count-transfer.sh &
+ #wvdial ${WVISP} ${WVAPN} ${WVPIN} ${WVWRLS} &> /tmp/pupdial.log & #v413
+ echo "${WVISP} ${WVAPN} ${WVPIN} ${WVWRLS}"
+ #wvdial ${WVISP} ${WVAPN} ${WVPIN} ${WVWRLS} 1>/tmp/pupdial.log 2>&1 &
+ wvdial ${WVISP} ${WVPIN} ${WVAPN} &>/tmp/pupdial.log &  #needs to be &> :: > directs to terminal instead file
+ [ ! -f /tmp/pupdial.log ] && sleep 1
+ [ ! -f /tmp/pupdial.log ] && sleep 1
+
+ kill_func(){
+  [ "`pidof pppd`" ] && kill -1 `pidof pppd`
+  sleep 2.5
+  [ "`pidof wvdial`" ] && kill -1 `pidof wvdial`
+ }
+ logbox_func(){
  Xdialog --center --wmclass "pupdial" --backtitle "NOTICE: If the log shows a failure to connect, please click left button" --title "PupDial: WvDial connection log" --ok-label "Disconnect, or stop trying" --cancel-label "Close window but stay online" --fixed-font --tailbox /tmp/pupdial.log 20 80
  if [ $? -eq 0 ];then
-  rm -f /etc/ppp/peers/wvdial
-  [ -f /etc/ppp/peers/wvdial-pipe ] && rm -f /etc/ppp/peers/wvdial-pipe
+  kill_func
+  #rm -f /etc/ppp/peers/wvdial
+  #[ -f /etc/ppp/peers/wvdial-pipe ] && rm -f /etc/ppp/peers/wvdial-pipe
+ fi
+  }
+  #logbox_func &
+  #logboxPID=$!
+  logbox_func
+  sleep_func(){
+  sleep 2.5;c=0
+  while [ "`pidof wvdial`" ] ; do
+  #while [ -L /sys/class/net/ppp0 ] ; do
+  #sleep 2.5
+  #done
+  #while [ "`pidof pppd`" ] ; do
+  #sleep 2.5
+  #done
+  #[ ! "`pidof pppd`" ] && echo "pppd not running" >>/tmp/pupdial.log
+  #echo "`which pppd` died" >>/tmp/pupdial.log
+  #while [ "`pidof wvdial`" ] ; do
+  sleep 2.5
+  c=$((c+1))
+  if [ "$c" == '4' ] ; then
+  if [ ! -L /sys/class/net/ppp0 ] ; then
+  return 1
+  else
+  return 0
+  fi
+  fi
+  done
+ }
+ #sleep_func
+  tail -n3 /tmp/pupdial.log
 
+  NOCARR=`tail -n40 /tmp/pupdial.log | grep -i 'No carrier' | wc -l`
+  [ "$NOCARR" ] && PINER=`tail -n3 /tmp/pupdial.log | grep 'AT+CPIN='`
+  [ "$PINER" ] && PINER=`tail -n2 /tmp/pupdial.log | grep 'ERROR'`
+  [ "$PINER" ] && PINER=`tail -n1 /tmp/pupdial.log | grep 'Bad init string'`
+  if [ "$PINER" -o "$NOCARR" -gt 9 ];then
+  #kill $logboxPID
+  XdialogPID=`ps | grep 'Xdialog' | grep 'pupdial' | awk '{print $1}'`
+  [ "$XdialogPID" ] && kill $XdialogPID
+  /etc/ppp/local/pgprs-count-transfer.sh &
+  wvdial ${WVAPN} ${WVISP} &>/tmp/pupdial.log &
+  #logbox_func &
+  logbox_func
+  fi
+  #sleep_func
+
+  [ ! "`pidof wvdial`" ] && echo "`which wvdial` died" >>/tmp/pupdial.log
+  kill_func
 #v3.98 put this in, now remove...
 #  mv -f /etc/ppp/optionsHIDE /etc/ppp/options
 
-  killall wvdial
-  killall pppd
+  #killall wvdial #2>>/tmp/pupdial.log
+  #killall pppd 2>>/tmp/pupdial.log
   #rm -f /tmp/pupdial.log
   echo '' >> /tmp/pupdial.log
   echo '------------------------------------------------------' >> /tmp/pupdial.log
   echo '' >> /tmp/pupdial.log
   exec pupdial #v3.91 go back to main window.
- fi
+ #fi
 fi
-
+exit 0 || exit 1
 ###END###
