/sbin/pup_event_frontend_d: Fixed a bug that when a partition icon app directory for an extended partition was created, that caused that directory not being deleted when the drive was disconnected. That caused troubles when a new drive with lesser partitons was inserted under the old drive name ie "sdd" , causing the BLOCKDIFF variable being set to both ADD and REMOVE for that drive, thus the icon got created and immediately deleted again every two seconds.

diff --git a/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d b/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
--- a/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
+++ b/woof-code/rootfs-skeleton/sbin/pup_event_frontend_d
@@ -93,8 +93,30 @@ _trap
 ########################################################################
 
 PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/X11R7/bin"
-OLDLANG=$LANG #100613
-export LANG=C #w004
+
+DEBUG=1
+OUT=/dev/null;ERR=$OUT
+[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
+[ "$DEBUG" = "2" ] && set -x
+
+Version='1.8.3-simple Macpup_F3-Puppy_Linux-430/2 KRG'
+usage(){
+MSG="
+$0 [help|version|start|stop|restart|reload]
+
+Script daemon to run in background to manage the
+Puppy specific drive icons on the desktop.
+The eventmanager GUI in the system menu alters the
+configuration file $CONFFILE, which is read
+by this script. Other configuration files used :
+/etc/rc.d/PUPSTATE, /etc/rc.d/functions4puppy4
+"
+MSG=`gettext "$MSG"`
+echo "$MSG"
+[ "$DISPLAY" ] && exec xmessage -title "FRONTEND_D HELP" -bg lightblue3 "$MSG
+" &
+exit $1
+}
 
 get_lineno(){  #workaround to grep line number in ash script since ash has no LINENO
     if [ "$1" ] ; then
@@ -103,11 +125,6 @@ get_lineno(){  #workaround to grep line number in ash script since ash has no LI
     echo 'UNKNOWN'
     fi
 }
-
-#_get_home_var(){
-#test "$HOME" = '/' && export HOME=/root
-#}
-#_get_home_var
 
 ########### check program ##############
 ###++2012-01-21
@@ -156,14 +173,6 @@ MY_HOME=${MY_HOME:-/var/local/PuppyLinux/pup_event}
 MY_CFG=${MY_CFG:-"$MY_HOME"/etc}
 MY_LOG=${MY_LOG:-"$MY_HOME"/log}
 MY_TMP=${MY_TMP:-"$MY_HOME"/tmp}
-mkdir $VERB -p "$MY_CFG" "$MY_LOG" "$MY_TMP"
-chown $VERB pup_event:pup_event "$MY_HOME"
-chown $VERB pup_event:pup_event "$MY_CFG" "$MY_LOG" "$MY_TMP"
-chmod $VERB 1774 "$MY_CFG" "$MY_LOG"
-chmod $VERB 1770 "$MY_TMP"
-[ "$DEBUG" ] && ls -ld "$MY_HOME"
-[ "$DEBUG" ] && ls -l  "$MY_HOME"
-cd "$MY_HOME" || { echo "Could not change into directory $MY_HOME ."; exit 2; }
 
 ### *** ROX-Filer Pinboard *** ###
 STATE_DIR=${STATE_DIR:-"$HOME/Choices/Puppy"}
@@ -291,27 +300,6 @@ trap "echo '$0:PID=$$:WINCH';echo WINCH >$MY_TMP/pup_event_manager.flg; echo WIN
 trap "echo '$0:PID=$$:STOP';echo STOP >$MY_TMP/pup_event_manager.flg;"  RTMIN+1 SIGRTMIN+1 36
 trap "echo '$0:PID=$$:CONT';echo CONT >$MY_TMP/pup_event_manager.flg;"  RTMAX-1 SIGRTMAX-1 63
 
-OUT=/dev/null;ERR=$OUT
-[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
-[ "$DEBUG" = "2" ] && set -x
-
-Version='1.8.1-simple Macpup_F3-Puppy_Linux-430/2 KRG'
-usage(){
-MSG="
-$0 [help|version|start|stop|restart|reload]
-
-Script daemon to run in background to manage the
-Puppy specific drive icons on the desktop.
-The eventmanager GUI in the system menu alters the
-configuration file $CONFFILE, which is read
-by this script. Other configuration files used :
-/etc/rc.d/PUPSTATE /etc/rc.d/functions4puppy4
-"
-echo "$MSG"
-[ "$DISPLAY" ] && exec xmessage -title "FRONTEND_D HELP" -bg blue3 "$MSG" &
-exit $1
-}
-
 ########### parameters start stop restart ##############
 
 #DEBUG=1
@@ -383,11 +371,24 @@ return 22 || exit 22;;
 esac
 ########### parameters start stop restart ##############
 
+OLDLANG=$LANG #100613
+OLDLANG=${OLDLANG:-C}
+export LANG=C #w004
+
+mkdir $VERB -p "$MY_CFG" "$MY_LOG" "$MY_TMP"
+chown $VERB pup_event:pup_event "$MY_HOME"
+chown $VERB pup_event:pup_event "$MY_CFG" "$MY_LOG" "$MY_TMP"
+chmod $VERB 1774 "$MY_CFG" "$MY_LOG"
+chmod $VERB 1770 "$MY_TMP"
+[ "$DEBUG" ] && ls -ld "$MY_HOME"
+[ "$DEBUG" ] && ls -l  "$MY_HOME"
+cd "$MY_HOME" || { echo "Could not change into directory $MY_HOME ."; exit 2; }
+
+
 ################# check if already running ############################
 ###+++2012-01-19
-DEBUG=1
 prog=$(basename $0)
-DAEMONS=`ps-FULL -f --no-headers -C "$prog"| grep -v '<defunct>'`
+DAEMONS=`ps-FULL -f --no-headers -C "$prog" | grep -vE 'grep|<defunct>'`
 PROGPID=$$
 _debug "
 .............
@@ -421,7 +422,7 @@ _debug "Is child."
 fi
 PIDS=`echo "$PIDS" |sed '1 d'`
 done
-DEBUG=
+
 ################# check if already running ############################
 
 ################# ORIG #########################################################
@@ -440,11 +441,13 @@ else
 DELAYFACTOR=0
 #CPUMHZ=`grep -m 1 -i '^cpu MHz' /proc/cpuinfo | tr -d ' ' | cut -f 2 -d ':' | cut -f 1 -d '.'`
  CPUMHZ=`grep -m 1 -i '^cpu MHz' /proc/cpuinfo | tr -d '[:blank:]' | cut -f 2 -d ':' | cut -f 1 -d '.'`
+ test "${CPUMHZ//[0-9/}" && unset CPUMHZ
+ CPUMHZ=${CPUMHZ:-1000}
  [ "$CPUMHZ" -a "$CPUMHZ" -gt 100 ] && DELAYFACTOR=$(( 1100 / CPUMHZ ))
  [ "$DELAYFACTOR" -gt 0 ] && sleep $DELAYFACTOR
 fi
 
-mount -t ramfs pup_event "$MY_TMP" || exit 2
+cut -f2 -d' ' /proc/mounts | grep $Q "^${MY_TMP}$" || mount -t ramfs pup_event "$MY_TMP" || _exit 2 "Unable to mount $MY_TMP ."
 
 ################# ORIG ######################################
 #v424 experiment, automatic unmounting...
@@ -1193,6 +1196,7 @@ _store_program_logging_level
  [ -z "`grep "$ppPATTERN" "$PUPPY_PIN"`" ] && { _reset_program_logging_level; return; }
  allNAMES=`grep -o "$ppPATTERN" "$PUPPY_PIN" | cut -f 2 -d '"'`
  [ "$DISPLAY" ] || { _reset_program_logging_level; return; }
+
  for oneDRVNAME in $allNAMES
  do
 
@@ -1213,9 +1217,14 @@ _store_program_logging_level
  </env:Body>
 </env:Envelope>"  | rox -R  2>>$ERR
  [ $? = 0 ] && _info "${oneDRVNAME}: Removed from PuppyPin ." || _warn "Could not remove ${oneDRVNAME} from PuppyPin ."
+
  rm $VERB -rf $PUP_EVENT_DIR/drive_${oneDRVNAME}
  [ $? = 0 ] && _info "${oneDRVNAME}: Removed AppRun handler ." || _warn "Could not remove ${oneDRVNAME} AppRun handler ."
- done
+
+ done #for oneDRVNAME in $allNAMES
+
+rm $VERB -rf $PUP_EVENT_DIR/drive_${DRV_NAME}* ###+++2018-01-18
+
 unset oneDRVNAME allNAMES ppPATTERN DRV_NAME
 _reset_program_logging_level
 }
@@ -1812,7 +1821,7 @@ return 0
 
 #_store_program_logging_level
 ###################################################################
-#now go into a two-second two-second loop...
+#now go into a two-second / four-second loop...
 cd "$MY_TMP" || return 1
 while :
 do
@@ -1832,13 +1841,13 @@ do
  fi
 
  BLOCKDIFF=`diff "$MY_TMP"/pup_event_frontend_block1 "$MY_TMP"/pup_event_frontend_block2`
- _debugx "BLOCKDIFF=$BLOCKDIFF"
+ _debugx "01:BLOCKDIFF=$BLOCKDIFF"
 
  #091223 some interfaces, no change in /sys/block when insert/remove a card...
  #note, /proc/partitions can be very slow to update, particularly when remove a card.
  #note, /sys/block/sd*/sd* shows card insertion but may not update on removal -- /usr/local/bin/drive_all will remove an invalid drive icon if clicked on.
  if [ ! "$BLOCKDIFF" ];then
-  #BLOCKSPROBE=""
+   unset HAVE_APPDIR BLOCKSPROBE
 
   for oneTESTDRV in `grep -E '^sd|^mmc' "$MY_TMP"/pup_event_frontend_block2` ##+-+2013-07-07
   do
@@ -1851,31 +1860,44 @@ do
    (true </dev/$oneTESTDRV) >>$OUT 2>>$ERR
 
    _debug "Checking $oneTESTDRV for primary partitions:"
-   for p in 1 2 3 4; do #check all possible primary partitions, since at least one primary must exist
+  #for p in 1 2 3 4; do #check all possible primary partitions, since at least one primary must exist
+   for p in 4 3 2 1; do #check all possible primary partitions, since at least one primary must exist
    if [ -e /sys/block/${oneTESTDRV}/${oneTESTDRV}$p ]; then #drive exists, but no partition (no card plugged in).
-    [ -d "$PUP_EVENT_DIR"/drive_${oneTESTDRV}$p ] && HAVE_PARTITION=1 || BLOCKSPROBE="${BLOCKSPROBE}+${oneTESTDRV}:"
-    _debug "BLOCKSPROBE='$BLOCKSPROBE'"
+    if [ -d "$PUP_EVENT_DIR"/drive_${oneTESTDRV}$p ]; then
+        _debug "$p:Have already APP_DIR as drive_${oneTESTDRV}$p"
+    else
+        _debug "$p:Adding +${oneTESTDRV}"
+        BLOCKSPROBE="${BLOCKSPROBE}+${oneTESTDRV}:"
+    fi
+    _debug "02:BLOCKSPROBE='$BLOCKSPROBE'"
     #dd if=/dev/${oneTESTDRV} of=/dev/null bs=512 count=1 >>$OUT 2>>$ERR #try force kernel to update.
+    break 1
    elif [ -d "$PUP_EVENT_DIR"/drive_${oneTESTDRV}$p ]; then
-    BLOCKSPROBE="${BLOCKSPROBE}-${oneTESTDRV}:"
+       _debug "$p:Have $PUP_EVENT_DIR/drive_${oneTESTDRV}$p"
+       _debug "$p:Subtracting -${oneTESTDRV}"
+       BLOCKSPROBE="${BLOCKSPROBE}-${oneTESTDRV}:"
    fi
-   if [ "$HAVE_PARTITION" ]; then
-   _debug "Found primary partition"
-   BLOCKSPROBE=`echo "$BLOCKSPROBE" | sed "s!+${oneTESTDRV}:!!g"`
-   fi
-   unset HAVE_PARTITION
-   done
-   #if [ "$HAVE_PARTITION" ]; then
-   #_debug "Found primary partition"
-   #unset BLOCKSPROBE HAVE_PARTITION
+   #if [ "$HAVE_APPDIR" ]; then
+   #_debug "Found first primary partition at $p"
+   ##BLOCKSPROBE=`echo "$BLOCKSPROBE" | sed "s!+${oneTESTDRV}:!!g"`
+   # BLOCKSPROBE=`echo "$BLOCKSPROBE" | sed "s!-${oneTESTDRV}:!!g"`
+   #break
    #fi
+   #unset HAVE_PARTITION
 
-  done
-  _debug "BLOCKSPROBE='$BLOCKSPROBE'"
+   done #for p
+
+   ##if [ "$HAVE_APPDIR" ]; then
+   ##_debug "Found primary partition"
+   ##unset BLOCKSPROBE HAVE_PARTITION
+   ##fi
+
+  done #for oneTESTDRV
+  _debug "10:BLOCKSPROBE='$BLOCKSPROBE'"
   [ "$BLOCKSPROBE" ] && BLOCKDIFF=`echo "$BLOCKSPROBE" | tr ':' '\n' | sort -u` #sort sorts + above -
  fi
 
- _debug "BLOCKDIFF='$BLOCKDIFF'"
+ _debug "11:BLOCKDIFF='$BLOCKDIFF'"
  #########hotplug block event##########
  if [ "$BLOCKDIFF" ];then
  _notice "Got hotplug event.."
@@ -1883,6 +1905,9 @@ do
 
    BLOCKSADD=`echo "$BLOCKDIFF" | grep -o '^\+[[:alnum:]]\+' | sed 's%^\+%%'`
    BLOCKSREM=`echo "$BLOCKDIFF" | grep -o '^\-[[:alnum:]]\+' | sed 's%^\-%%'`
+   #test "$BLOCKSADD" = "$BLOCKSREM" && return
+   BLOCKSADD=`echo "$BLOCKSADD" | /bin/grep -v "${BLOCKSREM:-'XXXX'}"`
+   BLOCKSREM=`echo "$BLOCKSREM" | /bin/grep -v "${BLOCKSADD:-'XXXX'}"`
 
    case $BLOCKSADD in
    ''|fd*) :;;
