/sbin/ poweroff,reboot: fixes of latest.

diff --git a/woof-code/rootfs-skeleton/sbin/reboot b/woof-code/rootfs-skeleton/sbin/reboot
--- a/woof-code/rootfs-skeleton/sbin/reboot
+++ b/woof-code/rootfs-skeleton/sbin/reboot
@@ -1,5 +1,30 @@
-#!/bin/sh
+#!/bin/ash
+
+[ "`whoami`" = "root" ] || exec sudo -A "${0}" "${@}" #110505
+
+REBOOTEXE='/bin/busybox reboot'
+#[ -f /sbin/minit ] && REBOOTEXE='/sbin/shutdown -r'   #-r means reboot. note, shutdown is part of minit pkg.
+ [ -f /sbin/minit ] && REBOOTEXE='hard-reboot RESTART' #note, hard-reboot is part of minit pkg.
+
+TTY=`tty`
+test -c "$TTY" || TTY=/dev/console
+
 
 /etc/rc.d/rc.shutdown
 
-exec /bin/busybox reboot
+case $? in
+0) exec ${REBOOTEXE} "$@"  #>/dev/null 2>&1
+   ;;
+*) #non-zero: an error occured
+   #maybe killed by fuser or killzombies
+   echo -e "$COLOR_RED""An Error Occurred." >"$TTY"
+   echo -e "$COLOR_red""Will return to X desktop." >"$TTY"
+   sleep 5s
+   mountpoint $Q /dev/pts || mount -t devpts devpts /dev/pts
+   mountpoint $Q /sys     || mount -t sysfs sysfs /sys
+   mountpoint $Q /proc    || mount -t proc proc /proc
+   exec xwin
+   ;;
+esac
+
+
