/sbin/reboot : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/sbin/reboot b/woof-code/rootfs-skeleton/sbin/reboot
--- a/woof-code/rootfs-skeleton/sbin/reboot
+++ b/woof-code/rootfs-skeleton/sbin/reboot
@@ -1,61 +1,78 @@
-#!/bin/bash
-
-Version='1.1 KRG'
+#!/bin/sh
 
 ERR=/dev/null;OUT=$ERR;VERB='';L_VERB='';A_VERB='';QUIET='-q'; ##+++2012-03-10
 [ "$DEBUG" ] && { ERR=/dev/stderr;OUT=/dev/stdout;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;QUIET=''; }
 
-usage(){
-MSG="
-$0 [help[|force|debug|verbose]|BB PARAMETERS]
-Version $Version .
-Puppy reboot script to run
-/etc/rc.d/rc.shutdown and finally
-/bin/busybox reboot .
-Simple PARAMETERS
-verbose,debug,force are passed to rc.shutdown,
-any other PARAMETERS get passed to busybox reboot .
-`busybox reboot --help 2>&1`
-"
-if [ "$2" ];then
-MSG="$MSG
+usage(){ echo "help for $0:
+When runs , checks if X not running .
+If X is running executing `which wmreboot` .
+wmreboot kills X and wm and 
+$0 runs /etc/rc.d/rc.shutdown
+and finally executes /bin/busybox reboot ." ; }
 
-$2
-"
-fi
-echo "$MSG"
-[ "$DISPLAY" ] && xmessage -bg black -fg yellow "$MSG"
-exit $1
-}
+PARAMETERS="$@"
+#PARAMETERS=`echo "$PARAMETERS" | tr '[[:upper:]]' '[[:lower:]]'`
+for param in $PARAMETERS; do
+echo $param >$OUT
+case $param in
+#h|-h|help|-help|--help) usage;exit 0;;
+[Hh]|-[Hh]|[-]*[Hh]*|[Hh]*) usage;exit 0;;
 
-#grep $QUIET -E 'help|usage' <<<$@ && usage 0 ##+++2012-03-10
+v|-v|verbose|[-]*verbose) VERBOSE=1; QUIET='';
+VERB=-v;L_VERB=--verbose;A_VERB=-verbose
+;;
+D|-D|debug|[-]*debug) DEBUG=1
+err=/dev/console;out=/dev/console #;output=$out $err
+;;
+s|-s|silent|[-]*silent) SILENT=1
+err=/dev/console;out=/dev/null
+;;
+q|-q|quiet|[-]*quiet) QUIET=1
+err=/dev/null;out=/dev/null #;output=$out $err
+;;
+*) BB_REBOOT="$BB_REBOOT $param";;
 
-for p in $@;do
-[ "$DEBUG" ] && echo $p
-case $p in
-help|usage)
-/etc/rc.d/rc.shutdown $p
-usage 0;;
-force|debug|verbose) RC="$RC $p" ;;
-*) RBOOT="$RBOOT $p" ;;
-esac;done
+esac
+done
 
-#if [ "`ps | grep -w 'X' | grep -v 'grep'`" ]; then
-if [ "`pidof X`" ]; then ##+++2012-03-10
-echo "Using '`which wm${0##*/}`' '$@'..."
-exec wmreboot "$@"
-fi
+#[ "$DISPLAY" ] && exit
 
-SHUT_HOW='rebooting' /etc/rc.d/rc.shutdown "$RC"
-RV="$?"
-[ "$RV" = '199' ] && exit 0
-[ "$RV" != '0' ] && exit 1
-
-KERNEL=`uname -r`
-if [ "${KERNEL:0:1}" = 3 ] ; then
-RBOOT="$RBOOT -f -n"
-elif [ "${KERNEL:0:1}" = 2 -a "${KERNEL:2:1}" = 6 -a "`echo "${KERNEL:4:2}" | sed 's|[^[:digit:]]||'`" -gt 34 ] ; then
-RBOOT="$RBOOT -f -n"
+#if [ -n "`ps | grep 'X :' | grep -v 'grep'`" ]; then
+if [ "`pidof X`" ]; then
+exec wmreboot $PARAMETERS
+exit
 fi
 
-exec /bin/busybox reboot $RBOOT
+RETval=''
+SHUT_HOW='rebooting' /etc/rc.d/rc.shutdown $PARAMETERS || RETval=$?
+if [ "$RETval" ];then
+case $RETval in
+199) echo;return 0 2>$ERR || exit 0;;
+*)
+echo -e "\n\e[1;31m""ERROR: < $RETval > canceling rc.shutdown""\e[0;39m"
+return $RETval 2>$ERR || exit $RETval
+;;
+esac
+fi
+
+#bash-3.2# busybox reboot --help
+#BusyBox v1.18.3 (2011-05-01 19:45:13 CEST) multi-call binary.
+#
+#Usage: reboot [-d DELAY] [-n] [-f]
+#
+#Reboot the system
+#
+#Options:
+#	-d SEC	Delay interval
+#	-n	Do not sync
+#	-f	Force (don't go through init)
+#
+#bash-3.2#
+BB_REBOOT="$BB_REBOOT -f"
+KERNEL_MAJOR=`uname -r |cut -f1 -d.`
+KERNEL_THREE=`uname -r |cut -f3 -d. |grep -o -e '^[0-9]*'`
+if [ "$KERNEL_MAJOR" -eq 2 -a "$KERNEL_THREE" -lt 37 ] ; then
+BB_REBOOT="${BB_REBOOT// \-f/}"
+fi
+echo "Executing /bin/busybox reboot '$BB_REBOOT'"
+exec /bin/busybox reboot $BB_REBOOT
