/sbin/reboot: Clean up code.

diff --git a/woof-code/rootfs-skeleton/sbin/reboot b/woof-code/rootfs-skeleton/sbin/reboot
--- a/woof-code/rootfs-skeleton/sbin/reboot
+++ b/woof-code/rootfs-skeleton/sbin/reboot
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/ash
 #
 # New header by Karl Reimer Godt, September 2014
   _TITLE_="Puppy_reboot"
@@ -15,11 +15,11 @@ ADD_PARAMETER_LIST=""
 ADD_PARAMETERS=""
 _provide_basic_parameters
 
-TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
+TWO_HELP='1'; TWO_VERSION='1'; TWO_VERBOSE='1'; TWO_DEBUG='1'; ## Set to anything if code requires further down (ie. custom usage or version message)
 ADD_HELP_MSG="$_COMMENT_"
 _parse_basic_parameters "$@"
-#[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
-#  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
 
 _trap
 
@@ -27,15 +27,23 @@ _trap
 # End new header
 #
 
-ERR=/dev/null;OUT=$ERR;VERB='';L_VERB='';A_VERB='';QUIET='-q'; ##+++2012-03-10
-[ "$DEBUG" ] && { ERR=/dev/stderr;OUT=/dev/stdout;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;QUIET=''; }
+#ERR=/dev/null;OUT=$ERR;VERB='';L_VERB='';A_VERB='';QUIET='-q'; ##+++2012-03-10
+#[ "$DEBUG" ] && { ERR=/dev/stderr;OUT=/dev/stdout;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;QUIET=''; }
 
 usage(){ echo "help for $0:
 When runs , checks if X not running .
 If X is running executing `which wmreboot` .
 wmreboot kills X and wm and
 $0 runs /etc/rc.d/rc.shutdown
-and finally executes /bin/busybox reboot ." ; }
+and finally executes /bin/busybox reboot .
+
+Options:
+
+busybox reboot options:
+`busybox reboot --help 2>&1`
+"
+
+/etc/rc.d/rc.shutdown --help ; }
 
 PARAMETERS="$@"
 #PARAMETERS=`echo "$PARAMETERS" | tr '[[:upper:]]' '[[:lower:]]'`
@@ -49,13 +57,13 @@ v|-v|verbose|[-]*verbose) VERBOSE=1; QUIET='';
 VERB=-v;L_VERB=--verbose;A_VERB=-verbose
 ;;
 D|-D|debug|[-]*debug) DEBUG=1
-err=/dev/console;out=/dev/console #;output=$out $err
+ERR=/dev/console;OUT=/dev/console #;output=$out $err
 ;;
 s|-s|silent|[-]*silent) SILENT=1
-err=/dev/console;out=/dev/null
+ERR=/dev/console;OUT=/dev/null
 ;;
 q|-q|quiet|[-]*quiet) QUIET=1
-err=/dev/null;out=/dev/null #;output=$out $err
+ERR=/dev/null;OUT=/dev/null #;output=$out $err
 ;;
 *) BB_REBOOT="$BB_REBOOT $param";;
 
@@ -70,19 +78,18 @@ exec wmreboot $PARAMETERS
 exit
 fi
 
-RETval=''
-SHUT_HOW='rebooting' /etc/rc.d/rc.shutdown $PARAMETERS || RETval=$?
-if [ "$RETval" ];then
-case $RETval in
+retVAL=''
+SHUT_HOW='rebooting' /etc/rc.d/rc.shutdown $PARAMETERS || retVAL=$?
+if [ "$retVAL" ];then
+case $retVAL in
 199) echo;return 0 2>$ERR || exit 0;;
 *)
-echo -e "\n\e[1;31m""ERROR: < $RETval > canceling rc.shutdown""\e[0;39m"
-return $RETval 2>$ERR || exit $RETval
+echo -e "\n\e[1;31m""ERROR: < $retVAL > canceling rc.shutdown""\e[0;39m"
+return $retVAL 2>$ERR || exit $retVAL
 ;;
 esac
 fi
 
-#bash-3.2# busybox reboot --help
 #BusyBox v1.18.3 (2011-05-01 19:45:13 CEST) multi-call binary.
 #
 #Usage: reboot [-d DELAY] [-n] [-f]
@@ -94,12 +101,14 @@ fi
 #   -n  Do not sync
 #   -f  Force (don't go through init)
 #
-#bash-3.2#
+
 BB_REBOOT="$BB_REBOOT -f"
 KERNEL_MAJOR=`uname -r |cut -f1 -d.`
 KERNEL_THREE=`uname -r |cut -f3 -d. |grep -o -e '^[0-9]*'`
 if [ "$KERNEL_MAJOR" -eq 2 -a "$KERNEL_THREE" -lt 37 ] ; then
 BB_REBOOT="${BB_REBOOT// \-f/}"
 fi
-echo "Executing /bin/busybox reboot '$BB_REBOOT'"
+echo -e "\\033[1;33m
+Executing /bin/busybox reboot '$BB_REBOOT'
+:\\033[0;39m"
 exec /bin/busybox reboot $BB_REBOOT
