/bin/mountMTP : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/bin/mountMTP b/woof-code/rootfs-skeleton/bin/mountMTP
--- a/woof-code/rootfs-skeleton/bin/mountMTP
+++ b/woof-code/rootfs-skeleton/bin/mountMTP
@@ -10,14 +10,16 @@ test -L /bin/mount    || _exit 4 "/bin/mount needs to be a link"
 test -e /bin/mountBAK || cp -a /bin/mount /bin/mountBAK
 
 test -e /bin/mountMTP.sh || {
-echo 'exit 0' >/bin/mountMTP.sh
-chmod +x /bin/mountMTP.sh
+echo 'exit 0' >/bin/mountMTP.sh || _exit 41 "Could not create /bin/mountMTP.sh wrapper"
+chmod $VERB +x /bin/mountMTP.sh || _exit 42 "Could not set /bin/mountMTP.sh executable"
 }
 
 OLD_MOUNT=`realpath /bin/mount`
+# REM: Needs here in case of early exit
+#      link /bin/mount does
+which go-mtpfs >>$OUT || _exit 6 "go-mtpfs not found in PATH"
 
-ln -sf mountMTP.sh /bin/mount || _exit 5 "Could not create link /bin/mount -> mountMTP.sh"
-
+ln $VERB -sf mountMTP.sh /bin/mount || _exit 5 "Could not create link /bin/mount -> mountMTP.sh"
 
 MOUNT_POINT=/mntf/MTPdev
 test -e "$MOUNT_POINT" || mkdir -p "$MOUNT_POINT"
@@ -27,4 +29,8 @@ go-mtpfs $GO_MTPFS_OPS "$MOUNT_POINT" &
 
 sleep 5
 
-ln -sf "$OLD_MOUNT" /bin/mount
+ln $VERB -sf "$OLD_MOUNT" /bin/mount
+_pidof go-mtpfs && exit 0 || exit 1
+
+# TODO: Handle GetStorageInfo 10001: SessionNotOpen
+#       app. when mtpdevice switches into lower-power-mode
