/bin/mount : Less verbosity in normal mode. To turn on verbose mode : VERBOSE=1 mount /dev/sdAX .

diff --git a/woof-code/rootfs-skeleton/bin/mount b/woof-code/rootfs-skeleton/bin/mount
--- a/woof-code/rootfs-skeleton/bin/mount
+++ b/woof-code/rootfs-skeleton/bin/mount
@@ -90,7 +90,7 @@ j=0
 for i in `seq 1 $#` ; do
 j=$((j+1))
 PARAM=`echo "$*" | cut -f $i -d ' '`
-echo '$'$j' ='"$PARAM"
+[ "$VERBOSE" = 1 ] && echo "\$j='$PARAM'"
 eval PARAME$j='\\'"${PARAM}"
 eval echo "\$PARAME$j"
 if [ -n "`echo $PARAM | grep '/' | grep -v /dev/`" ] ; then
@@ -116,16 +116,16 @@ MYPID=${$}
 #ALREADYMOUNTED=`busybox mount | cut -f 1 -d ' '`
 ALREADYMOUNTED=`cut -f1 -d ' ' /proc/mounts`
 SIMPLEMOUNT=''
-echo 'Simple mount begin'
+[ "$VERBOSE" = 1 ] && echo 'Simple mount begin'
 if [[ -n "`echo $1 | grep -E '/dev/|/mnt/'`" ]] && [[ "`echo "$@"`" = "$1" ]] && [[ -z "$2" ]] ; then
 #GREPPARAM=`echo "$1" | sed 's#-#\\\-#g'`
 #GREPPARAM=`echo "$1" | sed 's/\([[:punct:]]\)/\\\\\1/g; s/\\\\\\\\\\\/\\\/g'`
 ## from /sbin/init      sed 's/\([[:punct:]]\)/\\\\\1/g; s/\\\\/\\/g ; s#\ #\\\ #g ; s/ $// ; s/\\$//'
 GREPPARAM=$(echo "$1" | sed 's/\([[:punct:]]\)/\\\\\1/g ; s/\(\\\\\\\)*$//' | tr -s '\\')
-echo 'if #1'
+[ "$VERBOSE" = 1 ] && echo 'if #1'
 echo GREPPARAM="$GREPPARAM"
 if [ ! -f /etc/fstab ] || [ -z "`grep -w "$GREPPARAM" /etc/fstab | grep -v -E -e '^#|^[[:blank:]]*#'`" ] ; then
-echo 'if #2'
+[ "$VERBOSE" = 1 ] && echo 'if #2'
 simpledriveandpartitionname=`echo "$1" | sed 's#^/dev/## ; s#^/mnt/##'`
 [ -d "/mnt/$simpledriveandpartitionname" ] || mkdir "/mnt/$simpledriveandpartitionname"
 SIMPLEMOUNT="/dev/$simpledriveandpartitionname /mnt/$simpledriveandpartitionname"
@@ -133,7 +133,7 @@ fi
 fi
 
 #PARAMSCOMPLETE=`echo "$@" | sed 's#^# # ; s#$# #'`
-echo 'Part -a begin'
+[ "$VERBOSE" = 1 ] && echo 'Part -a begin'
 echo '|'"$@"'|'
 opt_a_PATTERN=`echo " $@" | grep -w -E -e '\ \-[a-z]*a[a-z]*|\ \-a[a-z]*|\ \-[a-z]*a|\ \-a' | sed 's#^ *##' | tr -s ' '`
 echo opt_a_PATTERN="$opt_a_PATTERN"
@@ -141,15 +141,15 @@ echo opt_a_PATTERN="$opt_a_PATTERN"
 if [[ -n "$opt_a_PATTERN" ]] ; then
 ### option -a given
 ### filer other params
-echo '144'
+[ "$VERBOSE" = 1 ] && echo '144'
 count_PARAMS=$(( $(echo "$opt_a_PATTERN" | wc -c) - 2 ))
-echo "count_PARAMS='$count_PARAMS'"
+[ "$VERBOSE" = 1 ] && echo "count_PARAMS='$count_PARAMS'"
 
 for i in `seq 0 $count_PARAMS` ; do
-echo $i
+[ "$VERBOSE" = 1 ] && echo $i
 PARAM=${opt_a_PATTERN:$i:1}
 [ "$PARAM" = " " ] && PARAM=''
-echo '|'"$PARAM"'|'
+[ "$VERBOSE" = 1 ] && echo '|'"$PARAM"'|'
 [ -z ${PARAM} ] || [ ${PARAM} = "a" ] && continue
 PARAMETERLINE="$PARAMETERLINE ${PARAM}"
 done
@@ -157,19 +157,19 @@ done
 PARAMETERLINE=`echo "$PARAMETERLINE" | sed 's# ##g ; s#-##g ; s#^#-#'`
 [ "$PARAMETERLINE" = "-" ] && PARAMETERLINE=''
 echo "PARAMETERLINE='$PARAMETERLINE'"
-echo 'if #3'
+[ "$VERBOSE" = 1 ] && echo 'if #3'
 
 if [ -n `readlink -f /etc/fstab` ] ; then
-echo 'if #4'
+[ "$VERBOSE" = 1 ] && echo 'if #4'
 FSTAB=`cat $(readlink -f /etc/fstab) | grep -E '^/dev/|^no' | grep -v -E -e 'noauto|^#|^[[:blank:]]*#' | tr '\t' ' ' | tr -s ' ' | sed 's/^[[:blank:]]*//'`
 MOUNTDIRS=`echo "$FSTAB" | cut -f 2 -d ' '`
 for i in $MOUNTDIRS ; do
-[ -d "$i" ] || { echo 'if #5';mkdir -p "$i"; }
+[ -d "$i" ] || { [ "$VERBOSE" = 1 ] && echo 'if #5';mkdir -p "$i"; }
 done
 
 ###first simple attempt###
 FSTYPES=`echo "$FSTAB" | cut -f 3 -d ' '`
-[ -n "`echo "$FSTYPES" | grep 'ntfs'`" ] && echo 'if #6' && SPECIALOPT='1'
+[ -n "`echo "$FSTYPES" | grep 'ntfs'`" ] && { [ "$VERBOSE" = 1 ] && echo 'if #6';SPECIALOPT='1'; }
 
 ###second loop attempt###
 for i in $MOUNTDIRS ; do
@@ -197,16 +197,16 @@ exit
 fi
 #######original part :
 else
-echo 'if #3 else'
+[ "$VERBOSE" = 1 ] && echo 'if #3 else'
 #v2.12 discovered difference between $@ and $*. Replaced all $@ with $* in this script...
 
 #extract all the '-' options, on separate lines... do NOT use $@!!!!...
 #v3.93 eliminate ' -- ' and all past it...
 DASHOPTS=`echo -n " $*" | tr '\t' ' ' | tr -s '[[:blank:]]' | sed 's/\(  *\)--\(  *\)/\1\2/g ; s#--$##' | tr ' ' '\n' | grep '^\-'` ##  ; s# *-- *##g## NOT needed anymore
-echo "DASHOPTS='$DASHOPTS'"
+[ "$VERBOSE" = 1 ] && echo "DASHOPTS='$DASHOPTS'"
 #needs an explicit '-t ntfs', does not work with /etc/fstab...
 if [ "`echo "$*" | grep 'ntfs'`" = "" ];then
-echo 'if #7'
+[ "$VERBOSE" = 1 ] && echo 'if #7'
  #v3.93 always use full mount, in case of params not understood by bb-mount...
  ##v2.10 hack for T2, scripts have '--bind'...
  #if [ "`echo -n "$*" | grep '\-\-bind'`" = "" ];then
@@ -217,15 +217,15 @@ echo 'if #7'
  # #as have mtab file (see below), can now use full mount...
   #v409 put in '-n' option as now have /etc/mtab symlink to /proc/mounts...
   if test -n "$SIMPLEMOUNT" ; then
-  echo 'if #8'
+  [ "$VERBOSE" = 1 ] && echo 'if #8'
   mount-FULL -n $SIMPLEMOUNT  ## does not work within double quotes
   RETVAL=$?
-  echo "mount-FULL simplemount RETVAL='$RETVAL'" #DBG
+  [ "$VERBOSE" = 1 ] && echo "mount-FULL simplemount RETVAL='$RETVAL'" #DBG
   else
-  echo 'if #8 else'
+  [ "$VERBOSE" = 1 ] && echo 'if #8 else'
   mount-FULL -n ${@}
   RETVAL=$?
-  echo "mount-FULL normal RETVAL='$RETVAL'" #DBG
+  [ "$VERBOSE" = 1 ] && echo "mount-FULL normal RETVAL='$RETVAL'" #DBG
  #fi
  fi
 else
@@ -237,7 +237,7 @@ else
  echo "CMDPRMS='$CMDPRMS'"
  ntfs-3g $CMDPRMS -o umask=0,no_def_opts 2>/tmp/ntfsmnterr${MYPID}.txt
  RETVAL=$?
- echo "ntfs-3g RETVAL='$RETVAL'"
+ [ "$VERBOSE" = 1 ] && echo "ntfs-3g RETVAL='$RETVAL'"
  #v2.16 ntfs-3g v1.417, part. scheduled for check, failed with value 10...
  #v4.00 ntfs-3g v1.2412 does not have 4,10, has 15 for dirty f.s., 14 hiberneted...
  if [ $RETVAL -eq 4 -o $RETVAL -eq 10 -o $RETVAL -eq 15 -o $RETVAL -eq 14 ];then  #try to force it...
@@ -250,7 +250,7 @@ else
    RETVAL=$?
    ERRMSG1=`cat /tmp/ntfsmnterr${MYPID}.txt`
    echo "ntfs-3gretval#4,10,15# RETVAL='$RETVAL'"
-   echo "$ERRMSG1"
+   [ "$VERBOSE" = 1 ] && echo "$ERRMSG1"
    if [ $RETVAL -eq 0 ];then
     echo "WARNING: NTFS f.s. mounted read/write but corrupted."
     [ "`pidof X`" = "" ] || nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was able to mount the NTFS
@@ -263,7 +263,7 @@ boot Windows and fix the filesystem first!!!" &
    fi
   fi
  fi
- echo "ntfs-3g_after_check_error_code RETVAL='$RETVAL'"
+ [ "$VERBOSE" = 1 ] && echo "ntfs-3g_after_check_error_code RETVAL='$RETVAL'"
  #ntfs-3g plays very safe and will not mount if thinks anything
  #wrong with ntfs f.s. But, we may want to recover files from a
  #damaged windows. So, fall back to the kernel ntfs driver...
@@ -271,9 +271,9 @@ boot Windows and fix the filesystem first!!!" &
   #mount read-only...
   busybox mount -r -t ntfs $CMDPRMS
   RETVAL=$?
-  echo "ntfs-3g switch to busybox mount RETVAL='$RETVAL'"
+  [ "$VERBOSE" = 1 ] && echo "ntfs-3g switch to busybox mount RETVAL='$RETVAL'"
   ERRMSG1=`cat /tmp/ntfsmnterr${MYPID}.txt`
-  echo "$ERRMSG1"
+  [ "$VERBOSE" = 1 ] && echo "$ERRMSG1"
   if [ $RETVAL -eq 0 ];then
    echo "WARNING: NTFS f.s. mounted read-only."
    [ "`pidof X`" = "" ] || nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was unable to mount the NTFS
@@ -287,39 +287,39 @@ to mount the partition read-only." &
 fi
 fi
 echo "final mount RETVAL='$RETVAL'"
-echo "DISPLAY='$DISPLAY'"
+[ "$VERBOSE" = 1 ] && echo "DISPLAY='$DISPLAY'"
 #v4.02 if there is a desktop icon (see pup_eventd), then refresh it...
 ##if [ "$RETVAL" -eq 0 -a "$DISPLAY" != "" ];then
 if [ -n "$DISPLAY" ] ; then  ##1
  ##DEVNAME="`busybox mount | tail -n 1 | grep '^/dev/' | cut -f 1 -d ' ' | cut -f 3 -d '/'`"
  #DEVNAMES="`busybox mount | cut -f 1 -d " " | /bin/grep -v -w "$ALREADYMOUNTED"`"
  DEVNAMES=`cut -f 1 -d ' ' /proc/mounts | /bin/grep -v -F -w "$ALREADYMOUNTED"`
- echo "DEVNAMES='$DEVNAMES'"
+ [ "$VERBOSE" = 1 ] && echo "DEVNAMES='$DEVNAMES'"
  ##if [ "$DEVNAME" != "" ];then  ##2
   for i in $DEVNAMES ; do
   DEVNAME=`basename $i`
   DRVNAME=`echo -n "$DEVNAME" | cut -c 1-3`
-  echo "DRVNAME='$DRVNAME'"
+  [ "$VERBOSE" = 1 ] && echo "DRVNAME='$DRVNAME'"
   #special case, SD card /dev/mmcblk0p1...
   [ "$DRVNAME" = "mmc" ] && DRVNAME=`echo -n "$DEVNAME" | sed -e 's/p[0-9]$//'`
   xDRVNAME="$DRVNAME" #v404
-  echo "xDRVNAME='$xDRVNAME'"
+  [ "$VERBOSE" = 1 ] && echo "xDRVNAME='$xDRVNAME'"
   [ -d /root/.pup_event/drive_${DEVNAME} ] && DRVNAME="$DEVNAME" #icon for each partition.
-  echo "DRVNAME='$DRVNAME'"
+  [ "$VERBOSE" = 1 ] && echo "DRVNAME='$DRVNAME'"
   if [ -d /root/.pup_event/drive_${DRVNAME} ];then  ##3
-   echo "/root/.pup_event/drive_'$DRVNAME' exists"
+   [ "$VERBOSE" = 1 ] && echo "/root/.pup_event/drive_'$DRVNAME' exists"
    case $DRVNAME in #v407
     fd*)
      DRV_CATEGORY="floppy"
-     echo "DRV_CATEGORY='$DRV_CATEGORY'"
+     [ "$VERBOSE" = 1 ] && echo "DRV_CATEGORY='$DRV_CATEGORY'"
     ;;
     *)
      dnPATTERN='/dev/'"${xDRVNAME}"'|'
      DRV_CATEGORY=`probedisk2 | grep "$dnPATTERN" | cut -f 2 -d '|'`
-     echo "dnPATTERN='$dnPATTERN' DRV_CATEGORY='$DRV_CATEGORY'"
+     [ "$VERBOSE" = 1 ] && echo "dnPATTERN='$dnPATTERN' DRV_CATEGORY='$DRV_CATEGORY'"
     ;;
    esac
-   echo 'starting icon_mounted_func ...'
+   [ "$VERBOSE" = 1 ] && echo 'starting icon_mounted_func ...'
    icon_mounted_func $DRVNAME $DRV_CATEGORY #see functions4puppy4
    echo '... returned from icon mounted func'
   fi  ##3
@@ -345,6 +345,6 @@ fi
 echo "RETVAL='$RETVAL'"
 [ "$RETVAL" = 0 ] || {
 [ "$simpledriveandpartitionname" -a -d "/mnt/$simpledriveandpartitionname" ] && rmdir "/mnt/$simpledriveandpartitionname"; }
-echo "... '$0' ...finished."
+[ "$VERBOSE" = 1 ] && echo "... '$0' ...finished."
 
 exit $RETVAL
