/bin/mount : Quotes cleanup.

diff --git a/woof-code/rootfs-skeleton/bin/mount b/woof-code/rootfs-skeleton/bin/mount
--- a/woof-code/rootfs-skeleton/bin/mount
+++ b/woof-code/rootfs-skeleton/bin/mount
@@ -127,36 +127,36 @@ echo GREPPARAM="$GREPPARAM"
 if [ ! -f /etc/fstab ] || [ -z "`grep -w "$GREPPARAM" /etc/fstab | grep -v -E -e '^#|^[[:blank:]]*#'`" ] ; then
 echo 'if #2'
 simpledriveandpartitionname=`echo "$1" | sed 's#^/dev/## ; s#^/mnt/##'`
-[ ! -d /mnt/$simpledriveandpartitionname ] && mkdir /mnt/$simpledriveandpartitionname
+[ -d "/mnt/$simpledriveandpartitionname" ] || mkdir "/mnt/$simpledriveandpartitionname"
 SIMPLEMOUNT="/dev/$simpledriveandpartitionname /mnt/$simpledriveandpartitionname"
 fi
 fi
 
 #PARAMSCOMPLETE=`echo "$@" | sed 's#^# # ; s#$# #'`
 echo 'Part -a begin'
-echo ':'"$@"':'
+echo '|'"$@"'|'
 opt_a_PATTERN=`echo " $@" | grep -w -E -e '\ \-[a-z]*a[a-z]*|\ \-a[a-z]*|\ \-[a-z]*a|\ \-a' | sed 's#^ *##' | tr -s ' '`
 echo opt_a_PATTERN="$opt_a_PATTERN"
 
 if [[ -n "$opt_a_PATTERN" ]] ; then
 ### option -a given
 ### filer other params
-echo '70 74'
+echo '144'
 count_PARAMS=$(( $(echo "$opt_a_PATTERN" | wc -c) - 2 ))
-echo count_PARAMS=$count_PARAMS
+echo "count_PARAMS='$count_PARAMS'"
 
 for i in `seq 0 $count_PARAMS` ; do
 echo $i
 PARAM=${opt_a_PATTERN:$i:1}
 [ "$PARAM" = " " ] && PARAM=''
-echo ':'$PARAM':'
+echo '|'"$PARAM"'|'
 [ -z ${PARAM} ] || [ ${PARAM} = "a" ] && continue
 PARAMETERLINE="$PARAMETERLINE ${PARAM}"
 done
 
 PARAMETERLINE=`echo "$PARAMETERLINE" | sed 's# ##g ; s#-##g ; s#^#-#'`
 [ "$PARAMETERLINE" = "-" ] && PARAMETERLINE=''
-echo 'PARAMETERLINE='"$PARAMETERLINE"
+echo "PARAMETERLINE='$PARAMETERLINE'"
 echo 'if #3'
 
 if [ -n `readlink -f /etc/fstab` ] ; then
@@ -164,7 +164,7 @@ echo 'if #4'
 FSTAB=`cat $(readlink -f /etc/fstab) | grep -E '^/dev/|^no' | grep -v -E -e 'noauto|^#|^[[:blank:]]*#' | tr '\t' ' ' | tr -s ' ' | sed 's/^[[:blank:]]*//'`
 MOUNTDIRS=`echo "$FSTAB" | cut -f 2 -d ' '`
 for i in $MOUNTDIRS ; do
-[ ! -d $i ] && echo 'if #5' && mkdir -p $i
+[ -d "$i" ] || { echo 'if #5';mkdir -p "$i"; }
 done
 
 ###first simple attempt###
@@ -174,11 +174,11 @@ FSTYPES=`echo "$FSTAB" | cut -f 3 -d ' '`
 ###second loop attempt###
 for i in $MOUNTDIRS ; do
 DEVICE=`echo "$FSTAB" | grep "$i" | cut -f 1 -d ' '`
-[ ! "$DEVICE" ] && echo -e "\e[31mError , no device specified for $i\e[39m" && continue
+[ "$DEVICE" ] || { echo -e "\e[31mError, no device specified for '$i'\e[39m";continue; }
 FSTYPE=`echo "$FSTAB" | grep "$i" | cut -f 3 -d ' '`
-[ ! "$FSTYPE" ] && echo -e "\e[31mError , no file system type  specified for $i\e[39m" && continue
+[ "$FSTYPE" ] || { echo -e "\e[31mError, no file system type specified for '$i'\e[39m";continue; }
 OPTION=`echo "$FSTAB" | grep "$i" | cut -f 4 -d ' '`
-[ ! "$OPTION" ] && echo -e "\e[31mError , no option(s) specified for $i\e[39m" && continue
+[ "$OPTION" ] || { echo -e "\e[31mError, no option(s) specified for '$i'\e[39m";continue; }
 
 MOUNTLINE="${PARAMETERLINE} -t ${FSTYPE} -o ${OPTION} ${DEVICE} $i"
 
@@ -186,13 +186,13 @@ if [ -z "`busybox mount | grep "$i"`" ] ; then
 mount-FULL $MOUNTLINE  #no double quotes at least for ash here ; this seems to sqeeze multiple following spaces into one space
 RETVAL=$?
 if [ "$RETVAL" != "0" ] ; then
-echo 'ERROR mounting' "$MOUNTLINE"
+echo "$0:ERROR mounting '$MOUNTLINE'"
 fi
 #mount-FULL "$PARAMETERLINE" "$DEVICE" "$i" -t "$FSTYPE" -o "$OPTION"
 fi
 done
 else
-echo -e "\\033[0;31m""Error , option '-a' given but fstab does not exists""\\033[0;39m"
+echo -e "\\033[0;31m""Error, option '-a' given but /etc/fstab does not exist.""\\033[0;39m"
 exit
 fi
 #######original part :
@@ -202,8 +202,8 @@ echo 'if #3 else'
 
 #extract all the '-' options, on separate lines... do NOT use $@!!!!...
 #v3.93 eliminate ' -- ' and all past it...
-DASHOPTS="`echo -n " $*" | tr '\t' ' ' | tr -s '[[:blank:]]' | sed 's/\(  *\)--\(  *\)/\1\2/g ; s#--$##' | tr ' ' '\n' | grep '^\-'`"  ##  ; s# *-- *##g## NOT needed anymore
-echo 'DASHOPTS='$DASHOPTS'='
+DASHOPTS=`echo -n " $*" | tr '\t' ' ' | tr -s '[[:blank:]]' | sed 's/\(  *\)--\(  *\)/\1\2/g ; s#--$##' | tr ' ' '\n' | grep '^\-'` ##  ; s# *-- *##g## NOT needed anymore
+echo "DASHOPTS='$DASHOPTS'"
 #needs an explicit '-t ntfs', does not work with /etc/fstab...
 if [ "`echo "$*" | grep 'ntfs'`" = "" ];then
 echo 'if #7'
@@ -220,24 +220,24 @@ echo 'if #7'
   echo 'if #8'
   mount-FULL -n $SIMPLEMOUNT  ## does not work within double quotes
   RETVAL=$?
-  echo 'mount-FULLsimplemount$RETVAL='"$RETVAL" #DBG
+  echo "mount-FULL simplemount RETVAL='$RETVAL'" #DBG
   else
   echo 'if #8 else'
   mount-FULL -n ${@}
   RETVAL=$?
-  echo 'mount-FULLnormal$RETVAL='"$RETVAL" #DBG
+  echo "mount-FULL normal RETVAL='$RETVAL'" #DBG
  #fi
  fi
 else
  #screen out all the options...
- CMDPRMS="`echo -n "$*" | tr '\t' ' ' | tr -s ' ' | tr ' ' '\n' | grep '^/' | tr '\n' ' '`"
+ CMDPRMS=`echo -n "$*" | tr '\t' ' ' | tr -s ' ' | tr ' ' '\n' | grep '^/' | tr '\n' ' '`
  #kirk advised these options so Rox will not complain about file
  #permissions when copy a file to a ntfs partition...
  [ -f /tmp/ntfsmnterr${MYPID}.txt ] && rm -f /tmp/ntfsmnterr${MYPID}.txt
- echo 'CMDPRMS='"$CMDPRMS"
+ echo "CMDPRMS='$CMDPRMS'"
  ntfs-3g $CMDPRMS -o umask=0,no_def_opts 2>/tmp/ntfsmnterr${MYPID}.txt
  RETVAL=$?
- echo 'ntfs-3g$RETVAL='"$RETVAL"
+ echo "ntfs-3g RETVAL='$RETVAL'"
  #v2.16 ntfs-3g v1.417, part. scheduled for check, failed with value 10...
  #v4.00 ntfs-3g v1.2412 does not have 4,10, has 15 for dirty f.s., 14 hiberneted...
  if [ $RETVAL -eq 4 -o $RETVAL -eq 10 -o $RETVAL -eq 15 -o $RETVAL -eq 14 ];then  #try to force it...
@@ -248,12 +248,12 @@ else
   else
    ntfs-3g $CMDPRMS -o force,umask=0,no_def_opts 2>/tmp/ntfsmnterr${MYPID}.txt
    RETVAL=$?
-   ERRMSG1="`cat /tmp/ntfsmnterr${MYPID}.txt`"
-   echo 'ntfs-3gretval#4,10,15#$RETVAL='"$RETVAL"
+   ERRMSG1=`cat /tmp/ntfsmnterr${MYPID}.txt`
+   echo "ntfs-3gretval#4,10,15# RETVAL='$RETVAL'"
    echo "$ERRMSG1"
    if [ $RETVAL -eq 0 ];then
     echo "WARNING: NTFS f.s. mounted read/write but corrupted."
-    [ ! "`pidof X`" = "" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was able to mount the NTFS
+    [ "`pidof X`" = "" ] || nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was able to mount the NTFS
 partition but returned this error message:
 $ERRMSG1
 
@@ -263,7 +263,7 @@ boot Windows and fix the filesystem first!!!" &
    fi
   fi
  fi
- echo 'ntfs-3g_after_check_error_code$RETVAL='"$RETVAL"
+ echo "ntfs-3g_after_check_error_code RETVAL='$RETVAL'"
  #ntfs-3g plays very safe and will not mount if thinks anything
  #wrong with ntfs f.s. But, we may want to recover files from a
  #damaged windows. So, fall back to the kernel ntfs driver...
@@ -271,12 +271,12 @@ boot Windows and fix the filesystem first!!!" &
   #mount read-only...
   busybox mount -r -t ntfs $CMDPRMS
   RETVAL=$?
-  echo 'ntfs-3g switch to busybox mount$RETVAL='"$RETVAL"
-  ERRMSG1="`cat /tmp/ntfsmnterr${MYPID}.txt`"
+  echo "ntfs-3g switch to busybox mount RETVAL='$RETVAL'"
+  ERRMSG1=`cat /tmp/ntfsmnterr${MYPID}.txt`
   echo "$ERRMSG1"
   if [ $RETVAL -eq 0 ];then
    echo "WARNING: NTFS f.s. mounted read-only."
-   [ ! "`pidof X`" = "" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was unable to mount the NTFS
+   [ "`pidof X`" = "" ] || nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was unable to mount the NTFS
 partition and returned this error message:
 $ERRMSG1
 
@@ -286,37 +286,37 @@ to mount the partition read-only." &
  fi
 fi
 fi
-echo 'final$RETVAL='"$RETVAL"
-echo '$DISPLAY    ='"$DISPLAY"
+echo "final mount RETVAL='$RETVAL'"
+echo "DISPLAY='$DISPLAY'"
 #v4.02 if there is a desktop icon (see pup_eventd), then refresh it...
 ##if [ "$RETVAL" -eq 0 -a "$DISPLAY" != "" ];then
 if [ -n "$DISPLAY" ] ; then  ##1
  ##DEVNAME="`busybox mount | tail -n 1 | grep '^/dev/' | cut -f 1 -d ' ' | cut -f 3 -d '/'`"
- DEVNAMES="`busybox mount | cut -f 1 -d " " | /bin/grep -v -w "$ALREADYMOUNTED"`"
+ #DEVNAMES="`busybox mount | cut -f 1 -d " " | /bin/grep -v -w "$ALREADYMOUNTED"`"
  DEVNAMES=`cut -f 1 -d ' ' /proc/mounts | /bin/grep -v -F -w "$ALREADYMOUNTED"`
- echo '$DEVNAMES   ='"$DEVNAMES"
+ echo "DEVNAMES='$DEVNAMES'"
  ##if [ "$DEVNAME" != "" ];then  ##2
   for i in $DEVNAMES ; do
   DEVNAME=`basename $i`
-  DRVNAME="`echo -n "$DEVNAME" | cut -c 1-3`"
-  echo 'DRVNAME     ='"$DRVNAME"
+  DRVNAME=`echo -n "$DEVNAME" | cut -c 1-3`
+  echo "DRVNAME='$DRVNAME'"
   #special case, SD card /dev/mmcblk0p1...
-  [ "$DRVNAME" = "mmc" ] && DRVNAME="`echo -n "$DEVNAME" | sed -e 's/p[0-9]$//'`"
+  [ "$DRVNAME" = "mmc" ] && DRVNAME=`echo -n "$DEVNAME" | sed -e 's/p[0-9]$//'`
   xDRVNAME="$DRVNAME" #v404
-  echo 'xDRVNAME    ='"$xDRVNAME"
+  echo "xDRVNAME='$xDRVNAME'"
   [ -d /root/.pup_event/drive_${DEVNAME} ] && DRVNAME="$DEVNAME" #icon for each partition.
-  echo 'DRVNAME     ='"$DRVNAME"
+  echo "DRVNAME='$DRVNAME'"
   if [ -d /root/.pup_event/drive_${DRVNAME} ];then  ##3
-   echo '/root/.pup_event/drive_'$DRVNAME' exists'
+   echo "/root/.pup_event/drive_'$DRVNAME' exists"
    case $DRVNAME in #v407
     fd*)
      DRV_CATEGORY="floppy"
-     echo '$DRV_CATEGORY='"$DRV_CATEGORY"
+     echo "DRV_CATEGORY='$DRV_CATEGORY'"
     ;;
     *)
      dnPATTERN='/dev/'"${xDRVNAME}"'|'
-     DRV_CATEGORY="`probedisk2 | grep "$dnPATTERN" | cut -f 2 -d '|'`"
-     echo 'dnPATTERN='"$dnPATTERN"' DRV_CATEGORY='"$DRV_CATEGORY"
+     DRV_CATEGORY=`probedisk2 | grep "$dnPATTERN" | cut -f 2 -d '|'`
+     echo "dnPATTERN='$dnPATTERN' DRV_CATEGORY='$DRV_CATEGORY'"
     ;;
    esac
    echo 'starting icon_mounted_func ...'
@@ -326,7 +326,7 @@ if [ -n "$DISPLAY" ] ; then  ##1
  done
 ## fi  ##2
 fi  ##1
-echo 'finishing now '"$0"' ...'
+echo "finishing now '$0' ..."
 #v409 now have /etc/mtab a symlink to /proc/mounts so this section not needed...
 ##v2.10 do not update /etc/mtab if '-n' option...
 #[ "`echo " $DASHOPTS" | grep '^\-n$'`" != "" ] && exit $RETVAL
@@ -342,9 +342,9 @@ if [ ! -L /etc/mtab ];then
  rm -f /etc/mtab
  ln -s /proc/mounts /etc/mtab
 fi
-echo '$RETVAL='"$RETVAL"
+echo "RETVAL='$RETVAL'"
 [ "$RETVAL" = 0 ] || {
 [ "$simpledriveandpartitionname" -a -d "/mnt/$simpledriveandpartitionname" ] && rmdir "/mnt/$simpledriveandpartitionname"; }
-echo '...'"$0"' finished'
+echo "... '$0' ...finished."
 
 exit $RETVAL
