mount/umount : Adjusted various files to use stat -f -c %T /proc instead test -f /proc/mounts to check if /proc is mounted. The mount command just needs the directory name of /proc . /proc may or may not exist and if exists may have content in unmounted status. The mount command ignores any content and mounts in overlay mode. Same with sysfs on /sys directory. But it refuses to mount further layers upon /proc and /sys, whereas on mounts of normal filesystems like ext2 it mounts in overlay mode - also tmpfs on /tmp and /dev are overlayed.
Further various fixes and bugfixes and cleanups.
Files modified :
/bin/: mount-old, mount.sh, mount2, umount2, ps
/sbin/: init
/usr/bin/: filemnt2
/etc/rc.d/: f4puppy5

diff --git a/woof-code/rootfs-skeleton/bin/mount-old b/woof-code/rootfs-skeleton/bin/mount-old
--- a/woof-code/rootfs-skeleton/bin/mount-old
+++ b/woof-code/rootfs-skeleton/bin/mount-old
@@ -2,20 +2,20 @@
 #
 # New header by Karl Reimer Godt, September 2014
   _TITLE_="Puppy_mount-old"
-_VERSION_=1.0omega
+_VERSION_=1.1omega
 _COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"
 
 MY_SELF="/bin/mount-old"
 MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
-[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5
+[ "$HAVE_F4PUPPY5" ] || . /etc/rc.d/f4puppy5
 
 ADD_PARAMETER_LIST=""
 ADD_PARAMETERS=""
 _provide_basic_parameters
 
-TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
+TWO_HELP='1'; TWO_VERSION='1'; TWO_VERBOSE='1'; TWO_DEBUG='1'; ## Set to anything if code requires further down (ie. custom usage or version message)
 ADD_HELP_MSG="$_COMMENT_"
 _parse_basic_parameters "$@"
 [ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
@@ -106,7 +106,7 @@ LANG=C
 
 ##################### usage version part ################################
 #Version='1.1-simple Puppy-Linux-4.3.0 KRG'
-Version='1.1-getopts Macpup_Foxy_3-Puppy-Linux-4.3.0 KRG'
+Version='1.2-getopts Macpup_Foxy_3-Puppy-Linux-4.3.0 KRG'
 
 #[ ! "$2" -a "$1" = "-q" ] && { busybox mount |sed "s|\(.*\) \(on\) \(.*\) \(type\) \(.*\) \(.*\)|'\1' \2 '\3' \4 '\5' \6|";exit $?; }
 #[ ! "$2" -a "$1" = '-Q' ] && { busybox mount |sed -r 's|(.*)( on )(.*)( type )(.*)( \(.*\))|"\1"\2"\3"\4"\5"\6|'; exit $?; }
@@ -136,21 +136,22 @@ Version='1.1-getopts Macpup_Foxy_3-Puppy-Linux-4.3.0 KRG'
 
 usage(){
 MSG="
-$0 [ pup options ] [ mount options ] DEVICE [DIR/]
+$0 [ wrapper options ] [ mount options ] DEVICE [DIR/]
 Script to fork different mount clis for the appropriate
 filesystem (ie ntfs-3g, mount-FULL, busybox mount) and
 manage the drive icons on the desktop.
 -H) this usage
--P) show version information
+-P) print version information
 
-Puppy Options (must be first option and only Puppy option)
--D) debug set -x
--C) codecheck set -n
+Wrapper Options (must be first option and only Wrapper option)
+-D)  print debug messages
+-DD) debug set -x
+-C)  codecheck set -n
 
 Normal Mount Option used additionally :
 -v) verbose
 
-Special Puppy only Option:
+Special wrapper only Option:
 -q) show mounts with single quoted output
 -Q) show mounts with double quoted output
 
@@ -158,25 +159,37 @@ For the appropriate mount binaries options,
 like mount-FULL, ntfs-3g, busybox mount,
 run BINARY --help|-h or man BINARY.
 "
+MSG=`gettext "${MSG}"`
 echo "$MSG"
-[ "$DISPLAY" ] && xmessage -bg orange2 "$MSG"
-exit $?
+[ "$DISPLAY" ] && xmessage -bg orange2 "$MSG" &
+exit $1
 }
 ##################### usage version part ################################
 
 
 ############# getopts part #####################
+
+##split $1 into single parameters #unused
+##params=`echo $1 | sed 's/^-*//;s/\(.\)/-\1 /g'`
+
+case $1 in
+*help)    usage 0;;
+*version) echo -e "$0: Version '$Version'\nTry -H for more info\n";exit 0;;
+esac
+
 OPTERR=0
 OUT=/dev/null;ERR=$OUT
-while getopts HPDv opt;do
+while getopts CDhHPv opt;do
 case $opt in
-H) usage 0;;
+h|H) usage 0;;
 P) echo -e "\n$0: Version '$Version'\n";exit 0;;
-D) DEBUG=1;set -x;shift;;
+D) DEBUG=$((DEBUG+1)); [ "$DEBUG" -ge 2 ] && set -x; shiftME=1;;
 v) VERBOSE=1;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;OUT=/dev/stdout;ERR=/dev/stderr;;
-C) set -n;shift;;
+C) setN=Y; shiftME=1;; #set -n;shift;; #set -n here hangs while loop..
 *) :;;
 esac;done
+test "$setN"    && set -n
+test "$shiftME" && shift
 ############# getopts part #####################
 
 
@@ -195,9 +208,9 @@ j=$((j+1))
 PARAM=`echo "$*" | cut -f $i -d ' '`
 [ "$DEBUG" -o "$VERBOSE" ] && echo '$'$j' ='"$PARAM"
 eval PARAME$j="${PARAM}"  ##+--2012-05-01 was eval PARAME$j='\\'"${PARAM}"
-[ "$DEBUG" -o "$VERBOSE" ] && eval echo "\$PARAME$j"    ##+--           showed as \/mnt/sda11
+[ "$DEBUG" -o "$VERBOSE" ] && eval echo "\$PARAME$j"    ##+-- showed as \/mnt/sda11
 if [ -n "`echo $PARAM | grep '/' | grep -v /dev/`" ] ; then
-[ -e "$PARAM" ] || { [ "$DEBUG" -o "$VERBOSE" ] && echo "Folder '$PARAM' does not exists. Creating now ...";mkdir -p "$PARAM"; }
+[ -e "$PARAM" ] || { [ "$DEBUG" -o "$VERBOSE" ] && echo "Folder '$PARAM' does not exists. Creating now ...";mkdir $VERB -p "$PARAM"; }
 fi
 done
 
@@ -233,11 +246,11 @@ if [[ -n "`echo $1 | grep -E '/dev/|/mnt/'`" ]] && [[ "`echo "$@"`" = "$1" ]] &&
 GREPPARAM=$(echo "$1" | sed 's/\([[:punct:]]\)/\\\\\1/g ; s/\(\\\\\\\)*$//' | tr -s '\\')
 [ "$DEBUG" ] && echo 'if #1'
 [ "$DEBUG" ] && echo GREPPARAM="$GREPPARAM"
-if [ ! -f /etc/fstab ] || [ -z "`grep -w "$GREPPARAM" /etc/fstab | grep -v -E -e '^#|^[[:blank:]]*#'`" ] ; then
+if [ ! -f /etc/fstab ] || [ -z "`grep -w "$GREPPARAM" /etc/fstab | grep -v -E '^#|^[[:blank:]]*#'`" ] ; then
 [ "$DEBUG" ] && echo 'if #2'
 simpledriveandpartitionname=`echo "$1" | sed 's#^/dev/## ; s#^/mnt/##'`
 #[ -d /mnt/$simpledriveandpartitionname ] || mkdir /mnt/$simpledriveandpartitionname
-mkdir -p /mnt/$simpledriveandpartitionname
+mkdir $VERB -p /mnt/$simpledriveandpartitionname
 
 SIMPLEMOUNT="/dev/$simpledriveandpartitionname /mnt/$simpledriveandpartitionname"
 
@@ -246,9 +259,9 @@ FS_TYPE=`guess_fstype /dev/$simpledriveandpartitionname`
 if [ "$FS_TYPE" = 'ntfs' ];then
 NTFS=1;fi
 
-elif [ "`grep -w "$GREPPARAM" /etc/fstab | grep -v -E -e '^#|^[[:blank:]]*#'`" ] ; then
-MOUNT_POINT=`grep -w "$GREPPARAM" /etc/fstab | grep -v -E -e '^#|^[[:blank:]]*#' |head -n1 |awk '{print $2}'`
-mkdir -p "$MOUNT_POINT"
+elif [ "`grep -w "$GREPPARAM" /etc/fstab | grep -v -E '^#|^[[:blank:]]*#'`" ] ; then
+MOUNT_POINT=`grep -w "$GREPPARAM" /etc/fstab | grep -v -E '^#|^[[:blank:]]*#' |head -n1 |awk '{print $2}'`
+mkdir $VERB -p "$MOUNT_POINT"
 
 fi
 fi
@@ -259,7 +272,7 @@ fi
 #PARAMSCOMPLETE=`echo "$@" | sed 's#^# # ; s#$# #'`
 [ "$DEBUG" ] && echo 'Part -a begin:'
 [ "$DEBUG" ] && echo ':'"$@"':'
-#opt_a_PATTERN=`echo " $@" | grep -w -E -e '\ \-[a-z]*a[a-z]*|\ \-a[a-z]*|\ \-[a-z]*a|\ \-a' | sed 's#^ *##' | tr -s ' '`
+#opt_a_PATTERN=`echo " $@" | grep -w -E '\ \-[a-z]*a[a-z]*|\ \-a[a-z]*|\ \-[a-z]*a|\ \-a' | sed 's#^ *##' | tr -s ' '`
 opt_a_PATTERN=`echo " $@" | grep -w -E -e '\ \-[[:alpha:]]*a[[:alpha:]]*|\ \-a[[:alpha:]]*|\ \-[[:alpha:]]*a|\ \-a' | sed 's#^ *##' | tr -s ' '`
 [ "$DEBUG" ] && echo "opt_a_PATTERN='$opt_a_PATTERN'"
 ############# manual alternative -a part ##############################################################################
@@ -286,10 +299,10 @@ PARAMETERLINE=`echo "$PARAMETERLINE" | sed 's# ##g ; s#-##g ; s#^#-#'`
 
 if [ -n `readlink -f /etc/fstab` ] ; then
 [ "$DEBUG" ] && echo 'if #4'
-FSTAB=`cat $(readlink -f /etc/fstab) | grep -E '^/dev/|^no' | grep -v -E -e 'noauto|^#|^[[:blank:]]*#' | tr '\t' ' ' | tr -s ' ' | sed 's/^[[:blank:]]*//'`
+FSTAB=`cat $(readlink -f /etc/fstab) | grep -E '^/dev/|^no' | grep -v -E 'noauto|^#|^[[:blank:]]*#' | tr '\t' ' ' | tr -s ' ' | sed 's/^[[:blank:]]*//'`
 MOUNTDIRS=`echo "$FSTAB" | cut -f 2 -d ' '`
 for i in $MOUNTDIRS ; do
-[ ! -d "$i" ] && { [ "$DEBUG" ] && echo 'if #5';mkdir -p "$i"; }
+[ ! -d "$i" ] && { [ "$DEBUG" ] && echo 'if #5';mkdir $VERB -p "$i"; }
 done
 
 ###first simple attempt###
@@ -359,14 +372,14 @@ if [ "`echo "$*" | grep 'ntfs'`" = "" ];then
     IFS='. ' read UPtime restU RUNtime restR </proc/uptime
     dmesg | tail | grep -w "$UPtime"
    fi
-  [ "$DEBUG" -o "$VERBOSE" ] && echo "mount-FULLsimplemount$RETVAL='$RETVAL'" #DBG
+  [ "$DEBUG" -o "$VERBOSE" ] && echo "mount-FULL simplemount RETVAL='$RETVAL'" #DBG
   else
   [ "$DEBUG" ] && echo 'if #8 else'
   mount-FULL -n "${@}"
   RETVAL=$?
   IFS='. ' read UPtime restU RUNtime restR </proc/uptime
   dmesg | tail | grep -w "$UPtime"
-  [ "$DEBUG" -o "$VERBOSE" ] && echo "mount-FULLnormal$RETVAL='$RETVAL'" #DBG
+  [ "$DEBUG" -o "$VERBOSE" ] && echo "mount-FULL normal RETVAL='$RETVAL'" #DBG
  #fi
  fi
 ######################## mount non-NTFS part #################################
@@ -382,13 +395,13 @@ else
  [ "$DEBUG" -o "$VERBOSE" ] && echo "CMDPRMS='$CMDPRMS'"
  ntfs-3g $CMDPRMS -o umask=0,no_def_opts 2>/tmp/ntfsmnterr${MYPID}.txt
  RETVAL=$?
- [ "$DEBUG" -o "$VERBOSE" ] && echo "ntfs-3g$RETVAL='$RETVAL'"
+ [ "$DEBUG" -o "$VERBOSE" ] && echo "ntfs-3g RETVAL='$RETVAL'"
 
  #v2.16 ntfs-3g v1.417, part. scheduled for check, failed with value 10...
  #v4.00 ntfs-3g v1.2412 does not have 4,10, has 15 for dirty f.s., 14 hiberneted...
 ####################### ntfs-3g force option ########################################################
- if [ $RETVAL -eq 4 -o $RETVAL -eq 10 -o $RETVAL -eq 15 -o $RETVAL -eq 14 ];then  #try to force it...
-  if [ $RETVAL -eq 14 ];then
+ if [ "$RETVAL" -eq 4 -o "$RETVAL" -eq 10 -o "$RETVAL" -eq 15 -o "$RETVAL" -eq 14 ];then  #try to force it...
+  if [ "$RETVAL" -eq 14 ];then
    #ntfs-3g $CMDPRMS -o umask=0,no_def_opts,remove_hiberfile 2>/tmp/ntfsmnterr${MYPID}.txt
    #RETVAL=$?
    #echo > /dev/null
@@ -397,11 +410,11 @@ else
    ntfs-3g $CMDPRMS -o force,umask=0,no_def_opts 2>/tmp/ntfsmnterr${MYPID}.txt
    RETVAL=$?
    ERRMSG1=`cat /tmp/ntfsmnterr${MYPID}.txt`
-   [ "$DEBUG" -o "$VERBOSE" ] && echo "ntfs-3gretval#4,10,15#$RETVAL='$RETVAL'"
+   [ "$DEBUG" -o "$VERBOSE" ] && echo "ntfs-3g retval#4,10,15# RETVAL='$RETVAL'"
    [ "$DEBUG" -o "$VERBOSE" ] && echo "$ERRMSG1"
-   if [ $RETVAL -eq 0 ];then
+   if [ "$RETVAL" -eq 0 ];then
     echo "WARNING: NTFS f.s. mounted read/write but corrupted."
-    [ ! "`pidof X`" = "" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was able to mount the NTFS
+    [ "`pidof X`" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was able to mount the NTFS
 partition but returned this error message:
 $ERRMSG1
 
@@ -413,7 +426,7 @@ boot Windows and fix the filesystem first!!!" &
  fi
 ####################### ntfs-3g force option ########################################################
 
- [ "$DEBUG" -o "$VERBOSE" ] && echo "ntfs-3g_after_check_error_code$RETVAL='$RETVAL'"
+ [ "$DEBUG" -o "$VERBOSE" ] && echo "ntfs-3g after_check_error_code RETVAL='$RETVAL'"
 
 ##################### ntfs mount with error ###################
  #ntfs-3g plays very safe and will not mount if thinks anything
@@ -421,18 +434,18 @@ boot Windows and fix the filesystem first!!!" &
  #damaged windows. So, fall back to the kernel ntfs driver...
 
 #################### busybox mount ntfs ro ############################################
- if [ ! $RETVAL -eq 0 ];then
+ if [ ! "$RETVAL" -eq 0 ];then
   #mount read-only...
-  busybox mount -r -t ntfs $CMDPRMS
+  busybox mount ${VERB:+'-vv'} -r -t ntfs $CMDPRMS
   RETVAL=$?
-  [ "$DEBUG" -o "$VERBOSE" ] && echo "ntfs-3g switch to busybox mount$RETVAL='$RETVAL'"
+  [ "$DEBUG" -o "$VERBOSE" ] && echo "ntfs-3g switch to busybox mount RETVAL='$RETVAL'"
   ERRMSG1=`cat /tmp/ntfsmnterr${MYPID}.txt`
   [ "$DEBUG" -o "$VERBOSE" ] && echo "$ERRMSG1"
 
 ################### present ro message ###########
-  if [ $RETVAL -eq 0 ];then
+  if [ "$RETVAL" -eq 0 ];then
    echo "WARNING: NTFS f.s. mounted read-only."
-   [ ! "`pidof X`" = "" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was unable to mount the NTFS
+   [ "`pidof X`" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was unable to mount the NTFS
 partition and returned this error message:
 $ERRMSG1
 
@@ -448,8 +461,8 @@ fi
 #######original mount part : ##################################################################
 
 
-[ "$DEBUG" -o "$VERBOSE" ] && echo "final$RETVAL='$RETVAL'"
-[ "$DEBUG" -o "$VERBOSE" ] && echo "$DISPLAY    ='$DISPLAY'"
+[ "$DEBUG" -o "$VERBOSE" ] && echo "final RETVAL='$RETVAL'"
+[ "$DEBUG" -o "$VERBOSE" ] && echo "DISPLAY     ='$DISPLAY'"
 
 
 ###################### DISPLAY and pup_event_frontend_d ####################################
@@ -458,7 +471,7 @@ fi
 if [ -n "$DISPLAY" -a "`pidof pup_event_frontend_d`" ] ; then  ##1
  ##DEVNAME=`busybox mount | tail -n 1 | grep '^/dev/' | cut -f 1 -d ' ' | cut -f 3 -d '/'`
  DEVNAMES=`busybox mount | cut -f 1 -d " " | grep -v -w "$ALREADYMOUNTED"`
- [ "$DEBUG" -o "$VERBOSE" ] && echo "$DEVNAMES   ='$DEVNAMES'"
+ [ "$DEBUG" -o "$VERBOSE" ] && echo "DEVNAMES    ='$DEVNAMES'"
  ##if [ "$DEVNAME" != "" ];then  ##2
   for i in $DEVNAMES ; do
   DEVNAME=`basename $i`
@@ -507,7 +520,7 @@ fi  ##1
 #v409, instead just make sure the symlink stays there...
 if [ ! -L /etc/mtab ];then
  rm -f /etc/mtab
- ln -s /proc/mounts /etc/mtab
+ ln -s ../proc/mounts /etc/mtab
 fi
 #################### mtab part #################################################
 
diff --git a/woof-code/rootfs-skeleton/usr/bin/filemnt2 b/woof-code/rootfs-skeleton/usr/bin/filemnt2
--- a/woof-code/rootfs-skeleton/usr/bin/filemnt2
+++ b/woof-code/rootfs-skeleton/usr/bin/filemnt2
@@ -14,7 +14,7 @@ TWO_DEBUG=1
 TWO_VERSION=1
 TWO_HELP=1
 TWO_VERBOSE=1
-#test -f /etc/rc.d/f4puppy5 && . /etc/rc.d/f4puppy5
+test -f /etc/rc.d/f4puppy5 && . /etc/rc.d/f4puppy5
 
 _exit()
 {
@@ -50,12 +50,6 @@ MAYBE_FILE=`echo -e "$*"`
 MAYBE_DIR="$MAYBE_FILE"
 _debug "MAYBE_FILE='$MAYBE_FILE'"
 ORIG_PARAMS="$*"
-
-if test -f "$*"; then FILE_MOUNT_LOOP="$*"; set --
-elif test -f "$MAYBE_FILE"; then FILE_MOUNT_LOOP="$MAYBE_FILE"; set --
-elif test -d "$*"; then FILE_MOUNT_POINT="$*"; set --
-elif test -d "$MAYBE_DIR"; then FILE_MOUNT_POINT="$MAYBE_DIR" ; set --
-fi
 
 _check_for_file_and_mountpoint(){
 while :
@@ -98,7 +92,7 @@ MSG_HELP="$MY_SELF_MSG:
  --verbose|-v) tell whats going on.
  --debug|-d)   print a lot of debugging.
 "
-[ "$*" ] && MSG_HELP="$$MSG_HELP
+[ "$*" ] && MSG_HELP="$MSG_HELP
 $*"
 gettext "$MSG_HELP"
 }
@@ -114,13 +108,21 @@ case $1 in
 -*help|-*h)     _tell_help; exit $?;;
 -*version|-*V)  _tell_version; exit $?;;
 -*verbose|-*v)  VERB=-v;;
--*debug|-*d)    VERB=-v;DEBUG=1;;
+-*debug|-*d)    VERB=-v;DEBUG=$((DEBUG+1));;
 *) _check_for_file_and_mountpoint "$1";;
 esac
 shift
 [ "$1" ] || break
 done
 }
+
+if test ! "$*"; then _tell_help; exit $?
+elif test -f "$*"; then FILE_MOUNT_LOOP="$*"; set --
+elif test -f "$MAYBE_FILE"; then FILE_MOUNT_LOOP="$MAYBE_FILE"; set --
+elif test -d "$*"; then FILE_MOUNT_POINT="$*"; set --
+elif test -d "$MAYBE_DIR"; then FILE_MOUNT_POINT="$MAYBE_DIR" ; set --
+fi
+
 test "$FILE_MOUNT_LOOP"    || _check_params "$@"
 
 if ! test "$FILE_MOUNT_POINT"; then
@@ -135,6 +137,20 @@ _debug "FILE_MOUNT_LOOP='$FILE_MOUNT_LOOP'"
 #
 
 # /mnt/home fix ?
+
+_alias_default(){
+alias rm="rm $VERB"
+alias cp="cp $VERB"
+alias mv="mv $VERB"
+alias ln="ln $VERB"
+alias mkdir="mkdir $VERB"
+alias rmdir="rmdir $VERB"
+alias chgrp="chgrp $VERB"
+alias chmod="chmod $VERB"
+alias chown="chown $VERB"
+alias modprobe="modprobe $Q $VERB"
+}
+_alias_default
 
 _losetup_a(){
 # old losetup-FULL has no -a options,
@@ -161,15 +177,15 @@ _ensure_loop_cont(){
     while read loop; do
     NR=${loop##*/}
     NR=${NR##*loop}
-    echo c=$c NR=$NR
+    _debug c=$c NR=$NR
     while :; do
-    test $NR = $c && break || { mknod /dev/loop$c b 7 $c; [ -d /dev/loop ] && ln -sf ../loop$c /dev/loop/$c; }
+    test "$NR" = $c && break || { mknod /dev/loop$c b 7 $c; [ -d /dev/loop ] && ln -sf ../loop$c /dev/loop/$c; }
     c=$((c+1))
     _debugx c=$c NR=$NR
-    test $c -le $usedLOOPS || break
+    test "$c" -le $usedLOOPS || break
     done
     c=$((c+1))
-    test $c -le $usedLOOPS || break
+    test "$c" -le $usedLOOPS || break
     done << EoI
 `ls -1d /dev/loop[0-9]* | sed 's!.*loop!!;s!/!!' | sort -n`
 EoI
@@ -188,7 +204,7 @@ EoI
     # REM : /dev/loop0 only would count as word '1', so need to reduce by one ..
     NR=$((NR-1))
     _debugx "NR=$NR"
-    if test $usedLOOPS -ge $NR; then
+    if test "$usedLOOPS" -ge $NR; then
     test -b /dev/loop$((NR+0)) || mknod /dev/loop$((NR+0)) b 7 $((NR+0))
     test -b /dev/loop$((NR+1)) || mknod /dev/loop$((NR+1)) b 7 $((NR+1))
     test -b /dev/loop$((NR+2)) || mknod /dev/loop$((NR+2)) b 7 $((NR+2))
@@ -235,7 +251,7 @@ _encrypted()
 
      *_cryptx*) #light encryption.
       CRYPTO='light'
-      modprobe $Q $VERB cryptoloop
+      modprobe cryptoloop
       rxvt -geometry 25x3 -title "$(gettext 'Enter password')" -bg orange -e losetup-FULL -E 1 $freeLOOP
       #losetup-FULL -E 1 $freeLOOP $imgFile
       Err=$?
@@ -254,8 +270,8 @@ _encrypted()
 
       for mod in cryptoloop aes_generic aes crypto_blkcipher blkcipher cbc
       do
-      modprobe $Q $VERB -l | grep $Q "/${mod}.ko$" || continue
-      modprobe $Q $VERB $mod
+      modprobe -l | grep $Q "/${mod}.ko$" || continue
+      modprobe $mod
       done
 
 # <linux/loop.h>
@@ -389,7 +405,7 @@ _debug Err=$Err
 
  _kernel_fs_support(){
      grep -v nodev /proc/filesystems | grep $Q "$*" && return 0
-     ( modinfo "$*" && modprobe $Q $VERB "$*" ) >>$OUT 2>>$ERR
+     ( modinfo "$*" && modprobe "$*" ) >>$OUT 2>>$ERR
  }
  test "$FS_TYPE" && _kernel_fs_support "$FS_TYPE" && T_OP="-t $FS_TYPE"
 
@@ -401,12 +417,12 @@ _debug Err=$Err
 
  if test $Err = 0; then
  _info "About to mount $T_OP "$freeLOOP" "$FILE_MOUNT_POINT""
- /bin/mount $T_OP "$freeLOOP" "$FILE_MOUNT_POINT"
+            /bin/mount $T_OP "$freeLOOP" "$FILE_MOUNT_POINT"
 
  elif test $Err = 9; then
 
  _info "About to mount $T_OP -o loop "$FILE_MOUNT_LOOP" "$FILE_MOUNT_POINT""
- /bin/mount $T_OP -o loop "$FILE_MOUNT_LOOP" "$FILE_MOUNT_POINT"
+            /bin/mount $T_OP -o loop "$FILE_MOUNT_LOOP" "$FILE_MOUNT_POINT"
 
  elif test $Err = 8; then
  _err "No free loop device available"
@@ -424,13 +440,13 @@ return $?
 
 _convert_nl_tab_sp_esc()
 {
-xP=${*// /\\040}
-xQ=${xP//	/\\011}  #TAB
-xR="${xQ//
+xP=${*//\\/\\134} #bsl
+xQ=${xP// /\\040}
+xR=${xQ//	/\\011}  #TAB
+xS="${xR//
 /\\012}"
-xS=${xR//\\/\\134}   #bsl
 echo "$xS"
-unset xR xQ xP xS
+unset xP xQ xR xS
 }
 
 _format_grep_pattern(){
@@ -501,6 +517,27 @@ _ask_to_run_sfs_load
   1) :;; 2) exit 0;; *) _warn "Unhandled return value from _ask_to_run_sfs_load";;
   esac
 
+__exit(){
+_get_yaf_args
+case $2 in mount)
+case $1 in
+0) #$YAF $yafBG $yafFG $yafPL $yafFONT $yafEXTRA $yafTXT "Success. Click again to unmount.";;
+	$YAF_CMD "Success. Click ${FILE_MOUNT_LOOP##*/} again to unmount." & true;;
+*) #$YAF $yafBG $yafFG $yafPL $yafFONT $yafEXTRA $yafTXT "Failure. Error code $1 . Is it an unsupported .sfs version or compression ?";;
+	$YAF_CMD "Failure. Error code $1 . Is it an unsupported .sfs version or compression ?" & false;;
+esac
+;;
+umount)
+case $1 in
+0) #$YAF $yafBG $yafFG $yafPL $yafFONT $yafEXTRA $yafTXT "Successfully unmounted.";;
+	$YAF_CMD "Successfully unmounted $FILE_MOUNT_POINT ." & true;;
+*) #$YAF $yafBG $yafFG $yafPL $yafFONT $yafEXTRA $yafTXT "Failure unmounting. Error code $1 . Are apps like rxvterminal open therein ?";;
+	$YAF_CMD "Failure unmounting. Error code $1 . Are apps like rxvterminal open therein ?" & false;;
+esac
+;;
+esac
+exit $1
+}
 
 if [ "$FILE_MOUNT_POINT" ]; then
  # toggle if already mounted
@@ -508,7 +545,7 @@ if [ "$FILE_MOUNT_POINT" ]; then
  if _check_dir_mounted; then
   rox -D "$FILE_MOUNT_POINT"
   /bin/umount -d "$FILE_MOUNT_POINT"
-  exit $?
+  __exit $? umount
  else
   _mount_it
  fi
@@ -520,7 +557,7 @@ else
  if _check_dir_mounted; then
   rox -D "$FILE_MOUNT_POINT"
   /bin/umount -d "$FILE_MOUNT_POINT"
-  exit $?
+  __exit $? umount
  else
  _mount_it
  fi
@@ -533,22 +570,25 @@ if test "$RV" = 0; then
  :
  #[ -d "$FILE_MOUNT_POINT" ] && rox "$FILE_MOUNT_POINT"
 else # clean up
- [ -d "$FILE_MOUNT_POINT" ] && rmdir $VERB "$FILE_MOUNT_POINT"
+ [ -d "$FILE_MOUNT_POINT" ] && rmdir "$FILE_MOUNT_POINT"
   if test "$freeLOOP"; then
-   _losetup_a | grep $Q -w "^$freeLOOP" && losetup $VERB -d "$freeLOOP"
+   _losetup_a | grep $Q -w "^$freeLOOP" && losetup -d "$freeLOOP"
   fi
   if test "$FILE_MOUNT_LOOP"; then
    LOOP_ASS=`losetup -j "$FILE_MOUNT_LOOP"`
    for l in $LOOP_ASS; do
+   test -b $l || continue
    losetup -d $l
    done
   fi
 fi
+
+__exit $RV mount
 
 #TODO:
 #/initrd/ support in use by puppy
 #DONE:encryption support
 #squashfs version support
 #squashfs compression
-#xmessages for success/failure
+#DONE:xmessages for success/failure
 #DONE:dialog to load or mount
