/usr/sbin/askpass: Batch adding of VERB , Q , ERR , OUT variables. Shorten tests ( omitt !=  ).

diff --git a/woof-code/rootfs-skeleton/usr/sbin/askpass b/woof-code/rootfs-skeleton/usr/sbin/askpass
--- a/woof-code/rootfs-skeleton/usr/sbin/askpass
+++ b/woof-code/rootfs-skeleton/usr/sbin/askpass
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/ash
 #Barry Kauler 2011, GPL3 (/usr/share/doc/legal)
 #specified in /etc/sudoers or /etc/sudo.conf, gui-helper for sudo. (path compiled-in to my sudo PET)
 #110513 display name of app that is requesting to run.
@@ -37,13 +37,13 @@ if [ $DISPLAY ];then
   </vbox>
 </window>
 "
- RETVAL="`gtkdialog3 --program=ASKDIALOG 2>/dev/null`"
+ RETVAL="`gtkdialog3 --program=ASKDIALOG 2>$ERR`"
  eval "$RETVAL"
 else
  echo >/dev/console
- echo -n "$(gettext 'Type admin password required to run this app:') " >/dev/console
+ echo "$(gettext 'Type admin password required to run this app:') " >/dev/console
  read -t 30 ADMINPASSWORD
- [ "$ADMINPASSWORD" = "" ] && echo '...failed' >/dev/console
+ [ "$ADMINPASSWORD" ] || echo '...failed' >/dev/console
 fi
 
 #echo "$RETVAL"
