/usr/sbin/askpass: Add VERB and other variables. Use ash as interpreter. Shorten test ( omitt != "" ).

diff --git a/woof-code/rootfs-skeleton/usr/sbin/askpass b/woof-code/rootfs-skeleton/usr/sbin/askpass
--- a/woof-code/rootfs-skeleton/usr/sbin/askpass
+++ b/woof-code/rootfs-skeleton/usr/sbin/askpass
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/ash
 #Barry Kauler 2011, GPL3 (/usr/share/doc/legal)
 #specified in /etc/sudoers or /etc/sudo.conf, gui-helper for sudo. (path compiled-in to my sudo PET)
 #110513 display name of app that is requesting to run.
@@ -41,9 +41,9 @@ if [ $DISPLAY ];then
  eval "$RETVAL"
 else
  echo >/dev/console
- echo -n "$(gettext 'Type admin password required to run this app:') " >/dev/console
+ echo "$(gettext 'Type admin password required to run this app:') " >/dev/console
  read -t 30 ADMINPASSWORD
- [ "$ADMINPASSWORD" = "" ] && echo '...failed' >/dev/console
+ [ "$ADMINPASSWORD" ] || echo '...failed' >/dev/console
 fi
 
 #echo "$RETVAL"
