woof-code/rootfs-skeleton/usr/sbin/background_reshape: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/background_reshape b/woof-code/rootfs-skeleton/usr/sbin/background_reshape
--- a/woof-code/rootfs-skeleton/usr/sbin/background_reshape
+++ b/woof-code/rootfs-skeleton/usr/sbin/background_reshape
@@ -1,11 +1,35 @@
 #!/bin/sh
 #Barry Kauler 2009
-#the background image is at /usr/share/backgrounds/default.jpg
-#this may have the wrong dimensions to suit either a 'normal' or a 'widescreen' monitor.
-#for now, keep this simple, assume image is suitable for normal screen, truncate vertically
-#if widescreen.
+# The background image is at /usr/share/backgrounds/default.jpg
+# This may have the wrong dimensions to suit either a 'normal' or a 'widescreen' monitor.
+# For now, keep this simple, assume image is suitable for normal screen, truncate vertically
+# if widescreen.
 #v424 fix maths.
 #v424 move ORIGINAL-* images to /usr/share/backgrounds_original
+
+_TITLE_=background_reshape
+_COMMENT_="CLI script to fit .JPEG files to wide screen."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=FILENAME.JPG
+ADD_PARAMETERS="File-name: /path/to/picture.jpg"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 
 LOG=/tmp/backg.log
 echo "$0:$*" >>"$LOG"
