/usr/sbin/bcrypt_gui: Handle special chars in passwords.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/bcrypt_gui b/woof-code/rootfs-skeleton/usr/sbin/bcrypt_gui
--- a/woof-code/rootfs-skeleton/usr/sbin/bcrypt_gui
+++ b/woof-code/rootfs-skeleton/usr/sbin/bcrypt_gui
@@ -6,6 +6,31 @@
 #most of this code was written by coolpup, I have just butchered it a bit.
 #w482 dogone: password must be 8 chars, logic fixed.
 
+
+_TITLE_=askpass
+_COMMENT_="GTKdialog GUI or CLI to enter a password."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
+
 if [ "`which bcrypt`" = "" ];then
  xmessage -center -bg red "The 'bcrypt' package must be installed first."
  exit
@@ -19,7 +44,7 @@ fi
   SOURCEFILE="$1"
   [ ! -f "$SOURCEFILE" ] && exit
  fi
- 
+
  MSG2="<text><label>\"  \"</label></text>"
  while [ 1 ];do
   if [ "$SOURCEFILE" = "" ];then
@@ -31,7 +56,7 @@ fi
 <window title=\"Bcrypt file encryption\" icon-name=\"gtk-file\">
 <vbox>
   <text><label>Welcome, this is a GUI for the 'bcrypt' utility, to encrypt or decrypt a file</label></text>
-   <text use-markup=\"true\"><label>\"<b>For file encryption or decryption, drag the file here ↓    </b>\"</label></text>          
+   <text use-markup=\"true\"><label>\"<b>For file encryption or decryption, drag the file here ↓    </b>\"</label></text>
   <hbox>
   <entry accept=\"directory\">${DEFAULT}<variable>SOURCEFILE</variable></entry>
   </hbox>
@@ -49,7 +74,7 @@ fi
    </entry>
   </hbox>
 
-  <hbox> 
+  <hbox>
   <button help>
    <action>Xdialog --wrap --screencenter --left --title \"Pcrypt - HELP\" --msgbox \"Bcrypt is a cross-platform file encryption utility which means that encrypted files are portable across all supported operating systems and processors, of which Linux and Win32 are two of them.\n\nIt is used for encrypting files, and can be used for secure deletion, which is better than any common file shredder since the deleted file has been encrypted beforehand. It is available from the main menu and from the right-click context menu by default for most of the basic text, image, and audio file types.\n\nPassphrases must be between 8 and 56 characters and are hashed internally to a 448 bit key (the largest keysize supported by the blowfish algorithm) regardless of the passphrase size. However, all characters supplied are significant since the stronger your passphrase, the more secure your data will be. WARNING: If you forget the encryption key (passphrase) your file can never be opened again in your lifetime and probably never will.\n\nBy default, bcrypt will compress input files before encryption, remove input files after they are processed (assuming they are processed successfully), and overwrite the original input files with random data three times before deleting them in order to prevent data recovery by unauthorized persons.\n\nEncrypted files will be saved with an extension of .bfe. Any files ending in .bfe will be assumed to be encrypted with bcrypt, and so bcrypt will attempt to decrypt them. Any other input files will be encrypted.\n\nBcrypt uses the blowfish encryption algorithm published by Bruce Schneier in 1993.\n\nPcrypt was created by coolpup for Puppy Linux, February 2009 GPL v3 Licence.\nBcrypt_gui based on Pcrypt, by Barry Kauler, April 2009.\n\nBcrypt copyright (c) 2002 Johnny Shelley All rights reserved. Licence supplied.\" 600x0</action>
   </button>
@@ -60,7 +85,28 @@ fi
 </window>"
 
   RETVALS="`gtkdialog3 --program=BCRYPT --center`"
-  eval "$RETVALS"
+
+ PWORD1=`echo "$RETVALS" | grep -m1 'PASSWORD1=.*'`
+ PWORD1_=${PWORD//PASSWORD1=\"/}
+ PWORD1_=`echo "$PWORD_" | sed 's/"$//'`
+ _PWORD1_=`echo "$PWORD_" | _string_to_octal`
+
+ PWORD2=`echo "$RETVALS" | grep -m1 'PASSWORD2=.*'`
+ PWORD2_=${PWORD//PASSWORD2=\"/}
+ PWORD2_=`echo "$PWORD_" | sed 's/"$//'`
+ _PWORD2_=`echo "$PWORD_" | _string_to_octal`
+
+   RETVALS_=`echo "$RETVALS" | grep -v 'PASSWORD[1-2]=.*'`
+
+ echo "$_PWORD1_"
+ echo "$_PWORD2_"
+ _RETVAL_="PASSWORD1='$_PWORD1_'
+ PASSWORD2='$_PWORD2_'
+$RETVALS_"
+
+  #eval "$RETVALS"
+  eval "$_RETVAL_"
+
   [ "$EXIT" != "OK" ] && break
   [ "$PASSWORD1" = "" ] && break
   [ "$PASSWORD2" = "" ] && break
@@ -77,7 +123,7 @@ fi
    MSG2="<text use-markup=\"true\"><label>\"<b>${MSG2}</b>\"</label></text>"
    continue
   fi
-  
+
   DIRNAME="`dirname "$SOURCEFILE"`"
   BASENAME="`basename "$SOURCEFILE"`"
   cd "$DIRNAME"
@@ -92,7 +138,7 @@ $PASSWORD2" | bcrypt $BASENAME 2>/tmp/bcrypt_error
    MSG2="<text use-markup=\"true\"><label>\"<b>${MSG2}</b>\"</label></text>"
    continue
   fi
-  
+
   break
  done
 
@@ -129,7 +175,19 @@ while [ $STATUS -ne 0 ];do
 
  RETVALS="`gtkdialog3 --program=MAIN_DIALOG`"
 
- eval "$RETVALS"
+ PWORD=`echo "$RETVALS" | grep -m1 'PASSWORD1=.*'`
+ PWORD_=${PWORD//PASSWORD1=\"/}
+ PWORD_=`echo "$PWORD_" | sed 's/"$//'`
+ _PWORD_=`echo "$PWORD_" | _string_to_octal`
+
+   EXIT_=`echo "$RETVALS" | grep -m1 'EXIT=.*'`
+
+ echo "$_PWORD_"
+ _RETVAL_="PASSWORD1='$_PWORD_'
+$EXIT_"
+
+ #eval "$RETVALS"
+ eval "$_RETVAL_"
 
  [ "$EXIT" != "OK" ] && break
  [ "$PASSWORD1" = "" ] && break
