woof-code/rootfs-skeleton/usr/sbin/browser-default: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/browser-default b/woof-code/rootfs-skeleton/usr/sbin/browser-default
--- a/woof-code/rootfs-skeleton/usr/sbin/browser-default
+++ b/woof-code/rootfs-skeleton/usr/sbin/browser-default
@@ -1,5 +1,28 @@
 #!/bin/sh -a
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 #kill `ps|grep "defbrowser"|awk '{print $1}'`
 
 SCREEN=`xwininfo -root | grep ' \-geometry ' | tr -s ' ' | cut -f 3 -d ' ' | cut -f 1 -d '+' | tr 'x' ' '`
@@ -7,18 +30,18 @@ HEIGHT=`echo -n "$SCREEN" | cut -f 2 -d ' '`
 YDIMENSION=`echo $(($HEIGHT - 163))`
 
 function CHGDEF(){
-	DEFOLD=`grep -v "#" /usr/local/bin/defaultbrowser`
-	DEFNEW="exec $BRS \"\$@\""
-	OLD=`echo $CUR|cut -d ' ' -f2`
-	if [[ "$BRS" != "$OLD" ]];then
-	echo "sed -i 's/$DEFOLD/$DEFNEW/' /usr/local/bin/defaultbrowser" >/tmp/change-browser
-	. /tmp/change-browser
-	#echo $OLD
-	   if [ `which yaf-splash2` != "" ];then
+        DEFOLD=`grep -v "#" /usr/local/bin/defaultbrowser`
+        DEFNEW="exec $BRS \"\$@\""
+        OLD=`echo $CUR|cut -d ' ' -f2`
+        if [[ "$BRS" != "$OLD" ]];then
+        echo "sed -i 's/$DEFOLD/$DEFNEW/' /usr/local/bin/defaultbrowser" >/tmp/change-browser
+        . /tmp/change-browser
+        #echo $OLD
+           if [ `which yaf-splash2` != "" ];then
        yaf-splash2 -font "-misc-dejavu sans-bold-r-normal--16-0-0-0-p-0-iso10646-1" -margin 4 -bg yellow -timeout 3 -outline 0 -text "$BRS is now the default browser" &
-	      else gtkdialog-splash -icon gtk-info -bg yellow -timeout 3 -outline 0 -text "$BRS is now the default browser" &
-	   fi
-	fi
+              else gtkdialog-splash -icon gtk-info -bg yellow -timeout 3 -outline 0 -text "$BRS is now the default browser" &
+           fi
+        fi
 }
 
 function browsenow(){
@@ -45,7 +68,7 @@ echo '#browsers' >/tmp/installed-browsers
 INSTALLED_BROWSERS=`cat /tmp/browserlist`
 for i in $INSTALLED_BROWSERS;do
 #grep 'Exec=' /usr/share/applications/$i|cut -d '=' -f2|sed 's/ \%U$//g'|sed s'/\// /'g | tr " " '\n' | tail -n1>/tmp/tmpbrs/$i
-	#cat /tmp/tmpbrs/$i>>/tmp/browserexecs
+        #cat /tmp/tmpbrs/$i>>/tmp/browserexecs
 grep -m1 '^Exec=' /usr/share/applications/$i|cut -d '=' -f2
 #grep -m1 '^Exec=' /usr/share/applications/$i|cut -d '=' -f2|awk '{print $1}' >/tmp/tmpbrs/$i
 basename `grep -m1 '^Exec=' /usr/share/applications/$i|cut -d '=' -f2|awk '{print $1}'`
@@ -60,7 +83,7 @@ done
 
 CUR=`grep -v "#" /usr/local/bin/defaultbrowser|awk '{print $2}'`
 if [ "$CUR" = "quickpet" ];then CUR="Change to a Browser!"
-	else CUR="Now $CUR"
+        else CUR="Now $CUR"
 fi
 
 defbrowser="
