woof-code/rootfs-skeleton/usr/sbin/burniso2cd: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/burniso2cd b/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
--- a/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
+++ b/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
@@ -1,12 +1,36 @@
 #!/bin/sh
 #(c) Copyright 2006, 2007 Barry Kauler.
 #Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html). 2007 www.puppylinux.com
-#simple script to burn an iso file to cd, using cdrecord.
+# Simple script to burn an iso file to cd, using cdrecord.
 #7Sept2007: cdecord -scanbus bugfix, plus overall improvements.
 #v3.02 2Nov2007 BK: bugfix. v3.94 24dec2007: no /dev/hd*
 #w482 change -pad to padsize=300k, recommended by xorriso developer.
 #w482 migrate to using xorriso.
 #v431 rerwin: Add wait for drive lights to stop flashing before verifying and log the verify dd messages.
+
+_TITLE_=burniso2cd
+_COMMENT_="Xdialog GUIs to burn .iso files to CD/DVD."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 
 CDRECORD='cdrecord'
 if [ "`which xorriso`" != "" ];then
@@ -103,14 +127,14 @@ Then click 'OK' button..." 0 0 4 32 $BURNSPEED "Set burn speed"`"
 
  sync
  if [ "$MEDIATYPE" = "CD" ];then
- 
+
   #if [ ! "`echo "$CDR" | grep '/dev/hd'`" = "" ];then
   # DEVDEV="ATAPI:$CDR"
   #else
   # DEVDEV="$CDR"
   #fi
   DEVDEV="$CDR" #w482
-  
+
   echo "Now executing:"
   echo " $CDRECORD $BURNMULTI -data -eject -v speed=$BURNSPEED dev=$DEVDEV $ISOFILE"
   rxvt -name burniso2cd -bg orange -geometry 80x10 -e $CDRECORD $BURNMULTI -data -eject -v speed=$BURNSPEED dev=$DEVDEV "$ISOFILE"
@@ -126,9 +150,9 @@ Then click 'OK' button..." 0 0 4 32 $BURNSPEED "Set burn speed"`"
  # ******Verify burn******
  DEVNAME="`echo -n "$CDR" | grep '/dev' | cut -f 3 -d '/'`"
  if [ ! "$DEVNAME" = "" -a "$RECHECK" = "yes" ];then
-  Xdialog --wmclass "mini-cd" --title "Burniso2cd: Finished" --stdout --yesno "Would you like to verify that the burn was successful? 
+  Xdialog --wmclass "mini-cd" --title "Burniso2cd: Finished" --stdout --yesno "Would you like to verify that the burn was successful?
 This may take a while depending on the size of the iso file." 0 0
-  if  [ "$?" = "0" ] ;then  
+  if  [ "$?" = "0" ] ;then
    xmessage -bg "#80ff80" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "Make sure the CD/DVD drive is closed,
 then click OK"
    echo "Waiting 15 seconds to allow drive lights to finish blinking" > /tmp/burniso2cd.log #v431
