woof-code/rootfs-skeleton/usr/sbin/burniso2cdTEST: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/burniso2cdTEST b/woof-code/rootfs-skeleton/usr/sbin/burniso2cdTEST
--- a/woof-code/rootfs-skeleton/usr/sbin/burniso2cdTEST
+++ b/woof-code/rootfs-skeleton/usr/sbin/burniso2cdTEST
@@ -5,6 +5,28 @@
 #7Sept2007: cdecord -scanbus bugfix, plus overall improvements.
 #v3.02 2Nov2007 BK: bugfix. v3.94 24dec2007: no /dev/hd*
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 MEDIATYPE="`Xdialog --wmclass "mini-cd" --title "Burniso2cd" --stdout --menubox "Welcome to our little CD/DVD burner program!\nPlease choose whether you want to burn to a CD or DVD media.\nNote that DVDs are always burnt 'open' so can be used by Puppy\nas normal or multisession, whereas for CD you will be given\nthe choice further on whether to burn as closed or open." 0 0 5 CD "CD-R or CD-RW (must be blank)" DVD "DVD-R or DVD-RW (must be blank)"`"
 [ ! $? -eq 0 ] && exit
@@ -125,12 +147,12 @@ Then click 'OK' button..." 0 0 4 32 $BURNSPEED "Set burn speed"`"
  # ******Verify burn******
  DEVNAME="`echo -n "$CDR" | grep '/dev' | cut -f 3 -d '/'`"
  if [ ! "$DEVNAME" = "" -a "$RECHECK" = "yes" ];then
-  Xdialog --wmclass "mini-cd" --title "Burniso2cd: Finished" --stdout --yesno "Would you like to verify that the burn was successful? 
+  Xdialog --wmclass "mini-cd" --title "Burniso2cd: Finished" --stdout --yesno "Would you like to verify that the burn was successful?
 This may take a while depending on the size of the iso file." 0 0
-  if  [ "$?" = "0" ] ;then  
+  if  [ "$?" = "0" ] ;then
    xmessage -bg "#80ff80" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "Make sure the CD/DVD drive is closed,
 then click OK"
-   if [ "$( md5sum $ISOFILE | cut -f 1 -d " " )" = "$(dd if=$CDR | head -c `stat --format=%s $ISOFILE` | md5sum | cut -f 1 -d " " )" ] ;then 
+   if [ "$( md5sum $ISOFILE | cut -f 1 -d " " )" = "$(dd if=$CDR | head -c `stat --format=%s $ISOFILE` | md5sum | cut -f 1 -d " " )" ] ;then
     xmessage -bg "#80ff80" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "The burn has been verified as good!"
    else
     xmessage -bg "#ffc0c0" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "The burn was not verified. You should start over"
