/usr/sbin/burniso2cd : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/burniso2cd b/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
--- a/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
+++ b/woof-code/rootfs-skeleton/usr/sbin/burniso2cd
@@ -1,62 +1,82 @@
 #!/bin/sh
 #(c) Copyright 2006, 2007 Barry Kauler.
-#Lesser GPL licence v2 (/usr/share/doc/legal). 2007 www.puppylinux.com
+#Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html). 2007 www.puppylinux.com
 #simple script to burn an iso file to cd, using cdrecord.
 #7Sept2007: cdecord -scanbus bugfix, plus overall improvements.
 #v3.02 2Nov2007 BK: bugfix. v3.94 24dec2007: no /dev/hd*
 #w482 change -pad to padsize=300k, recommended by xorriso developer.
 #w482 migrate to using xorriso.
-#v431 rerwin: Add wait for drive lights to stop flashing before verifying and log the verify dd messages.
-#110205 previous probedisk script removed.
-#120201 rodin.s: internationalized.
-#120323 replace 'xmessage' with 'pupmessage'.
-#120329 Xdialog bug --yesno supposed to "yes" "No" buttons, but they are "OK" "Cancel".
-#130203 change probedisk2 to probedisk.
 
-export TEXTDOMAIN=burniso2cd
-export TEXTDOMAINDIR=/usr/share/locale
-export OUTPUT_CHARSET=UTF-8
-eval_gettext () {
-  local myMESSAGE=$(gettext "$1")
-  eval echo \"$myMESSAGE\"
+
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+trap "exit 1" HUP INT QUIT KILL TERM
+
+OUT=/dev/null;ERR=$OUT
+[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
+[ "$DEBUG" = "2" ] && set -x
+
+Version='1.1'
+
+usage(){
+USAGE_MSG="
+$0 [ PARAMETERS ]
+
+-V|--version : showing version information
+-H|--help : show this usage information
+
+*******  *******  *******  *******  *******  *******  *******  *******  *******
+$2
+"
+echo "$USAGE_MSG"
+exit $1
 }
-export LANGORG=$LANG
 
-Yes_lbl="$(gettext 'Yes')"
-No_lbl="$(gettext 'No')"
+[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
+[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
 
-CDRECORD='cdrecord'
-if [ "`which xorriso`" != "" ];then
+###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+
+CDRECORD=`which cdrecord`
+if [ "`which xorriso`" ];then
  CDRECORD='xorrecord'
  export MKISOFS='xorrisofs' #growisofs reads this variable.
 fi
 
-MEDIATYPE="`Xdialog --wmclass "mini-cd" --title "Burniso2cd" --stdout --menubox "$(gettext "Welcome to our little CD/DVD burner program!\nPlease choose whether you want to burn to a CD or DVD media.\nNote that DVDs are always burnt 'open' so can be used by Puppy\nas normal or multisession, whereas for CD you will be given\nthe choice further on whether to burn as closed or open.")" 0 0 5 CD "$(gettext 'CD-R or CD-RW (must be blank)')" DVD "$(gettext 'DVD-R or DVD-RW (must be blank)')"`"
-[ ! $? -eq 0 ] && exit
+[ "$CDRECORD" ] || exit 1
 
-SELECTIONS="`probedisk | grep '|optical|' | grep '/dev/' | cut -f 1,3 -d '|' | tr " " '_' | tr -s '_'`" #110205
-SELECTIONX="`echo "$SELECTIONS" | tr '|' " " | tr "\n" " "`"
+SELECTIONS=`probedisk | grep '|cdrom|' | grep '/dev/' | cut -f 1,3 -d '|' | tr " " '_' | tr -s '_'`
+echo "SELECTIONS='$SELECTIONS'"
+SELECTIONX=`echo "$SELECTIONS" | tr '|' " " | tr "\n" " "`
+echo "SELECTIONX='$SELECTIONX'"
 
-if [ "$SELECTIONX" = "" ];then
- pupmessage -bg '#FF8080' "$(gettext 'Sorry, no CD/DVD drive detected')"
- exit
+if [ ! "$SELECTIONX" ];then
+ xmessage "Sorry, no CD/DVD drive detected"
+ exit 0
 fi
 
-BURNERDRIVE="`Xdialog --wmclass "mini-cd" --title "$(gettext 'Burniso2cd: Choose burner drive')" --stdout --menubox "$(gettext 'Choose the CD/DVD drive to burn to')" 400x200 5 $SELECTIONX 2> /dev/null`"
-[ ! $? -eq 0 ] && exit
+MEDIATYPE=`Xdialog --wmclass "mini-cd" --title "Burniso2cd" --stdout --menubox "Welcome to our little CD/DVD burner program!\nPlease choose whether you want to burn to a CD or DVD media.\nNote that DVDs are always burnt 'open' so can be used by Puppy\nas normal or multisession, whereas for CD you will be given\nthe choice further on whether to burn as closed or open." 0 0 5 CD "CD-R or CD-RW (must be blank)" DVD "DVD-R or DVD-RW (must be blank)"`
+[ $? = 0 ] || exit 0
 
-[ ! -f /etc/cdburnerdevice ] && echo -n "$BURNERDRIVE" | sed -e 's/\/dev\///g' > /etc/cdburnerdevice
+echo "MEDIATYPE='$MEDIATYPE'"
 
-ISOFILE="`Xdialog --wmclass "mini-cd" --backtitle "$(gettext 'Please choose the iso file...')" --title "$(gettext 'Burniso2cd: Choose iso file')" --stdout --no-buttons --fselect "*.iso" 0 0`"
-if [ ! $? -eq 0 ];then
- exit
+BURNERDRIVE=`Xdialog --wmclass "mini-cd" --title "Burniso2cd: Choose burner drive" --stdout --menubox "Choose the CD/DVD drive to burn to" 400x200 5 $SELECTIONX 2> /dev/null`
+[ $? = 0 ] || exit 0
+echo "BURNERDRIVE='$BURNERDRIVE'"
+[ -f /etc/cdburnerdevice ] || echo -n "$BURNERDRIVE" | sed -e 's/\/dev\///g' > /etc/cdburnerdevice
+
+ISOFILE=`Xdialog --wmclass "mini-cd" --backtitle "Please choose the iso file..." --title "Burniso2cd: Choose iso file" --stdout --no-buttons --fselect "*.iso" 0 0`
+if [ $? != 0 ];then
+ exit 0
 fi
 
+echo "ISOFILE='$ISOFILE'"
 CDR="$BURNERDRIVE"
-CDDESCR="`echo "$SELECTIONS" | grep "$CDR" | cut -f 2 -d '|'`"
+CDDESCR=`echo "$SELECTIONS" | grep "$CDR" | cut -f 2 -d '|'`
+echo "CDDESCR='$CDDESCR'"
 
-while [ ! "`mount | grep "$CDR"`" = "" ];do
- pupmessage -bg "#ff8080" -center -name "burniso2cd" -title "Burniso2cd: ERROR" "The $CDR CD/DVD drive, described as:
+while [ "`mount | grep "$CDR"`" ];do
+ xmessage -bg "#ff8080" -center -name "burniso2cd" -title "Burniso2cd: ERROR" "The $CDR CD/DVD drive, described as:
  $CDDESCR
 is currently mounted.
 Use MUT or Pmount to unmount it.
@@ -64,23 +84,24 @@ Use MUT or Pmount to unmount it.
 Please unmount CD drive, then click OK button..."
 done
 
-if [ "$MEDIATYPE" = "CD" ];then
- Xdialog --wmclass "mini-cd" --title "Burniso2cd" --stdout --ok-label "$(gettext 'NORMAL')" --cancel-label "$(gettext 'MULTI')"  --yesno "$(gettext 'You have selected iso file:')
+if [ "$MEDIATYPE" = 'CD' ];then
+
+ Xdialog --wmclass "mini-cd" --title "Burniso2cd" --stdout --ok-label "NORMAL" --cancel-label "MULTI"  --yesno "You have selected iso file:
  $ISOFILE
 
-$(gettext 'Do you want to burn a multi-session CD?
-A multi-session CD is one that is left "open" so that further
+Do you want to burn a multi-session CD?
+A multi-session CD is one that is left \"open\" so that further
 tracks may be burnt later. The iso file that you have selected
 will be burnt now as the first track.
 Note, this is an experimental option for the Puppy live-CD, to
 allow burning of sessions back to CD, thus personal data is saved
-to CD and a hard drive or usb stick is not required.')
+to CD and a hard drive or usb stick is not required.
 
-$(gettext "Please choose 'NORMAL' unless you have some special reason to burn
+Please choose 'NORMAL' unless you have some special reason to burn
 the CD multi-session (such as the iso is specifically for multisession).
 
 Click 'NORMAL' button for normal burn...
-Click 'MULTI' button for multi-session...")" 0 0
+Click 'MULTI' button for multi-session..." 0 0
 
  RETVAL=$?
 else
@@ -99,10 +120,10 @@ case $RETVAL in
   ;;
  12) #multi dvd
   BURNMULTI="yes"
-  BURNMSG="$(gettext '(blank DVD-R. A DVD+/-RW will be fast-wiped if it has data)')"
+  BURNMSG="(blank DVD-R. A DVD+/-RW will be fast-wiped if it has data)"
   ;;
  *)
-  exit
+  exit $RETVAL
   ;;
 esac
 
@@ -110,66 +131,73 @@ RECHECK="yes"
 BURNSPEED="10"
 
 while [ 1 ];do #burn-again-loop
-  BURNSPEED="`Xdialog --wmclass "mini-cd" --title "$(gettext 'Burniso2cd: Burn') $MEDIATYPE" --stdout --spinbox "$(eval_gettext "Please insert blank \\\$MEDIATYPE into \\\$CDR")
+
+ IFS=':' read LABEL CAN_SET_SPEED <<EOI
+$(cd-info $CDR | grep -i 'Can set drive speed')
+EOI
+
+ if [ "$CAN_SET_SPEED" = 'Yes' ] ; then
+ BURNSPEED=`Xdialog --wmclass "mini-cd" --title "Burniso2cd: Burn $MEDIATYPE" --stdout --spinbox "Please insert blank $MEDIATYPE into $CDR
 $BURNMSG
-$(gettext '(which is described as:') ${CDDESCR})
+(which is described as: ${CDDESCR})
 
-$(gettext 'Then click 'OK' button...')" 0 0 4 32 $BURNSPEED "$(gettext 'Set burn speed')"`"
+Then click 'OK' button..." 0 0 4 32 $BURNSPEED "Set burn speed"`
 
- [ ! $? -eq 0 ] && exit
-
- sync
- if [ "$MEDIATYPE" = "CD" ];then
- 
-  #if [ ! "`echo "$CDR" | grep '/dev/hd'`" = "" ];then
-  # DEVDEV="ATAPI:$CDR"
-  #else
-  # DEVDEV="$CDR"
-  #fi
-  DEVDEV="$CDR" #w482
-  
-  echo "$(gettext 'Now executing:')"
-  echo " $CDRECORD $BURNMULTI -data -eject -v speed=$BURNSPEED dev=$DEVDEV $ISOFILE"
-  rxvt -name burniso2cd -bg orange -geometry 80x10 -e $CDRECORD $BURNMULTI -data -eject -v speed=$BURNSPEED dev=$DEVDEV "$ISOFILE"
- else #dvd
-  echo "$(gettext 'Now executing:')"
-  echo " growisofs -speed=$BURNSPEED -Z $CDR=$ISOFILE"
-  rxvt -name burniso2cd -bg orange -geometry 80x10 -e growisofs -speed=$BURNSPEED -Z $CDR="$ISOFILE"
+ [ $? = 0 ] || exit 0
  fi
  sync
- echo "$(gettext '...done')"
+
+ echo "BURNSPEED='$BURNSPEED'"
+
+ echo '#!/bin/sh' >/tmp/burniso2cd
+ if [ "$MEDIATYPE" = "CD" ];then
+  DEVDEV="$CDR" #w482
+  echo "
+$CDRECORD $BURNMULTI -data -v speed=$BURNSPEED dev=$DEVDEV \"$ISOFILE\"" >>/tmp/burniso2cd
+ else #dvd
+ echo "
+growisofs -speed=$BURNSPEED -Z $CDR=\"$ISOFILE\"" >>/tmp/burniso2cd
+ fi
+ echo 'RETVAL=$?
+read -n1 -p "Press Enter " EK
+echo "$RETVAL" >/tmp/burniso2cd.ok
+exit $RETVAL
+' >>/tmp/burniso2cd
+
+ chmod +x /tmp/burniso2cd
+ rxvt -name burniso2cd -bg orange -geometry 80x10 -e /tmp/burniso2cd
+ read BURNOK </tmp/burniso2cd.ok
+ sync
+ [ "$BURNOK" = 0 ] && echo "...done." || echo "...failure..."
 
  #v2.10 kirk contributed this...
  # ******Verify burn******
- DEVNAME="`echo -n "$CDR" | grep '/dev' | cut -f 3 -d '/'`"
- if [ ! "$DEVNAME" = "" -a "$RECHECK" = "yes" ];then
-  Xdialog --wmclass "mini-cd" --title "$(gettext 'Burniso2cd: Finished')" --stdout --ok-label "$Yes_lbl" --cancel-label "$No_lbl" --yesno "$(gettext 'Would you like to verify that the burn was successful? 
-This may take a while depending on the size of the iso file.')" 0 0
-  if  [ "$?" = "0" ] ;then  
-   pupmessage -bg "#80ff80" -center -name "burniso2cd" -title "$(gettext 'Burniso2cd: Burn Verify')" "$(gettext 'Make sure the CD/DVD drive is closed,
-then click OK')"
-   echo "Waiting 15 seconds to allow drive lights to finish blinking" > /tmp/burniso2cd.log #v431
-   sleep 15 #v431
-   if [ "$( md5sum $ISOFILE | cut -f 1 -d " " )" = "$(dd if=$CDR 2>> /tmp/burniso2cd.log | head -c `stat --format=%s $ISOFILE` | md5sum | cut -f 1 -d " " )" ] ;then #v431
-    pupmessage -bg "#80ff80" -center -name "burniso2cd" -title "$(gettext 'Burniso2cd: Burn Verify')" "$(gettext 'The burn has been verified as good!')"
+ DEVNAME=`echo -n "$CDR" | grep '/dev' | cut -f 3 -d '/'`
+ if [ "$DEVNAME" -a "$RECHECK" = "yes" ];then
+  Xdialog --wmclass "mini-cd" --title "Burniso2cd: Finished" --stdout --yesno "Would you like to verify that the burn was successful?
+This may take a while depending on the size of the iso file." 0 0
+  if  [ "$?" = "0" ] ;then
+   xmessage -bg "#80ff80" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "Make sure the CD/DVD drive is closed,
+then click OK"
+   if [ "$( md5sum $ISOFILE | cut -f 1 -d " " )" = "$(dd if=$CDR | head -c `stat --format=%s $ISOFILE` | md5sum | cut -f 1 -d " " )" ] ;then
+    xmessage -bg "#80ff80" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "The burn has been verified as good!"
    else
-    pupmessage -bg "#ffc0c0" -center -name "burniso2cd" -title "$(gettext 'Burniso2cd: Burn Verify')" "$(gettext 'The burn was not verified. See details in /tmp/burniso2cd.log. You should start over.')"
+    xmessage -bg "#ffc0c0" -center -name "burniso2cd" -title "Burniso2cd: Burn Verify" -buttons "OKAY:10" "The burn was not verified. You should start over"
    fi
   else
    RECHECK="no" #do not check if doing repeat burns.
   fi
  fi
 
- eject $CDR
- Xdialog --wmclass "mini-cd" --title "$(gettext 'Burniso2cd: Finished')" --stdout --ok-label "$(gettext 'FINISHED')" --cancel-label "$(gettext 'REPEAT')" --yesno "$(gettext 'If all went well, you have now burnt iso file')
+ Xdialog --wmclass "mini-cd" --title "Burniso2cd: Finished" --stdout --ok-label "FINISHED" --cancel-label "REPEAT" --yesno "If all went well, you have now burnt iso file
 $ISOFILE
-$(gettext 'to a') $MEDIATYPE!
+to a $MEDIATYPE!
 
-$(gettext 'If you want to burn the iso file to another') $MEDIATYPE,
-$(gettext "click 'REPEAT' button...")
+If you want to burn the iso file to another $MEDIATYPE,
+click 'REPEAT' button...
 
-$(gettext "Otherwise, click 'FINISHED' to quit...")" 0 0
+Otherwise, click 'FINISHED' to quit..." 0 0
  [ $? -ne 1 ] && break
 done #burn-again-loop
-
+eject $CDR
 ###END###
