woof-code/rootfs-skeleton/usr/sbin/cdburner-wizard: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/cdburner-wizard b/woof-code/rootfs-skeleton/usr/sbin/cdburner-wizard
--- a/woof-code/rootfs-skeleton/usr/sbin/cdburner-wizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/cdburner-wizard
@@ -6,6 +6,30 @@
 #updated for 2.17
 #v431 man, this script is ancient! have done some fixing.
 
+_TITLE_=cdburnerwizard
+_COMMENT_="Xdialog to setup /dev/cdrom and /dev/dvd."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
+
 DRIVESFND="`probedisk2`"
 OPTICALDRVSFND="`echo "$DRIVESFND" | grep '|optical|'`"
 
@@ -65,7 +89,7 @@ if [ $XREPLY -eq 11 ];then #choose cdrom
    echo -n $CDROMLINK | cut -f 3 -d '/' > /etc/cdromdevice
    rm -f /dev/cdrom
    ln -s $CDROMLINK /dev/cdrom
- fi 
+ fi
 fi
 
 if [ $XREPLY -eq 20 ];then #choose dvd
@@ -82,7 +106,7 @@ if [ $XREPLY -eq 20 ];then #choose dvd
    echo -n $DVDLINK | cut -f 3 -d '/' > /etc/dvddevice
    rm -f /dev/dvd
    ln -s $DVDLINK /dev/dvd
- fi 
+ fi
 fi
 
 
