woof-code/rootfs-skeleton/usr/sbin/chooselocale: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/chooselocale b/woof-code/rootfs-skeleton/usr/sbin/chooselocale
--- a/woof-code/rootfs-skeleton/usr/sbin/chooselocale
+++ b/woof-code/rootfs-skeleton/usr/sbin/chooselocale
@@ -3,11 +3,35 @@
 #2009 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #w001 initial creation.
 #w004 checkbox for utf8. w019 fixup.
-#w470 $1=composeonly option, when call from 3builddistro. 
+#w470 $1=composeonly option, when call from 3builddistro.
 #w473 disable en_US.utf8 generation, hangs PC if low RAM (64MB system).
 #w478 bugfix, dialog_table was incorrect.
 #v431 updated LANGUAGEDESCR variable.
 #w0910 /usr/share/i18n/charmaps may not be gzipped (ubuntu karmic).
+
+_TITLE_=chooselocale
+_COMMENT_="Xdialog GUIs to manage LANG variable."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 
 startLang="$LANG"
 LANG=C #Xdialog seems to need this.
@@ -146,7 +170,7 @@ echo 'if 1'
     #no match, i think forced to use utf8...
     localedef -f UTF-8 -i $LANGCHOICE --no-archive ${LANGCHOICE}.utf8 #> /dev/null
     NEWLANG="LANG=${LANGCHOICE}.utf8"
-	UTF8='.utf8'
+        UTF8='.utf8'
    fi
   else
   echo 'else 3'
@@ -165,15 +189,15 @@ echo 'if 1'
  fi
 
  [ "$XSTATUS" != "x" ] && exit
- 
+
  Xdialog --left --wrap --title "Country setup" --ok-label "Restart X now" --cancel-label "Finished"  --yesno "Ok, the change has been made and will take effect at next boot. However, if you click the 'Restart X now' button X will exit then restart and the new locale will immediately take effect -- however make sure that all other applications are closed first as restarting X will rudely kill them! Otherwise, just click 'Finished' for the new locale to take effect at next boot.\n\nTechnical details:\nLocale files have been generated in /usr/lib/locale (if not already) and LANG variable set to ${LANGCHOICE}${UTF8} in '$mainFile'." 0 100
- 
+
  if [ $? -eq 0 ];then
   rm -rf /tmp/.X0-lock
   sync
   exec restartwm $CURRENTWM
  fi
- 
+
 fi
 
 ###END###
