woof-code/rootfs-skeleton/usr/sbin/connectwizard_2nd: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/connectwizard_2nd b/woof-code/rootfs-skeleton/usr/sbin/connectwizard_2nd
--- a/woof-code/rootfs-skeleton/usr/sbin/connectwizard_2nd
+++ b/woof-code/rootfs-skeleton/usr/sbin/connectwizard_2nd
@@ -1,10 +1,34 @@
 #!/bin/sh
 #(c) Copyright 2010 Barry Kauler bkhome.org
 #Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
-#called from 'connectwizard'
-#choose between old Network Wizard, new Network Wizard and Pwireless2.
+# Called from 'connectwizard'
+# Choose between old Network Wizard, new Network Wizard and Pwireless2.
 #100227 BK initial creation of script.
 #100306 added Barry's Simple Network Setup.
+
+_TITLE_=connectwizard2
+_COMMENT_="GTKdialog GUI to select various network setup suites."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 
 #100306
 SNS=""
@@ -84,7 +108,7 @@ export MAIN_DIALOG="
 </window>
 "
 
-RETSTRING="`gtkdialog3 --program=MAIN_DIALOG --center`" 
+RETSTRING="`gtkdialog3 --program=MAIN_DIALOG --center`"
 #[ "`echo "$RETSTRING" | grep 'EXIT' | grep 'OK'`" = "" ] && return
 #gtkdialog3 --program=MAIN_DIALOG --center
 
@@ -114,7 +138,7 @@ if [ "`echo "$RETSTRING" | grep '^EXIT' | grep 'FLAG'`" != "" ];then
    NWCHOICE="Barry's Simple Network Setup"
   ;;
  esac
- 
+
  IFSUP="`ifconfig | grep -E '^eth|^wlan'`"
  if [ "$IFSUP" != "" ];then
   IFSUP="`echo "$IFSUP" | cut -f 1 -d ' ' | tr '\n' ' '`"
@@ -125,7 +149,7 @@ $IFSUP
  else
   MSG1="No interfaces are active, so was the tool unsatisfactory? If it actually was OK, click the 'YES SET AS DEFAULT' button. But, it seems not, so..."
  fi
- 
+
   CURREXEC="`cat /usr/local/bin/defaultconnect | tail -n 1 | tr -s " " | cut -f 2 -d " "`"
   [ "`grep 'gprs' /usr/local/bin/defaultconnect`" != "" ] && CURREXEC='pgprs-connect'
   [ "$CURREXEC" = "gkdial" ] && CURREXEC="pupdial" #for older pups.
@@ -167,7 +191,7 @@ $IFSUP
 </window>
 "
 
-  RETSTRING="`gtkdialog3 --program=POST_DIALOG --center`" 
+  RETSTRING="`gtkdialog3 --program=POST_DIALOG --center`"
   if [ "`echo "$RETSTRING" | grep '^EXIT' | grep 'FLAG'`" != "" ];then
    CHOSENACTION="`echo "$RETSTRING" | grep '^EXIT' | grep 'FLAG' | cut -f 2 -d '"'`" #'geany
    case $CHOSENACTION in
@@ -191,7 +215,7 @@ $IFSUP
     ;;
    esac
   fi
- 
+
 fi
 
 ###END###
