woof-code/rootfs-skeleton/usr/sbin/download_file: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/download_file b/woof-code/rootfs-skeleton/usr/sbin/download_file
--- a/woof-code/rootfs-skeleton/usr/sbin/download_file
+++ b/woof-code/rootfs-skeleton/usr/sbin/download_file
@@ -1,9 +1,9 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler 2010. License GPL v3 /usr/share/doc/legal.
 #BK a simple frontend for wget.
-#called from /usr/local/petget/petget, downloadpkgs.sh.
-#URL passed in, only downloads to current directory.
-#only put up user-response dlg windows if failure.
+# Called from /usr/local/petget/petget, downloadpkgs.sh.
+# URL passed in, only downloads to current directory.
+# Only put up user-response dlg windows if failure.
 #101116 first version.
 #101117 url sanity check. more download size check.
 #101118 for ftp connection have to get size differently.
@@ -19,6 +19,7 @@
 # adding gettext
 export TEXTDOMAINDIR=/usr/share/locale
 export TEXTDOMAIN=download_file
+
 eval_gettext () {
   local myMESSAGE=$(gettext "$1")
   eval echo \"$myMESSAGE\"
@@ -27,6 +28,31 @@ LANG="`cat /etc/profile|grep '^LANG='`"
 eval $LANG
 export LANG_USER=$LANG
 #-----------------------------#
+
+
+_TITLE_=download_file
+_COMMENT_="Xdialog GUIs for wget."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=URLSPEC
+ADD_PARAMETERS="URL: fullpath ie. 'http://www.server.org/folder/file.pet'"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 
 #exit number: 0 ok, 1 unable to download, 2 download fail, 3 invalid url.
 
@@ -223,14 +249,14 @@ Do you want to try again, or give up?')" 0 0
   exit 2
  fi
  kill $PID1
- 
+
  #paranoid, check size of downloaded file...
  SIZEB_LOCAL=`stat --format=%s "${FILENAME}"`
  if [ $SIZEB_LOCAL -ne $SIZEB_ONLINE ];then
   INSERT1=''
   continue
  fi
- 
+
  break
 done
 
