woof-code/rootfs-skeleton/usr/sbin/edit-initramfs: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs b/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
--- a/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
+++ b/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
@@ -1,9 +1,32 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler 2012, bkhome.org
 #License GPL3 (/usr/share/doc/legal)
-#shared-mime-info pkg has assigned initrd.gz mime-type application/initramfs-gz (by me).
-#Click on initrd.gz in ROX-Filer, this script will run (see /root/Choices/MIME-types/application_initramfs-gz).
-#note: script not internationalized, as this is a developer's tool.
+# shared-mime-info pkg has assigned initrd.gz mime-type application/initramfs-gz (by me).
+# Click on initrd.gz in ROX-Filer, this script will run (see /root/Choices/MIME-types/application_initramfs-gz).
+# Note: script not internationalized, as this is a developer's tool.
+
+_TITLE_=edit-initramfs
+_COMMENT_="Repack initrd.gz ."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=FILENAME
+ADD_PARAMETERS="File-name: /path/to/initrd.gz"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 [ ! $1 ] && exit 1
 [ ! -f "$1" ] && exit 1
@@ -34,10 +57,10 @@ cd /root
 [ "$1" = "/root/initrd.gz" ] && cp -f /root/initrd.gz /tmp/
 
 if [ -d initrd-expanded ];then
- 
+
  pupdialog --background "yellow" --backtitle "initrd.gz: update?" --yesno "An initrd.gz is already expanded at /root/initrd-expanded. Is this correct, do you want to use /root/initrd-expanded to update ${1}?" 0 0
  if [ $? -eq 0 ];then
-  
+
   compr_func "$1"
   if [ $? -ne 0 ];then
    pupdialog --background '#FF8080' --backtitle "initrd.gz: fail" --msgbox "Sorry, could not recognise compression type, unable to update initrd.gz." 0 0
@@ -51,16 +74,16 @@ if [ -d initrd-expanded ];then
    mv -f initrd.${EXT} "$1"
    pupdialog --background '#80FF80' --backtitle "initrd.gz: success" --msgbox "File ${1} has been updated with the contents of /root/initrd-expanded." 0 0
   fi
-   
+
  fi
  pupdialog --background "yellow" --backtitle "initrd.gz: finished" --yesno "Do you want to delete /root/initrd-expanded? If in doubt, please choose Yes" 0 0
  if [ $? -eq 0 ];then
   rox -D /root/initrd-expanded 2>/dev/null
   rm -rf /root/initrd-expanded
  fi
-  
+
 else
- 
+
  pupdialog --background "yellow" --backtitle "initrd.gz: expand?"  --yesno "Do you want to open up initrd.gz, and optionally edit it?" 0 0
  if [ $? -eq 0 ];then
   compr_func "$1"
