/usr/sbin/eventmanager: Major code overhaul for last commit. Added recognition of DISPLAY variable for appropriate eventmanager.conf file in /etc . Disabled the redraw icon and changed the headline since restart of X is not neccessary anymore. Use a loop to restart the GUI after pressing OK button to be able to review the settings.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/eventmanager b/woof-code/rootfs-skeleton/usr/sbin/eventmanager
--- a/woof-code/rootfs-skeleton/usr/sbin/eventmanager
+++ b/woof-code/rootfs-skeleton/usr/sbin/eventmanager
@@ -42,11 +42,19 @@
 #
 ########################################################################
 
-. /etc/rc.d/f4puppy5
+test -s /etc/rc.d/f4puppy5 && . /etc/rc.d/f4puppy5
 # BATCHMARKER01 - Marker for Line-Position to bulk insert code into.
 
 PROG='/usr/sbin/eventmanager'
+
+DISP=${DISPLAY%.*}
+if test "$DISP"; then
+CONF_FILE=/etc/eventmanager."$DISP".conf
+test -s $CONF_FILE || cp $VERB -f /etc/eventmanager $CONF_FILE
+else
 CONF_FILE=/etc/eventmanager
+fi
+
 PARENT="$0"
 
 SHOWMODE=$1 #v405 optional to modify gui.
@@ -80,23 +88,28 @@ fi
 exit $RV
 }
 
+
+while :
+do
+
 [ -s $CONF_FILE ] && { . $CONF_FILE || _exit_with_xmessage 2 "Error reading $CONF_FILE ."; }
+CONFIG="`cat $CONF_FILE`" # used after gtkdialog exit. But read here in case something alters the CONF_FILE in between.
 
-[ "$ICONDESK" != "true" -a "$ICONDESK" != "false" ] && ICONDESK="true"
-[ "$HOTPLUGNOISY" != "true" -a "$HOTPLUGNOISY" != "false" ] && HOTPLUGNOISY="false"
-[ "$AUTOTARGET" != "true" -a "$AUTOTARGET" != "false" ] && AUTOTARGET="true"
-[ "$ICONPARTITIONS" != "true" -a "$ICONPARTITIONS" != "false" ] && ICONPARTITIONS="true"
-[ "$HOTPLUGON" != "true" -a "$HOTPLUGON" != "false" ] && HOTPLUGON="true"
-[ "$BACKENDON" != "true" -a "$BACKENDON" != "false" ] && BACKENDON="true"
-[ "$FD0ICON" != "true" -a "$FD0ICON" != "false" ] && FD0ICON="true"
+[ "$FD0ICON" = "true" -o "$FD0ICON" = "false" ]               || FD0ICON="true"
+[ "$ICONDESK" = "true" -o "$ICONDESK" = "false" ]             || ICONDESK="true"
+[ "$HOTPLUGON" = "true" -o "$HOTPLUGON" = "false" ]           || HOTPLUGON="true"
+[ "$BACKENDON" = "true" -o "$BACKENDON" = "false" ]           || BACKENDON="true"
+[ "$AUTOTARGET" = "true" -o "$AUTOTARGET" = "false" ]         || AUTOTARGET="true"
+[ "$HOTPLUGNOISY" = "true" -o "$HOTPLUGNOISY" = "false" ]     || HOTPLUGNOISY="false"
+[ "$ICONPARTITIONS" = "true" -o "$ICONPARTITIONS" = "false" ] || ICONPARTITIONS="true"
 
-[ ! $RAMSAVEINTERVAL ] && RAMSAVEINTERVAL=30
-[ ! $POWERTIMEOUT ] && POWERTIMEOUT=0 #w007 0=never.
-[ ! $AUTOUNMOUNT ] && AUTOUNMOUNT="false" #v424
+RAMSAVEINTERVAL=${RAMSAVEINTERVAL:-30}
+POWERTIMEOUT=${POWERTIMEOUT:-0}        #w007 0=never.
+AUTOUNMOUNT=${AUTOUNMOUNT:-"false"}    #v424
 
-[ -z "$ICON_PLACE_START_GAP" ] && ICON_PLACE_START_GAP=32 #KRG
-[ -z "$ICON_PLACE_EDGE_GAP" ] && ICON_PLACE_EDGE_GAP=64
-[ -z "$ICON_PLACE_ORIENTATION" ] && ICON_PLACE_ORIENTATION='bottom'
+ICON_PLACE_EDGE_GAP=${ICON_PLACE_EDGE_GAP:-64}
+ICON_PLACE_START_GAP=${ICON_PLACE_START_GAP:-32} #KRG
+ICON_PLACE_ORIENTATION=${ICON_PLACE_ORIENTATION:-'bottom'}
 
 if [ -z "$ICON_PLACE_SPACING" ] ; then
 GEO_ROOT=`xwininfo -root | grep '\-geometry' | sed 's#^[[:blank:]]*##' | cut -f2 -d ' ' | sed 's#+.*##' | cut -f 2 -d 'x'`
@@ -125,35 +138,35 @@ fi
 
 HBOX_ICONPOS="
   <hbox>
-  <text xalign=\"0\"><label>Choose Position of Icons :</label></text>
-  <radiobutton>
-  <label>\"bottom  \"</label>
-  <default>${ICONPOSITIONB}</default>
-  <variable>ICONPSITIONB</variable>
-  </radiobutton>
-  <radiobutton>
-  <label>\"right  \"</label>
-  <default>${ICONPOSITIONR}</default>
-  <variable>ICONPSITIONR</variable>
-  </radiobutton>
-  <radiobutton>
-  <label>\"top  \"</label>
-  <default>${ICONPOSITIONT}</default>
-  <variable>ICONPSITIONT</variable>
-  </radiobutton>
-  <radiobutton>
-  <label>\"left  \"</label>
-  <default>${ICONPOSITIONL}</default>
-  <variable>ICONPSITIONL</variable>
-  </radiobutton>
-  <text xalign=\"0\"><label>\"            \"</label></text>
+   <text xalign=\"0.0\"><label>Choose Position of Icons :</label></text>
+   <radiobutton>
+    <label>\"bottom  \"</label>
+    <default>${ICONPOSITIONB}</default>
+    <variable>ICONPSITIONB</variable>
+   </radiobutton>
+   <radiobutton>
+    <label>\"right  \"</label>
+    <default>${ICONPOSITIONR}</default>
+    <variable>ICONPSITIONR</variable>
+   </radiobutton>
+   <radiobutton>
+    <label>\"top  \"</label>
+    <default>${ICONPOSITIONT}</default>
+    <variable>ICONPSITIONT</variable>
+   </radiobutton>
+   <radiobutton>
+    <label>\"left  \"</label>
+    <default>${ICONPOSITIONL}</default>
+    <variable>ICONPSITIONL</variable>
+   </radiobutton>
+   <text xalign=\"0.0\"><label>\"            \"</label></text>
   </hbox>
 "
 ##other vars
 PGS=`grep "pinboard_grid_step" $HOME/.config/rox.sourceforge.net/ROX-Filer/Options | sed -e "s/ *<[^>]*>//g"`
-echo $PGS
+echo "PGS=$PGS"
 DIS=`grep 'DRVICON=.*' /etc/rc.d/functions4puppy4 | head -n 1 | grep -o '[-0-9]\+'`
-[ -z "$DIS" ] && DIS=48
+DIS=${DIS:-48}
 HDIS=$(( DIS / 2 ))  ###KRG
 
 #w007 as have a optional cutdown gui, make sure these are all preset...
@@ -195,13 +208,14 @@ FRAMES_DESKTOP_ICONS="
  ${HBOX_ICONPOS}
  </frame>
 
- <frame>
-  <checkbox>
-   <label>Tick box to erase then redraw and realign existing icons</label>
-   <default>false</default>
-   <variable>NEWICONWIPE</variable>
-  </checkbox>
- </frame>
+# <frame>
+#  <checkbox>
+#   <label>Tick box to erase then redraw and realign existing icons</label>
+#   <default>false</default>
+#   <variable>NEWICONWIPE</variable>
+#  </checkbox>
+# </frame>
+
 </frame>
 "
 
@@ -216,9 +230,9 @@ FRAME_DRIVE_HANDLER="
    <default>${AUTOTARGET}</default>
    <variable>NEWAUTOTARGET</variable>
   </checkbox>
- </vbox>
+# </vbox>
 
- <vbox>
+# <vbox>
   <text><label>Normally you have to click on a drive icon to run the 'handler', but this checkbox makes the 'handler' run as soon as a media is plugged in. For example, plug in a DVD and it will immediately either get mounted, or if the above checkbox is ticked the media player will run:</label></text>
   <checkbox>
    <label>Tick box for auto-launch 'handler' when media plugged in</label>
@@ -232,17 +246,20 @@ FRAME_DRIVE_HANDLER="
 
 FRAME_FLOPPY="
 <frame Legacy>
+ <vbox>
   <text><label>Linux does not support hotplug detection of when a legacy floppy diskette is inserted or removed. Periodic probing requires starting the drive motor, which is very slow -- and do you want the motor to startup every 4 seconds? Therefore, if your PC has a floppy drive, tick this box to have a permanent icon on desktop (regardless whether a diskette is actually inserted, or even a floppy drive!).</label></text>
   <checkbox>
    <label>Tick box for floppy drive icon on desktop</label>
    <default>${FD0ICON}</default>
    <variable>NEWFD0ICON</variable>
   </checkbox>
+ </vbox>
 </frame>
 "
 
 FRAMES_ACTIVATE="
 <frame Activate Puppy Event Manager>
+<vbox>
 <text><label>The 'pup_event' Puppy Event Daemon runs in the background and handles hotplugging of drives, including the desktop drive icons. This also includes automatic module and firmware loading if new hardware is detected. However, turn it all off, and Puppy will revert to the same behaviour as versions prior to 4.x, in which there is no hotplug support. This reduces resource usage, so try unticking these on very old slow PCs. Pmount can still be run manually to mount and unmount partitions.</label></text>
   <checkbox>
    <label>Tick box for hotplug module/firmware loading</label>
@@ -272,7 +289,7 @@ FRAMES_ACTIVATE="
    </vbox>
   </hbox>
  </frame>
-
+</vbox>
 </frame>
 "
 
@@ -299,7 +316,7 @@ FRAME_RAMSAVE="
 
 FRAMES_PP_ROX="
 <frame PuppyPin RoxPinBoard>
-#<vbox>
+<vbox>
 #<combobox>
 #<item>This new tab lets you define some variables for the drive icons.</item>
 #<item>Note , that 'Rox-Filer > Options > Pinboard > Icon grid step'</item>
@@ -376,9 +393,10 @@ to get changes to the pin grid step working.\"
   </hbox>
   </frame>
 
-  </frame>
-</frame>
-</frame>
+  </frame>   #<frame>
+ </frame>    #<frame Note :>
+</vbox>
+</frame>     #<frame PuppyPin RoxPinBoard>
 "
 
 FRAME_POWER="
@@ -408,7 +426,7 @@ if [ "$SHOWMODE" = "desktop" ];then
 <vbox>
 
   <text use-markup=\"true\">
-  <label>\"<b>Restart X for changes to take affect</b>\"</label></text>
+  <label>\"<b>Short configuration for pup_event_frontend_d</b>\"</label></text>
 
 <notebook labels=\"Desktop Icons|Icon Handler|Legacy\">
 
@@ -448,7 +466,7 @@ else
 <vbox>
 
 <text use-markup=\"true\">
-<label>\"<b>Restart X for changes to take affect</b>\"</label></text>
+<label>\"<b>Configuration for pup_event_frontend_d</b>\"</label></text>
 
 <notebook labels=\"Activate|Desktop Icons|PinBoard|Icon Handler|Legacy Floppy|Power|Save Session\">
 
@@ -466,6 +484,14 @@ $FRAME_RAMSAVE
    <button ok></button>
    <button cancel></button>
  </hbox>
+
+ <hbox>
+   <button>
+    <label>Show small Event Manager</label>
+    <action type=\"exit\">desktopem</action>
+   </button>
+ </hbox>
+
 </vbox>
 </window>
 "
@@ -500,120 +526,122 @@ MAIN_DIALOG=${MAIN_DIALOG2:-"$MAIN_DIALOG"}
 _print_with_line_numbers "$MAIN_DIALOG"
 
 RETSTRING="`gtkdialog3 --program=MAIN_DIALOG --center`"
-[ $? -ne 0 ] && _exit_with_xmessage 1 "Some unknown error occured."
+[ $? -eq 0 ] || _exit_with_xmessage 1 "Some unknown error occured."
 
 eval "$RETSTRING"
 
 #echo "$RETSTRING" #TEST
 
-[ "$EXIT" = "abort" ] && _exit_with_xmessage 0 "Aborted"
-[ "$EXIT" = "Cancel" ] && _exit_with_xmessage 0 "Canceled."
-[ "$EXIT" ] || _exit_with_xmessage 1 "Some unknown error occured."
-
-#v405 it is running with 'desktop' param, now rerun with all tabs...
-[ "$EXIT" = "fullem" ] && exec eventmanager
+case "$EXIT" in
+ "abort" )  _exit_with_xmessage 0 "Aborted. Bye Bye.";;
+ "Cancel" ) _exit_with_xmessage 0 "Canceled. Good bye.";;
+ "" )       _exit_with_xmessage 1 "Some unknown error occured.";;
+ "desktopem" ) exec $MY_SELF desktop;;
+ "fullem" )    exec $MY_SELF;; #v405 it is running with 'desktop' param, now rerun with all tabs...
+esac
 
 #make sure that RAMSAVEINTERVAL is an integer only...
-[ "$NEWRAMSAVEINTERVAL" ] || NEWRAMSAVEINTERVAL=30 #412
+NEWRAMSAVEINTERVAL=${NEWRAMSAVEINTERVAL:-30} #412
+case $NEWRAMSAVEINTERVAL in -*) NEWRAMSAVEINTERVAL=0;; esac
 NEWRAMSAVEINTERVAL=`echo "$NEWRAMSAVEINTERVAL" | sed -e 's/[^0-9]//g'`
 #do not allow too-frequent saves...
 [ $NEWRAMSAVEINTERVAL -gt 0 -a $NEWRAMSAVEINTERVAL -lt 5 ] && NEWRAMSAVEINTERVAL=5
-echo "$NEWPOWERTIMEOUT"
+
+echo "NEWPOWERTIMEOUT=$NEWPOWERTIMEOUT"
 #w007 make sure that POWERTIMEOUT is integer only...
-[ "$NEWPOWERTIMEOUT" ] || NEWPOWERTIMEOUT=0
+NEWPOWERTIMEOUT=${NEWPOWERTIMEOUT:-0}
+case $NEWPOWERTIMEOUT in -*) NEWPOWERTIMEOUT=0;; esac
 NEWPOWERTIMEOUT=`echo "$NEWPOWERTIMEOUT" | sed -e 's/[^0-9]//g'`  ##[^0-9] seems to mean none digits
-echo "$NEWPOWERTIMEOUT"
+echo "NEWPOWERTIMEOUT=$NEWPOWERTIMEOUT"
 #do not allow too-frequent power-down...
-#[ "`echo
-#[ "$NEWPOWERTIMEOUT" -lt 0 ] && NEWPOWERTIMEOUT=0 not necessary
 [ $NEWPOWERTIMEOUT -gt 0 -a $NEWPOWERTIMEOUT -lt 5 ] && NEWPOWERTIMEOUT=5
 
 #v403 if major-switch has turned off hotplug support, only show one icon...
-[ "$NEWBACKENDON" ] || NEWBACKENDON="true" #v412
-[ "$NEWHOTPLUGON" ] || NEWHOTPLUGON="true" #v412
+NEWBACKENDON=${NEWBACKENDON:-"true"} #v412
+NEWHOTPLUGON=${NEWHOTPLUGON:-"true"} #v412
 [ "$NEWBACKENDON" = "false" ] && NEWHOTPLUGON="false"
 if [ "$NEWHOTPLUGON" = "false" ];then
- NEWICONDESK="false"
  NEWICONPARTITIONS="false"
  NEWHOTPLUGNOISY="false"
- NEWAUTOTARGET="false"
  NEWAUTOUNMOUNT="false" #v424
+ NEWAUTOTARGET="false"
+ NEWICONDESK="false"
 fi
-[ "$NEWIPSGAP" -lt "$(( $DIS /2 ))" ] && NEWIPSGAP=32
+[ "$NEWIPSGAP" -lt $(( DIS / 2 )) ] && NEWIPSGAP=32
 
 STATUS=0
-CONFIG="`cat $CONF_FILE`"
+#CONFIG="`cat $CONF_FILE`"
 
 _adjust_config(){
 if test "$*"; then
 CONFIG=`echo "$CONFIG" | sed -e "$*"`
+else
+ false
 fi
 STATUS=$((STATUS+$?))
 }
 
 rsPATTERN="s/^RAMSAVEINTERVAL=.*/RAMSAVEINTERVAL=\"${NEWRAMSAVEINTERVAL}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$rsPATTERN"`"
 _adjust_config "$rsPATTERN"
 
 #w007...
 ptPATTERN="s/^POWERTIMEOUT=.*/POWERTIMEOUT=\"${NEWPOWERTIMEOUT}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$ptPATTERN"`"
 _adjust_config "$ptPATTERN"
+
 idPATTERN="s/^ICONDESK=.*/ICONDESK=\"${NEWICONDESK}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$idPATTERN"`"
 _adjust_config "$idPATTERN"
+
 ipPATTERN="s/^ICONPARTITIONS=.*/ICONPARTITIONS=\"${NEWICONPARTITIONS}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$ipPATTERN"`"
 _adjust_config "$ipPATTERN"
+
 hnPATTERN="s/^HOTPLUGNOISY=.*/HOTPLUGNOISY=\"${NEWHOTPLUGNOISY}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$hnPATTERN"`"
 _adjust_config "$hnPATTERN"
+
 atPATTERN="s/^AUTOTARGET=.*/AUTOTARGET=\"${NEWAUTOTARGET}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$atPATTERN"`"
 _adjust_config "$atPATTERN"
+
 hoPATTERN="s/^HOTPLUGON=.*/HOTPLUGON=\"${NEWHOTPLUGON}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$hoPATTERN"`"
 _adjust_config "$hoPATTERN"
+
 boPATTERN="s/^BACKENDON=.*/BACKENDON=\"${NEWBACKENDON}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$boPATTERN"`"
 _adjust_config "$boPATTERN"
+
 fiPATTERN="s/^FD0ICON=.*/FD0ICON=\"${NEWFD0ICON}\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$fiPATTERN"`"
 _adjust_config "$fiPATTERN"
+
 auPATTERN="s/^AUTOUNMOUNT=.*/AUTOUNMOUNT=\"${NEWAUTOUNMOUNT}\"/" #v424
-#CONFIG="`echo "$CONFIG" | sed -e "$auPATTERN"`"
 _adjust_config "$auPATTERN"
-##newtabpart
+
+## new tab part
 newipsyP="s/^ICON_PLACE_SPACING_Y=.*/ICON_PLACE_SPACING_Y=\"$NEWIPSPACY\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$newipsyP"`"
 _adjust_config "$newipsyP"
+
 newipsxP="s/^ICON_PLACE_SPACING_X=.*/ICON_PLACE_SPACING_X=\"$NEWIPSPACX\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$newipsxP"`"
-_adjust_config
+_adjust_config "$newipsxP"
+
 newipspP="s/^ICON_PLACE_SPACING=.*/ICON_PLACE_SPACING=\"$NEWIPSPAC\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$newipspP"`"
 _adjust_config "$newipspP"
+
 newipsgP="s/^ICON_PLACE_START_GAP=.*/ICON_PLACE_START_GAP=\"$NEWIPSGAP\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$newipsgP"`"
 _adjust_config "$newipsgP"
+
 newipegyP="s/^ICON_PLACE_EDGE_GAP_Y=.*/ICON_PLACE_EDGE_GAP_Y=\"$NEWIPEGAPY\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$newipegPy"`"
 _adjust_config "$newipegyP"
+
 newipegxP="s/^ICON_PLACE_EDGE_GAP_X=.*/ICON_PLACE_EDGE_GAP_X=\"$NEWIPEGAPX\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$newipegxP"`"
 _adjust_config "$newipegxP"
+
 newipegP="s/^ICON_PLACE_EDGE_GAP=.*/ICON_PLACE_EDGE_GAP=\"$NEWIPEGAP\"/"
-#CONFIG="`echo "$CONFIG" | sed -e "$newipegP"`"
 _adjust_config "$newipegP"
-####placementpart
+
+## placement part
 [ "$ICONPSITIONR" = "true" ] && ICP='right'
 [ "$ICONPSITIONL" = "true" ] && ICP='left'
 [ "$ICONPSITIONT" = "true" ] && ICP='top'
 [ "$ICONPSITIONB" = "true" ] && ICP='bottom'
 
 newiposP="s/^ICON_PLACE_ORIENTATION=.*/ICON_PLACE_ORIENTATION='$ICP'/"
-#CONFIG="`echo "$CONFIG" | sed -e "$newiposP"`"
-echo newipos="$newiposP"
+echo "newipos=$newiposP"
 _adjust_config "$newiposP"
 
 if test "$STATUS" = 0; then
@@ -635,12 +663,24 @@ elif [ "$ICONDESK" != "$NEWICONDESK" ] ; then
 elif [ "$NEWICONWIPE" = "true" ] ; then
  echo "ICONWIPE" >>/tmp/pup_event_icon_change_flag #v411
 else
- exec pup_event_frontend_d restart &
+# if _pidof $Q pup_event_frontend_d; then
+#  exec pup_event_frontend_d restart &
+# else
+#  exec pup_event_frontend_d start &
+# fi
+ xmessage -title "Puppy Event Manager" -timeout 10 -bg orange1 "Puppy Event Manager:
+ Restarting pup_event_frontend_d .." &
+ if test -s /var/run/pup_event_frontend_d.pid."$DISP"; then
+  exec pup_event_frontend_d restart &
+ else
+  exec pup_event_frontend_d start &
+ fi
 fi
-##[ -n "`pidof pup_event_frontend_d`" ] && pup_event_frontend_d restart
+
+done
 
 if [ "$PARENT" = "$PROG" ] ; then
-_exit_with_xmessage 0 "All done."
+_exit_with_xmessage 0 "All done. Good bye."
 else
 return
 fi
