woof-code/rootfs-skeleton/usr/sbin/exploderpm: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/exploderpm b/woof-code/rootfs-skeleton/usr/sbin/exploderpm
--- a/woof-code/rootfs-skeleton/usr/sbin/exploderpm
+++ b/woof-code/rootfs-skeleton/usr/sbin/exploderpm
@@ -10,6 +10,35 @@
 # (c) bjdouma@xs4all.nl VER="v1.5, october 2004"
 #110705 bk: added -i install option for rpm.
 
+_TITLE_=exploderpm
+_COMMENT_="CLI to install .deb and .rpm archives."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST="OPT|FILE"
+ADD_PARAMETERS="-i : use cpio --unconditional -idm
+-l : Omit PASS2, use cpio -t
+-v : Omit PASS2, use cpio -v
+-x : use cpio -idm -ivdm
+
+File-name: /path/to/package.rpm"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
+
 OPT="$1"
 FILE="$2"
 [[ $OPT = '-lv' ]] && VERBOSE='v' OPT='-l'
@@ -26,39 +55,39 @@ explode() {
 
 gzip_sieve()
 {
-	# gzip-magic: 0x1F,0x8B
-	sed -ne '/1[fF]/{;N;/8[bB]$/{;s/1[fF]//g;s/^0*//g;P;};}'
+        # gzip-magic: 0x1F,0x8B
+        sed -ne '/1[fF]/{;N;/8[bB]$/{;s/1[fF]//g;s/^0*//g;P;};}'
 }
 
 bzip2_sieve()
 {
-	# bzip2-magic: 0x42,0x5A,0x68
-	sed -ne '/42/{;N;/5[aA]$/{;N;/68$/{s/42//g;s/5[aA]//g;s/^0*//g;P;};};}'
+        # bzip2-magic: 0x42,0x5A,0x68
+        sed -ne '/42/{;N;/5[aA]$/{;N;/68$/{s/42//g;s/5[aA]//g;s/^0*//g;P;};};}'
 }
 
 probe()
 {
-	dd if=$FILE ibs=$O skip=1 2>/dev/null \
-	| $2 -dc - 2>/dev/null \
-	| cpio "$1" 2>/dev/null
+        dd if=$FILE ibs=$O skip=1 2>/dev/null \
+        | $2 -dc - 2>/dev/null \
+        | cpio "$1" 2>/dev/null
 }
 
 explode_deb() {
 
 PASS1="probe -t$VERBOSE"
 case $OPT in
-	'-l'|'-v') PASS2=":" ;;
-	'-x') PASS2="probe -idm" ;;
+        '-l'|'-v') PASS2=":" ;;
+        '-x') PASS2="probe -idm" ;;
 esac
 
 for AR in gzip bzip2 ; do
-	e=1
-	HEADER_SIZE=256000
-	AR_OFFSETS=$(od -A d -N $HEADER_SIZE -v -t x1 -w1 $FILE | ${AR}_sieve)
-	for O in $AR_OFFSETS ; do
-		$PASS1 $AR 2>/dev/null && $PASS2 $AR && e=0
-	done
-	[ $e -eq 0 ] && return $e
+        e=1
+        HEADER_SIZE=256000
+        AR_OFFSETS=$(od -A d -N $HEADER_SIZE -v -t x1 -w1 $FILE | ${AR}_sieve)
+        for O in $AR_OFFSETS ; do
+                $PASS1 $AR 2>/dev/null && $PASS2 $AR && e=0
+        done
+        [ $e -eq 0 ] && return $e
 done
 }
 
@@ -81,40 +110,40 @@ explode_rpm() {
   gz="$(echo -en '\037\0213')"
   #xz="$(echo -en '\0fd\037\07a\058\05a\000')"
   case $OPT in
-	'-x')
-		case "$comp" in
-			BZh)      dd if="$pkg" ibs=$o skip=1 2>/dev/null | bunzip2 | cpio --quiet -ivdm ;;
-			"$gz"*)   dd if="$pkg" ibs=$o skip=1 2>/dev/null | gunzip | cpio --quiet -ivdm ;;
-			"]"*)     dd if="$pkg" ibs=$o skip=1 2>/dev/null | unxz | cpio --quiet -ivdm ;;
-			*)        echo "Unrecognized rpm file: $pkg"; return 1 ;;
-		esac
-	;;
-	'-l')
-		case "$comp" in
-			BZh)      dd if="$pkg" ibs=$o skip=1 2>/dev/null | bunzip2 | cpio --quiet -t$VERBOSE ;;
-			"$gz"*)   dd if="$pkg" ibs=$o skip=1 2>/dev/null | gunzip | cpio --quiet -t$VERBOSE ;;
-			"]"*)     dd if="$pkg" ibs=$o skip=1 2>/dev/null | unxz | cpio --quiet -t$VERBOSE ;;
-			*)        echo "Unrecognized rpm file: $pkg"; return 1 ;;
-		esac
-	;;
-	'-i') #110705 install
-		CURRDIR="`pwd`"
-		if [ ! -f ${CURRDIR}/${pkg} ];then
-		 echo "Error: ${CURRDIR}/${pkg} does not exist"
-		 return 1
-		fi
-		cd /
-		case "$comp" in
-			BZh)      dd if="${CURRDIR}/$pkg" ibs=$o skip=1 2>/dev/null | bunzip2 | cpio --quiet --unconditional -idm ;;
-			"$gz"*)   dd if="${CURRDIR}/$pkg" ibs=$o skip=1 2>/dev/null | gunzip | cpio --quiet --unconditional -idm ;;
-			"]"*)     dd if="${CURRDIR}/$pkg" ibs=$o skip=1 2>/dev/null | unxz | cpio --quiet --unconditional -idm ;;
-			*)        echo "Unrecognized rpm file: $pkg"; return 1 ;;
-		esac
-		RETSTAT=$?
-		cd "$CURRDIR"
-		[ $RETSTAT != 0 ] && return 1
-		return 0
-	;;
+        '-x')
+                case "$comp" in
+                        BZh)      dd if="$pkg" ibs=$o skip=1 2>/dev/null | bunzip2 | cpio --quiet -ivdm ;;
+                        "$gz"*)   dd if="$pkg" ibs=$o skip=1 2>/dev/null | gunzip | cpio --quiet -ivdm ;;
+                        "]"*)     dd if="$pkg" ibs=$o skip=1 2>/dev/null | unxz | cpio --quiet -ivdm ;;
+                        *)        echo "Unrecognized rpm file: $pkg"; return 1 ;;
+                esac
+        ;;
+        '-l')
+                case "$comp" in
+                        BZh)      dd if="$pkg" ibs=$o skip=1 2>/dev/null | bunzip2 | cpio --quiet -t$VERBOSE ;;
+                        "$gz"*)   dd if="$pkg" ibs=$o skip=1 2>/dev/null | gunzip | cpio --quiet -t$VERBOSE ;;
+                        "]"*)     dd if="$pkg" ibs=$o skip=1 2>/dev/null | unxz | cpio --quiet -t$VERBOSE ;;
+                        *)        echo "Unrecognized rpm file: $pkg"; return 1 ;;
+                esac
+        ;;
+        '-i') #110705 install
+                CURRDIR="`pwd`"
+                if [ ! -f ${CURRDIR}/${pkg} ];then
+                 echo "Error: ${CURRDIR}/${pkg} does not exist"
+                 return 1
+                fi
+                cd /
+                case "$comp" in
+                        BZh)      dd if="${CURRDIR}/$pkg" ibs=$o skip=1 2>/dev/null | bunzip2 | cpio --quiet --unconditional -idm ;;
+                        "$gz"*)   dd if="${CURRDIR}/$pkg" ibs=$o skip=1 2>/dev/null | gunzip | cpio --quiet --unconditional -idm ;;
+                        "]"*)     dd if="${CURRDIR}/$pkg" ibs=$o skip=1 2>/dev/null | unxz | cpio --quiet --unconditional -idm ;;
+                        *)        echo "Unrecognized rpm file: $pkg"; return 1 ;;
+                esac
+                RETSTAT=$?
+                cd "$CURRDIR"
+                [ $RETSTAT != 0 ] && return 1
+                return 0
+        ;;
   esac
   [ $? != 0 ] && return 1
   # The directories that are not listed in the RPM file are always created
