/usr/sbin/filemnt : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/filemnt b/woof-code/rootfs-skeleton/usr/sbin/filemnt
--- a/woof-code/rootfs-skeleton/usr/sbin/filemnt
+++ b/woof-code/rootfs-skeleton/usr/sbin/filemnt
@@ -50,18 +50,18 @@ Version='1.3-getopts Macpup_Opera_2-Puppy_Linux_431 KRG'  ## Create MOUNT_EXE an
                                                           ## and some functions to let mount.sh handle
                                                           ##  creation and deletion of mountpoint directories
                                                           ##  and close/open ROX-Filer windows
-Version='1.4-getopts Macpup_Opera_2-Puppy_Linux_431 KRG'  ## 3 BUGFIXES : 
-                                                          ##  -false added to losetup -f test return value 
-                                                          ##  -use imageFILEBASE instead oneIMGBASE in check_already_mounted_func 
+Version='1.4-getopts Macpup_Opera_2-Puppy_Linux_431 KRG'  ## 3 BUGFIXES :
+                                                          ##  -false added to losetup -f test return value
+                                                          ##  -use imageFILEBASE instead oneIMGBASE in check_already_mounted_func
                                                           ##   because losetup -j could override testing all loop devices
-                                                          ##  -typos in comments and debug output 
+                                                          ##  -typos in comments and debug output
                                                           ## 3 functions added :
                                                           ##  _losetup : switch to correct losetup usage
                                                           ##  _test_bb_version : helper for losetup
-                                                          ##  _fuser : switch to correct fuser usage                                                         
+                                                          ##  _fuser : switch to correct fuser usage
 
 Version='1.5-getopts Macpup_Opera_2-Puppy_Linux_431 KRG'  ## Add sfs_load interface
-                                                          
+
 usage (){
 MSG="
 $0 [-h -V -l ] FILENAME.EXT
@@ -93,20 +93,27 @@ if [ "`which sfs_load`" ]; then
 case $PUPMODE in
 
 ''|2|3) :;;
-*) 
-  LOAD_MSG=`gettext "Do you want insert/load/integrate the 
-$imageFILEBASE into the current running 
+*)
+  case "$imageFILEBASE" in
+  *.sfs)
+    LOAD_MSG=`gettext "Do you want insert/load/integrate the
+$imageFILEBASE into the current running
 $DISTRO_NAME $DISTRO_VERSION ?
-Or do you just want to mount it to look inside ? 
-"`   
-  xmessage -buttons "Insert:100,Mount:101" "$LOAD_MSG"
-  case $? in
-  100) exec sfs_load "$@";;
-  *) :;;
+Or do you just want to mount it to look inside ?
+"`
+    INSERT_B=`gettext 'Insert'`
+    MOUNT_B=`gettext 'Mount'`
+    xmessage -buttons "$INSERT_B:100,$MOUNT_B:101" "$LOAD_MSG"
+    case $? in
+    100) exec sfs_load "$@";;
+    101) :;;
+    *) exit 0;;
+    esac
+  ;;
   esac
 ;;
-
 esac
+
 fi
 }
 
