filemnt : Bulk Maintanance Replacement of today.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/filemnt b/woof-code/rootfs-skeleton/usr/sbin/filemnt
--- a/woof-code/rootfs-skeleton/usr/sbin/filemnt
+++ b/woof-code/rootfs-skeleton/usr/sbin/filemnt
@@ -359,6 +359,39 @@ fi # 5
 
 if [ -z "$UNMOUNT" ] ; then #55 == yes || [ -n "$MOUNT" ] == again
 
+_handle_squashfs()
+{
+  if [ "$Type" = "squashfs" ];then #8
+
+   diskTYPE_OUT=`disktype "${file_toMOUNT}" 2>&1`
+   test "`echo "$diskTYPE_OUT" | grep 'Input/output error'`" && { [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "ERROR : The
+${file_toMOUNT##*/} may be corrupted.
+Cannot mount it currently."; ##exit 1
+   } || {
+
+   if [ "`disktype "${file_toMOUNT}" | grep "$SFSSTR"`" = "" ];then #8.1
+
+    if [ $SFSMAJOR -eq 4 ] ;then #8.1.1 #100606
+     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This is likely an older version 3.x squashfs file, not usable.
+All Linux kernels 2.6.29 or later require version 4.x squashfs files.
+Note, there is an SFS-version-converter in the Utility menu, run that first.
+
+`unsquashfs -s file_toMOUNT 2>&1`
+"
+    else #8.1.1
+     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This is likely a newer version 4.x squashfs file, not usable.
+All Linux kernels 2.6.28 or earlier require version 3.x squashfs files.
+Note, there is an SFS-version-converter in the Utility menu, run that first.
+
+`unsquashfs -s file_toMOUNT 2>&1`
+"
+    fi #8.1.1
+    exit 1
+   fi #8.1
+   }
+  fi #8
+}
+
 _guess_file_fstype()
 {
   Type=`guess_fstype "$file_toMOUNT"`
