filemnt : Bulk Maintanance Replacement of today.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/filemnt b/woof-code/rootfs-skeleton/usr/sbin/filemnt
--- a/woof-code/rootfs-skeleton/usr/sbin/filemnt
+++ b/woof-code/rootfs-skeleton/usr/sbin/filemnt
@@ -113,6 +113,7 @@ esac
 
 #[ "$KERNELSUBVER" -gt 28 ] && SFSSTR='squashfs, version 4'
 }
+_debug "SFSSTR='$SFSSTR' SFSMAJOR='$SFSMAJOR'"
 
 imgFile="$1"
 if [ -z "$imgFile" ] ;then exit 1 ;fi #1
@@ -259,8 +260,20 @@ if [ -z "$UNMOUNT" ] ; then #55 == yes || [ -n "$MOUNT" ] == again
   fi
   #v423 detect wrong squashfs version...
   if [ "$Type" = "squashfs" ];then #8
+
+   diskTYPE_OUT=`disktype "${imgFile}" 2>&1`
+   test "`echo "$diskTYPE_OUT" | grep 'Input/output error'`" && { [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "ERROR : The
+${imgFile##*/} may be corrupted.
+Cannot mount it currently."; ##exit 1
+   } || {
+
    if [ "`disktype "${imgFile}" | grep "$SFSSTR"`" = "" ];then #8.1
-    if [ $KERNELSUBVER -gt 28 ];then #8.1.1
+
+    if [ "`echo "$KERNELVER" | grep -E '^2\.6`" -a $KERNELSUBVER -gt 28 ];then #8.1.1
+     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This is an older version 3.x squashfs file, not usable.
+All Linux kernels 2.6.29 or later require version 4.x squashfs files.
+Note, there is an SFS-version-converter in the Utility menu, run that first."
+    elif [ "`echo "$KERNELVER" | grep -E '^3\.[0-9]'`" ];then #8.1.1
      [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This is an older version 3.x squashfs file, not usable.
 All Linux kernels 2.6.29 or later require version 4.x squashfs files.
 Note, there is an SFS-version-converter in the Utility menu, run that first."
@@ -269,8 +282,9 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
 All Linux kernels 2.6.28 or earlier require version 3.x squashfs files.
 Note, there is an SFS-version-converter in the Utility menu, run that first."
     fi #8.1.1
-    exit
+    exit 1
    fi #8.1
+   }
   fi #8
 
 
