woof-code/rootfs-skeleton/usr/sbin/filemnt: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/filemnt b/woof-code/rootfs-skeleton/usr/sbin/filemnt
--- a/woof-code/rootfs-skeleton/usr/sbin/filemnt
+++ b/woof-code/rootfs-skeleton/usr/sbin/filemnt
@@ -1,9 +1,32 @@
 #!/bin/bash
-##############  ROX app.: Click image files to mount & unmount.	by: Terry Becker	aka: SunBurnt
-##############	File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
+##############  ROX app.: Click image files to mount & unmount. by: Terry Becker        aka: SunBurnt
+##############  File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
 #v423 detect wrong squashfs version 3.x or 4.x.
 #v424 advise of sfs-version-converter.
 #100606 have backported squashfs4 to kernel 2.6.27.47.
+
+_TITLE_=filemount
+_COMMENT_="CLI to mount image files ( .sfs,.2fs,.iso )."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=FILENAME
+ADD_PARAMETERS="File-name : /path/to/file.iso"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 #v423...
 KERNELVER="`uname -r`"
@@ -28,12 +51,12 @@ fi
   imgFile="`pwd``echo $imgFile |sed 's/^\.//'`"
  fi
  MntPt='/mnt/'`echo "$imgFile" |sed "s#^\.##g" |sed "s#/#+#g"`
- 
 
-if [ 1 -eq 2 ] ;then	##############################################	JUMP OVER this SECTION.
+
+if [ 1 -eq 2 ] ;then    ##############################################  JUMP OVER this SECTION.
 
  loMnts="`mount |grep '/dev/loop' |awk '{print $1}'`"
- echo "$loMnts" |while read LOOP					### test if file's mounted
+ echo "$loMnts" |while read LOOP                                        ### test if file's mounted
  do
    loFile="`losetup-FULL $LOOP |sed 's/^.*(//' |sed 's/).*$//'`"
    if [ "$loFile" = "$imgFile" ] ;then
@@ -43,16 +66,16 @@ if [ 1 -eq 2 ] ;then	##############################################	JUMP OVER th
    i=`expr $i + 1`
  done
 
-fi			##############################################	END of JUMP SECTION.
+fi                      ##############################################  END of JUMP SECTION.
 
 
-							### file's not mounted, mount it
+                                                        ### file's not mounted, mount it
 # if [ $i -eq 16 ] ;then
 
  imgFileBASE="`basename "$imgFile"`" #BK
 
  if [ ! -d "$MntPt" ] ;then
- 
+
   #BK check if already mounted elsewhere...
   for ONELOOP in `mount | grep '^/dev/loop' | cut -f 1 -d ' ' | tr '\n' ' '`
   do
@@ -65,8 +88,8 @@ fi			##############################################	END of JUMP SECTION.
      exit
     fi
   done
-   
-  Ext=`echo "$imgFile" |sed 's/^.*\.//'`	# get file type from extention
+
+  Ext=`echo "$imgFile" |sed 's/^.*\.//'`        # get file type from extention
   if [ "$Ext" = '2fs' ] ;then
    Type='ext2'
   elif [ "$Ext" = '3fs' ] ;then
@@ -80,10 +103,10 @@ fi			##############################################	END of JUMP SECTION.
   # BK
   #elif [ "$imgFile" = 'initrd.gz' ] ;then
   # Type='ext2'
-  # gunzip $imgFile				# handle gzip image file
+  # gunzip $imgFile                             # handle gzip image file
   # imgFile="echo "$imgFile" |sed 's/.gz$//'"
   fi
-  
+
   #v423 detect wrong squashfs version...
   if [ "$Type" = "squashfs" ];then
    if [ "`disktype "${imgFile}" | grep "$SFSSTR"`" = "" ];then
@@ -101,7 +124,7 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
     exit
    fi
   fi
-  
+
 #  echo -e "\nimgFile = $imgFile\t\tExt  = $Ext"
 #  echo -e "MntPt   = $MntPt\t\tType = $Type\n"
   echo -e "\n ### Mount: $imgFile\n"
@@ -111,9 +134,9 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
   if [ $Err -eq 0 ] ;then
    rox -d $MntPt # mount good, run rox filer
    yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
-  fi	
+  fi
 
- else							### file's mounted, unmount it
+ else                                                   ### file's mounted, unmount it
   rox -D $MntPt #BK
   umount $MntPt
   Err=$?
@@ -122,11 +145,11 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
   yaf-splash -timeout 3 -font "8x16" -outline 0 -margin 4 -bg orange -text "Unmounting $imgFileBASE" #BK
   #Xdialog --title " Notice..." --no-button \
   #        --infobox "
-  #UnMounting: $imgFile  
+  #UnMounting: $imgFile
   #" 0 0 2000
   echo -e "\n ### UnMount: $imgFile\n"
   rmdir $MntPt
  fi
- if [ $Err -gt 0 ] ;then			# ERROR: mount/unmount
+ if [ $Err -gt 0 ] ;then                        # ERROR: mount/unmount
   xmessage -title " ERROR..." "  Failed mounting or unmounting with errorcode $Err ..."
  fi
