woof-code/rootfs-skeleton/usr/sbin/filemnt: Changed  header to use standards in f4puppy5 . Maybe some fixes for very old code.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/filemnt b/woof-code/rootfs-skeleton/usr/sbin/filemnt
--- a/woof-code/rootfs-skeleton/usr/sbin/filemnt
+++ b/woof-code/rootfs-skeleton/usr/sbin/filemnt
@@ -1,10 +1,10 @@
 #!/bin/bash
-##############  ROX app.: Click image files to mount & unmount.	by: Terry Becker	aka: SunBurnt
-##############	File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
+##############  ROX app.: Click image files to mount & unmount. by: Terry Becker    aka: SunBurnt
+##############  File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
 #v423 detect wrong squashfs version 3.x or 4.x.
 #v424 advise of sfs-version-converter.
 
-
+__old_header__(){
 ###KRG Fr 31. Aug 23:34:58 GMT+1 2012
 
 trap "exit 1" HUP INT QUIT KILL TERM
@@ -34,14 +34,15 @@ exit $1
 [ "`echo "$1" | grep -wE "\-version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
 }
 ###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+}
 
 ########################################################################
 #
 # CHANGES by Karl Reimer Godt
 # 01.0 : added xmessage dialog if already mounted to choose actions :
 #        Quit,ROX-Filer,console,Unmount,Unmountall,MountAnotherTime
-# 02.0 : position of removal of $MntPt changed in code
-# 03.0 : double quoted all $imgFile AND $MntPt in case of spaces
+# 02.0 : position of removal of $mntPT changed in code
+# 03.0 : double quoted all $imgFILE AND $mntPT in case of spaces
 # 04.0 : added support for these extensions :
 #        .squashfs, .sqfs, .squashfs.img -> .sfs
 #        .ext3fs.img -> ext3
@@ -103,10 +104,10 @@ OUT=/dev/null;ERR=$OUT
 while getopts Vvdhl opt;do
 case $opt in
 V) echo -e "\n$0: Version '$Version'\n";exit 0;;
-v) VERBOSE=1;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;ERR=/dev/stderr;OUT=/dev/stdout;;
-d) DEBUG=1;set -x;;
+v) VERBOSE=1;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;ERR=/dev/stderr;OUT=/dev/stdout;shift;;
+d) DEBUG=1;set -x;shift;;
 h) usage 0;;
-l) exec 1>>/tmp/filemnt.log 2>&1;;
+l) shift;exec 1>>/tmp/filemnt.log 2>&1;;
 *) :;;
 esac;done
 
@@ -121,81 +122,81 @@ if [ "$KERNEL_MAJ" -lt 3 ] ; then
 [ "$KERNELSUBVER" -lt 29 ] && SFSSTR='squashfs, version 3'
 fi
 
-imgFile="$1"
-if [ -z "$imgFile" ];then usage 1 ;fi
-[ -f "$imgFile" ] || { echo "'$imgFile' seems not to be here . Exit .";exit 1; }
+imgFILE="$1"
+if [ -z "$imgFILE" ];then usage 1 ;fi
+[ -f "$imgFILE" ] || { echo "'$imgFILE' seems not to be here . Exit .";exit 1; }
 
-if [ "`basename "$imgFile"`" = 'initrd' ] ; then
- if [ "`file "$imgFile" | grep -i 'cpio'`" ] ; then
-  cd `dirname "$imgFile"`
+if [ "`basename "$imgFILE"`" = 'initrd' ] ; then
+ if [ "`file "$imgFILE" | grep -i 'cpio'`" ] ; then
+  cd `dirname "$imgFILE"`
   rm -rf initrd-tree
   mkdir initrd-tree
   cd initrd-tree
   cat ../initrd |cpio -i -d
   exit $?
  else
-  gzip -9 "$imgFile" ;fi
+  gzip -9 "$imgFILE" ;fi
   exit $?
 fi
 
-if [ "`basename "$imgFile"`" = 'initrd.gz' ] ; then
- if [ "`file "$imgFile" | grep -i 'cpio'`" ] ; then
-  cd `dirname "$imgFile"`
+if [ "`basename "$imgFILE"`" = 'initrd.gz' ] ; then
+ if [ "`file "$imgFILE" | grep -i 'cpio'`" ] ; then
+  cd `dirname "$imgFILE"`
   rm -rf initrd-tree
   mkdir initrd-tree
   cd initrd-tree
   zcat ../initrd.gz |cpio -i -d
   exit $?
  else
-  gunzip "$imgFile" ;fi
+  gunzip "$imgFILE" ;fi
   exit $?
 fi
 
-if [ "`basename "$imgFile"`" = 'initrd.xz' ] ; then
- if [ "`file "$imgFile" | grep -i 'cpio'`" ] ; then
-  cd `dirname "$imgFile"`
+if [ "`basename "$imgFILE"`" = 'initrd.xz' ] ; then
+ if [ "`file "$imgFILE" | grep -i 'cpio'`" ] ; then
+  cd `dirname "$imgFILE"`
   rm -rf initrd-tree
   mkdir initrd-tree
   cd initrd-tree
   xzcat ../initrd.xz |cpio -i -d
   exit $?
  else
-   xz -d  "$imgFile" ;fi
+   xz -d  "$imgFILE" ;fi
    exit $?
 fi
 
-if [ "`dirname "$imgFile"`" = '\.' ] ;then # 2
-      imgFile=`pwd``echo "$imgFile" |sed 's/^\.//'`
+if [ "`dirname "$imgFILE"`" = '\.' ] ;then # 2
+      imgFILE=`pwd``echo "$imgFILE" |sed 's/^\.//'`
 fi # 2
 
 
-#MntPt='/mnt/'`echo "$imgFile" |sed "s#^\.##g" |sed "s#/#+#g"`
-MntPt='/mnt/'`basename "$imgFile"`.$$  ##my change
-grepPatternMntPt=`echo "$MntPt" | sed 's#\([[:punct:]]\)#\\\1#g'`
-grepPatternImgFile=`echo "$imgFile" | sed 's#\([[:punct:]]\)#\\\1#g'`
+#mntPT='/mnt/'`echo "$imgFILE" |sed "s#^\.##g" |sed "s#/#+#g"`
+mntPT='/mnt/'`basename "$imgFILE"`.$$  ##my change
+grepPatternMntPt=`echo "$mntPT" | sed 's#\([[:punct:]]\)#\\\1#g'`
+grepPatternImgFile=`echo "$imgFILE" | sed 's#\([[:punct:]]\)#\\\1#g'`
 
-if [ 1 -eq 2 ] ;then	##############################################	JUMP OVER this SECTION.
+if [ 1 -eq 2 ] ;then    ##############################################  JUMP OVER this SECTION.
 
  loMnts=`mount |grep '/dev/loop' |awk '{print $1}'`
- echo "$loMnts" |while read LOOP					### test if file's mounted
+ echo "$loMnts" |while read LOOP                    ### test if file's mounted
  do
    loFile=`losetup-FULL $LOOP |sed 's/^.*(//' |sed 's/).*$//'`
-   if [ "$loFile" = "$imgFile" ] ;then
+   if [ "$loFile" = "$imgFILE" ] ;then
     echo -e "\n ### Loop File: $loFile"
     break
    fi
    i=`expr $i + 1`
  done
 
-fi			##############################################	END of JUMP SECTION.
+fi          ##############################################  END of JUMP SECTION.
 
 
-							### file's not mounted, mount it
+                            ### file's not mounted, mount it
 # if [ $i -eq 16 ] ;then
 
-imgFileBASE=`basename "$imgFile"` #BK  ##only for yaf/xmessage message not too long
+imgFileBASE=`basename "$imgFILE"` #BK  ##only for yaf/xmessage message not too long
 
-if [ ! -d "$MntPt" ] ;then # 5
+if [ ! -d "$mntPT" ] ;then # 5
 
 check_already_mounted_func(){
 
@@ -213,10 +214,10 @@ check_already_mounted_func(){
     echo "IMGBASE='$IMGBASE' imgFileBASE='$imgFileBASE'" #TEST
     #not perfect, but paths may be symlinks...
 
-    if [ "$IMGBASE" = "$imgFileBASE" ];then #if [ "$MNTDIMG" = "$imgFile" ];then #6
+    if [ "$IMGBASE" = "$imgFileBASE" ];then #if [ "$MNTDIMG" = "$imgFILE" ];then #6
 
      if [ -n "$DISPLAY" ] ; then #66
-xmessage -buttons "Quit:190,ROX-Filer:191,console:192,Unmount:193,Unmount all $IMGBASE:194,Mount another time:199" "$imgFile
+xmessage -buttons "Quit:190,ROX-Filer:191,console:192,Unmount:193,Unmount all $IMGBASE:194,Mount another time:199" "$imgFILE
 is already mounted and in-use by Puppy .
 Do you want to unmount it or mount it to another mount point ?"
 RETVAL=$?
@@ -224,35 +225,35 @@ if [ "$RETVAL" = "190" ] ; then #666  ##Quit
      exit
 
 elif [ "$RETVAL" = "191" ] ; then #666  ##ROX-Filer
-       MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
-       rox "$MntPt"
+       mntPT=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
+       rox "$mntPT"
        exit
 
 elif [ "$RETVAL" = "192" ] ; then #666  ##console
-       MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
-       cd "$MntPt"
+       mntPT=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
+       cd "$mntPT"
        pwd
        rxvt &
        exit
 
 elif [ "$RETVAL" = "193" ] ; then #666  ##umount
        UNMOUNT='yes'
-       MntPt=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
+       mntPT=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
        return
 
 elif [ "$RETVAL" = "194" ] ; then #666  ##umount ALL $IMGBASE
        UNMOUNT='yes'
-       MntPt=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
-       echo 1 "$MntPt"
-       MntPt2=`echo "$MntPt" | sed "1 d"` ##only umount all others exect one
+       mntPT=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
+       echo 1 "$mntPT"
+       MntPt2=`echo "$mntPT" | sed "1 d"` ##only umount all others exect one
        echo 2 "$MntPt2"
        for i in $MntPt2 ; do
        GREP=`echo "$i" | sed 's#\.#\\\.#g;s#\+#\\\+#g;s#-#\\\-#g'`
        echo "$GREP"
        LOOPD=$(busybox mount | grep "$GREP" | cut -f 1 -d ' ')
        echo "$LOOPD"
-       #USEapps=`fuser -c $LOOPD`    ##---2011_10_27
-       USEapps=`fuser -m "$MntPt2"`   ##+++2011_10_27
+       #USEapps=`fuser -c $LOOPD`     ##---2011-10-27
+       USEapps=`fuser -m "$MntPt2"`   ##+++2011-10-27
        echo 3 "$USEapps"
        USEapps=`echo "$USEapps" | sed 's/[[:alpha:]]//g'`
        echo 4 "$USEapps"
@@ -265,15 +266,15 @@ elif [ "$RETVAL" = "194" ] ; then #666  ##umount ALL $IMGBASE
        sleep 2
        rmdir $i
        done
-       MntPt=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
+       mntPT=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
        return
 
 else #666
      MOUNT='again'
      return
 fi   ###666
-else ##66      ##+++2011_10_27 to fix call from without X running
-UNMOUNT='yes'  ##+++2011_10_27
+else ##66      ##+++2011-10-27 to fix call from without X running
+UNMOUNT='yes'  ##+++2011-10-27
 fi ##66
 fi #6
 done
@@ -285,7 +286,7 @@ fi # 5
 
 if [ -z "$UNMOUNT" ] ; then #55 == yes || [ -n "$MOUNT" ] == again
 
-  Ext=`echo "$imgFile" |sed 's/^.*\.//'`	# get file type from extention
+  Ext=`echo "$imgFILE" |sed 's/^.*\.//'`    # get file type from extention
   if [ "$Ext" = '2fs' ] ;then #7
    Type='ext2'
   elif [ "$Ext" = '3fs' ] ;then
@@ -300,25 +301,25 @@ if [ -z "$UNMOUNT" ] ; then #55 == yes || [ -n "$MOUNT" ] == again
    Type='squashfs'
   elif [ "$Ext" = 'iso' ] ;then
    #Fatdog fat16 first and iso9660 second  ###+++2013-03-02
-   TYPES=`disktype "$imgFile" |grep 'file system'`
+   TYPES=`disktype "$imgFILE" |grep 'file system'`
    if [ "`echo "$TYPES" |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]' | grep -i 'UDF'`" ];then
     Type=udf
    else
     Type=iso9660
    fi
    else
-   Type=`disktype "$imgFile" |grep 'file system' |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]'` ##+++2012-06-04 udf or iso9660
+   Type=`disktype "$imgFILE" |grep 'file system' |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]'` ##+++2012-06-04 udf or iso9660
    #Type='iso9660' ##---2012-06-04
   # BK
-  #elif [ "$imgFile" = 'initrd.gz' ] ;then
+  #elif [ "$imgFILE" = 'initrd.gz' ] ;then
   # Type='ext2'
-  # gunzip $imgFile				# handle gzip image file
-  # imgFile="echo "$imgFile" |sed 's/.gz$//'"
+  # gunzip $imgFILE             # handle gzip image file
+  # imgFILE="echo "$imgFILE" |sed 's/.gz$//'"
   fi #7
 
   #v423 detect wrong squashfs version...
   if [ "$Type" = "squashfs" ];then #8
-   DISK_TYPE=`disktype "${imgFile}"`
+   DISK_TYPE=`disktype "${imgFILE}"`
    if [ "`echo "${DISK_TYPE}" | grep "$SFSSTR"`" = "" ];then #8.1
     xmessage -bg orange1 "$DISK_TYPE"
     if [ $KERNELSUBVER -gt 28 ];then #8.1.1
@@ -334,34 +335,34 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
    fi #8.1
   fi #8
 
-#  echo -e "\nimgFile = $imgFile\t\tExt  = $Ext"
-#  echo -e "MntPt   = $MntPt\t\tType = $Type\n"
-  echo -e "\n$0 : Mount: $imgFile\n"
-  mkdir -p "$MntPt"
+#  echo -e "\nimgFile = $imgFILE\t\tExt  = $Ext"
+#  echo -e "mntPT   = $mntPT\t\tType = $Type\n"
+  echo -e "\n$0 : Mount: $imgFILE\n"
+  mkdir -p "$mntPT"
   echo '-------------'
-  mount -t $Type -o loop "$imgFile" "$MntPt"
-  Err=$?     ##+++2011_10_27
+  mount $VERB -t $Type -o loop "$imgFILE" "$mntPT"
+  Err=$?     ##+++2011-10-27
   echo '-------------'
   sleep 2s
-  #Err=$?    ##---2011_10_27
-  if [ $Err -eq 0 ] || [ -n "`mount | grep "$MntPt"`" ];then #9
+  #Err=$?    ##---2011-10-27
+  if [ $Err -eq 0 ] || [ -n "`mount | grep "$mntPT"`" ];then #9
    if [ -n "$DISPLAY" ] ; then #99
-    rox -d "$MntPt" # mount good, run rox filer
+    rox -d "$mntPT" # mount good, run rox filer
    ##[ -n "$DISPLAY" ] && yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
     yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
    fi #99
   fi #9
 
- else #55	[ -n "$UNMOUNT" ]					### file's mounted, unmount it
+ else #55   [ -n "$UNMOUNT" ]                   ### file's mounted, unmount it
 
-   [ -n "$DISPLAY" ] && rox -D "$MntPt" #BK
+   [ -n "$DISPLAY" ] && rox -D "$mntPT" #BK
 
-       GREP=`echo "$MntPt" | sed 's#\.#\\\.#g;s#\+#\\\+#g;s#-#\\\-#g'`
+       GREP=`echo "$mntPT" | sed 's#\.#\\\.#g;s#\+#\\\+#g;s#-#\\\-#g'`
        echo 1 "$GREP"
        LOOPD=$(busybox mount | grep "$GREP" | cut -f 1 -d ' ')
        echo 2 "$LOOPD"
-       #USEapps=`fuser -c $LOOPD`  ##---2011_10_27
-       USEapps=`fuser -m "$MntPt"`  ##---2011_10_27
+       #USEapps=`fuser -c $LOOPD`  ##---2011-10-27
+       USEapps=`fuser -m "$mntPT"`  ##---2011-10-27
        echo 3 "$USEapps"
        USEapps=`echo "$USEapps" | sed 's/[[:alpha:]]//g;s/[[:punct:]]//g'`
        echo 4 "$USEapps"
@@ -372,31 +373,31 @@ Note, there is an SFS-version-converter in the Utility menu, run that first."
 
   sleep 2s
   echo '------------'
-  umount "$MntPt"
+  umount "$mntPT"
   Err=$?
   echo '------------'
   #yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg orange -text "$Err"
-  #sleep 2s  ##+-2011_10_27
-  #rmdir $MntPt
-  #yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg orange -text "$MntPt"
+  #sleep 2s  ##+-2011-10-27
+  #rmdir $mntPT
+  #yaf-splash -timeout 6 -font "8x16" -outline 0 -margin 4 -bg orange -text "$mntPT"
 
 
   [ -n "$DISPLAY" ] && yaf-splash -timeout 3 -font "8x16" -outline 0 -margin 4 -bg orange -text "Unmounting $imgFileBASE" #BK
-   sleep 2s  ##+++2011_10_27
+   sleep 2s  ##+++2011-10-27
   #Xdialog --title " Notice..." --no-button \
   #        --infobox "
-  #UnMounting: $imgFile
+  #UnMounting: $imgFILE
   #" 0 0 2000
 
-  echo -e "\n$0 UnMount: $imgFile\n"
+  echo -e "\n$0 UnMount: $imgFILE\n"
 
-  #[ -d "$MntPt" -a "`busybox mount | grep "$MntPt"`" = "" ] && rmdir "$MntPt"  #=-2011_10_27
-   [ -d "$MntPt" ] && [ -z "`ls "$MntPt" 2>/dev/null`" ] && rmdir "$MntPt"
+  #[ -d "$mntPT" -a "`busybox mount | grep "$mntPT"`" = "" ] && rmdir "$mntPT"  #=-2011-10-27
+   [ -d "$mntPT" ] && [ -z "`ls "$mntPT" 2>/dev/null`" ] && rmdir "$mntPT"
  fi #55
 
- if [ "$Err" -gt 0 ] ;then			# ERROR: mount/unmount # 9999
-  [ -n "$DISPLAY" ] && xmessage -bg red -title "ERROR..." "Returned <$Err> ... mounting or unmounting $MntPt"
-  [ -d "$MntPt" ] && [ -z "`ls "$MntPt" 2>/dev/null`" ] && rmdir "$MntPt"  ##+++2011_10_27
+ if [ "$Err" -gt 0 ] ;then          # ERROR: mount/unmount # 9999
+  [ -n "$DISPLAY" ] && xmessage -bg red -title "ERROR..." "Returned <$Err> ... mounting or unmounting $mntPT"
+  [ -d "$mntPT" ] && [ -z "`ls "$mntPT" 2>/dev/null`" ] && rmdir "$mntPT"  ##+++2011-10-27
  fi # 9999
 
 
