woof-code/rootfs-skeleton/usr/sbin/fixdesk: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/fixdesk b/woof-code/rootfs-skeleton/usr/sbin/fixdesk
--- a/woof-code/rootfs-skeleton/usr/sbin/fixdesk
+++ b/woof-code/rootfs-skeleton/usr/sbin/fixdesk
@@ -1,11 +1,11 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler, Feb 2012 bkhome.org
-#licence GPL3 (refer /usr/share/doc/legal)
-#this script has been created to translate English <-> Non-English certain files that are related to the desktop in some way.
-#the files to be translated, and the translations, are defined in /usr/share/sss/desk_strings/
-#note, the translations in /usr/share/sss are managed by MoManager (see Utility menu).
-#fixdesk has to be called whenever the locale is changed.
-#note, the SSS domain 'menu_strings' (/usr/share/sss/menu_strings) is read by /usr/sbin/fixmenus.
+#Licence GPL3 (refer /usr/share/doc/legal)
+# This script has been created to translate English <-> Non-English certain files that are related to the desktop in some way.
+# The files to be translated, and the translations, are defined in /usr/share/sss/desk_strings/
+# Note, the translations in /usr/share/sss are managed by MoManager (see Utility menu).
+# fixdesk has to be called whenever the locale is changed.
+# Note, the SSS domain 'menu_strings' (/usr/share/sss/menu_strings) is read by /usr/sbin/fixmenus.
 #120209 first release.
 #120209 this script now called from /usr/sbin/quicksetup, whenever locale is changed.
 #120209 convert this script into generic handler of sss-domains, allow symlinks (ex: fixscripts now a symlink to fixdesk).
@@ -20,6 +20,29 @@
 #you can run "fixdesk en" or "fixdesk de" in a terminal to convert the target files to en or de
 #(or other language). this is convenient for testing your translations.
 
+_TITLE_=fixdesk
+_COMMENT_="DLI to translate files in /usr/share/sss/SSSFILE/SSSFILE ."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=LANG
+ADD_PARAMETERS="Language : short ie. de, fr .."
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 SSSDOMAIN="desk_strings"    #this was it prior to 120209.
 SSSSCRIPT=$(basename $0)    #but now can have symlinks to fixdesk. ex: fixscripts
 case $SSSSCRIPT in
@@ -27,15 +50,19 @@ case $SSSSCRIPT in
  fixscripts) SSSDOMAIN="script_strings" ;;
  *)          SSSDOMAIN="$SSSSCRIPT" ;;  #for the future.
 esac
+
 SSSFILE="${SSSDOMAIN}"      #filenames are same as the domain ex: /usr/share/sss/script_strings/script_strings.de
+
 mkdir -p /tmp/momanager
 mkdir -p /var/local/sss
+
 . /etc/rc.d/PUPSTATE
 
 if [ "$LANG" = "C" ];then #in case caller script did this.
  LANG="`grep '^LANG=' /etc/profile | cut -f 2 -d '=' | cut -f 1 -d ' '`"
  export LANG
 fi
+
 LANG1="`echo -n $LANG | cut -f 1 -d '_'`"  #ex: de
 [ ! -f /usr/share/sss/${SSSDOMAIN}/${SSSDOMAIN}.$LANG1 ] && LANG1='en' #sanity check. if translation sss-file not exist, change files back to english.
 #this script may be called from /usr/sbin/momanager, with passed param...
