woof-code/rootfs-skeleton/usr/sbin/framebufferwizard: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/framebufferwizard b/woof-code/rootfs-skeleton/usr/sbin/framebufferwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/framebufferwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/framebufferwizard
@@ -1,12 +1,34 @@
 #!/bin/sh
 #(c) Copyright 2005 Barry Kauler www.goosee.com/puppy
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
-#pup up to 1.0.3 only used Xvesa Kdrive server.
-#v1.0.4 introduces framebuffer Xfbdev Kdriver server, choice
-#at first bootup.
+# Puppy up to 1.0.3 only used Xvesa Kdrive server.
+#v1.0.4 introduces framebuffer Xfbdev Kdriver server, choice at first bootup.
+
+_TITLE_=framebufferwizard
+_COMMENT_="CLI to set X11 kdrive server."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 ###KRG>>>>
-FINDX=`find /usr/bin /usr/X11/bin -type l -name 'X' -o -type f -name 'X' | tr '\n' ' '` 
+FINDX=`find /usr/bin /usr/X11/bin -type l -name 'X' -o -type f -name 'X' | tr '\n' ' '`
 for i in $FINDX ; do
 if [ -z "`ls -l $i | grep '\->'`" ] ; then
 echo -e "\\033[0;31m""Warning : There seems to be anything other
@@ -21,13 +43,13 @@ FBSERVERS=`find /usr/bin /usr/X11/bin -type f -name "X*" | grep -v 'Xorg'`
 LIST=''
 for i in $FBSERVERS ; do
 LIST="$LIST
-$i \"`basename $i`\"" 
+$i \"`basename $i`\""
 done
 LIST=`echo "$LIST" | sort --key=2 --field-separator=" " | sed '/^$/d' | tr '\n' ' '`
 DIAL="dialog --title \"Xframebuffer Server Wizard\" --menu \"Choose the Xserver
 from this list .
 It uses a simple find 'X*' , so please make sure you
-don't choose anything other , than Xservers.\" 0 0 0 $LIST" 
+don't choose anything other , than Xservers.\" 0 0 0 $LIST"
 eval $DIAL 2>/tmp/Xframebufferserver.choice
 if [ $? -eq 0 ];then
 XSERVER=`cat /tmp/Xframebufferserver.choice`
@@ -314,10 +336,10 @@ NEWCHOICES="`echo -n "$VIDEOCHOICES" | grep -v "$FBMODE" | tr "\n" "V" | sed -e 
 OLDCHOICE=""
 if [ "$FBMODE" ];then
  if [ "`echo -n "$VIDEOCHOICES" | grep "$FBMODE"`" = "" ];then
-  OLDCHOICE="${FBMODE}_unknown on 
+  OLDCHOICE="${FBMODE}_unknown on
 "
  else
-  OLDCHOICE="${FBMODE}_supported on 
+  OLDCHOICE="${FBMODE}_supported on
 "
  fi
 
