woof-code/rootfs-skeleton/usr/sbin/get_bluetooth_connection: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/get_bluetooth_connection b/woof-code/rootfs-skeleton/usr/sbin/get_bluetooth_connection
--- a/woof-code/rootfs-skeleton/usr/sbin/get_bluetooth_connection
+++ b/woof-code/rootfs-skeleton/usr/sbin/get_bluetooth_connection
@@ -11,6 +11,30 @@
 # OBEX IrMC Sync Server
 #Optional argument: device RFCOMM*, the current device, in case multiple instances found.
 
+_TITLE_=get_bluetooth_connection
+_COMMENT_="CLI to determine BT network."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST="BTSVCNAME|CURRENTDEV"
+ADD_PARAMETERS="BT server name: DUN, FTP, HF, HS, OBEX, OPUSH, SP
+Current device: optional ie. /dev/rfcomm0"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 which rfcomm >/dev/null || exit 1
 which sdptool >/dev/null || exit 1
 BTSVCNAME="$1"
@@ -57,7 +81,7 @@ exit 1
      while ! pup_event_backend_modprobe_protect --bluetooth_rfcomm_number=$RFCOMMNUM;do
       RFCOMMNUM=`expr $RFCOMMNUM + 1`
       [ $RFCOMMNUM -gt 10 ] && exit 1
-     done 
+     done
     fi
     [ ! -e /dev/rfcomm$RFCOMMNUM ] \
      && mknod /dev/rfcomm$RFCOMMNUM c 216 $RFCOMMNUM
