woof-code/rootfs-skeleton/usr/sbin/gparted_shell: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/gparted_shell b/woof-code/rootfs-skeleton/usr/sbin/gparted_shell
--- a/woof-code/rootfs-skeleton/usr/sbin/gparted_shell
+++ b/woof-code/rootfs-skeleton/usr/sbin/gparted_shell
@@ -5,6 +5,29 @@
 #v424 update desktop drive icons. note, this is also done in /usr/sbin/bootflash, puppyinstaller.
 #v424 report that gparted crash with a non-english locale.
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 #v424 report that gparted crash with a non-english locale. well, maybe just do this...
 export LANG=C
 
@@ -24,7 +47,7 @@ do
 done
 
  echo "<radiobutton><label>ALL DRIVES. Scan all drives at startup</label><variable>RADIO_all</variable></radiobutton>" >> /tmp/gparted_shell_probe
- 
+
 DRVTAGS="`cat /tmp/gparted_shell_probe`"
 
 export MAIN_DIALOG="
@@ -32,9 +55,9 @@ export MAIN_DIALOG="
  <vbox>
   <text><label>Welcome, Gparted is an application to examine and modify partitions in a disk drive. At startup, the default behaviour is for Gparted to scan for all drives in the computer, and on some computers this can take a very long time. Therefore, this dialog window enables you to make a choice of which drive you want to work on (and Gparted will only scan that drive at startup).</label></text>
   <text><label>WARNING: A PC may have a single VFAT or NTFS partition, with Windows installed, and you might want to decrease the size of that partition so as to be able to create a Linux partition. For Windows XP/98/95 this is usually ok (but be careful not to make it too small, say 5GB for XP). However, Vista gets very upset if the partition is resized and may not work properly afterward (in some cases won't even start) -- there may be a fix for this, but we don't know what it is.</label></text>
-  
+
   ${DRVTAGS}
-  
+
   <hbox>
    <button>
     <label>OKAY</label>
