grub-install : Bulk Maintanance Replacement of today.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/grub-install b/woof-code/rootfs-skeleton/usr/sbin/grub-install
--- a/woof-code/rootfs-skeleton/usr/sbin/grub-install
+++ b/woof-code/rootfs-skeleton/usr/sbin/grub-install
@@ -83,46 +83,46 @@ EOF
 
 # Usage: getraid_mdadm mddevice
 # Routine to find a physical device from an md device
-# If found, the first grub BIOS device (from device.map) is returned 
+# If found, the first grub BIOS device (from device.map) is returned
 # If no BIOS drives match the RAID devices, the first device returned
 # from mdadm -D is returned
 getraid_mdadm() {
-	device=$1
-	mdadm=$(mdadm -D "$device") || {
-		echo "$PROG: mdadm -D $device failed" >&2
-		exit 1
-	}
-	eval "$(
-		echo "$mdadm" | awk '
-			$1 == "Number" && $2 == "Major" { start = 1; next }
-			$1 == "UUID" { print "uuid=" $3; start = 0; next }
-			!start { next }
-			$2 == 0 && $3 == 0 { next }
-			{ devices = devices "\n" $NF }
-			END { print "devices='\''" devices "'\''" }
-		'
-	)"
+        device=$1
+        mdadm=$(mdadm -D "$device") || {
+                echo "$PROG: mdadm -D $device failed" >&2
+                exit 1
+        }
+        eval "$(
+                echo "$mdadm" | awk '
+                        $1 == "Number" && $2 == "Major" { start = 1; next }
+                        $1 == "UUID" { print "uuid=" $3; start = 0; next }
+                        !start { next }
+                        $2 == 0 && $3 == 0 { next }
+                        { devices = devices "\n" $NF }
+                        END { print "devices='\''" devices "'\''" }
+                '
+        )"
 
-	# Convert RAID devices list into a list of disks
-	tmp_disks=`echo "$devices" | sed -e 's%\([vsh]d[a-z]\)[0-9]*$%\1%' \
-					 -e 's%\(d[0-9]*\)p[0-9]*$%\1%' \
-					 -e 's%\(fd[0-9]*\)$%\1%' \
-					 -e 's%/part[0-9]*$%/disc%' \
-					 -e 's%\(c[0-7]d[0-9]*\).*$%\1%' \
-					 -e '/^$/d' |
-				     sed -n '1h;2,$H;${g;s/\n/|/g;p}'`
+        # Convert RAID devices list into a list of disks
+        tmp_disks=`echo "$devices" | sed -e 's%\([vsh]d[a-z]\)[0-9]*$%\1%' \
+                                         -e 's%\(d[0-9]*\)p[0-9]*$%\1%' \
+                                         -e 's%\(fd[0-9]*\)$%\1%' \
+                                         -e 's%/part[0-9]*$%/disc%' \
+                                         -e 's%\(c[0-7]d[0-9]*\).*$%\1%' \
+                                         -e '/^$/d' |
+                                     sed -n '1h;2,$H;${g;s/\n/|/g;p}'`
 
-	# Find first BIOS disk that's a member of the RAID array
-	# Default to first RAID member if no tmp_disks are BIOS devices
-	set -- `egrep $tmp_disks $device_map | \
-		sort | \
-		sed -n 1p `
-	device=${2:-${tmp_disks%%|*}}
+        # Find first BIOS disk that's a member of the RAID array
+        # Default to first RAID member if no tmp_disks are BIOS devices
+        set -- `egrep $tmp_disks $device_map | \
+                sort | \
+                sed -n 1p `
+        device=${2:-${tmp_disks%%|*}}
 
-	# Return first partition on BIOS disk that's part of the RAID
-	echo "$devices" | \
-		sed -n "\:${device}:p" | \
-		sed -n 1p
+        # Return first partition on BIOS disk that's part of the RAID
+        echo "$devices" | \
+                sed -n "\:${device}:p" | \
+                sed -n 1p
 }
 
 # Usage: convert os_device
@@ -131,140 +131,140 @@ getraid_mdadm() {
 convert () {
     # First, check if the device file exists.
     if test -e "$1"; then
-	:
+        :
     else
-	echo "$1: Not found or not a block device." 1>&2
-	exit 1
+        echo "$1: Not found or not a block device." 1>&2
+        exit 1
     fi
 
     # Break the device name into the disk part and the partition part.
     case "$host_os" in
     linux*)
-	# Find an actual physical device if we're passed a RAID device
-	case $1 in
-		/dev/md*)  set -- `getraid_mdadm $1`
-	esac
-	tmp_disk=`echo "$1" | sed -e 's%\([vsh]d[a-z]\)[0-9]*$%\1%' \
-				  -e 's%\(d[0-9]*\)p[0-9]*$%\1%' \
-				  -e 's%\(fd[0-9]*\)$%\1%' \
-				  -e 's%/part[0-9]*$%/disc%' \
-				  -e 's%\(c[0-7]d[0-9]*\).*$%\1%' \
-				  -e 's%\(e[0-9]\.[0-9]*\).*$%\1%'`
-	tmp_part=`echo "$1" | sed -e 's%.*/[vsh]d[a-z]\([0-9]*\)$%\1%' \
-				  -e 's%.*d[0-9]*p%%' \
-				  -e 's%.*/fd[0-9]*$%%' \
-				  -e 's%.*/floppy/[0-9]*$%%' \
-				  -e 's%.*/\(disc\|part\([0-9]*\)\)$%\2%' \
-				  -e 's%.*c[0-7]d[0-9]*p*%%' \
-				  -e 's%.*e[0-9]\.[0-9]*p%%' \
-				  -e 's%.*e[0-9]\.[0-9]*\$%%'`
-	;;
+        # Find an actual physical device if we're passed a RAID device
+        case $1 in
+                /dev/md*)  set -- `getraid_mdadm $1`
+        esac
+        tmp_disk=`echo "$1" | sed -e 's%\([vsh]d[a-z]\)[0-9]*$%\1%' \
+                                  -e 's%\(d[0-9]*\)p[0-9]*$%\1%' \
+                                  -e 's%\(fd[0-9]*\)$%\1%' \
+                                  -e 's%/part[0-9]*$%/disc%' \
+                                  -e 's%\(c[0-7]d[0-9]*\).*$%\1%' \
+                                  -e 's%\(e[0-9]\.[0-9]*\).*$%\1%'`
+        tmp_part=`echo "$1" | sed -e 's%.*/[vsh]d[a-z]\([0-9]*\)$%\1%' \
+                                  -e 's%.*d[0-9]*p%%' \
+                                  -e 's%.*/fd[0-9]*$%%' \
+                                  -e 's%.*/floppy/[0-9]*$%%' \
+                                  -e 's%.*/\(disc\|part\([0-9]*\)\)$%\2%' \
+                                  -e 's%.*c[0-7]d[0-9]*p*%%' \
+                                  -e 's%.*e[0-9]\.[0-9]*p%%' \
+                                  -e 's%.*e[0-9]\.[0-9]*\$%%'`
+        ;;
     gnu*)
-	tmp_disk=`echo "$1" | sed 's%\([vsh]d[0-9]*\).*%\1%'`
-	tmp_part=`echo "$1" | sed "s%$tmp_disk%%"` ;;
+        tmp_disk=`echo "$1" | sed 's%\([vsh]d[0-9]*\).*%\1%'`
+        tmp_part=`echo "$1" | sed "s%$tmp_disk%%"` ;;
     freebsd* | kfreebsd*-gnu)
-	tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([saw]d[0-9]*\).*$%\1%' \
-			    | sed 's%r\{0,1\}\(da[0-9]*\).*$%\1%'`
-	tmp_part=`echo "$1" \
-	    | sed "s%.*/r\{0,1\}[saw]d[0-9]\(s[0-9]*[a-h]\)%\1%" \
-       	    | sed "s%.*/r\{0,1\}da[0-9]\(s[0-9]*[a-h]\)%\1%"`
-	;;
+        tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([saw]d[0-9]*\).*$%\1%' \
+                            | sed 's%r\{0,1\}\(da[0-9]*\).*$%\1%'`
+        tmp_part=`echo "$1" \
+            | sed "s%.*/r\{0,1\}[saw]d[0-9]\(s[0-9]*[a-h]\)%\1%" \
+            | sed "s%.*/r\{0,1\}da[0-9]\(s[0-9]*[a-h]\)%\1%"`
+        ;;
     netbsd* | knetbsd*-gnu)
-	tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([sw]d[0-9]*\).*$%r\1d%' \
-	    | sed 's%r\{0,1\}\(fd[0-9]*\).*$%r\1a%'`
-	tmp_part=`echo "$1" \
-	    | sed "s%.*/r\{0,1\}[sw]d[0-9]\([abe-p]\)%\1%"`
-	;;
+        tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([sw]d[0-9]*\).*$%r\1d%' \
+            | sed 's%r\{0,1\}\(fd[0-9]*\).*$%r\1a%'`
+        tmp_part=`echo "$1" \
+            | sed "s%.*/r\{0,1\}[sw]d[0-9]\([abe-p]\)%\1%"`
+        ;;
     *)
-	echo "grub-install does not support your OS yet." 1>&2
-	exit 1 ;;
+        echo "grub-install does not support your OS yet." 1>&2
+        exit 1 ;;
     esac
 
     # Get the drive name.
     tmp_drive=`grep -v '^#' $device_map | grep "$tmp_disk *$" \
-	| sed 's%.*\(([hf]d[0-9][a-z0-9,]*)\).*%\1%'`
+        | sed 's%.*\(([hf]d[0-9][a-z0-9,]*)\).*%\1%'`
 
     # If not found, print an error message and exit.
     if test "x$tmp_drive" = x; then
-	echo "$1 does not have any corresponding BIOS drive." 1>&2
-	# If /boot is on a RAID device, provide more information
-	if mdadm --detail "$bootdir_device" >/dev/null 2>&1; then
-	    echo "You can run grub-install on your RAID device [$bootdir_device]," 1>&2
-	    echo "or you can define [$1] in [$device_map]." 1>&2
-	fi
-	exit 1
+        echo "$1 does not have any corresponding BIOS drive." 1>&2
+        # If /boot is on a RAID device, provide more information
+        if mdadm --detail "$bootdir_device" >/dev/null 2>&1; then
+            echo "You can run grub-install on your RAID device [$bootdir_device]," 1>&2
+            echo "or you can define [$1] in [$device_map]." 1>&2
+        fi
+        exit 1
     fi
 
     if test "x$tmp_part" != x; then
-	# If a partition is specified, we need to translate it into the
-	# GRUB's syntax.
-	case "$host_os" in
-	linux*)
-	    echo "$tmp_drive" | sed "s%)$%,`expr $tmp_part - 1`)%" ;;
-	gnu*)
-	    if echo $tmp_part | grep "^s" >/dev/null; then
-		tmp_pc_slice=`echo $tmp_part \
-		    | sed "s%s\([0-9]*\)[a-z]*$%\1%"`
-		tmp_drive=`echo "$tmp_drive" \
-		    | sed "s%)%,\`expr "$tmp_pc_slice" - 1\`)%"`
-	    fi
-	    if echo $tmp_part | grep "[a-z]$" >/dev/null; then
-		tmp_bsd_partition=`echo "$tmp_part" \
-		    | sed "s%[^a-z]*\([a-z]\)$%\1%"`
-		tmp_drive=`echo "$tmp_drive" \
-		    | sed "s%)%,$tmp_bsd_partition)%"`
-	    fi
-	    echo "$tmp_drive" ;;
-	freebsd* | kfreebsd*-gnu)
-	    if echo $tmp_part | grep "^s" >/dev/null; then
-		tmp_pc_slice=`echo $tmp_part \
-		    | sed "s%s\([0-9]*\)[a-h]*$%\1%"`
-		tmp_drive=`echo "$tmp_drive" \
-		    | sed "s%)%,\`expr "$tmp_pc_slice" - 1\`)%"`
-	    fi
-	    if echo $tmp_part | grep "[a-h]$" >/dev/null; then
-		tmp_bsd_partition=`echo "$tmp_part" \
-		    | sed "s%s\{0,1\}[0-9]*\([a-h]\)$%\1%"`
-		tmp_drive=`echo "$tmp_drive" \
-		    | sed "s%)%,$tmp_bsd_partition)%"`
-	    fi
-	    echo "$tmp_drive" ;;
-	netbsd* | knetbsd*-gnu)
-	    if echo $tmp_part | grep "^[abe-p]$" >/dev/null; then
-		tmp_bsd_partition=`echo "$tmp_part" \
-		    | sed "s%\([a-p]\)$%\1%"`
-		tmp_drive=`echo "$tmp_drive" \
-		    | sed "s%)%,$tmp_bsd_partition)%"`
-	    fi
-	    echo "$tmp_drive" ;;
-	esac
+        # If a partition is specified, we need to translate it into the
+        # GRUB's syntax.
+        case "$host_os" in
+        linux*)
+            echo "$tmp_drive" | sed "s%)$%,`expr $tmp_part - 1`)%" ;;
+        gnu*)
+            if echo $tmp_part | grep "^s" >/dev/null; then
+                tmp_pc_slice=`echo $tmp_part \
+                    | sed "s%s\([0-9]*\)[a-z]*$%\1%"`
+                tmp_drive=`echo "$tmp_drive" \
+                    | sed "s%)%,\`expr "$tmp_pc_slice" - 1\`)%"`
+            fi
+            if echo $tmp_part | grep "[a-z]$" >/dev/null; then
+                tmp_bsd_partition=`echo "$tmp_part" \
+                    | sed "s%[^a-z]*\([a-z]\)$%\1%"`
+                tmp_drive=`echo "$tmp_drive" \
+                    | sed "s%)%,$tmp_bsd_partition)%"`
+            fi
+            echo "$tmp_drive" ;;
+        freebsd* | kfreebsd*-gnu)
+            if echo $tmp_part | grep "^s" >/dev/null; then
+                tmp_pc_slice=`echo $tmp_part \
+                    | sed "s%s\([0-9]*\)[a-h]*$%\1%"`
+                tmp_drive=`echo "$tmp_drive" \
+                    | sed "s%)%,\`expr "$tmp_pc_slice" - 1\`)%"`
+            fi
+            if echo $tmp_part | grep "[a-h]$" >/dev/null; then
+                tmp_bsd_partition=`echo "$tmp_part" \
+                    | sed "s%s\{0,1\}[0-9]*\([a-h]\)$%\1%"`
+                tmp_drive=`echo "$tmp_drive" \
+                    | sed "s%)%,$tmp_bsd_partition)%"`
+            fi
+            echo "$tmp_drive" ;;
+        netbsd* | knetbsd*-gnu)
+            if echo $tmp_part | grep "^[abe-p]$" >/dev/null; then
+                tmp_bsd_partition=`echo "$tmp_part" \
+                    | sed "s%\([a-p]\)$%\1%"`
+                tmp_drive=`echo "$tmp_drive" \
+                    | sed "s%)%,$tmp_bsd_partition)%"`
+            fi
+            echo "$tmp_drive" ;;
+        esac
     else
-	# If no partition is specified, just print the drive name.
-	echo "$tmp_drive"
+        # If no partition is specified, just print the drive name.
+        echo "$tmp_drive"
     fi
 }
 
 # Usage: resolve_symlink file
 # Find the real file/device that file points at
 resolve_symlink () {
-	tmp_fname=$1
-	# Resolve symlinks
-	while test -L $tmp_fname; do
-		tmp_new_fname=`ls -al $tmp_fname | sed -n 's%.*-> \(.*\)%\1%p'`
-		if test -z "$tmp_new_fname"; then
-			echo "Unrecognized ls output" 2>&1
-			exit 1
-		fi
+        tmp_fname=$1
+        # Resolve symlinks
+        while test -L $tmp_fname; do
+                tmp_new_fname=`ls -al $tmp_fname | sed -n 's%.*-> \(.*\)%\1%p'`
+                if test -z "$tmp_new_fname"; then
+                        echo "Unrecognized ls output" 2>&1
+                        exit 1
+                fi
 
-		# Convert relative symlinks
-		case $tmp_new_fname in
-			/*) tmp_fname="$tmp_new_fname"
-			;;
-			*) tmp_fname="`echo $tmp_fname | sed 's%/[^/]*$%%'`/$tmp_new_fname"
-			;;
-		esac
-	done
-	echo "$tmp_fname"
+                # Convert relative symlinks
+                case $tmp_new_fname in
+                        /*) tmp_fname="$tmp_new_fname"
+                        ;;
+                        *) tmp_fname="`echo $tmp_fname | sed 's%/[^/]*$%%'`/$tmp_new_fname"
+                        ;;
+                esac
+        done
+        echo "$tmp_fname"
 }
 
 # Usage: find_device file
@@ -272,14 +272,14 @@ resolve_symlink () {
 find_device () {
     # For now, this uses the program `df' to get the device name, but is
     # this really portable?
-    tmp_fname=`df $1/ | sed -n 's%.*\(/dev/[^ 	]*\).*%\1%p'`
+    tmp_fname=`df $1/ | sed -n 's%.*\(/dev/[^   ]*\).*%\1%p'`
 
     if test -z "$tmp_fname"; then
-	echo "Could not find device for $1" 2>&1
-	exit 1
+        echo "Could not find device for $1" 2>&1
+        exit 1
     fi
 
-	tmp_fname=`resolve_symlink $tmp_fname`
+        tmp_fname=`resolve_symlink $tmp_fname`
 
     echo "$tmp_fname"
 }
@@ -288,36 +288,36 @@ find_device () {
 for option in "$@"; do
     case "$option" in
     -h | --help)
-	usage
-	exit 0 ;;
+        usage
+        exit 0 ;;
     -v | --version)
-	echo "grub-install (GNU GRUB ${VERSION})"
-	exit 0 ;;
+        echo "grub-install (GNU GRUB ${VERSION})"
+        exit 0 ;;
     --root-directory=*)
-	rootdir=`echo "$option" | sed 's/--root-directory=//'` ;;
+        rootdir=`echo "$option" | sed 's/--root-directory=//'` ;;
     --grub-shell=*)
-	grub_shell=`echo "$option" | sed 's/--grub-shell=//'` ;;
+        grub_shell=`echo "$option" | sed 's/--grub-shell=//'` ;;
     --no-floppy)
-	no_floppy="--no-floppy" ;;
+        no_floppy="--no-floppy" ;;
     --force-lba)
-	force_lba="--force-lba" ;;
+        force_lba="--force-lba" ;;
     --recheck)
-	recheck=yes ;;
+        recheck=yes ;;
     # This is an undocumented feature...
     --debug)
-	debug=yes ;;
+        debug=yes ;;
     -*)
-	echo "Unrecognized option \`$option'" 1>&2
-	usage
-	exit 1
-	;;
+        echo "Unrecognized option \`$option'" 1>&2
+        usage
+        exit 1
+        ;;
     *)
-	if test "x$install_device" != x; then
-	    echo "More than one install_devices?" 1>&2
-	    usage
-	    exit 1
-	fi
-	install_device="${option}" ;;
+        if test "x$install_device" != x; then
+            echo "More than one install_devices?" 1>&2
+            usage
+            exit 1
+        fi
+        install_device="${option}" ;;
     esac
 done
 
@@ -395,13 +395,13 @@ else
     # Before all invocations of the grub shell, call sync to make sure
     # the raw device is in sync with any bufferring in filesystems.
     sync
- 
+
     $grub_shell --batch $no_floppy --device-map=$device_map <<EOF >$log_file
 quit
 EOF
     if grep "Error [0-9]*: " $log_file >/dev/null; then
-	cat $log_file 1>&2
-	exit 1
+        cat $log_file 1>&2
+        exit 1
     fi
 
     rm -f $log_file
@@ -427,7 +427,7 @@ case "$install_device" in
     # I don't know why, but some shells wouldn't die if exit is
     # called in a function.
     if test "x$install_drive" = x; then
-	exit 1
+        exit 1
     fi ;;
 \([hf]d[0-9]*\))
     install_drive="$install_device" ;;
@@ -487,31 +487,33 @@ test -n "$mklog" && log_file=`$mklog`
 sync
 
 # On XFS, sync() is not enough.
-if [ `grub-probe -t fs ${grubdir}` = "xfs" ] ; then
+if test "`which grub-probe`"; then
+if [ "`grub-probe -t fs ${grubdir}`" = "xfs" ] ; then
   xfs_freeze -f ${grubdir} && xfs_freeze -u ${grubdir}
   # We don't have set -e.  If xfs_freeze failed, it's worth trying anyway,
   # maybe we're lucky.
+fi
 fi
 
 for file in ${grubdir}/stage1 ${grubdir}/stage2 ${grubdir}/*stage1_5; do
     count=5
     tmp=`echo $file | sed "s|^${grubdir}|${grub_prefix}|"`
     while test $count -gt 0; do
-	$grub_shell --batch $no_floppy --device-map=$device_map <<EOF >$log_file
+        $grub_shell --batch $no_floppy --device-map=$device_map <<EOF >$log_file
 dump ${root_drive}${tmp} ${img_file}
 quit
 EOF
-	if grep "Error [0-9]*: " $log_file >/dev/null; then
-	    :
-	elif cmp $file $img_file >/dev/null; then
-	    break
-	fi
-	sleep 1
-	count=`expr $count - 1`    
+        if grep "Error [0-9]*: " $log_file >/dev/null; then
+            :
+        elif cmp $file $img_file >/dev/null; then
+            break
+        fi
+        sleep 1
+        count=`expr $count - 1`
     done
     if test $count -eq 0; then
-	echo "The file $file not read correctly." 1>&2
-	exit 1
+        echo "The file $file not read correctly." 1>&2
+        exit 1
     fi
 done
 
@@ -527,28 +529,28 @@ sync
 
 # Now perform the installation.
 if echo "$install_device" | grep -qs "^/dev/md[0-9]" 2>/dev/null; then
-	# installing to an md device; write an MBR to each disk in the RAID
-	echo -n > $log_file
-	for disk in $(mdadm --detail "$install_device" 2>/dev/null | \
-			grep " active sync " 2>/dev/null | \
-			sed "s/^.* active sync\s*//" 2>/dev/null \
-	); do
-		dev=$(echo "$disk" | sed "s/[0-9]\+$//")
-		bootpart=${disk#$dev}
-		grubroot=$(($bootpart-1))
-		hddev=$(echo "$install_drive" | sed "s/[()]//g" | sed "s/,.*//")
-		echo "Installing GRUB to $dev as ($hddev,$grubroot)..."
-		$grub_shell --device-map=/dev/null <<EOF >>$log_file
+        # installing to an md device; write an MBR to each disk in the RAID
+        echo -n > $log_file
+        for disk in $(mdadm --detail "$install_device" 2>/dev/null | \
+                        grep " active sync " 2>/dev/null | \
+                        sed "s/^.* active sync\s*//" 2>/dev/null \
+        ); do
+                dev=$(echo "$disk" | sed "s/[0-9]\+$//")
+                bootpart=${disk#$dev}
+                grubroot=$(($bootpart-1))
+                hddev=$(echo "$install_drive" | sed "s/[()]//g" | sed "s/,.*//")
+                echo "Installing GRUB to $dev as ($hddev,$grubroot)..."
+                $grub_shell --device-map=/dev/null <<EOF >>$log_file
 device ($hddev) $dev
 root ($hddev,$grubroot)
 setup $force_lba --stage2=$grubdir/stage2 --prefix=$grub_prefix ($hddev)
 quit
 EOF
-	done
+        done
 else
-	# traditional case, normal grub installation
-	echo "Installing GRUB to $install_device as $install_drive..."
-	$grub_shell --batch $no_floppy --device-map=$device_map <<EOF >$log_file
+        # traditional case, normal grub installation
+        echo "Installing GRUB to $install_device as $install_drive..."
+        $grub_shell --batch $no_floppy --device-map=$device_map <<EOF >$log_file
 root $root_drive
 setup $force_lba --stage2=$grubdir/stage2 --prefix=$grub_prefix $install_drive
 quit
