woof-code/rootfs-skeleton/usr/sbin/grubconfig: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/grubconfig b/woof-code/rootfs-skeleton/usr/sbin/grubconfig
--- a/woof-code/rootfs-skeleton/usr/sbin/grubconfig
+++ b/woof-code/rootfs-skeleton/usr/sbin/grubconfig
@@ -3,6 +3,29 @@
 #v423 kirk: add ext4 support.
 #v424 BK: bugfixes. fix accidental wiping partition!
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 #BK...
 export XDIALOG_HIGH_DIALOG_COMPAT=true
 #all incidents of 'dialog' replaced by 'Xdialog' below...
@@ -222,7 +245,7 @@ If you have more than one hard drive, and want GRUB installed
 to the MBR of another hard drive, put the device below or
 leave the box blank for '$mbr_dev'.
 EOF
- 
+
    #    $DIALOG --title "HARD DRIVE MBR" --inputbox "`cat $TMP/tmpmsg`" 0 68 2> $TMP/mbr_dev
    kill $INFOPID 2>/dev/null
    $DIALOG --title "Grubconfig: HARD DRIVE MBR" --inputbox "`cat $TMP/tmpmsg`" 0 0 2> $TMP/mbr_dev
@@ -233,16 +256,16 @@ EOF
     echo
     echo "Cancelled!"
     exit
-   fi 
+   fi
    MBR_DEV="`cat $TMP/mbr_dev`"
    ombr_dev="$mbr_dev" #BK
    if [ -n $MBR_DEV ]; then
     mbr_dev="$MBR_DEV"
    fi
-   
+
    #BK bug above, dunno why...
    [ "$mbr_dev" = "" ] && mbr_dev="$ombr_dev"
-      
+
    #BK if probe $mbr_dev; then
    if [ ! "`probepart | grep "$mbr_dev"`" = "" ];then
     break
@@ -318,7 +341,7 @@ hd="`cat $TMP/hd_grub`"
 other() {
  D=`echo "$@" | cut -d ' ' -f 1`
  get_root_dev $D
- 
+
 if echo "$@" | grep -q HURD ; then
 grub --no-floppy --batch << EOF 1>$TMP/find_file 2>$TMP/null
 find ($hd,$p2)/boot/gnumach.gz
@@ -340,7 +363,7 @@ elif echo "$@" | grep -q BSD ; then
 if echo "$@" | grep -q FreeBSD ; then
 OTHER="root ($hd,$p2,a)
   kernel /boot/loader"
-else  
+else
 OTHER="rootnoverify ($hd,$p2)
   chainloader +1"
 fi
@@ -436,7 +459,7 @@ Which option would you like? (Cancel button to exit script)" \
  fi
  TG="`cat $TMP/reply`"
 fi
- 
+
  if [ "$TG" = "MBR" ]; then
   hd_mbr
   MBR=YES
@@ -454,7 +477,7 @@ fi
      sleep 3
 
  # Search for Linux partitions:
- grep "83  Linux" $TMP/DEV | while read PART ; do 
+ grep "83  Linux" $TMP/DEV | while read PART ; do
  if [ ! "$PART" = "" ]; then
   LNXP="`echo $PART | cut -f 1 -d ' '`"
   p1=`echo $LNXP | cut -b9-`
@@ -466,7 +489,7 @@ fi
 
   title="Linux (on $LNXP)"
 
-  num="`echo $LNXP | cut -b8-`" 
+  num="`echo $LNXP | cut -b8-`"
 
   cat << EOF > $TMP/part.$num.sort
 # Linux bootable partition config begins
@@ -514,7 +537,7 @@ grep -v "Ext'd" | grep -v "Extend" | grep -v -i "swap" | while read PART ; do
   LABEL="`cat $TMP/label`"
   fi
 
-  num="`echo $DOSP | cut -b8-`" 
+  num="`echo $DOSP | cut -b8-`"
 
   cat << EOF > $TMP/part.$num.sort
 # Other bootable partition config begins
@@ -528,18 +551,18 @@ done
  chmod 644 $BOOT/grub/$grub_config
  message=yes
  installcolor;
- 
+
 #  # BK v2.02...
 #  if [ "$LOOPBRK" = "yes" ];then
    umount $BOOT_TMP 2>$TMP/null && rmdir $BOOT_TMP
    rm -rf $TMP
-#   break 
+#   break
 #  fi
 # done #BIGWHILELOOP BK
  #something wrong with trying to have a while loop here.
  #instead, a flag to rerun grubconfig...
  echo -n "$LOOPBRK" > /tmp/loopbrk.txt
- 
+
 } #end simplegrub func.
 
 find_kernel() {
@@ -644,15 +667,15 @@ you want to the line 'hdd=scsi' etc. and press enter, then
 
 Examples of the difference between Linux and GRUB device names.
 
-Linux IDE:	GRUB IDE:	Linux SCSI:	GRUB SCSI:
-/dev/hda1       (hd0,0)		/dev/sda1       (hd0,0)
-/dev/hda2       (hd0,1)		/dev/sda2       (hd0,1)
-/dev/hda3       (hd0,2)		/dev/sda1       (hd0,2)
-/dev/hda4       (hd0,3)		/dev/sda2       (hd0,3)
-/dev/hdb1       (hd1,0)		/dev/sdb1       (hd1,0)
-/dev/hdb2       (hd1,1)		/dev/sdb2       (hd1,1)
-/dev/hdb3       (hd1,2)		/dev/sdb1       (hd1,2)
-/dev/hdb4       (hd1,3)		/dev/sdb2       (hd1,3)
+Linux IDE:      GRUB IDE:       Linux SCSI:     GRUB SCSI:
+/dev/hda1       (hd0,0)         /dev/sda1       (hd0,0)
+/dev/hda2       (hd0,1)         /dev/sda2       (hd0,1)
+/dev/hda3       (hd0,2)         /dev/sda1       (hd0,2)
+/dev/hda4       (hd0,3)         /dev/sda2       (hd0,3)
+/dev/hdb1       (hd1,0)         /dev/sdb1       (hd1,0)
+/dev/hdb2       (hd1,1)         /dev/sdb2       (hd1,1)
+/dev/hdb3       (hd1,2)         /dev/sdb1       (hd1,2)
+/dev/hdb4       (hd1,3)         /dev/sdb2       (hd1,3)
 
 These are some examples of how to use GRUB from the command prompt.
 
@@ -730,14 +753,14 @@ quit
 EOF
 SUCCESS=$?
 installed="installed on the MBR of $mbr_dev"
-fi  
+fi
 
       if [ -r $BOOT/grub/$grub_config ]; then
        mv $BOOT/grub/$grub_config $BOOT/grub/$grub_config.old.$$
       fi
 
 if [ ! "$backup_mbr" = "" ]; then
-mbr_backup=`basename $backup_mbr` 
+mbr_backup=`basename $backup_mbr`
  cat << EOF > $BOOT/grub/$grub_config
 # GRUB configuration file '/boot/grub/$grub_config'.
 # generated by 'grubconfig'.  `date +%c 2>$TMP/null`
@@ -811,16 +834,16 @@ fi
    kill $INFOPID 2>/dev/null
    XDIALOG_HIGH_DIALOG_COMPAT=false $DIALOG --title "Grubconfig" --no-buttons --infobox "Installing the GRUB Bootloader..." 0 0 25000 & #5 40
    INFOPID=$!
-   sleep 2 
- 
+   sleep 2
+
    if [ ! "$KILL" = "NO" ]; then
    killall klogd 2>$TMP/null
    sleep 1
    klogd -c 3 2>$TMP/null
    fi
-   
+
    install_grub
- 
+
  if [ ! "$SUCCESS" = "0" ]; then # some GRUB error occured
   if [ ! "$backup_mbr" = "" -a ! "$mbr_dev" = "" ]; then
   if [ -s "$backup_mbr" ]; then
@@ -908,7 +931,7 @@ root_device() {
   if [ -z "$ROOT_DEVICE" -a -s /etc/fstab ]; then
     ROOT_DEVICE="`grep -v "^#" /etc/fstab 2>$TMP/null | grep " / " | awk '{print $1}'`"
   fi
-  
+
   if [ -n "$ROOT_DEVICE" ]; then
   if echo $ROOT_DEVICE | grep -q -E "/dev/ram|/dev/root|tmpfs|rootfs|/dev/loop"; then
     unset ROOT_DEVICE
@@ -919,7 +942,7 @@ root_device() {
   [ "$ROOT_DEVICE" = "none" ] && ROOT_DEVICE=""
   #BK quick hack for v2.16...
   [ "$ROOT_DEVICE" = "unionfs" ] && ROOT_DEVICE=""
-  
+
     if [ -n "$ROOT_DEVICE" ]; then
 cat << EOF > $TMP/tmpmsg
 Where do you want the GRUB files to go?
@@ -960,7 +983,7 @@ do
       rm -rf $TMP
       chroot_umount
       exit
-    fi    
+    fi
       ROOT_DEV=`cat $TMP/root_device`
 
      if [ "$ROOT_DEVICE" = "" -a "$ROOT_DEV" = "" ]; then
@@ -970,31 +993,31 @@ do
      if [ "$ROOT_DEVICE" = "$ROOT_DEV" ]; then
        break
      fi
-    
+
        if [ ! "$ROOT_DEV" = "" ]; then
          ROOT_DEVICE=`cat $TMP/root_device`
        fi
-    
+
         if ! grep "^$ROOT_DEVICE" $TMP/DEV | grep -q "83  Linux" ; then
          kill $INFOPID 2>/dev/null
-	     $DIALOG --title "Grubconfig: ERROR" --msgbox \
+             $DIALOG --title "Grubconfig: ERROR" --msgbox \
           "The partition '$ROOT_DEVICE' is not Linux." 0 0 #5 55
-	  continue
+          continue
         fi
-       
+
        if mount 2>$TMP/null | grep -q "^$ROOT_DEVICE" 2>$TMP/null ; then
            BOOT="`mount 2>$TMP/null | grep $ROOT_DEVICE | cut -d ' ' -f 3`/boot"
          if echo "fooboo" > $BOOT/fooboo 2>$TMP/null ; then
- 	      rm -f $BOOT/fooboo
+              rm -f $BOOT/fooboo
          else
           kill $INFOPID 2>/dev/null
- 	      $DIALOG --title "Grubconfig: ERROR" --msgbox \
+              $DIALOG --title "Grubconfig: ERROR" --msgbox \
            "The partition '$ROOT_DEVICE' is mounted read-only, \
            either unmount it or mount it read-write." 0 0 #6 55
            rm -rf $TMP
            chroot_umount
-	   exit
-	 fi
+           exit
+         fi
            break
        else
        umount $BOOT_TMP 2>$TMP/null
@@ -1018,12 +1041,12 @@ do
     XDIALOG_HIGH_DIALOG_COMPAT=false $DIALOG --title "Grubconfig" --no-buttons --infobox "Working, please wait..." 0 0 25000 & #3 20
     INFOPID=$!
     sleep 1
-    
+
  fs=`mount | grep "^$ROOT_DEVICE" | awk '{print $5}'`
  [ "$fs" = "ext2" -o "$fs" = "ext3" -o "$fs" = "ext4" ] && fs=e2fs #v423 kirk: add ext4. v424 typo.
  [ "$fs" = "msdos" ] && fs=fat
  [ "$fs" = "vfat" ] && fs=fat
- 
+
  if [ -d /usr/share/grub -o -d /usr/lib/grub -o -d /usr/local/share/grub ]; then
  mkdir -p $BOOT/grub
  if [ -d /usr/share/grub ]; then
@@ -1033,7 +1056,7 @@ do
  elif [ -d /usr/lib/grub ]; then
  cp-FULL -p /usr/lib/grub/*/*stage* $BOOT/grub 2>$TMP/null
  fi
- 
+
  for f in stage1 stage2 $fs"_stage1_5"
  do
  if [ ! -f $BOOT/grub/$f ]; then
@@ -1043,7 +1066,7 @@ do
  echo "directory, containing the stage files."
  chroot_umount
  exit 1
- fi 
+ fi
  done
  else
  echo "ERROR: Can't find stage files from the grub package."
@@ -1060,7 +1083,7 @@ HDR="no" # this means the header section of /boot/grub/menu.lst has not yet
 LNX="no" # this means no Linux partition has been defined as bootable
          # through GRUB. Both of these must change to "yes" before GRUB will
          # install from this script.
- 
+
  # OK, now let's see if we should automate things:
  $DIALOG --title "GRUBCONFIG Kent Robotti (modified for Puppy Linux)" --no-collapse --menu \
  "Puppy Linux users: if running this from the Universal Installer,\n\
@@ -1161,7 +1184,7 @@ the "Root" selection. Please pick a target location:" 15 68 3 \
    elif [ "$TG" = "Root" ]; then
     MBR=NO
    elif [ "$TG" = "Floppy" ]; then
-    GRUB_TARGET="/dev/fd0"    
+    GRUB_TARGET="/dev/fd0"
     MBR=NO
    else
     HDR="no"
@@ -1197,7 +1220,7 @@ else
      "No Linux partitions found!" 0 0 #5 35
       continue
 fi
-    
+
     if [ -s $TMP/parts ]; then
       cat $TMP/parts | sed "s/\"//g" | sed "/^$/d" > $TMP/parts.a
     else
@@ -1205,7 +1228,7 @@ fi
      "No Linux partitions chosen!" 0 0 #5 35
       continue
     fi
-        
+
     for PART in `cat $TMP/parts.a` ; do
 
 cat << EOF > $TMP/tmpmsg
@@ -1228,15 +1251,15 @@ EOF
      LABEL="`cat $TMP/reply`"
     if [ "$LABEL" = "" ]; then
      LABEL="Linux"
-    fi    
-    
+    fi
+
   p1=`echo $PART | cut -b 9-`
   p2=$(( $p1 - 1 ))
 
   find_kernel
   get_root_dev $PART
 
-  num="`echo $PART | cut -b8-`" 
+  num="`echo $PART | cut -b8-`"
 
   cat << EOF > $TMP/part.$num.sort
 # Linux bootable partition config begins
@@ -1294,7 +1317,7 @@ fi
       continue
     fi
       rm -f $TMP/tmpmsg*
-    
+
     for PART in `cat $TMP/parts.a` ; do
 cat << EOF > $TMP/tmpmsg
 `echo "   Device Boot      Start         End      Blocks   Id  System"`
@@ -1314,7 +1337,7 @@ EOF
      LABEL="`cat $TMP/reply`"
     if [ "$LABEL" = "" ]; then
      LABEL=Unknown
-    fi    
+    fi
     p1=`echo $PART | cut -b 9-`
     p2=$(( $p1 - 1 ))
 
@@ -1322,7 +1345,7 @@ EOF
 
     other $part
 
-    num="`echo $PART | cut -b8-`" 
+    num="`echo $PART | cut -b8-`"
 
   cat << EOF > $TMP/part.$num.sort
 # Other bootable partition config begins
@@ -1358,7 +1381,7 @@ must do so before installing GRUB." 8 70
    chroot_umount
    break
   elif [ "$REPLY" = "View" ]; then
-  
+
   rm -f $TMP/view.conf
   if ls $TMP/part.*.sort 2>$TMP/null ; then
   for f in `ls $TMP/part.*.sort`
@@ -1366,12 +1389,12 @@ must do so before installing GRUB." 8 70
     cat $f >> $TMP/view.conf
   done
   fi
-  
+
   if [ -f $TMP/initrd.conf ]; then
     cat $TMP/initrd.conf >> $TMP/view.conf
     rm -f $TMP/initrd.conf
   fi
-   
+
    if [ -r $TMP/view.conf ]; then
     kill $INFOPID 2>/dev/null
     $DIALOG --title "YOUR NEW /boot/grub/$grub_config" --textbox "$TMP/view.conf" 22 70
@@ -1403,12 +1426,12 @@ These are the options you can use at the GRUB expert install menu:
    You'll be asked where you want to install GRUB. This
    can be to your Master Boot Record, a Linux partition's
    superblock (for OS/2's Boot Manager etc. to boot), or
-   to a 1.44MB formatted floppy disk. 
-   
+   to a 1.44MB formatted floppy disk.
+
    Try installing to a floppy disk first, if it works
    on the floppy it will probably work on the MBR or
    superblock.
-   
+
    Once you've started a new /boot/grub/$grub_config file, you must
    add at least one OS to it before you can install GRUB.
 
@@ -1416,21 +1439,21 @@ These are the options you can use at the GRUB expert install menu:
    one that will hold the GRUB files in /boot/grub.
 
    You then may want to add other partitions if you have any.
-   
+
 2. Menu choices to add Linux and other DOS/WIN/BSD/OS2/HURD/QNX/
    PLAN9/BEOS/Minix partitions to the /boot/grub/$grub_config
    file.
 
-   These all pretty much work the same way. You'll be asked 
-   which partitions you want to include in the grub menu, and 
+   These all pretty much work the same way. You'll be asked
+   which partitions you want to include in the grub menu, and
    you'll also be asked to assign a label to each partition.
    The label can be any name such as "Slackware Linux" or
    "WinXP" etc.
 
 3. Install GRUB
-   
-   Once you've looked at your new config file and are 
-   satisfied with the way it looks, pick this option to 
+
+   Once you've looked at your new config file and are
+   satisfied with the way it looks, pick this option to
    install GRUB and exit the GRUB installation menu.
 
 Other options:
@@ -1439,34 +1462,34 @@ Other options:
 
    If you haven't begun building a new $grub_config file, this choice
    will let you take a look at the existing one in /boot/grub
-   on your GRUB Linux partition. 
+   on your GRUB Linux partition.
 
    If you have begun constructing a new $grub_config file, this
    option will let you view the progress on that.
 
  -- Skip GRUB installation or exit this menu
 
-  This option skips GRUB installation. Use this if you don't 
-  want to install GRUB, or if you've already installed it and 
+  This option skips GRUB installation. Use this if you don't
+  want to install GRUB, or if you've already installed it and
   want to exit.
 
- -- Help - Read this GRUB Bootloader HELP file 
- 
+ -- Help - Read this GRUB Bootloader HELP file
+
 -----------
 
 Other GRUB information:
 
-  GRUB on the Master Boot Record can be removed easily. 
+  GRUB on the Master Boot Record can be removed easily.
   DOS/Win9x fdisk has a 'C:\ fdisk /mbr' option that restores the
   original master boot record. You can also restore your original boot
   sector from the copy 'grubconfig' makes in /boot/grub/mbr.device.number.
-  
+
   This is probably the best way to go about it.
   # dd if=/boot/grub/mbr.device.number of=/dev/device bs=512 count=1
-  
+
   If you want to make any changes you don't need to run grubconfig
   again, you can just edit /boot/grub/$grub_config by hand.
-  
+
 --- end of GRUB help
 
 grubconfig is based on liloconfig by Patrick Volkerding fron the
