woof-code/rootfs-skeleton/usr/sbin/hackfontsize: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/hackfontsize b/woof-code/rootfs-skeleton/usr/sbin/hackfontsize
--- a/woof-code/rootfs-skeleton/usr/sbin/hackfontsize
+++ b/woof-code/rootfs-skeleton/usr/sbin/hackfontsize
@@ -1,18 +1,44 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler March 2013, bkhome.org.
 #License GPL3 2013 (see /usr/share/doc/legal).
-#hack to fix font sizes. Puppy has moved from 78 to 96 dpi.
-#can be called from a running puppy, standalone, from ppm, or from woof.
-#called from 3builddistro (woof), or /usr/local/petget/hacks-postinstall.sh.
+# Hack to fix font sizes. Puppy has moved from 78 to 96 dpi.
+# Can be called from a running puppy, standalone, from ppm, or from woof.
+# Called from 3builddistro (woof), or /usr/local/petget/hacks-postinstall.sh.
 #130326 first release.
 #130329 changed stat --format=%Y to stat -c %Y, so busybox applet will work.
+
+_TITLE_=fontsizehack
+_COMMENT_="CLI to alter config files for change from 78 to 96 dpi."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=RUNNINGIN
+ADD_PARAMETERS="Running in : any parameter, to set 'single'"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 
 GTKRCS=""
 JWMTHEMES=""
 ROXPREFIX=""
+
 RUNNINGIN="standalone"
 [ -d ../rootfs-skeleton ] && [ -d rootfs-complete ] && RUNNINGIN="woof"
 [ $1 ] && RUNNINGIN="single" #maybe from ppm when install a package.
+
 case $RUNNINGIN in
  standalone) #execute in a running puppy, no passed param.
   GTKRCS="`ls /usr/share/themes/*/gtk-2.0/gtkrc | grep -v ' ' | tr '\n' ' '`"
@@ -32,6 +58,7 @@ case $RUNNINGIN in
   XRESFILE="/root/.Xresources"
  ;;
 esac
+
 JWMPREFIX="$ROXPREFIX"
 
 XFTDPI=`grep '^Xft.dpi:' ${XRESFILE} | tr '\t' ' ' | tr -s ' ' | cut -f 2 -d ' '`
@@ -58,7 +85,7 @@ if [ $XFTDPI -ge 96 ];then
    fi
   done
  fi
- 
+
  #fix jwm themes...
  if [ "$JWMTHEMES" ];then
   for AJWMTHEME in $JWMTHEMES
@@ -102,7 +129,7 @@ if [ $XFTDPI -ge 96 ];then
    fi
   fi
  fi
-  
+
  #fix rox-filer...
  if [ "$ROXPREFIX" ];then
   echo -n "" > /tmp/aroxthemefixed
