woof-code/rootfs-skeleton/usr/sbin/hostname-set: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/hostname-set b/woof-code/rootfs-skeleton/usr/sbin/hostname-set
--- a/woof-code/rootfs-skeleton/usr/sbin/hostname-set
+++ b/woof-code/rootfs-skeleton/usr/sbin/hostname-set
@@ -1,6 +1,6 @@
 #!/bin/sh
 #Barry Kauler Oct. 2011
-#this is called from Internet Connection Wizard, script ''.
+# This is called from Internet Connection Wizard, script ''.
 #111028 have copied dlg code inside 'connectwizard' script, then call here with hostname passed param.
 #111028 fully internationalised.
 #111103 gcmartin: accept '-' char in hostname.
@@ -13,6 +13,30 @@
 
 export TEXTDOMAIN=hostname-set
 export OUTPUT_CHARSET=UTF-8
+
+_TITLE_=hostname-set
+_COMMENT_="CLI to test modem for 'Q0V1E1' 'Z' 'S0=0' '&C1' '&D2' 'S11=55' '+FCLASS=0' ."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=NEW_HOSTNAME
+ADD_PARAMETERS="NEW_HOSTNAME : Provide a new hostname"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 
 #111103 current hostname is $HOSTNAME, but if rerun this script before restarting X, need to get from here...
 [ -f /etc/hostname ] && HOSTNAME="`cat /etc/hostname`"
@@ -30,15 +54,15 @@ M_2=$(gettext "Your computer has been assigned a unique name, known as the 'host
 if [ "$1" = "" ];then #111028 111117
  export HOSTNAME_DIALOG="<window title=\"${WINTITLE}\" window_position=\"1\" icon-name=\"mini-hostname\">
  <vbox>
- 
+
   <text><label>${M_2}</label></text>
- 
+
   <hbox>
    <text><label>$(gettext 'Hostname'):</label></text>
    <entry tooltip-text=\"${M_1}\">
    <input>echo -n \"$NEW_HOSTNAME\"</input><variable>ENTRY_HOSTNAME</variable></entry>
   </hbox>
-  
+
   <hbox>
    <button ok></button>
    <button cancel></button>
