woof-code/rootfs-skeleton/usr/sbin/icon_switcher_cli: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/icon_switcher_cli b/woof-code/rootfs-skeleton/usr/sbin/icon_switcher_cli
--- a/woof-code/rootfs-skeleton/usr/sbin/icon_switcher_cli
+++ b/woof-code/rootfs-skeleton/usr/sbin/icon_switcher_cli
@@ -6,6 +6,29 @@
 #w002 first creation.
 #w477 record name of theme in /etc/desktop_icon_theme
 
+_TITLE_=iconswitcher-cli
+_COMMENT_="CLI to change icon desktop theme."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=NEWTHEME
+ADD_PARAMETERS="New theme : Name of the new theme ie. Blue-Moon, Tok-tok .."
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 NEWTHEME="$1"
 
 [ "$NEWTHEME" = "" ] && exit
@@ -35,7 +58,7 @@ do
   touch -m /usr/local/lib/X11/pixmaps/${xONEBASENAME}24.png #v3.98
  fi
 done
- 
+
 #w477 record current theme...
 echo -n "$NEWTHEME" > /etc/desktop_icon_theme
 
