woof-code/rootfs-skeleton/usr/sbin/icon_switcher: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/icon_switcher b/woof-code/rootfs-skeleton/usr/sbin/icon_switcher
--- a/woof-code/rootfs-skeleton/usr/sbin/icon_switcher
+++ b/woof-code/rootfs-skeleton/usr/sbin/icon_switcher
@@ -7,6 +7,29 @@
 #w477 record name of theme in /etc/desktop_icon_theme
 #100411 fbpanel menu did not update.
 
+_TITLE_=iconswitcher
+_COMMENT_="GTKdialog GUI to select icon theme in /usr/local/lib/X11/themes/ ."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 #  <text><label>\"${CHARPAD}\"</label></text>
 
 ICONSETSGUI=""
@@ -42,7 +65,7 @@ export ICONSWITCHGUI="
   <text><label>Choose the icon-set for desktop and menu</label></text>
 
   ${ICONSETSGUI}
-  
+
   <hbox>
    <button><input file stock=\"gtk-quit\"></input><label>QUIT</label></button>
   </hbox>
@@ -85,7 +108,7 @@ if [ "$NEWTHEME" != "" ];then
    touch -m /usr/local/lib/X11/pixmaps/${xONEBASENAME}24.png #v3.98
   fi
  done
- 
+
 # export ENDGUI="
 #<window title=\"Puppy Icon Switcher\" icon-name=\"gtk-convert\">
 # <vbox>
@@ -113,7 +136,7 @@ Click OK button and you will see them...\"</label></text>
  </vbox>
 </window>"
  gtkdialog3 --program=ENDGUI
- 
+
  #w477 record current theme...
  echo -n "$NEWTHEME" > /etc/desktop_icon_theme
 
