woof-code/rootfs-skeleton/usr/sbin/importfrompuppy1: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/importfrompuppy1 b/woof-code/rootfs-skeleton/usr/sbin/importfrompuppy1
--- a/woof-code/rootfs-skeleton/usr/sbin/importfrompuppy1
+++ b/woof-code/rootfs-skeleton/usr/sbin/importfrompuppy1
@@ -1,6 +1,29 @@
 #!/bin/sh
 # script to import from puppy1 to puppy2.
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 echo "This script will import installed packages and personal files from a"
 echo "pupxxx file (the personal storage file used by Puppy 1.x.x) to Puppy2."
 echo "But, you have to know the partition in which it resides."
