woof-code/rootfs-skeleton/usr/sbin/input-wizard: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/input-wizard b/woof-code/rootfs-skeleton/usr/sbin/input-wizard
--- a/woof-code/rootfs-skeleton/usr/sbin/input-wizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/input-wizard
@@ -1,8 +1,8 @@
 #!/bin/sh
 #(c) Barry Kauler 2005/2006 www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
-#keyboard/mouse wizard for Puppy Linux
-#based on code from /usr/X11R7/bin/xwin
+# keyboard/mouse wizard for Puppy Linux
+# Based on code from /usr/X11R7/bin/xwin
 #updated for 2.17
 #v411 rerwin: touchpad fix.
 #v411 rerwin: mouse detect fixes.
@@ -13,6 +13,29 @@
 #100127 notice to restart X if change keyboard layout (see code in /usr/bin/xwin to sync x and console).
 #100215 moved sync code for console/xorg kbd layout from xwin.
 #100527 added jemimah's flsynclient touchpad config.
+
+_TITLE_=inputwizard
+_COMMENT_="GTKdialog GUIs to setup input devices (keyboard,mice)."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 export MouseKeyboardWizard="
  <vbox>
@@ -44,7 +67,7 @@ export MouseKeyboardWizard="
     <action type=\"exit\">EXIT=KEY3BUTTON</action>
    </button>
   </hbox>
-  
+
   <hbox>
    <text>
     <label>Choose type of mouse...</label>
@@ -176,8 +199,8 @@ while :; do
   KEY1BUTTON)
    #added by playdayz to check for the incomplete xorg.conf
 if grep -q XkbLayout /etc/X11/xorg.conf;
-	then askkbdlayout
-	else exec comconexp &
+        then askkbdlayout
+        else exec comconexp &
 fi
  #this is extended menu, func above.
    #...this sets KEYBOARD, FONTMAP, CODEPAGE variables.
@@ -306,7 +329,7 @@ fi
     </checkbox>
 "
    fi  #v4.11 end
-  
+
    #v1.0.7 modified for gtkdialog2...
    export MouseWizard="
  <wtitle>Mouse Wizard</wtitle>
@@ -385,8 +408,8 @@ fi
      ln -snf $COMPORT /dev/mouse #v411
      #2.4 kernel has serial mouse support inbuilt.
      if [ -e /lib/modules/2.6 ];then #v1.0.2 k2.6...
-      modprobe 8250_pci 
-      modprobe sermouse 
+      modprobe 8250_pci
+      modprobe sermouse
      fi
     fi
     if [ ! "`echo "$RETPARAMS" | grep "RADIO003" | grep "true"`" = "" ];then
@@ -407,7 +430,7 @@ fi
      ZEROTAPTIME="`grep '"MaxTapTime"' /etc/X11/xorg.conf | grep '"0"'`"
      if [ "`echo "$RETPARAMS" | grep "CHECKBOX013" | grep "true"`" != "" ];then #enable tapping
       if [ "$ZEROTAPTIME" != "" ];then #currently disabled, else leave as is
-       [ -f /root/.maxtaptime ] && MAXTAPTIME="`grep -m 1 '"MaxTapTime"' /root/.maxtaptime`" || MAXTAPTIME='	Option "MaxTapTime" "220"'
+       [ -f /root/.maxtaptime ] && MAXTAPTIME="`grep -m 1 '"MaxTapTime"' /root/.maxtaptime`" || MAXTAPTIME='    Option "MaxTapTime" "220"'
        SEDSCRIPT="s/$ZEROTAPTIME/$MAXTAPTIME/"
        sed -i -e  "$SEDSCRIPT" /etc/X11/xorg.conf
       fi
@@ -416,13 +439,13 @@ fi
        MAXTAPTIME="`grep '"MaxTapTime"' /etc/X11/xorg.conf`"
        if [ "$MAXTAPTIME" != "" ];then
         echo "$MAXTAPTIME" > /root/.maxtaptime
-        ZEROTAPTIME='	Option "MaxTapTime" "0"'
+        ZEROTAPTIME='   Option "MaxTapTime" "0"'
         SEDSCRIPT="s/$MAXTAPTIME/$ZEROTAPTIME/"
         sed -i -e  "$SEDSCRIPT" /etc/X11/xorg.conf
        fi
       fi
      fi
-    fi     
+    fi
     #v4.11 end
 
     #v2.14 modified by Raul Suarez (rarsa at yahoo.com)
@@ -531,7 +554,7 @@ fi
      if [ ! -f /etc/X11/xkb/symbols/${XKEYMAP} ];then
       #echo "ERROR: Console keyboard `cat /etc/keymap` no matching Xorg layout. PLEASE REPORT TO BK"
       XKEYMAP='us'
-      KMAPERR="There is a problem. 
+      KMAPERR="There is a problem.
 You have chosen \"$KMAP\" console keyboard map, however Xorg
 cannot find a matching layout. Note, available Xorg layouts
 are in /etc/X11/xkb/symbols/pc.
@@ -546,7 +569,7 @@ For now, setting Xorg to use \"us\" layout."
    fi
    currXKEYMAP="`grep '#xkeymap0' /etc/X11/xorg.conf | tr '\t' ' ' | tr -s ' ' | cut -f 4 -d '"'`" #'geany fix
    if [ "$currXKEYMAP" != "$XKEYMAP" ];then
-    skPATTERN="s%.*#xkeymap0%	Option      \"XkbLayout\" \"${XKEYMAP}\" #xkeymap0%"
+    skPATTERN="s%.*#xkeymap0%   Option      \"XkbLayout\" \"${XKEYMAP}\" #xkeymap0%"
     sed -i -e "${skPATTERN}" /etc/X11/xorg.conf #100130
    fi
   fi
@@ -556,7 +579,7 @@ Note, this information is saved in file /etc/keymap
 
 YOU WILL NEED TO RESTART X FOR THIS TO TAKE EFFECT
 
-Press OK button to continue Wizard..." 
+Press OK button to continue Wizard..."
   Xdialog --title "Keyboard Wizard" --msgbox "$KMAPMSG" 0 0
  fi
 
