woof-code/rootfs-skeleton/usr/sbin/keyboard-layout: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/keyboard-layout b/woof-code/rootfs-skeleton/usr/sbin/keyboard-layout
--- a/woof-code/rootfs-skeleton/usr/sbin/keyboard-layout
+++ b/woof-code/rootfs-skeleton/usr/sbin/keyboard-layout
@@ -1,8 +1,8 @@
 #!/bin/sh
 #(c) Barry Kauler 2005/2006 www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
-#keyboard/mouse wizard for Puppy Linux
-#based on code from /usr/X11R7/bin/xwin
+# Keyboard/Mouse wizard for Puppy Linux
+# Based on code from /usr/X11R7/bin/xwin
 #updated for 2.17
 #v411 rerwin: touchpad fix.
 #v411 rerwin: mouse detect fixes.
@@ -14,7 +14,28 @@
 #100215 moved sync code for console/xorg kbd layout from xwin.
 #100527 added jemimah's flsynclient touchpad config.
 
+  _TITLE_=
+_COMMENT_=""
 
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 askkbdlayout () #091122
 {
@@ -125,8 +146,8 @@ askkbdlayout () #091122
   sync
   exec restartwm $CURRENTWM
  fi
- 
 
-#done 
+
+#done
 #end while loop.
 ###END###
