woof-code/rootfs-skeleton/usr/sbin/keymap-set: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/keymap-set b/woof-code/rootfs-skeleton/usr/sbin/keymap-set
--- a/woof-code/rootfs-skeleton/usr/sbin/keymap-set
+++ b/woof-code/rootfs-skeleton/usr/sbin/keymap-set
@@ -11,34 +11,59 @@
 #120627 handle different path to keymaps in kbd pkg.
 #120715 fix wrong pattern, 'de' was finding 'de-latin1'. fix symbols different location.
 
+__default_header__(){
+_TITLE_=set-keymap
+_COMMENT_="CLI to change keyboard relaten config files."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+}
+
 MYNAME=$(basename $0)
 VERSION=20100812
 usage() {
-	echo "$MYNAME ver.-$VERSION
+        echo "$MYNAME ver.-$VERSION
 usage: $MYNAME [ somekeymap ]
-		set keymap to 'somekeymap' or ask with dialog
-	$MYNAME cli
-		ask keymap with console dialog
-	$MYNAME --load
-	    set keymap according to /etc/keymap
-	$MYNAME --xopt [ somekeymap ]
-		show xorg.conf xkb options for 'somekeymap' or according to /etc/keymap
-	$MYNAME --list
-		show available key maps"
-	exit 1
+                set keymap to 'somekeymap' or ask with dialog
+        $MYNAME cli
+                ask keymap with console dialog
+        $MYNAME --load
+            set keymap according to /etc/keymap
+        $MYNAME --xopt [ somekeymap ]
+                show xorg.conf xkb options for 'somekeymap' or according to /etc/keymap
+        $MYNAME --list
+                show available key maps"
+        exit 1
 }
 xmap() {
   M=$1
   case "$M" in
-    az*) M="fr";;	#azerty
-    cf*) M="ca";;	#canadian french
-    cr*) M="hr";;	#croat
-    dv*) M="us";;	#dvorak
-    mk*) M="mkd";;	#macedonia
-    sl*) M="si";;	#slovene
-    sv) M="se";;	#sweden
-    uk) M="gb";;	#united kingdom
-    wa*) M="be";;	#wangbe
+    az*) M="fr";;       #azerty
+    cf*) M="ca";;       #canadian french
+    cr*) M="hr";;       #croat
+    dv*) M="us";;       #dvorak
+    mk*) M="mkd";;      #macedonia
+    sl*) M="si";;       #slovene
+    sv) M="se";;        #sweden
+    uk) M="gb";;        #united kingdom
+    wa*) M="be";;       #wangbe
     *)  M=$(echo $M|cut -b 1-2)
         echo "$SYMBOLS" | grep -q "$M" || M="us"
       ;;
@@ -60,7 +85,7 @@ makelist() {
       done
     else
       #echo "$OLDMAP"
-      #[ "$DEFMAP" != "" ] && echo "$DEFMAP" 
+      #[ "$DEFMAP" != "" ] && echo "$DEFMAP"
       #echo "$MAPS"
       for MP in $OLDMAP $DEFMAP $MAPS; do
         echo "$MP ."
@@ -79,10 +104,12 @@ LANG=C
 KMAPPATH='/lib/keymaps'
 [ -d /usr/share/kbd/keymaps/i386 ] && KMAPPATH='/usr/share/kbd/keymaps/i386'
 [ -d /usr/share/keymaps/i386 ] && KMAPPATH='/usr/share/keymaps/i386' #debian, gentoo. note, debian files have extension .kmap.gz, gentoo have .map.gz
+
 case $KMAPPATH in #120627
  /lib/keymaps) KMAPFILES="`find /lib/keymaps -mindepth 1 -maxdepth 1 -name '*.gz' | sort`" ;; #ex: us.gz
  *) KMAPFILES="`find ${KMAPPATH}/[^i]* -name '*.map' -o -name '*.kmap' -o -name '*.map.gz' -o -name '*.kmap.gz' -not -name 'defkeymap*' | sort`" ;;
 esac
+
 MAPS="$(echo "$KMAPFILES" | sed -e 's%^.*/%%' -e 's%\.gz$%%')"
 
 if [ -d /etc/X11/xkb/symbols/pc ];then #120715 fix symbols different location.
@@ -90,6 +117,7 @@ if [ -d /etc/X11/xkb/symbols/pc ];then #120715 fix symbols different location.
 else
  SYMBOLS="$(find /etc/X11/xkb/symbols -mindepth 1 -maxdepth 1 -type f | sed -e 's%/etc/X11/xkb/symbols/%%')"
 fi
+
 OLDMAP=""
 [ -f /etc/keymap ] && OLDMAP=$(cat /etc/keymap)
 [ "$OLDMAP" = "" ] && OLDMAP="us"
@@ -99,6 +127,7 @@ OLDMAP=""
 NEWMAP=""
 XOPT=""
 VERBOSE=""
+
 case "$1" in
   *-li*) # show available key maps
     makelist
@@ -113,7 +142,7 @@ case "$1" in
     [ "$1" != "" ] ||  NEWMAP=$(cat /etc/keymap 2>/dev/null)
    ;;
   cli) XSTATUS=""; shift;;
-  -ver)	echo "$MYNAME ver.-$VERSION"; exit;;
+  -ver) echo "$MYNAME ver.-$VERSION"; exit;;
   -*) usage;;
 esac
 [ $# -le 1 ] || usage
@@ -142,7 +171,7 @@ XKEYMAP=$(basename $NEWMAP .kmap) #120627
 XKEYMAP=$(basename $XKEYMAP .map)
 MODEL="pc102"
 VARIANT=""
-if ! echo "$SYMBOLS" | grep -q "$XKEYMAP"; then 
+if ! echo "$SYMBOLS" | grep -q "$XKEYMAP"; then
   XK1=$(echo $XKEYMAP | cut -d'-' -f1)
   XK2=$(echo $XKEYMAP | cut -d'-' -f2)
   XK3=$(echo $XKEYMAP | cut -d'-' -f3)
@@ -177,7 +206,7 @@ if [ "$NEW" != "" ];then
   #[ "$NEWMAP" = "$OLDMAP" ] && exit 0
   [ "$VERBOSE" ] && echo -ne "Loading \"$NEWMAP\" keyboard map... "
   echo -n $NEWMAP > /etc/keymap
-  cp -f /etc/keymap /etc/keymap_previous	# prevent xwin rewrites
+  cp -f /etc/keymap /etc/keymap_previous        # prevent xwin rewrites
   case $NEWMAP in
     *.map|*.kmap) loadkeys $NEWMAP || exit 1 #120627
     ;;
@@ -202,13 +231,13 @@ F=/etc/X11/xorg.conf
 TMPF=/tmp/xorg.conf
 # read old settings
 ALINE=$(grep -i '^[[:blank:]]*Option.*XkbModel' $F| head -n 1| cut -d'#' -f1)
-for W in $ALINE; do :; done	# set last word to W
+for W in $ALINE; do :; done     # set last word to W
 OLDMODEL=$(echo $W|tr -d '"')
 ALINE=$(grep -i '^[[:blank:]]*Option.*XkbLayOut' $F| head -n 1| cut -d'#' -f1)
 for W in $ALINE; do :; done
 OLDLAYOUT=$(echo $W|tr -d '"')
 ALINE=$(grep -i '^[[:blank:]]*Option.*XkbVariant' $F| head -n 1| cut -d'#' -f1)
-for W in $ALINE; do :; done	# set last word to W
+for W in $ALINE; do :; done     # set last word to W
 OLDVARIANT=$(echo $W|tr -d '"')
 #[ "$OLDMODEL" =  "" -a "$OLDLAYOUT" = "" ] && exit
 # rewrite xorg.conf
@@ -220,8 +249,8 @@ if [ "$MODEL" != "$OLDMODEL" -o "$LAYOUT" != "$OLDLAYOUT" -o "$VARIANT" != "$OLD
    done
    if [ "$FOUND" = "" ]; then
    echo 'Section "InputDevice"
-	Identifier  "Keyboard0"
-	Driver      "kbd"'
+        Identifier  "Keyboard0"
+        Driver      "kbd"'
    fi
    echo "    Option         \"XkbRules\" \"xorg\""
    echo "    Option         \"XkbModel\" \"$MODEL\""
@@ -231,7 +260,7 @@ if [ "$MODEL" != "$OLDMODEL" -o "$LAYOUT" != "$OLDLAYOUT" -o "$VARIANT" != "$OLD
    echo 'EndSection'
    fi
    while read ALINE; do
-	 echo $ALINE| grep -v '^[[:blank:]]*Option.*Xkb' && break
+         echo $ALINE| grep -v '^[[:blank:]]*Option.*Xkb' && break
    done
    while read ALINE; do echo $ALINE; done) <$F >$TMPF
   [ -s $TMPF ] && mv -f $F $F.bak && mv $TMPF $F
