woof-code/rootfs-skeleton/usr/sbin/lang2initrd: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/lang2initrd b/woof-code/rootfs-skeleton/usr/sbin/lang2initrd
--- a/woof-code/rootfs-skeleton/usr/sbin/lang2initrd
+++ b/woof-code/rootfs-skeleton/usr/sbin/lang2initrd
@@ -1,7 +1,7 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler 2012. License: GPL3 (/usr/share/doc/legal)
-#this script called from /usr/sbin/quicksetup, /usr/bin/wmreboot, wmpoweroff.
-#passed in params: $NEWLANG
+# This script called from /usr/sbin/quicksetup, /usr/bin/wmreboot, wmpoweroff.
+# Passed in params: $NEWLANG
 #120401 change logic to modify init (see also quicksetup).
 #121124 ensure that all [ ] are escaped in initrd translation-file. see also /usr/sbin/fixdesk, fixmenus.
 #121125 revert 121124.
@@ -10,6 +10,29 @@
 export TEXTDOMAIN=lang2initrd
 export OUTPUT_CHARSET=UTF-8
 . gettext.sh
+
+_TITLE_=changeLANGinInitrd
+_COMMENT_="CLI to translate messages in scripts."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=MEWLANG
+ADD_PARAMETERS="New LANG : whole LANG ie. fr_FR@Euro"
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 . /etc/rc.d/PUPSTATE
 
