woof-code/rootfs-skeleton/usr/sbin/legacy_grub_2013: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/legacy_grub_2013 b/woof-code/rootfs-skeleton/usr/sbin/legacy_grub_2013
--- a/woof-code/rootfs-skeleton/usr/sbin/legacy_grub_2013
+++ b/woof-code/rootfs-skeleton/usr/sbin/legacy_grub_2013
@@ -4,9 +4,32 @@
 export TEXTDOMAIN=legacy_grub_2013
 export OUTPUT_CHARSET=UTF-8
 
+_TITLE_=install-grub-legacy
+_COMMENT_="GTKdialog GUI to install GRUB 0.97 bootloader in simple mode."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 INSTALL () {
 
-# $1=stage1  $2=partition  $3=stage2  $4=windows  $5=Ubuntu  $6:true=frugal,false=full 
+# $1=stage1  $2=partition  $3=stage2  $4=windows  $5=Ubuntu  $6:true=frugal,false=full
 
 TIMEOUT=2
 [ -n "$4" -o -n "$5" ] && TIMEOUT=10
@@ -103,7 +126,7 @@ export PROG="
         <variable>QFRUG</variable>
         <label>$(gettext 'Frugal')</label>
        </radiobutton>
-       <radiobutton> 
+       <radiobutton>
          <variable>QFULL</variable>
          <label>$(gettext 'Full')</label>
       </radiobutton>
@@ -155,7 +178,7 @@ export PROG="
         <variable>EFRUG</variable>
         <label>$(gettext 'Frugal')</label>
        </radiobutton>
-       <radiobutton> 
+       <radiobutton>
          <variable>EFULL</variable>
          <label>$(gettext 'Full')</label>
       </radiobutton>
@@ -181,10 +204,10 @@ IFS=$I
 Xdialog --title " " --yesno "$(gettext 'Do you really want to install GRUB?')" 0 0
 [ $? -gt 0 ] && exit
 
-if [ "$EXIT" = "$(gettext 'Quick Install')" ]; then			#quick install
-  INSTALL "(hd0)" "sda1" "(hd0,0)" "" "" "$QFRUG" 			#true=frugal, false=full
-else									#expert install
-  INSTALL "$STAGE1" "$PART" "$STAGE2" "$WIN" "$UBUNTU" "$EFRUG" 	#true=frugal, false=full
+if [ "$EXIT" = "$(gettext 'Quick Install')" ]; then                     #quick install
+  INSTALL "(hd0)" "sda1" "(hd0,0)" "" "" "$QFRUG"                       #true=frugal, false=full
+else                                                                    #expert install
+  INSTALL "$STAGE1" "$PART" "$STAGE2" "$WIN" "$UBUNTU" "$EFRUG"         #true=frugal, false=full
 fi
 
 Xdialog --title " " --msgbox "$(gettext 'Done!')" 0 0
