/usr/sbin/loginmanager: Handle special chars in passwords.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/loginmanager b/woof-code/rootfs-skeleton/usr/sbin/loginmanager
--- a/woof-code/rootfs-skeleton/usr/sbin/loginmanager
+++ b/woof-code/rootfs-skeleton/usr/sbin/loginmanager
@@ -16,6 +16,30 @@ export TEXTDOMAINDIR=/usr/share/locale
 export OUTPUT_CHARSET=UTF-8
 . gettext.sh
 
+_TITLE_=askpass
+_COMMENT_="GTKdialog GUI or CLI to enter a password."
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
+
 HOMEUSER="`whoami`"
 xHOMEUSER="$HOMEUSER"
 [ "$HOMEUSER" = "root" ] && xHOMEUSER='administrator'
@@ -106,14 +130,14 @@ export MAIN_DIALOG="
 <window title=\"Login and Security Manager\" icon-name=\"gtk-execute\" resizable=\"false\">
  <vbox>
   <text use-markup=\"true\"><label>\"<b>$(gettext 'Currently you are logged in as:') <big>${xHOMEUSER}</big></b>\"</label></text>
-  
+
   <hbox>
    <pixmap><input file>/usr/share/doc/puppylogo96.png</input></pixmap>
    <frame administrator>
     <text><label>$(gettext "Puppy is structured in such a way that we consider running as administrator (also known as 'root') to be safe*, and is the choice of most users.")</label></text>
    </frame>
   </hbox>
-  
+
   <hbox>
    <pixmap><input file>/root/spot/spot.png</input></pixmap>
    <frame spot>
@@ -123,7 +147,7 @@ export MAIN_DIALOG="
     </vbox>
    </frame>
   </hbox>
-  
+
   <hbox>
    <pixmap><input file>/usr/share/doc/fido96.png</input></pixmap>
    <frame fido>
@@ -133,7 +157,7 @@ export MAIN_DIALOG="
     </vbox>
    </frame>
   </hbox>
-  
+
   <hbox>
    <text><label>$(gettext 'Help:')</label></text>
    <button><input file>/usr/local/lib/X11/mini-icons/mini-question.xpm</input><action>basichtmlviewer file:///usr/share/doc/root.htm & </action></button>
@@ -149,9 +173,22 @@ export MAIN_DIALOG="
 
 
 RETSTRING="`gtkdialog --program=MAIN_DIALOG --center`"
-[ $? -ne 0 ] && exit
+[ $? -ne 0 ] && exit 1
 
-eval "$RETSTRING"
+ PWORD=`echo "$RETSTRING" | grep -m1 'ADMINPASSWORD=.*'`
+ PWORD_=${PWORD//ADMINPASSWORD=\"/}
+ PWORD_=`echo "$PWORD_" | sed 's/"$//'`
+ _PWORD_=`echo "$PWORD_" | _string_to_octal`
+
+   RETSTRING_=`echo "$RETSTRING" | grep -v 'ADMINPASSWORD=.*'`
+
+ echo "$_PWORD_"
+ _RETVAL_="ADMINPASSWORD='$_PWORD_'
+$RETSTRING_"
+
+
+#eval "$RETSTRING"
+eval "$_RETVAL_"
 [ "$EXIT" != "OK" ] && exit
 
 #if [ "$CHANGE2ROOT" != "" ];then
@@ -181,7 +218,7 @@ if [ "$HOMEUSER" = "root" ];then #130604
       case $ANAME in
        seamonkey)
         extramsg="
-$(gettext 'Note also, the restrictions apply to all components of the SeaMonkey suite, including browser, Composer, address-book and ChatZilla.')" 
+$(gettext 'Note also, the restrictions apply to all components of the SeaMonkey suite, including browser, Composer, address-book and ChatZilla.')"
        ;;
       esac
       M_sm1="$(eval_gettext "The next time that you start \${ANAME}, it will run as user 'spot'.")
