woof-code/rootfs-skeleton/usr/sbin/modemprobe: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/modemprobe b/woof-code/rootfs-skeleton/usr/sbin/modemprobe
--- a/woof-code/rootfs-skeleton/usr/sbin/modemprobe
+++ b/woof-code/rootfs-skeleton/usr/sbin/modemprobe
@@ -1,10 +1,33 @@
 #!/bin/sh
 #Barry Kauler GPL 2007.
-#called from pupdial.
+# Called from pupdial.
 #v405 july 2008: total overhaul.
 #v465 rerwin: v413 added module names for wireless modems
 #v477 rerwin: v413 handle both lspci formats (replacing v003).
 #v477 rerwin: v413 added more module names for wireless modems
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 if [ -h /dev/modem ];then
  MODEMDEV="`readlink /dev/modem`"
@@ -13,7 +36,7 @@ PORT: /dev/modem is currently linked to port ${MODEMDEV}."
 #v433 check for bluetooth modem and set as /dev/modem...
 else
  MSGMDM3=""
- if which rfcomm >/dev/null && which sdptool >/dev/null;then  
+ if which rfcomm >/dev/null && which sdptool >/dev/null;then
   DUNPATTERN="`sdptool search DUN | sed -n -e '/^Searching/h' -e '/^    Channel:/{H;x}' -e 's/Searching for DUN on //' -e 's/ ...\n    Channel://p'`"
   if [ "$DUNPATTERN" != "" ];then
    DUNRFCLIST="`rfcomm -a | grep ' connected' | sed -e 's/ channel//' | grep -F "$DUNPATTERN" | cut -f 1 -d :`"
@@ -75,11 +98,11 @@ export MAINDIALOG="
     <action type=\"exit\">SETUP</action>
    </button>
   </hbox>
- 
+
  <frame Manual probing>
- 
+
   <text><label>The above does a fully automatic probe, however if it is unsatisfactory you can consider some manual probing and setup...</label></text>
- 
+
   <frame Serial hardware modem>
   <hbox>
    <text><label>If you have a true-hardware external serial or internal ISA card (or in some rare cases an internal PCI card), or think you might, click a button to probe. Note that 'ttyS0' is the same as 'com1' in DOS/Windows. Note also, 'ttyS0' is the most likely port, unless you have some other serial device such as a mouse. If the test is succesful then you will be offered to set /dev/modem and basic setup of /etc/wvdial.conf. (Note that these modems are not autodetected at bootup by Puppy, but are probed by the automatic PROBE button above)</label></text>
@@ -112,11 +135,11 @@ export MAINDIALOG="
    </vbox>
   </hbox>
   </frame>
-  
+
   <frame Autodetected modems>
    <hbox>
     <text><label>\"Most modems are autodetected by Puppy at bootup, but it has to be turned on! (or plugged in). ${MSGMDM1}\"</label></text>
-    
+
    <vbox>
    <button>
     <label>HELP</label>
@@ -125,7 +148,7 @@ export MAINDIALOG="
    </vbox>
    </hbox>
   </frame>
-  
+
   <hbox>
    <text><label>Click this button to blacklist a modem module. Note that you will then have to click the ERASE button, then reboot Puppy so that autodetection can re-occur.</label></text>
    <vbox>
@@ -144,9 +167,9 @@ export MAINDIALOG="
    </button>
    </vbox>
   </hbox>
- 
+
  </frame>
-  
+
  </vbox>
 </window>
 "
@@ -204,7 +227,7 @@ if [ "$DEVM" != "" ];then #4.06 probe found a modem (and not /dev/modem)
  xDEVM="`echo -n "$DEVM" | cut -f 3,4 -d '/'`"
  ln -snf $xDEVM /dev/modem #v4.06
  touch /tmp/.pupdial-modem_detected #v433
- 
+
  if [ -f /tmp/wvdial.conf ];then
   grep -v '^;' /tmp/wvdial.conf > /etc/wvdial.conf
   rm -f /tmp/wvdial.conf
