woof-code/rootfs-skeleton/usr/sbin/modem-wizard: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/modem-wizard b/woof-code/rootfs-skeleton/usr/sbin/modem-wizard
--- a/woof-code/rootfs-skeleton/usr/sbin/modem-wizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/modem-wizard
@@ -3,6 +3,29 @@
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #v405 updated. not currently being used.
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 KERNVER="`uname -r`"
 DEVM=""
 IRQM=""
@@ -22,7 +45,7 @@ irq_from_device()
  #v1.0.2 it seems that setserial may be more trouble than its worth...
  #in the case of linmodems it often doesn't work...
  set -- `setserial -v -b $dev auto_irq skip_test autoconfig session_lockout`
- [ "$6" ] && echo $6 | tr -d \) 
+ [ "$6" ] && echo $6 | tr -d \)
 }
 
 # kill processing attached to device
@@ -127,16 +150,16 @@ case ${?} in
    10)# ttyS0
      testmodem /dev/ttyS0
      ;;
-   11)# 
+   11)#
      testmodem /dev/ttyS1
      ;;
-   12)# 
+   12)#
      testmodem /dev/ttyS2
      ;;
-   13)# 
+   13)#
      testmodem /dev/ttyS3
      ;;
-   14)# 
+   14)#
      testmodem /dev/ttyS4
      ;;
    15)# = save
@@ -189,7 +212,7 @@ MSG1
        modprobe ltmodem
        modprobe ltserial
        sleep 1
-      fi    
+      fi
       testmodem /dev/ttyLT0
      ;;
    21) #smartlink linmodem (refer rc.network)
@@ -305,7 +328,7 @@ MSG1
         #test modem...
         testmodem /dev/ttySL0
        fi
-      fi     
+      fi
      ;;
     22) #ESS modem
       #avoid clashes with pctel modules...
