woof-code/rootfs-skeleton/usr/sbin/modemtest: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/modemtest b/woof-code/rootfs-skeleton/usr/sbin/modemtest
--- a/woof-code/rootfs-skeleton/usr/sbin/modemtest
+++ b/woof-code/rootfs-skeleton/usr/sbin/modemtest
@@ -6,6 +6,29 @@
 #v477 rerwin: v413 wait longer for modem response; add splash message during sleep
 #v424 rerwin: reset skip-PIN flag
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 #[ ! $1 ] && exit
 DEVM=$1
 PARAM2=$2
@@ -95,7 +118,7 @@ modem_test_func() {
    modem_device_to_conf_func $DEVM #v433 set tested dev
    if [ "$DEVM" = "$MODEMDEV" -a "$PARAM2" = "" ];then
     Xdialog --left --wmclass "pupdial" --title "PupDial: modem test" --no-cancel --msgbox "Success, the modem responds as $DEVM! (The modem is there; getting it to dial out is another matter!)" 0 0
-   else 
+   else
     Xdialog --left --wmclass "pupdial" --title "PupDial: modem test" --no-cancel --yesno "${MSGSUCCESS}" 0 0
     if [ $? -eq 0 ];then
      yaf-splash -font "8x16" -outline 0 -margin 4 -bg orange -text "Please wait, updating settings..." &
