woof-code/rootfs-skeleton/usr/sbin/momanager: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/momanager b/woof-code/rootfs-skeleton/usr/sbin/momanager
--- a/woof-code/rootfs-skeleton/usr/sbin/momanager
+++ b/woof-code/rootfs-skeleton/usr/sbin/momanager
@@ -1,9 +1,9 @@
 #!/bin/sh
 #(c) Barry Kauler Feb 2012 bkhome.org
-#licence GPL3 refer /usr/share/doc/legal
-#the intention of this script is to manage non-english translations of files.
-#this is to include shell scripts, xml, .desktop and menu files.
-#translation will only be for the current language, and UTF-8 must be enabled.
+#License GPL3 refer /usr/share/doc/legal
+# The intention of this script is to manage non-english translations of files.
+# This is to include shell scripts, xml, .desktop and menu files.
+# Translation will only be for the current language, and UTF-8 must be enabled.
 #120205 first release, handle gettext'ed scripts.
 #120206 added internationalization management of menu.
 #120206 simplify gui with help buttons.
@@ -48,6 +48,29 @@
 
 #***MOMANAGER IS ENGLISH ONLY (NOT GETTEXT'ED)***
 #it is for use by developers/translators with knowledge of english.
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 PARAM1=""
 [ $1 ] && PARAM1="$1"
@@ -221,7 +244,7 @@ for ADESKTOP in `find /usr/share/applications -mindepth 1 -maxdepth 1 -type f -n
 do
  [ "`grep '^Icon' $ADESKTOP`" = "" ] && continue #some dummy .desktop files used by xfce, ignore them.
  ADESKNAME="`basename $ADESKTOP`"
- 
+
  #find out what package it is from...
  xPTN=" ${ADESKNAME}$"
  zPTN="^${ADESKTOP}$"
@@ -230,7 +253,7 @@ do
  #...return nothing if in Woof
  [ ! "$aPKGNAME" ] && [ -f "${PATHPREFIX}${ADESKTOP}" ] && aPKGNAME="WOOF" #file is in Woof.
  [ ! "$aPKGNAME" ] && aPKGNAME="UNKNOWN"
- 
+
  if [ "`grep "$dPTN" $ADESKTOP`" != "" ];then
   YESDESK_XML="${YESDESK_XML}
 <item>${ADESKNAME} (${aPKGNAME})</item>"
@@ -332,10 +355,10 @@ bPTN="xml:lang=\"${ORIGLANG12}\"" #ex: xml:lang="de_DE"
 for AXMLFILE in $XMLFILES
 do
  AXMLFILE="`echo -n "$AXMLFILE" | sed -e 's%SPACECHAR% %g'`"
- 
+
  #[ "`echo -n "$AXMLFILE" | grep 'apps/ROX-Filer/'`" != "" ] && continue #120307 ROX-Filer now translated via /usr/share/doc/nls/ROX-Filer/ROX-Filer.pot
  #120308 ...no, we still need to edit this, see User Manual.
- 
+
  #want to know if from Woof or a builtin pkg or later-installed pkg...
  BASEAXMLFILE="`basename "$AXMLFILE"`"
  xPTN=" ${BASEAXMLFILE}$"
@@ -358,7 +381,7 @@ do
  #...return nothing if in Woof
  [ ! "$aPKGNAME" ] && [ -f "${PATHPREFIX}${AXMLFILE}" ] && aPKGNAME="WOOF" #file is in Woof.
  [ ! "$aPKGNAME" ] && aPKGNAME="UNKNOWN"
- 
+
  FNDFLAG=''
  FNDFLAG="`grep "$aPTN" "$AXMLFILE"`"
  [ ! "$FNDFLAG" ] && FNDFLAG="`grep "$bPTN" "$AXMLFILE"`"
@@ -478,14 +501,14 @@ YESCNT=0 ; NOCNT=0 ; YESBIN_XML="" ; NOBIN_XML=""
 for ANLSDIR in `ls -1 /usr/share/doc/nls | tr '\n' ' '`
 do
  if [ -d  /usr/share/doc/nls/${ANLSDIR} ];then
- 
+
   #120309 po files may now be there... ex: /usr/share/doc/nls/ROX-Filer/de.po
   FNDPO="`find /usr/share/doc/nls/${ANLSDIR} -mindepth 1 -maxdepth 1 -type f -name '*.po' | tr '\n' ' '`"
   for APO in $FNDPO
   do
    echo "$APO" >> /tmp/momanager/translations4langpack
   done
- 
+
   BINEXEC=""
   BINEXEC="`which $ANLSDIR`"
   [ ! "$BINEXEC" ] && BINEXEC="`find /usr/local -maxdepth 4 -executable -type f -name "$ANLSDIR"`" #ex: /usr/local/simple_network_setup/proxy-setup
@@ -493,7 +516,7 @@ do
    if [ "`file "$BINEXEC" | grep ' ELF ' | grep 'LSB executable'`" != "" ];then
     #have found binary executable for the pot file...
     TEXTDOMAINVALUE="$ANLSDIR" #TEXTDOMAIN must be same as executable name.
-    
+
     #want to know if from Woof or a builtin pkg or later-installed pkg...
     BASEBINEXEC="`basename "$BINEXEC"`"
     xPTN=" ${BASEBINEXEC}$"
@@ -516,7 +539,7 @@ do
     #...return nothing if in Woof
     [ ! "$aPKGNAME" ] && [ -f "${PATHPREFIX}${BINEXEC}" ] && aPKGNAME="WOOF" #file is in Woof.
     [ ! "$aPKGNAME" ] && aPKGNAME="UNKNOWN"
-    
+
     FNDMO=""
     PREFIXLOCALEDIR='/usr/share/locale' #120308
     if [ -f /usr/share/locale/${ORIGLANG12}/LC_MESSAGES/${TEXTDOMAINVALUE}.mo ];then
@@ -544,7 +567,7 @@ do
      NOBIN_XML="${NOBIN_XML}
 <item>${BINEXEC} (${TEXTDOMAINVALUE} ${aPKGNAME})</item>"
     fi
-    
+
    fi
   fi
  fi
@@ -614,7 +637,7 @@ fi
 
 export MM2_DLG="<window title=\"MoManager: Puppy files\" window_position=\"1\" resizable=\"false\" icon-name=\"${WINICON}\">
  <vbox>
- 
+
   <text use-markup=\"true\" width-chars=\"86\"><label>\"<big>Welcome! To fully translate Puppy to your <b>${ORIGLANG12}</b> locale, you need to get all of the files on the right-side drop-down lists over to the left-side lists. Simple! Click the help buttons for explanation about each list...</big>\"</label></text>
 
   <frame Scripts>
@@ -631,7 +654,7 @@ export MM2_DLG="<window title=\"MoManager: Puppy files\" window_position=\"1\" r
    </vbox>
   </hbox>
   </frame>
-  
+
   <frame Menu categories>
    <hbox>
     <vbox>
@@ -646,7 +669,7 @@ export MM2_DLG="<window title=\"MoManager: Puppy files\" window_position=\"1\" r
     </vbox>
    </hbox>
   </frame>
-  
+
   <frame Menu entries>
    <hbox>
     <vbox>
@@ -661,7 +684,7 @@ export MM2_DLG="<window title=\"MoManager: Puppy files\" window_position=\"1\" r
     </vbox>
    </hbox>
   </frame>
-  
+
   <frame XML files>
    <hbox>
     <vbox>
@@ -676,7 +699,7 @@ export MM2_DLG="<window title=\"MoManager: Puppy files\" window_position=\"1\" r
     </vbox>
    </hbox>
   </frame>
-  
+
   <frame SSS domains>
    <hbox>
     <vbox>
@@ -706,8 +729,8 @@ export MM2_DLG="<window title=\"MoManager: Puppy files\" window_position=\"1\" r
     </vbox>
    </hbox>
   </frame>
-  
-  
+
+
   <hbox>
    ${POEDIT_XML}
    <text><label>Create a langpack PET:</label></text>
@@ -717,7 +740,7 @@ export MM2_DLG="<window title=\"MoManager: Puppy files\" window_position=\"1\" r
    <button><label>About</label><action>pupdialog --background '#8080FF' --backtitle 'MoManager: About' --msgbox 'Created by Barry Kauler for Puppy Linux. (c) Copyright Barry Kauler 2012, license GPL3 (refer /usr/share/doc/legal)' 0 0 & </action></button>
    <button><label>Exit</label><action>EXIT:quit</action></button>
   </hbox>
-  
+
  </vbox>
 </window>
 "
@@ -829,7 +852,7 @@ case $EXIT in
    POPCOL='LightPink'
   fi
   poptop_func "$BINMSG" $POPCOL
-  
+
   #130502 L18L/BK: stay in a loop if there is an error converting .po to .mo...
   ABORTFLG=0
   cp -f /tmp/momanager/${ATEXTDOMAIN}.po /tmp/momanager/${ATEXTDOMAIN}.poBACKUP1
@@ -862,7 +885,7 @@ Click 'Abort' to give up..." 0 0
     *)  ABORTFLG=9 ; break ;; #1=Abort
    esac
   done
-  
+
   [ $ROPID -ne 0 ] && kill $ROPID
   if [ $ABORTFLG -eq 0 ];then #130502
    LANG=${ORIGLANG} rxvt -e msgfmt --check --output-file=/tmp/momanager/${ATEXTDOMAIN}.mo /tmp/momanager/${ATEXTDOMAIN}.po
@@ -887,7 +910,7 @@ Click 'Abort' to give up..." 0 0
   export LANG=$ORIGLANG
   exec momanager reenter
  ;;
- 
+
  create_mo)
   #ex: NOMO_COMBO='/usr/sbin/mousecheck (mousecheck)'
   ASCRIPT="`echo -n "$NOMO_COMBO" | cut -f 1 -d '(' | rev | cut -f 2 -d ' ' | rev`"
@@ -1077,7 +1100,7 @@ Click 'Abort' to give up..." 0 0
   export LANG=$ORIGLANG
   exec momanager reenter
  ;;
- 
+
  edit_top|create_top) #menu categories.
   APKGNAME='WOOF'
   if [ "$EXIT" = "edit_top" ];then
@@ -1128,13 +1151,13 @@ Click 'Abort' to give up..." 0 0
   export LANG=$ORIGLANG
   exec momanager reenter
  ;;
- 
+
  create_sss) #BK's Simple String Substitution method.
   APKGNAME="WOOF"
   SSSFILE="$NOSSS_COMBO" #ex: menu_strings (located at /usr/share/sss/menu_strings/)
   cp -f /usr/share/sss/$SSSFILE/$SSSFILE /tmp/momanager/$SSSFILE.$ORIGLANG1
   sync
-  
+
   #120224 special handling req'd for doc_strings...
   if [ "$SSSFILE" = "doc_strings" ];then
    cp -f /usr/share/sss/$SSSFILE/$SSSFILE /usr/share/sss/$SSSFILE/$SSSFILE.$ORIGLANG1
@@ -1216,7 +1239,7 @@ Click 'Abort' to give up..." 0 0
    export LANG=$ORIGLANG
    exec momanager reenter
   fi
-  
+
   killall geany 2>/dev/null
   poptop_func "The SSS file is now open in a text editor. You must only edit between the last two % characters. Edit, then Save, then Quit text editor..."
   ASTAT="`stat --format=%y "/usr/share/sss/$SSSFILE/$SSSFILE" | cut -f 1 -d ' ' | tr -d '-'`" #so can check against file version in latest Woof.
@@ -1253,13 +1276,13 @@ Click 'Abort' to give up..." 0 0
   export LANG=$ORIGLANG
   exec momanager reenter
  ;;
- 
+
  edit_sss)
   APKGNAME="WOOF"
   SSSFILE="$YESSSS_COMBO" #ex: menu_strings.de (located at /usr/share/sss/menu_strings/)
   SSSFILE="`echo -n "$SSSFILE" | rev | cut -f 2-9 -d '.' | rev`" #dump the extension, ex: menu_strings.de -> menu_strings
   #cp -f /usr/share/sss/$SSSFILE/$SSSFILE.$ORIGLANG1 /tmp/momanager/$SSSFILE.$ORIGLANG1
-  
+
   #120224 special handling req'd for doc_strings...
   if [ "$SSSFILE" = "doc_strings" ];then
    #ask what files want to edit (instead of just cycling through all of them)...
@@ -1340,7 +1363,7 @@ Click 'Abort' to give up..." 0 0
    export LANG=$ORIGLANG
    exec momanager reenter
   fi
-  
+
   #sync translated sss-file with original (master) sss-file (/usr/share/sss/$SSSFILE/$SSSFILE)...
   #ex: 'menu_strings' is the master (no translations in it), 'menu_strings.de' has German translations.
   #(Woof developers only have to edit the master, and the translation sss-files will sync to it).
@@ -1394,7 +1417,7 @@ Click 'Abort' to give up..." 0 0
    esac
   done
   echo  >> /tmp/momanager/$SSSFILE.$ORIGLANG1
-  
+
   sync
   killall geany 2>/dev/null
   poptop_func "The SSS file is now open in a text editor. You must only edit between the last two % characters. Edit, then Save, then Quit text editor..."
@@ -1432,7 +1455,7 @@ Click 'Abort' to give up..." 0 0
   export LANG=$ORIGLANG
   exec momanager reenter
  ;;
- 
+
  edit_xml|create_xml) #XML data files.
   if [ "$EXIT" = "edit_xml" ];then
    XMLFILE="`echo -n "$YESXML_COMBO" | cut -f 1 -d ' '`"
@@ -1467,7 +1490,7 @@ Click 'Abort' to give up..." 0 0
   export LANG=$ORIGLANG
   exec momanager reenter
  ;;
- 
+
  edit_bin|create_bin) #binary executables.
   if [ "$EXIT" = "edit_bin" ];then
    ABIN="`echo -n "$YESBIN_COMBO" | cut -f 1 -d '(' | rev | cut -f 2-9 -d ' ' | rev`"
@@ -1572,7 +1595,7 @@ WARNING: If there is an existing mo file, MoManager uncompiles it and merges wit
   export LANG=$ORIGLANG
   exec momanager reenter
  ;;
- 
+
  create_pet) #create a langpack PET
   mv -f /root/langpack_${GENLANG}-${ADATE}.pet /root/langpack_${GENLANG}-${ADATE}.petOLD 2>/dev/null
   [ -d /root/langpack_${GENLANG}-${ADATE} ] && rm -rf /root/langpack_${GENLANG}-${ADATE}
@@ -1594,21 +1617,21 @@ WARNING: If there is an existing mo file, MoManager uncompiles it and merges wit
    mkdir -p /root/langpack_${GENLANG}-${ADATE}"${ADIR}"
    cp -a -f "$ALINE" /root/langpack_${GENLANG}-${ADATE}"${ADIR}"/
   done
-  
+
   #130503 L18L: rename AppInfo.xml to AppInfo.xml.in for langpack (see also /usr/share/doc/langpack-template/pinstall.sh in Woof)
   sync #130807 L18L
   for AFILE in `ls -1 /root/langpack_${GENLANG}-${ADATE}/usr/local/apps/*/AppInfo.xml | tr '\n' ' '`
   do
    mv $AFILE "${AFILE}.in"
   done
-  
+
   #120926 want to accumulate many .desktop files (not just for installed pkgs), in /usr/share/applications.in...
   mkdir -p /root/langpack_${GENLANG}-${ADATE}/usr/share/applications.in
   cp -a -f /usr/share/applications.in/* /root/langpack_${GENLANG}-${ADATE}/usr/share/applications.in/
   cp -a -f /root/langpack_${GENLANG}-${ADATE}/usr/share/applications/* /root/langpack_${GENLANG}-${ADATE}/usr/share/applications.in/
   rm -r -f /root/langpack_${GENLANG}-${ADATE}/usr/share/applications
   pupdialog --background 'yellow' --backtitle "Menu .desktop files" --colors --msgbox "Translated .desktop files are now in \Zb/root/langpack_${GENLANG}-${ADATE}/usr/share/applications.in\ZB, and the translations will be inserted into same-name .desktop files in /usr/share/applications or /usr/local/share/applications when the langpack PET pkg is installed, and when the PPM installs a pkg. However, please do note that you can manually accumulate as many .desktop files in /usr/share/applications.in in your host Puppy system as you want, not just for installed pkgs, and MoManager will copy all of these into the langpack. For example, say that you have translated .desktop files for OpenOffice -- put them into \Zb/usr/share/applications.in\ZB -- it doesn't matter that the Puppy in which the langpack will be installed does not (yet) have OpenOffice installed. This operation has already been performed." 0 0
-  
+
   mv -f /root/langpack_${GENLANG}-${ADATE}/usr/share/desktop-directories /root/langpack_${GENLANG}-${ADATE}/usr/share/desktop-directories.in
   #120313 offer to find more...
   pupdialog --background 'orange' --backtitle "Langpack PET almost done" --colors --yes-label "Build PET" --no-label "Find all" --yesno "The langpack has been assembled in folder /root/langpack_${GENLANG}-${ADATE}, ready to be made into a PET. Click \ZbBuild PET\ZB to do this now. However, if you want, you can click \ZbFind all\ZB to tell MoManager to hunt for any other mo, po, pot, t12s translation files in the system, plus ${ORIGLANG1} hunspell dictionary, and include those in the PET..." 0 0
@@ -1663,7 +1686,7 @@ WARNING: If there is an existing mo file, MoManager uncompiles it and merges wit
     cp -a -f /usr/share/man/${ORIGLANG1}/man* /root/langpack_${GENLANG}-${ADATE}/usr/share/man/${ORIGLANG1}/
    fi
   fi
-  
+
   sync
   cd /root
   dir2tgz /root/langpack_${GENLANG}-${ADATE}
