woof-code/rootfs-skeleton/usr/sbin/paperconfig: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/paperconfig b/woof-code/rootfs-skeleton/usr/sbin/paperconfig
--- a/woof-code/rootfs-skeleton/usr/sbin/paperconfig
+++ b/woof-code/rootfs-skeleton/usr/sbin/paperconfig
@@ -5,40 +5,63 @@
 # Copyright (C) 1996, Yves Arrouye <arrouye@debian.org>
 #               2001, Adrian Bunk  <bunk@fs.tum.de>
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 usage() {
     if [ "$1" = -h ]
     then
-	exec 1>&2
-	echo -n U
+        exec 1>&2
+        echo -n U
     else
-	echo -n u
+        echo -n u
     fi
 
     echo "sage: `basename $0` [ -v, --version ] [ -h, --help ] [ -p, --paper name | --force ]"
 
     if [ "$1" = -h ]
     then
-	cat <<EOF
+        cat <<EOF
 
 Options: -v, --verbose          print version information and exit
          -h, --help             print this help and exit
-	 -p, --paper name	specify the paper to use
+         -p, --paper name       specify the paper to use
          --force                force paper configuration
 EOF
-	exit 0
+        exit 0
     else
-	exit 1
+        exit 1
     fi
 }
 
 # "|| true" added below, to assure that the script does not fail even if
 # called with bash -e. (MP 22/08/98)
 
-unset PAPERSIZE || true 
+unset PAPERSIZE || true
 : ${PAPERCONF:=/etc/papersize}
 export PAPERCONF
 
-unset PAPERDIR || true 
+unset PAPERDIR || true
 : ${PAPERDIR:=/etc/libpaper.d}
 export PAPERDIR
 
@@ -52,25 +75,25 @@ fi
 while [ $# -ne 0 ]
 do
     case "$1" in
-	-v|--version)
-	    echo "`basename $0` version 1.0" \
-		"by Yves Arrouye <arrouye@debian.org>"
-	    exit 0
-	    ;;
-	-h|--help)
-	    usage -h
-	    ;;
-	-p|--paper)
-	    test $# -gt 1 || usage
-	    paper="$2"
-	    shift
-	    ;;
-	--force)
-	    force=1
-	    ;;
-	*)
-	    usage
-	    ;;
+        -v|--version)
+            echo "`basename $0` version 1.0" \
+                "by Yves Arrouye <arrouye@debian.org>"
+            exit 0
+            ;;
+        -h|--help)
+            usage -h
+            ;;
+        -p|--paper)
+            test $# -gt 1 || usage
+            paper="$2"
+            shift
+            ;;
+        --force)
+            force=1
+            ;;
+        *)
+            usage
+            ;;
     esac
     shift
 done
@@ -87,18 +110,18 @@ format() {
 
     for w
     do
-	if [ `echo "$_start$_cline$w " | wc -c` -ge 0$_maxwidth ]
-	then
-	    echo "$_cline"
-	    _cline=
-	    _start=
-	fi
-	_cline="$_cline$w "
+        if [ `echo "$_start$_cline$w " | wc -c` -ge 0$_maxwidth ]
+        then
+            echo "$_cline"
+            _cline=
+            _start=
+        fi
+        _cline="$_cline$w "
     done
 
     if [ -n "$_cline" ]
     then
-	echo "$_cline"
+        echo "$_cline"
     fi
 
     unset _maxwidth _cline _start
@@ -115,10 +138,10 @@ setpaper() {
     if 2>/dev/null echo "$paperright" >${PAPERCONF}.new
     then
         if 2>/dev/null mv -f ${PAPERCONF}.new $PAPERCONF
-	then
-	    if 2>/dev/null chmod 644 $PAPERCONF
-	    then
-		ok=1
+        then
+            if 2>/dev/null chmod 644 $PAPERCONF
+            then
+                ok=1
             fi
         fi
     fi
@@ -128,14 +151,14 @@ setpaper() {
         echo `basename $0`: cannot create $PAPERCONF
         exit 2
     else
-	#
-	# Added code for calling back applications when
-	# papersize changes. See bug #345466
-	# eppesuig@debian.org, 2006-01-05
-	if [ -d ${PAPERDIR} ]
-	then
-	    run-parts ${PAPERDIR}
-	fi
+        #
+        # Added code for calling back applications when
+        # papersize changes. See bug #345466
+        # eppesuig@debian.org, 2006-01-05
+        if [ -d ${PAPERDIR} ]
+        then
+            run-parts ${PAPERDIR}
+        fi
     fi
 }
 
@@ -143,8 +166,8 @@ if [ ! -z "$paper" ]
 then
     if invalidpaper $paper
     then
-	>&2 echo `basename $0`: \"$paper\" is not a known paper name
-	exit 3
+        >&2 echo `basename $0`: \"$paper\" is not a known paper name
+        exit 3
     fi
     setpaper "$paper"
     exit 0
@@ -155,7 +178,7 @@ knownpapers="`paperconf -a`"
 prompt=
 width=72
 
-# "|| true" added below, to assure that the script does not fail even if 
+# "|| true" added below, to assure that the script does not fail even if
 # called with bash -e. (MP 22/08/98)
 
 paper=`paperconf 2>/dev/null || true`
@@ -168,11 +191,11 @@ then
 
     if [ -x /usr/bin/pager ]
     then
-	: ${PAGER:=/usr/bin/pager}
+        : ${PAGER:=/usr/bin/pager}
     fi
     if [ -x /bin/more ]
     then
-	: ${PAGER:=/bin/more}
+        : ${PAGER:=/bin/more}
     fi
     : ${PAGER:=cat}
 
@@ -180,7 +203,7 @@ then
     export LESS
 
     (
-	cat <<EOF
+        cat <<EOF
 The default (also known as system) paper can be chosen from many known
 papers that are currently recognized by programs using the libpaper
 library (with libpaper, paper names are case insensitive; if you use
@@ -189,8 +212,8 @@ library, this may not be true and some of the papers listed below may
 not be known by these programs):
 
 EOF
-	echo "$papers" | sed 's/^/    /'
-	echo
+        echo "$papers" | sed 's/^/    /'
+        echo
     ) | ${PAGER}
 
     : ${paper:=$dftpaper}
@@ -205,10 +228,10 @@ while invalidpaper "$paper"
 do
     if [ -z "$paper" ]
     then
-	echo "Please choose a paper from the available papers list."
+        echo "Please choose a paper from the available papers list."
     else
-	echo "Unknow paper \"$paper\"," \
-	    "please choose one from the available papers list."
+        echo "Unknow paper \"$paper\"," \
+            "please choose one from the available papers list."
     fi
 
     paper=$dftpaper
@@ -218,7 +241,7 @@ do
     paper=$ans
 done
 
-if [ "`paperconf 2>/dev/null`" != "$paper" ] || grep -q "[# 	]" $PAPERCONF
+if [ "`paperconf 2>/dev/null`" != "$paper" ] || grep -q "[#     ]" $PAPERCONF
 then
     setpaper "$paper"
 fi
