woof-code/rootfs-skeleton/usr/sbin/pcreatetorrent: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pcreatetorrent b/woof-code/rootfs-skeleton/usr/sbin/pcreatetorrent
--- a/woof-code/rootfs-skeleton/usr/sbin/pcreatetorrent
+++ b/woof-code/rootfs-skeleton/usr/sbin/pcreatetorrent
@@ -2,6 +2,29 @@
 
 VERSION=1.4 ##by Jason Pline 2007-12-28
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 ##find a suitable version of gtkdialog (needs 0.7.20 or greater) currently (as of puppy 4 and maybe before)
 ##the executable is named gtkdialog3. Exit with a warning incase gtkdialog isn't found.
 GTKDIALOG=""
@@ -103,26 +126,26 @@ export NEWGUI="
 <vbox>
 
     <frame Select one or the other>
-	<hbox>
+        <hbox>
     <radiobutton active=\"true\">
       <label>Make a torrent of a directory</label>
       <variable>RADIOBUTTON1</variable>
-		<action>if true enable:NEWDIR</action>
-		<action>if true enable:FILE_BROWSE_DIRECTORY</action>
+                <action>if true enable:NEWDIR</action>
+                <action>if true enable:FILE_BROWSE_DIRECTORY</action>
       <action>if false disable:NEWDIR</action>
       <action>if false disable:FILE_BROWSE_DIRECTORY</action>
     </radiobutton>
     <radiobutton active=\"false\">
       <label>Make a torrent of a single file</label>
       <variable>RADIOBUTTON2</variable>
-		<action>if true enable:ENTRY1</action>
-		<action>if true enable:FILE_BROWSE_FILENAME</action>
+                <action>if true enable:ENTRY1</action>
+                <action>if true enable:FILE_BROWSE_FILENAME</action>
       <action>if false disable:ENTRY1</action>
       <action>if false disable:FILE_BROWSE_FILENAME</action>
     </radiobutton>
     </hbox>
-	<frame Select a directory>
-	<hbox>
+        <frame Select a directory>
+        <hbox>
       <entry accept=\"directory\">
         <label>Select a Directory</label>
         <variable>NEWDIR</variable>
@@ -134,17 +157,17 @@ export NEWGUI="
       </button>
   </hbox>
   </frame>
-	<frame Select a single file>
+        <frame Select a single file>
     <hbox>
       <entry accept=\"filename\">
         <label>Select an Existing File</label>
         <variable>ENTRY1</variable>
-			<visible>disabled</visible>
+                        <visible>disabled</visible>
       </entry>
       <button>
         <input file stock=\"gtk-file\"></input>
         <variable>FILE_BROWSE_FILENAME</variable>
-			<visible>disabled</visible>
+                        <visible>disabled</visible>
         <action type=\"fileselect\">ENTRY1</action>
       </button>
     </hbox>
@@ -153,7 +176,7 @@ export NEWGUI="
 
     <frame Select your piece rate size for the torrent file>
     <hbox>
-    <combobox>	
+    <combobox>
      <variable>RATECOMBO</variable>
       $RATES
     </combobox>
@@ -162,7 +185,7 @@ export NEWGUI="
 
     <frame Select a tracker & create a torrent>
     <hbox>
-    <combobox>	
+    <combobox>
      <variable>TRACKERCOMBO</variable>
       $TRACKERS
     </combobox>
@@ -170,25 +193,25 @@ export NEWGUI="
       <input file icon=\"gtk-yes\"></input>
       <label>Create</label>
       <action type=\"exit\">CREATE_TORRENT</action>
-    </button> 
+    </button>
     </hbox>
     </frame>
-    
+
     <frame Remove/Add tracker - Exit program>
     <hbox>
-    
+
     <button>
       <input file icon=\"gtk-remove\"></input>
       <label>Remove Tracker</label>
       <action type=\"exit\">REMOVE_THE_TRACKER</action>
     </button>
-    
+
     <button>
       <input file icon=\"gtk-add\"></input>
       <label>Add A Tracker</label>
       <action type=\"exit\">ADD_A_TRACKER</action>
     </button>
-    
+
     <button>
       <input file icon=\"gtk-quit\"></input>
       <label>QUIT</label>
@@ -217,7 +240,7 @@ NEWDIR="`echo "$PCREATETORRENT" | grep NEWDIR= | cut -f 2 -d '"' | sed 's/"//g'`
 if [ "$NEWDIR" = "" ]; then
 NEWDIR="`echo "$PCREATETORRENT" | grep ENTRY1= | cut -f 2 -d '"' | sed 's/"//g'`"
 fi
-if [ "$NEWDIR" = "" ]; then   
+if [ "$NEWDIR" = "" ]; then
 export MAIN_DIALOG="
  <vbox>
   <text wrap=\"true\" width-chars=\"50\">
@@ -257,7 +280,7 @@ rxvt -bg black -fg green --geometry 60x10 -e ctorrent -t "$FILE" -u "$URL" -l "$
 else
 $TERMINAL -e ctorrent -t "$FILE" -u "$URL" -l "$RATE" -s $HOME/pcreatetorrent/torrents/"$TORR"
 fi
- 
+
 export MAIN_DIALOG="
  <vbox>
   <text wrap=\"true\" width-chars=\"50\">
@@ -317,54 +340,54 @@ export NEWGUI2="
     <text><label>http://tracker.etree.org:6969/announce</label></text>
     <text><label>In this box just enter the url no port/announce</label></text>
     <text><label>i.e. http://tracker.etree.org</label></text>
-    <entry>	
+    <entry>
      <variable>NEWURL</variable>
       <input>echo http://</input>
     </entry>
     </vbox>
     </frame>
-    
+
     <frame enter the port number for the tracker>
     <vbox>
-    <entry>	
+    <entry>
      <variable>NEWPORT</variable>
      <input>echo 6969</input>
     </entry>
     </vbox>
     </frame>
-    
+
     <frame enter the path on the server>
     <vbox>
-    <entry>	
+    <entry>
      <variable>NEWPATH</variable>
      <input>echo /announce</input>
     </entry>
     </vbox>
     </frame>
-    
+
     <vbox>
     <text><label>enter a name to represent this tracker</label></text>
     <text><label>i.e. bt.etree.org</label></text>
-    <entry>	
+    <entry>
      <variable>NEWNAME</variable>
     </entry>
     </vbox>
-    
+
     <frame create and exit buttons>
-    <hbox>    
-    
+    <hbox>
+
     <button>
       <input file icon=\"gtk-yes\"></input>
       <label>CREATE</label>
       <action type=\"exit\">ADD-TRACKER</action>
-	</button>
-	
+        </button>
+
     <button>
       <input file icon=\"gtk-quit\"></input>
       <label>QUIT</label>
       <action type=\"exit\">Exit-NOW</action>
     </button>
-    
+
   </hbox>
   </frame>
 
