woof-code/rootfs-skeleton/usr/sbin/pcur: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pcur b/woof-code/rootfs-skeleton/usr/sbin/pcur
--- a/woof-code/rootfs-skeleton/usr/sbin/pcur
+++ b/woof-code/rootfs-skeleton/usr/sbin/pcur
@@ -1,6 +1,29 @@
 #!/bin/sh
 #(c) copyright Barry Kauler aug 2009. Licence LGPL.
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 PREVTHEME=""
 if [ -e /root/.icons/default ];then
  PREVTHEME="`readlink /root/.icons/default | rev | cut -f 1 -d '/' | rev`"
@@ -15,14 +38,14 @@ do
 
  #precaution that 'cursors' subdir exists...
  [ ! -d /root/.icons/${ONEITEM}/cursors ] && continue
- 
+
  if [ ! -f /usr/share/icons/${ONEITEM}.png ];then
   cd /root/.icons/${ONEITEM}/cursors
   xcur2png -d /tmp/xcur2png left_ptr
   mv -f /tmp/xcur2png/left_ptr_000.png /usr/share/icons/${ONEITEM}.png
   rm -f /tmp/xcur2png/left_ptr_*.png
  fi
- 
+
  if [ "$ONEITEM" = "$PREVTHEME" ];then
   FIRSTITEM="<item icon=\"${ONEITEM}\">${ONEITEM} CURRENT THEME</item>"
  else
@@ -40,7 +63,7 @@ CURITEMS="  <tree>
     <variable>CHOOSECUR</variable>
     <height>${LISTHEIGHT}</height>
   </tree>"
-  
+
 if [ "$CURLIST" = "" ];then
  CURITEMS="<text use-markup=\"true\">
     <label>\"<b>You first need to install some cursor themes! For now, quit this program. Run the Puppy Package Manager and look in the 'Desktop' category</b>\"</label></text>"
@@ -53,10 +76,10 @@ export MAIN_DIALOG="
       <label>\"<b>You must restart X to use the new theme</b>\"</label>
     </text>
     <text><label>Choose one you like, click 'OK', close down all applications, then choose 'Restart X server' in the 'Shutdown' menu...</label></text>
-    
-    
+
+
     ${CURITEMS}
-    
+
     <hbox>
      <button ok></button>
      <button cancel></button>
