woof-code/rootfs-skeleton/usr/sbin/pdict: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pdict b/woof-code/rootfs-skeleton/usr/sbin/pdict
--- a/woof-code/rootfs-skeleton/usr/sbin/pdict
+++ b/woof-code/rootfs-skeleton/usr/sbin/pdict
@@ -2,6 +2,29 @@
 #BK nov 2007 gui frontend for dict.
 # 2010-05-26 ecube: refurbishing
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 WIDTH=550; HEIGHT=700
 
 echo -n "" > /tmp/pdict-results.txt
@@ -11,7 +34,7 @@ if [ "`ls /root/.dict_dbs`" = "" ]; then
 fi
 
 DICTLIST="`cat /root/.dict_dbs`"
-COMBOCONTENT="`echo "$DICTLIST" | grep -v '^Databases available:' | sed -e 's/^/<item>/' | sed -e 's/$/<\/item>/'`" 
+COMBOCONTENT="`echo "$DICTLIST" | grep -v '^Databases available:' | sed -e 's/^/<item>/' | sed -e 's/$/<\/item>/'`"
 
 export MAIN_DIALOG="
 <window title=\"Pdict dictionary and thesaurus\" icon-name=\"gtk-info\">
@@ -49,7 +72,7 @@ export MAIN_DIALOG="
     <height>$HEIGHT</height>
    </edit>
   </frame>
-  <hbox>     
+  <hbox>
    <button>
     <label>exit</label>
     <input file stock=\"gtk-quit\"></input>
