woof-code/rootfs-skeleton/usr/sbin/pdvdrsab: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pdvdrsab b/woof-code/rootfs-skeleton/usr/sbin/pdvdrsab
--- a/woof-code/rootfs-skeleton/usr/sbin/pdvdrsab
+++ b/woof-code/rootfs-skeleton/usr/sbin/pdvdrsab
@@ -3,9 +3,32 @@
 VERSION=0.1
 
 #Pdvdrsab - the rsab stands for rip, shrink, author, burn
-#This script depends on gktdialog-0.7.20 or possibly greater (can be named gtkdialog3)
-#it also depends on vobcopy to rip the dvd
-#To take full advantage of this script you'll also want to install vamps, dvdauthor, & ffmpeg
+# This script depends on gktdialog-0.7.20 or possibly greater (can be named gtkdialog3)
+# It also depends on vobcopy to rip the dvd
+# To take full advantage of this script you'll also want to install vamps, dvdauthor, & ffmpeg
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 rm -f /tmp/$WHOAMI-pvobcopy* 2>/dev/null
 
@@ -124,7 +147,7 @@ export DIALOG="
 <hbox>
     <edit>
       <variable>INFO</variable>
-      <input file>/tmp/$WHOAMI-pvobcopy-info</input> 
+      <input file>/tmp/$WHOAMI-pvobcopy-info</input>
       <width>400</width>
       <height>500</height>
     </edit>
@@ -132,7 +155,7 @@ export DIALOG="
 </frame>
 <hbox>
       <button>
-			<input file icon=\"gtk-quit\"></input>
+                        <input file icon=\"gtk-quit\"></input>
         <label>QUIT</label>
         <action type=\"closewindow\">closewindow</action>
       </button>
@@ -160,12 +183,12 @@ $PROBEDRIVES
 "
 if [ "`which vamps`" != "" ]; then
 RIPGUI="$RIPGUI
-	<frame Select an existing mpg or vob to shrink>
-	<hbox>
+        <frame Select an existing mpg or vob to shrink>
+        <hbox>
       <entry editable=\"true\" accept=\"filename\">
         <label>Select an Existing File</label>
         <variable>VAMPSFILE</variable>
-			<visible>disabled</visible>
+                        <visible>disabled</visible>
       </entry>
       <button>
         <input file stock=\"gtk-file\"></input>
@@ -173,8 +196,8 @@ RIPGUI="$RIPGUI
         <action type=\"fileselect\">VAMPSFILE</action>
       </button>
       </hbox>
-	</frame>
-	
+        </frame>
+
       <hbox>
       <text><label>enter the shrink to size:</label></text>
       <entry>
@@ -182,20 +205,20 @@ RIPGUI="$RIPGUI
     <input>echo 4485</input>
     <visible>disabled</visible>
     </entry>
-    </hbox> 
+    </hbox>
 
 "
 fi
 if [ "`which dvdauthor`" != "" ]; then
 RIPGUI="$RIPGUI
-	<frame Select your directory or file to author>
-	<hbox>
+        <frame Select your directory or file to author>
+        <hbox>
     <radiobutton active=\"true\">
       <label>Select a directory</label>
       <variable>RADIO1</variable>
       <visible>disabled</visible>
-		<action>if true enable:DIRENTRY</action>
-		<action>if true enable:FILE_BROWSE_DIRECTORY</action>
+                <action>if true enable:DIRENTRY</action>
+                <action>if true enable:FILE_BROWSE_DIRECTORY</action>
       <action>if false disable:DIRENTRY</action>
       <action>if false disable:FILE_BROWSE_DIRECTORY</action>
     </radiobutton>
@@ -203,17 +226,17 @@ RIPGUI="$RIPGUI
       <label>or select a single file</label>
       <variable>RADIO2</variable>
       <visible>disabled</visible>
-		<action>if true enable:FILEENTRY</action>
-		<action>if true enable:FILE_BROWSE_FILENAME</action>
+                <action>if true enable:FILEENTRY</action>
+                <action>if true enable:FILE_BROWSE_FILENAME</action>
       <action>if false disable:FILEENTRY</action>
       <action>if false disable:FILE_BROWSE_FILENAME</action>
     </radiobutton>
     </hbox>
-	<hbox>
+        <hbox>
       <entry editable=\"true\" accept=\"directory\">
         <label>Select a Directory</label>
         <variable>DIRENTRY</variable>
-			<visible>disabled</visible>
+                        <visible>disabled</visible>
       </entry>
       <button>
         <input file stock=\"gtk-open\"></input>
@@ -225,7 +248,7 @@ RIPGUI="$RIPGUI
       <entry editable=\"true\" accept=\"filename\">
         <label>Select an Existing File</label>
         <variable>FILEENTRY</variable>
-			<visible>disabled</visible>
+                        <visible>disabled</visible>
       </entry>
       <button>
         <input file stock=\"gtk-file\"></input>
@@ -239,12 +262,12 @@ RIPGUI="$RIPGUI
 fi
 if [ "`which growisofs`" != "" ]; then
 RIPGUI="$RIPGUI
-	<frame Select your VIDEO_TS folder to burn>
-	<hbox>
+        <frame Select your VIDEO_TS folder to burn>
+        <hbox>
       <entry editable=\"true\" accept=\"directory\">
         <label>Select a Directory</label>
         <variable>BURNDIR</variable>
-			<visible>disabled</visible>
+                        <visible>disabled</visible>
       </entry>
       <button>
         <input file stock=\"gtk-open\"></input>
@@ -256,12 +279,12 @@ RIPGUI="$RIPGUI
 "
 fi
 RIPGUI="$RIPGUI
-	<hbox>
+        <hbox>
     <radiobutton active=\"true\">
       <label>Rip</label>
       <variable>RADIO3</variable>
-		<action>if true disable:VAMPSFILE</action>
-		<action>if true disable:SHRINKFACTOR</action>
+                <action>if true disable:VAMPSFILE</action>
+                <action>if true disable:SHRINKFACTOR</action>
       <action>if true disable:RADIO1</action>
       <action>if true disable:RADIO2</action>
       <action>if true disable:DIRENTRY</action>
@@ -275,8 +298,8 @@ RIPGUI="$RIPGUI
     <radiobutton active=\"false\">
       <label>Shrink</label>
       <variable>RADIO4</variable>
-		<action>if true enable:VAMPSFILE</action>
-		<action>if true enable:SHRINKFACTOR</action>
+                <action>if true enable:VAMPSFILE</action>
+                <action>if true enable:SHRINKFACTOR</action>
       <action>if true disable:RADIO1</action>
       <action>if true disable:RADIO2</action>
       <action>if true disable:DIRENTRY</action>
@@ -291,14 +314,14 @@ RIPGUI="$RIPGUI
      <radiobutton active=\"false\">
       <label>Author</label>
       <variable>RADIO5</variable>
-		<action>if true disable:VAMPSFILE</action>
-		<action>if true disable:SHRINKFACTOR</action>
+                <action>if true disable:VAMPSFILE</action>
+                <action>if true disable:SHRINKFACTOR</action>
       <action>if true enable:RADIO1</action>
       <action>if true enable:RADIO2</action>
       <action>if true enable:DIRENTRY</action>
       <action>if true disable:PROBECOMBO</action>
       <action>if true disable:BURNDIR</action>
-    </radiobutton>   
+    </radiobutton>
 "
 fi
 if [ "`which growisofs`" != "" ]; then
@@ -306,8 +329,8 @@ RIPGUI="$RIPGUI
      <radiobutton active=\"false\">
       <label>Burn</label>
       <variable>RADIO6</variable>
-		<action>if true disable:VAMPSFILE</action>
-		<action>if true disable:SHRINKFACTOR</action>
+                <action>if true disable:VAMPSFILE</action>
+                <action>if true disable:SHRINKFACTOR</action>
       <action>if true disable:RADIO1</action>
       <action>if true disable:RADIO2</action>
       <action>if true disable:DIRENTRY</action>
@@ -317,26 +340,26 @@ RIPGUI="$RIPGUI
 "
 fi
 RIPGUI="$RIPGUI
-	</hbox>
+        </hbox>
 
-	<hbox>
+        <hbox>
     <button>
       <input file icon=\"gtk-cdrom\"></input>
-	  <label>dvd info</label>
+          <label>dvd info</label>
       <action>vobcopy -i \$PROBECOMBO -I 2>/tmp/$WHOAMI-pvobcopy-info</action>
       <action type=\"launch\">DIALOG</action>
-    </button>   
+    </button>
       <button>
-			<input file icon=\"gtk-execute\"></input>
+                        <input file icon=\"gtk-execute\"></input>
         <label>Execute</label>
         <action type=\"exit\">EXIT_NEXT</action>
       </button>
       <button>
-			<input file icon=\"gtk-quit\"></input>
+                        <input file icon=\"gtk-quit\"></input>
         <label>QUIT</label>
         <action type=\"exit\">EXIT_NOW</action>
       </button>
-	</hbox>
+        </hbox>
 
 </frame>
 </vbox>
@@ -464,22 +487,22 @@ export RIPGUI="
 <hbox>
 <vbox>
 <frame dvd ripping gui>
-		<text><label>Title with the most chapters is $MOST</label></text>
+                <text><label>Title with the most chapters is $MOST</label></text>
       <hbox>
       <text><label>enter title to rip:</label></text>
       <entry>
     <variable>TITLETORIP</variable>
     <input>echo $TITLE</input>
     </entry>
-    </hbox> 
-    
+    </hbox>
+
       <hbox>
       <text><label>enter the name:</label></text>
       <entry>
     <variable>RIPNAME</variable>
     <input>echo $NAME</input>
     </entry>
-    </hbox> 
+    </hbox>
 "
 if [ "`which vamps`" != "" ]; then
 RIPGUI="$RIPGUI
@@ -493,7 +516,7 @@ RIPGUI="$RIPGUI
       <action>if false disable:SHRINKFACTOR</action>
     </checkbox>
     </hbox>
-    
+
       <hbox>
       <text><label>enter the shrink to size:</label></text>
       <entry>
@@ -501,8 +524,8 @@ RIPGUI="$RIPGUI
     <input>echo 4485</input>
     <visible>disabled</visible>
     </entry>
-    </hbox> 
-    
+    </hbox>
+
 "
 fi
 if [ "`which dvdauthor`" != "" ]; then
@@ -515,7 +538,7 @@ RIPGUI="$RIPGUI
       <action>if true enable:BURNCHECK</action>
       <action>if false disable:BURNCHECK</action>
     </checkbox>
-    </hbox>    
+    </hbox>
 "
 fi
 if [ "`which growisofs`" != "" ]; then
@@ -527,13 +550,13 @@ RIPGUI="$RIPGUI
       <default>false</default>
       <visible>disabled</visible>
     </checkbox>
-    </hbox>    
+    </hbox>
 "
 fi
 RIPGUI="$RIPGUI
 </frame>
 
-<frame If mirror option is checked all above will be ignored>    
+<frame If mirror option is checked all above will be ignored>
     <hbox>
    <checkbox>
       <label>Check here for a mirror copy of the dvd</label>
@@ -543,12 +566,12 @@ RIPGUI="$RIPGUI
     </hbox>
 </frame>
 
-	<frame Select your save to directory>
-	<hbox>
+        <frame Select your save to directory>
+        <hbox>
       <entry accept=\"directory\">
         <label>Select a Directory</label>
         <variable>SAVEDIRECTORY</variable>
-			<input>echo $DIR</input>
+                        <input>echo $DIR</input>
       </entry>
       <button>
         <input file stock=\"gtk-open\"></input>
@@ -556,25 +579,25 @@ RIPGUI="$RIPGUI
         <action type=\"fileselect\">SAVEDIRECTORY</action>
       </button>
       </hbox>
-	</frame>
+        </frame>
 
-	<hbox>
+        <hbox>
     <button>
       <input file icon=\"gtk-cdrom\"></input>
-	  <label>dvd info</label>
+          <label>dvd info</label>
       <action type=\"launch\">DIALOG</action>
-    </button>  
+    </button>
       <button>
-			<input file icon=\"gtk-execute\"></input>
+                        <input file icon=\"gtk-execute\"></input>
         <label>Rip</label>
         <action type=\"exit\">EXIT_RIP</action>
       </button>
       <button>
-			<input file icon=\"gtk-quit\"></input>
+                        <input file icon=\"gtk-quit\"></input>
         <label>QUIT</label>
         <action type=\"exit\">EXIT_NOW</action>
       </button>
-	</hbox>
+        </hbox>
 </vbox>
 </hbox>
 </window>
@@ -771,7 +794,7 @@ rxvt -bg black -fg green -title pvobcopy --geometry 79x20 -e /tmp/$WHOAMI-pvobco
 else
 "$TERMINAL" -e /tmp/$WHOAMI-pvobcopy-exec5
 fi
-rm -f $FILE 
+rm -f $FILE
 mv $FILE.mpg $FILE
 fi
 CANFIT=NO
