woof-code/rootfs-skeleton/usr/sbin/pmodemdiag: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pmodemdiag b/woof-code/rootfs-skeleton/usr/sbin/pmodemdiag
--- a/woof-code/rootfs-skeleton/usr/sbin/pmodemdiag
+++ b/woof-code/rootfs-skeleton/usr/sbin/pmodemdiag
@@ -1,9 +1,32 @@
 #!/bin/bash
 #Barry Kauler, LGPL 2010
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 NAMEDATE="`date -u +%Y%m%d`"
 if [ "$1" = "--help" ];then
-	cat 1>&2 << EOT
+        cat 1>&2 << EOT
 
 Usage: `basename $0` [options]
 
@@ -17,7 +40,7 @@ EOT
  exit
 fi
 [ -e ~/pmodemdiag-$NAMEDATE.tar.gz ] && echo -e " A file already exists with the intended name of the new tarball file:\n  pmodemdiag-$NAMEDATE.tar.gz\n Please rename or delete it and then rerun pmodemdiag."  && exit
-if [ `cat /etc/puppyversion | cut -b 1-3` -ge 431 ];then 
+if [ `cat /etc/puppyversion | cut -b 1-3` -ge 431 ];then
  echo " Running PupScan silently to get hardware IDs and drivers."
 else
  echo " Running PupScan to get hardware IDs and drivers - please close its window manually."
