woof-code/rootfs-skeleton/usr/sbin/pmodprobeoption: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pmodprobeoption b/woof-code/rootfs-skeleton/usr/sbin/pmodprobeoption
--- a/woof-code/rootfs-skeleton/usr/sbin/pmodprobeoption
+++ b/woof-code/rootfs-skeleton/usr/sbin/pmodprobeoption
@@ -1,12 +1,36 @@
 #!/bin/sh
 #Barry Kauler, LGPL 2010
+#
+# Adapted from Vodaphone Mobile Connect scripts.
+# This driver script functions only if the product id is not already
+#  compiled into another driver and does not appear in the modules_alias file.
+# This consolidates the modprobe and echo-to-new_id portions of vmc scripts:
+#  vmc-huawei, vmc-novatel, vmc-option, vmc-zte.
+# It supports both Option and Sierra (vendor 1199) modems.
+# It may be necessary to blacklist pl2303 and onda
 
-#Adapted from Vodaphone Mobile Connect scripts.
-# This driver script functions only if the product id is not already 
-# compiled into another driver and does not appear in the modules_alias file.
-#This consolidates the modprobe and echo-to-new_id portions of vmc scripts: vmc-huawei, vmc-novatel, vmc-option, vmc-zte.
-#It supports both Option and Sierra (vendor 1199) modems.
-#It may be necessary to blacklist pl2303 and onda
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 VID="$1"
 PID="$2"
@@ -26,7 +50,7 @@ echo "pmodprobeoption: Probing MODULE: $MODULE  Setting ${MODULE}1/new_id" >> /t
  #All fields are passed in as hexadecimal values (no leading 0x).
 echo -e "pmodprobeoption: usbserial new_id files:\n`ls -1 /sys/bus/usb-serial/drivers/*/new_id`" >> /tmp/udevtrace-modem.log  #DEBUG
  sleep 5
- 
+
  #Run modem initialization script to detect modem.
  [ ! -e /tmp/usb_modeswitch_active ] && /etc/init.d/$SCRIPT start
  [ ! -e /tmp/usb_modeswitch_active ] && echo "pmodprobeoption: `date | tr -s ' ' | cut -f 4 -d ' '` - Completed modem initialization script $SCRIPT" >> /tmp/udevtrace-modem.log  #DEBUG
