woof-code/rootfs-skeleton/usr/sbin/pppoe-connect: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect b/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
@@ -22,6 +22,29 @@
 #
 #***********************************************************************
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 # From AUTOCONF
 prefix=/usr
 exec_prefix=${prefix}
@@ -100,9 +123,9 @@ fi
 
 if test "$DEBUG" != "" ; then
     if test "$LINUX_PLUGIN" != "" ; then
-	echo "Cannot use DEBUG mode and LINUX_PLUGIN at the same time."
-	echo "Kernel-mode PPPoE is experimental and unsupported."
-	exit 1
+        echo "Cannot use DEBUG mode and LINUX_PLUGIN at the same time."
+        echo "Kernel-mode PPPoE is experimental and unsupported."
+        exit 1
     fi
     echo "* The following section identifies your Ethernet interface" >> $DEBUG
     echo "* and user name.  Some ISP's need 'username'; others" >> $DEBUG
@@ -121,17 +144,17 @@ if test `uname -s` = Linux ; then
     modprobe ppp_async > /dev/null 2>&1
     modprobe ppp_synctty > /dev/null 2>&1
     if test -n "$LINUX_PLUGIN" ; then
-	modprobe pppox > /dev/null 2>&1
-	modprobe pppoe > /dev/null 2>&1
+        modprobe pppox > /dev/null 2>&1
+        modprobe pppoe > /dev/null 2>&1
     fi
 fi
 
 if test "$SYNCHRONOUS" = "yes" ; then
     PPPOE_SYNC=-s
     PPPD_SYNC=sync
-	# Increase the chances of it working on Linux...
+        # Increase the chances of it working on Linux...
     if test `uname -s` = Linux ; then
-	modprobe n_hdlc > /dev/null 2>&1
+        modprobe n_hdlc > /dev/null 2>&1
     fi
 else
     PPPOE_SYNC=""
@@ -199,7 +222,7 @@ esac
 if test "$LINUX_PLUGIN" != "" ; then
     PLUGIN_OPTS="plugin $LINUX_PLUGIN nic-$ETH"
     if test -n "$SERVICENAME" ; then
-	PLUGIN_OPTS="$PLUGIN_OPTS rp_pppoe_service $SERVICENAME"
+        PLUGIN_OPTS="$PLUGIN_OPTS rp_pppoe_service $SERVICENAME"
     fi
 
     # Interface name MUST BE LAST!!
@@ -226,7 +249,7 @@ elif test "$DNSTYPE" = "SPECIFY" ; then
     rm -f /etc/resolv.conf
     echo "nameserver $DNS1" > /etc/resolv.conf
     if test -n "$DNS2" ; then
-	echo "nameserver $DNS2" >> /etc/resolv.conf
+        echo "nameserver $DNS2" >> /etc/resolv.conf
     fi
 fi
 
@@ -234,28 +257,28 @@ fi
 PPPOE_CMD="$PPPOE -p $PPPOE_PIDFILE -I $ETH -T $PPPOE_TIMEOUT -U $PPPOE_SYNC $CLAMPMSS $ACNAME $SERVICENAMEOPT $PPPOE_EXTRA"
 if test "$DEBUG" != "" ; then
     if test "$DEMAND" != "" ; then
-	echo "(Turning off DEMAND for debugging purposes)"
-	DEMAND=""
+        echo "(Turning off DEMAND for debugging purposes)"
+        DEMAND=""
     fi
     echo "* The following section shows the pppd command we will invoke" >> $DEBUG
     echo "pppd invocation" >> $DEBUG
     echo "$SETSID $PPPD pty '$PPPOE_CMD' $PPP_STD_OPTIONS $PPPD_SYNC debug" >> $DEBUG
     echo "---------------------------------------------" >> $DEBUG
     $SETSID $PPPD pty "$PPPOE_CMD -D $DEBUG-0" \
-	$PPP_STD_OPTIONS \
-	$PPPD_SYNC \
-	debug >> $DEBUG 2>&1
+        $PPP_STD_OPTIONS \
+        $PPPD_SYNC \
+        debug >> $DEBUG 2>&1
     echo "---------------------------------------------" >> $DEBUG
     echo "* The following section is an extract from your log." >> $DEBUG
     echo "* Look for error messages from pppd, such as" >> $DEBUG
     echo "* a lack of kernel support for PPP, authentication failure" >> $DEBUG
     echo "* etc." >> $DEBUG
     if test -f "/var/log/messages" ; then
-	echo "Extract from /var/log/messages" >> $DEBUG
-	grep 'ppp' /var/log/messages | tail -150 >> $DEBUG
+        echo "Extract from /var/log/messages" >> $DEBUG
+        grep 'ppp' /var/log/messages | tail -150 >> $DEBUG
     elif test -f "/var/adm/messages"; then
-	echo "Extract from /var/adm/messages" >> $DEBUG
-	grep 'ppp' /var/adm/messages | tail -150 >> $DEBUG
+        echo "Extract from /var/adm/messages" >> $DEBUG
+        grep 'ppp' /var/adm/messages | tail -150 >> $DEBUG
     else
         echo "Can't find messages file (looked for /var/{log,adm}/messages" >> $DEBUG
     fi
@@ -273,9 +296,9 @@ if test "$DEBUG" != "" ; then
     cat $DEBUG-0 >> $DEBUG
     rm -f $DEBUG-0
     for i in 1 2 3 4 5 6 7 8 9 10 ; do
-	echo ""
-	echo ""
-	echo ""
+        echo ""
+        echo ""
+        echo ""
     done
     echo "*** Finished debugging run.  Please review the file"
     echo "*** '$DEBUG' and try to"
@@ -292,22 +315,22 @@ echo $$ > $PIDFILE
 
 while [ true ] ; do
     if test "$OVERRIDE_PPPD_COMMAND" != "" ; then
-	$SETSID $OVERRIDE_PPPD_COMMAND &
-	echo "$!" > $PPPD_PIDFILE
+        $SETSID $OVERRIDE_PPPD_COMMAND &
+        echo "$!" > $PPPD_PIDFILE
     elif test "$LINUX_PLUGIN" != "" ; then
-	$SETSID $PPPD $PPP_STD_OPTIONS $DEMAND &
-	echo "$!" > $PPPD_PIDFILE
+        $SETSID $PPPD $PPP_STD_OPTIONS $DEMAND &
+        echo "$!" > $PPPD_PIDFILE
     else
-	$SETSID $PPPD pty "$PPPOE_CMD" \
-	    $PPP_STD_OPTIONS \
-	    $DEMAND \
-	    $PPPD_SYNC &
-	echo "$!" > $PPPD_PIDFILE
+        $SETSID $PPPD pty "$PPPOE_CMD" \
+            $PPP_STD_OPTIONS \
+            $DEMAND \
+            $PPPD_SYNC &
+        echo "$!" > $PPPD_PIDFILE
     fi
     wait
 
     if test "$RETRY_ON_FAILURE" = "no" ; then
-	exit
+        exit
     fi
 
     # Run /etc/ppp/pppoe-lost if it exists
