woof-code/rootfs-skeleton/usr/sbin/pppoe-status: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-status b/woof-code/rootfs-skeleton/usr/sbin/pppoe-status
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-status
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-status
@@ -19,13 +19,36 @@
 #
 #***********************************************************************
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 # Defaults
 CONFIG=/etc/ppp/pppoe.conf
 
 case "$#" in
     1)
-	CONFIG="$1"
-	;;
+        CONFIG="$1"
+        ;;
 esac
 
 if [ ! -f "$CONFIG" -o ! -r "$CONFIG" ] ; then
@@ -45,8 +68,8 @@ fi
 # If no PPPOE_PIDFILE, connection is down, unless we're using the Linux plugin
 if [ "$LINUX_PLUGIN" = "" ] ; then
     if [ ! -r "$PPPOE_PIDFILE" ] ; then
-	echo "pppoe-status: Link is down (can't read pppoe PID file $PPPOE_PIDFILE)"
-	exit 1
+        echo "pppoe-status: Link is down (can't read pppoe PID file $PPPOE_PIDFILE)"
+        exit 1
     fi
 fi
 
@@ -63,19 +86,19 @@ PPPD_PID=`cat "$PPPD_PIDFILE"`
 # try both locations.
 for i in /etc/ppp/ppp*.pid /var/run/ppp*.pid ; do
     if [ -r $i ] ; then
-	PID=`cat $i`
-	if [ "$PID" = "$PPPD_PID" ] ; then
-	    IF=`basename $i .pid`
-	    netstat -rn | grep " ${IF}\$" > /dev/null
-	    # /sbin/ifconfig $IF | grep "UP.*POINTOPOINT" > /dev/null
-	    if [ "$?" != "0" ] ; then
-		echo "pppoe-status: Link is attached to $IF, but $IF is down"
-		exit 1
-	    fi
-	    echo "pppoe-status: Link is up and running on interface $IF"
-	    /sbin/ifconfig $IF
-	    exit 0
-	fi
+        PID=`cat $i`
+        if [ "$PID" = "$PPPD_PID" ] ; then
+            IF=`basename $i .pid`
+            netstat -rn | grep " ${IF}\$" > /dev/null
+            # /sbin/ifconfig $IF | grep "UP.*POINTOPOINT" > /dev/null
+            if [ "$?" != "0" ] ; then
+                echo "pppoe-status: Link is attached to $IF, but $IF is down"
+                exit 1
+            fi
+            echo "pppoe-status: Link is up and running on interface $IF"
+            /sbin/ifconfig $IF
+            exit 0
+        fi
     fi
 done
 
