woof-code/rootfs-skeleton/usr/sbin/pppoe-connect: Header, use f4puppy5, clean ups.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect b/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
@@ -22,6 +22,26 @@
 #
 #***********************************************************************
 
+  _TITLE_=
+_COMMENT_=
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+source /etc/rc.d/f4puppy5
+
+ADD_PARAMETER_LIST=""
+ADD_PARAMETERS=""
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+}
+
 # From AUTOCONF
 prefix=/usr
 exec_prefix=${prefix}
@@ -39,7 +59,7 @@ LANG=C
 export LANG
 
 # Must be root
-if test "`/usr/bin/id -u`" != 0 ; then
+if test "`/usr/bin/id -u`" != 0; then
     echo "$0: You must be root to run this script" >& 2
     exit 1
 fi
@@ -62,7 +82,7 @@ case "$#" in
     ;;
 esac
 
-if test ! -f "$CONFIG" -o ! -r "$CONFIG" ; then
+if test ! -f "$CONFIG" -o ! -r "$CONFIG"; then
     echo "$0: Cannot read configuration file '$CONFIG'" >& 2
     exit 1
 fi
@@ -81,11 +101,11 @@ case "$#" in
 esac
 
 # Check that config file is sane
-if test "$USER" = "" ; then
+if test "$USER" = ""; then
     echo "$0: Check '$CONFIG' -- no setting for USER" >& 2
     exit 1
 fi
-if test "$ETH" = "" ; then
+if test "$ETH" = ""; then
     echo "$0: Check '$CONFIG' -- no setting for ETH" >& 2
     exit 1
 fi
@@ -93,16 +113,16 @@ fi
 PPPD_PID=0
 
 # Catch common error
-if test "$DEBUG" = "1" ; then
+if test "$DEBUG" = "1"; then
     echo "*** If you want to use DEBUG, invoke pppoe-start, not pppoe-connect."
     exit 1
 fi
 
-if test "$DEBUG" != "" ; then
-    if test "$LINUX_PLUGIN" != "" ; then
-	echo "Cannot use DEBUG mode and LINUX_PLUGIN at the same time."
-	echo "Kernel-mode PPPoE is experimental and unsupported."
-	exit 1
+if test "$DEBUG" != ""; then
+    if test "$LINUX_PLUGIN" != ""; then
+    echo "Cannot use DEBUG mode and LINUX_PLUGIN at the same time."
+    echo "Kernel-mode PPPoE is experimental and unsupported."
+    exit 1
     fi
     echo "* The following section identifies your Ethernet interface" >> $DEBUG
     echo "* and user name.  Some ISP's need 'username'; others" >> $DEBUG
@@ -117,70 +137,70 @@ fi
 if test `uname -s` = Linux ; then
     $IFCONFIG $ETH up mtu 1500
     # For 2.4 kernels.  Will fail on 2.2.x, but who cares?
-    modprobe ppp_generic > /dev/null 2>&1
-    modprobe ppp_async > /dev/null 2>&1
-    modprobe ppp_synctty > /dev/null 2>&1
-    if test -n "$LINUX_PLUGIN" ; then
-	modprobe pppox > /dev/null 2>&1
-	modprobe pppoe > /dev/null 2>&1
+    modprobe ppp_generic >$OUT 2>$ERR
+    modprobe ppp_async >$OUT 2>$ERR
+    modprobe ppp_synctty >$OUT 2>$ERR
+    if test -n "$LINUX_PLUGIN"; then
+    modprobe pppox >$OUT 2>$ERR
+    modprobe pppoe >$OUT 2>$ERR
     fi
 fi
 
-if test "$SYNCHRONOUS" = "yes" ; then
+if test "$SYNCHRONOUS" = "yes"; then
     PPPOE_SYNC=-s
     PPPD_SYNC=sync
-	# Increase the chances of it working on Linux...
+    # Increase the chances of it working on Linux...
     if test `uname -s` = Linux ; then
-	modprobe n_hdlc > /dev/null 2>&1
+    modprobe n_hdlc >$OUT 2>$ERR
     fi
 else
     PPPOE_SYNC=""
     PPPD_SYNC=""
 fi
 
-if test -n "$ACNAME" ; then
+if test -n "$ACNAME"; then
     ACNAME="-C $ACNAME"
 fi
 
-if test -n "$SERVICENAME" ; then
+if test -n "$SERVICENAME"; then
     SERVICENAMEOPT="-S $SERVICENAME"
 else
     SERVICENAMEOPT=""
 fi
 
-if test "$CLAMPMSS" = "no" ; then
+if test "$CLAMPMSS" = "no"; then
     CLAMPMSS=""
 else
     CLAMPMSS="-m $CLAMPMSS"
 fi
 
 # If DNSTYPE is SERVER, we must use "usepeerdns" option to pppd.
-if test "$DNSTYPE" = "SERVER" ; then
+if test "$DNSTYPE" = "SERVER"; then
     PEERDNS=yes
     USEPEERDNS=yes
 fi
 
-if test "$PEERDNS" = "yes" ; then
+if test "$PEERDNS" = "yes"; then
     PEERDNS="usepeerdns"
 else
     PEERDNS=""
 fi
 
 # Backward config file compatibility -- PEERDNS used to be USEPEERDNS
-if test "$USEPEERDNS" = "yes" ; then
+if test "$USEPEERDNS" = "yes"; then
     PEERDNS="usepeerdns"
 fi
-if test "$USEPEERDNS" = "no" ; then
+if test "$USEPEERDNS" = "no"; then
     PEERDNS=""
 fi
 
 
 # Backward config file compatibility
-if test "$DEMAND" = "" ; then
+if test "$DEMAND" = ""; then
     DEMAND=no
 fi
 
-if test "$DEMAND" = "no" ; then
+if test "$DEMAND" = "no"; then
     DEMAND=""
 else
     DEMAND="demand persist idle $DEMAND 10.112.112.112:10.112.112.113 ipcp-accept-remote ipcp-accept-local connect true noipdefault ktune"
@@ -196,18 +216,18 @@ case "$FIREWALL" in
 esac
 
 # If we're using kernel-mode PPPoE on Linux...
-if test "$LINUX_PLUGIN" != "" ; then
+if test "$LINUX_PLUGIN" != ""; then
     PLUGIN_OPTS="plugin $LINUX_PLUGIN nic-$ETH"
-    if test -n "$SERVICENAME" ; then
-	PLUGIN_OPTS="$PLUGIN_OPTS rp_pppoe_service $SERVICENAME"
+    if test -n "$SERVICENAME"; then
+    PLUGIN_OPTS="$PLUGIN_OPTS rp_pppoe_service $SERVICENAME"
     fi
 
     # Interface name MUST BE LAST!!
     PLUGIN_OPTS="$PLUGIN_OPTS $ETH"
-    modprobe pppoe > /dev/null 2>&1
+    modprobe pppoe >$OUT 2>$ERR
 fi
 
-if test "$DEFAULTROUTE" != "no" ; then
+if test "$DEFAULTROUTE" != "no"; then
     DEFAULTROUTE="defaultroute"
 else
     DEFAULTROUTE=""
@@ -217,45 +237,45 @@ fi
 PPP_STD_OPTIONS="$PLUGIN_OPTS noipdefault noauth default-asyncmap $DEFAULTROUTE hide-password nodetach $PEERDNS mtu 1492 mru 1492 noaccomp nodeflate nopcomp novj novjccomp user $USER lcp-echo-interval $LCP_INTERVAL lcp-echo-failure $LCP_FAILURE $PPPD_EXTRA"
 
 # Jigger DNS if required...
-if test "$DNSTYPE" = "SERVER" ; then
+if test "$DNSTYPE" = "SERVER"; then
     # Sorry, dude...
     rm -f /etc/resolv.conf
     ln -s /etc/ppp/resolv.conf /etc/resolv.conf
-elif test "$DNSTYPE" = "SPECIFY" ; then
+elif test "$DNSTYPE" = "SPECIFY"; then
     # Sorry, dude...
     rm -f /etc/resolv.conf
     echo "nameserver $DNS1" > /etc/resolv.conf
-    if test -n "$DNS2" ; then
-	echo "nameserver $DNS2" >> /etc/resolv.conf
+    if test -n "$DNS2"; then
+    echo "nameserver $DNS2" >> /etc/resolv.conf
     fi
 fi
 
 # PPPoE invocation
 PPPOE_CMD="$PPPOE -p $PPPOE_PIDFILE -I $ETH -T $PPPOE_TIMEOUT -U $PPPOE_SYNC $CLAMPMSS $ACNAME $SERVICENAMEOPT $PPPOE_EXTRA"
-if test "$DEBUG" != "" ; then
-    if test "$DEMAND" != "" ; then
-	echo "(Turning off DEMAND for debugging purposes)"
-	DEMAND=""
+if test "$DEBUG" != ""; then
+    if test "$DEMAND" != ""; then
+    echo "(Turning off DEMAND for debugging purposes)"
+    DEMAND=""
     fi
     echo "* The following section shows the pppd command we will invoke" >> $DEBUG
     echo "pppd invocation" >> $DEBUG
     echo "$SETSID $PPPD pty '$PPPOE_CMD' $PPP_STD_OPTIONS $PPPD_SYNC debug" >> $DEBUG
     echo "---------------------------------------------" >> $DEBUG
     $SETSID $PPPD pty "$PPPOE_CMD -D $DEBUG-0" \
-	$PPP_STD_OPTIONS \
-	$PPPD_SYNC \
-	debug >> $DEBUG 2>&1
+    $PPP_STD_OPTIONS \
+    $PPPD_SYNC \
+    debug >> $DEBUG 2>&1
     echo "---------------------------------------------" >> $DEBUG
     echo "* The following section is an extract from your log." >> $DEBUG
     echo "* Look for error messages from pppd, such as" >> $DEBUG
     echo "* a lack of kernel support for PPP, authentication failure" >> $DEBUG
     echo "* etc." >> $DEBUG
-    if test -f "/var/log/messages" ; then
-	echo "Extract from /var/log/messages" >> $DEBUG
-	grep 'ppp' /var/log/messages | tail -150 >> $DEBUG
+    if test -f "/var/log/messages"; then
+    echo "Extract from /var/log/messages" >> $DEBUG
+    grep 'ppp' /var/log/messages | tail -150 >> $DEBUG
     elif test -f "/var/adm/messages"; then
-	echo "Extract from /var/adm/messages" >> $DEBUG
-	grep 'ppp' /var/adm/messages | tail -150 >> $DEBUG
+    echo "Extract from /var/adm/messages" >> $DEBUG
+    grep 'ppp' /var/adm/messages | tail -150 >> $DEBUG
     else
         echo "Can't find messages file (looked for /var/{log,adm}/messages" >> $DEBUG
     fi
@@ -273,9 +293,9 @@ if test "$DEBUG" != "" ; then
     cat $DEBUG-0 >> $DEBUG
     rm -f $DEBUG-0
     for i in 1 2 3 4 5 6 7 8 9 10 ; do
-	echo ""
-	echo ""
-	echo ""
+    echo ""
+    echo ""
+    echo ""
     done
     echo "*** Finished debugging run.  Please review the file"
     echo "*** '$DEBUG' and try to"
@@ -291,23 +311,23 @@ fi
 echo $$ > $PIDFILE
 
 while [ true ] ; do
-    if test "$OVERRIDE_PPPD_COMMAND" != "" ; then
-	$SETSID $OVERRIDE_PPPD_COMMAND &
-	echo "$!" > $PPPD_PIDFILE
-    elif test "$LINUX_PLUGIN" != "" ; then
-	$SETSID $PPPD $PPP_STD_OPTIONS $DEMAND &
-	echo "$!" > $PPPD_PIDFILE
+    if test "$OVERRIDE_PPPD_COMMAND" != ""; then
+    $SETSID $OVERRIDE_PPPD_COMMAND &
+    echo "$!" > $PPPD_PIDFILE
+    elif test "$LINUX_PLUGIN" != ""; then
+    $SETSID $PPPD $PPP_STD_OPTIONS $DEMAND &
+    echo "$!" > $PPPD_PIDFILE
     else
-	$SETSID $PPPD pty "$PPPOE_CMD" \
-	    $PPP_STD_OPTIONS \
-	    $DEMAND \
-	    $PPPD_SYNC &
-	echo "$!" > $PPPD_PIDFILE
+    $SETSID $PPPD pty "$PPPOE_CMD" \
+        $PPP_STD_OPTIONS \
+        $DEMAND \
+        $PPPD_SYNC &
+    echo "$!" > $PPPD_PIDFILE
     fi
     wait
 
-    if test "$RETRY_ON_FAILURE" = "no" ; then
-	exit
+    if test "$RETRY_ON_FAILURE" = "no"; then
+    exit
     fi
 
     # Run /etc/ppp/pppoe-lost if it exists
