woof-code/rootfs-skeleton/usr/sbin/pppoe-start: Header, use f4puppy5, clean ups.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-start b/woof-code/rootfs-skeleton/usr/sbin/pppoe-start
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-start
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-start
@@ -22,6 +22,26 @@
 #
 #***********************************************************************
 
+  _TITLE_=
+_COMMENT_=
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+source /etc/rc.d/f4puppy5
+
+ADD_PARAMETER_LIST=""
+ADD_PARAMETERS=""
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+}
+
 # From AUTOCONF
 prefix=/usr
 exec_prefix=${prefix}
@@ -53,8 +73,8 @@ if [ "$DEBUG" = "1" ] ; then
     export DEBUG
     mkdir $DEBUG
     if [ "$?" != 0 ] ; then
-	$ECHO "Could not create directory $DEBUG... exiting"
-	exit 1
+    $ECHO "Could not create directory $DEBUG... exiting"
+    exit 1
     fi
     DEBUG=$DEBUG/pppoe-debug.txt
 
@@ -74,11 +94,11 @@ if [ "$DEBUG" = "1" ] ; then
     $ECHO "---------------------------------------------" >> $DEBUG
     if [ "`uname -s`" = "Linux" ] ; then
         $ECHO "* The following section contains information about kernel modules" >> $DEBUG
-	$ECHO "* If the module for your Ethernet card is 'tulip', you might" >> $DEBUG
-	$ECHO "* want to look for an updated version at http://www.scyld.com" >> $DEBUG
-	$ECHO "Output of lsmod" >> $DEBUG
-	lsmod >> $DEBUG
-	$ECHO "---------------------------------------------" >> $DEBUG
+    $ECHO "* If the module for your Ethernet card is 'tulip', you might" >> $DEBUG
+    $ECHO "* want to look for an updated version at http://www.scyld.com" >> $DEBUG
+    $ECHO "Output of lsmod" >> $DEBUG
+    lsmod >> $DEBUG
+    $ECHO "---------------------------------------------" >> $DEBUG
     fi
     $ECHO "* The following section lists your routing table." >> $DEBUG
     $ECHO "* If you have an entry which starts with '0.0.0.0', you probably" >> $DEBUG
@@ -106,11 +126,11 @@ fi
 # Sort out command-line arguments
 case "$#" in
     1)
-	CONFIG="$1"
-	;;
+    CONFIG="$1"
+    ;;
     3)
-	CONFIG="$3"
-	;;
+    CONFIG="$3"
+    ;;
 esac
 
 if [ ! -f "$CONFIG" -o ! -r "$CONFIG" ] ; then
@@ -123,19 +143,19 @@ export CONFIG
 # Check for command-line overriding of ETH and USER
 case "$#" in
     2|3)
-	ETH="$1"
-	USER="$2"
-	;;
+    ETH="$1"
+    USER="$2"
+    ;;
 esac
 
 # Check for pidfile
 if [ -r "$PIDFILE" ] ; then
     PID=`cat "$PIDFILE"`
     # Check if still running
-    kill -0 $PID > /dev/null 2>&1
+    kill -0 $PID >$OUT 2>$ERR
     if [ $? = 0 ] ; then
-	$ECHO "$ME: There already seems to be a PPPoE connection up (PID $PID)" >& 2
-	exit 1
+    $ECHO "$ME: There already seems to be a PPPoE connection up (PID $PID)" >& 2
+    exit 1
     fi
     # Delete bogus PIDFILE
     rm -f "$PIDFILE" "$PIDFILE.pppd" "$PIDFILE.pppoe" "$PIDFILE.start"
@@ -149,7 +169,7 @@ if [ "$DEBUG" != "" ] ; then
     exit 0
 fi
 
-$CONNECT "$@" > /dev/null 2>&1 &
+$CONNECT "$@" >$OUT 2>$ERR &
 CONNECT_PID=$!
 
 if [ "$CONNECT_TIMEOUT" = "" -o "$CONNECT_TIMEOUT" = 0 ] ; then
@@ -164,30 +184,30 @@ fi
 # Monitor connection
 TIME=0
 while [ true ] ; do
-    ${exec_prefix}/sbin/pppoe-status $CONFIG > /dev/null 2>&1
+    ${exec_prefix}/sbin/pppoe-status $CONFIG >$OUT 2>$ERR
 
     # Looks like the interface came up
     if [ $? = 0 ] ; then
-	# Print newline if standard input is a TTY
-	tty -s && $ECHO " Connected!"
-	exit 0
+    # Print newline if standard input is a TTY
+    tty -s && $ECHO " Connected!"
+    exit 0
     fi
 
     if test -n "$FORCEPING" ; then
-	printf "%s" "$FORCEPING"
+    printf "%s" "$FORCEPING"
     else
-	tty -s && printf "%s" "$PING"
+    tty -s && printf "%s" "$PING"
     fi
     sleep $CONNECT_POLL
     TIME=`expr $TIME + $CONNECT_POLL`
     if [ $TIME -gt $CONNECT_TIMEOUT ] ; then
-	break
+    break
     fi
 done
 
 $ECHO "TIMED OUT" >& 2
 # Timed out!  Kill the pppoe-connect process and quit
-kill $CONNECT_PID > /dev/null 2>&1
+kill $CONNECT_PID >$OUT 2>$ERR
 
 # Clean up PIDFILE(s)
 rm -f "$PIDFILE" "$PIDFILE.pppd" "$PIDFILE.pppoe" "$PIDFILE.start"
