woof-code/rootfs-skeleton/usr/sbin/pppoe-status: Header, use f4puppy5, clean ups.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-status b/woof-code/rootfs-skeleton/usr/sbin/pppoe-status
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-status
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-status
@@ -18,14 +18,33 @@
 # If config_file is omitted, defaults to /etc/ppp/pppoe.conf
 #
 #***********************************************************************
+  _TITLE_=
+_COMMENT_=
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+source /etc/rc.d/f4puppy5
+
+ADD_PARAMETER_LIST=""
+ADD_PARAMETERS=""
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+}
 
 # Defaults
 CONFIG=/etc/ppp/pppoe.conf
 
 case "$#" in
     1)
-	CONFIG="$1"
-	;;
+    CONFIG="$1"
+    ;;
 esac
 
 if [ ! -f "$CONFIG" -o ! -r "$CONFIG" ] ; then
@@ -45,8 +64,8 @@ fi
 # If no PPPOE_PIDFILE, connection is down, unless we're using the Linux plugin
 if [ "$LINUX_PLUGIN" = "" ] ; then
     if [ ! -r "$PPPOE_PIDFILE" ] ; then
-	echo "pppoe-status: Link is down (can't read pppoe PID file $PPPOE_PIDFILE)"
-	exit 1
+    echo "pppoe-status: Link is down (can't read pppoe PID file $PPPOE_PIDFILE)"
+    exit 1
     fi
 fi
 
@@ -63,19 +82,19 @@ PPPD_PID=`cat "$PPPD_PIDFILE"`
 # try both locations.
 for i in /etc/ppp/ppp*.pid /var/run/ppp*.pid ; do
     if [ -r $i ] ; then
-	PID=`cat $i`
-	if [ "$PID" = "$PPPD_PID" ] ; then
-	    IF=`basename $i .pid`
-	    netstat -rn | grep " ${IF}\$" > /dev/null
-	    # /sbin/ifconfig $IF | grep "UP.*POINTOPOINT" > /dev/null
-	    if [ "$?" != "0" ] ; then
-		echo "pppoe-status: Link is attached to $IF, but $IF is down"
-		exit 1
-	    fi
-	    echo "pppoe-status: Link is up and running on interface $IF"
-	    /sbin/ifconfig $IF
-	    exit 0
-	fi
+    PID=`cat $i`
+    if [ "$PID" = "$PPPD_PID" ] ; then
+        IF=`basename $i .pid`
+        netstat -rn | grep " ${IF}\$" >$OUT
+        # /sbin/ifconfig $IF | grep "UP.*POINTOPOINT" > /dev/null
+        if [ "$?" != "0" ] ; then
+        echo "pppoe-status: Link is attached to $IF, but $IF is down"
+        exit 1
+        fi
+        echo "pppoe-status: Link is up and running on interface $IF"
+        /sbin/ifconfig $IF
+        exit 0
+    fi
     fi
 done
 
