woof-code/rootfs-skeleton/usr/sbin/pppoe-setup: Added or cleaned up header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-setup b/woof-code/rootfs-skeleton/usr/sbin/pppoe-setup
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-setup
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-setup
@@ -15,18 +15,13 @@
 
 ###KRG Fr 31. Aug 23:34:58 GMT+1 2012
 
-
-
 trap "exit 1" HUP INT QUIT KILL TERM
-
 
 OUT=/dev/null;ERR=$OUT
 [ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
 [ "$DEBUG" = "2" ] && set -x
 
-
 Version='1.1'
-
 
 usage(){
 USAGE_MSG="
@@ -43,8 +38,6 @@ exit $1
 
 [ "`echo "$1" | grep -wE "\-help|\-H"`" ] && usage 0
 [ "`echo "$1" | grep -wE "\-version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
-
-
 
 ###KRG Fr 31. Aug 23:34:58 GMT+1 2012
 
@@ -73,9 +66,9 @@ umask 077
 copy() {
     cp $1 $2
     if [ "$?" != 0 ] ; then
-	$ECHO "*** Error copying $1 to $2"
-	$ECHO "*** Quitting."
-	exit 1
+    $ECHO "*** Error copying $1 to $2"
+    $ECHO "*** Quitting."
+    exit 1
     fi
 }
 
@@ -127,12 +120,12 @@ while [ true ] ; do
     read U
 
     if [ "$U" = "" ] ; then
-	U="$USER"
+    U="$USER"
     fi
 
     # Under Linux, "fix" the default interface if eth1 is not available
     if test `uname -s` = "Linux" ; then
-	$IFCONFIG $ETH > /dev/null 2>&1 || ETH=eth0
+    $IFCONFIG $ETH > /dev/null 2>&1 || ETH=eth0
     fi
     $ECHO ""
     $ECHO "INTERFACE"
@@ -144,7 +137,7 @@ while [ true ] ; do
     read E
 
     if [ "$E" = "" ] ; then
-	E="$ETH"
+    E="$ETH"
     fi
 
     $ECHO ""
@@ -157,7 +150,7 @@ while [ true ] ; do
     printf "%s" ">>> Enter the demand value (default $DEMAND): "
     read D
     if [ "$D" = "" ] ; then
-	D=$DEMAND
+    D=$DEMAND
     fi
 
 
@@ -178,7 +171,7 @@ while [ true ] ; do
     printf "%s" ">>> Enter the DNS information here: "
 
     read DNS1
-    
+
     #v4.00 BK if enter 'server', somehow /etc/resolv.conf gets changed to a
     #symlink to /etc/ppp/resolv.conf (which is a symlink to /etc/resolv.conf)
     #so it's a circle. This script does not do that, something else does if it
@@ -190,36 +183,36 @@ while [ true ] ; do
 
     if [ "$DNS1" != "" ] ; then
         if [ "$DNS1" != "server" ] ; then
-	    $ECHO "Please enter the IP address of your ISP's secondary DNS server."
-	    $ECHO "If you just press enter, I will assume there is only one DNS server."
-	    printf "%s" ">>> Enter the secondary DNS server address here: "
-	    read DNS2
-	fi
+        $ECHO "Please enter the IP address of your ISP's secondary DNS server."
+        $ECHO "If you just press enter, I will assume there is only one DNS server."
+        printf "%s" ">>> Enter the secondary DNS server address here: "
+        read DNS2
+    fi
     fi
 
     while [ true ] ; do
-	$ECHO ""
-	$ECHO "PASSWORD"
-	$ECHO ""
-	stty -echo
-	printf "%s" ">>> Please enter your PPPoE password:    "
-	read PWD1
-	$ECHO ""
-	printf "%s" ">>> Please re-enter your PPPoE password: "
-	read PWD2
-	$ECHO ""
-	stty echo
-	if [ "$PWD1" = "$PWD2" ] ; then
-	    break
-	fi
+    $ECHO ""
+    $ECHO "PASSWORD"
+    $ECHO ""
+    stty -echo
+    printf "%s" ">>> Please enter your PPPoE password:    "
+    read PWD1
+    $ECHO ""
+    printf "%s" ">>> Please re-enter your PPPoE password: "
+    read PWD2
+    $ECHO ""
+    stty echo
+    if [ "$PWD1" = "$PWD2" ] ; then
+        break
+    fi
 
-	printf "%s" ">>> Sorry, the passwords do not match.  Try again? (y/n)"
-	read ANS
-	case "$ANS" in
-	    N|No|NO|Non|n|no|non)
-		$ECHO "OK, quitting.  Bye."
-		exit 1
-	esac
+    printf "%s" ">>> Sorry, the passwords do not match.  Try again? (y/n)"
+    read ANS
+    case "$ANS" in
+        N|No|NO|Non|n|no|non)
+        $ECHO "OK, quitting.  Bye."
+        exit 1
+    esac
     done
 
     # Firewalling
@@ -227,47 +220,47 @@ while [ true ] ; do
     $ECHO "FIREWALLING"
     $ECHO ""
     if test `uname -s` != "Linux" ; then
-	$ECHO "Sorry, firewalling is only supported under Linux.  Consult"
-	$ECHO "your operating system manuals for details on setting up"
-	$ECHO "packet filters for your system."
-	FIREWALL=NONE
+    $ECHO "Sorry, firewalling is only supported under Linux.  Consult"
+    $ECHO "your operating system manuals for details on setting up"
+    $ECHO "packet filters for your system."
+    FIREWALL=NONE
     else
-	$ECHO "Please choose the firewall rules to use.  Note that these rules are"
-	$ECHO "very basic.  You are strongly encouraged to use a more sophisticated"
-	$ECHO "firewall setup; however, these will provide basic security.  If you"
-	$ECHO "are running any servers on your machine, you must choose 'NONE' and"
-	$ECHO "set up firewalling yourself.  Otherwise, the firewall rules will deny"
-	$ECHO "access to all standard servers like Web, e-mail, ftp, etc.  If you"
-	$ECHO "are using SSH, the rules will block outgoing SSH connections which"
-	$ECHO "allocate a privileged source port."
-	$ECHO ""
-	while [ true ] ; do
-	    $ECHO "The firewall choices are:"
-	    $ECHO "0 - NONE: This script will not set any firewall rules.  You are responsible"
-	    $ECHO "          for ensuring the security of your machine.  You are STRONGLY"
-	    $ECHO "          recommended to use some kind of firewall rules."
-	    $ECHO "1 - STANDALONE: Appropriate for a basic stand-alone web-surfing workstation"
-	    $ECHO "2 - MASQUERADE: Appropriate for a machine acting as an Internet gateway"
-	    $ECHO "                for a LAN"
-	    printf "%s" ">>> Choose a type of firewall (0-2): "
-	    read a
-	    if [ "$a" = 0 -o "$a" = 1 -o "$a" = 2 ] ; then
-		break
-	    fi
-	    $ECHO "Please enter a number from 0 to 2"
-	done
+    $ECHO "Please choose the firewall rules to use.  Note that these rules are"
+    $ECHO "very basic.  You are strongly encouraged to use a more sophisticated"
+    $ECHO "firewall setup; however, these will provide basic security.  If you"
+    $ECHO "are running any servers on your machine, you must choose 'NONE' and"
+    $ECHO "set up firewalling yourself.  Otherwise, the firewall rules will deny"
+    $ECHO "access to all standard servers like Web, e-mail, ftp, etc.  If you"
+    $ECHO "are using SSH, the rules will block outgoing SSH connections which"
+    $ECHO "allocate a privileged source port."
+    $ECHO ""
+    while [ true ] ; do
+        $ECHO "The firewall choices are:"
+        $ECHO "0 - NONE: This script will not set any firewall rules.  You are responsible"
+        $ECHO "          for ensuring the security of your machine.  You are STRONGLY"
+        $ECHO "          recommended to use some kind of firewall rules."
+        $ECHO "1 - STANDALONE: Appropriate for a basic stand-alone web-surfing workstation"
+        $ECHO "2 - MASQUERADE: Appropriate for a machine acting as an Internet gateway"
+        $ECHO "                for a LAN"
+        printf "%s" ">>> Choose a type of firewall (0-2): "
+        read a
+        if [ "$a" = 0 -o "$a" = 1 -o "$a" = 2 ] ; then
+        break
+        fi
+        $ECHO "Please enter a number from 0 to 2"
+    done
 
-	case "$a" in
-	    0)
-		FIREWALL=NONE
-		;;
-	    1)
-		FIREWALL=STANDALONE
-		;;
-	    2)
-		FIREWALL=MASQUERADE
-		;;
-	esac
+    case "$a" in
+        0)
+        FIREWALL=NONE
+        ;;
+        1)
+        FIREWALL=STANDALONE
+        ;;
+        2)
+        FIREWALL=MASQUERADE
+        ;;
+    esac
     fi
 
     $ECHO ""
@@ -276,42 +269,42 @@ while [ true ] ; do
     $ECHO "Ethernet Interface: $E"
     $ECHO "User name:          $U"
     if [ "$D" = "no" ] ; then
-	$ECHO "Activate-on-demand: No"
+    $ECHO "Activate-on-demand: No"
     else
-	$ECHO "Activate-on-demand: Yes; idle timeout = $D seconds"
+    $ECHO "Activate-on-demand: Yes; idle timeout = $D seconds"
     fi
 
     if [ "$DNS1" != "" ] ; then
         if [ "$DNS1" = "server" ] ; then
-	    $ECHO "DNS addresses:      Supplied by ISP's server"
+        $ECHO "DNS addresses:      Supplied by ISP's server"
         else
-	    $ECHO "Primary DNS:        $DNS1"
-	    if [ "$DNS2" != "" ] ; then
-		$ECHO "Secondary DNS:      $DNS2"
-	    fi
+        $ECHO "Primary DNS:        $DNS1"
+        if [ "$DNS2" != "" ] ; then
+        $ECHO "Secondary DNS:      $DNS2"
+        fi
         fi
     else
-	$ECHO "DNS:                Do not adjust"
+    $ECHO "DNS:                Do not adjust"
     fi
     $ECHO "Firewalling:        $FIREWALL"
     $ECHO ""
     while [ true ] ; do
         printf "%s" '>>> Accept these settings and adjust configuration files (y/n)? '
         read ANS
-	case "ANS" in
-	    Y|y|yes|Yes|oui|Oui)
-		ANS=y
-		;;
+    case "ANS" in
+        Y|y|yes|Yes|oui|Oui)
+        ANS=y
+        ;;
             N|n|no|No|non|Non)
-		ANS=n
-		;;
-	esac
-	if [ "$ANS" = "y" -o "$ANS" = "n" ] ; then
-	    break
+        ANS=n
+        ;;
+    esac
+    if [ "$ANS" = "y" -o "$ANS" = "n" ] ; then
+        break
         fi
     done
     if [ "$ANS" = "y" ] ; then
-	break
+    break
     fi
 done
 
@@ -327,9 +320,9 @@ if [ "$DNS1" = "server" ] ; then
 else
     PEERDNS=no
     if [ "$DNS1" = "" ] ; then
-	DNSTYPE=NOCHANGE
+    DNSTYPE=NOCHANGE
     else
-	DNSTYPE=SPECIFY
+    DNSTYPE=SPECIFY
     fi
 fi
 
@@ -360,19 +353,19 @@ fi
 
 if [ "$DNS1" != "" ] ; then
     if [ "$DNS1" != "server" ] ; then
-	 $ECHO "Adjusting /etc/resolv.conf"
-	 if [ -r /etc/resolv.conf ] ; then
-	    grep -s "MADE-BY-RP-PPPOE" /etc/resolv.conf > /dev/null 2>&1
-	    if [ "$?" != 0 ] ; then
-		 $ECHO "  (But first backing it up to /etc/resolv.conf-bak)"
-		 copy /etc/resolv.conf /etc/resolv.conf-bak
-	    fi
-	 fi
-	 $ECHO "# MADE-BY-RP-PPPOE" > /etc/resolv.conf
-	 $ECHO "nameserver $DNS1" >> /etc/resolv.conf
-	 if [ "$DNS2" != "" ] ; then
-	    $ECHO "nameserver $DNS2" >> /etc/resolv.conf
-	 fi
+     $ECHO "Adjusting /etc/resolv.conf"
+     if [ -r /etc/resolv.conf ] ; then
+        grep -s "MADE-BY-RP-PPPOE" /etc/resolv.conf > /dev/null 2>&1
+        if [ "$?" != 0 ] ; then
+         $ECHO "  (But first backing it up to /etc/resolv.conf-bak)"
+         copy /etc/resolv.conf /etc/resolv.conf-bak
+        fi
+     fi
+     $ECHO "# MADE-BY-RP-PPPOE" > /etc/resolv.conf
+     $ECHO "nameserver $DNS1" >> /etc/resolv.conf
+     if [ "$DNS2" != "" ] ; then
+        $ECHO "nameserver $DNS2" >> /etc/resolv.conf
+     fi
     fi
 fi
 
@@ -391,9 +384,9 @@ else
 fi
 
 egrep -v "^$U|^\"$U\"" /etc/ppp/pap-secrets-bak > /etc/ppp/pap-secrets
-$ECHO "\"$U\"	*	\"$PWD1\"" >> /etc/ppp/pap-secrets
+$ECHO "\"$U\"   *   \"$PWD1\"" >> /etc/ppp/pap-secrets
 egrep -v "^$U|^\"$U\"" /etc/ppp/chap-secrets-bak > /etc/ppp/chap-secrets
-$ECHO "\"$U\"	*	\"$PWD1\"" >> /etc/ppp/chap-secrets
+$ECHO "\"$U\"   *   \"$PWD1\"" >> /etc/ppp/chap-secrets
 
 $ECHO ""
 $ECHO ""
