woof-code/rootfs-skeleton/usr/sbin/pppoe-stop: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-stop b/woof-code/rootfs-skeleton/usr/sbin/pppoe-stop
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-stop
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-stop
@@ -20,6 +20,29 @@
 #
 #***********************************************************************
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 # Set to "C" locale so we can parse messages from commands
 LANG=C
 export LANG
@@ -44,7 +67,7 @@ STARTPID="$PIDFILE.start"
 
 # Backward config file compatibility
 if test "$DEMAND" = "" ; then
-	DEMAND=no
+        DEMAND=no
 fi
 
 # Ignore SIGTERM
@@ -57,23 +80,23 @@ if [ -r "$PIDFILE" ] ; then
     # Check if still running
     kill -0 $PID > /dev/null 2>&1
     if [ $? != 0 ] ; then
-	echo "$ME: The pppoe-connect script (PID $PID) appears to have died" >& 2
+        echo "$ME: The pppoe-connect script (PID $PID) appears to have died" >& 2
     fi
 
     # Kill pppd, which should in turn kill pppoe
     if [ -r "$PPPD_PIDFILE" ] ; then
-	PPPD_PID=`cat "$PPPD_PIDFILE"`
-	$LOGGER -p daemon.notice "Killing pppd"
-	echo "Killing pppd ($PPPD_PID)"
-	kill $PPPD_PID > /dev/null 2>&1 || exit 1
+        PPPD_PID=`cat "$PPPD_PIDFILE"`
+        $LOGGER -p daemon.notice "Killing pppd"
+        echo "Killing pppd ($PPPD_PID)"
+        kill $PPPD_PID > /dev/null 2>&1 || exit 1
     fi
 
     # Kill pppoe-start
     PIDS=`cat $STARTPID`
     kill -0 $PIDS > /dev/null 2>&1
     if [ $? = 0 ] ; then
-	$LOGGER -p daemon.notice "Killing pppoe-connect"
-	kill $PIDS > /dev/null 2>&1
+        $LOGGER -p daemon.notice "Killing pppoe-connect"
+        kill $PIDS > /dev/null 2>&1
     fi
 
     # Kill pppoe-connect
@@ -83,8 +106,8 @@ if [ -r "$PIDFILE" ] ; then
 
     # Kill pppd again, in case it's still hanging around
     if [ -r "$PPPD_PIDFILE" ] ; then
-	PPPD_PID=`cat "$PPPD_PIDFILE"`
-	kill -9 $PPPD_PID > /dev/null 2>&1 || exit 1
+        PPPD_PID=`cat "$PPPD_PIDFILE"`
+        kill -9 $PPPD_PID > /dev/null 2>&1 || exit 1
     fi
 
     rm -f "$PIDFILE" "$PPPD_PIDFILE" "$PPPOE_PIDFILE" "$STARTPID"
