woof-code/rootfs-skeleton/usr/sbin/ptooltips: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/ptooltips b/woof-code/rootfs-skeleton/usr/sbin/ptooltips
--- a/woof-code/rootfs-skeleton/usr/sbin/ptooltips
+++ b/woof-code/rootfs-skeleton/usr/sbin/ptooltips
@@ -2,9 +2,32 @@
 #ptooltips 0.2
 #Sigmund Berglund
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 if [ "$1" = "-end" ]; then
-	for I in `ps | grep -E "ptooltips|yaf-splash -bw 1 -timeout 2 -bg lightgrey -outline 0" | awk '{print $1}'`; do kill -9 $I; done
-	exit
+        for I in `ps | grep -E "ptooltips|yaf-splash -bw 1 -timeout 2 -bg lightgrey -outline 0" | awk '{print $1}'`; do kill -9 $I; done
+        exit
 fi
 
 MOUSE_X="`getcurpos | awk '{print $1}'`"
