woof-code/rootfs-skeleton/usr/sbin/Pudd: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/Pudd b/woof-code/rootfs-skeleton/usr/sbin/Pudd
--- a/woof-code/rootfs-skeleton/usr/sbin/Pudd
+++ b/woof-code/rootfs-skeleton/usr/sbin/Pudd
@@ -1,8 +1,8 @@
 #!/bin/sh
 #2006 (c) Copyright Barry Kauler www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
-#this is a frontend to dd
-# will copy corrupted partitions, as well as healthy ones.
+# This is a frontend to dd
+# Will copy corrupted partitions, as well as healthy ones.
 #
 # Modified by Laurent Cas, April 2007
 # to display a message window when the script begins
@@ -10,7 +10,28 @@
 # everything is going well.
 #
 
+  _TITLE_=
+_COMMENT_=""
 
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 BKCOLOR='#ffe0e0'
 BLURBERR=""
@@ -119,7 +140,7 @@ or file, on the same PC or over a network. You can use Pudd to make copies of fl
 disks, to make clones of a drive/partition, or to rescue a failing drive/partition.
 
 Okay, the first thing to do is decide on the source:
- 1. If the source is a file, it must be a complete filesystem, such as produced by a 
+ 1. If the source is a file, it must be a complete filesystem, such as produced by a
     previous usage of Pudd to copy a partition or drive  to a file -- such a \"file\" is
     not like an ordinary text or graphic file, it is an image of a partition or complete
     drive. An image file can be copied to a partition or drive,  an ordinary file cannot.
@@ -294,7 +315,7 @@ echo "1"
 "
     fi
     ;;
-   *) 
+   *)
     exit
     ;;
 esac
@@ -363,7 +384,7 @@ if [ "$SOURCECHOICE" = "file" ];then
   fi
   SOURCEFS="`disktype $SOURCEPART | grep "file system" | head -n 1 | tr -s " " | cut -f 1 -d " "`"
   if [ "$SOURCEFS" = "" ];then
-   xmessage -bg "#ff0000" -name Pudd -title "Puppy universal dd: ERROR" -center "Sorry, this file does not have a filesystem inside it. 
+   xmessage -bg "#ff0000" -name Pudd -title "Puppy universal dd: ERROR" -center "Sorry, this file does not have a filesystem inside it.
 Pudd is not intended for copying ordinary files. A file with a filesystem inside it is an
 image of a drive or partition, and may be copied back to a drive or partition. Try again..."
   else
@@ -386,12 +407,12 @@ that the destination will have errors in it also.
 
 If the destination is a file, it will be compressed with the \"gzip\" program. This
 means that the file will be about half the size of the source drive/partition.
-Well, even though the destination file is compressed, you will still need to 
+Well, even though the destination file is compressed, you will still need to
 uncompress it if you ever want to mount it by loopback device, and Pudd also will
 uncompress it if it has to be copied to another drive/partition.
 
 If the destination is a drive/partition, it must be at least as large as the source
-drive/partition -- Pudd will display some info about this in the next window. 
+drive/partition -- Pudd will display some info about this in the next window.
 
 If the destination is a partition, Pudd will offer to grow the filesystem to fill
 the partition. However, this only applies if the source partition is an ext2,
@@ -422,7 +443,7 @@ MSG1
 RETVAL=$?
 
 case ${RETVAL} in
-   10)# file 
+   10)# file
      DESTCHOICE="file"
      break
      ;;
@@ -513,8 +534,8 @@ if [ "$DESTCHOICE" = "partition" ];then
    break
   fi
   #dest part is too small...
-  xmessage -bg "#ff8080" -center -name "Pudd" -title "Puppy universal dd: ERROR" "Sorry, the destination partition is too small. The source 
-$SOURCEPART is $SOURCESIZE Kbytes but the destination 
+  xmessage -bg "#ff8080" -center -name "Pudd" -title "Puppy universal dd: ERROR" "Sorry, the destination partition is too small. The source
+$SOURCEPART is $SOURCESIZE Kbytes but the destination
 $DESTPART is $DESTSIZE Kbytes. Try again..."
  done #WHILE4
 fi
@@ -534,8 +555,8 @@ if [ "$DESTCHOICE" = "drive" ];then
    break
   fi
   #dest drive is too small...
-  xmessage -bg "#ff8080" -center -name "Pudd" -title "Puppy universal dd: ERROR" "Sorry, the destination drive is too small. The source 
-$SOURCEPART is $SOURCESIZE Kbytes but the destination 
+  xmessage -bg "#ff8080" -center -name "Pudd" -title "Puppy universal dd: ERROR" "Sorry, the destination drive is too small. The source
+$SOURCEPART is $SOURCESIZE Kbytes but the destination
 $DESTPART is $DESTSIZE Kbytes. Try again..."
  done
 fi
@@ -690,7 +711,7 @@ Would you like to do this size optimisation?" 0 0
      echo 'read nnn' >> /tmp/backuppartition.sh
      sync
      chmod 755 /tmp/backuppartition.sh
-     rxvt -name Pudd -title "Puppy universal dd: copying" -bg "#ffff00" -geometry 80x8 -e /tmp/backuppartition.sh ${DESTPART} ${SOURCEPART} ${DESTSIZE} ${ALLOWGROW} 
+     rxvt -name Pudd -title "Puppy universal dd: copying" -bg "#ffff00" -geometry 80x8 -e /tmp/backuppartition.sh ${DESTPART} ${SOURCEPART} ${DESTSIZE} ${ALLOWGROW}
      ;;
    13)# EXIT
      ;;
