/usr/sbin/Pudd: Batch adding of VERB , Q , ERR , OUT variables. Shorten tests ( omitt !=  ).

diff --git a/woof-code/rootfs-skeleton/usr/sbin/Pudd b/woof-code/rootfs-skeleton/usr/sbin/Pudd
--- a/woof-code/rootfs-skeleton/usr/sbin/Pudd
+++ b/woof-code/rootfs-skeleton/usr/sbin/Pudd
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/ash
 #2006 (c) Copyright Barry Kauler www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #this is a frontend to dd
@@ -34,7 +34,7 @@ FOUNDZIP=""
 # #load ide-floppy.o to access atapi zip drive...
 # ZIPMODULE="`lsmod | grep "ide-floppy"`"
 # if [ "$ZIPMODULE" = "" ];then
-#  modprobe ide-floppy
+#  modprobe $VERB ide-floppy
 # fi
 #fi
 
@@ -68,7 +68,7 @@ while [ 1 ];do #first loop.
  RETMSG0="`probepart -k 2>&1`"
  if [ ! $? -eq 0 ];then
   BLURB2="...HOWEVER, Puppy detects an error probing the partitions!!!"
-  USBERR="`echo -n "$RETMSG0" | grep "/dev/sd"`"
+  USBERR="`echo "$RETMSG0" | grep "/dev/sd"`"
   if [ ! "$USBERR" = "" ];then
    sync
    #find what usb mounted on and unmount (don't assume /mnt/flash)...
@@ -78,9 +78,9 @@ while [ 1 ];do #first loop.
     rox -D "$ONEUSBMNT"
     #fuser -k -m $ONEUSBMNT
     sync
-    umount -r $ONEUSBMNT 2> /tmp/umounterr.txt
+    umount $VERB $VERB -r $ONEUSBMNT 2> /tmp/umounterr.txt
    done
-   modprobe -r usb-storage
+   modprobe $VERB -r usb-storage
    BLURB2="...HOWEVER, Puppy detects an error probing the USB partitions!!!"
   fi
   BKCOLOR='#ffc0c0'
@@ -93,18 +93,18 @@ while [ 1 ];do #first loop.
  PROBEDISKALL="$FOUNDFD0$PROBEDISK0"
 
  #we should not copy from/to anything that is mounted...
- MNTLIST="`df | grep "/dev/" | cut -f 1 -d " " | tr "\n" " "`"
+ MNTLIST="`/bin/df | grep "/dev/" | cut -f 1 -d " " | tr "\n" " "`"
  for MNTONE in $MNTLIST
  do
-  NONMATCH="`echo -n "$PROBEPARTALL" | grep -v "$MNTONE"`"
+  NONMATCH="`echo "$PROBEPARTALL" | grep -v "$MNTONE"`"
   PROBEPARTALL="$NONMATCH"
  done
  #...PROBEPARTALL has mounted partitions removed.
- DISKLIST="`echo -n "$PROBEDISKALL" | cut -f 1 -d "|" | tr "\n" " "`"
+ DISKLIST="`echo "$PROBEDISKALL" | cut -f 1 -d "|" | tr "\n" " "`"
  for DISKONE in $DISKLIST
  do
   if [ ! "`echo "$MNTLIST" | grep "$DISKONE"`" = "" ];then
-   NONMATCH="`echo -n "$PROBEDISKALL" | grep -v "$DISKONE"`"
+   NONMATCH="`echo "$PROBEDISKALL" | grep -v "$DISKONE"`"
    PROBEDISKALL="$NONMATCH"
   fi
  done
@@ -113,7 +113,7 @@ while [ 1 ];do #first loop.
 
 # Added by LC
 # we remove the information message at beginning of the script
-kill $XPID >/dev/null 2>&1
+kill $XPID >$OUT 2>&1
 
 BLURB1="Welcome to Pudd, the Puppy universal dd drive/partition/image-file backup/rescue program!
 This program will copy any drive, partition, or image-file to another drive, partition
@@ -184,9 +184,9 @@ case ${RETVAL} in
       sync
       umount $ONEUSBMNT 2> /tmp/umounterr.txt
      done
-     modprobe -r usb-storage
+     modprobe $VERB -r usb-storage
      xmessage -bg "#ff00ff" -title "Puppy universal dd: probe USB" -center -buttons "" "Wait awhile for the usb-storage driver to reload..." &
-     modprobe usb-storage
+     modprobe $VERB usb-storage
      killall xmessage
      ;;
    15)# probe ZIP
@@ -203,17 +203,17 @@ case ${RETVAL} in
     xmessage -bg "#ffe0e0" -center -name "Pudd" -title "Puppy universal dd: probe ZIP" -buttons "Parallel port ZIP":14,"IDE (internal) ZIP":15,"none of these:10" "Please choose what type of ZIP drive you have..."
     RETVAL=$?
     if [ $RETVAL -eq 14 ];then
-     modprobe -r imm #won't be loaded first time probably.
+     modprobe $VERB -r imm #won't be loaded first time probably.
      sleep 1
-     modprobe imm
+     modprobe $VERB imm
      if [ $? -eq 0 ];then
       ZIPLOADED="imm"
      fi
     fi
     if [ $RETVAL -eq 15 ];then
-     modprobe -r ide-floppy
+     modprobe $VERB -r ide-floppy
      sleep 1
-     modprobe ide-floppy
+     modprobe $VERB ide-floppy
      if [ $? -eq 0 ];then
       ZIPLOADED="ide-floppy"
      fi
@@ -226,13 +226,13 @@ case ${RETVAL} in
       #have to find the partition...
       #(got code for this out of rc.sysinit)...
       ZIPDRIVE="`echo "$PROBEZIP" | cut -f 1 -d '|'`"
-      ZIPDRIVX="`echo -n $ZIPDRIVE | cut -f 3 -d '/'`"
+      ZIPDRIVX="`echo $ZIPDRIVE | cut -f 3 -d '/'`"
       PHOM4="`
-echo -n $ZIPDRIVX
+echo $ZIPDRIVX
 echo "4"
 `"
       PHOM1="`
-echo -n $ZIPDRIVX
+echo $ZIPDRIVX
 echo "1"
 `"
       if [ ! "$ZIPDRIVE" = "" ];then
@@ -313,7 +313,7 @@ ALLDISKSS="`echo "$ALLDISKSM" | tr "\n" ":" | sed -e 's/:/ /g'`" #single line.
 
 if [ "$SOURCECHOICE" = "partition" ];then
  SOURCETAG="`Xdialog --wmclass "Pudd" --title "Puppy universal dd: choose source partition" --stdout \
- --no-tags --menubox "Choose the partition to be copied from:" 0 0 0 $ALLPARTSS 2> /dev/null `"
+ --no-tags --menubox "Choose the partition to be copied from:" 0 0 0 $ALLPARTSS 2>$ERR `"
  if [ ! $? -eq 0 ];then
   exit
  fi
@@ -325,7 +325,7 @@ fi
 
 if [ "$SOURCECHOICE" = "drive" ];then
  SOURCETAG="`Xdialog --wmclass "Pudd" --title "Puppy universal dd: choose source drive" --stdout \
- --no-tags --menubox "Choose the drive to be copied from:" 0 0 0 $ALLDISKSS 2> /dev/null `"
+ --no-tags --menubox "Choose the drive to be copied from:" 0 0 0 $ALLDISKSS 2>$ERR `"
  if [ ! $? -eq 0 ];then
   exit
  fi
@@ -449,7 +449,7 @@ case ${RETVAL} in
      ;;
    16)# fdisk
      FDISKTAG="`Xdialog --wmclass "Pudd" --title "Puppy universal dd: run fdisk" --stdout \
- --no-tags --menubox "Choose the drive to be examined by fdisk:" 0 0 0 $ALLDISKSS 2> /dev/null `"
+ --no-tags --menubox "Choose the drive to be examined by fdisk:" 0 0 0 $ALLDISKSS 2>$ERR `"
      if [ $? -eq 0 ];then
       FDISKPART="`echo "$ALLDISKSM" | grep "$FDISKTAG" | cut -f 2 -d " " | cut -f 1 -d "|"`"
       rxvt -e fdisk $FDISKPART
@@ -473,10 +473,10 @@ if [ "$DESTCHOICE" = "remote" ];then
   if [ ! $? -eq 0 ];then
    exit
   fi
-  REMOTEADDR=`echo -n "$RETSTR" | cut -f 1 -d "|"`
-  REMOTEPORT=`echo -n "$RETSTR" | cut -f 2 -d "|"`
+  REMOTEADDR=`echo "$RETSTR" | cut -f 1 -d "|"`
+  REMOTEPORT=`echo "$RETSTR" | cut -f 2 -d "|"`
   #need to know that remote PC is reachable...
-  RETSTR="`ping -c 1 -q $REMOTEADDR | grep ' 0% '`" #not to REMOTEPORT, as will mess up data transfer.
+  RETSTR="`ping -c 1 $Q $REMOTEADDR | grep ' 0% '`" #not to REMOTEPORT, as will mess up data transfer.
   if [ "$RETSTR" = "" ];then
    ERRBLURB="ERROR, $REMOTEADDR IS NOT REACHABLE!
 
@@ -493,7 +493,7 @@ fi
 if [ "$DESTCHOICE" = "partition" ];then
  while [ 1 ];do #WHILE4
   DESTTAG="`Xdialog --wmclass "Pudd" --title "Puppy universal dd: choose destination partition" --stdout \
- --no-tags --menubox "Choose the partition to be copied to:" 0 0 0 $ALLPARTSS 2> /dev/null `"
+ --no-tags --menubox "Choose the partition to be copied to:" 0 0 0 $ALLPARTSS 2>$ERR `"
   if [ ! $? -eq 0 ];then
    exit
   fi
@@ -523,7 +523,7 @@ fi
 
 if [ "$DESTCHOICE" = "drive" ];then
  while [ 1 ];do
-  DESTTAG="`Xdialog --wmclass "Pudd" --title "Puppy universal dd: choose destination drive" --stdout --no-tags --menubox "Choose the drive to be copied to:" 0 0 0 $ALLDISKSS 2> /dev/null `"
+  DESTTAG="`Xdialog --wmclass "Pudd" --title "Puppy universal dd: choose destination drive" --stdout --no-tags --menubox "Choose the drive to be copied to:" 0 0 0 $ALLDISKSS 2>$ERR `"
   if [ ! $? -eq 0 ];then
    exit
   fi
@@ -562,8 +562,8 @@ else
 fi
 
 #v1.0.7
-#SPACEINFO="`df | grep -v "rootfs" | grep -v "/dev/loop0"`"
-SPACEINFO="`df -k | grep -v "rootfs" | grep -v "/dev/loop0" | grep -v "/dev/loop3" | grep -v "none"`"
+#SPACEINFO="`/bin/df | grep -v "rootfs" | grep -v "/dev/loop0"`"
+SPACEINFO="`/bin/df -k | grep -v "rootfs" | grep -v "/dev/loop0" | grep -v "/dev/loop3" | grep -v "none"`"
 
 if [ "$DESTCHOICE" = "file" ];then
  DESTXTN="${DESTPART}.gz"
@@ -596,7 +596,7 @@ RETVAL=$?
 case ${RETVAL} in
    10)# continue
      #finally, get to try dd...
-     echo '#!/bin/sh' > /tmp/backuppartition.sh
+     echo '#!/bin/ash' >/tmp/backuppartition.sh
      if [ "$DESTCHOICE" = "file" ];then
 
       #if source is partition, zeroise unused part for max compression...
@@ -609,9 +609,9 @@ is zeroised. This involves temporarily mounting it on /mnt/tmp,
 writing zeroes to the unused areas, then unmounting it.
 Would you like to do this size optimisation?" 0 0
         if [ $? -eq 0 ];then
-         mkdir /mnt/tmp 2> /dev/null
+         mkdir $VERB /mnt/tmp 2>$ERR
          if [ ! "`echo "$SOURCEFS" | grep --extended-regexp "ext2|ext3|Ext2|Ext3"`" = "" ];then
-          APPLYFS="`echo -n "$SOURCEFS" | tr "E" "e"`"
+          APPLYFS="`echo "$SOURCEFS" | tr "E" "e"`"
          else
           if [ ! "`echo "$SOURCEFS" | grep --extended-regexp "FAT12|FAT16|FAT32|msdos|vfat"`" = "" ];then
            APPLYFS="vfat"
@@ -619,79 +619,79 @@ Would you like to do this size optimisation?" 0 0
            APPLYFS="reiserfs"
           fi
          fi
-         echo 'echo "Now zeroising unused areas of $2 ..."' >> /tmp/backuppartition.sh
-         echo 'echo "For a large partition, this may take awhile..."'  >> /tmp/backuppartition.sh
-         echo "mount -t $APPLYFS $SOURCEPART /mnt/tmp"  >> /tmp/backuppartition.sh
-         echo 'PARTFREE=`df | grep "$2" | tr -s " " | head -n 1 | cut -f 4 -d " "`'  >> /tmp/backuppartition.sh
-         echo 'cd /mnt/tmp'  >> /tmp/backuppartition.sh
-         echo 'dd if=/dev/zero of=empty.tmp bs=1024 count=$PARTFREE'  >> /tmp/backuppartition.sh
-         echo 'sync'  >> /tmp/backuppartition.sh
-         echo 'rm -f empty.tmp'  >> /tmp/backuppartition.sh
-         echo 'sync'  >> /tmp/backuppartition.sh
-         echo 'cd /'  >> /tmp/backuppartition.sh
-         echo 'umount /mnt/tmp'  >> /tmp/backuppartition.sh
-         echo 'rmdir /mnt/tmp'  >> /tmp/backuppartition.sh
-         echo 'echo "...done"'  >> /tmp/backuppartition.sh
-         echo 'echo'  >> /tmp/backuppartition.sh
+         echo 'echo "Now zeroising unused areas of $2 ..."' >>/tmp/backuppartition.sh
+         echo 'echo "For a large partition, this may take awhile..."'  >>/tmp/backuppartition.sh
+         echo "mount $VERB $VERB -t $APPLYFS $SOURCEPART /mnt/tmp"  >>/tmp/backuppartition.sh
+         echo 'PARTFREE=`/bin/df | grep "$2" | tr -s " " | head -n 1 | cut -f 4 -d " "`'  >>/tmp/backuppartition.sh
+         echo 'cd /mnt/tmp'  >>/tmp/backuppartition.sh
+         echo 'dd if=/dev/zero of=empty.tmp bs=1024 count=$PARTFREE'  >>/tmp/backuppartition.sh
+         echo 'sync'  >>/tmp/backuppartition.sh
+         echo 'rm -f empty.tmp'  >>/tmp/backuppartition.sh
+         echo 'sync'  >>/tmp/backuppartition.sh
+         echo 'cd /'  >>/tmp/backuppartition.sh
+         echo 'umount /mnt/tmp'  >>/tmp/backuppartition.sh
+         echo 'rmdir /mnt/tmp'  >>/tmp/backuppartition.sh
+         echo 'echo "...done"'  >>/tmp/backuppartition.sh
+         echo 'echo'  >>/tmp/backuppartition.sh
         fi
        fi
       fi
 
-      echo 'echo "Now copying $2 to $1, please wait very patiently..."' >> /tmp/backuppartition.sh
+      echo 'echo "Now copying $2 to $1, please wait very patiently..."' >>/tmp/backuppartition.sh
       echo "dd if=$SOURCEPART | gzip - > $DESTPART.gz" >>  /tmp/backuppartition.sh
       echo 'if [ ! $? -eq 0 ];then' >>  /tmp/backuppartition.sh
-      echo ' echo' >> /tmp/backuppartition.sh
-      echo ' echo "Read error, starting again, ignoring errors..."' >> /tmp/backuppartition.sh
-      echo " dd if=$SOURCEPART  conv=noerror | gzip - > $DESTPART.gz" >> /tmp/backuppartition.sh
-      echo 'fi' >> /tmp/backuppartition.sh
+      echo ' echo' >>/tmp/backuppartition.sh
+      echo ' echo "Read error, starting again, ignoring errors..."' >>/tmp/backuppartition.sh
+      echo " dd if=$SOURCEPART  conv=noerror | gzip - > $DESTPART.gz" >>/tmp/backuppartition.sh
+      echo 'fi' >>/tmp/backuppartition.sh
      else
       if [ "$DESTCHOICE" = "remote" ];then
-       echo 'echo "Now copying $2 to remote PC, please wait very patiently..."' >> /tmp/backuppartition.sh
-       echo "dd if=$SOURCEPART | gzip -c | nc $REMOTEADDR $REMOTEPORT" >> /tmp/backuppartition.sh
-       echo 'if [ ! $? -eq 0 ];then' >> /tmp/backuppartition.sh
-       echo ' echo' >> /tmp/backuppartition.sh
-       echo ' echo "Read error, starting again and will ignore errors..."' >> /tmp/backuppartition.sh
-       echo ' echo "KILL THE NETCAT LISTENER ON REMOTE PC, AND START IT AGAIN"' >> /tmp/backuppartition.sh
-       echo ' echo -n "DO THAT RIGHT NOW, THEN PRESS ENTER KEY: "' >> /tmp/backuppartition.sh
-       echo ' read mmmm' >> /tmp/backuppartition.sh
-       echo " dd if=$SOURCEPART conv=noerror | gzip -c | nc $REMOTEADDR $REMOTEPORT" >> /tmp/backuppartition.sh
-       echo 'fi' >> /tmp/backuppartition.sh
+       echo 'echo "Now copying $2 to remote PC, please wait very patiently..."' >>/tmp/backuppartition.sh
+       echo "dd if=$SOURCEPART | gzip -c | nc $REMOTEADDR $REMOTEPORT" >>/tmp/backuppartition.sh
+       echo 'if [ ! $? -eq 0 ];then' >>/tmp/backuppartition.sh
+       echo ' echo' >>/tmp/backuppartition.sh
+       echo ' echo "Read error, starting again and will ignore errors..."' >>/tmp/backuppartition.sh
+       echo ' echo "KILL THE NETCAT LISTENER ON REMOTE PC, AND START IT AGAIN"' >>/tmp/backuppartition.sh
+       echo ' echo "DO THAT RIGHT NOW, THEN PRESS ENTER KEY: "' >>/tmp/backuppartition.sh
+       echo ' read mmmm' >>/tmp/backuppartition.sh
+       echo " dd if=$SOURCEPART conv=noerror | gzip -c | nc $REMOTEADDR $REMOTEPORT" >>/tmp/backuppartition.sh
+       echo 'fi' >>/tmp/backuppartition.sh
       else
-       echo 'echo "Now copying $2 to $1, please wait very patiently..."' >> /tmp/backuppartition.sh
-       echo "dd if=$SOURCEPART of=$DESTPART" >> /tmp/backuppartition.sh
-       echo 'if [ ! $? -eq 0 ];then' >> /tmp/backuppartition.sh
-       echo ' echo' >> /tmp/backuppartition.sh
-       echo ' echo "Read error, starting again and will ignore errors..."' >> /tmp/backuppartition.sh
-       echo " dd if=$SOURCEPART of=$DESTPART conv=noerror" >> /tmp/backuppartition.sh
-       echo 'fi' >> /tmp/backuppartition.sh
+       echo 'echo "Now copying $2 to $1, please wait very patiently..."' >>/tmp/backuppartition.sh
+       echo "dd if=$SOURCEPART of=$DESTPART" >>/tmp/backuppartition.sh
+       echo 'if [ ! $? -eq 0 ];then' >>/tmp/backuppartition.sh
+       echo ' echo' >>/tmp/backuppartition.sh
+       echo ' echo "Read error, starting again and will ignore errors..."' >>/tmp/backuppartition.sh
+       echo " dd if=$SOURCEPART of=$DESTPART conv=noerror" >>/tmp/backuppartition.sh
+       echo 'fi' >>/tmp/backuppartition.sh
       fi
      fi
 
-     echo 'sync' >> /tmp/backuppartition.sh
-     echo 'echo' >> /tmp/backuppartition.sh
+     echo 'sync' >>/tmp/backuppartition.sh
+     echo 'echo' >>/tmp/backuppartition.sh
      if [ ! "$ALLOWGROW" = "" ];then
-      echo 'echo "Resizing $4 filesystem to fill $3 Kbyte partition..."' >> /tmp/backuppartition.sh
+      echo 'echo "Resizing $4 filesystem to fill $3 Kbyte partition..."' >>/tmp/backuppartition.sh
       if [ ! "`echo "$ALLOWGROW" | grep --extended-regexp "ext2|ext3|Ext2|Ext3"`" = "" ];then
-       echo 'echo "First check and fix f.s...."' >> /tmp/backuppartition.sh
-       echo "e2fsck -f -y $DESTPART" >> /tmp/backuppartition.sh
-       echo "sync" >> /tmp/backuppartition.sh
-       echo 'echo "Now resizing f.s...."' >> /tmp/backuppartition.sh
-       echo "resize2fs -f $DESTPART" >> /tmp/backuppartition.sh
+       echo 'echo "First check and fix f.s...."' >>/tmp/backuppartition.sh
+       echo "e2fsck -f -y $DESTPART" >>/tmp/backuppartition.sh
+       echo "sync" >>/tmp/backuppartition.sh
+       echo 'echo "Now resizing f.s...."' >>/tmp/backuppartition.sh
+       echo "resize2fs -f $DESTPART" >>/tmp/backuppartition.sh
       else
        if [ ! "`echo "$ALLOWGROW" | grep --extended-regexp "FAT12|FAT16|FAT32|msdos|vfat"`" = "" ];then
-        echo 'echo "WARNING: Immature code, do not use for anything critical!"' >> /tmp/backuppartition.sh
-        echo 'echo "         Changes have been backed up in /tmp/fsresizebackup.dat"' >> /tmp/backuppartition.sh
-        echo 'echo "         (see fsresize doc page how to restore f.s.)"' >> /tmp/backuppartition.sh
-        echo "fsresize $DESTPART $DESTSIZE -b /tmp/fsresizebackup.dat" >> /tmp/backuppartition.sh
+        echo 'echo "WARNING: Immature code, do not use for anything critical!"' >>/tmp/backuppartition.sh
+        echo 'echo "         Changes have been backed up in /tmp/fsresizebackup.dat"' >>/tmp/backuppartition.sh
+        echo 'echo "         (see fsresize doc page how to restore f.s.)"' >>/tmp/backuppartition.sh
+        echo "fsresize $DESTPART $DESTSIZE -b /tmp/fsresizebackup.dat" >>/tmp/backuppartition.sh
        fi
       fi
-      echo 'echo "...done"' >> /tmp/backuppartition.sh
-      #echo 'fi' >> /tmp/backuppartition.sh
+      echo 'echo "...done"' >>/tmp/backuppartition.sh
+      #echo 'fi' >>/tmp/backuppartition.sh
      fi
-     echo 'echo -n "Backup finished. Press ENTER key to exit: "' >> /tmp/backuppartition.sh
-     echo 'read nnn' >> /tmp/backuppartition.sh
+     echo 'echo "Backup finished. Press ENTER key to exit: "' >>/tmp/backuppartition.sh
+     echo 'read nnn' >>/tmp/backuppartition.sh
      sync
-     chmod 755 /tmp/backuppartition.sh
+     chmod $VERB 755 /tmp/backuppartition.sh
      rxvt -name Pudd -title "Puppy universal dd: copying" -bg "#ffff00" -geometry 80x8 -e /tmp/backuppartition.sh ${DESTPART} ${SOURCEPART} ${DESTSIZE} ${ALLOWGROW} 
      ;;
    13)# EXIT
