woof-code/rootfs-skeleton/usr/sbin/pupcamera: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pupcamera b/woof-code/rootfs-skeleton/usr/sbin/pupcamera
--- a/woof-code/rootfs-skeleton/usr/sbin/pupcamera
+++ b/woof-code/rootfs-skeleton/usr/sbin/pupcamera
@@ -31,7 +31,7 @@
 #GTKDIALOGEXE=gtkdialog4
 #HOSTNAME=puppypc28154
 #HOSTTYPE=i486
-#IFS='   
+#IFS='
 #'
 #INTERFACE=6/1/1
 #MACHTYPE=i486-t2-linux-gnu
@@ -51,6 +51,29 @@
 
 export TEXTDOMAIN=pupcamera
 export OUTPUT_CHARSET=UTF-8
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 GTKDIALOGEXE='gtkdialog'
 [ "`which gtkdialog4`" ] && GTKDIALOGEXE='gtkdialog4'
@@ -101,7 +124,7 @@ fi
 echo -n "" > /tmp/pupcamera_ports
 CAMERAINFO=""
 if [ "$BUSNUM" ];then
- 
+
  #get product description from lsusb (usbutils pkg)...
  VENDORINSERT=""
  if which lsusb;then
@@ -117,7 +140,7 @@ if [ "$BUSNUM" ];then
    fi
   fi
  fi
- 
+
  CAMERAINFO="<text use-markup=\"true\"><label>\"$(gettext 'A camera is detected connected via USB.')
 $(gettext 'The Linux kernel has identified it as:')
  $(gettext 'Type:') <b>${PRODUCTDESC}</b>
