woof-code/rootfs-skeleton/usr/sbin/pupdial_wizard_helper: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pupdial_wizard_helper b/woof-code/rootfs-skeleton/usr/sbin/pupdial_wizard_helper
--- a/woof-code/rootfs-skeleton/usr/sbin/pupdial_wizard_helper
+++ b/woof-code/rootfs-skeleton/usr/sbin/pupdial_wizard_helper
@@ -12,6 +12,29 @@
 export TEXTDOMAIN=pupdial_wizard_helper
 export OUTPUT_CHARSET=UTF-8
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 DEFAULTCONNECT="`cat /usr/local/bin/defaultconnect | tail -n 1 | tr -s " " | cut -f 2 -d " "`"
 [ "$DEFAULTCONNECT" == "pupdial" ] && exit
 
