woof-code/rootfs-skeleton/usr/sbin/pupdial_init_hotpluggable: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pupdial_init_hotpluggable b/woof-code/rootfs-skeleton/usr/sbin/pupdial_init_hotpluggable
--- a/woof-code/rootfs-skeleton/usr/sbin/pupdial_init_hotpluggable
+++ b/woof-code/rootfs-skeleton/usr/sbin/pupdial_init_hotpluggable
@@ -1,7 +1,7 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler Dec. 2010. License GPL v3 /usr/share/doc/legal.
-#called from pupdial. Based upon earlier scripts by Richard Erwin.
-#there were scripts in /etc/init.d created by Richard, now moved to here.
+# Called from pupdial. Based upon earlier scripts by Richard Erwin.
+# There were scripts in /etc/init.d created by Richard, now moved to here.
 #101205 use modem-stats to eliminate non-responsive ttyUSB ports.
 #101206 wait. remember previous modem.
 #101207 if usb-modeswitch has already set /dev/gsmmodem, use it.
@@ -14,14 +14,37 @@
 export TEXTDOMAIN=pupdial_init_hotpluggable
 export OUTPUT_CHARSET=UTF-8
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 #hso.ko: this site http://www.pharscape.org/hso.html states that the hso driver is in kernel
 #2.6.27. Yes, it is in kernel/drivers/net/usb/hso.ko. It is also in the 2.6.30.* kernel.
 #however it is missing from 2.6.31 and later kernels...
 #oh, i see why. I have configured 2.6.31 and later with 'rfkill' turned off, which
 #hso requires: in kernel source drivers/net/usb/Kconfig:
 #config USB_HSO
-#	tristate "Option USB High Speed Mobile Devices"
-#	depends on USB && RFKILL
+#       tristate "Option USB High Speed Mobile Devices"
+#       depends on USB && RFKILL
 #101210 ...I was able to compile it separately, have put it in zzz pkg, for testing.
 #110302 2.6.32.28 kernel has rfkill and hso enabled. no longer using zzz pkg.
 
