woof-code/rootfs-skeleton/usr/sbin/puppyinstaller: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller b/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
--- a/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
+++ b/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
@@ -2,9 +2,9 @@
 #(c) Copyright Barry Kauler 2006 www.puppylinux.com
 #2007 Lesser GPL licence v2 (/usr/share/doc/legal/lgpl-2.1.txt)
 # BK july 2007:
-#/usr/sbin/puppyinstaller-217 is heavily modified by Dougal (based on
-# puppyinstaller from v2.14). Was used in 216 and 217.
-#/usr/sbin/puppyinstaller-bk is the v2.14 one with minimal mods. for 2.17.1+
+#  /usr/sbin/puppyinstaller-217 is heavily modified by Dougal (based on
+#   puppyinstaller from v2.14). Was used in 216 and 217.
+#  /usr/sbin/puppyinstaller-bk is the v2.14 one with minimal mods. for 2.17.1+
 #aug 2007 updated for 2.20: 'root=/dev/ram0' removed as using initramfs.
 #v3.94 BK dec 2007: no longer any hd* drives.
 #v3.95 BK jan 2008: handle Classmate laptop.
@@ -33,6 +33,29 @@
 #100719 warning frugal, do not install to folder if want save session to entire partition.
 #100720 removed 'nosmp' kernel boot param.
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 export LANG=C
 #NEWVER="`cat /etc/puppyversion`"
 KERNELVER="`uname -r`"
@@ -58,7 +81,7 @@ fsfunc() { #f.s. type param passed in
  JFS)      FSTYPE="jfs" ;;
  XFS)      FSTYPE="xfs" ;;
  *)        FSTYPE="" ;; #100412
- esac 
+ esac
 }
 
 ispupfunc() { #two params: fstype partition
@@ -115,11 +138,11 @@ not boot, it may be that the partition(s) is confusing the PC's BIOS.
 Personally, I was able to fix such a USB drive by wiping the existing partition
 and then create it again using GParted.
 The steps to do this are very simple: when GParted is running,
- 1. delete all partitions on the USB device. 
+ 1. delete all partitions on the USB device.
  2. Create a new primary FAT16 partition, to fill the entire drive.
  3. Click the 'Apply' button to write changes to the USB drive.
- 4. Set the 'boot' configuration flag (right-click on partition, 
-    choose 'manage flags'). 
+ 4. Set the 'boot' configuration flag (right-click on partition,
+    choose 'manage flags').
 
 If GParted is installed, it is now running and you can do the above.
 Quiting GParted will return you to the Puppy Universal Installer...
@@ -234,7 +257,7 @@ if [ "$SRCPATH" = "" ];then
   else
    Xdialog --wmclass "gtkdialog2" --left --title "Puppy universal installer: ERROR" --msgbox "Sorry, Puppy is not on the CD.\nPlease mount the CD using one of the mount programs\n(see File Managers menu) then click OK button..." 0 0
    RETVAL=1
-  fi 
+  fi
  fi
  if [ ! $RETVAL -eq 0 ];then #DIRECTORY
   SRCFPATH="`Xdialog --wmclass "gtkdialog2" --left --backtitle "Please find the latest Puppy files\nvmlinuz, initrd.gz and ${DISTRO_FILE_PREFIX}-$NEWVER.sfs,\nTHEN HIGHLIGHT ANY ONE OF THEM\nand click the OK button" --title "Puppy universal installer" --stdout --no-buttons --no-cancel --fselect "*" 0 0`"
@@ -295,7 +318,7 @@ case $PMEDIA in
   done
  ;;
  cd)
-  #find cd drives... 
+  #find cd drives...
   CDDRIVES="`echo "$PROBEDISK" | grep '|optical|' | cut -f 3 -d '/' | cut -f 1 -d '|' | tr "\n" " "`"
   SELECTIONS=""
   for ONEHD in $CDDRIVES
@@ -352,7 +375,7 @@ chmod 755 /tmp/dlg1
 
 /tmp/dlg1
 [ $? -ne 0 ] && exit
- 
+
 DRVSEL="`cat /tmp/retval`"
 [ "$DRVSEL" = "" ] && exit
 
@@ -627,7 +650,7 @@ if [ ! "`echo "$RETTXT" | grep 'EXIT:REFORMAT'`" = "" ];then
    continue #BIG LOOP
   fi
   #exit
-  
+
  fi
 else
  DESTPART="`echo "$RETTXT" | grep 'EXIT:' | cut -f 2 -d ':'`"
@@ -694,16 +717,16 @@ case $FINALPMEDIA in
    DESTNUM="`echo -n "$DESTPART" | cut -b 4-5`"
    dd if=/dev/$DESTDRV of=/tmp/mbr446.bin bs=446 count=1
    sync
-   
+
    #v3.95
    ALPHADUMP="`hexdump -C /tmp/mbr446.bin | cut -f 2 -d '|' | tr '\n' ' ' | tr -d ' '`"
    #this will be =1 if mbr has 'GRUB' in it, else =0...
    FLAGGRUB="`echo "$ALPHADUMP" | grep 'GRUB' | wc -l`"
-   
+
    #v3.97 have a case where normal bootable flash vfat pen drive has the
    #string 'GRUB.Geom.HardDisk.Read.Error' in the mbr...
    [ "$FLAGGRUB" = "1" ] && [ "`echo "$ALPHADUMP" | grep 'GRUB.Geom.HardDisk.Read.Error'`" != "" ] && FLAGGRUB="0"
-   
+
    if [ "`hexdump -x /tmp/mbr446.bin | tr -s " " | cut -f 2-9 -d " " | grep '[1-9a-zA-Z]'`" = "" -o "$FLAGGRUB" = "1" ];then
     MBRCHOICE="`Xdialog --wmclass "gtkdialog2" --left --title "Puppy Universal Installer" --no-cancel --stdout --menubox "The bootstrap loader code is missing from the MBR (Master Boot Record),\nmeaning that the USB drive will not boot. Please choose one of the\nfollowing to fix this. Personally, I have had success with mbr.bin." 0 0 4 sys-nopart.mbr "Bootstrap loader code, created by JustGreg" mbr.bin "From the Syslinux package" mbrfat.bin "From the makebootfat package" spb2_mbr.bin "From spblinux, created by Christian Ostheimer" `"
    else
@@ -718,7 +741,7 @@ case $FINALPMEDIA in
      sync
     fi
    fi
-   
+
    #check that partition has 'boot' flag set...
    QPATTERN="^Partition ${DESTNUM}:"
    if [ "`disktype /dev/$DESTDRV | grep "$QPATTERN" | grep 'bootable'`" = "" ];then
@@ -1048,7 +1071,7 @@ Click OK to quit..."
   DESTMNTPT="`mount | grep "/dev/$DESTPART" | tr -s " " | cut -f 3 -d " "`"
   #v2.02 ntfs-3g needs this...
   #[ "$DESTMNTPT" = "" ] && DESTMNTPT="`ps -e | grep -o ntfs\-3g.* | grep "/dev/$DESTPART" | sed -e 's/[^a-zA-Z0-9/._\-]/ /g' | tr -s ' ' | tr ' ' "\n" | grep '^/mnt/'`"
-  
+
    [ "$DESTMNTPT" = "" ] && DESTMNTPT="`ps -e | grep -o 'ntfs\-3g.*' | grep "/dev/$DESTPART" | tr '\t' ' ' | tr -s ' ' | tr ' ' "\n" | grep '^/mnt/'`"
 
   if [ "$DESTMNTPT" = "" ];then
@@ -1070,7 +1093,7 @@ and you may choose to upgrade or totally replace."
   if [ ! "$DESTFS" = "vfat" ];then
    Xdialog --wmclass "gtkdialog2" --left --buttons-style text --title "Puppy Universal Installer" --ok-label "FRUGAL" --cancel-label "FULL" --yesno "You have chosen to install to /dev/$DESTPART, which appears to be an internal
 hard drive ($FINALPMEDIA).
-$PREVPUPMSG 
+$PREVPUPMSG
 
 There are two ways to install Puppy to the partition:
 
@@ -1115,10 +1138,10 @@ Click window close box to quit..." 0 0
    GRUB_PARTN=`expr $GRUB_PARTN - 1`
    GRUB_PARTN=",$GRUB_PARTN"
   fi
-   
+
   #INSTOPTION, install puppy to DESTPART...
   if [ "$INSTOPTION" = "1" ];then #frugal.
-  
+
    case $DESTFS in #100719
     ext2|ext3|ext4|reiserfs|minix|btrfs)
      Xdialog --stdout --wmclass "gtkdialog2" --left --title "Puppy Universal Installer" --msgbox "You have chosen a frugal installation. As you are installing Puppy to a
@@ -1137,7 +1160,7 @@ If you intend to, or might want to, save the session to entire partition, do
 NOT install to a sub-directory, leave the folder field empty..." 0 0
     ;;
    esac
-   
+
    Xdialog --stdout --wmclass "gtkdialog2" --left --title "Puppy Universal Installer" --fixed-font --no-cancel --inputbox "Puppy is going to be installed to partition ${DESTPART}, which is currently
 mounted on path ${DESTMNTPT}. As this will be a frugal install, you can
 choose to place the Puppy files in a folder. This is very convenient if you
@@ -1153,7 +1176,7 @@ do not type the '). Type a single word consisting of characters and numeric
 digits only, or leave blank if you want to install Puppy at '/'..." 0 0 "puppy${NEWVER}" >/tmp/NEWPSUBDIR
    [ $? -ne 0 ] && exit
    NEWPSUBDIR="`cat /tmp/NEWPSUBDIR | sed -e 's%/%%g'`"
-   
+
    yaf-splash -font "8x16" -outline 0 -margin 4 -bg orange -text "Please wait, copying files to $DESTPART, in folder $NEWPSUBDIR..." &
    XPID=$!
    mkdir -p $DESTMNTPT/$NEWPSUBDIR
@@ -1170,9 +1193,9 @@ digits only, or leave blank if you want to install Puppy at '/'..." 0 0 "puppy${
    sync
    kill $XPID
    umount /dev/$DESTPART
-   
+
    if [ "`echo -n "$DESTFS" | grep -E 'msdos|vfat'`" != "" ];then
-   
+
     Xdialog --wmclass "gtkdialog2" --left --title "Puppy Universal Installer" --ok-label "CREATE_BOOT_DISK" --cancel-label "NO_BOOT_DISK" --yesno "
 A floppy disk can be used to boot Puppy.
 Currently we are offering WakePup2, a generic boot floppy
@@ -1183,7 +1206,7 @@ Grub bootloader." 0 0
     if [ $? -eq 0 ];then
      /usr/sbin/wakepup2
     fi
-    
+
    fi
    xNEWPSUBDIR=""
    OPTIONPSUBDIR=""
@@ -1239,7 +1262,7 @@ just click the 'OK' button to finish the installation, then go to the
 not need the text in the text editor window, as the installers will probe
 your PC for all installations of Puppy and other operating systems).
 ${grubEXTRAMSG}" 0 0
-   
+
    #finished. could put up a final dlg here, then quit script.
    Xdialog --wmclass "gtkdialog2" --title "Puppy Universal Installer" --msgbox "Okay, all done!" 0 0
    exit
@@ -1286,7 +1309,7 @@ ${grubEXTRAMSG}" 0 0
    cp -a -u --remove-destination $DESTMNTPT/srcmntpt/usr $DESTMNTPT/
    cp -a -u --remove-destination $DESTMNTPT/srcmntpt/var $DESTMNTPT/
    [ -d $DESTMNTPT/srcmntpt/opt ] && cp -a -u --remove-destination $DESTMNTPT/srcmntpt/opt $DESTMNTPT/ #v2.11
-   
+
    #v2.12 external modules file...
    #w482 fix handling if separate zdrv file...
    [ -f $SRCPATH/${ZDRVSFS} ] && cp -af $SRCPATH/${ZDRVSFS} $DESTMNTPT/
@@ -1306,7 +1329,7 @@ ${grubEXTRAMSG}" 0 0
     cp -af /lib/modules/$KERNELVER/initrd/* $DESTMNTPT/lib/modules/$KERNELVER/
     depmod -b $DESTMNTPT
    fi
-   
+
    #100113 /bin/TARGETEXES has list of executables that were copied from initrd (and not in main f.s.)...
    if [ -f /bin/TARGETEXES ];then
     for ONEEXE in `cat /bin/TARGETEXES` #ex: sbin/e2fsck
@@ -1323,7 +1346,7 @@ ${grubEXTRAMSG}" 0 0
     cp -a -f /lib/consolefonts/* ${DESTMNTPT}/lib/consolefonts/
    fi
 
-   
+
    mkdir $DESTMNTPT/sys 2>/dev/null
    rm -f $DESTMNTPT/var/log/modprobes.log 2>/dev/null #v2.13 see /sbin/modprobe script.
    #...not necessary, not using this any more.
@@ -1342,7 +1365,7 @@ ${grubEXTRAMSG}" 0 0
    Xdialog --wmclass "gtkdialog2" --title "Puppy Universal Installer" --no-buttons --infobox "Please wait, executing rc.update script..." 0 0 60000 &
    XPID=$!
    sleep 2
-   
+
    if [ -f $DESTMNTPT/etc/puppyversion ];then #historical file, old installations.
     echo -n "$PUPVEROLD" > $DESTMNTPT/etc/puppyversion #set it back to what it was.
    fi
@@ -1351,7 +1374,7 @@ ${grubEXTRAMSG}" 0 0
     sed -e "$vPATTERN" $DESTMNTPT/etc/DISTRO_SPECS > /tmp/distro_specs_old
     cp -f /tmp/distro_specs_old $DESTMNTPT/etc/DISTRO_SPECS #set DISTRO_VERSION back to what it was.
    fi
-   
+
    #chroot $DESTMNTPT -c /etc/rc.d/rc.update option2hdinstall
    #busybox chroot does not have -c ...
    chroot $DESTMNTPT /etc/rc.d/rc.update option2hdinstall
@@ -1538,7 +1561,7 @@ ordering as reported by Pmount, which may be wrong for GRUB!
 
      Xdialog --wmclass "gtkdialog2" --left --title "Universal Installer" --msgbox "You have chosen to update an existing GRUB installation.
 This requires a final manual step...
-Find the \"menu.lst\" file (usually in /boot/grub in the 
+Find the \"menu.lst\" file (usually in /boot/grub in the
 partition in which GRUB is installed) and insert this:
 
 title Puppy Linux $NEWVER full install in $DESTPART
