woof-code/rootfs-skeleton/usr/sbin/puppypdf: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/puppypdf b/woof-code/rootfs-skeleton/usr/sbin/puppypdf
--- a/woof-code/rootfs-skeleton/usr/sbin/puppypdf
+++ b/woof-code/rootfs-skeleton/usr/sbin/puppypdf
@@ -1,18 +1,39 @@
 #!/bin/bash
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #v426 nikin: bugfix.
-
-#info screen
-#choose input file
-#specify output file name
-#result notification
+# 1)Info screen
+# 2)Choose input file
+# 3)Specify output file name
+# 4)Result notification
 #
 ##----------- convert file to pdf ---------->
 #
-# author: thoughtjourney, 13/06/2005
+# Author: thoughtjourney, 13/06/2005
 #
 ##------------------------------------------>
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 #------------------------------variables--------------------------------->
 
@@ -25,7 +46,7 @@ SUPP="The Puppy PDF Conversion Wizard (puppyPDF) takes an input file\nand conver
 #-------------------------------functions-------------------------------->
 
 #---prints puppyPDF help--->
-function usage  
+function usage
 {
    echo
    echo -e "puppyPDF [OPTIONS... ]\n"
@@ -44,7 +65,7 @@ function gui
 }
 
 #---checks to ensure cli arguments are valid--->
-function checkArgs  
+function checkArgs
 {
    if [ -f "$INPUT" ]; then
 
@@ -70,7 +91,7 @@ function checkArgs
                  255)
                   echo "";;
                 esac
-           else 
+           else
                 #--- for cli interface --->
                 echo -e "\nPlease specify a valid input file\n"
                 usage
@@ -94,7 +115,7 @@ function checkArgs
            255)
              echo "";;
          esac
-      else 
+      else
          echo -e "\nPlease specify a valid input file\n"
          usage
          exit 0
@@ -109,7 +130,7 @@ function checkArgs
       if [ $GUI -eq 1 ]; then
          Xdialog --title "INFO BOX" \
                  --infobox "no output filename specified,\nusing $INPUT.pdf" 13 45 20000
-      fi         
+      fi
    fi
 
 
@@ -127,7 +148,7 @@ function checkArgs
              echo "";;
          esac
 
-       else      
+       else
          echo -e "$OUTPUT already exists! Press ENTER to continue or CTRL-C to quit\n"
          read in
        fi
@@ -161,13 +182,13 @@ function chooseFile
    INPUT=`Xdialog --stdout --title "Choose File to Convert" --fselect ~ 28 60 2>/dev/null`
 
    case $? in
-	   0)
+           0)
              Xdialog --title "Next step: save as..."\
                      --infobox "The next step is to specify the name of your pdf file.\n\n Press OK to continue.\n\n" 0 0 10000
              outputName;;
-	   1)
+           1)
              splash;;
-	   255)
+           255)
              echo "";;
    esac
 
@@ -180,11 +201,11 @@ function outputName
    OUTPUT=`Xdialog --stdout --title "Save As..." --fselect "$INPUT.pdf" 28 60 2>/dev/null`
 
    case $? in
-	   0)
+           0)
              finalConfirm;;
-	   1)
+           1)
              splash;;
-	   255)
+           255)
              echo "";;
    esac
 }
@@ -206,17 +227,17 @@ If this is correct, choose YES\n To quit, choose NO\n\n" 0 0
        splash;;
      255)
        echo "";;
-   esac 
+   esac
 }
 
 #---performs the file conversion--->
-function convert 
+function convert
 {
    echo printing...
 
    #-- convert to ps--->
    res=`abiword --to=ps --to-name="$TEMP" "$INPUT"`
- 
+
    if [ "$res" = "" ]; then
 
        #-- convert to pdf--->
@@ -235,7 +256,7 @@ function convert
           Xdialog --title "File Conversion error!"\
                   --infobox "There was an error in the file conversion process!\n\nCheck that your input file format is supported.\n\n\
 Press OK to exit.\n\n" 0 0 20000
-          rm -f "$OUTPUT"	
+          rm -f "$OUTPUT"
           exit 1
        fi
    else
@@ -246,7 +267,7 @@ Press OK to exit.\n\n" 0 0 20000
 Press OK to exit.\n\n" 0 0 20000
       rm -f "$OUTPUT"
       exit 1
-   fi	
+   fi
 }
 
 #---opens the pdf document--->
@@ -273,7 +294,7 @@ if [ "$1" ]; then
                                 ;;
         -o | -O)                shift
                                 OUTPUT=$1
-                                ;;	 
+                                ;;
         -h | --help )           usage
                                 exit
                                 ;;
