woof-code/rootfs-skeleton/usr/sbin/pupscan: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pupscan b/woof-code/rootfs-skeleton/usr/sbin/pupscan
--- a/woof-code/rootfs-skeleton/usr/sbin/pupscan
+++ b/woof-code/rootfs-skeleton/usr/sbin/pupscan
@@ -7,6 +7,29 @@
 #v431 rerwin: Add --silent option to only generate files, without display.
 #100108 BK 'scanpci' is not working properly xorg 7.5. actually it is no longer part of libpciaccess pkg.
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 [ "`echo $@ | grep ' *--silent *'`" != "" ] && SILENT=true || SILENT=false #v431
 KERNVER="`uname -r`"
 ZDRV='' #set in PUPSTATE.
@@ -161,9 +184,9 @@ USBMODINFO="`cat /lib/modules/$KERNVER/modules.alias | tr -s " " | grep '^alias 
    VENDOR="`echo -n "$ONENUM" | cut -f 1 -d '|' | cut -f 2 -d '='`"
    PRODUCT="`echo -n "$ONENUM" | cut -f 2 -d '|' | cut -f 2 -d '='`"
    ONEUSB="0x${VENDOR} 0x${PRODUCT}"
-   
+
    [ "$ONEUSB" = "0x0000 0x0000" ] && continue
-   
+
    YESPARA=no
    USBMODULE=""
    rm -f /tmp/usbmodulexxx
@@ -183,14 +206,14 @@ USBMODINFO="`cat /lib/modules/$KERNVER/modules.alias | tr -s " " | grep '^alias 
    done
    [ ! -s /tmp/usbdevdescr ] && [ "`grep ' ' /tmp/usbmodulexxx`" != "" ] && echo "Product=`cat /tmp/usbmodulexxx`" > /tmp/usbdevdescr && rm /tmp/usbmodulexxx #v425
    [ -f /tmp/usbmodulexxx ] && USBMODULE="`cat /tmp/usbmodulexxx`"
-   
+
    [ "$USBMODULE" = "" ] && USBMODULE="`echo "$USBMODINFO" | grep "$ONEUSB" | cut -f 3 -d ' ' | tail -n 1`" #v425
 
    #echo "DESCRIPTION: $CHIPDESC" >> /tmp/usbchipnummod.txt
    cat /tmp/usbdevdescr >> /tmp/usbchipnummod.txt
    echo "VendorID=$VENDOR  ProductID=$PRODUCT  KERNEL-MODULE=$USBMODULE" >> /tmp/usbchipnummod.txt
    echo  >> /tmp/usbchipnummod.txt
-   
+
   done
 
 [ ! -s /tmp/usbchipnummod.txt ] && echo "No plugged-in USB devices" > /tmp/usbchipnummod.txt #v3.01
@@ -216,7 +239,7 @@ MAINDIALOG="
 <wtitle>Puppy hardware-interfaces information</wtitle>
 <hbox>
  <vbox>
-  
+
   <frame Kernel modules>
   <hbox>
    <text><label>At bootup, Puppy examines the hardware interfaces to determine what kernel drivers (modules) to load, and does so. Click this button for information on loaded modules:</label></text>
@@ -258,7 +281,7 @@ MAINDIALOG="
   </frame>
 
   ${USBSECTION}
-  
+
   <frame result>
    <edit>
     <variable>INFO</variable>
@@ -267,7 +290,7 @@ MAINDIALOG="
     <height>300</height>
    </edit>
   </frame>
-  <hbox>     
+  <hbox>
    <button>
     <label>exit</label>
     <action>EXIT=EXIT</action>
@@ -289,7 +312,7 @@ MAINDIALOG="
 #  </hbox>
 #  </frame>
 
-rm -f /tmp/hwproberesult.txt #v425 erase stale info 
+rm -f /tmp/hwproberesult.txt #v425 erase stale info
 
 if [ "`which scanpci`" = "" ];then
  echo 'echo "This must be a cutdown Puppy that does not have the scanpci utility
