woof-code/rootfs-skeleton/usr/sbin/pusbmodeswitch: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pusbmodeswitch b/woof-code/rootfs-skeleton/usr/sbin/pusbmodeswitch
--- a/woof-code/rootfs-skeleton/usr/sbin/pusbmodeswitch
+++ b/woof-code/rootfs-skeleton/usr/sbin/pusbmodeswitch
@@ -2,6 +2,29 @@
 #Barry Kauler, LGPL 2010
 #Portions of this script are derived from the usb_modeswitch.tcl script created by Josua Dietze of the USB_ModeSwitch project (http://www.draisberghof.de/usb_modeswitch/).
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 #Upgraded version to utilize the integrated config directory, emulating the tcl wrapper script.
 ARGUMENTS="$@"
 [ "$ARGUMENTS" = "" -o "$ARGUMENTS" = "-W" ] \
@@ -47,7 +70,7 @@ pup_usb_modeswitch_func() {
  [ ! -d $DEVDIR ] \
   && echo "Top sysfs directory not found ($DEVDIR)! Exiting" \
   && return 0
- 
+
  IDV=""; IDP=""; UMA=""; UPR=""; USE=""
  [ -e $DEVDIR/idVendor ] && IDV="`cat $DEVDIR/idVendor`"
  [ -e $DEVDIR/idProduct ] && IDP="`cat $DEVDIR/idProduct`"
@@ -92,7 +115,7 @@ pup_usb_modeswitch_func() {
       break
      fi
     fi
-   fi   
+   fi
   done
   [ $COUNT -ge 20 ] && [ "$SVE" = "" ] \
    && echo "SCSI tree not found" \
@@ -145,7 +168,7 @@ $IDV:$IDP" #Ordered to match effect of reverse sort
     && IDP="`echo $NEWIDS | cut -f 2 -d :`"
   fi
   [ "$IDV" != "" -a "$IDP" != "" ] \
-   && /usr/sbin/pmodprobeoption $IDV $IDP   
+   && /usr/sbin/pmodprobeoption $IDV $IDP
  fi
  return $?
 #end wrapper substitute
@@ -174,7 +197,7 @@ fi
 USBSTORAGEDELAY="`grep 'options usb-storage ' /etc/modprobe.conf | grep -w --only-matching 'delay_use=[0-9]*' | cut -f 2 -d '='`"
 [ "$USBSTORAGEDELAY" = "" ] && USBSTORAGEDELAY="5" #default value
 sleep $USBSTORAGEDELAY; sleep 5
-  
+
 if [ "$ARGUMENT2" = "" ]; then #single arg
  if [ -e /usr/bin/tclsh -a "$USE_TCL_WRAPPER" = yes ];then
   tcl_usb_modeswitch_func &> /tmp/usb_modeswitch.temp.log
