woof-code/rootfs-skeleton/usr/sbin/pwsget: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pwsget b/woof-code/rootfs-skeleton/usr/sbin/pwsget
--- a/woof-code/rootfs-skeleton/usr/sbin/pwsget
+++ b/woof-code/rootfs-skeleton/usr/sbin/pwsget
@@ -1,9 +1,32 @@
 #! /bin/bash
-
+#
 # Pwget created by Lobster with thanks to Zigbert and Pwsget additions by gposil
 # for Puppy Dingo and Linux Tmxxine
 # Jan 2008 GPL v3 License
 # http://tmxxine.com
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 LOGIN=""
 
@@ -57,4 +80,4 @@ if [ $EXIT = OK ]; then
   rxvt -name Xwget -bg "#F3F2DF" -e wget -c --http-user=$LOGIN --http-password=$PWORD --ftp-user=$LOGIN --ftp-password=$PWORD -P "$DEST" $SOURCE
   rox -d "$DEST"
   fi
-fi 
+fi
