woof-code/rootfs-skeleton/usr/sbin/quicksetup: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/quicksetup b/woof-code/rootfs-skeleton/usr/sbin/quicksetup
--- a/woof-code/rootfs-skeleton/usr/sbin/quicksetup
+++ b/woof-code/rootfs-skeleton/usr/sbin/quicksetup
@@ -1,10 +1,10 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler Oct. 2011, http://bkhome.org
 #License: Oct. 2011, GPL3 (refer /usr/share/doc/legal)
-#A GUI when start desktop first time, to replace the text-mode dialogs (locale, keyboard-layout, timezone)
-#inspired by shinobar's countrywizard.qs (firstrun), but a complete rewrite.
-#replaces the old single-purpose scripts: chooselocale timezone-set (now symlinks)
-#propose first startup, run 'quickcountry, which is symlink.
+# A GUI when start desktop first time, to replace the text-mode dialogs (locale, keyboard-layout, timezone)
+# Inspired by shinobar's countrywizard.qs (firstrun), but a complete rewrite.
+# Replaces the old single-purpose scripts: chooselocale timezone-set (now symlinks)
+# Propose first startup, run 'quickcountry, which is symlink.
 #111019 first version.
 #1110120 call shinobar's 'keymap-set' script. FLAG_CHANGED improved.
 #111020 'countrywizard', 'xrandrshell' now symlinks to 'quicksetup'.
@@ -63,6 +63,29 @@
 export TEXTDOMAIN=quicksetup
 export OUTPUT_CHARSET=UTF-8
 . gettext.sh
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 . /etc/DISTRO_SPECS
 . /etc/rc.d/PUPSTATE
