woof-code/rootfs-skeleton/usr/sbin/remasterpup2: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/remasterpup2 b/woof-code/rootfs-skeleton/usr/sbin/remasterpup2
--- a/woof-code/rootfs-skeleton/usr/sbin/remasterpup2
+++ b/woof-code/rootfs-skeleton/usr/sbin/remasterpup2
@@ -1,5 +1,5 @@
 #!/bin/sh
-#simple script to remaster the puppy live-cd.
+# Simple script to remaster the puppy live-cd.
 #(c) Copyright 2006 Barry Kauler, www.puppyos.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #BK 9 oct 2007: updated for puppy v3.01.
@@ -31,6 +31,29 @@
 #100117 save user-modified rox globicons file.
 # 20jan10 Puppy v4.x(before woof) backward compatibility
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 # remasterpup2.mo
 m_01="Puppy simple CD remaster"
 m_02="ERROR"
@@ -45,7 +68,7 @@ mounted on directory /initrd\${PUP_LAYER}, that will be acceptable for this prog
 You will also need a current live-CD, as the program gets files off it.\n
 Anyone want to try it?
 \n\n
-Click 'Ok' button to quit..." 
+Click 'Ok' button to quit..."
 #m_04 skipped
 m_05="Welcome! This little program takes a snapshot of your current system and burns it to CD.
 \n\n
@@ -74,7 +97,7 @@ m_14="This remaster program needs to read some files off the current live-CD.\n
 You can also use a .iso file if it is already mounted as a virtual CD."
 m_14_1="Choose the CD/DVD drive..."
 m_14_2="NO CD/DVD drives found."
-m_15="Mounted CD, get rid of it before running this program!" 
+m_15="Mounted CD, get rid of it before running this program!"
 m_16="Please insert the current Puppy live-CD into drive \$BURNERDRV.\n
 Then click OK..."
 m_16_1="Do you like to make \$ZDRVSFS, the separate driver file?"
@@ -187,17 +210,17 @@ m_35="\$SFSPATH found.\nDo you reuse it without any change?"
 
 # I18N
 # set locale
-# myLOCALE=$LANG # is enough for puppy. but this code is more general. 
-for myLOCALE in C $(echo $LANGUAGE|cut -d':' -f1) $LC_ALL $LANG;do :;done	# ex. 	ja_JP.UTF-8
+# myLOCALE=$LANG # is enough for puppy. but this code is more general.
+for myLOCALE in C $(echo $LANGUAGE|cut -d':' -f1) $LC_ALL $LANG;do :;done       # ex.   ja_JP.UTF-8
 # search locale file
-myLOCALE1=$(echo $myLOCALE|cut -d'.' -f1)		# ex.	ja_JP
-myLOCALE2=$(echo $myLOCALE|cut -d'_' -f1)	# ex.	ja
+myLOCALE1=$(echo $myLOCALE|cut -d'.' -f1)               # ex.   ja_JP
+myLOCALE2=$(echo $myLOCALE|cut -d'_' -f1)       # ex.   ja
 LOCALEDIR=/usr/share/locale
 LOCALEFILE=$(basename $0).mo
 for D in C $myLOCALE2 $myLOCALE1 $myLOCALE
 do
-	F="$LOCALEDIR/$D/LC_MESSAGES/$LOCALEFILE"
-	[ -f "$F" ] && . "$F" 
+        F="$LOCALEDIR/$D/LC_MESSAGES/$LOCALEFILE"
+        [ -f "$F" ] && . "$F"
 done
 # end of I18N
 
@@ -209,13 +232,13 @@ SELECTIONS="`probedisk2 2>&1 | grep '^/dev/' | grep "|optical|" | cut -f 1,3 -d 
 #zSELECTIONS="`echo "$SELECTIONS" | tr '\n' ' '`" #v431 bugfix. # shinobar: need not for this code
 SELECTIONS="$SELECTIONS $VIRTUALCD"
 if [ "$(echo "$SELECTIONS"|tr -d ' ')" = "" ]; then
-	Xdialog --wrap --left --title "$m_01: $m_02" --msgbox "$m_14_2
+        Xdialog --wrap --left --title "$m_01: $m_02" --msgbox "$m_14_2
 $MSG" 0 0
-	exit
+        exit
 fi
 DIALOG="Xdialog --wrap --left --title \"$m_01\" --stdout --menubox \"$MSG\n\n$m_14_1\" 0 48 4 $SELECTIONS 2> /dev/null"
 BURNERDRV=""
-RESULT=$(eval $DIALOG) #w018	# 22jun09
+RESULT=$(eval $DIALOG) #w018    # 22jun09
 [ $? -ne 0 ] && exit
 BURNERDRV=$RESULT
 [ "$BURNERDRV" = "" ] && exit
@@ -224,7 +247,7 @@ BURNERDRV="`echo -n "$BURNERDRV" | cut -f 3 -d '/'`"
 
 #export LANG=C #faster, plus Xdialog happier. # never do so for I18N
 #LANG_ORG=LANG
-LANG=C				# 15jul09 can be faster
+LANG=C                          # 15jul09 can be faster
 KERNELVER="`uname -r`"
 
 #variables created at bootup by /initrd/usr/sbin/init...
@@ -269,14 +292,14 @@ SIZEBIN=`du -sk /bin | cut -f 1`
 SIZESBIN=`du -sk /sbin | cut -f 1`
 SIZELIB=`du -sk /lib | cut -f 1`
 SIZEUSR=`du -sk /usr | cut -f 1`
-SIZEOPT=0	# 01jul09
+SIZEOPT=0       # 01jul09
 [ -d /opt ] && SIZEOPT=`du -sk /opt | cut -f 1`
 sync
 #kill $XPID
 #SIZETOTALK=`expr $SIZEBIN + $SIZESBIN + $SIZELIB + $SIZEUSR + $SIZEOPT`
 #SIZETOTALM=`expr $SIZETOTALK \/ 1024`
 SIZETOTALK=`dc $SIZEBIN $SIZESBIN + $SIZELIB + $SIZEUSR + $SIZEOPT + p`
-SIZETOTALM=`dc $SIZETOTALK 1024 \/ p| cut -d'.' -f1`	# 01jul09
+SIZETOTALM=`dc $SIZETOTALK 1024 \/ p| cut -d'.' -f1`    # 01jul09
 [ "$SIZETOTALM" ] || SIZETOTALM=1
 #echo "SIZETOTALM=$SIZETOTALM"
 #estimate a compressed size...
@@ -375,8 +398,8 @@ fi
 NEW="yes"
 SFSPATH=$(ls -1 $WKGMNTPT/puppylivecdbuild/$SFSBASE*.sfs 2>/dev/null)
 if [ "$SFSPATH" != "" -a $(echo "$SFSPATH" | wc -l) -eq 1 ]; then
-	eval m_35=\"$m_35\"
-	Xdialog --wrap --left --title "$m_01" --yesno "$m_35" 0 0 && NEW="no"
+        eval m_35=\"$m_35\"
+        Xdialog --wrap --left --title "$m_01" --yesno "$m_35" 0 0 && NEW="no"
 fi
 SFSPATH=""
 
@@ -407,7 +430,7 @@ if [ "$CDMNTPT" = "" ];then
  eval m_16=\"$m_16\"
  while [ 1 ];do
  Xdialog --wrap --left  --title "$m_01" --msgbox "$m_16" 0 0
- [ $? -eq 0  ] || exit	# 22jun09
+ [ $? -eq 0  ] || exit  # 22jun09
  #now mount it...
  CDMNTPT="/mnt/$BURNERDRV"
  mkdir -p /mnt/$BURNERDRV
@@ -446,8 +469,8 @@ mkdir $WKGMNTPT/puppylivecdbuild
    sync
    for F in vmlinuz initrd.gz ${ZDRVSFS} grldr menu.lst '*.xpm' isolinux.bin isolinux.cfg '*.msg' '*.16' '*.HTM*' '*.ICO' '*.INF'
    do
-	cp $CDMNTPT/$F $WKGMNTPT/puppylivecdbuild/ 2> /dev/null
-	sync
+        cp $CDMNTPT/$F $WKGMNTPT/puppylivecdbuild/ 2> /dev/null
+        sync
    done
 umount /dev/$BURNERDRV 2> /dev/null
 
@@ -458,8 +481,8 @@ XPID=$!
 
 #create new ${DISTRO_FILE_PREFIX}-xxx.sfs file...
 squash() {
-	echo $0 $@
-	rxvt -bg orange -fg black -title "$m_01" -geometry 80x6 -e mksquashfs $@
+        echo $0 $@
+        rxvt -bg orange -fg black -title "$m_01" -geometry 80x6 -e mksquashfs $@
 }
 DIRHOME=""
 [ -d /home ] && DIRHOME="/home"
@@ -472,9 +495,9 @@ sync
 #note, /home could be in underdog linux...
 
 # modules copied from initrd
-ANOTHER_REMOVE="/lib/modules/$KERNELVER/initrd /lib/modules/*/modules.*"	# 28dec09 modules.*
+ANOTHER_REMOVE="/lib/modules/$KERNELVER/initrd /lib/modules/*/modules.*"        # 28dec09 modules.*
 if [ "$MKZDRV" = "yes" ]; then
-  rm -f $WKGMNTPT/puppylivecdbuild/$ZDRVSFS 
+  rm -f $WKGMNTPT/puppylivecdbuild/$ZDRVSFS
   mksquashfs /lib $WKGMNTPT/puppylivecdbuild/$ZDRVSFS -keep-as-directory -e /lib/[^m]* $ANOTHER_REMOVE
   ANOTHER_REMOVE="/lib/modules"
 fi
@@ -569,7 +592,7 @@ sort -u /tmp/root/.packages/woof-installed-packages > /tmp/woof-installed-packag
 mv -f /tmp/woof-installed-packages-tmp /tmp/root/.packages/woof-installed-packages
 echo -n "" > /tmp/root/.packages/user-installed-packages #v431
 
-eval m_19=\"$m_19\" 
+eval m_19=\"$m_19\"
 Xdialog --wrap --left --title "$m_01" --msgbox "$m_19" 0 0
 sync
 mksquashfs /tmp/root $WKGMNTPT/puppylivecdbuild/$SFSBASE.sfs -keep-as-directory
@@ -608,7 +631,7 @@ cp -af /etc/eventmanager /tmp/etc/ #v411
 
 #what about settings for a particular pc?...
 MSG1="$m_20"
-eval m_21=\"$m_21\" 
+eval m_21=\"$m_21\"
 Xdialog --wrap --left --title "$m_01" --default-no --yesno "$m_21" 0 0
 if [ $? -eq 0 ];then
  cp -af /etc/codepage /tmp/etc/
