woof-code/rootfs-skeleton/usr/sbin/remove_builtin: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/remove_builtin b/woof-code/rootfs-skeleton/usr/sbin/remove_builtin
--- a/woof-code/rootfs-skeleton/usr/sbin/remove_builtin
+++ b/woof-code/rootfs-skeleton/usr/sbin/remove_builtin
@@ -1,6 +1,6 @@
 #!/bin/sh
 #Barry Kauler Dec. 2010, license GPL v3 /usr/share/doc/legal.
-#based on a script by technosaurus, Dec. 2010.
+# Based on a script by technosaurus, Dec. 2010.
 #101222 fix menu.
 #101227 technosaurus: fixed reverse dependency check.
 #110505 support sudo for non-root user.
@@ -17,6 +17,28 @@ eval_gettext () {
   eval echo \"$myMESSAGE\"
 }
 export LANGORG=$LANG
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 #export LANG=C #keep Xdialog happy. #off for gettext
 
