woof-code/rootfs-skeleton/usr/sbin/run-as-spot: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/run-as-spot b/woof-code/rootfs-skeleton/usr/sbin/run-as-spot
--- a/woof-code/rootfs-skeleton/usr/sbin/run-as-spot
+++ b/woof-code/rootfs-skeleton/usr/sbin/run-as-spot
@@ -4,6 +4,29 @@
 # License: GPL version 3 or later
 #130604 BK: slight mods. see also /usr/sbin/setup-spot (support/setup-spot in woof).
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 [ ! $1 ] && exit
 CWD=$(pwd)
 APP="$1"; shift
@@ -14,7 +37,7 @@ if [ $(id -u) -eq 0 ]; then
  touch /root/spot/.Xauthority
  #following line is mostly there to catch any root:root files that may have got copied in...
  chown -R spot:spot /root/spot &
- export XAUTHORITY=/root/spot/.Xauthority  
+ export XAUTHORITY=/root/spot/.Xauthority
  export XDG_CONFIG_HOME=/root/spot/.config
  export XDG_CACHE_HOME=/root/spot/.cache
  export XDG_DATA_HOME=/root/spot/.local/share
