/usr/sbin/savesession-dvd : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd b/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd
--- a/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd
+++ b/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd
@@ -9,34 +9,36 @@
 #w482 use xorriso instead of cdrtools/cdrkit if installed.
 
 
-###KRG Fr 31. Aug 23:34:58 GMT+1 2012
 
-trap "exit 1" HUP INT QUIT KILL TERM
+#************
+#KRG
+
 
 OUT=/dev/null;ERR=$OUT
 [ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
-[ "$DEBUG" = "2" ] && set -x
+[ "$DEBUG" = 2 ] && set -x
 
-Version='1.1'
+
+Version=1.1-KRG-MacPup_O2
 
 usage(){
-USAGE_MSG="
-$0 [ PARAMETERS ]
-
--V|--version : showing version information
--H|--help : show this usage information
-
-*******  *******  *******  *******  *******  *******  *******  *******  *******
-$2
+MSG="
+$0 [ help | version ]
 "
-echo "$USAGE_MSG"
+echo "$MSG
+$2"
 exit $1
 }
+[ "`echo "$1" | grep -Ei "help|\-h"`" ] && usage 0
+[ "`echo "$1" | grep -Ei "version|\-V"`" ] && { echo "$0: $Version";exit 0; }
 
-[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
-[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
 
-###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+trap "exit" HUP INT QUIT ABRT KILL TERM
+
+
+#KRG
+#************
+
 
 #/etc/rc.d/rc.shutdown saves session at shutdown, savesession-dvd is called
 #from desktop icon to do an immediate save to multisession-cd.
@@ -76,17 +78,17 @@ CDR="/dev/$SAVEPART"
 
 if [ ! "$CONSRUN" = "" ];then
  multisavefunc
- exit $?
+ exit
 fi
 
 
 if [ "$PUPMODE" != "77" ];then
  xmessage -bg "indian red" -center -title "SaveSession-DVD" "Sorry, this is not a multisession live-CD/DVD"
- exit 1
+ exit
 fi
 if [ "$CDR" = "" ];then
  xmessage -bg "indian red" -center -title "SaveSession-DVD" "Sorry, this is not a multisession live-CD/DVD"
- exit 1
+ exit
 fi
 
 
@@ -98,7 +100,7 @@ if [ "`mount | grep "$CDR"`" != "" ];then
  sync
  umount $CDR
  if [ ! $? -eq 0 ];then
-  xmessage -bg "indian red" -center -title "SaveSession: ERROR" "Sorry, '$CDR' is currently mounted and cannot be automatically
+  xmessage -bg "indian red" -center -title "SaveSession: ERROR" "Sorry, $CDR is currently mounted and cannot be automatically
 unmounted. You will need to unmount it manually.
 
 Click OK button to quit..."
