woof-code/rootfs-skeleton/usr/sbin/set-xftdpi: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/set-xftdpi b/woof-code/rootfs-skeleton/usr/sbin/set-xftdpi
--- a/woof-code/rootfs-skeleton/usr/sbin/set-xftdpi
+++ b/woof-code/rootfs-skeleton/usr/sbin/set-xftdpi
@@ -1,6 +1,29 @@
 #!/bin/sh
 #BK Aug 2009, gpl
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 #export LANG=C #xdialog happy with this.
 #export LC_ALL=C
 for l in `locale |sed 's|=\(.*\)|=C|'` ; do echo $l;eval $l;export $l;done
@@ -20,10 +43,10 @@ do
  CNT=`expr $CNT + 1`
 done
 
-##--radiolist	<text> <height> <width> <list height> <tag1> <item1> <status1> {<help1>}...
+##--radiolist   <text> <height> <width> <list height> <tag1> <item1> <status1> {<help1>}...
 #XDIALOG="Xdialog --left --stdout --title \"Set global font size\" --no-tags --radiolist \"Please choose dpi (dots per inch) for the screen.\nThe larger the value, the bigger that antialiased\nfonts will render on the screen. Adjust up or down if\nfonts are rendering too small or too big on screen.\n\nNote1: Some apps do not use antialiased rendering\n            and will not be affected by this setting.\n\nNote2: Change will only take effect after restarting X\" 0 0 0 ${RADIOBUTTONS}"
 
-##--spinbox	<text> <height> <width> <min value> <max value> <default value> <label>
+##--spinbox     <text> <height> <width> <min value> <max value> <default value> <label>
 XDIALOG="Xdialog --left \
  --stdout \
  --title \"Set global font size\" \
