woof-code/rootfs-skeleton/usr/sbin/sfsget: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/sfsget b/woof-code/rootfs-skeleton/usr/sbin/sfsget
--- a/woof-code/rootfs-skeleton/usr/sbin/sfsget
+++ b/woof-code/rootfs-skeleton/usr/sbin/sfsget
@@ -1,8 +1,8 @@
 #!/bin/sh
 #(c) copyright Barry Kauler 2011, bkhome.org
-#Licence 2011 GPL V3 (/usr/share/doc/legal)
-#$1 is optional name of an sfs file passed on commandline, download it. ex: devx.sfs
-#$1 optional prefix, sub-directory on the official download URL. ex: wary-5.2/devx.sfs
+# Licence 2011 GPL V3 (/usr/share/doc/legal)
+# $1 is optional name of a sfs file passed on commandline, download it. ex: devx.sfs
+# $1 optional prefix, sub-directory on the official download URL. ex: wary-5.2/devx.sfs
 #110402 first version.
 #110422 DISTRO_VERSION variable now has dotted format. note, also now using full dotted version# in puppy filenames.
 #110813 bug fix, sfs file has '_' in name.
@@ -18,6 +18,29 @@
 
 export TEXTDOMAIN=sfsget
 export OUTPUT_CHARSET=UTF-8
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 SFS_FILE=''; SFS_DIR=''
 if [ $1 ];then
@@ -234,7 +257,7 @@ while [ $DLRET -ne 0 ];do
  <frame>
   ${REPOBUTTONS}
  </frame>
- 
+
  <hbox>
   <button>
    <label>$(gettext 'Test URLs')</label>
@@ -248,7 +271,7 @@ while [ $DLRET -ne 0 ];do
  </hbox>
 </vbox>
 </window>
-" 
+"
  RETPARAMS="`gtkdialog3 --program=DEPS_DIALOG`"
 
  [ "`echo "$RETPARAMS" | grep 'BUTTON_SFS_DOWNLOAD'`" = "" ] && exit 1
