woof-code/rootfs-skeleton/usr/sbin/timezone-set: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/timezone-set b/woof-code/rootfs-skeleton/usr/sbin/timezone-set
--- a/woof-code/rootfs-skeleton/usr/sbin/timezone-set
+++ b/woof-code/rootfs-skeleton/usr/sbin/timezone-set
@@ -1,11 +1,34 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler 2007 www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
-#utility to select the timezone.
-#Note, as Puppy will mostly be on PCs coexisting with Windows,
-#hardware clock (CMOS) is set to local time (see /etc/rc.d/rc.local0)
+# Utility to select the timezone.
+# Note, as Puppy will mostly be on PCs coexisting with Windows,
+# hardware clock (CMOS) is set to local time (see /etc/rc.d/rc.local0)
 #BK oct2007: updated for 3.02
 #w019 april 2009: cli mode so can run from /etc/rc.d/rc.update
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 export LANG=C
 
