woof-code/rootfs-skeleton/usr/sbin/usb_modeswitch_status: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/usb_modeswitch_status b/woof-code/rootfs-skeleton/usr/sbin/usb_modeswitch_status
--- a/woof-code/rootfs-skeleton/usr/sbin/usb_modeswitch_status
+++ b/woof-code/rootfs-skeleton/usr/sbin/usb_modeswitch_status
@@ -1,6 +1,6 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler Nov. 2010. License: GPL v3 /usr/share/doc/legal.
-#called from /lib/udev/usb_modeswitch, which in turn is called by udev rule when a 3G modem inserted.
+# Called from /lib/udev/usb_modeswitch, which in turn is called by udev rule when a 3G modem inserted.
 #101208 rewrite, simpler.
 #101209 switch has occurred, but sometimes (my ZTE K3571-Z modem) usbserial.ko fails to attach to usb interface.
 #110914 think possible this script gets called almost simultaneously more than once.
@@ -13,6 +13,29 @@
 export TEXTDOMAIN=usb_modeswitch_status
 export OUTPUT_CHARSET=UTF-8
 export LANG="`cat /etc/profile|grep '^LANG='| cut -d '=' -f2`"
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 #all of the uevent env. variables are visible here. ex (my Optus 3G modem):
 #130326 note: DEVICE variable no longer in 3.5+ kernel, as /proc/bus/usb removed...
@@ -85,7 +108,7 @@ if [ $BRKCNT -lt 30 ];then
     fi
    fi
   fi
-  
+
   #110914 this works on my new laptop...
   #if ls /dev/ttyUSB* 2>/dev/null;then
    if [ ! -h /dev/gsmmodem  ];then #supposed to be auto-created, but what if it fails.
@@ -98,7 +121,7 @@ if [ $BRKCNT -lt 30 ];then
    fi
    #...er, but problem, not removed when modem unplugged.
   #fi
- 
+
  fi
  kill $yPID
  DISPLAY=":0" yaf-splash -placement center -close never -timeout 12 -bg green -fontsize large -text "$(gettext '3G USB modem now ready for use')" &
