woof-code/rootfs-skeleton/usr/sbin/user2root: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/user2root b/woof-code/rootfs-skeleton/usr/sbin/user2root
--- a/woof-code/rootfs-skeleton/usr/sbin/user2root
+++ b/woof-code/rootfs-skeleton/usr/sbin/user2root
@@ -1,8 +1,8 @@
 #!/bin/sh
 #(c) copyright Barry Kauler, May 2013, bkhome.org
 #License GPL3 (refer /usr/share/doc/legal).
-#called from /usr/sbin/loginmanager, to change back to 'root'.
-#may also be called standalone.
+# Called from /usr/sbin/loginmanager, to change back to 'root'.
+# May also be called standalone.
 #130527 first version.
 
 NOWUSER="`whoami`"
@@ -10,6 +10,29 @@ NOWUSER="`whoami`"
 
 export TEXTDOMAIN=user2root
 export OUTPUT_CHARSET=UTF-8
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 #change auto login back to root...
 rootEXPR="s%^tty1.*%tty1::respawn:/sbin/mingetty --autologin root tty1%"
