/usr/sbin/video-wizard: Add VERB and other variables. Use ash as interpreter. Shorten test ( omitt != "" ).

diff --git a/woof-code/rootfs-skeleton/usr/sbin/video-wizard b/woof-code/rootfs-skeleton/usr/sbin/video-wizard
--- a/woof-code/rootfs-skeleton/usr/sbin/video-wizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/video-wizard
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/ash
 #BK video-wizard (c) Copyright 2007 Barry Kauler
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #written for Puppy v3.00
@@ -27,24 +27,24 @@ MODEBASENUM="`echo "$ALLMODES" | tr ' ' '\n' | grep '640x480x16' | cut -f 1 -d '
 if [ -e /tmp/videomode ];then
  CURRENTMODE="`cat /tmp/videomode`"
  #in case new mode no good, ctrl-alt-backspace will come up in safe mode...
- [ "$MODEBASENUM" ] && echo -n "$MODEBASENUM 640x480x16" > /tmp/videomode #v3.02
+ [ "$MODEBASENUM" ] && echo "$MODEBASENUM 640x480x16" >/tmp/videomode #v3.02
 else
  CURRENTMODE="`cat /etc/videomode`"
 fi
-echo "$CURRENTMODE" > /tmp/xvesacurrentmode #v3.02
-CURRENTNUMBER="`echo -n "$CURRENTMODE" | cut -f 1 -d ' '`"
-CURRENTVALS="`echo -n "$CURRENTMODE" | cut -f 2 -d ' '`"
+echo "$CURRENTMODE" >/tmp/xvesacurrentmode #v3.02
+CURRENTNUMBER="`echo "$CURRENTMODE" | cut -f 1 -d ' '`"
+CURRENTVALS="`echo "$CURRENTMODE" | cut -f 2 -d ' '`"
 
 [ -f /etc/xextraoptions ] && CURRENTXOPTIONS="`cat /etc/xextraoptions`"
 
 RADIOSECTION=""
 for ONEMODE in $ALLMODES
 do
- MODENUMBER="`echo -n "$ONEMODE" | cut -f 1 -d '|'`"
- MODEVALS="`echo -n "$ONEMODE" | cut -f 2 -d '|'`"
- XVAL=`echo -n "$MODEVALS" | cut -f 1 -d 'x'`
- YVAL=`echo -n "$MODEVALS" | cut -f 2 -d 'x'`
- COLDEPTH=`echo -n "$MODEVALS" | cut -f 3 -d 'x'`
+ MODENUMBER="`echo "$ONEMODE" | cut -f 1 -d '|'`"
+ MODEVALS="`echo "$ONEMODE" | cut -f 2 -d '|'`"
+ XVAL=`echo "$MODEVALS" | cut -f 1 -d 'x'`
+ YVAL=`echo "$MODEVALS" | cut -f 2 -d 'x'`
+ COLDEPTH=`echo "$MODEVALS" | cut -f 3 -d 'x'`
  [ $XVAL -lt 640 ] && continue
  [ $YVAL -lt 480 ] && continue
  [ $COLDEPTH -lt 16 ] && continue
@@ -122,8 +122,8 @@ RETVALS="`gtkdialog3 --program=MAIN_DIALOG`"
 
 echo "$RETVALS"
 
-[ "`echo "$RETVALS" | grep '^EXIT='`" = "" ] && exit #invalid stuff.
-[ "`echo "$RETVALS" | grep 'abort'`" != "" ] && exit #invalid stuff.
+[ "`echo "$RETVALS" | grep '^EXIT='`" ] || exit #invalid stuff.
+[ "`echo "$RETVALS" | grep 'abort'`" ] && exit #invalid stuff.
 
 CHOSENMODE="`echo "$RETVALS" | grep 'RADIO' | grep '"true"' | cut -f 2 -d '_' | cut -f 1 -d '=' | tr '|' ' '`"
 CHOSENBUTTON="`echo "$RETVALS" | grep '^EXIT' | cut -f 2 -d '"'`" #'geany
@@ -131,8 +131,8 @@ CHOSENXOPTIONS="`echo "$RETVALS" | grep '^ENTRY' | cut -f 2 -d '"'`" #'geany
 
 echo "CHOSENMODE=$CHOSENMODE CHOSENBUTON=$CHOSENBUTTON"
 
-echo -n "$CHOSENMODE"  > /tmp/videomode
-echo -n "$CHOSENXOPTIONS" > /etc/xextraoptions
+echo "$CHOSENMODE"  >/tmp/videomode
+echo "$CHOSENXOPTIONS" >/etc/xextraoptions
 
 if [ "$CHOSENBUTTON" = "TESTBUTTON" ];then
  touch /tmp/pup_event_icon_change_flag #v404 see /sbin/clean_desk_icons (called from .xinitrc).
@@ -141,7 +141,7 @@ if [ "$CHOSENBUTTON" = "TESTBUTTON" ];then
 fi
 
 if [ "$CHOSENBUTTON" = "OKAYBUTTON" ];then
- echo -n "$CHOSENMODE" > /etc/videomode
+ echo "$CHOSENMODE" >/etc/videomode
  rm -f /tmp/videomode
  rm -f /tmp/Xflag #prevent endless restarts. see xwin*.
 fi
@@ -150,7 +150,7 @@ if [ $PUPMODE -eq 5 ];then
  if [ ! "`grep 'alias snd\-card\-0' /etc/modprobe.conf`" = "" ];then
   wavplay /usr/share/audio/2barks.wav &
   sleep 3
-  killall wavplay 2> /dev/null
+  killall wavplay 2>$ERR
  fi
 fi
 
