woof-code/rootfs-skeleton/usr/sbin/wmswitcher : Added.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/wmswitcher b/woof-code/rootfs-skeleton/usr/sbin/wmswitcher
--- a/woof-code/rootfs-skeleton/usr/sbin/wmswitcher
+++ b/woof-code/rootfs-skeleton/usr/sbin/wmswitcher
@@ -6,40 +6,64 @@
 #ver 0.3 #2010-07-12
 #ver 0.4 #2010-07-25
 #ver 0.5 #2010-08-01
+#ver 0.6-KRG #2017-03-24
 
-ver="0.5"
+ver="0.6-KRG"
 #find images for gui
 IMGDIR="/usr/share/pixmaps"
 #test that we actually are running jwm or icewm
-CURWM=`head -c5 /etc/windowmanager`
+CURWM=`head -c5 /etc/windowmanager` #this is a workaround if icewm was started with "icewm-session"
+DISP=${DISPLAY%.*}
+test -f /etc/windowmanager.$DISP && CURWM=`head -c5 /etc/windowmanager.$DISP`
+
 echo "CURWM='$CURWM'"
-if [ "$CURWM" != jwm -a "$CURWM" != icewm ];then /usr/X11R7/bin/yaf-splash -bg hotpink -margin 3 -font "-misc-dejavu sans-bold-r-normal--20-0-0-0-p-0-iso10646-1" -timeout 3 -outline 0 -text "ERROR: You aren't using Jwm or Icwm, programm exiting. Bye"
-    exit
+if [ "$CURWM" != jwm -a "$CURWM" != icewm ];then
+/usr/X11R7/bin/yaf-splash -bg hotpink -margin 3 \
+ -font "-misc-dejavu sans-bold-r-normal--20-0-0-0-p-0-iso10646-1" \
+ -timeout 3 -outline 0 \
+ -text "ERROR: You aren't using Jwm or Icwm, programm exiting. Bye"
+    exit 3
 fi
 #make sure icewm exists
 ICETHERE=`which icewm`
-if [ "$ICETHERE" = "" ];then /usr/X11R7/bin/yaf-splash -bg hotpink -margin 3 -font "-misc-dejavu sans-bold-r-normal--20-0-0-0-p-0-iso10646-1" -timeout 3 -outline 0 -text "ERROR: Icewm is not installed"
-    exit 2
+if [ "$ICETHERE" = "" ];then
+/usr/X11R7/bin/yaf-splash -bg hotpink -margin 3 \
+ -font "-misc-dejavu sans-bold-r-normal--20-0-0-0-p-0-iso10646-1" \
+ -timeout 3 -outline 0 \
+ -text "ERROR: Icewm is not installed"
+    exit 4
 fi
-#cp $VERB -f /usr/bin/restartwm /usr/bin/.restartwm.bak #see /root/Startup/zfixwm (cleanup)#No, moved to pinstall
+#cp $VERB -f /usr/bin/restartwm /usr/bin/.restartwm.bak #see /root/Startup/zfixwm (cleanup)
+#No, moved to pinstall
 
 #using rpl, a new program introduced by BarryK in woof
-#icewm changer #careful! critical system files being tampered with
-ICEWM(){
-    FUTUREWM=`grep -we '^NEXTWM=' /usr/bin/restartwm` 2>/dev/null
-    echo "rpl -v '$FUTUREWM' 'NEXTWM=\"icewm\"' /usr/bin/restartwm" >/tmp/wmswithcer
-    . /tmp/wmswithcer
-    rm -f /tmp/wmswithcer
+#icewm changer
+#careful! critical system files being tampered with
+_ICEWM(){
+    FUTUREWM=`grep -we '^NEXTWM=' /usr/bin/restartwm` #2>/dev/null
+    echo "rpl -v '$FUTUREWM' 'NEXTWM=\"icewm\"' /usr/bin/restartwm" >/tmp/wmswitcher
+    . /tmp/wmswitcher
+    rm -f /tmp/wmswitcher
 
 }
+ICEWN(){
+echo 'icewm' >/etc/windowmanager.next
+echo 'icewm' >/etc/windowmanager.next.$DISP
+}
 export -f ICEWM
-#jwm changer #ditto icewm comment
-JWM(){
-    FUTUREWM=`grep -we '^NEXTWM=' /usr/bin/restartwm` 2>/dev/null
-    echo "rpl -v '$FUTUREWM' 'NEXTWM=\"jwm\"' /usr/bin/restartwm" >/tmp/wmswithcer
-    . /tmp/wmswithcer
-    rm -f /tmp/wmswithcer
 
+#jwm changer
+#ditto icewm comment
+_JWM(){
+    FUTUREWM=`grep -we '^NEXTWM=' /usr/bin/restartwm` #2>/dev/null
+    echo "rpl -v '$FUTUREWM' 'NEXTWM=\"jwm\"' /usr/bin/restartwm" >/tmp/wmswitcher
+    . /tmp/wmswitcher
+    rm -f /tmp/wmswitcher
+
+}
+JWM(){
+echo 'jwm' >/etc/windowmanager.next
+echo 'jwm' >/etc/windowmanager.next.$DISP
 }
 export -f JWM
 #switch function
