woof-code/rootfs-skeleton/usr/sbin/xdelta_gui: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xdelta_gui b/woof-code/rootfs-skeleton/usr/sbin/xdelta_gui
--- a/woof-code/rootfs-skeleton/usr/sbin/xdelta_gui
+++ b/woof-code/rootfs-skeleton/usr/sbin/xdelta_gui
@@ -1,15 +1,38 @@
 #!/bin/sh
 #(c) Copyright Barry Kauler 2009, puppylinux.com
 #2009 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
-#a frontend for the 'xdelta' utility.
-#$1 is normally invoked by clicking on a .delta file in rox, $1 has full path.
-#also supports drag and drop.
-#can be invoked from commandline like this:
+# A frontend for the 'xdelta' utility.
+# $1 is normally invoked by clicking on a .delta file in rox, $1 has full path.
+# Also supports drag and drop.
+# Can be invoked from commandline like this:
 #  # xdelta_gui oldfile:newfile.delta <<script searches for oldfile.
 #  # xdelta_gui oldfile newfile       <<script will generate .delta file
 #  # xdelta_gui oldfile genfile.delta <<recreate oldfile
 #...first ex, .delta has old/new files encoded into its own filename.
 #100131 altenate delta file format "oldfile___newfile.delta" (three underscores).
+
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
 
 if [ "`which xdelta3`" = "" ];then
  xmessage -center -bg red "The 'xdelta' package must be installed first"
@@ -18,18 +41,18 @@ fi
 
 old_find_func () {
  #needs OLDFILENAME, sets SOURCEFILE_OLD.
-	 xmessage -bg orange -center -buttons "" "Please wait, searching for old file..." &
-	 XPID=$!
-	 SOURCEFILE_OLD="`find /root -maxdepth 4 -type f -name ${OLDFILENAME} | head -n 1`"
-	 if [ "$SOURCEFILE_OLD" = "" ];then
+         xmessage -bg orange -center -buttons "" "Please wait, searching for old file..." &
+         XPID=$!
+         SOURCEFILE_OLD="`find /root -maxdepth 4 -type f -name ${OLDFILENAME} | head -n 1`"
+         if [ "$SOURCEFILE_OLD" = "" ];then
       #SOURCEFILE_OLD="`find /mnt/home -maxdepth 4 -type f -name ${OLDFILENAME} | head -n 1`"
-	  for ONEMNTD in `mount | grep '^/dev/sd[a-z]' | cut -f 3 -d ' ' | tr '\n' ' '`
-	  do
-	   SOURCEFILE_OLD="`find ${ONEMNTD} -maxdepth 4 -type f -name ${OLDFILENAME} | head -n 1`"
-	   [ "$SOURCEFILE_OLD" != "" ] && break
-	  done
-	 fi
-	 kill $XPID
+          for ONEMNTD in `mount | grep '^/dev/sd[a-z]' | cut -f 3 -d ' ' | tr '\n' ' '`
+          do
+           SOURCEFILE_OLD="`find ${ONEMNTD} -maxdepth 4 -type f -name ${OLDFILENAME} | head -n 1`"
+           [ "$SOURCEFILE_OLD" != "" ] && break
+          done
+         fi
+         kill $XPID
      if [ "$SOURCEFILE_OLD" = "" ];then
       xmessage -bg yellow -center "Sorry could not find ${OLDFILENAME}. You will have to manually drag it into the 'Old file' box"
      fi
@@ -125,20 +148,20 @@ if [ "$SECONDBOX" = "" ];then
  </hbox>"
 fi
 
- 
+
 export XDELTA_DLG="
 <window title=\"Xdelta difference manager\" icon-name=\"gtk-file\">
 <vbox>
   <text><label>Welcome, this is a GUI for the 'xdelta' utility, to manage changes between two files</label></text>
    <text use-markup=\"true\"><label>\"<b>To generate a '.delta' file, drag old and new files here, or to recreate the new file drag old and '.delta' files here ↓    </b>\"</label></text>
-          
+
   <hbox>
    <text><label>Old file:</label></text>
    <entry accept=\"directory\">${DEFAULT_OLD}<variable>SOURCEFILE_OLD</variable></entry>
   </hbox>
   ${SECONDBOX}
-  
-  <hbox> 
+
+  <hbox>
   <button help>
    <action>Xdialog --wrap --screencenter --left --title \"Xdelta - HELP\" --msgbox \"Xdelta is an application program designed to compute changes between two files. These changes (deltas) are similar to the output of the 'diff' program in that they may be used to store and transmit only the changes between files.  However, unlike diff, the output of Xdelta is not expressed in a human-readable format -- Xdelta can also also apply these deltas to a copy of the original file.  Xdelta uses a fast, linear algorithm and performs well on both binary and text files.\n\nTo create a '.delta' file, you need two original files, an 'old' and a 'new' file. The generated delta file will have an extension of '.delta'.\n\nYou can recreate the original 'new' file, as long as you have the original 'old' file and the '.delta' file. This GUI frontend makes this easy -- just drag the .delta file into the box, and the progam will search for and locate the original old file. Or, just click on a .delta file in a ROX-Filer window to regenerate the original new file.\n\nThe author of Xdelta is Joshua MacDonald. The Rsync algorithm, which inspired the core delta algorithm, is due to Andrew Tridgell and Paul Mackerras. The GUI is written by Barry Kauler. Licence is GPL v2.\" 600x0</action>
   </button>
@@ -152,7 +175,7 @@ RETVALS="`gtkdialog3 --program=XDELTA_DLG --center`"
 eval "$RETVALS"
 EXITERR=""
 [ "$EXIT" != "generate" ] && exit
- 
+
 if [ "$SOURCEFILE_2ND" != "" ];then
  if [ "`echo -n "$SOURCEFILE_2ND" | grep '\.delta$'`" = "" ];then
   SOURCEFILE_DELTA=""
@@ -162,7 +185,7 @@ if [ "$SOURCEFILE_2ND" != "" ];then
   SOURCEFILE_DELTA="$SOURCEFILE_2ND"
  fi
 fi
- 
+
 if [ "$SOURCEFILE_NEW" != "" ];then
  [ ! -f "$SOURCEFILE_NEW" ] && EXITERR="yes"
  if [ "$EXITERR" != "" ];then
