xorgwizard : Cleanups.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -92,17 +92,18 @@
 #
 ########################################################################
 
-TMP_DIR='/tmp/xorgwizard';mkdir -p "$TMP_DIR"
-#[ "`tty`" != "/dev/tty1" ] && sleep 2s && chvt 1
+TMP_DIR=/tmp/xorgwizard;mkdir -p "$TMP_DIR"
+
 
 # redirect errors to file (to help debug):
-exec 2>"$TMP_DIR"/xorgwizard-errors.log
+exec 2>>"$TMP_DIR"/xorgwizard-errors.log
 
 PSFND=`ps`
 CURRENTX=`readlink /usr/bin/X`
-if [ "$CURRENTX" = "" ];then #w007 fix if not a symlink.
+if [ ! "$CURRENTX" ];then #w007 fix if not a symlink.
+ which Xorg || { echo 'Warning: No Xorg server installed !'
  ln -snf Xorg /usr/bin/X
- CURRENTX='Xorg'
+ CURRENTX=Xorg
 fi
 
 . /etc/rc.d/functions4puppy4 #v411 has choosemousefunc().
@@ -110,7 +111,7 @@ fi
 #v2.0.0
 #read the console keymap (country layout), apply to xkb...
 CONSKEYMAP=`cat /etc/keymap | cut -b 1-2`
-[ "$CONSKEYMAP" = "" ] && CONSKEYMAP="us"
+[ "$CONSKEYMAP" ] || CONSKEYMAP="us"
 case $CONSKEYMAP in
  az) #azerty
   XKEYMAP="fr"
@@ -230,20 +231,21 @@ to modify the existing file.\"</label></text>
 
 
 #do this code block if X is running...
-if [ "`echo -n "$PSFND" | grep '\.xinitrc'`" != "" ];then
+if [ "`echo -n "$PSFND" | grep '\.xinitrc'`" ];then
 
  RETSTR=`echo "$MAIN1" | gtkdialog2 --stdin`
- RETVAL="`echo "$RETSTR" | grep 'EXIT:' | cut -f 2 -d ':'`"
+ RETVAL=`echo "$RETSTR" | grep 'EXIT:' | cut -f 2 -d ':'`
 
  case $RETVAL in
   11) #XorgWizard.
    #rm /etc/mousedevice # Dougal: any reason for this?
    mv -f /etc/X11/xorg.conf /etc/X11/xorg.conf.prev 2>/dev/null
    [ -e /usr/bin/Xvesa ] && ln -sf Xvesa /usr/bin/X
-   NEXTWM=`cat /etc/windowmanager`
-   echo -n "$NEXTWM" > /etc/windowmanager #this makes change permanent.
-   echo -n "$NEXTWM" > /tmp/wmexitmode.txt
-   echo -n "$NEXTWM" > /tmp/xwin/wmexitmode.txt
+   #NEXTWM=`cat /etc/windowmanager`
+   read NEXTWM </etc/windowmanager
+   echo "$NEXTWM" > /etc/windowmanager #this makes change permanent.
+   echo "$NEXTWM" > /tmp/wmexitmode.txt
+   echo "$NEXTWM" > /tmp/xwin/wmexitmode.txt
    echo 'ICONWIPE' > /tmp/pup_event_icon_change_flag  ##+++2011_10_30
    sync
    exec killall X
@@ -268,7 +270,7 @@ that changing the settings will cause no change on the screen." &
    XMSGPID=$!
    MODELINE0=`xvidtune | grep '^"[0-9]'`
    kill $XMSGPID
-   if [ ! "$MODELINE0" = "" ];then
+   if [ "$MODELINE0" ];then
     xmessage -bg orange -title "Xvidtune: Modeline" -buttons Write:10,Quit:11 "The new modeline is:
 $MODELINE0
 
@@ -778,7 +780,7 @@ fi
 
 #ddcprobe on my laptop returns one 'timing:' line but no 'monitorrange:', so
 #can fall back to calculating freqs...
-if [ ! "$MONCHOICES" = "" ];then
+if [ "$MONCHOICES" != "" ];then
  ##hmmm, maybe always use the freqs of the 'timing:' lines rather than the
  ##'monitorrange:' as it always seems to be too high...
  if [ "$HORIZSYNC" = "" -o "$VERTREFRESH" = "" ];then
@@ -843,7 +845,7 @@ if [ "$HORIZSYNC" = "" -o "$VERTREFRESH" = "" ];then #"" if monitor not plug-n-p
   2>"$TMP_DIR"/taggen.txt
   [ $? = 255 ] && exit
   CHOICE=`cat "$TMP_DIR"/taggen.txt 2>/dev/null | tail -n1`
-  [ "$CHOICE" = "" ] && continue
+  [ "$CHOICE" ] || continue
   ## Dougal: use case-structure for setting params -- safer than the old way
   ## (not sure why Barry only uses 16-bit, maybe worth improving?)
   case "$CHOICE" in
@@ -963,7 +965,7 @@ fi
 #if have MONCHOICES, that's all i want to display (with warning if not in card list).
 #if no MONCHOICES, then display card list only...
 echo -n "" > "$TMP_DIR"/finalchoices.txt
-if [ "$MONCHOICES" = "" ];then
+if [ ! "$MONCHOICES" ];then
  for ONECHOICE in $CARDCHOICES
  do
   if [ "$RECMODE" = "$ONECHOICE" ];then
@@ -1006,7 +1008,7 @@ echo ' --no-collapse --title "Puppy Video Wizard" --ok-label "OK" --extra-label 
 shown in the format WidthxHeightxBits, where Width and Height are
 screen resolution in pixels, 16/24 bits = 65,536/16,777,216 colors.
 ' >> "$TMP_DIR"/choosexmodedlg
-[ ! "$RECMODE" = "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >> "$TMP_DIR"/choosexmodedlg
+[ "$RECMODE" != "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >> "$TMP_DIR"/choosexmodedlg
 echo '\Z1RECOMMENDATION: Choose <TEST> button to verify it works!\Z0' >> "$TMP_DIR"/choosexmodedlg
 echo '
 OK:   Use the selected mode...
@@ -1145,7 +1147,7 @@ if grep -F -q 'Alps' /proc/bus/input/devices ; then
 echo "Copied /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic 9" >> "$TMP_DIR"/xorgwizard.messages && sleep 2s #9s
  cp /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic
  modprobe evdev
- if [ "`grep '^modprobe evdev' /etc/rc.d/rc.local`" = "" ];then #v2.17
+ if [ ! "`grep '^modprobe evdev' /etc/rc.d/rc.local`" ];then #v2.17
   echo "modprobe evdev" >> /etc/rc.d/rc.local
  fi
  # Where we want to insert new lines...
@@ -1376,7 +1378,7 @@ TAB then ENTER to tweak parameters in xorg.conf & retest X..." 0 0
  EXTRALABEL=""
  INTELDRVMSG=""
  I810OLD=`find /usr/lib/xorg/modules/drivers \( -type f -o -type l \) -name i810OLD_drv.so`
- if [ "$I810OLD" != "" ];then
+ if [ "$I810OLD" ];then
   if [ "${CARD0DRIVER}" = "intel" ];then
    TRYDRV='i810'
    EXTRABUTTON='--extra-button'
@@ -1495,7 +1497,7 @@ Press TAB then ENTER to open xorg.conf in a text editor..." 0 0
  RVAL4=$?
  [ $RVAL4 = 255 ] && exit
  if [ $RVAL4 -eq 0 ];then
-  if [ "$MONCHOICES" = "" ];then
+  if [ ! "$MONCHOICES" ];then
    #not plug-n-play.
    MSGPNP="WARNING: Your monitor is not plug-and-play so this Wizard cannot
          determine its max allowable refresh frequency. A very cheap old
