/usr/sbin/xorgwizard : Dialog text bugfixes for last commit. MSGwelcomeXVESA variable to contain same dialog text for two GUIS to select Xvesa/Commandline or Xorg. Cleanup obsolete commented code. Fix errors in tweak refresh code to test that HorizSync and VertRefresh ranges are less-more. Ranges more-less like 67-60 lead to Xorg not accepting the config file with obscure message, that the VertRefresh keyword needs a range value, wich is there, but in left->right descending range, needs to be left->rigt ascending like 60-67 .

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -106,7 +106,7 @@ XORG_TEST_RESULTS_FILE="$TMP_DIR"/xorgwizard_initrc_test_results
 alias Xorg="/usr/bin/Xorg $XORG_OPTS"
 
 XORG_DIALOG_TITLE="Puppy Xorg Video Wizard"
-XSERVER_DIALOG_TILTE="Puppy Video Server Wizard"
+XSERVER_DIALOG_TITLE="Puppy Video Server Wizard"
 
 VIEWER=less     #if DEBUG show log files
 VIEWER_OPTS=
@@ -342,26 +342,27 @@ sysctl -w kernel.printk=$LVL >>$OUT 2>>$ERR # do not say anything
 oldKERNEL_LOGLVL=`_get_kernel_loglevel`
 _set_kernel_loglevel 3 || : # TODO say something if it failed
 
-MSGwelcome="Welcome to the $XSERVER_DIALOG_TITLE!
+MSGwelcome="Welcome to the ${XSERVER_DIALOG_TITLE}!
 "
 #100401 if xorgwizard started with any passed param, bypass initial window...
 if [ ! "$1" ];then  ##0
 
 _offer_Xvesa(){  ##+++2013-04-12
- if [ "`which Xvesa`" != "" ];then #091125  ##1
+ #if [ "`which Xvesa`" != "" ];then #091125  ##1
   MSGwelcome="" #100820
-  #If video adapter would hang Xvesa, tell user and allow only Xorg.
-  #if [ -s "$TMP_DIR"/ddcprobeoem.txt ] || grep $Q -f /etc/xorgoverrides "$TMP_DIR"/ddcprobe.txt 2>>$ERR;then     #Xvesa hanger encountered  ##2
-  if [ -s "$TMP_DIR"/ddcprobeoem.txt ] || grep $Q -f /etc/xorgoverrides "$TMP_DIR"/ddcprobe.txt ;then
-   dialog --colors --title "$XSERVER_DIALOG_TITLE" \
-   --yes-label "Xorg" --no-label "Commandline" \
-   --yesno "Welcome to the XSERVER_$DIALOG_TITLE!
+  MSGwelcomeXVESA="Welcome to the ${XSERVER_DIALOG_TITLE}!
 
 Puppy has two X servers (to run Puppy in graphics mode):
 Xvesa: A very small and simple \"Kdrive\" X server.
 Xorg:  A very large and sophisticated X server, with many hardware-
        specific drivers for optimum performance ( note: there is also
-       a generic Xorg driver named 'vesa', not the same as Xvesa ! )
+       a generic Xorg driver named 'vesa', not the same as Xvesa ! )"
+  #If video adapter would hang Xvesa, tell user and allow only Xorg.
+  #if [ -s "$TMP_DIR"/ddcprobeoem.txt ] || grep $Q -f /etc/xorgoverrides "$TMP_DIR"/ddcprobe.txt 2>>$ERR;then     #Xvesa hanger encountered  ##2
+  if [ -s "$TMP_DIR"/ddcprobeoem.txt ] || grep $Q -f /etc/xorgoverrides "$TMP_DIR"/ddcprobe.txt ;then ##2
+   dialog --colors --title "$XSERVER_DIALOG_TITLE" \
+   --yes-label "Setup Xorg" --no-label "Commandline" \
+   --yesno "$MSGwelcomeXVESA
 
 \Z1Your video hardware likely would cause the Xvesa server to freeze Puppy, 
 so your options are to use Xorg or exit to the command prompt.\Z0
@@ -372,55 +373,43 @@ Make sure you have at least 96 MB of RAM+SWAP, for Xorg to function.
 But some quirky video hardware does not work with either Xorg and Xvesa, 
 in which case you can only operate from the command line.  
 
-Press ENTER for Xorg...
+Press ENTER for setting up Xorg...
 Press TAB (or right-arrow) key then ENTER key to use the command line...\Zn" 0 0
-   #[ ! $? -eq 0 ] && exit
-   if [ ! $? -eq 0 ] ; then ##---2011-11-22 CONFUSED due to not had experience with this GUI
-   #echo
-   #echo
-   #echo "linking Xvesa /usr/bin/X ..."
-   #echo "to restore Xorg , remove /usr/bin/X and link it manually ln $VERB -s  Xorg /usr/bin/X"
-   #echo
-   #rm /usr/bin/X
-   #ln -s Xvesa /usr/bin/X
-   exit
+   if [ $? -ne 0 ] ; then #no button returns 1, ESC 255
+   exit 0
    fi
-   ###---2011-11-22</CONFUSED>
   else   #normal video adapter  ##2
    #offer to drop out to Xvesa...
    dialog --colors --title "$XSERVER_DIALOG_TITLE" \
-   --yes-label "Xorg server" --no-label "Xvesa server" \
-   --yesno "Welcome to the $XSERVER_DIALOG_TITLE!
-
-Puppy has two X servers (to run Puppy in graphics mode):
-Xvesa: A very small and simple \"Kdrive\" generic X server.
-Xorg:  A very large and sophisticated X server, with many hardware-
-       specific drivers for optimum performance ( note: there is also
-       a generic Xorg driver named 'vesa', not the same as Xvesa ! )
+   --yes-label "Xorg Server" --no-label "Xvesa Server" \
+   --yesno "$MSGwelcomeXVESA
 
 Xvesa works flawlessly on most video hardware, simple to configure,
 but one major disadvantage is that screen refresh rate is fixed.
 Also, Xvesa has limited support for input devices, and lacks features
 like hardware-acceleration (video may be jerky on slow PCs).
 
-It is recommended that you choose the <Xorg> button now, but some
+It is recommended to choose the <Xorg Server> button now, but some
 quirky video hardware does not work with Xorg, in which case you can
-run this Wizard again and choose the <Xvesa> button.
+run this Wizard again and choose the <Xvesa Server> button.
 
 Press ENTER for Xorg...
 Press TAB (or right-arrow) key then ENTER key for Xvesa...\Zn" 0 0
    STATUS=$?  #v3.99
-   [ "$STATUS" -eq '-1' -o "$STATUS" -eq 255 ] && exit   #v3.99 ESC to exit, same as above dialogs  ##+2011-11-22 added 255 test for ESC key ; CRTL+C returns '1' , CNTR+Z clears screen returning '0'
+   case "$STATUS" in -1|255) exit 255;; esac  #v3.99 ESC to exit, same as above dialogs  
+   ##+2011-11-22 added 255 test for ESC key ; CRTL+C returns '1' , CNTR+Z clears screen returning '0'
    if [ "$STATUS" -eq 1 ];then   #v3.99 Xvesa selected  ##3
     echo;echo;echo "linking Xvesa /usr/bin/X ..."  ##+++2011-11-22
     rm $VERB /usr/bin/X
     ln $VERB -sf Xvesa /usr/bin/X #Xvesa is now the default X server.
     if [ "$?" -eq 0 ] ; then
-     echo -e "\e[1;32m""Type ' xwin ' to start Xvesa server""\e[0;39m"
+     echo -e "\e[1;32m""Type ' xwin ' to start Desktop with Xvesa server""\e[0;39m"
+     true
     else
      echo -e "\e[1;31m""ERROR linking ' Xvesa /usr/bin/X '""\e[0;39m"
+     false
     fi
-    exit ###+++2011-11-22 CONMMENTED ALL PARTS OUT BELOW:
+    exit $? ###+++2011-11-22 CONMMENTED ALL PARTS OUT BELOW:
     #when start xorgwizard from commandline, it messes up xorg.conf...
     #if [ -f "$XORG_CONF_FILE" ];then  ##4
      #if [ -f "$XORG_CONF_FILE".bak ];then  ##5
@@ -435,7 +424,7 @@ Press TAB (or right-arrow) key then ENTER key for Xvesa...\Zn" 0 0
     #exit #w478
    fi  ##3
   fi   #v3.99  ##2
- fi  ##1
+ #fi  ##1 which Xvesa
 }
 
 which Xvesa >>$OUT && _offer_Xvesa
@@ -488,7 +477,7 @@ fi
 _choose_driver_msg
 
  dialog --colors --title "$XORG_DIALOG_TITLE" \
- --ok-label "Probe" --cancel-label "vesa" \
+ --ok-label "Probe" --cancel-label "vesa driver" \
  --extra-button --extra-label "Choose" \
  --yesno "${MSGwelcome}'Xorg' (or just 'X') is software that will run Puppy in graphics mode,
 that is, display a desktop with windows, mouse, etc. Xorg has a dozen
@@ -509,7 +498,7 @@ Press ENTER key to probe for correct hardware-specific driver...
 Or, TAB then ENTER to choose another driver...
 Or, TAB, TAB then ENTER to select the generic vesa driver..." 0 0
  STATUS=$?
- [ "$STATUS" -lt 0 -o "$STATUS" -ge 254 ] && exit
+ [ "$STATUS" -lt 0 -o "$STATUS" -ge 254 ] && exit 255
  ALLDRIVERS="`ls -1 "$XORG_MODULE_DIR"/drivers | grep 'so$'`"
  #ALLDRIVERS="`ls -1 "$XORG_MODULE_DIR"/drivers 2>>$ERR | grep 'so$'`"
  ###+2011_10_30 added 2>>$ERR
@@ -520,18 +509,20 @@ Or, TAB, TAB then ENTER to select the generic vesa driver..." 0 0
   fi  ##12
  else  ##11
   if [ "$STATUS" -eq 3 ];then #100401 choose. 100430 improved... 100820 improved... ##13
-#   ALLDRVLIST="`ls -1 "$XORG_MODULE_DIR"/drivers "$XORG_MODULE_DIR"/drivers-alternate "$XORG_MODULE_DIR"/drivers-backup 2>>$ERR | grep -E '^[a-zA-Z0-9].*_drv.so' | cut -f 1 -d '_' | tr '\n' ' '`"
+
+_create_xorg_driver_list(){
+#   ALLDRVLIST="`ls -1 "$XORG_MODULE_DIR"/drivers "$XORG_MODULE_DIR"/drivers-alternate "$XORG_MODULE_DIR"/drivers-backup 2>>$ERR | grep -E '^[a-zA-Z0-9].*_drv.so' | cut -f 1 -d '_'`"
 #   dialog --title "$XORG_DIALOG_TITLE" --inputbox "Here are all the Xorg drivers:
 #${ALLDRVLIST}
 #
 #Type the name of the one you want to use and press ENTER:" 0 0 2>"$TMP_DIR"/tagchosendrv.txt
-   #ALLDRVLIST="`ls -1 "$XORG_MODULE_DIR"/drivers "$XORG_MODULE_DIR"/drivers-alternate "$XORG_MODULE_DIR"/drivers-backup 2>>$ERR | grep -E '^[a-zA-Z0-9].*_drv.so' | cut -f 1 -d '_' | sort -u | tr '\n' ' '`"
+   #ALLDRVLIST="`ls -1 "$XORG_MODULE_DIR"/drivers "$XORG_MODULE_DIR"/drivers-alternate "$XORG_MODULE_DIR"/drivers-backup 2>>$ERR | grep -E '^[a-zA-Z0-9].*_drv.so' | cut -f 1 -d '_' | sort -u`"
    ALLDRVLIST=`ls -1 "$XORG_MODULE_DIR"/drivers "$XORG_MODULE_DIR"/drivers-alternate "$XORG_MODULE_DIR"/drivers-backup | grep -E '^[a-zA-Z0-9]+*_drv.so' | cut -f 1 -d '_' | sort -u`
 
    drvLIST=""
    for oneDRV in $ALLDRVLIST
    do
-    if [ -h "$XORG_MODULE_DIR"/drivers/${oneDRV}_drv.so ];then #ignore hyperlinks  ##14
+    if [ -L "$XORG_MODULE_DIR"/drivers/${oneDRV}_drv.so ];then #ignore links  ##14
      #[ -h "$XORG_MODULE_DIR"/drivers/i810_drv.so ] && rm $VERB -f "$XORG_MODULE_DIR"/drivers/i810_drv.so #should not be there.
      continue
     fi  ##14
@@ -671,16 +662,29 @@ ${oneDRV} ${oneDRV}"
     esac
    done
    drvLIST="`echo "$drvLIST" | sort -k 2 -t " " | tr '\n' ' '`"
-   drvDLG="dialog --title \"$XORG_DIALOG_TITLE\" --menu \"Choose a Xorg driver (down-arrow or up-arrow then ENTER):\" 0 0 0 ${drvLIST}"
-   eval $drvDLG 2>"$TMP_DIR"/tagchosendrv.txt
-
-   if [ $? -eq 0 ];then  ##15
+}
+_create_xorg_driver_list
+   
+  if test "$drvLIST"; then
+    drvDLG="dialog --title \"$XORG_DIALOG_TITLE\" --menu \"Choose a Xorg driver (down-arrow or up-arrow then ENTER):\" 0 0 0 ${drvLIST}"
+    eval $drvDLG 2>"$TMP_DIR"/tagchosendrv.txt
+    STATUS=$?
+  else
+    STATUS=253 
+  fi
+   
+  if [ "$STATUS" -eq 0 ];then  ##15
     CHOSENDRV="`cat "$TMP_DIR"/tagchosendrv.txt`"
     echo "1: RESTARTING '$MY_SELF' CHOSENDRV='$CHOSENDRV'"
     sleep 5s
     alternate_driver_func $CHOSENDRV
     exec "$MY_SELF" $CHOSENDRV ###RESTART### note, passed param causes bypass of the initial window.
-   else  ##15
+  elif [ "$STATUS" -eq 253 ];then
+     _err "FIXME: Failure creating dirver list to select in menu."
+    exit 255
+  elif [ "$STATUS" -eq 255 ];then
+    exit 255
+  else  ##15
     echo "2: RESTARTING '$MY_SELF' without driver parameter"
     sleep 5s
     exec "$MY_SELF" ###RESTART###
@@ -692,7 +696,7 @@ ${oneDRV} ${oneDRV}"
    cp $VERB -f "$XORG_MODULE_DIR"/drivers-backup/vesa_drv.so "$XORG_MODULE_DIR"/drivers/
   fi  ##13
  fi  ##11
-fi ##0  # no option/parameter
+fi ##0  # option/no option/parameter
 
 #resolution changer uses this. it must be removed here...
 rm $VERB -f /etc/xrandrindex
@@ -702,27 +706,28 @@ ln $VERB -sf Xorg /usr/bin/X
 # Dougal: moved echo to below xorg probing, since loop isn't slow anymore...
 [ "$DEBUG" ] || clear
 echo -en "\\033[1;35m" #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
-echo -n "Probing video hardware, please wait..."
+echo -n "Xorg Probing video hardware, please wait..."
 echo -e "\\033[0;39m"
 #autoprobe...
 Xorg -configure >"$TMP_DIR"/xorgprobe.txt 2>&1
 test $? = 0 || {
 echo -e '\033[1;31m'"Xorg -configure may have crashed."
-echo "Press any key to show logfile in less viewer "
-echo -en "Press 'Q' to quit the less viewer "'\033[0;39m'
+echo "Press any key to show logfile in $VIEWER viewer "
+#echo -en "Press 'Q' to quit the less viewer "'\033[0;39m' #VIEWER_MSG="To exit the viewer, press 'q' key."
+echo -en "$VIEWER_MSG "'\033[0;39m'
 read -n1 GOON
-less "$TMP_DIR"/xorgprobe.txt
+$VIEWER $VIEWER_OPTS "$TMP_DIR"/xorgprobe.txt
 
 if test -e /root/xorg.conf.new; then
- echo -en '\033[1;31m'"Press any key to show new xorg.conf.new file in less viewer "'\033[0;39m'
+ echo -en '\033[1;31m'"Press any key to show new xorg.conf.new file in $VIEWER viewer "'\033[0;39m'
  read -n1 GOON
- less /root/xorg.conf.new
+ $VIEWER $VIEWER_OPTS /root/xorg.conf.new
 else
-echo -e '\033[1;31m'"Xorg -configure failed to create a usable xorg.conf.new file."
-echo -e '\033[1;33m'"We will go on though.."
-echo -en '\033[1;31m'"Press any key to go on "'\033[0;39m'
-read -n1 GOON
-cp $VERB "${XORG_CONF_FILE}0" /root/xorg.conf.new
+ echo -e '\033[1;31m'"Xorg -configure failed to create a usable xorg.conf.new file."
+ echo -e '\033[1;33m'"We will go on though..and hoping for the best.."
+ echo -en '\033[1;31m'"Press any key to go on "'\033[0;39m'
+ read -n1 GOON
+ cp $VERB "${XORG_CONF_FILE}0" /root/xorg.conf.new
 fi
 }
 #... config in /root/xorg.conf.new
@@ -877,7 +882,7 @@ cp $VERB -f "$TMP_DIR"/xorg.conf.mousefix "$XORG_CONF_FILE"
 
 #echo "Probing the video card and monitor..."
 #code below is not distinguishing multiple cards/monitors...
-HORIZSYNC="$HORIZSYNC0"
+  HORIZSYNC="$HORIZSYNC0"
 VERTREFRESH="$VERTREFRESH0"
 test "$CARD0DRIVER" || CARD0DRIVER=UNKNOWN
 
@@ -905,7 +910,7 @@ TIMINGOK="yes"
 if [ -s "$TMP_DIR"/ddcprobeoem.txt ];then   #v3.99 begin
  if [ ! -f /etc/xorgoverrides ] || ! grep -f "$TMP_DIR"/ddcprobeoem.txt /etc/xorgoverrides;then
   echo "`cat "$TMP_DIR"/ddcprobeoem.txt`" >>/etc/xorgoverrides  #append new signature if user canceled out from hung Xvesa
-  sync
+  _sync
  fi
 fi
 if [ -f /etc/xorgoverrides ] && grep -f /etc/xorgoverrides "$TMP_DIR"/ddcprobe.txt;then   #v3.99 end
@@ -949,10 +954,16 @@ DMIDECODE="`dmidecode`"
 #modes supported by card...
 CARDCHOICES=""
 if [ -e /usr/bin/Xvesa -a "$XVESALISTOK" = "yes" ];then #format of each line: 1024x768x16
- echo -e '\nIf initialization freezes here, press ctrl-c and type "xorgwizard",\nselect "Xorg", choose monitor type and choose video mode.'   #v3.99
+ ( sleep 2;
+ echo -e '\nUsing Xvesa -listmodes to gain supported resolution modes..
+If initialization freezes here, press ctrl-c and type "xorgwizard",
+select "Xorg", choose monitor type and choose video mode.' ) &  #v3.99
  grep '^oem:' "$TMP_DIR"/ddcprobe.txt >"$TMP_DIR"/ddcprobeoem.txt   #v3.99 current adapter signature
- Xvesa -listmodes 2>&1 | cut -f 2 -d ' ' | grep -E 'x16$|x24$' | sort -t x -n >"$TMP_DIR"/Xmodes.txt
+ busybox timeout -t 20 -s 2 Xvesa -listmodes 2>&1 | cut -f 2 -d ' ' | grep -E 'x16$|x24$' | sort -t x -n >"$TMP_DIR"/Xmodes.txt
+ [ $? = 0 ] || exit 255
  rm $VERB "$TMP_DIR"/ddcprobeoem.txt  #v3.99 didn't hang in Xvesa, so delete signature
+ sleep 3
+ echo -e $Green1'Xvesa -listmodes completed'$Reset0
 else
  #the vesa 'mode:' lines returned by ddcprobe are very limited...
  grep '^mode:' "$TMP_DIR"/ddcprobe.txt | grep -E 'x64k|x16m'| cut -f 2 -d ' ' | sed -e 's/x64k/x16/g ; s/x16m/x24/g' >"$TMP_DIR"/Xmodes.txt
@@ -1032,12 +1043,12 @@ if [ "$MONCHOICES" != "" ];then
   done
   #v3.93 hmmm, above still can round down too much, add 2...
   UHORIZSYNC=$((UHORIZSYNC + 2))
-  if [ $LHORIZSYNC -le $UHORIZSYNC ]; then
+  if [ "$LHORIZSYNC" -le $UHORIZSYNC ]; then
   HORIZSYNC="${LHORIZSYNC}-${UHORIZSYNC}"
   else
   HORIZSYNC="${UHORIZSYNC}-${LHORIZSYNC}"
   fi
-  if [ $LVERTREFRESH -le $UVERTREFRESH ]; then
+  if [ "$LVERTREFRESH" -le $UVERTREFRESH ]; then
   VERTREFRESH="${LVERTREFRESH}-${UVERTREFRESH}"
   else
   VERTREFRESH="${UVERTREFRESH}-${LVERTREFRESH}"
@@ -1383,8 +1394,8 @@ fi
 #MINVERT=`echo -n "$VERTREFRESH" | grep -o '^[0-9]*'`
 #MINHORIZ=`echo -n "$HORIZSYNC" | grep -o '^[0-9]*'`
 MAXHORIZ=${HORIZSYNC#*-}  #; MAXHORIZ=${MAXHORIZ%.*}
-MINVERT=${VERTREFRESH%-*} #;  MINVERT=${MINVERT%.*}
 MINHORIZ=${HORIZSYNC%-*}  #; MINHORIZ=${MINHORIZ%.*}
+MINVERT=${VERTREFRESH%-*} #;  MINVERT=${MINVERT%.*}
 
 #now write the Screen section...
 #091119 handle multiple screens... 100430 add metamodes entry...
@@ -2043,7 +2054,7 @@ Press TAB then ENTER to open xorg.conf in a text editor..." 0 0
  EXVAL10=$?
  if [ "$EXVAL10" -eq 255 ]; then
   exit 255
- elif [ $EXVAL10 -eq 0 ];then
+ elif [ "$EXVAL10" -eq 0 ];then
   if [ "$MONCHOICES" = "" ];then
    #not plug-n-play.
    MSGPNP="WARNING: Your monitor is not plug-and-play so this Wizard cannot
@@ -2089,16 +2100,38 @@ $MSGPNP" 0 0 0 \
   CHOSENVERT=`tail -n1 "$TMP_DIR"/tagvert.txt`
   NEEDHORIZ=`gtf $XTEST $YTEST $CHOSENVERT | grep -o 'hsync: .*' | cut -f 2 -d ' ' | cut -f 1 -d '.'`
   let NEEDHORIZ=NEEDHORIZ+1 #compensate for rounding off error.
-  aPATTERN="s/HORIZSYNC0/${HORIZSYNC}/g"
-  if [ "$NEEDHORIZ" -gt ${MAXHORIZ%.*} ];then
-   if [ "$MONCHOICES" = "" ];then
-    #monitor not plug and play.
-    aPATTERN="s/HORIZSYNC0/${MINHORIZ}\\-${NEEDHORIZ}/g"
+  aPATTERN="s/HORIZSYNC0/${HORIZSYNC}/"
+  #if [ "$NEEDHORIZ" -gt ${MAXHORIZ%.*} ];then
+  # if [ "$MONCHOICES" = "" ];then
+  #  #monitor not plug and play.
+  #  aPATTERN="s/HORIZSYNC0/${MINHORIZ}\\-${NEEDHORIZ}/"
+  # fi
+  #fi
+  if test ${MINHORIZ%.*} -le ${MAXHORIZ%.*}; then
+   if test ${NEEDHORIZ%.*} -le ${MINHORIZ%.*}; then
+    aPATTERN="s/HORIZSYNC0/${NEEDHORIZ}\\-${MAXHORIZ}/"
+    MINHORIZ=$NEEDHORIZ
+   else
+    aPATTERN="s/HORIZSYNC0/${MINHORIZ}\\-${MAXHORIZ}/"
+   fi
+  else
+   if test ${NEEDHORIZ%.*} -ge ${MINHORIZ%.*}; then
+    aPATTERN="s/HORIZSYNC0/${MINHORIZ}\\-${MAXHORIZ}/"
+   else
+    aPATTERN="s/HORIZSYNC0/${NEEDHORIZ}\\-${MAXHORIZ}/"
+    MINHORIZ=$NEEDHORIZ
    fi
   fi
   sed -e "$aPATTERN" "$TMP_DIR"/xorg.conf.tmp >"$TMP_DIR"/xorg.conf.tmp2
-  bPATTERN="s/VERTREFRESH0/${MINVERT}\\-${CHOSENVERT}/g"
+  
+  if test ${MINVERT%.*} -le ${CHOSENVERT%.*}; then
+   bPATTERN="s/VERTREFRESH0/${MINVERT}\\-${CHOSENVERT}/"
+  else
+   bPATTERN="s/VERTREFRESH0/${CHOSENVERT}\\-${MINVERT}/"
+   MINVERT=$CHOSENVERT
+  fi
   _sync
+
   sed -e "$bPATTERN" "$TMP_DIR"/xorg.conf.tmp2 >"$XORG_CONF_FILE"
   _sync
 
@@ -2111,8 +2144,12 @@ $MSGPNP" 0 0 0 \
   else
    sed -i'.sed' -e "$mm2PATTERN" "$XORG_CONF_FILE"
   fi
-
-  rm $VERB -f "$TMP_DIR"/xorg.conf.tmp2
+    newHORIZSYNC=`grep    'HorizSync'         "$XORG_CONF_FILE" | grep -v '^[[:blank:]]*#' | head -n1 | awk '{print $2}'`
+  test "$newHORIZSYNC"   && HORIZSYNC=$newHORIZSYNC
+  newVERTREFRESH=`grep    'VertRefresh'       "$XORG_CONF_FILE" | grep -v '^[[:blank:]]*#' | head -n1 | awk '{print $2}'`
+  test "$newVERTREFRESH" && VERTREFRESH=$newVERTREFRESH
+  [ "$DEBUG" ] && rm $VERB -f "$TMP_DIR"/xorg.conf.tmp2
+ 
  else
   dialog --no-collapse --title "$XORG_DIALOG_TITLE" \
   --msgbox "Before editing xorg.conf, consider this...
