/usr/sbin/xorgwizard: Improve the formatting of the PROFILECHIP and PROFILEMONITOR variables. Fallback to UnknowChip and UnknownMonitor. Use _command lspci because busybox lspci does not find or use the pci.ids file.
When using SUBSTDRV, add the former Driver "name" after #card0driver marker
ie modesetting when changing driver and selecting eg. "vesa" .

Add 1600x900 and 1600x1050 modes to select in resolution fallback menu.

Fix a few colouration variables $Res to $Reset0 .

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -359,7 +359,7 @@ fi
 #and xorg.conf has been removed.
 
 #v3.99 begin
-echo "Lowlevel probing the video card and monitor..."
+echo -e $Pink1"Lowlevel probing the video card and monitor..."$Reset0
 _do_ddcprobe(){
 _edebug $Red0"_do_ddcprobe";
 
@@ -390,7 +390,7 @@ _edebug $Red0"_do_ddcprobe";
 
   sleep 2s
   case "`cat "$tmpDIR"/ddcprobe.txt`" in *edidfail*)
-   _notice "ddcprobe failed to determine the video";
+   _notice "ddcprobe failed to determine the monitor's edid";
    _info "Trying again..";
    sleep 1
    DDCPROBE=`ddcprobe`
@@ -411,9 +411,11 @@ _edebug $Red0"_do_ddcprobe";
  _get_edid
 
 if [ -n "`grep -i 'edidfail' "$tmpDIR"/ddcprobe.txt`" ]; then
-echo -e $Red1"ddcprobe still failed to determine the video.."$Res
-echo -e "Exiting $0 now."
-exit 20
+ if ! grep $Q '^mode:' "$tmpDIR"/ddcprobe.txt; then
+  echo -e $Red1"ddcprobe still failed to determine the video monitor.."$Reset0
+  echo -e "Exiting $0 now."
+  exit 20
+ fi
 fi
 }
 _do_ddcprobe
@@ -567,7 +569,7 @@ fi
 # Dougal: moved echo to below xorg probing, since loop isn't slow anymore...
 ##clear
 #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
-echo -e $Pink1"Probing video hardware 'Xorg -configure' , please wait.."$Res
+echo -e $Pink1"Probing video hardware 'Xorg -configure' , please wait.."$Reset0
 #autoprobe...
 Xorg -configure -logfile "$HOME"/Xorg_configure.log > "$tmpDIR"/xorgprobe.txt 2>&1 #... config in $HOME/xorg.conf.new
 XorgConfRV=$?
@@ -769,12 +771,12 @@ $aLINE
         *Driver*) CARD0DRIVER="$FBODY"; aLINE="$aLINE #card0driver" ;;
         *VendorName*) CARD0VENDOR="$FBODY"
          case "$CARD0VENDOR" in 'Unknown Vendor'|'')
-          CARD0VENDOR="lscpi: `_command lspci | grep -i 'display controller' |rev|cut -f1 -d: |rev`"
+          CARD0VENDOR="lscpi: `_command lspci | grep -i 'display controller' |rev|cut -f1 -d: |rev | tr '[[:punct:][:blank:]]' '_' | tr -s '_'`"
           ;; esac
         ;;
         *BoardName*) CARD0BOARD="$FBODY"
          case "$CARD0BOARD" in 'Unknown Board'|'')
-          CARD0BOARD="lscpi: `_command lspci | grep -i 'VGA compatible controller' |rev|cut -f1 -d: |rev`"
+          CARD0BOARD="lscpi: `_command lspci | grep -i 'VGA compatible controller' |rev|cut -f1 -d: |rev | tr '[[:punct:][:blank:]]' '_' | tr -s '_'`"
           ;; esac
         ;;
         *Screen[0-9]*Top?Of*Screen0*) aLINE="#$aLINE" ;;
@@ -823,13 +825,13 @@ $(cat "$HOME"/xorg.conf.new | sed 's!$!__XORGWIZARD__!' | tr -d '\n' | sed 's/En
 _END1
 ###################################################################
 else
- echo -e $Red1"Xorg -configure failed to create some usable $$HOME/xorg.conf.new file."$Res
- echo -e $Red0"Please up- or downgrade the kernel or Xorg."$Res
+ echo -e $Red1"Xorg -configure failed to create some usable $$HOME/xorg.conf.new file."$Reset0
+ echo -e $Red0"Please up- or downgrade the kernel or Xorg."$Reset0
  exit 252
 fi
 
-test "$CARD0VENDOR" || CARD0VENDOR="lscpi: `_command lspci | grep -i 'display controller' |rev|cut -f1 -d: |rev`"
-test "$CARD0BOARD"  ||  CARD0BOARD="lscpi: `_command lspci | grep -i 'VGA compatible controller' |rev|cut -f1 -d: |rev`"
+test "$CARD0VENDOR" || CARD0VENDOR="lscpi: `_command lspci | grep -i 'display controller' |rev|cut -f1 -d: |rev | tr '[[:punct:][:blank:]]' '_' | tr -s '_'`"
+test "$CARD0BOARD"  ||  CARD0BOARD="lscpi: `_command lspci | grep -i 'VGA compatible controller' |rev|cut -f1 -d: |rev | tr '[[:punct:][:blank:]]' '_' | tr -s '_'`"
 HORIZSYNC="$HORIZSYNC0"
 VERTREFRESH="$VERTREFRESH0"
 
@@ -1087,26 +1089,28 @@ CRT: Cathode Ray Tube (normal monitor).
 Choose \"Z\" if you have the monitor user manual, and it has the
 horizontal and vertical frequency specifications.
 DOWN-ARROW to highlight choice, ENTER key to finish..."  0 0 0 \
- "A" "h31.5v40-70       LCD Panel 640x480" \
- "B" "h31.5-37v40-70    LCD Panel 800x600" \
- "B2" "h31.5-90v60      LCD Panel 1024x600" \
- "C" "h31.5-48.5v40-70  LCD Panel 1024x768" \
- "D" "h31.5-90v60       LCD Panel 1280x800" \
- "E" "h31.5-67v50-75    LCD Panel 1280x1024" \
- "F" "h31.5-90v60       LCD Panel 1360x768" \
- "G" "h31.5-90v59-75    LCD Panel 1400x1050" \
- "H" "h31.5-100v59-75   LCD Panel 1440x900" \
- "I" "h31.5-90v60       LCD Panel 1600x1200" \
- "J" "h31.5-90v60       LCD Panel 1680x1050" \
- "K" "h30-68v67         LCD HDTV  1920x1080" \
- "L" "h31.5-90v60       LCD Panel 1920x1200" \
- "M" "h31.5v50-61       CRT 640x480" \
- "N" "h31.5-35v50-61    CRT 800x600 (old 14inch monitor)" \
- "O" "h31.5-48.5v56-72  CRT 1024x768 (basic 15inch monitor)" \
- "P" "h31.5-79v50-90    CRT 1280x1024 (basic 17inch monitor)" \
- "Q" "h31.5-90v50-90    CRT 1400x1050" \
- "R" "h31.5-94v50-90    CRT 1600x1200" \
- "Z" "SELECT THIS IF YOU KNOW MONITOR FREQUENCY SPECS" \
+ "A"  "h31.5v40-70       LCD Panel 640x480" \
+ "B"  "h31.5-37v40-70    LCD Panel 800x600" \
+ "B2" "h31.5-90v60       LCD Panel 1024x600" \
+ "C"  "h31.5-48.5v40-70  LCD Panel 1024x768" \
+ "D"  "h31.5-90v60       LCD Panel 1280x800" \
+ "E"  "h31.5-67v50-75    LCD Panel 1280x1024" \
+ "F"  "h31.5-90v60       LCD Panel 1360x768" \
+ "G"  "h31.5-90v59-75    LCD Panel 1400x1050" \
+ "H"  "h31.5-100v59-75   LCD Panel 1440x900" \
+ "I3" "h31.5-90v60       LCD Panel 1600x900" \
+ "I2" "h31.5-90v60       LCD Panel 1600x1050" \
+ "I"  "h31.5-90v60       LCD Panel 1600x1200" \
+ "J"  "h31.5-90v60       LCD Panel 1680x1050" \
+ "K"  "h30-68v67         LCD HDTV  1920x1080" \
+ "L"  "h31.5-90v60       LCD Panel 1920x1200" \
+ "M"  "h31.5v50-61       CRT 640x480" \
+ "N"  "h31.5-35v50-61    CRT 800x600 (old 14inch monitor)" \
+ "O"  "h31.5-48.5v56-72  CRT 1024x768 (basic 15inch monitor)" \
+ "P"  "h31.5-79v50-90    CRT 1280x1024 (basic 17inch monitor)" \
+ "Q"  "h31.5-90v50-90    CRT 1400x1050" \
+ "R"  "h31.5-94v50-90    CRT 1600x1200" \
+ "Z"  "SELECT THIS IF YOU KNOW MONITOR FREQUENCY SPECS" \
   2>"$tmpDIR"/taggen.txt
   RV1="$?";
   [ "$RV1" -eq -1 -o "$RV1" -eq 255 ] && exit 1
@@ -1160,7 +1164,17 @@ DOWN-ARROW to highlight choice, ENTER key to finish..."  0 0 0 \
      HORIZSYNC="31.5-100"
      VERTREFRESH="59-75"
      ;;
-   I) # "h31.5-90v60        LCD Panel 1600x1200"
+  I3) # "h31.5-90v60       LCD Panel 1600x900"
+     REC_VIDEO_MODE="1600x900x16"
+     HORIZSYNC="31.5-90"
+     VERTREFRESH="50-76"
+    ;;
+  I2) # "h31.5-90v60       LCD Panel 1600x1050"
+     REC_VIDEO_MODE="1600x1050x16"
+     HORIZSYNC="31.5-90"
+     VERTREFRESH="50-76"
+    ;;
+  I) # "h31.5-90v60        LCD Panel 1600x1200"
      REC_VIDEO_MODE="1600x1200x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="60"
@@ -1218,7 +1232,7 @@ DOWN-ARROW to highlight choice, ENTER key to finish..."  0 0 0 \
      RV3="$?";
      [ "$RV3" -eq -1 -o "$RV3" -eq 255 ] && exit 1
        HORIZSYNC=`cat "$tmpDIR"/taghoriz.txt 2>>$ERR | tail -n1`
-     VERTREFRESH=`cat "$tmpDIR"/tagvert.txt 2>>$ERR | tail -n1`
+     VERTREFRESH=`cat "$tmpDIR"/tagvert.txt  2>>$ERR | tail -n1`
      [ "$HORIZSYNC" ]   || continue
      [ "$VERTREFRESH" ] || continue
      # comment out -- it's the default from above
@@ -1245,7 +1259,16 @@ if [ "$MONCHOICES" = "" ];then
    echo "$oneCHOICE \"Unconfirmed for monitor, OK for video card\" \\"   >> "$tmpDIR"/finalchoices.txt
   fi
  done
- for oneCHOICE in 640x480x16 800x600x16 1024x600x16 1024x768x16 1280x800x16 1280x1024x16 1360x768x16 1400x1050x16 1440x900x16 1600x1200x16 1680x1050x16 1920x1080x16 1920x1200x16 640x480x24 800x600x24 1024x600x24 1024x768x24 1280x800x24 1280x1024x24 1360x768x24 1400x1050x24 1440x900x24 1600x1200x24 1680x1050x24 1920x1080x24 1920x1200x24
+ for oneCHOICE in 640x480x16 800x600x16 \
+ 1024x600x16  1024x768x16  1280x800x16  1280x1024x16 \
+ 1360x768x16  1400x1050x16 1440x900x16 \
+ 1600x900x16  1600x1050x16 1600x1200x16 1680x1050x16 \
+ 1920x1080x16 1920x1200x16 \
+ 640x480x24   800x600x24 \
+ 1024x600x24  1024x768x24  1280x800x24  1280x1024x24 \
+ 1360x768x24  1400x1050x24 1440x900x24 \
+ 1600x900x24  1600x1050x24 1600x1200x24 1680x1050x24 \
+ 1920x1080x24 1920x1200x24
  do
   case "$CARDCHOICES" in *$oneCHOICE*) :;; *) # we've done CARDCHOICES above
    echo "$oneCHOICE \"Unconfirmed for monitor, maybe NOT OK for card\" \\" >> "$tmpDIR"/finalchoices.txt ;;
@@ -1413,21 +1436,22 @@ MINHORIZ=${HORIZSYNC%-*}   #; MINHORIZ=${MINHORIZ%.*}
 _write_hardware_profile(){
 test "$KEEP_XORG_CONF" && return 0
 #v2.13 want a hardware profile so can bootup on different PCs...
-   PROFILECHIP=`grep -m1 '^oem: '     "$tmpDIR"/ddcprobe.txt |cut -f2  -d ' ' | sed 's/[[:punct:]]/_/g'`  #was cut -f 2-4 -d ' '| tr ' ' '_' | sed -e 's/[^0-9a-zA-Z]/_/g'
- PROFILEVENDOR=`grep -m1 '^vendor: '  "$tmpDIR"/ddcprobe.txt |cut -f2- -d ' ' | sed 's/[[:punct:]]/_/g'`
-PROFILEPRODUCT=`grep -m1 '^product: ' "$tmpDIR"/ddcprobe.txt |cut -f2- -d ' ' | sed 's/[[:punct:]]/_/g'`
+   PROFILECHIP=`grep -m1 '^oem: '     "$tmpDIR"/ddcprobe.txt |cut -f2  -d ' ' | sed 's/[[:punct:][:space:]]/_/g' | tr -s '[:punct:]'`  #was cut -f 2-4 -d ' '| tr ' ' '_' | sed -e 's/[^0-9a-zA-Z]/_/g'
+ PROFILEVENDOR=`grep -m1 '^vendor: '  "$tmpDIR"/ddcprobe.txt |cut -f2- -d ' ' | sed 's/[[:punct:][:space:]]/_/g' | tr -s '[:punct:]'`
+PROFILEPRODUCT=`grep -m1 '^product: ' "$tmpDIR"/ddcprobe.txt |cut -f2- -d ' ' | sed 's/[[:punct:][:space:]]/_/g' | tr -s '[:punct:]'`
    PROFILECHIP="${PROFILECHIP} ${PROFILEPRODUCT}"
-[ "${PROFILECHIP// /}" ] || PROFILECHIP=`lspci | grep -m1 -iE 'graph|vga|display' |cut -f3 -d':' | tr -s '[[:blank:]]' | sed 's%^ *%%;s% *$%%;s%[^[:alnum:]]%_%g'`
+[ "${PROFILECHIP// /}" ] || PROFILECHIP=`_command lspci | grep -m1 -iE 'graph|vga|display' |cut -f3 -d':' | tr -s '[[:blank:]]' | sed 's%^ *%%;s% *$%%;s%[^[:alnum:]]%_%g' | tr -s '[:punct:]'`
+[ "$PROFILECHIP" ] || PROFILECHIP=UnknownChip
 ## Dougal: maybe add "^monitorname: "??
 #PROFILEMONITOR=`grep -E -m1 '^monitorrange: |^monitorid: |^eisa: ' "$tmpDIR"/ddcprobe.txt | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`
 #v3.95 'eisa:' and 'id:' return fluctuating values on some PCs, so search in this order...
- PROFILEMONITOR=`grep -iE '^monitorid: |^Monitor name: ' "$tmpDIR"/ddcprobe.txt         | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`
- [ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^monitorname: ' "$tmpDIR"/ddcprobe.txt  | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`
- [ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^monitorrange: ' "$tmpDIR"/ddcprobe.txt | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`
-#[ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^dtiming: ' "$tmpDIR"/ddcprobe.txt      | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`
- [ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^manufacture: ' "$tmpDIR"/ddcprobe.txt  | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`
-#[ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^eisa: ' "$tmpDIR"/ddcprobe.txt         | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`
-
+ PROFILEMONITOR=`grep -iE '^monitorid: |^Monitor name: ' "$tmpDIR"/ddcprobe.txt         | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
+ [ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^monitorname: ' "$tmpDIR"/ddcprobe.txt  | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
+ [ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^monitorrange: ' "$tmpDIR"/ddcprobe.txt | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
+#[ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^dtiming: ' "$tmpDIR"/ddcprobe.txt      | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
+ [ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^manufacture: ' "$tmpDIR"/ddcprobe.txt  | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
+#[ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^eisa: ' "$tmpDIR"/ddcprobe.txt         | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
+ [ "$PROFILEMONITOR" ] || PROFILEMONITOR=UnknownMonitor
 KERNEL_RELEASE=`uname -r`
 V=`Xorg -version 2>&1|sed '/^$/d'`
 CV=`echo "$V" |sed 's|^|#|'`
@@ -1440,10 +1464,10 @@ echo "#PuppyHardwareProfile=${PROFILECHIP}-${PROFILEMONITOR}"
 ) >> "$XORGCONFFILE"
 #create a copy of xorg.conf with the profile in the filename...
 echo "Copyied $XORGCONFFILE $XORGCONFFILE.${PROFILECHIP}-${PROFILEMONITOR} :Step 12" >> "$tmpDIR"/xorgwizard.messages && sleep 1s #9s
-/bin/cp $VERB -a --remove-destination "$XORGCONFFILE" "$XORGCONFFILE".${PROFILECHIP}-${PROFILEMONITOR}
+/bin/cp $VERB -a --remove-destination "$XORGCONFFILE" "$XORGCONFFILE"."${PROFILECHIP}-${PROFILEMONITOR}"
 card0driver=`grep -m1 '#card0driver' "$XORGCONFFILE" | awk -F '"' '{print $2}'`
 [ "$card0driver" ] || card0driver=NONE
-/bin/cp $VERB -a --remove-destination "$XORGCONFFILE" "$XORGCONFFILE".${CARD0DRIVER}-${card0driver}-${PROFILECHIP}-${PROFILEMONITOR}
+/bin/cp $VERB -a --remove-destination "$XORGCONFFILE" "$XORGCONFFILE"."${CARD0DRIVER}-${card0driver}-${PROFILECHIP}-${PROFILEMONITOR}"
 
 #also write profile to the backup (used for tweaking vertrefresh)...
 (
@@ -2175,7 +2199,7 @@ if pidof Xorg >>$OUT; then
   fi
 
 else
- echo -e $Red1"Xorg may crashed. Check your configuration."$Res
+ echo -e $Red1"Xorg may crashed. Check your configuration."$Reset0
  sleep 3
 fi
 
@@ -2450,9 +2474,9 @@ called '\Z3vesa\Z4' (note, this is not the \Z1Xvesa X server\Z4!), that works wi
 most video hardware, but some performance may be lost.
 
 The current driver being used by
-Xorg is     '\Z5${CARD0DRIVER}\Z4', and your video
-vendor is:  '\Z0${CARD0VENDOR}\Z4'
-board info: '\Z5${CARD0BOARD}\Z4'
+Xorg is  '\Z5${CARD0DRIVER}\Z4', your card or monitor
+vendor:  '\Z0${CARD0VENDOR}\Z4', and the card or
+board :  '\Z5${CARD0BOARD}\Z4'
 
 So, if you have already tried '\Zbtweaking\ZB' or you know that the Xorg
 '\Z0${CARD0DRIVER}\Z4' driver does not work on your hardware, consider the
@@ -2466,6 +2490,8 @@ generic driver, otherwise press ahead and try tweaking...${ALTERNATIVE_DRV_MSG}\
   _debug "CARD0DRIVER='$CARD0DRIVER'"
   [ "$RV6" = '1' ] && SUBSTDRV='vesa'
   [ "$RV6" -eq 3 ] && SUBSTDRV="$TRYDRV" #w482 intel or i810
+  #wasCARD0DRIVER=$CARD0DRIVER
+  wasCARD0DRIVER=`grep -m1 '#card0driver' "$XORGCONFFILE" | cut -f2 -d'"'`
   CARD0DRIVER="$SUBSTDRV"
   _debug "SUBSTDRV='$SUBSTDRV'"
   _debug "CARD0DRIVER='$CARD0DRIVER'"
@@ -2486,7 +2512,7 @@ generic driver, otherwise press ahead and try tweaking...${ALTERNATIVE_DRV_MSG}\
    [ "$DEBUG" ] && less /etc/X11/xorg.conf
 
    CARD0DRIVER=$oldCARD0DRIVER
-   aPATTERN="s%.*#card0driver.*%\tDriver\t\t\"${CARD0DRIVER}\" #card0driver #set new%g"
+   aPATTERN="s%.*#card0driver.*%\tDriver\t\t\"${CARD0DRIVER}\" #card0driver #was $wasCARD0DRIVER%g"
    sed -e "$aPATTERN" "$XORGCONFFILE" > "$tmpDIR"/xorg.conf.tmp2
                    [ "$DEBUG" ] && less "$tmpDIR"/xorg.conf.tmp2
    _sync
