/usr/sbin/xorgwizard : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -185,7 +185,7 @@ CURRENTX=`readlink /usr/bin/X`
 CURRENTX=`basename "$CURRENTX"`
 if [ "$CURRENTX" = "" ];then #w007 fix if not a symlink.
  if test -x /usr/bin/Xorg; then
-  ln $VERB -sf /usr/bin/Xorg /usr/bin/X
+  ln $VERB -sf Xorg /usr/bin/X
   CURRENTX='Xorg'
  fi
 fi
@@ -694,7 +694,7 @@ Press TAB (or right-arrow) key then ENTER key for Xvesa...\Zn" 0 0
   fi
   #exec xwin
   #....Xvesa Wizard will run automatically if no /etc/videomode.
-  ln $VERB -sf /usr/bin/Xvesa /usr/bin/X #Xvesa is now the default X server.
+  ln $VERB -sf Xvesa /usr/bin/X #Xvesa is now the default X server.
   echo "linked X to Xvesa , type xwin to start graphics mode."
   exit 250 #w478
  fi
@@ -703,15 +703,15 @@ fi   #v3.99
 #resolution changer uses this. it must be removed here...
 echo "Removing '/etc/xrandrindex' ..."
 rm $VERB -f /etc/xrandrindex
-echo "Linking /usr/bin/Xorg /usr/bin/X ..."
-ln $VERB -sf /usr/bin/Xorg /usr/bin/X
+echo "Linking to Xorg from /usr/bin/X ..."
+ln $VERB -sf Xorg /usr/bin/X
 
 unset KEEP_XORG_CONF
 
 while :
 do
 
-if ! "$KEEP_XORG_CONF"; then
+if test ! "$KEEP_XORG_CONF"; then
 # Dougal: moved echo to below xorg probing, since loop isn't slow anymore...
 #clear
 echo -en "\\033[1;35m" #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
@@ -1619,17 +1619,17 @@ do
 #test "$f" = "${XORGCONFFILE}.d/Card0.conf" && continue
  test "$f" = "$tmpDIR/Card0.conf" && continue
 #sed -i 's%^[^#]%#%' "$f"
-sed -i 's%^\([^#].*\)%#\1%' "$f"
+sed -i'.sed' 's%^\([^#].*\)%#\1%' "$f"
 done
 #sed -i 's%^#*%%' "$XORGCONFFILE".d/Card0.conf
-sed -i 's%^#*%%' "$tmpDIR"/Card0.conf
+sed -i'.sed' 's%^#*%%' "$tmpDIR"/Card0.conf
 #p1=`grep -E 'Driver[[:blank:]]+".*"' "$XORGCONFFILE".d/Card0.conf`
 p1=`grep -E 'Driver[[:blank:]]+".*"' "$tmpDIR"/Card0.conf`
 p2=`echo "$p1" | sed -r 's%(^.*)("[^"]*")(.*$)%\(\1\)\(\2\)\(\3\)%'`
 _debug "'$p2'"
 # TODO: Worked OK until now, but may need similar in Device.conf
 #sed -i -r "s%$p2%\1\"$*\"\3%" "$XORGCONFFILE".d/Card0.conf
-sed -i -r "s%$p2%\1\"$*\"\3%" "$tmpDIR"/Card0.conf
+sed -i'.sed' -r "s%$p2%\1\"$*\"\3%" "$tmpDIR"/Card0.conf
 test $? = 0 && CARD0DRIVER="$*"
 grep -E 'Driver[[:blank:]]+".*"' "$tmpDIR"/Card0.conf
 sleep 4
@@ -1732,13 +1732,13 @@ unset SEC NEWSEC
  Subsection*|'#Subsection'*)
   HAVE_SUBSEC=1
   case $aLINE in
-  '# '*|'#	'*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
+  '#'[[:blank:]]*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
    *)         NEWSEC="$NEWSEC\n\t$aLINE";;
   esac
  ;;
  EndSubsection|'#EndSubsection')
  case $aLINE in
- '# '*|'#	'*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
+ '#'[[:blank:]]*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
  *)           NEWSEC="$NEWSEC\n\t$aLINE";;
  esac
  unset HAVE_SUBSEC
@@ -1746,12 +1746,12 @@ unset SEC NEWSEC
  *)
    if test "$HAVE_SUBSEC"; then
    case $aLINE in
-   '# '*|'#	'*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
+   '#'[[:blank:]]*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
    *)       NEWSEC="$NEWSEC\n\t\t$aLINE";;
    esac
    elif test "$NEWSEC"; then
    case $aLINE in
-   '# '*|'#	'*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
+   '#'[[:blank:]]*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
    *)         NEWSEC="$NEWSEC\n\t$aLINE";;
    esac
    else
@@ -1784,7 +1784,7 @@ unset NEWSEC CARD DRIVER
      NEWSEC="$NEWSEC\n$aLINE";;
    '#'*Driver*\"*\"*) DRIVER=`echo "$aLINE" | cut -f2 -d'"'`
      NEWSEC="$NEWSEC\n$aLINE";;
-   '# '*|'#	'*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
+   '#'[[:blank:]]*) NEWSEC="$NEWSEC\n$aLINE";; #TAB
     *Identifier*Card[0-9]*) CARD=`echo "$aLINE" | cut -f2 -d'"'`
      NEWSEC="$NEWSEC\n\t$aLINE";;
     *Driver*\"*\"*) DRIVER=`echo "$aLINE" | cut -f2 -d'"'`
@@ -1950,12 +1950,12 @@ echo "$OTHER_CARDS_CONF" ; }
 for f in $OTHER_CARDS_CONF
 do
 #sed -i 's%^%#%' "$f"
-sed -i 's%^\([^#].*\)%#\1%' "$f"
+sed -i'.sed' 's%^\([^#].*\)%#\1%' "$f"
 done
 #test -f "$CardFILE" || return 5
 test -s "$CardFILE" || return 6
 #need to reset CARD0DRIVER
-sed -i 's%^#*%%' "$CardFILE" || return 7
+sed -i'.sed' 's%^#*%%' "$CardFILE" || return 7
 cat "$CardFILE"
 echo
 grep -E 'Driver' "$CardFILE" || return 8
@@ -2057,7 +2057,7 @@ the 'Change_mouse' button now."
  --title "Xorg Graphics Wizard" --yesno "Okay, just about to take the plunge.
 ${MOUSEMSG}
 
-After choosing 'TEST_X_NOW' button, if the next screen shows a nice
+After choosing <TEST X NOW> button, if the next screen shows a nice
 dialog box, then X started okay. If the screen is blank or garbage,
 then failure (In such a case, just press the ENTER key to terminate
 the test, preferably within the 60 second test timeout).
@@ -2066,8 +2066,9 @@ IMPORTANT: If the ENTER key does not terminate the test, press the
 combination CTRL-ALT-BACKSPACE (some odd old PCs may even require
 you to press CTRL-ALT-BACKSPACE twice to terminate the test!)
 
-Press ENTER key now to start X graphics mode (may take a few secs)...
-TAB then ENTER to change the mouse (afterward will return here)..." 0 0
+Press ENTER key for testing X graphics mode (may take a few secs)...
+Press TAB and ENTER key to change the mouse (serial/ps2)
+(afterward will return here)..." 0 0
  DQ5=$?;[ "$DQ5" = "" -o "$DQ5" = 255 ] && exit 250
  if [ ! "$DQ5" -eq 0 ];then
   #change the mouse... (then go back up to above dialog)
@@ -2079,8 +2080,9 @@ TAB then ENTER to change the mouse (afterward will return here)..." 0 0
  fi
 
  #w460 test Xorg...
- ( timeout -k 3 7 /usr/bin/Xorg -ignoreABI -config "$XORGCONFFILE" -logfile "$tmpDIR"/Xorg_xinitrc_test.log :0 ) &
- cc=0
+ #( timeout -k 3 7 /usr/bin/Xorg -ignoreABI -config "$XORGCONFFILE" -logfile "$tmpDIR"/Xorg_xinitrc_test.log :0 ) &
+  ( timeout -t7 /usr/bin/Xorg -ignoreABI -config "$XORGCONFFILE" -logfile "$tmpDIR"/Xorg_xinitrc_test.log :0 ) &    #busybox timeout syntax
+cc=0
  sleep 1
  while :; do
  pidof Xorg >>$OUT || break
@@ -2205,7 +2207,16 @@ ${INTELDRVMSG}" 0 0
   #CARD0DRIVER="$SUBSTDRV"
   if [ "$RET2" -ne 0 ];then
    CARD0DRIVER="$SUBSTDRV"
-   aPATTERN="s/.*#card0driver/  Driver      \"${SUBSTDRV}\" #card0driver/"
+   #aPATTERN="s/.*#card0driver/  Driver      \"${SUBSTDRV}\" #card0driver/"
+   whereLINE=`grep -E '#card[0-9]+driver' "$XORGCONFFILE" | grep -v '^[[:blank:]]*#' | head -n1`
+   if test "$whereLINE"; then
+    MARKER=`echo "$whereLINE" | awk '{print $3}'`
+    DRIVER=`echo "$whereLINE" | awk '{print $2}'`
+    aPATTERN="s/.*${MARKER}/\tDriver\t\t\"${SUBSTDRV}\"\t${MARKER}/"
+   else
+    echo 'ERROR: Getting real cardNdriver failed. Falling back to #card0driver'
+    aPATTERN="s/.*#card0driver/\tDriver\t\t\"${SUBSTDRV}\"\t#card0driver/"
+   fi
    sed -e "$aPATTERN" "$XORGCONFFILE" > "$tmpDIR"/xorg.conf.tmp2
    _sync
    cp $VERB -f "$tmpDIR"/xorg.conf.tmp2 "$XORGCONFFILE"
@@ -2338,6 +2349,10 @@ Press ENTER key to edit xorg.conf..." 0 0
   #edit xorg.conf...
   test -f "$XORGCONFFILE" || _exit 99 "No regular $XORGCONFFILE file"
   mp "$XORGCONFFILE"
+  oldCARD0DRIVER=$CARD0DRIVER
+  newCARD0DRIVER=`grep -E '#card[0-9]+driver' "$XORGCONFFILE" | grep -v '^[[:blank:]]*#' | head -n1`
+  CARD0DRIVER=`echo "$newCARD0DRIVER" | cut -f2 -d'"'`
+  test "$CARD0DRIVER" || CARD0DRIVER=CODE_ERROR
   KEEP_XORG_CONF=1
  fi
 sleep 1
@@ -2361,7 +2376,7 @@ graphics server that runs on most graphic chips." 0 0
   DQ9=$?;[ "$DQ9" = 0 -o "$DQ9" = 1 ] || exit 250
   if [ "$DQ9" -eq 0 ];then
    echo "Linked X to Xvesa"
-   ln $VERB -sf /usr/bin/Xvesa /usr/bin/X
+   ln $VERB -sf Xvesa /usr/bin/X
   else
    #prevent Xvesa video wizard from running after X has started...
    echo "Removed "$tmpDIR"/videomode"
@@ -2377,14 +2392,17 @@ fi
 #mv -f /root/xorg.conf.new $tmpDIR/xorg.conf.new
 cp $VERB -f /root/xorg.conf.new "$tmpDIR"/xorg.conf.new
 
-if [ "$XORGTEST" = 3 ];then #<FIX> (XTEST=0 is <OK> button)
+#if [ "$XORGTEST" = 3 ];then #<FIX> (XTEST=0 is <OK> button)
  #need to do this here again in case of tweaking made some changes...
  #create a copy of xorg.conf with the profile in the filename...
  cp $VERB -af "$XORGCONFFILE" "$XORGCONFFILE".${PROFILECHIP}-${PROFILEMONITOR}
  cp $VERB -af "$XORGCONFFILE" "$XORGCONFFILE".${PROFILECHIP}-${PROFILEMONITOR}-${CARD0DRIVER}
+ if test "$oldCARD0DRIVER"; then
+ cp $VERB -af "$XORGCONFFILE" "$XORGCONFFILE".${PROFILECHIP}-${PROFILEMONITOR}-${oldCARD0DRIVER}-${CARD0DRIVER}
+ fi
  #clear
  echo "Xorg Graphics Wizard completed. Type 'xwin' to start X..."
-else
+#else
  #clear
  #user chose the <OK> button, so going directly into X without testing.
  echo -en "\\033[1;31m" #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
@@ -2394,7 +2412,7 @@ else
  echo "Graphics Wizard from within X (in the Setup menu) -- module 'Xvidtune'"
  echo -n "may be used, with caution, to finetune the display dimensions."
  echo -e "\\033[0;39m"
-fi
+#fi
 
 exit $?
 ###END###
