/usr/sbin/xorgwizard: Minor clean-ups.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -352,7 +352,7 @@ Press TAB (or right-arrow) key then ENTER key for Xvesa...\Zn" 0 0
      #if [ -f /etc/X11/xorg.conf.bak ];then  ##5
       #basic test to see that file has right stuff in it...
       #if [ -z "`grep -F 'VertRefresh' /etc/X11/xorg.conf`" ] ;then  ##6
-       #echo "xorgwizard message : cp -f .bak xorg.conf "`date` >> /etc/X11/xorgmessgs.txt
+       #echo "xorgwizard message : cp -f .bak xorg.conf "`date` >>/etc/X11/xorgmessgs.txt
        #cp -f /etc/X11/xorg.conf.bak /etc/X11/xorg.conf
       #fi  ##6
      #fi  ##5
@@ -626,7 +626,7 @@ echo -en "\\033[1;35m" #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aqua
 echo -n "Probing video hardware, please wait..."
 echo -e "\\033[0;39m"
 #autoprobe...
-Xorg -configure > /tmp/xorgprobe.txt 2>&1
+Xorg -configure >/tmp/xorgprobe.txt 2>&1
 #... config in /root/xorg.conf.new
 
 
@@ -759,7 +759,7 @@ EndSection"
  done <<_END2
 $(echo "$aSECTION" | tr '%' '\n')
 _END2
-echo -e "$TEMPSECTION" >> /etc/X11/xorg.conf
+echo -e "$TEMPSECTION" >>/etc/X11/xorg.conf
 sync
 done <<_END1
 $(cat /root/xorg.conf.new | tr '\n' '%' | sed 's/EndSection/EndSection\n/g' )
@@ -795,7 +795,7 @@ XVESALISTOK="yes"
 TIMINGOK="yes"
 if [ -s /tmp/ddcprobeoem.txt ];then   #v3.99 begin
  if [ ! -f /etc/xorgoverrides ] || ! grep -f /tmp/ddcprobeoem.txt /etc/xorgoverrides;then
-  echo "`cat /tmp/ddcprobeoem.txt`" >> /etc/xorgoverrides  #append new signature if user canceled out from hung Xvesa
+  echo "`cat /tmp/ddcprobeoem.txt`" >>/etc/xorgoverrides  #append new signature if user canceled out from hung Xvesa
   sync
  fi
 fi
@@ -804,12 +804,12 @@ if [ -f /etc/xorgoverrides ] && grep -f /etc/xorgoverrides /tmp/ddcprobe.txt;the
  #VERTREFRESH=""
  XVESALISTOK="no" #'Xvesa -listmodes' hangs.
  TIMINGOK="no"    #ddcprobe returns incomplete 'timing:' info (res's missing).
- [ "`grep 'mode: 640x480x64k' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 640x480x64k' >> /tmp/ddcprobe.txt
- [ "`grep 'mode: 640x480x16m' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 640x480x16m' >> /tmp/ddcprobe.txt
- [ "`grep 'mode: 800x600x64k' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 800x600x64k' >> /tmp/ddcprobe.txt
- [ "`grep 'mode: 800x600x16m' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 800x600x16m' >> /tmp/ddcprobe.txt
- [ "`grep 'mode: 1024x768x64k' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 1024x768x64k' >> /tmp/ddcprobe.txt
- [ "`grep 'mode: 1024x768x16m' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 1024x768x16m' >> /tmp/ddcprobe.txt
+ [ "`grep 'mode: 640x480x64k' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 640x480x64k' >>/tmp/ddcprobe.txt
+ [ "`grep 'mode: 640x480x16m' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 640x480x16m' >>/tmp/ddcprobe.txt
+ [ "`grep 'mode: 800x600x64k' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 800x600x64k' >>/tmp/ddcprobe.txt
+ [ "`grep 'mode: 800x600x16m' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 800x600x16m' >>/tmp/ddcprobe.txt
+ [ "`grep 'mode: 1024x768x64k' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 1024x768x64k' >>/tmp/ddcprobe.txt
+ [ "`grep 'mode: 1024x768x16m' /tmp/ddcprobe.txt`" = "" ] && echo 'mode: 1024x768x16m' >>/tmp/ddcprobe.txt
 fi   #v3.93 end
 
 #v3.94 detect if a Classmate PC laptop with 800x480 screen...
@@ -818,29 +818,29 @@ fi   #v3.93 end
 #  if [ "`dmesg | grep 'CPU0: Intel(R) Celeron(R) M processor          900MHz'`" != "" ];then
 #   if [ "`dmesg | grep 'uDiskOnChip'`" != "" ];then
 #    #yep, looks like this is a Classmate model with 800x480...
-#    echo 'timing: 800x480@60' >> /tmp/ddcprobe.txt
+#    echo 'timing: 800x480@60' >>/tmp/ddcprobe.txt
 #   fi
 #  fi
 # fi
 #fi
 #v3.97 improved method: CM=Classmate, 915=chip 10=generation#...
-[ "`dmidecode -s bios-version | grep '^CM91510'`" != "" ] && echo 'timing: 800x480@60' >> /tmp/ddcprobe.txt
+[ "`dmidecode -s bios-version | grep '^CM91510'`" != "" ] && echo 'timing: 800x480@60' >>/tmp/ddcprobe.txt
 #v3.95 recognise more special screens...
 DMIDECODE="`dmidecode`"
 #recognise EeePC Asus laptop...
-[ "`echo "$DMIDECODE" | grep 'Product Name: 701'`" != "" ] && [ "`echo "$DMIDECODE" | grep 'Serial Number: EeePC'`" != "" ] && echo 'timing: 800x480@60' >> /tmp/ddcprobe.txt
+[ "`echo "$DMIDECODE" | grep 'Product Name: 701'`" != "" ] && [ "`echo "$DMIDECODE" | grep 'Serial Number: EeePC'`" != "" ] && echo 'timing: 800x480@60' >>/tmp/ddcprobe.txt
 
 
 #modes supported by card...
 CARDCHOICES=""
 if [ -e /usr/bin/Xvesa -a "$XVESALISTOK" = "yes" ];then #format of each line: 1024x768x16
  echo -e '\nIf initialization freezes here, press ctrl-c and type "xorgwizard",\nselect "Xorg", choose monitor type and choose video mode.'   #v3.99
- grep '^oem:' /tmp/ddcprobe.txt > /tmp/ddcprobeoem.txt   #v3.99 current adapter signature
- Xvesa -listmodes 2>&1 | cut -f 2 -d ' ' | grep -E 'x16$|x24$' | sort -t x -n > /tmp/Xmodes.txt
+ grep '^oem:' /tmp/ddcprobe.txt >/tmp/ddcprobeoem.txt   #v3.99 current adapter signature
+ Xvesa -listmodes 2>&1 | cut -f 2 -d ' ' | grep -E 'x16$|x24$' | sort -t x -n >/tmp/Xmodes.txt
  rm /tmp/ddcprobeoem.txt  #v3.99 didn't hang in Xvesa, so delete signature
 else
  #the vesa 'mode:' lines returned by ddcprobe are very limited...
- grep '^mode:' /tmp/ddcprobe.txt | grep -E 'x64k|x16m'| cut -f 2 -d ' ' | sed -e 's/x64k/x16/g ; s/x16m/x24/g' > /tmp/Xmodes.txt
+ grep '^mode:' /tmp/ddcprobe.txt | grep -E 'x64k|x16m'| cut -f 2 -d ' ' | sed -e 's/x64k/x16/g ; s/x16m/x24/g' >/tmp/Xmodes.txt
 fi
 sync
 CARDCHOICES="`cat /tmp/Xmodes.txt`"
@@ -1089,20 +1089,20 @@ fi
 while [ 1 ];do #more-monchoices-loop
  #if have MONCHOICES, that's all i want to display (with warning if not in card list).
  #if no MONCHOICES, then display card list only...
- echo -n "" > /tmp/finalchoices.txt
+ echo -n "" >/tmp/finalchoices.txt
  if [ "$MONCHOICES" = "" ];then
   for oneCHOICE in $CARDCHOICES
   do
    if [ "$RECMODE" = "$oneCHOICE" ];then
-    echo "$oneCHOICE \"Unconfirmed MAXIMUM for monitor, OK for card\" \\" >> /tmp/finalchoices.txt
+    echo "$oneCHOICE \"Unconfirmed MAXIMUM for monitor, OK for card\" \\" >>/tmp/finalchoices.txt
    else
-    echo "$oneCHOICE \"Unconfirmed for monitor, OK for video card\" \\" >> /tmp/finalchoices.txt
+    echo "$oneCHOICE \"Unconfirmed for monitor, OK for video card\" \\" >>/tmp/finalchoices.txt
    fi
   done
   for oneCHOICE in 640x480x16 800x600x16 1024x600x16 1024x768x16 1280x800x16 1280x1024x16 1360x768x16 1400x1050x16 1440x900x16 1600x1200x16 1680x1050x16 1920x1080x16 1920x1200x16 640x480x24 800x600x24 1024x600x24 1024x768x24 1280x800x24 1280x1024x24 1360x768x24 1400x1050x24 1440x900x24 1600x1200x24 1680x1050x24 1920x1080x24 1920x1200x24
   do
    case "$CARDCHOICES" in *$oneCHOICE*) ;; *) # we've done CARDCHOICES above
-    echo "$oneCHOICE \"Unconfirmed for monitor, maybe NOT OK for card\" \\" >> /tmp/finalchoices.txt ;;
+    echo "$oneCHOICE \"Unconfirmed for monitor, maybe NOT OK for card\" \\" >>/tmp/finalchoices.txt ;;
    esac
   done
  else
@@ -1117,8 +1117,8 @@ while [ 1 ];do #more-monchoices-loop
    for oneCHOICE in ${oneCUTXY}x16 ${oneCUTXY}x24
    do
     case "$CARDCHOICES" in
-     *$oneCHOICE*) echo "$oneCHOICE \"OK for monitor, OK for video card\" \\" >> /tmp/finalchoices.txt ;;
-     *) echo "$oneCHOICE \"OK for monitor, maybe NOT OK for card\" \\" >> /tmp/finalchoices.txt ;;
+     *$oneCHOICE*) echo "$oneCHOICE \"OK for monitor, OK for video card\" \\" >>/tmp/finalchoices.txt ;;
+     *) echo "$oneCHOICE \"OK for monitor, maybe NOT OK for card\" \\" >>/tmp/finalchoices.txt ;;
     esac
    done
   done
@@ -1128,44 +1128,44 @@ while [ 1 ];do #more-monchoices-loop
  FINALCHOICES="`cat /tmp/finalchoices.txt | sort -t x -n`" #v3.93 rerwin
 
  if [ "$MONCHOICES" = "" ];then #100406
-  echo '#!/bin/sh' > /tmp/choosexmodedlg
-  echo -n "dialog --colors --extra-button --aspect 11 --default-item $RECMODE" >> /tmp/choosexmodedlg
+  echo '#!/bin/sh' >/tmp/choosexmodedlg
+  echo -n "dialog --colors --extra-button --aspect 11 --default-item $RECMODE" >>/tmp/choosexmodedlg
   echo ' --no-collapse --title "Puppy Video Wizard" --ok-label "OK" --extra-label "TEST" --cancel-label "EXIT" --menu "Please use the UP/DOWN ARROW keys to select a video mode. Choices are
 shown in the format WidthxHeightxBits, where Width and Height are
 screen resolution in pixels, 16/24 bits = 65,536/16,777,216 colors.
-' >> /tmp/choosexmodedlg
-  [ ! "$RECMODE" = "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >> /tmp/choosexmodedlg
-  echo '\Z1RECOMMENDATION: Choose <TEST> button to verify it works!\Z0' >> /tmp/choosexmodedlg
+' >>/tmp/choosexmodedlg
+  [ ! "$RECMODE" = "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >>/tmp/choosexmodedlg
+  echo '\Z1RECOMMENDATION: Choose <TEST> button to verify it works!\Z0' >>/tmp/choosexmodedlg
   echo '
 OK:     Just press ENTER key to immediately use the selected mode...
 TEST: TAB key then ENTER to test and debug the mode before using it...
-EXIT: Exit to text-mode console, do not start X...\Zn" 0 0 0 \' >> /tmp/choosexmodedlg #'geanyfix.
-  echo "$FINALCHOICES" >> /tmp/choosexmodedlg
-  echo ' 2>/tmp/tag.txt' >> /tmp/choosexmodedlg
-  echo 'exit $?' >> /tmp/choosexmodedlg
+EXIT: Exit to text-mode console, do not start X...\Zn" 0 0 0 \' >>/tmp/choosexmodedlg #'geanyfix.
+  echo "$FINALCHOICES" >>/tmp/choosexmodedlg
+  echo ' 2>/tmp/tag.txt' >>/tmp/choosexmodedlg
+  echo 'exit $?' >>/tmp/choosexmodedlg
   chmod 755 /tmp/choosexmodedlg
   /tmp/choosexmodedlg
   XAUTO=$? #=0 for automatic.
   [ $XAUTO -ne 0 ] && [ $XAUTO -ne 3 ] && exit #drop out to console.
  else
   #offer more resolutions if MONCHOICES inadequate...
-  echo '#!/bin/sh' > /tmp/choosexmodedlg
-  echo -n "dialog --colors --extra-button --aspect 11 --default-item $RECMODE" >> /tmp/choosexmodedlg
+  echo '#!/bin/sh' >/tmp/choosexmodedlg
+  echo -n "dialog --colors --extra-button --aspect 11 --default-item $RECMODE" >>/tmp/choosexmodedlg
   echo ' --no-collapse --title "Puppy Video Wizard" --ok-label "OK" --extra-label "TEST" --cancel-label "MORE" --menu "Please use the UP/DOWN ARROW keys to select a video mode. Choices are
 shown in the format WidthxHeightxBits, where Width and Height are
 screen resolution in pixels, 16/24 bits = 65,536/16,777,216 colors.
-' >> /tmp/choosexmodedlg
-  [ "$RECMODE" != "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >> /tmp/choosexmodedlg
-  echo '\Z1RECOMMENDATION: Choose <TEST> button to verify it works!\Z0' >> /tmp/choosexmodedlg
+' >>/tmp/choosexmodedlg
+  [ "$RECMODE" != "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >>/tmp/choosexmodedlg
+  echo '\Z1RECOMMENDATION: Choose <TEST> button to verify it works!\Z0' >>/tmp/choosexmodedlg
   echo '
-NOTICE: If auto-probe has not detected a resolution that you know your monitor supports, click the <MORE> button to display more resolutions to choose from...' >> /tmp/choosexmodedlg
+NOTICE: If auto-probe has not detected a resolution that you know your monitor supports, click the <MORE> button to display more resolutions to choose from...' >>/tmp/choosexmodedlg
   echo '
 OK:     Just press ENTER key to immediately use the selected mode...
 TEST: TAB key then ENTER to test and debug the mode before using it...
-MORE: Display more monitor resolutions to choose from...\Zn" 0 0 0 \' >> /tmp/choosexmodedlg #'geanyfix.
-  echo "$FINALCHOICES" >> /tmp/choosexmodedlg
-  echo ' 2>/tmp/tag.txt' >> /tmp/choosexmodedlg
-  echo 'exit $?' >> /tmp/choosexmodedlg
+MORE: Display more monitor resolutions to choose from...\Zn" 0 0 0 \' >>/tmp/choosexmodedlg #'geanyfix.
+  echo "$FINALCHOICES" >>/tmp/choosexmodedlg
+  echo ' 2>/tmp/tag.txt' >>/tmp/choosexmodedlg
+  echo 'exit $?' >>/tmp/choosexmodedlg
   chmod 755 /tmp/choosexmodedlg
   /tmp/choosexmodedlg
   XAUTO=$? #=0 for automatic.
@@ -1244,7 +1244,7 @@ Section \"Screen\"
 EndSection
 "
 done
-echo "$SCRNSECTION" >> /etc/X11/xorg.conf
+echo "$SCRNSECTION" >>/etc/X11/xorg.conf
 
 PREFERREDMODE=$FINALXY   #v3.98 rerwin - set monitor preferred mode same as screen mode.
 #horiz and vert sync ranges and preferred mode were found earlier but not written... v3.98
@@ -1253,7 +1253,7 @@ cp -f /etc/X11/xorg.conf /tmp/xorg.conf.tmp
 sed -e "s/HORIZSYNC0/$HORIZSYNC/g ; s/VERTREFRESH0/$VERTREFRESH/g ; s/PREFERREDMODE0/$PREFERREDMODE/g" /tmp/xorg.conf.tmp >/etc/X11/xorg.conf   #v3.98 rerwin - added update of preferredmode.
 #BPATTERN="s/VERTREFRESH0/$VERTREFRESH/g"
 sync
-#cat /tmp/xorg.conf.tmp2 | sed -e "$BPATTERN" > /etc/X11/xorg.conf
+#cat /tmp/xorg.conf.tmp2 | sed -e "$BPATTERN" >/etc/X11/xorg.conf
 #sync
 #rm -f /tmp/xorg.conf.tmp2
 
@@ -1263,7 +1263,7 @@ if grep -F -q 'Elantech' /proc/bus/input/devices ; then
  cp /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic
  modprobe evdev
  if [ "`grep '^modprobe evdev' /etc/rc.d/rc.local`" = "" ];then #v2.17
-  echo "modprobe evdev" >> /etc/rc.d/rc.local
+  echo "modprobe evdev" >>/etc/rc.d/rc.local
  fi
  # Where we want to insert new lines...
  OLD1='Section "Module"'
@@ -1311,7 +1311,7 @@ if grep -F -q 'Alps' /proc/bus/input/devices ; then
  cp /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic
  modprobe evdev
  if [ "`grep '^modprobe evdev' /etc/rc.d/rc.local`" = "" ];then #v2.17
-  echo "modprobe evdev" >> /etc/rc.d/rc.local
+  echo "modprobe evdev" >>/etc/rc.d/rc.local
  fi
  # Where we want to insert new lines...
  OLD1='Section "Module"'
@@ -1359,7 +1359,7 @@ fi
 if grep -F -q 'Synaptics' /proc/bus/input/devices ; then
  cp /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic
  modprobe evdev
- echo "modprobe evdev" >> /etc/rc.d/rc.local
+ echo "modprobe evdev" >>/etc/rc.d/rc.local
  # Where we want to insert new lines...
  OLD1='Section "Module"'
  OLD2='Section "ServerLayout"'
@@ -1421,11 +1421,11 @@ PROFILEMONITOR="`grep '^monitorid: ' /tmp/ddcprobe.txt | head -n 1 | cut -f 2 -d
 #[ "$PROFILEMONITOR" = "" ] && PROFILEMONITOR="`grep '^manufacture: ' /tmp/ddcprobe.txt | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
 #[ "$PROFILEMONITOR" = "" ] && PROFILEMONITOR="`grep '^eisa: ' /tmp/ddcprobe.txt | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
 
-echo "#PuppyHardwareProfile=${PROFILECHIP}${PROFILEMONITOR}" >> /etc/X11/xorg.conf
+echo "#PuppyHardwareProfile=${PROFILECHIP}${PROFILEMONITOR}" >>/etc/X11/xorg.conf
 #create a copy of xorg.conf with the profile in the filename...
 cp -af /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}${PROFILEMONITOR}
 #also write profile to the backup (used for tweaking vertrefresh)...
-echo "#PuppyHardwareProfile=${PROFILECHIP}${PROFILEMONITOR}" >> /tmp/xorg.conf.tmp
+echo "#PuppyHardwareProfile=${PROFILECHIP}${PROFILEMONITOR}" >>/tmp/xorg.conf.tmp
 
 #v2.12
 #note, this code will have to go into 'xwin' also.
@@ -1444,7 +1444,7 @@ if grep -F 'oem:' /tmp/ddcprobe.txt | grep -F -q 'Intel' ;then
   915resolution 38 $MYXRES $MYYRES
   #...replaces mode 38 (1024x768).
   #create something for xwin to eecute...
-  echo "915resolution 38 $MYXRES $MYYRES" > /etc/resolutionfix
+  echo "915resolution 38 $MYXRES $MYYRES" >/etc/resolutionfix
  fi
 else
  #in case plug usb or multisession-cd into different pc...
@@ -1670,7 +1670,7 @@ generic driver, otherwise press ahead and try tweaking...${EXTRADRVMSG}" 0 0
    #EndSection
 
    aPATTERN="s/.*#card0driver/  Driver      \"${SUBSTDRV}\" #card0driver/"
-   sed -e "$aPATTERN" /etc/X11/xorg.conf > /tmp/xorg.conf.tmp2
+   sed -e "$aPATTERN" /etc/X11/xorg.conf >/tmp/xorg.conf.tmp2
    sync
    cp -f /tmp/xorg.conf.tmp2 /etc/X11/xorg.conf
    CARD0DRIVER="$SUBSTDRV" #100109
@@ -1819,10 +1819,10 @@ $MSGPNP" 0 0 0 \
     aPATTERN="s/HORIZSYNC0/${MINHORIZ}\\-${NEEDHORIZ}/g"
    fi
   fi
-  sed -e "$aPATTERN" /tmp/xorg.conf.tmp > /tmp/xorg.conf.tmp2
+  sed -e "$aPATTERN" /tmp/xorg.conf.tmp >/tmp/xorg.conf.tmp2
   bPATTERN="s/VERTREFRESH0/${MINVERT}\\-${CHOSENVERT}/g"
   sync
-  sed -e "$bPATTERN" /tmp/xorg.conf.tmp2 > /etc/X11/xorg.conf
+  sed -e "$bPATTERN" /tmp/xorg.conf.tmp2 >/etc/X11/xorg.conf
   sync
 
   #100430 nvidia driver needs to set metamodes entry in Screen section...
