xorgwizard : Code clean up.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -104,10 +104,10 @@ tmpDir='/tmp/xorgwizard';mkdir -p "$tmpDir"
 echo "
 `date`" >>"$tmpDir"/xorgwizard.messages
 
-[ "`tty`" = "not a tty" -o "`tty`" = '?' ] && { sleep 2s;chvt 1; }
+[ "`tty`" = "not a tty" -o "`tty`" = '?' ] && { sleep 2s; chvt 1; }
 
 ##+++2012-01-30
-if [ "`whoami`" = 'root' ];then
+if [ "`whoami`" = 'root' ]; then
 XORGCONFFILE=/etc/X11/xorg.conf
 else
 XORGCONFFILE=xorg.conf
@@ -121,7 +121,7 @@ alias modprobe='modprobe -b' #+++2012-02-03
 
 PSFND=`ps`
 CURRENTX=`readlink /usr/bin/X`
-if [ "$CURRENTX" = "" ];then #w007 fix if not a symlink.
+if [ "$CURRENTX" = "" ]; then #w007 fix if not a symlink.
  ln -snf Xorg /usr/bin/X
  CURRENTX='Xorg'
 fi
@@ -251,7 +251,7 @@ to modify the existing file.\"</label></text>
 
 
 #do this code block if X is running...
-if [ ! "`echo -n "$PSFND" | grep "\\.xinitrc"`" = "" ];then
+if [ "`echo -n "$PSFND" | grep "\\.xinitrc"`" != "" ]; then
 
  RETSTR=`echo "$MAIN1" | gtkdialog2 --stdin`
  RETVAL=`echo "$RETSTR" | grep 'EXIT:' | cut -f 2 -d ':'`
@@ -289,7 +289,7 @@ that changing the settings will cause no change on the screen." &
    XMSGPID=$!
    MODELINE0=`xvidtune | grep '^"[0-9]'`  ##"'geany
    kill $XMSGPID
-   if [ ! "$MODELINE0" = "" ];then
+   if [ "$MODELINE0" != "" ]; then
     xmessage -bg orange -title "Xvidtune: Modeline" -buttons Write:10,Quit:11 "The new modeline is:
 $MODELINE0
 
@@ -299,7 +299,7 @@ the 'UseModes' line (do not delete it) in the Monitor section.
 
 To insert this into /etc/X11/xorg.conf, click 'Write' button...
 To exit without changing xorg.conf, click 'Quit' button..."
-    if [ $? -eq 10 ];then
+    if [ $? -eq 10 ]; then
      PATTERNA="s/.*#modes0modeline0/ ModeLine $MODELINE0 #modes0modeline0/g"
      cat /etc/X11/xorg.conf | sed -e "$PATTERNA" > "$tmpDir"/xorg.conf.new
      sync
@@ -330,7 +330,7 @@ fi
 
 #v3.99 begin
 #If video adapter would hang Xvesa, tell user and allow only Xorg.
-if [ -s "$tmpDir"/ddcprobeoem.txt ] || grep -q -f /etc/xorgoverrides "$tmpDir"/ddcprobe.txt 2>$ERR;then   #Xvesa hanger encountered
+if [ -s "$tmpDir"/ddcprobeoem.txt ] || grep -q -f /etc/xorgoverrides "$tmpDir"/ddcprobe.txt 2>$ERR; then   #Xvesa hanger encountered
  dialog --colors --title "Puppy Video Wizard" --yes-label "Xorg" --no-label "Commandline" --yesno "Welcome to the Puppy Video Wizard!
 
 Puppy has two X servers (to run Puppy in graphics mode):
@@ -371,10 +371,10 @@ Press TAB (or right-arrow) key then ENTER key for Xvesa...\Zn" 0 0
  if [ "$STATUS" -eq 1 ];then   #v3.99 Xvesa selected
   ln -sf Xvesa /usr/bin/X #Xvesa becomming now the default X server ..
   #when start xorgwizard from commandline, it messes up xorg.conf...
-  if [ -f /etc/X11/xorg.conf ];then
-   if [ -f /etc/X11/xorg.conf.bak ];then
+  if [ -f /etc/X11/xorg.conf ]; then
+   if [ -f /etc/X11/xorg.conf.bak ]; then
     #basic test to see that file has right stuff in it...
-    if [ -z "`grep -F 'VertRefresh' /etc/X11/xorg.conf | grep -v '^[[:blank:]]*#'`" ] ;then
+    if [ -z "`grep -F 'VertRefresh' /etc/X11/xorg.conf | grep -v '^[[:blank:]]*#'`" ]; then
      echo "Not found VertRefresh in xorg.conf.
  Copying /etc/X11/xorg.conf.bak /etc/X11/xorg.conf 4" >> "$tmpDir"/xorgwizard.messages && sleep 2s #9s #DBG
      cp -f /etc/X11/xorg.conf.bak /etc/X11/xorg.conf
@@ -389,7 +389,7 @@ Press TAB (or right-arrow) key then ENTER key for Xvesa...\Zn" 0 0
 fi   #v3.99
 
 ###completely rebuild xorg.conf...
-if [ -f /etc/X11/xorg.conf ];then
+if [ -f /etc/X11/xorg.conf ]; then
 # echo
 # echo "/etc/X11/xorg.conf exists. XorgWizard rebuilds it from scratch."
 # echo -e "Hit ENTER key to quit, or type \"y\" then ENTER keys to rename"
@@ -461,7 +461,7 @@ do
  #  Tabs at beginning of lines are lost when reading, so I add them
  #+ where appropriate (i.e. before every line except for Section borders).
  #+ ("\n"=newline ; "\t"=tab)
- IDENTIFIER="" ; XSECTION="" ; TEMPSECTION=""
+ IDENTIFIER=""; XSECTION=""; TEMPSECTION=""
 
  while read ALINE
  do
@@ -530,7 +530,7 @@ $ALINE
     ;;
 
 
-   Section?\"*) XSECTION=${ALINE%\"*} ; XSECTION=${XSECTION##*\"}
+   Section?\"*) XSECTION=${ALINE%\"*}; XSECTION=${XSECTION##*\"}
     TEMPSECTION="\n$ALINE"
     continue # just added line -- no need to get to bottom
     ;;
@@ -549,13 +549,13 @@ $ALINE
     esac
     ;;
 
-   *Identifier*) IDENTIFIER=${ALINE%\"*} ; IDENTIFIER=${IDENTIFIER##*\"}
+   *Identifier*) IDENTIFIER=${ALINE%\"*}; IDENTIFIER=${IDENTIFIER##*\"}
     ;;
    *\"ZAxisMapping\"*) continue
     ;;
-   *HorizSync*[0-9]*) set -- $ALINE ; HORIZSYNC0="$2$3$4" ; continue
+   *HorizSync*[0-9]*) set -- $ALINE; HORIZSYNC0="$2$3$4"; continue
     ;;
-   *VertRefresh*[0-9]*) set -- $ALINE ; VERTREFRESH0="$2$3$4" ; continue
+   *VertRefresh*[0-9]*) set -- $ALINE; VERTREFRESH0="$2$3$4"; continue
     ;;
 
    *Option*\"Protocol\"?\"auto\"*)
@@ -584,7 +584,7 @@ $ALINE
     TEMPSECTION="$TEMPSECTION
 \t${BLA}Option\t\"Emulate3Buttons\"
 \t${BLA}Option\t\"Emulate3Timeout\" \"50\""
-    if [ "`cat /etc/mousebuttons`" = "5" ] ; then #scrollwheel
+    if [ "`cat /etc/mousebuttons`" = "5" ]; then #scrollwheel
      BLA=""
     else
      BLA="#"
@@ -598,12 +598,12 @@ $ALINE
  if [ "$XSECTION" = "Device" ]; then
   case $IDENTIFIER in
   Card0)
-   FBODY=${ALINE%\"*} ; FBODY=${FBODY##*\"}
+   FBODY=${ALINE%\"*}; FBODY=${FBODY##*\"}
     case "$ALINE" in
-        *Driver*) CARD0DRIVER="$FBODY" ; ALINE="$ALINE #card0driver" ;;
+        *Driver*) CARD0DRIVER="$FBODY"; ALINE="$ALINE #card0driver" ;;
         *VendorName*) CARD0VENDOR="$FBODY" ;;
         *BoardName*) CARD0BOARD="$FBODY"
-        if [ "$CARD0BOARD" = 'Unknown Board' ];then
+        if [ "$CARD0BOARD" = 'Unknown Board' ]; then
         CARD0BOARD="lscpi: `lspci | grep 'VGA compatible controller' |rev|cut -f1 -d: |rev`"
         fi
         ;;
@@ -695,13 +695,13 @@ get_edid_func
 #v3.98 added more CYBER lines & corrected case
 XVESALISTOK="yes"
 TIMINGOK="yes"
-if [ -s "$tmpDir"/ddcprobeoem.txt ];then   #v3.99 begin
- if [ ! -f /etc/xorgoverrides ] || ! grep -q -f "$tmpDir"/ddcprobeoem.txt /etc/xorgoverrides;then
+if [ -s "$tmpDir"/ddcprobeoem.txt ]; then   #v3.99 begin
+ if [ ! -f /etc/xorgoverrides ] || ! grep -q -f "$tmpDir"/ddcprobeoem.txt /etc/xorgoverrides; then
   echo "`cat "$tmpDir"/ddcprobeoem.txt`" >> /etc/xorgoverrides  #append new signature if user canceled out from hung Xvesa
   sync
  fi
 fi
-if [ -f /etc/xorgoverrides ] && grep -q -f /etc/xorgoverrides "$tmpDir"/ddcprobe.txt;then   #v3.99 end
+if [ -f /etc/xorgoverrides ] && grep -q -f /etc/xorgoverrides "$tmpDir"/ddcprobe.txt; then   #v3.99 end
  #HORIZSYNC=""
  #VERTREFRESH=""
  XVESALISTOK="no" #'Xvesa -listmodes' hangs.
@@ -803,10 +803,10 @@ fi
 
 #ddcprobe on my laptop returns one 'timing:' line but no 'monitorrange:', so
 #can fall back to calculating freqs...
-if [ ! "$MONCHOICES" = "" ];then
+if [ "$MONCHOICES" != "" ]; then
  ##hmmm, maybe always use the freqs of the 'timing:' lines rather than the
  ##'monitorrange:' as it always seems to be too high...
- if [ "$HORIZSYNC" = "" -o "$VERTREFRESH" = "" ];then
+ if [ "$HORIZSYNC" = "" -o "$VERTREFRESH" = "" ]; then
   UHORIZSYNC=32    #start with mediocre values.
   UVERTREFRESH=60  # /
   LHORIZSYNC=30    # /
@@ -815,7 +815,7 @@ if [ ! "$MONCHOICES" = "" ];then
   do
    ONEVERT=${ONECH#*@}
    ONEX=${ONECH%x*}
-   ONEY=${ONECH#*x} ; ONEY=${ONEY%@*}
+   ONEY=${ONECH#*x}; ONEY=${ONEY%@*}
    ONEHORIZ=`gtf $ONEX $ONEY $ONEVERT | grep -o 'hsync:.*' | cut -f 2 -d ' ' | cut -f 1 -d '.'`
    [ $ONEVERT -lt $LVERTREFRESH ] && LVERTREFRESH=$ONEVERT
    [ $ONEHORIZ -gt $UHORIZSYNC ] && UHORIZSYNC=$ONEHORIZ
@@ -1031,7 +1031,7 @@ echo ' --no-collapse --title "Puppy Video Wizard" --ok-label "OK" --extra-label 
 shown in the format WidthxHeightxBits, where Width and Height are
 screen resolution in pixels, 16/24 bits = 65,536/16,777,216 colors.
 ' >> "$tmpDir"/choosexmodedlg
-[ ! "$RECMODE" = "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >> "$tmpDir"/choosexmodedlg
+[ "$RECMODE" != "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >> "$tmpDir"/choosexmodedlg
 echo '\Z1RECOMMENDATION: Choose <TEST> button to verify it works!\Z0' >> "$tmpDir"/choosexmodedlg
 echo '
 OK:     Just press ENTER key to immediately use the selected mode...
@@ -1072,18 +1072,18 @@ FINALXY=${CHOSENRES%x*}
 ##  Dougal: note that old code (line below) didn't work in my case: 50.0-160.0
 ##+ seems like the ".0" gave it problems, so ended up with MAXVERT=""
 #MAXVERT=`echo -n "$VERTREFRESH" | grep -o '[ -,][0-9]*$' | sed -e 's/^[ -,]//g'`
-MAXVERT=${VERTREFRESH#*-} ; MAXVERT=${MAXVERT%.*}
-if [ $MAXVERT -gt 85 ];then
+MAXVERT=${VERTREFRESH#*-}; MAXVERT=${MAXVERT%.*}
+if [ $MAXVERT -gt 85 ]; then
  #VPATTERN="s/${MAXVERT}$/85/g"
  #VERTREFRESH=`echo -n "$VERTREFRESH" | sed -e "$VPATTERN"`
  echo "MAXVERT='$MAXVERT' gt 85 , setting it to 85" >> "$tmpDir"/xorgwizard.messages
  VERTREFRESH=${VERTREFRESH/$MAXVERT/85}
 else
  #want to cut down rating on modern LCD panels also...
- if [ $MAXVERT -gt 74 ] && [ $MAXVERT -lt 86 ];then
+ if [ $MAXVERT -gt 74 ] && [ $MAXVERT -lt 86 ]; then
    #and if manufactured in 2004 or later...
    #(so older CRTs in this range maxvert 75-85 will get rejected)
-   if grep '^manufacture: ' "$tmpDir"/ddcprobe.txt | grep -E ' 20[1-9][0-9]| 200[4-9]' ;then
+   if grep '^manufacture: ' "$tmpDir"/ddcprobe.txt | grep -E ' 20[1-9][0-9]| 200[4-9]'; then
     let LCDMAXVERT=MAXVERT-4
     #VPATTERN="s/${MAXVERT}$/${LCDMAXVERT}/g"
     #VERTREFRESH=`echo -n "$VERTREFRESH" | sed -e "$VPATTERN"`
@@ -1132,11 +1132,11 @@ sync
 
 ## Dougal (v2.16??):
 ## Kirk's code for adding synaptics touchpads (or my version of it...)
-if grep -F -q 'Alps' /proc/bus/input/devices ; then
+if grep -F -q 'Alps' /proc/bus/input/devices; then
 echo "Copied /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic 9" >> "$tmpDir"/xorgwizard.messages && sleep 2s #9s
  cp /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic
  modprobe evdev
- if [ "`grep '^modprobe evdev' /etc/rc.d/rc.local`" = "" ];then #v2.17
+ if [ "`grep '^modprobe evdev' /etc/rc.d/rc.local`" = "" ]; then #v2.17
   echo "modprobe evdev" >> /etc/rc.d/rc.local
  fi
  # Where we want to insert new lines...
@@ -1184,7 +1184,7 @@ Section "Monitor"'
  sed "s%$OLD1%$NEW1%; s%$OLD2%$NEW2%; s%$OLD3%$NEW3%" /etc/X11/xorg.conf-without-synaptic >/etc/X11/xorg.conf
 fi
 
-if grep -F -q 'Synaptics' /proc/bus/input/devices ; then
+if grep -F -q 'Synaptics' /proc/bus/input/devices; then
  echo "Copying etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic 11" >> "$tmpDir"/xorgwizard.messages && sleep 2s #9s
  cp /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic
  modprobe evdev
@@ -1311,11 +1311,11 @@ PROFILEMONITOR=`grep '^monitorid: ' $tmpDir/ddcprobe.txt | head -n 1 | cut -f 2 
 
 
 
-KERNVERS=`uname -r`
+KERNEL_RELEASE=`uname -r`
 V=`Xorg -version 2>&1|sed '/^$/d'`
 CV=`echo "$V" |sed 's|^|#|'`
 version=`echo "$V" |head -n2 |grep -E -i -o 'date.*|version.*' | tr '\n' ' '`
-echo "#Linux Kernel : $KERNVERS" >> /etc/X11/xorg.conf
+echo "#Linux Kernel : $KERNEL_RELEASE" >> /etc/X11/xorg.conf
 echo "#Xorg Server Version :" >> /etc/X11/xorg.conf
 echo "$CV" >> /etc/X11/xorg.conf
 echo "#PuppyHardwareProfile=${PROFILECHIP}-${PROFILEMONITOR}" >> /etc/X11/xorg.conf
@@ -1336,14 +1336,14 @@ echo "#PuppyHardwareProfile=${PROFILECHIP}-${PROFILEMONITOR}" >> "$tmpDir"/xorg.
 #video bios may not offer the chosen resolution if it is widescreen.
 #for intel video there is a way to patch the video bios, but this
 #has to be run at every boot...
-if grep -F 'oem:' "$tmpDir"/ddcprobe.txt | grep -F -q 'Intel' ;then
+if grep -F 'oem:' "$tmpDir"/ddcprobe.txt | grep -F -q 'Intel'; then
  #MYXYRES=`echo -n "$CHOSENRES" | cut -f 1-2 -d 'x'`
  MYXYRES=${CHOSENRES%x*}
- if ! grep -q "$MYXYRES" "$tmpDir"/Xmodes.txt ;then
+ if ! grep -q "$MYXYRES" "$tmpDir"/Xmodes.txt; then
   #MYXRES=`echo -n "$CHOSENRES" | cut -f 1 -d 'x'`
   #MYYRES=`echo -n "$CHOSENRES" | cut -f 2 -d 'x'`
   MYXRES=${CHOSENRES%%x*}
-  MYYRES=${CHOSENRES%x*} ; MYYRES=${MYYRES#*x}
+  MYYRES=${CHOSENRES%x*}; MYYRES=${MYYRES#*x}
   #this is an app that patches video-bios, but in ram only...
   915resolution 38 $MYXRES $MYYRES
   #...replaces mode 38 (1024x768).
@@ -1355,7 +1355,7 @@ else
  [ -f /etc/resolutionfix ] && rm -f /etc/resolutionfix
 fi
 
-[ "$XAUTO" -ne 0 -a "$XAUTO" -ne 3 ] && { echo "XAUTO='$XAUTO' ,so exit";exit $?; } #drop out to console.
+[ "$XAUTO" -ne 0 -a "$XAUTO" -ne 3 ] && { echo "XAUTO='$XAUTO' ,exiting."; exit $?; } #drop out to console.
 
 #code here to test the video...
 CHOSENVERT=""
@@ -1596,7 +1596,7 @@ elif [ "`grep -i 'INTEL' /etc/X11/xorg.conf |grep -E 'Driver|VendorName|BoardNam
  echo
  echo "I810OLD='$I810OLD'"
 
- if [ "$I810OLD" != "" ];then
+ if [ "$I810OLD" != "" ]; then
   if [ "${CARD0DRIVER}" = "intel" ];then
    TRYDRV='i810'
    EXTRABUTTON='--extra-button'
@@ -1647,7 +1647,7 @@ generic driver, otherwise press ahead and try tweaking...${ALTERNATIVE_DRV_MSG}\
   [ "$RV6" -eq 3 ] && SUBSTDRV="$TRYDRV" #w482 intel or i810
   CARD0DRIVER="$SUBSTDRV"
   if [ "$RV6" -ne 0 ];then
-   APATTERN="s/.*#card0driver/  Driver      \"${CARD0DRIVER}\" #card0driver/g"
+   APATTERN="s/.*#card0driver/\tDriver\t\"${CARD0DRIVER}\" #card0driver/g"
    sed -e "$APATTERN" /etc/X11/xorg.conf > "$tmpDir"/xorg.conf.tmp2
    sync
    echo "Copying $tmpDir/xorg.conf.tmp2 /etc/X11/xorg.conf 13" >> "$tmpDir"/xorgwizard.messages && sleep 2s #9s
@@ -1674,9 +1674,9 @@ to open xorg.conf in a text editor and change whatever you wish.
 
 Press \Z0ENTER\Z4 key for the easy option to tweak refresh frequency...
 Press TAB then \Z1E\Z0\ZbNTER\ZB\Z4 to open xorg.conf in a text editor...\Zn" 0 0
- RV7="$?";[ "$RV7" != '0' -a "$RV7" != '1' ] && break
- if [ "$RV7" -eq 0 ];then
-  if [ "$MONCHOICES" = "" ];then
+ RV7="$?"; [ "$RV7" != '0' -a "$RV7" != '1' ] && break
+ if [ "$RV7" -eq 0 ]; then
+  if [ "$MONCHOICES" = "" ]; then
    #not plug-n-play.
    MSGPNP="\Z1WARNING\Z0: Your monitor is not plug-and-play so this Wizard cannot
          determine its max allowable refresh frequency. A very cheap old
@@ -1709,7 +1709,7 @@ $MSGPNP" 0 0 0 \
  "$VERT4" "$MSGV4" \
  "$VERT5" "$MSGV5" \
  2>"$tmpDir"/tagvert.txt
- RV8="$?";[ "$RV8" = '-1' -o "$RV8" = '255' ] && break
+ RV8="$?"; [ "$RV8" = '-1' -o "$RV8" = '255' ] && break
   #FUTURE: use xrandr above, to determine alternative lower frequencies.
 
   CHOSENVERT=`cat "$tmpDir"/tagvert.txt 2>$ERR | tail -n1`
@@ -1734,8 +1734,8 @@ $MSGPNP" 0 0 0 \
 
 /etx/X11/xorg.conf has these lines in the Monitor section :
 
-  \Z5HorizSync    $HORIZSYNC\Z0
-  VertRefresh  $VERTREFRESH
+  \Z5HorizSync    '$HORIZSYNC'\Z0
+  VertRefresh    '$VERTREFRESH'
 
 \Z4For the resolution that you want to run at, you many want to narrow
 -down the specs in xorg.conf . For example, say you want 1024x768@85,
@@ -1759,7 +1759,7 @@ If you cannot get Xorg to work, press TAB then ENTER to choose
 the \"\Z1X\Z0\Zbvesa\ZB\Z4\" button.
 This will start Puppy with the simple driverless \Z1Xvesa graphics server\Z4
 that runs on most (old) video hardware.\Zn" 0 0
- RV9="$?";[ "$RV9" != '0' -a "$RV9" != '1' ] && exit
+ RV9="$?"; [ "$RV9" != '0' -a "$RV9" != '1' ] && exit
   if [ ! "$RV9" -eq 0 ];then
   echo "Linked 'Xvesa' towards '/usr/bin/X'"
    ln -sf Xvesa /usr/bin/X
@@ -1777,7 +1777,7 @@ fi
 #mv -f /root/xorg.conf.new "$tmpDir"/xorg.conf.new
 cp -a /root/xorg.conf.new "$tmpDir"/xorg.conf.new
 
-if [ $XAUTO -ne 0 ];then #<FIX> (XAUTO=0 is <OK> button)
+if [ $XAUTO -ne 0 ]; then #<FIX> (XAUTO=0 is <OK> button)
  #need to do this here again in case of tweaking made some changes...
  #create a copy of xorg.conf with the profile in the filename...
  echo "Copyied /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}-${PROFILEMONITOR} 15" >> "$tmpDir"/xorgwizard.messages && sleep 2s #9s
