woof-code/rootfs-skeleton/usr/sbin/xorgwizard: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -48,6 +48,29 @@
 #100820 Xvesa present, improve dialogs if choose Xorg.
 #100820 for intel video, mplayer needs 'Option "LinearAlloc" "6144"' in xorg.conf.
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 # redirect errors to file (to help debug):
 exec 2>/tmp/xorgwizard-errors.log
 
@@ -626,20 +649,20 @@ do
    EndSection*)
     if [ "$XSECTION" = "InputDevice" -a "$IDENTIFIER" = "Keyboard0" ] ; then
      TEMPSECTION="$TEMPSECTION
-	Option      \"XkbRules\" \"xorg\"
-	Option      \"XkbModel\" \"pc102\"
-	Option      \"XkbLayout\" \"$XKEYMAP\" #xkeymap0"
+        Option      \"XkbRules\" \"xorg\"
+        Option      \"XkbModel\" \"pc102\"
+        Option      \"XkbLayout\" \"$XKEYMAP\" #xkeymap0"
     elif [ "$XSECTION" = "Monitor" -a "$IDENTIFIER" = "Monitor0" ] ; then
      TEMPSECTION="$TEMPSECTION
-	HorizSync    HORIZSYNC0
-	VertRefresh  VERTREFRESH0
-	#UseModes     \"Modes0\" #monitor0usemodes
-	Option      \"PreferredMode\" \"PREFERREDMODE0\"
-	$ALINE
+        HorizSync    HORIZSYNC0
+        VertRefresh  VERTREFRESH0
+        #UseModes     \"Modes0\" #monitor0usemodes
+        Option      \"PreferredMode\" \"PREFERREDMODE0\"
+        $ALINE
 
 Section \"Modes\"
-	Identifier \"Modes0\"
-	#modes0modeline0
+        Identifier \"Modes0\"
+        #modes0modeline0
 EndSection"
      #v3.98 rerwin - added preferredmode line, after usemodes line.
      continue # we added the line before the "Modes" section, so continue
@@ -662,36 +685,36 @@ EndSection"
    *Option*\"Protocol\"?\"auto\"*)
     case "`cat /etc/mousedevice 2>/dev/null`" in
      input/mice) TEMPSECTION="$TEMPSECTION
-	Option	    \"Protocol\" \"IMPS/2\" #mouse0protocol"
-	  continue
-	  ;;
+        Option      \"Protocol\" \"IMPS/2\" #mouse0protocol"
+          continue
+          ;;
      *ttyS*) TEMPSECTION="$TEMPSECTION
-	Option	    \"Protocol\" \"Microsoft\" #mouse0protocol"
-	  continue
-	  ;;
+        Option      \"Protocol\" \"Microsoft\" #mouse0protocol"
+          continue
+          ;;
      *) TEMPSECTION="$TEMPSECTION
-	Option	    \"Protocol\" \"auto\" #mouse0protocol"
-	  continue
-	  ;;
+        Option      \"Protocol\" \"auto\" #mouse0protocol"
+          continue
+          ;;
     esac
     ;;
    */dev/mouse*|*/dev/input/mice*) #v2.21
     TEMPSECTION="$TEMPSECTION\n\t$ALINE"
     case "`cat /etc/xextraoptions`" in
      *2button*) BLA="" ;;
-	 *) BLA="#" ;;
-	esac
-	TEMPSECTION="$TEMPSECTION
-	${BLA}Option      \"Emulate3Buttons\"
-	${BLA}Option      \"Emulate3Timeout\" \"50\""
-	if [ "`cat /etc/mousebuttons`" = "5" ] ; then #scrollwheel
-	 BLA=""
-	else
-	 BLA="#"
-	fi
+         *) BLA="#" ;;
+        esac
+        TEMPSECTION="$TEMPSECTION
+        ${BLA}Option      \"Emulate3Buttons\"
+        ${BLA}Option      \"Emulate3Timeout\" \"50\""
+        if [ "`cat /etc/mousebuttons`" = "5" ] ; then #scrollwheel
+         BLA=""
+        else
+         BLA="#"
+        fi
     TEMPSECTION="$TEMPSECTION
-	${BLA}Option      \"ZAxisMapping\" \"4 5\" #scrollwheel"
-	continue # we added the line at the beginning
+        ${BLA}Option      \"ZAxisMapping\" \"4 5\" #scrollwheel"
+        continue # we added the line at the beginning
     ;;
   esac
 
@@ -927,97 +950,97 @@ if [ "$HORIZSYNC" = "" -o "$VERTREFRESH" = "" ];then #"" if monitor not plug-n-p
   ## Dougal: use case-structure for setting params -- safer than the old way
   ## (not sure why Barry only uses 16-bit, maybe worth improving?)
   case "$CHOICE" in
-   A) # "h31.5v40-70		LCD Panel 640x480"
+   A) # "h31.5v40-70            LCD Panel 640x480"
      RECMODE="640x480x16"
      HORIZSYNC="31.5"
      VERTREFRESH="40-70"
      ;;
-   B) # "h31.5-37v40-70		LCD Panel 800x600"
+   B) # "h31.5-37v40-70         LCD Panel 800x600"
      RECMODE="800x600x16"
      HORIZSYNC="31.5-37"
      VERTREFRESH="40-70"
      ;;
-   B2) # "h31.5-90v60		LCD Panel 1024x600"
+   B2) # "h31.5-90v60           LCD Panel 1024x600"
      RECMODE="1024x600x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="60"
      ;;
-   C) # "h31.5-48.5v40-70	LCD Panel 1024x768"
+   C) # "h31.5-48.5v40-70       LCD Panel 1024x768"
      RECMODE="1024x768x16"
      HORIZSYNC="31.5-48.5"
      VERTREFRESH="40-70"
      ;;
-   D) # "h31.5-90v60		LCD Panel 1280x800"
+   D) # "h31.5-90v60            LCD Panel 1280x800"
      RECMODE="1280x800x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="60"
      ;;
-   E) # "h31.5-67v50-75		LCD Panel 1280x1024"
+   E) # "h31.5-67v50-75         LCD Panel 1280x1024"
      RECMODE="1280x1024x16"
      HORIZSYNC="31.5-67"
      VERTREFRESH="50-75"
      ;;
-   F) # "h31.5-90v60		LCD Panel 1360x768"
+   F) # "h31.5-90v60            LCD Panel 1360x768"
      RECMODE="1360x768x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="60"
      ;;
-   G) # "h31.5-90v59-75		LCD Panel 1400x1050"
+   G) # "h31.5-90v59-75         LCD Panel 1400x1050"
      RECMODE="1400x1050x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="59-75"
      ;;
-   H) # "h31.5-100v59-75	LCD Panel 1440x900"
+   H) # "h31.5-100v59-75        LCD Panel 1440x900"
      RECMODE="1440x900x16"
      HORIZSYNC="31.5-100"
      VERTREFRESH="59-75"
      ;;
-   I) # "h31.5-90v60		LCD Panel 1600x1200"
+   I) # "h31.5-90v60            LCD Panel 1600x1200"
      RECMODE="1600x1200x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="60"
      ;;
-   J) # "h31.5-90v60		LCD Panel 1680x1050"
+   J) # "h31.5-90v60            LCD Panel 1680x1050"
      RECMODE="1680x1050x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="60"
      ;;
-   K) # "h30-68v67		LCD HDTV  1920x1080"
+   K) # "h30-68v67              LCD HDTV  1920x1080"
      RECMODE="1920x1080x16"
      HORIZSYNC="30-68"
      VERTREFRESH="67"
      ;;
-   L) # "h31.5-90v60		LCD Panel 1920x1200"
+   L) # "h31.5-90v60            LCD Panel 1920x1200"
      RECMODE="1920x1200x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="60"
      ;;
-   M) # "h31.5v50-61		CRT 640x480"
+   M) # "h31.5v50-61            CRT 640x480"
      RECMODE="640x480x16"
      HORIZSYNC="31.5"
      VERTREFRESH="50-61"
      ;;
-   N) # "h31.5-35v50-61		CRT 800x600 (old 14inch monitor)"
+   N) # "h31.5-35v50-61         CRT 800x600 (old 14inch monitor)"
      RECMODE="800x600x16"
      HORIZSYNC="31.5-35"
      VERTREFRESH="50-61"
      ;;
-   O) # "h31.5-48.5v56-72	CRT 1024x768 (basic 15inch monitor)"
+   O) # "h31.5-48.5v56-72       CRT 1024x768 (basic 15inch monitor)"
      RECMODE="1024x768x16"
      HORIZSYNC="31.5-48.5"
      VERTREFRESH="56-72"
      ;;
-   P) # "h31.5-79v50-90		CRT 1280x1024 (basic 17inch monitor)"
+   P) # "h31.5-79v50-90         CRT 1280x1024 (basic 17inch monitor)"
      RECMODE="1280x1024x16"
      HORIZSYNC="31.5-79"
      VERTREFRESH="50-90"
      ;;
-   Q) # "h31.5-90v50-90		CRT 1400x1050"
+   Q) # "h31.5-90v50-90         CRT 1400x1050"
      RECMODE="1400x1050x16"
      HORIZSYNC="31.5-90"
      VERTREFRESH="50-90"
      ;;
-   R) # "h31.5-94v50-90		CRT 1600x1200"
+   R) # "h31.5-94v50-90         CRT 1600x1200"
      RECMODE="1600x1200x16"
      HORIZSYNC="31.5-94"
      VERTREFRESH="50-90"
@@ -1186,15 +1209,15 @@ SCRNSECTION=""
 for i in $SCREEN_LIST; do
 SCRNSECTION="$SCRNSECTION
 Section \"Screen\"
-	Identifier \"Screen$i\"
-	Device     \"Card$i\"
-	Monitor    \"Monitor$i\"
-	DefaultDepth $FINALDEPTH
-	#Option         \"metamodes\" \"${FINALXY}_60 +0+0\" #METAMODES_${i}
-	Subsection \"Display\"
-		Depth       $FINALDEPTH
-		Modes       \"${FINALXY}\"
-	EndSubsection
+        Identifier \"Screen$i\"
+        Device     \"Card$i\"
+        Monitor    \"Monitor$i\"
+        DefaultDepth $FINALDEPTH
+        #Option         \"metamodes\" \"${FINALXY}_60 +0+0\" #METAMODES_${i}
+        Subsection \"Display\"
+                Depth       $FINALDEPTH
+                Modes       \"${FINALXY}\"
+        EndSubsection
 EndSection
 "
 done
@@ -1226,16 +1249,16 @@ if grep -F -q 'Elantech' /proc/bus/input/devices ; then
 
  # ...and the replacements
  NEW1='Section "Module"\
-	Load "synaptics"'
+        Load "synaptics"'
 
  NEW2='Section "ServerLayout"\
-	InputDevice "Synaptics Mouse" "AlwaysCore"'
+        InputDevice "Synaptics Mouse" "AlwaysCore"'
 
  NEW3='Section "InputDevice"\
-	Identifier "Synaptics Mouse"\
-	Driver "synaptics"\
-	Option "Device" "/dev/psaux"\
-	Option "Protocol" "auto-dev"\
+        Identifier "Synaptics Mouse"\
+        Driver "synaptics"\
+        Option "Device" "/dev/psaux"\
+        Option "Protocol" "auto-dev"\
         Option "LeftEdge" "60"\
         Option "RightEdge" "1070"\
         Option "TopEdge" "90"\
@@ -1274,34 +1297,34 @@ if grep -F -q 'Alps' /proc/bus/input/devices ; then
 
  # ...and the replacements
  NEW1='Section "Module"\
-	Load "synaptics"'
+        Load "synaptics"'
 
  NEW2='Section "ServerLayout"\
-	InputDevice "Synaptics Mouse" "AlwaysCore"'
+        InputDevice "Synaptics Mouse" "AlwaysCore"'
 
  NEW3='Section "InputDevice"\
-	Identifier "Synaptics Mouse"\
-	Driver "synaptics"\
-	Option "Device" "/dev/psaux"\
-	Option "Protocol" "auto-dev"\
-	Option "LeftEdge" "120"\
-	Option "RightEdge" "930"\
-	Option "TopEdge" "120"\
-	Option "BottomEdge" "650"\
-	Option "FingerLow" "14"\
-	Option "FingerHigh" "15"\
-	Option "MaxTapTime" "0"\
-	Option "MaxTapMove" "110"\
-	Option "VertScrollDelta" "20"\
-	Option "MinSpeed" "0.3"\
-	Option "MaxSpeed" "0.75"\
-	Option "AccelFactor" "0.030"\
-	Option "EdgeMotionMinSpeed" "200"\
-	Option "EdgeMotionMaxSpeed" "200"\
-	Option "UpDownScrolling" "1"\
-	Option "CircularScrolling" "1"\
-	Option "CircScrollDelta" "0.1"\
-	Option "CircScrollTrigger" "2"\
+        Identifier "Synaptics Mouse"\
+        Driver "synaptics"\
+        Option "Device" "/dev/psaux"\
+        Option "Protocol" "auto-dev"\
+        Option "LeftEdge" "120"\
+        Option "RightEdge" "930"\
+        Option "TopEdge" "120"\
+        Option "BottomEdge" "650"\
+        Option "FingerLow" "14"\
+        Option "FingerHigh" "15"\
+        Option "MaxTapTime" "0"\
+        Option "MaxTapMove" "110"\
+        Option "VertScrollDelta" "20"\
+        Option "MinSpeed" "0.3"\
+        Option "MaxSpeed" "0.75"\
+        Option "AccelFactor" "0.030"\
+        Option "EdgeMotionMinSpeed" "200"\
+        Option "EdgeMotionMaxSpeed" "200"\
+        Option "UpDownScrolling" "1"\
+        Option "CircularScrolling" "1"\
+        Option "CircScrollDelta" "0.1"\
+        Option "CircScrollTrigger" "2"\
 EndSection\
 \
 Section "Monitor"'
@@ -1321,30 +1344,30 @@ if grep -F -q 'Synaptics' /proc/bus/input/devices ; then
 
  # ...and the replacements
  NEW1='Section "Module"\
-	Load "synaptics"'
+        Load "synaptics"'
 
  NEW2='Section "ServerLayout"\
-	InputDevice "Synaptics Mouse" "AlwaysCore"'
+        InputDevice "Synaptics Mouse" "AlwaysCore"'
 
  NEW3='Section "InputDevice"\
-	Identifier "Synaptics Mouse"\
-	Driver "synaptics"\
-	Option "Device" "/dev/psaux"\
-	Option "Protocol" "auto-dev"\
-	Option "LeftEdge" "1700"\
-	Option "RightEdge" "5300"\
-	Option "TopEdge" "1700"\
-	Option "BottomEdge" "4200"\
-	Option "FingerLow" "25"\
-	Option "FingerHigh" "30"\
-	Option "MaxTapTime" "0"\
-	Option "MaxTapMove" "220"\
-	Option "VertScrollDelta" "100"\
-	Option "MinSpeed" "0.10"\
-	Option "MaxSpeed" "0.30"\
-	Option "AccelFactor" "0.0030"\
-	Option "SHMConfig" "on"\
-	#Option "Repeater" "/dev/ps2mouse"\
+        Identifier "Synaptics Mouse"\
+        Driver "synaptics"\
+        Option "Device" "/dev/psaux"\
+        Option "Protocol" "auto-dev"\
+        Option "LeftEdge" "1700"\
+        Option "RightEdge" "5300"\
+        Option "TopEdge" "1700"\
+        Option "BottomEdge" "4200"\
+        Option "FingerLow" "25"\
+        Option "FingerHigh" "30"\
+        Option "MaxTapTime" "0"\
+        Option "MaxTapMove" "220"\
+        Option "VertScrollDelta" "100"\
+        Option "MinSpeed" "0.10"\
+        Option "MaxSpeed" "0.30"\
+        Option "AccelFactor" "0.0030"\
+        Option "SHMConfig" "on"\
+        #Option "Repeater" "/dev/ps2mouse"\
 EndSection\
 \
 Section "Monitor"'
@@ -1456,9 +1479,9 @@ TAB then ENTER to change the mouse (afterward will return here)..." 0 0
  #w460 test Xorg...
  export MONCHOICES
  xinit /usr/sbin/xinitrc_test -- /usr/bin/Xorg :0
- 
+
  less /var/log/Xorg.0.log
- 
+
  eval "`cat /tmp/xorgwizard_initrc_test_results`" #results from xinitrc_test
 #...XTEST, YTEST, HSTEST, VRTEST.
 
@@ -1608,22 +1631,22 @@ generic driver, otherwise press ahead and try tweaking...${EXTRADRVMSG}" 0 0
 
    #this is what a 'vesa' section in xorg.conf looks like:
    #Section "Device"
-   #	### Available Driver options are:-
-   #	### Values: <i>: integer, <f>: float, <bool>: "True"/"False",
-   #	### <string>: "String", <freq>: "<f> Hz/kHz/MHz"
-   #	### [arg]: arg optional
-   #	#Option     "ShadowFB"           	# [<bool>]
-   #	#Option     "DefaultRefresh"     	# [<bool>]
-   #	#Option     "ModeSetClearScreen" 	# [<bool>]
-   #	#Option     "NoDDC"              	# [<bool>]
-   #	Identifier  "Card0"
-   #	Driver      "vesa" #card0driver
-   #	VendorName  "Unknown Vendor"
-   #	BoardName   "Unknown Board"
-   #	BusID       "PCI:0:2:0"
+   #    ### Available Driver options are:-
+   #    ### Values: <i>: integer, <f>: float, <bool>: "True"/"False",
+   #    ### <string>: "String", <freq>: "<f> Hz/kHz/MHz"
+   #    ### [arg]: arg optional
+   #    #Option     "ShadowFB"                  # [<bool>]
+   #    #Option     "DefaultRefresh"            # [<bool>]
+   #    #Option     "ModeSetClearScreen"        # [<bool>]
+   #    #Option     "NoDDC"                     # [<bool>]
+   #    Identifier  "Card0"
+   #    Driver      "vesa" #card0driver
+   #    VendorName  "Unknown Vendor"
+   #    BoardName   "Unknown Board"
+   #    BusID       "PCI:0:2:0"
    #EndSection
 
-   APATTERN="s/.*#card0driver/	Driver      \"${SUBSTDRV}\" #card0driver/"
+   APATTERN="s/.*#card0driver/  Driver      \"${SUBSTDRV}\" #card0driver/"
    sed -e "$APATTERN" /etc/X11/xorg.conf > /tmp/xorg.conf.tmp2
    sync
    cp -f /tmp/xorg.conf.tmp2 /etc/X11/xorg.conf
@@ -1780,7 +1803,7 @@ $MSGPNP" 0 0 0 \
   sync
 
   #100430 nvidia driver needs to set metamodes entry in Screen section...
-  #	#Option         \"metamodes\" \"${FINALXY}_60 +0+0\" #METAMODES_${i}
+  #     #Option         \"metamodes\" \"${FINALXY}_60 +0+0\" #METAMODES_${i}
   mmPATTERN="s%.* #METAMODES%    Option         \"metamodes\" \"${XTEST}x${YTEST}_${CHOSENVERT} +0+0\" #METAMODES%"
   mm2PATTERN="s%.* #METAMODES%    #Option         \"metamodes\" \"${XTEST}x${YTEST}_${VRTEST} +0+0\" #METAMODES%"
   if [ "`grep 'Driver' /etc/X11/xorg.conf | grep '"nvidia"'`" != "" ];then
