xwin,xinitrc_test,xorgwizard : Few minor bugfixes for these latest commits.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -101,7 +101,7 @@ exec 2>>"$TMP_DIR"/xorgwizard-errors.log
 PSFND=`ps`
 CURRENTX=`readlink /usr/bin/X`
 if [ ! "$CURRENTX" ];then #w007 fix if not a symlink.
- which Xorg || { echo 'Warning: No Xorg server installed !'
+ which Xorg || { echo 'Warning: No Xorg server installed !'; }
  ln -snf Xorg /usr/bin/X
  CURRENTX=Xorg
 fi
@@ -357,8 +357,8 @@ Press TAB (or right-arrow) key then ENTER key for Xvesa...\Zn" 0 0
    if [ -f /etc/X11/xorg.conf.bak ];then
     #basic test to see that file has right stuff in it...
     if [ -z "`grep -F 'VertRefresh' /etc/X11/xorg.conf | grep -v '^[[:blank:]]*#'`" ] ;then
-     echo "Not found VertRefresh in xorg.conf.
- Copying /etc/X11/xorg.conf.bak /etc/X11/xorg.conf 4" >> "$TMP_DIR"/xorgwizard.messages && sleep 2s #9s #DBG
+     echo "Not found VertRefresh in xorg.conf , so
+copying /etc/X11/xorg.conf.bak /etc/X11/xorg.conf 4" >> "$TMP_DIR"/xorgwizard.messages && sleep 2s #9s #DBG
      cp -f /etc/X11/xorg.conf.bak /etc/X11/xorg.conf
     fi
    fi
@@ -397,9 +397,9 @@ ln -sf Xorg /usr/bin/X
 
 # Dougal: moved echo to below xorg probing, since loop isn't slow anymore...
 ##clear
-echo -en "\\033[1;35m" #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
+echo -en '\033[1;35m' #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
 echo -n "Probing video hardware, please wait..."
-echo -e "\\033[0;39m"
+echo -e '\033[0;39m'
 
 #need to create xorg.conf so that at subsequent boots, xwin will not run xorgwizard...
 echo "Copying /etc/X11/xorg.conf0 /etc/X11/xorg.conf 3" >> "$TMP_DIR"/xorgwizard.messages && sleep 2s #9s
@@ -1271,7 +1271,7 @@ PROFILEMONITOR=`grep '^monitorid: ' $TMP_DIR/ddcprobe.txt | head -n 1 | cut -f 2
 
 echo "#PuppyHardwareProfile=${PROFILECHIP}-${PROFILEMONITOR}" >> /etc/X11/xorg.conf
 #create a copy of xorg.conf with the profile in the filename...
-echo "Copyied /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}${PROFILEMONITOR} 12" >> "$TMP_DIR"/xorgwizard.messages && sleep 2s #9s
+echo "Copyied /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}-${PROFILEMONITOR} 12" >> "$TMP_DIR"/xorgwizard.messages && sleep 2s #9s
 cp -af /etc/X11/xorg.conf /etc/X11/"xorg.conf.${PROFILECHIP}-${PROFILEMONITOR}"
 #also write profile to the backup (used for tweaking vertrefresh)...
 echo "#PuppyHardwareProfile=${PROFILECHIP}-${PROFILEMONITOR}" >> "$TMP_DIR"/xorg.conf.tmp
@@ -1609,8 +1609,8 @@ mv -f /root/xorg.conf.new "$TMP_DIR"/xorg.conf.new
 if [ $XAUTO -ne 0 ];then #<FIX> (XAUTO=0 is <OK> button)
  #need to do this here again in case of tweaking made some changes...
  #create a copy of xorg.conf with the profile in the filename...
- echo "Copyied /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}${PROFILEMONITOR} 15" >> "$TMP_DIR"/xorgwizard.messages && sleep 2s #9s
- cp -af /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}${PROFILEMONITOR}
+ echo "Copyied /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}-${PROFILEMONITOR} 15" >> "$TMP_DIR"/xorgwizard.messages && sleep 2s #9s
+ cp -af /etc/X11/xorg.conf /etc/X11/"xorg.conf.${PROFILECHIP}-${PROFILEMONITOR}"
  ##clear
  echo "Xorg Video Wizard completed. Type 'xwin' to start X..."
 else
