/usr/sbin/xorgwizard: Use XORG_DRIVER_DIR=/usr/X11/lib/xorg/modules/drivers  needed by i810OLD_drv.so .

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -84,6 +84,10 @@ _trap
 #
 ########################################################################
 
+# VARIABLES
+#XORG_DRIVER_DIR=/usr/lib/xorg/modules/drivers
+ XORG_DRIVER_DIR=/usr/X11/lib/xorg/modules/drivers #needed by i810OLD_drv.so
+
 OUT=/dev/null;ERR=$OUT
 [ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
  [ "$DEBUG" = "2" ] && set -x
@@ -92,7 +96,15 @@ tmpDir='/tmp/xorgwizard';mkdir -p "$tmpDir"
 echo "
 `date`" >>"$tmpDir"/xorgwizard.messages
 
-[ "`tty`" = "not a tty" -o "`tty`" = '?' ] && { sleep 2s; chvt 1; }
+#[ "`tty`" = "not a tty" -o "`tty`" = '?' ] && { sleep 2s; chvt 1; }
+tty >$OUT
+case $? in
+0) :;;      # info tty has exit codes
+1) sleep 2s; chvt 1;;
+2) _warn "given incorrect arguments";;
+3) _warn "write error occurs";;
+*) _err  "Unhandled return code by tty command";;
+esac
 
 ##+++2012-01-30
 if [ "`whoami`" = 'root' ]; then
@@ -1202,7 +1214,7 @@ echo "Copied /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic 9" >> "$tmpD
  cp $VERB /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic
  modprobe $Q $VERB evdev
  if [ "`grep '^modprobe evdev' /etc/rc.d/rc.local`" = "" ]; then #v2.17
-  echo "modprobe evdev" >> /etc/rc.d/rc.local
+  echo 'modprobe $Q $VERB evdev' >> /etc/rc.d/rc.local
  fi
  # Where we want to insert new lines...
  OLD1='Section "Module"'
@@ -1253,7 +1265,7 @@ if grep -F $Q 'Synaptics' /proc/bus/input/devices; then
  echo "Copying etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic 11" >> "$tmpDir"/xorgwizard.messages && sleep 2s #9s
  cp $VERB /etc/X11/xorg.conf /etc/X11/xorg.conf-without-synaptic
  modprobe $Q $VERB evdev
- echo "modprobe evdev" >> /etc/rc.d/rc.local
+ echo 'modprobe $Q $VERB evdev' >> /etc/rc.d/rc.local
  # Where we want to insert new lines...
  OLD1='Section "Module"'
  OLD2='Section "ServerLayout"'
@@ -1753,11 +1765,11 @@ generic driver, otherwise press ahead and try tweaking...${ALTERNATIVE_DRV_MSG}\
    echo "Copying $tmpDir/xorg.conf.tmp2 /etc/X11/xorg.conf 13" >> "$tmpDir"/xorgwizard.messages && sleep 2s #9s
     if [ "$TRYDRV" ];then
     if [ "INTEL_CARD" ];then
-     rm $VERB /usr/lib/xorg/modules/drivers/i810_drv.so
+     rm $VERB "$XORG_DRIVER_DIR"/i810_drv.so
       if [ "$TRYDRV" == "intel" ];then
-       ln $VERB -s intel_drv.so /usr/lib/xorg/modules/drivers/i810_drv.so
+       ln $VERB -s intel_drv.so "$XORG_DRIVER_DIR"/i810_drv.so
       else
-       ln $VERB -s i810OLD_drv.so /usr/lib/xorg/modules/drivers/i810_drv.so
+       ln $VERB -s i810OLD_drv.so "$XORG_DRIVER_DIR"/i810_drv.so
       fi
     fi #INTEL_CARD
     fi #TRYDRV
