/usr/sbin/xorgwizard : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -1,4 +1,5 @@
 #!/bin/bash
+# REM: bash for export -f _do_xvidtune()
 #(c) Copyright Barry Kauler 2006,2007 www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 ## Abused by Dougal, Feb 2007
@@ -570,7 +571,7 @@ quirky graphic cards do not work with Xorg, in which case you must operate from 
 
 Press ENTER for Xorg...
 Press TAB (or right-arrow) key then ENTER key to use the command line...\Zn" 0 0
- [ ! $? -eq 0 ] && exit 250
+ [ "$?" -eq 0 ] || exit 250
 
 else   #normal video adapter
 #v3.99 end
@@ -593,7 +594,7 @@ run this Wizard again and choose the <Xvesa> button.
 Press ENTER for Xorg \Z1probing will take several seconds\Z0...
 Press TAB (or right-arrow) key then ENTER key for Xvesa...\Zn" 0 0
  STATUS=$?  #v3.99
- [ $STATUS -eq -1 -o $STATUS -gt 254 ] && exit 250  #v3.99 ESC to exit, same as above dialogs
+ [ "$STATUS" = "" -o "$STATUS" = '-1' -o "$STATUS" = 255 ] && exit 250  #v3.99 ESC to exit, same as above dialogs
  if [ $STATUS -eq 1 ];then   #v3.99 Xvesa selected
   ln -sf /usr/bin/Xvesa /usr/bin/X #Xvesa is now the default X server.
   #when start xorgwizard from commandline, it messes up xorg.conf...
@@ -963,7 +964,7 @@ if [ "$HORIZSYNC" = "" -o "$VERTREFRESH" = "" ];then #"" if monitor not plug-n-p
  "R" "h31.5-94v50-90    CRT 1600x1200" \
  "Z" "SELECT THIS IF YOU KNOW MONITOR FREQUENCY SPECS" \
   2>"$tmpDIR"/taggen.txt
-  [ $? -ne 0 ] && exit 250
+  [ "$?" = 0 ] || exit 250
   CHOICE=`tail -n1 "$tmpDIR"/taggen.txt 2>$ERR`
   [ "$CHOICE" = "" ] && continue
   ## Dougal: use case-structure for setting params -- safer than the old way
@@ -1066,9 +1067,9 @@ if [ "$HORIZSYNC" = "" -o "$VERTREFRESH" = "" ];then #"" if monitor not plug-n-p
      ;;
    Z) # "SELECT THIS IF YOU KNOW MONITOR FREQUENCY SPECS"
      dialog --title "Xorg Graphics Wizard" --inputbox "Please enter the horizontal frequency range of the monitor, in KHz. An example is given:" 0 0 "31.5-48.5" 2>"$tmpDIR"/taghoriz.txt
-     [ $? -ne 0 ] && exit 250
+     [ "$?" = 0 ] || exit 250
      dialog --title "Xorg Graphics Wizard" --inputbox "Please enter the vertical frequency range of the monitor, in Hz. An example is given:" 0 0 "56-72" 2>"$tmpDIR"/tagvert.txt
-     [ $? -ne 0 ] && exit 250
+     [ "$?" = 0 ] || exit 250
      HORIZSYNC=`tail -n1 "$tmpDIR"/taghoriz.txt 2>$ERR`
      VERTREFRESH=`tail -n1 "$tmpDIR"/tagvert.txt 2>$ERR`
      [ "$HORIZSYNC" = "" ] && continue
@@ -1417,7 +1418,7 @@ you to press CTRL-ALT-BACKSPACE twice to terminate the test!)
 
 Press ENTER key now to start X graphics mode (may take a few secs)...
 TAB then ENTER to change the mouse (afterward will return here)..." 0 0
- DQ5=$?;[ $DQ5 -eq 255 ] && exit 250
+ DQ5=$?;[ "$DQ5" = "" -o "$DQ5" = 255 ] && exit 250
  if [ ! $DQ5 -eq 0 ];then
   #change the mouse... (then go back up to above dialog)
   choosemousefunc
@@ -1458,13 +1459,13 @@ Press ENTER if test was okay (or to fall back to Xvesa)... "
                   Refresh frequency    $VRTEST Hz
                   Driver               $CARD0DRIVER
 If you are reporting success, great, but if the display was not quite
-right, say displaced or distorted, you now have the option of tweaking
+right, say displaced or distorted, you now have the option to tweak
 various parameters in the X configuration file (/etc/X11/xorg.conf).
 Ditto if testing X was an abysmal failure.
 
 ${TWKMSG}
-TAB then ENTER to tweak parameters in xorg.conf & retest X..." 0 0
- DQ6=$?;[ $DQ6 -eq 255 ] && exit 250
+or TAB then ENTER to tweak parameters in xorg.conf & retest X..." 0 0
+ DQ6=$?;[ "$DQ6" = "" -o "$DQ6" = 255 ] && exit 250
  if [ $DQ6 -eq 0 ];then
   break
  fi
@@ -1492,7 +1493,15 @@ ATTN: There is an newer Intel video driver that might work better...'
  fi
 
  if [ "$CARD0DRIVER" != "vesa" ];then #v2.11
-  dialog --no-collapse ${EXTRABUTTON} --title "Xorg Graphics Wizard" --yes-label "Tweak_xorg.conf" --no-label "Generic_driver" ${EXTRALABEL} --yesno "Before continuing to tweaking xorg.conf, one other thing to consider.
+  # REM: dialog has a bug that switches yes/no label option to ok/cancel label if extra-button provided...
+  if [ "$EXTRABUTTON" != "" ]; then
+    YES_LBL='--ok-label'
+     NO_LBL='--cancel-label'
+  else
+    YES_LBL='--yes-label'
+     NO_LBL='--no-label'
+  fi
+  dialog --no-collapse ${EXTRABUTTON} --title "Xorg Graphics Wizard" ${YES_LBL} "Tweak_xorg.conf" ${NO_LBL} "Generic_driver" ${EXTRALABEL} --yesno "Before continuing to tweaking xorg.conf, one other thing to consider.
 Xorg has a dozen or so drivers for particular graphic chips, which
 optimises performance for the matching hardware, but sometimes a
 driver does not work right or there is no exact driver to match the
@@ -1510,7 +1519,7 @@ So, if you have already tried 'tweaking' or you know that the Xorg
 generic driver. Click 'Generic_driver' to change Xorg to using the
 generic driver, otherwise press ahead and try tweaking...
 ${INTELDRVMSG}" 0 0
-  RET2=$?;[ $RET2 -eq 255 ] && exit 250
+  RET2=$?;[ "$RET2" = "" -o "$RET2" = 255 ] && exit 250
   SUBSTDRV='vesa'
   [ $RET2 -eq 3 ] && SUBSTDRV="$TRYDRV" #w482 intel or i810
    CARD0DRIVER="$SUBSTDRV"
@@ -1561,7 +1570,7 @@ Again, the PPM may offer extra packages to add these capabilities.
 
 For now, keep going with using the Generic driver
 (for general PC use, this is proably all that you need anyway)..." 0 0
-  DM6=$?;[ $DM6 -eq 255 ] && exit 250
+  DM6=$?;[ "$DM6" = "" -o "$DM6" = 255 -o "$DM6" = '-1' ] && exit 250
   fi
  fi
 
@@ -1574,7 +1583,7 @@ to open xorg.conf in a text editor and change whatever you wish.
 
 Press ENTER key for the easy option, tweak refresh frequency...
 Press TAB then ENTER to open xorg.conf in a text editor..." 0 0
- DQ7=$?;[ $DQ7 -eq 255 ] && exit 250
+ DQ7=$?;[ "$DQ7" = "" -o "$DQ7" = 255 -o "$DQ7" = '-1' ] && exit 250
  if [ $DQ7 -eq 0 ];then
   if [ "$MONCHOICES" = "" ];then
    #not plug-n-play.
@@ -1609,7 +1618,7 @@ $MSGPNP" 0 0 0 \
  "$VERT4" "$MSGV4" \
  "$VERT5" "$MSGV5" \
  2>"$tmpDIR"/tagvert.txt
-  [ $? -eq 255 ] && { echo "Aborted.";exit 250; }
+  [ "$?" = 255 ] && { echo "Aborted.";exit 250; }
   #FUTURE: use xrandr above, to determine alternative lower frequencies.
 
   CHOSENVERT=`tail -n1 "$tmpDIR"/tagvert.txt 2>$ERR`
@@ -1642,7 +1651,7 @@ For the resolution that you want to run at, you many want to narrow
 but xorg.conf has VertRefresh 50-160. -- maybe narrow that to 50-85.
 
 Press ENTER key to edit xorg.conf..." 0 0
-  DQ8=$?;[ $DQ8 -ne 0 ] && exit 250
+  DQ8=$?;[ "$DQ8" = 0 ] || exit 250
   #edit xorg.conf...
   mp /etc/X11/xorg.conf
  fi
@@ -1658,7 +1667,7 @@ Puppy with Xorg.
 If you cannot get Xorg to work, press TAB then ENTER to choose
 the \"Xvesa\" button. This will start Puppy with the simple Xvesa
 graphics server that runs on most graphic chips." 0 0
-  DQ9=$?;[ $DQ9 -ne 0 -o $DQ9 -ne 1 ] && exit 250
+  DQ9=$?;[ "$DQ9" = 0 -o "$DQ9" = 1 ] || exit 250
   if [ $DQ9 -eq 0 ];then
    echo "Linked X to Xvesa"
    ln -sf /usr/bin/Xvesa /usr/bin/X
@@ -1677,7 +1686,7 @@ fi
 #mv -f /root/xorg.conf.new /tmp/xorg.conf.new
 cp -f /root/xorg.conf.new "$tmpDIR"/xorg.conf.new
 
-if [ $XTEST -eq 3 ];then #<FIX> (XAUTO=0 is <OK> button)
+if [ "$XTEST" = 3 ];then #<FIX> (XAUTO=0 is <OK> button)
  #need to do this here again in case of tweaking made some changes...
  #create a copy of xorg.conf with the profile in the filename...
  cp -af /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}-${PROFILEMONITOR}
