/usr/sbin/xorgwizard: Code changes for last commits. Now worked partly with Xorg v1.10.6 kernel 2.6.31.14 .
This xorgwizard does not add a #card[1-9]driver every Device section
while processing /root/xorg.conf.new except #card0driver,
thus making things difficult while replacing entries.
Also Screen[1-9] lines in ServerLayout are not commented.

Worked today when editing xorg.conf
to re-enable all commented needed sections in xorg.conf
and commenting Screen[1-9] lines in Section ServerLayout.
mp editor seems to put some difficult LF into the file,
that makes sed choke, thus _split_device_section() failed to create
new Card[0-9].conf files with content.
In that case _split_device_section returned non-zero.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard
@@ -289,6 +289,8 @@ case $CONSKEYMAP in
   ;;
 esac
 
+if [ "`echo -n "$PSFND" | grep '\.xinitrc'`" != "" ];then
+
 KNOWNXservers="Xati Xchips Xephyr Xepson Xfake Xfbdev Xi810 Xmach64 Xmga Xneomagic Xnest Xnvidia Xorg Xpm2 Xr128 Xsdl Xsmi Xvesa Xvfb Xvia"
 #KNOWNXservers="Xchips Xfake Xephyr Xfbdev Xnest Xorg Xvesa Xvfb"
 for content in $KNOWNXservers ; do
@@ -436,7 +438,7 @@ and the Wizard will run in text mode, before X is launched.
 echo Step 3 >&2
 
 #do this code block if X is running...
-if [ ! "`echo -n "$PSFND" | grep '\.xinitrc'`" = "" ];then
+#if [ "`echo -n "$PSFND" | grep '\.xinitrc'`" != "" ];then
 echo Step 4 >&2
  RETSTR=`echo "$MAIN_DIALOG" | gtkdialog2 --stdin`  ##-p "$MAIN_DIALOG"`"  ## | gtkdialog2`"  ## --stdin`
  ##gtkdialog2 --program=MAIN_DIALOG
@@ -705,7 +707,8 @@ Section \"Modes\"
     #ModeLine  \"name\" mode-description  ## see man xorg.conf
     #                   dot (pixel) clock, horizontal timings(hdisp,hsyncstart, hsyncend, htotal), vertical timings(vdisp, vsyncstart, vsyncend, vtotal) [, list of flags(+-HSunc, +-VSync, +-CSync) ]
     #modes0modeline0
-EndSection"
+EndSection
+"
      #v3.98 rerwin - added preferredmode line, after usemodes line.
      continue # we added the line before the "Modes" section, so continue
     fi
@@ -1145,7 +1148,7 @@ fi
 
 #FINALCHOICES=`cat $tmpDIR/finalchoices.txt`
 FINALCHOICES=`cat "$tmpDIR"/finalchoices.txt | sort -t x -n` #v3.93 rerwin
-echo "FINALCHOICES='$FINALCHOICES'"
+echo -e "\\033[1;32m""FINALCHOICES='$FINALCHOICES'""\\033[0;39m"
 #read -p "Press any key to go on " -n1 -t 20 GO_ON_KEY_1056
 echo "Press any key to go on "
 read -s -n1 -t20 GO_ON_KEY_1060;echo
@@ -1155,17 +1158,17 @@ echo ' --no-collapse --title "Puppy Graphics Wizard" --ok-label "OK" --extra-lab
 shown in the format WidthxHeightxBits, where Width and Height are
 screen resolution in pixels, 16/24 bits = 65,536/16,777,216 colors.
 ' >> "$tmpDIR"/choosexmodedlg
-[ ! "$RECMODE" = "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >> "$tmpDIR"/choosexmodedlg
-echo '\Z1RECOMMENDATION: Choose <TEST> button to verify it works!\Z0' >> "$tmpDIR"/choosexmodedlg
+[ "$RECMODE" != "" ] && echo "CANNOT DECIDE? ...${RECMODE} is suggested as a good choice."  >> "$tmpDIR"/choosexmodedlg
+echo '\Z1RECOMMENDATION: Choose <TEST> button to verify it works!\Zn' >> "$tmpDIR"/choosexmodedlg
 echo '
 OK:     Just press ENTER key to immediately use the selected mode...
 TEST: TAB key then ENTER to test and debug the mode before using it...
 EXIT: Exit to text-mode console, do not start X...\Zn" 0 0 0 \' >> "$tmpDIR"/choosexmodedlg #'geanyfix.
 echo "$FINALCHOICES" >> "$tmpDIR"/choosexmodedlg
-echo ' 2>"$tmpDIR"/tag.txt' >> "$tmpDIR"/choosexmodedlg
+echo " 2>$tmpDIR/tag.txt" >> "$tmpDIR"/choosexmodedlg
 echo 'exit $?' >> "$tmpDIR"/choosexmodedlg
 
-chmod 755 "$tmpDIR"/choosexmodedlg
+chmod $VERB 0755 "$tmpDIR"/choosexmodedlg
 "$tmpDIR"/choosexmodedlg
 XTEST=$? #=0 for automatic.
 [ $XTEST -ne 0 ] && [ $XTEST -ne 3 ] && { echo -e "XTEST='$XTEST' and -ne '0' and -ne '3'\nExiting '$0'.";exit 250; } #drop out to console. w005 uncommented.
@@ -1271,7 +1274,7 @@ if grep $Q -F 'Alps' /proc/bus/input/devices ; then
  NEW3='Section "InputDevice"\
     Identifier "Synaptics Mouse"\
     Driver "synaptics"\
-#    Option "Device" "/dev/psaux"\
+   #Option "Device" "/dev/psaux"\
     Option "Protocol" "auto-dev"\
     Option "LeftEdge" "120"\
     Option "RightEdge" "930"\
@@ -1318,7 +1321,7 @@ if grep $Q -F 'Synaptics' /proc/bus/input/devices ; then
  NEW3='Section "InputDevice"\
     Identifier "Synaptics Mouse"\
     Driver "synaptics"\
-#    Option "Device" "/dev/psaux"\
+   #Option "Device" "/dev/psaux"\
     Option "Protocol" "auto-dev"\
     Option "LeftEdge" "1700"\
     Option "RightEdge" "5300"\
@@ -1333,7 +1336,7 @@ if grep $Q -F 'Synaptics' /proc/bus/input/devices ; then
     Option "MaxSpeed" "0.30"\
     Option "AccelFactor" "0.0030"\
     Option "SHMConfig" "on"\
-    #Option "Repeater" "/dev/ps2mouse"\
+   #Option "Repeater" "/dev/ps2mouse"\
 EndSection\
 \
 Section "Monitor"'
@@ -1388,9 +1391,13 @@ else
  [ -f /etc/resolutionfix ] && rm $VERB -f /etc/resolutionfix
 fi
 
+DEBUG=1
+Q=
+VERB=-v
+
 _get_driver_description(){
 unset DESCR
-test "$*" || return 2
+test "$*" || return 3
 case $* in
 apm)           DESCR='Alliance ProMotion video driver';;
 ark)           DESCR='driver for ARK Logic chipset';;
@@ -1475,17 +1482,23 @@ test "$f" = "${XORGCONFFILE}.d/Card0.conf" && continue
 sed -i 's%^\([^#].*\)%#\1%' "$f"
 done
 sed -i 's%^#*%%' "$XORGCONFFILE".d/Card0.conf
-p1=`grep -E 'Driver[[:blank:]]+".*"[[:blank:]]+#card[0-9]+driver' "$XORGCONFFILE".d/Card0.conf`
+p1=`grep -E 'Driver[[:blank:]]+".*"' "$XORGCONFFILE".d/Card0.conf`
 p2=`echo "$p1" | sed -r 's%(^.*)("[^"]*")(.*$)%\(\1\)\(\2\)\(\3\)%'`
 _debug "'$p2'"
 # TODO: Worked OK until now, but may need similar in Device.conf
 sed -i -r "s%$p2%\1\"$*\"\3%" "$XORGCONFFILE".d/Card0.conf
+test $? = 0 && CARD0DRIVER1="$*"
+p1=`grep -m1 -E 'Driver[[:blank:]]+".*"' "$XORGCONFFILE"`
+p2=`echo "$p1" | sed -r 's%(^.*)("[^"]*")(.*$)%\(\1\)\(\2\)\(\3\)%'`
+_debug "'$p2'"
+sed -i -r "s%$p2%\1\"$*\"\3%" "$XORGCONFFILE"
 test $? = 0 && CARD0DRIVER="$*"
+test "$CARD0DRIVER1" = "$CARD0DRIVER"
 }
 
 _show_all_drivers(){
 
-[ "$DEBUG" ] && ls -1 $XORG_DRIVER_DIR && sleep 1
+[ "$DEBUG" ] && ls -1 "$XORG_DRIVER_DIR" && sleep 1
 ALL_DRIVERS=`ls -1 "$XORG_DRIVER_DIR"/*_drv.so`
 unset ALL_DRIVER_LIST
 while read driver
@@ -1505,7 +1518,7 @@ done <<EoI
 `echo "$ALL_DRIVERS"`
 EoI
 
-[ "$DEBUG" ] && echo "$ALL_DRIVER_LIST" && sleep 1
+_debug "$ALL_DRIVER_LIST" && sleep 1
 
 test "$ALL_DRIVER_LIST" || ALL_DRIVER_LIST='WARNING "No drivers detected in '"$XORG_DRIVER_DIR"'"'
 
@@ -1525,7 +1538,7 @@ detected drivers, press TAB key to mark the <\Z1C\Z0\Zbancel\ZB> button
 and then press Enter.'
 
 #since descr contains space, needs workaround using eval..
-rm -f "$tmpDIR"/select_driver
+rm $VERB -f "$tmpDIR"/select_driver
 set - $ALL_DRIVER_LIST
 eval "dialog --colors --backtitle '$BTTEXT' --title '$TTEXT' --menu '$MENU_TEXT' 0 0 0 $@ 2>$tmpDIR/select_driver"
 case $? in
@@ -1551,6 +1564,9 @@ esac
 
 _split_sections(){
 
+test -f "$XORGCONFFILE" || return 3
+
+rm $VERB -rf "$XORGCONFFILE".d
 mkdir $VERB -p "$XORGCONFFILE".d
 
 for dev in "ServerLayout" "Files" "Module" "InputDevice" "Monitor" "Modes" "Device" "Screen"
@@ -1562,30 +1578,40 @@ for dev in "ServerLayout" "Files" "Module" "InputDevice" "Monitor" "Modes" "Devi
  sed "/./{H;d};x;/Section \"$dev\".*\".*\".*EndSection/!d" "$XORGCONFFILE" >"$XORGCONFFILE".d/"$dev".conf
  }
 
+test -s "$tmpDIR"/"$dev".conf && {
 echo "
-#SEDMARKER" >>"$tmpDIR"/"$dev".conf
+#SEDMARKER" >>"$tmpDIR"/"$dev".conf; } || {
+    rm $VERB -f "$tmpDIR"/"$dev".conf; }
 
 done
+
+test -f "$tmpDIR"/Device.conf
 }
 
 _split_device_section(){
 # split the device section
+test -f "$tmpDIR"/Device.conf || return 3
 c=-1
 while :
 do
 c=$((c+1))
  grep $Q -E "[[:blank:]]+\"Card$c\"" "$tmpDIR"/Device.conf || break
 
+  rm $VERB -f "$tmpDIR"/Card$c.conf
  #sed "/./{H;d};x;/^Section \"Device\".*\"Card$c\".*EndSection$/!d" "$tmpDIR"/Device.conf >"$tmpDIR"/Card$c.conf
  #sed -r "/./{H;d};x;/^Section \"Device\".*\"Card$c\".*EndSection/!d" "$tmpDIR"/Device.conf >"$tmpDIR"/Card$c.conf
-  sed "/./{H;$!d};x;/Section \"Device\".*\"Card$c\".*EndSection$/!d" "$tmpDIR"/Device.conf >"$tmpDIR"/Card$c.conf
+  sed "/./{H;d};x;/Section \"Device\".*\"Card$c\".*EndSection$/!d" "$tmpDIR"/Device.conf >"$tmpDIR"/Card$c.conf
  test $? = 0 && {
+  rm $VERB -f "$XORGCONFFILE".d/Card$c.conf
  #sed "/./{H;d};x;/^Section \"Device\".*\"Card$c\".*EndSection$/!d" "$tmpDIR"/Device.conf >"$XORGCONFFILE".d/Card$c.conf
  #sed -r "/./{H;d};x;/^Section \"Device\".*\"Card$c\".*EndSection/!d" "$tmpDIR"/Device.conf >"$XORGCONFFILE".d/Card$c.conf
-  sed "/./{H;$!d};x;/Section \"Device\".*\"Card$c\".*EndSection$/!d" "$tmpDIR"/Device.conf >"$XORGCONFFILE".d/Card$c.conf
+  sed "/./{H;d};x;/Section \"Device\".*\"Card$c\".*EndSection$/!d" "$tmpDIR"/Device.conf >"$XORGCONFFILE".d/Card$c.conf
  }
-
+test -s "$XORGCONFFILE".d/Card$c.conf || rm $VERB -f "$XORGCONFFILE".d/Card$c.conf
+test -s "$tmpDIR"/Card.$c.conf        || rm $VERB -f "$tmpDIR".d/Card$c.conf
 done
+ls -ls "$XORGCONFFILE".d/ 
+test -f "$XORGCONFFILE".d/Card0.conf
 }
 
 _make_driver_list(){
@@ -1594,28 +1620,29 @@ unset DRIVERS DRIVERS_LIST0 DRIVERS_LIST
 for n in `seq 0 1 $((c-1))`
 do
 
-[ "$DEBUG" ] && grep "#card${n}driver" "$tmpDIR"/Card$n.conf
+test -f "$tmpDIR"/Card$n.conf || continue
+grep $Q -E 'Driver[[:blank:]]+"[^"]*"' "$tmpDIR"/Card$n.conf
 DRIVERS="$DRIVERS
-`grep \"#card${n}driver\" $tmpDIR/Card$n.conf | cut -f2 -d'\"'`"
+`grep -E 'Driver[[:blank:]]+\"[^\"]*\"' $tmpDIR/Card$n.conf | cut -f2 -d'\"'`"
 
 done
 
-[ "$DEBUG" ] && echo "DRIVERS:$DRIVERS"
+_debug "DRIVERS:$DRIVERS"
 test "$DRIVERS" || DRIVERS_MSG='Error, no Drivers detected.'
-[ "$DEBUG" ] && echo "DRIVERS:$DRIVERS"
+_debug "DRIVERS:$DRIVERS"
 
 BAD_DRIVERS=`echo "$DRIVERS" | grep -E 'fbdev|modesetting|vesa'`
-[ "$DEBUG" ] && echo "BAD_DRIVERS:$BAD_DRIVERS"
+_debugx "BAD_DRIVERS:$BAD_DRIVERS"
 test "$BAD_DRIVERS" && BAD_DRIVERS_MSG='\Z4'`echo $BAD_DRIVERS`'\Zn' || BAD_DRIVERS_MSG='\Z1No simple video drivers detected.\Zn'
-[ "$DEBUG" ] && echo "BAD_DRIVERS:$BAD_DRIVERS"
+_debug "BAD_DRIVERS:$BAD_DRIVERS"
 
 GOOD_DRIVERS=`echo "$DRIVERS" | grep -vE 'fbdev|modesetting|vesa'`
-[ "$DEBUG" ] && echo "GOOD_DRIVERS:$GOOD_DRIVERS"
+_debugx "GOOD_DRIVERS:$GOOD_DRIVERS"
 test "$GOOD_DRIVERS" && GOOD_DRIVERS_MSG='\Z2'`echo $GOOD_DRIVERS`'\Zn' || GOOD_DRIVERS_MSG='\Z1Attention, no sophisticated video drivers detected.\Zn'
-[ "$DEBUG" ] && echo "GOOD_DRIVERS:$GOOD_DRIVERS"
+_debug "GOOD_DRIVERS:$GOOD_DRIVERS"
 
 #DRIVERS_LIST=`grep -h -o 'Card[0-9]\+.*' "$tmpDIR"/Card*.conf | cut -f1 -d'#'`
-DRIVERS_LIST0=`grep -h -o 'Driver[[:blank:]]\+".*".*#.*' "$tmpDIR"/Card*.conf | cut -f1 -d'#'`
+DRIVERS_LIST0=`grep -h -o 'Driver[[:blank:]]\+".*"' "$tmpDIR"/Card*.conf | cut -f1 -d'#'`
 test "$DEBUG" && {
 echo
 echo "$DRIVERS_LIST0" ; }
@@ -1665,7 +1692,7 @@ But you can also choose out of all installed drivers for Card0:"
 
 while :;
 do
-dialog --colors --cancel-label "$CTEXT" --backtitle "$BTTEXT" --title "$TTEXT" --menu "$MSG_TEXT" 0 0 2 $DRIVERS_LIST 2>"$tmpDIR"/select_card
+dialog --colors --cancel-label "$CTEXT" --backtitle "$BTTEXT" --title "$TTEXT" --menu "$MSG_TEXT" 0 0 5 $DRIVERS_LIST 2>"$tmpDIR"/select_card
 case $? in 0) _debug "_select_driver:0:OK"; break;; #OK
 1) echo 1;      #Cancel
   _show_all_drivers
@@ -1711,7 +1738,8 @@ _enable_card_conf(){
 
 #SELECTED_DRIVER=`tail -n1 "$tmpDIR"/select_driver`
 #test "$SELECTED_DRIVER" || _some_thing_wrong 'Error reading selected driver'
-
+test -f "$tmpDIR"/select_card || return 3
+test -s "$tmpDIR"/select_card || return 4
 SELECTED_CARD=`tail -n1 "$tmpDIR"/select_card`
 test "$SELECTED_CARD" || _some_thing_wrong 'Error reading selected video card'
 
@@ -1733,40 +1761,46 @@ do
 #sed -i 's%^%#%' "$f"
 sed -i 's%^\([^#].*\)%#\1%' "$f"
 done
-
-sed -i 's%^#*%%' "$CardFILE"
+test -f "$CardFILE" || return 5
+test -s "$CardFILE" || return 6
 #need to reset CARD0DRIVER
-CARD0DRIVER=`grep -E 'Driver[[:blank:]]+"[^"]+"[[:blank:]]+#card[0-9]+driver' "$CardFILE" | cut -f2 -d'"'`
-
+CARD0DRIVER=`grep -E 'Driver[[:blank:]]+"[^"]+"' "$CardFILE" | grep -vE '^[[:blank:]]*#' | cut -f2 -d'"'`
+sed -i 's%^#*%%' "$CardFILE"
 }
 
 _comment_all_section_device_in_xorg_conf(){
+
+test -s "$XORGCONFFILE" || return 3
 
 _get_total_line_nr(){
  wc -l "$XORGCONFFILE" | awk '{print $1}'
 }
 
 _get_first_card_nr(){
- grep -n -m1 -E 'Driver[[:blank:]]+"[^"]*"[[:blank:]]+#card[0-9]+driver' "$XORGCONFFILE" | cut -f1 -d':'
+ grep -n -m1 -E 'Driver[[:blank:]]+"[^"]*"' "$XORGCONFFILE" | cut -f1 -d':'
 }
 
 _get_last_card_nr(){
- grep -n -E 'Driver[[:blank:]]+"[^"]*"[[:blank:]]+#card[0-9]+driver' "$XORGCONFFILE" | tail -n1 | cut -f1 -d':'
+ grep -n -E 'Driver[[:blank:]]+"[^"]*"' "$XORGCONFFILE" | tail -n1 | cut -f1 -d':'
 }
 
 _get_first_section_decice(){
+test "$fcnr" || return 3
  head -n $fcnr "$XORGCONFFILE" | grep -n "^[#'']*Section" | tail -n1 | cut -f1 -d':'
 }
 
 _get_first_endsection(){
+test "$fes" || return 3
  tail -n $fes "$XORGCONFFILE" | grep -m1 -n "^[#'']*EndSection" | cut -f1 -d':'
 }
 
 _get_last_section_decice(){
+test "$lcnr" || return 3
  head -n $lcnr "$XORGCONFFILE" | grep -n "^[#'']*Section" | tail -n1 | cut -f1 -d':'
 }
 
 _get_last_endsection(){
+test "$les" || return 3
  tail -n $les "$XORGCONFFILE" | grep -m1 -n "^[#'']*EndSection" | tail -n1 | cut -f1 -d':'
 }
 
@@ -1797,6 +1831,7 @@ _debug " lcnr=$lcnr"
 _debug "lesnr=$lesnr"
 
 _simple_comment_every_line(){
+ test "$fsdnr" -a "$lesnr" || return 3
  sed -i "$fsdnr,$lesnr s%^\([^#].*\)%#\1%" "$XORGCONFFILE"
 }
 _simple_comment_every_line
@@ -1809,9 +1844,23 @@ sed -i 's%^\([^#].*\)%#\1%' "$XORGCONFFILE".d/Device.conf
 }
 
 _ask_driver(){
-_split_sections       || return 3
-_split_device_section || return 4
-_make_driver_list     || return 5
+_split_sections
+RV=$?
+echo "_split_sections returned $RV"
+test $RV = 0 || return 3
+
+_split_device_section 
+RV=$?
+echo "_split_device_section returned $RV"
+test $RV = 0 || return 4
+
+
+_make_driver_list
+RV=$?
+echo "_split_device_section returned $RV"
+test $RV = 0 || return 5
+
+
 _select_driver
  case $? in
  9)
@@ -1820,8 +1869,23 @@ _select_driver
  0) :;;
  *) exit 1;;
  esac
-_enable_card_conf     || return 7
+
+_enable_card_conf; RV=$?
+case $RV in
+0) echo _enable_card_conf returned 0;;
+1) echo _enable_card_conf returned 1;;
+2) echo _enable_card_conf returned 2;;
+3) echo _enable_card_conf returned 3;;
+4) echo _enable_card_conf returned 4;;
+5) echo _enable_card_conf returned 5;;
+6) echo _enable_card_conf returned 6;;
+*) echo _enable_card_conf retuned OTHER;;
+esac
+test $RV = 0 || return 7
+
 _comment_all_section_device_in_xorg_conf || return 8
+
+
 _comment_all_section_device_in_xorg_conf_d_device || return 9
 }
 
@@ -1879,14 +1943,29 @@ TAB then ENTER to change the mouse (afterward will return here)..." 0 0
  fi
 
  #w460 test Xorg...
+ /usr/bin/Xorg -ignoreABI -config /etc/X11/xorg.conf -logfile /var/log/Xorg_xinitrc_test.log :0 &
+ sleep 1
+ while :; do
+ pidof Xorg || break
+ c=$((c+1))
+ test $c = 5 &&  break
+ done
+ #pidof Xorg && { killall Xorg; true; } || { echo Xorg server likely crashed; }
+ if pidof Xorg; then
  xinit /usr/sbin/xinitrc_test -- /usr/bin/Xorg -ignoreABI -config /etc/X11/xorg.conf -logfile /var/log/Xorg_xinitrc_test.log :0
  #[ $? = 0 ] || exit 1
+
 if [ -f "$tmpDIR"/xorgwizard_initrc_test_results ]; then
  #eval "`cat $tmpDIR/xorgwizard_initrc_test_results`" #results from xinitrc_test
 #...XTEST, YTEST, HSTEST, VRTEST.
  source "$tmpDIR"/xorgwizard_initrc_test_results
 sleep 1s
 fi
+else
+ echo "Xorg crashed. Check your configuration."
+ sleep 3
+fi
+
 #less /var/log/Xorg.0.log
 #mp  /var/log/Xorg.0.log
 #e3 /var/log/Xorg.0.log
@@ -1961,7 +2040,7 @@ called 'vesa' (note, this is not the Xvesa X server!), that works with
 most graphic chips, but some performance may be lost.
 
 The current driver being used by
-Xorg is     '${CARD0DRIVER}' ,and your graphics
+Xorg is     '${CARD0DRIVER}' , and your graphics
 vendor is:  '${CARD0VENDOR}'
 board info: '${CARD0BOARD}'
 
@@ -1970,26 +2049,27 @@ So, if you have already tried 'tweaking' or you know that the Xorg
 generic driver. Click 'Generic_driver' to change Xorg to using the
 generic driver, otherwise press ahead and try tweaking...
 ${INTELDRVMSG}" 0 0
-  RET2=$?;[ "$RET2" = "" -o "$RET2" = 255 ] && exit 250
+  RET2=$?;
+  [ "$RET2" = "" -o "$RET2" = 255 ] && exit 250
   SUBSTDRV='vesa'
   [ $RET2 -eq 3 ] && SUBSTDRV="$TRYDRV" #w482 intel or i810
-   CARD0DRIVER="$SUBSTDRV"
+  #CARD0DRIVER="$SUBSTDRV"
   if [ $RET2 -ne 0 ];then
-   #CARD0DRIVER="$SUBSTDRV"
-   APATTERN="s/.*#card0driver/  Driver      \"${SUBSTDRV}\" #card0driver/g"
-   sed -e "$APATTERN" /etc/X11/xorg.conf > "$tmpDIR"/xorg.conf.tmp2
+   CARD0DRIVER="$SUBSTDRV"
+   aPATTERN="s/.*#card0driver/  Driver      \"${SUBSTDRV}\" #card0driver/g"
+   sed -e "$aPATTERN" /etc/X11/xorg.conf > "$tmpDIR"/xorg.conf.tmp2
    _sync
    cp $VERB -f "$tmpDIR"/xorg.conf.tmp2 /etc/X11/xorg.conf
-   CURRDRV=`basename $(readlink -e /usr/lib/xorg/modules/drivers/i810_drv.so)`
-   rm $VERB /usr/lib/xorg/modules/drivers/i810_drv.so
+   CURRDRV=`basename $(realpath "$XORG_DRIVER_DIR"/i810_drv.so)`
+   rm $VERB -f /usr/lib/xorg/modules/drivers/i810_drv.so
    if [ "$CURRDRV" = 'i810OLD_drv.so' ];then
-    ln $VERB -s intel_drv.so /usr/lib/xorg/modules/drivers/i810_drv.so
+    ln $VERB -s intel_drv.so "$XORG_DRIVER_DIR"/i810_drv.so
    else
-    ln $VERB -s i810OLD_drv.so /usr/lib/xorg/modules/drivers/i810_drv.so
+    ln $VERB -s i810OLD_drv.so "$XORG_DRIVER_DIR"/i810_drv.so
    fi
    continue
   fi
- else #using xorg 'vesa' driver...
+ else #if [ "$CARD0DRIVER" != "vesa" ];then #v2.11
   #SPECVESA=`find -L /usr/lib -noleaf -mount -type f -name vesa_drv.so`
   SPECVESA=`find -L /usr/lib -noleaf -xdev -type f -name vesa_drv.so | tail -n1`
   ##+2011-10-30 added tail
@@ -2076,17 +2156,17 @@ $MSGPNP" 0 0 0 \
   NEEDHORIZ=`gtf $XTEST $YTEST $CHOSENVERT | grep -o 'hsync: .*' | cut -f 2 -d ' ' | cut -f 1 -d '.'`
   let NEEDHORIZ=NEEDHORIZ+1 #compensate for rounding off error.
 
-  APATTERN="s/HORIZSYNC0/${HORIZSYNC}/g"
+  aPATTERN="s/HORIZSYNC0/${HORIZSYNC}/g"
   if [ $NEEDHORIZ -gt ${MAXHORIZ%.*} ];then
    if [ "$MONCHOICES" = "" ];then
     #monitor not plug and play.
-    APATTERN="s/HORIZSYNC0/${MINHORIZ}\\-${NEEDHORIZ}/g"
+    aPATTERN="s/HORIZSYNC0/${MINHORIZ}\\-${NEEDHORIZ}/g"
    fi
   fi
-  sed -e "$APATTERN" "$tmpDIR"/xorg.conf.tmp > "$tmpDIR"/xorg.conf.tmp2
-  BPATTERN="s/VERTREFRESH0/${MINVERT}\\-${CHOSENVERT}/g"
+  sed -e "$aPATTERN" "$tmpDIR"/xorg.conf.tmp > "$tmpDIR"/xorg.conf.tmp2
+  bPATTERN="s/VERTREFRESH0/${MINVERT}\\-${CHOSENVERT}/g"
   _sync
-  sed -e "$BPATTERN" "$tmpDIR"/xorg.conf.tmp2 > /etc/X11/xorg.conf
+  sed -e "$bPATTERN" "$tmpDIR"/xorg.conf.tmp2 > /etc/X11/xorg.conf
   _sync
   rm $VERB -f "$tmpDIR"/xorg.conf.tmp2
 
@@ -2104,8 +2184,11 @@ but xorg.conf has VertRefresh 50-160. -- maybe narrow that to 50-85.
 Press ENTER key to edit xorg.conf..." 0 0
   DQ8=$?;[ "$DQ8" = 0 ] || exit 250
   #edit xorg.conf...
+  test -f /etc/X11/xorg.conf || _exit 99 "No regular /etc/X11/xorg.conf file"
   mp /etc/X11/xorg.conf
  fi
+sleep 1
+
 done #testloop
 #########################################################
 
