woof-code/rootfs-skeleton/usr/sbin/xrandrshell: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/xrandrshell b/woof-code/rootfs-skeleton/usr/sbin/xrandrshell
--- a/woof-code/rootfs-skeleton/usr/sbin/xrandrshell
+++ b/woof-code/rootfs-skeleton/usr/sbin/xrandrshell
@@ -2,8 +2,32 @@
 #(c) Copyright Barry Kauler 2006 www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #v3.99 BK: fix for new version of xrandr, plus some enhancement.
+# Note, /etc/xrandrindex is read by /root/.xinitrc when X is started.
 
-#note, /etc/xrandrindex is read by /root/.xinitrc when X is started.
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
+
 
 XRANDR="`xrandr -q`"
 
@@ -31,7 +55,7 @@ TESTINDEX="`Xdialog --left --title "Xorg Resolution Changer" --stdout --no-tags 
 if [ ! $? -eq 0 ];then
  #made no choice.
  exit
-fi 
+fi
 
 xrandr -s $TESTINDEX
 
