wlan : Bulk Maintanance Replacement of today by Update_from_current_system .

diff --git a/woof-code/rootfs-skeleton/etc/init.d/FIRMWARE/wlan b/woof-code/rootfs-skeleton/etc/init.d/FIRMWARE/wlan
--- a/woof-code/rootfs-skeleton/etc/init.d/FIRMWARE/wlan
+++ b/woof-code/rootfs-skeleton/etc/init.d/FIRMWARE/wlan
@@ -1,8 +1,8 @@
-#!/bin/sh
+#!/bin/ash
 
-# rc.wlan 
+# rc.wlan
 #
-# chkconfig: 2345 9 91 
+# chkconfig: 2345 9 91
 # description: Activates/Configures/Disables the devices
 
 if [ ! -f /etc/wlan/shared ] ; then
@@ -13,7 +13,7 @@ fi
 . /etc/wlan/shared
 
 if [ -f /etc/init.d/functions ] ; then
-	. /etc/init.d/functions
+    . /etc/init.d/functions
 fi
 
 usage()
@@ -28,26 +28,26 @@ action=$1
 case "$action" in
 
 start)
-	# This will implicitly fire off wland via hotplug.
-	echo -n "Starting WLAN Devices: "
-	if ! $MODPROBE p80211; then
-		echo "Failed to load p80211.o."
-		exit 1
-	fi
+    # This will implicitly fire off wland via hotplug.
+    echo -n "Starting WLAN Devices: "
+    if ! $MODPROBE p80211; then
+        echo "Failed to load p80211.o."
+        exit 1
+    fi
 
-	# NOTE: We don't explicitly insmod the card driver here.  The
-	#  best thing to do is to specify an alias in /etc/modules.conf.
+    # NOTE: We don't explicitly insmod the card driver here.  The
+    #  best thing to do is to specify an alias in /etc/modules.conf.
 
-	for DEVICE in $WLAN_DEVICES; do
-	    $MODPROBE $DEVICE
-	    # if we don't have hotplug.. do things the old-fashioned way.
-	    if [ $HAS_HOTPLUG = 'n' ] ; then
-		wlan_bring_it_up $DEVICE
-	    fi
-	done
+    for DEVICE in $WLAN_DEVICES; do
+        $MODPROBE $DEVICE
+        # if we don't have hotplug.. do things the old-fashioned way.
+        if [ $HAS_HOTPLUG = 'n' ] ; then
+        wlan_bring_it_up $DEVICE
+        fi
+    done
 
-	# And hotplug will take care of the rest, namely device 
-	# initialization and whatnot.
+    # And hotplug will take care of the rest, namely device
+    # initialization and whatnot.
 
         if [ -f /etc/init.d/functions ] ; then
                 echo_success
@@ -55,42 +55,42 @@ start)
                 echo
         fi
 
-	;;
+    ;;
 
 stop)
-	echo -n "Shutting Down WLAN Devices: "
-	echo -n "Shutting Down WLAN Devices: "
-	# Do a reset on each device to make sure none of them are still
-	#  trying to generate interrupts.
-	for DEVICE in $WLAN_DEVICES; do
-		wlan_disable $DEVICE
-		ifconfig $DEVICE down
-		$MODPROBE -r $DEVICE
-	done
-	
-	# remove p80211, which will implictly kill wland.
-	$MODPROBE -r p80211
+    echo -n "Shutting Down WLAN Devices: "
+    echo -n "Shutting Down WLAN Devices: "
+    # Do a reset on each device to make sure none of them are still
+    #  trying to generate interrupts.
+    for DEVICE in $WLAN_DEVICES; do
+        wlan_disable $DEVICE
+        ifconfig $DEVICE down
+        $MODPROBE -r $DEVICE
+    done
+
+    # remove p80211, which will implictly kill wland.
+    $MODPROBE -r p80211
 
         if [ -f /etc/init.d/functions ] ; then
                 echo_success
         else
                 echo
         fi
-	;;
+    ;;
 
 status)
-	status wland
-	;;
+    status wland
+    ;;
 
 restart|reload|force-reload)
-	$0 stop
-	$0 start
-	EXITCODE=$?
-	;;
+    $0 stop
+    $0 start
+    EXITCODE=$?
+    ;;
 
     *)
-	usage
-	;;
+    usage
+    ;;
 
 esac
 
