defaulthandler : Bulk Maintanance Replacement of today by Update_from_current_system .

diff --git a/woof-code/rootfs-skeleton/usr/local/bin/defaulthandler b/woof-code/rootfs-skeleton/usr/local/bin/defaulthandler
--- a/woof-code/rootfs-skeleton/usr/local/bin/defaulthandler
+++ b/woof-code/rootfs-skeleton/usr/local/bin/defaulthandler
@@ -1,38 +1,48 @@
 #!/bin/ash
 #barryk 2005. partial update 2008.
 
-AFILE="`basename "$1"`"
+aFILE="`basename "$1"`"
 
-if [ "`echo -n "$AFILE" | grep '\.'`" = "" ];then
+if [ "`echo -n "$aFILE" | grep '\.[[:alnum:]]\+$'`" = "" ];then
  #/usr/local/bin/defaulttexteditor "$1"
- exit
+ echo
+ echo "ERROR:"
+ echo "$0:$*"
+ echo "Need extension to determine filetype."
+ echo
+ exit 1
 else
- AEXT="`echo "$AFILE" | rev | cut -f 1 -d '.' | rev`"
+ aEXT="`echo "$aFILE" | rev | cut -f 1 -d '.' | rev`"
 fi
 
 #this needs to be fleshed out a bit more...
-case $AEXT in
+case $aEXT in
  txt|TXT)
-  /usr/local/bin/defaulttexteditor "$1"
+  /usr/local/bin/defaulttexteditor "${1+$@}"
   ;;
  doc|DOC|rtf|RTF)
-  /usr/local/bin/defaultwordprocessor "$1"
+  /usr/local/bin/defaultwordprocessor "${1+$@}"
   ;;
  xls|XLS)
-  /usr/local/bin/defaultspreadsheet "$1"
+  /usr/local/bin/defaultspreadsheet "${1+$@}"
   ;;
  htm|html|HTM|HTML)
   #/usr/local/bin/defaulttexteditor "$1"
-  /usr/local/bin/defaulthtmlviewer "$1"
+  /usr/local/bin/defaulthtmlviewer "${1+$@}"
   ;;
  png|PNG|gif|GIF|jpg|JPG|jpeg|JPEG|xpm|XPM)
-  /usr/local/bin/defaultpaint "$1"
+  /usr/local/bin/defaultpaint "${1+$@}"
   ;;
  pdf|PDF|ps|PS|eps|EPS)
-  epdfview "$1"
+  epdfview "$1+$@}"
   ;;
  *)
-  /usr/local/bin/defaulttexteditor "$1"
+  echo "WARNING"
+  echo "$0:$@"
+  echo "Unhandled file extension '$aEXT'"
+  echo "Will start /usr/local/bin/defaulttexteditor as last attempt.."
+  /usr/local/bin/defaulttexteditor "${1+$@}"
+  echo
   ;;
 esac
 
