/usr/local/bin/drive_all: Update AppInfo.xml in case of media change.

diff --git a/woof-code/rootfs-skeleton/usr/local/bin/drive_all b/woof-code/rootfs-skeleton/usr/local/bin/drive_all
--- a/woof-code/rootfs-skeleton/usr/local/bin/drive_all
+++ b/woof-code/rootfs-skeleton/usr/local/bin/drive_all
@@ -36,38 +36,8 @@
 # 04.0 : Added support for udf .
 # 05.0 : Added support for different /sbin/probepart output
 #
-# /dev/sda2:
-# #OLD LABEL="2nd"
-# LABEL="MacPup_F_3"
-# #OLD UUID="a4f28ea3-eede-49f8-93ca-dbeefe8f72fa"
-# UUID="f7956448-f63f-44f4-a725-f15dd21add97"
-# TYPE="ext3"
-# DISTRO_VERSION=430            #481·#416·#218·#478··#####change·this·as·required#####
-# DISTRO_BINARY_COMPAT="puppy"  #"ubuntu"·#"puppy"···#####change·this·as·required#####
-# case·$DISTRO_BINARY_COMPAT·in
-# puppy)·#built·entirely·from·Puppy·v2.x·or·v3.x·or·4.x·pet·pkgs.
-# DISTRO_NAME="Puppy"
-# DISTRO_FILE_PREFIX="pup"  #"ppa"·#"ppa4"·#"pup2"··#pup4··###CHANGE·AS·REQUIRED,·recommend·limit·four·characters###
-# DISTRO_COMPAT_VERSION="4" #"2"··#4·····###CHANGE·AS·REQUIRED,·recommend·single·digit·5,·4,·3,·or·2###
-# ;;
-# esac
-# PUPMODE=2
-# KERNVER=2.6.34-KRG-i486
-# ATADRIVES='·sda'
-# USB_SATAD=''
-# PUP_HOME='/'
-# PDEV1='sda2'
-# #OLD Linux·puppypc·2.6.34-KRG-i486·#3·SMP·Fri·Dec·31·05:10:23·GMT-8·2010·i686·GNU/Linux
-# Linux puppypc 3.4.9-KRG-iCore2-smp-pae-srv1000gz #1 SMP Sun Sep 16 18:34:45 GMT+1 2012 i686 GNU/Linux
-# Xserver=/usr/X11R7/bin/Xorg
-# #OLD $LANG=de_DE@euro
-# $LANG=de_DE.utf8
-# #OLD today=Mi·18.·Jan·03:21:35·GMT+1·2012
-# today=Mon Sep 17 20:33:36 GMT+1 2012
 #
-# TODO 1 : iconhandler for udf
-#
-#
+# TODO 1 : Update drive's AppInfo.xml if media change (for cd- drives)
 #
 ########################################################################
 
@@ -81,7 +51,7 @@ MY_SELF="$0"
 MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
-[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5
+[ "$HAVE_F4PUPPY5" ] || . /etc/rc.d/f4puppy5
 
 ADD_PARAMETER_LIST="eventmanager|unmount|unmountall|[pmount_]DRV_CATEGORY ] [ FSTYPE ]"
 ADD_PARAMETERS="pmount_DRV_CATEGORY :
@@ -102,9 +72,21 @@ _parse_basic_parameters "$@"
 _trap
 }
 
+# VARIABLES
+### *** ROX-Filer Pinboard *** ###
+STATE_DIR="$HOME/Choices/Puppy"
+EXE_DIR='pup_event'
+PUP_EVENT_DIR="$STATE_DIR/$EXE_DIR"
+#PUP_EVENT_DIR="$HOME/Choices/Puppy/pup_event"
+#PUP_EVENT_DIR="$HOME/.pup_event"
+DRIVE_ICON_DIR="/usr/local/lib/X11/pixmaps"
+CONFFILEROX="$HOME/.config/rox.sourceforge.net/ROX-Filer/Options"
+  PUPPY_PIN="$HOME/Choices/ROX-Filer/PuppyPin"
+
+
 #w002 extracted as a func...
 _killzombies(){
-   ZOMBIES=`/bin/ps -H -A | grep '<defunct>' | sed 's#^[[:blank:]]*##'|sed -e 's/  /|/g' | grep -v '|||' | cut -f 1 -d ' '`
+   ZOMBIES=`/bin/ps -H -A | grep '<defunct>' | sed 's#^[[:blank:]]*##'|sed -e 's/  /|/g' | grep -v '|||' | awk '{print $1}'`
    for oneZOMBIE in $ZOMBIES
    do
     echo "Killing parent(less?) zombie process $oneZOMBIE"
@@ -210,7 +192,7 @@ PLEASE PRESS THE \"EXIT\" BUTTON!"
    fi
 
   else  # Unmount succeded
-   #[ "$oneDRVNAME" = "sr0" -o "$oneDRVNAME" = "sr1" ] && eject /dev/$oneDRVNAME
+
    case $oneDRVNAME in
     sr[0-9]*|scd[0-9]*|hd[a-d]) _command eject /dev/$oneDRVNAME;;
    esac
@@ -218,9 +200,9 @@ PLEASE PRESS THE \"EXIT\" BUTTON!"
 
   [ "$yPID_" ] && { /bin/ps -p $yPID_ >>$OUT 2>>$ERR && kill $yPID_; }
   break
-  #[ "$yPID_" ] && { /bin/ps -p $yPID_ >>$OUT 2>>$ERR && kill $yPID_; }
+
  done
-  #[ "$yPID_" ] && { /bin/ps -p $yPID_ >>$OUT 2>>$ERR && kill $yPID_; }
+
 }
 
 _notice "Called with \$*='$*'"
@@ -262,7 +244,7 @@ _notice "DRV_CATEGORY='$DRV_CATEGORY' FSTYPE='$FSTYPE' MOUNT_OPTS='$MOUNT_OPTS'"
 [ -b /dev/"$oneDRVNAME" ] || _exit 6
 
 [ -f /etc/eventmanager.cfg ] && . /etc/eventmanager.cfg #written to by /usr/sbin/eventmanager
-[ $RAMSAVEINTERVAL ] || RAMSAVEINTERVAL=30
+#[ $RAMSAVEINTERVAL ] || RAMSAVEINTERVAL=30
 
 #[ "$AUTOTARGET" != "true" -a "$AUTOTARGET" != "false" ]     && AUTOTARGET="true"
 case $AUTOTARGET in
@@ -295,7 +277,7 @@ if [ "$oneDRVNAME" = "drives" ];then
  exec pmount $DRV_CATEGORY
 fi
 # pmount_,eventmanager,unmount,unmountall
-#if [ "`echo "${1}" | grep 'pmount_'`" ];then #v403 chose pmount from drive icon menu.
+
 case $DRV_CATEGORY in
  pmount_*)
  DRV_CATEGORY=`echo -n "${1}" | cut -f 2 -d '_'`
@@ -305,15 +287,15 @@ case $DRV_CATEGORY in
  fi
  exec pmount ${DRV_CATEGORY}
 ;;
-#elif [ "$1" = "eventmanager" ];then #v403 chosen from drive icon menu.
+
 eventmanager)
  #v405 'desktop' param, cutdown tabs for desktop drive icons only...
  exec eventmanager desktop
 ;;
-#elif [ "$1" = "unmount" ];then #v403 chose unmount from drive icon menu.
+
 unmount)
  mPATTERN='^/dev/'"$oneDRVNAME"' '
- #MNTPT=`mount | grep "$mPATTERN" | cut -f 3 -d ' '`
+
  MNTPT=`/bin/df | tac | grep -m1 "$mPATTERN" | tr -s ' ' | cut -f 6- -d ' '`
  if [ "$MNTPT" = "" ]; then
   #case $DRV_CATEGORY in optical)
@@ -328,16 +310,13 @@ unmount)
 is in use by Puppy. You cannot unmount it."
   exit 201
  fi
- #yaf-splash -bg purple3 -text "Unmounting '$MNTPT' .." & yPID=$!
- _unmount
- #[ "$yPID" ] && { /bin/ps -p $yPID >>$OUT 2>>$ERR && kill $yPID; }
+  _unmount
  exit $?
 ;;
 #v424 have added right-click menu item to unmount all partitions (see pup_event_frontend_d)...
-#elif [ "$1" = "unmountall" ];then
+
 unmountall)
- #for MNTPT in `mount | tac | grep '^/dev/' | grep -vE '^/dev/loop|^/dev/ram|^/dev/md|^/dev/mtd|^/dev/nbd' | cut -f 3 -d ' ' | grep -v '^/initrd/' | grep -v '^/$'`
- #while read device blocks used avail percent MNTPT
+
  while read -r oneDRVNAME MNTPT rest
  do
  [ "$MNTPT" ] || continue
@@ -350,12 +329,9 @@ unmountall)
  done <<EoI
 `tac /proc/mounts | grep '^/dev/' | grep -vE '^/dev/loop|^/dev/ram|^/dev/md|^/dev/mtd|^/dev/nbd'`
 EoI
-
-# done <<EoI
-#`/bin/df | tac | grep '^/dev/' | grep -vE '^/dev/loop|^/dev/ram|^/dev/md|^/dev/mtd|^/dev/nbd'`
-#EoI
  exit $?
 ;;
+
 *mountro)
          grep $Q -w "^/dev/$oneDRVNAME" /proc/mounts && {
 
@@ -370,11 +346,11 @@ EoI
  [ "$yioPID" ] && { /bin/ps -p $yioPID >>$OUT 2>>$ERR && kill $yioPID; }
 
 
-   if grep -w "^/dev/$oneDRVNAME" /proc/mounts | awk '{print $4}' | grep $Q -w rw
+   if grep -w "^/dev/$oneDRVNAME" /proc/mounts | awk '{print $4}' | grep $Q -w 'rw'
  then
         /bin/mount $VERB -o remount,ro /dev/"$oneDRVNAME" /mnt/"$oneDRVNAME" || false
 
- elif grep -w "^/dev/$oneDRVNAME" /proc/mounts | awk '{print $4}' | grep $Q -w ro
+ elif grep -w "^/dev/$oneDRVNAME" /proc/mounts | awk '{print $4}' | grep $Q -w 'ro'
  then
         /bin/mount $VERB -o remount,rw /dev/"$oneDRVNAME" /mnt/"$oneDRVNAME" || false
 
@@ -404,8 +380,52 @@ exit $RV
 ;;
 
 esac
-#fi
+
 # pmount_,eventmanager,unmount,unmountall
+
+# REM: Since the drive icons for cd drives stay on desktop,
+#      Tooltips need updated when hoovering over icon
+#      For Media no fstype ..
+#      I make a whole title list
+_update_appinfo_mediacd(){
+
+cdINFO=`disktype /dev/$oneDRVNAME`
+test "$cdINFO" || return 1
+
+ SIZE=`echo "$cdINFO" | grep -o 'size .*' | cut -f1-3 -d ' '`
+TITLE=`echo "$cdINFO" | grep -e 'CD-ROM.*'`
+
+TRACKS=`echo "$cdINFO" | grep '^Track'`
+
+mINFO="<Summary>
+$TITLE
+$SIZE"
+
+while read T NR MEDIA t SIZE POWER size b TIME
+do
+[ "$T" ] || continue
+mINFO="$mINFO
+$T $NR $MEDIA $SIZE $POWER $TIME"
+
+done<<EoI
+`echo "$TRACKS"`
+EoI
+
+mINFO="$mINFO
+</Summary>"
+
+mkdir $VERB -p "$drive_iconDIR"
+
+echo "<?xml version=\"1.0\"?>
+<AppInfo>
+   ${mINFO}
+" >/tmp/AppInfo.xml
+
+#sed -n '/<About>/,/<\/AppInfo>/ p' $PUP_EVENT_DIR/drive_${oneDRVNAME}/AppInfo.xml
+sed -n '/<About>/,/<\/AppInfo>/ p' $PUP_EVENT_DIR/drive_${oneDRVNAME}/AppInfo.xml >>/tmp/AppInfo.xml
+test $? = 0 && cp $VERB -f /tmp/AppInfo.xml $PUP_EVENT_DIR/drive_${oneDRVNAME}/
+
+}
 
 #oh, now have to analyse the media, decide what app to run...
 #if [ "$oneDRVNAME" = "sr0" -o "$oneDRVNAME" = "sr1" ];then
@@ -479,6 +499,7 @@ EoI
    #cddetect does not work properly for dvd's, try something else...
    __start_mediaplayer(){
     if [ "`dvd+rw-mediainfo /dev/sr0 | grep 'Mounted Media: .* DVD-ROM'`" ];then
+
      ln $VERB -sf /dev/${oneDRVNAME} /dev/dvd
      exec defaultmediaplayer dvd://
     fi
@@ -487,6 +508,7 @@ EoI
    ;;
 
   1) #audio
+     _update_appinfo_mediacd
      ln $VERB -sf /dev/${oneDRVNAME} /dev/cdrom
      exec defaultmediaplayer cdda://
    ;;
@@ -494,12 +516,14 @@ EoI
      true
    ;;
   5) #video dvd
+     _update_appinfo_mediacd
      ln $VERB -sf /dev/${oneDRVNAME} /dev/dvd
      exec defaultmediaplayer dvd://
    ;;
   8) # udf with .wma wav files [VCD: , ] 8 ##+++2012-01-20
      # FSTYPE='udf'
      FSTYPE=`guess_fstype /dev/$oneDRVNAME`
+     _update_appinfo_mediacd
      ln $VERB -sf /dev/${oneDRVNAME} /dev/dvd
      exec defaultmediaplayer dvd://
    ;;
@@ -512,6 +536,66 @@ EoI
  [ "$FSTYPE" ] || FSTYPE=unknown
  [ "$FSTYPE" = unknown ] && unset FSTYPE
 fi
+
+_format_size(){ #from pup_event_frontend_d
+ SIZE="$1"
+ [ $SIZE ] || SIZE=0
+ if [ $SIZE -gt 1048576 ];then #1024*1024
+  SIZE=`LANG=$OLDLANG dc $SIZE 1048576 \/ p` #100613 dc o/p '.' if LANG=C.
+  SIZE="`LANG=$OLDLANG printf "%.1f" $SIZE`GB" #100613
+ elif [ $SIZE -gt 1024 ];then
+  SIZE="$(( SIZE / 1024 ))"'MB'
+ else
+   SIZE=`LANG=$OLDLANG dc $SIZE 1024 \/ p` #100613
+   SIZE="`LANG=$OLDLANG printf "%.3f" $SIZE`MB" #100613
+ fi
+ [ "$SIZE" = "0.0MB" ] && SIZE="0"
+ [ "$SIZE" = "0,0MB" ] && SIZE="0" #100613
+}
+
+# REM: Media may have changed or FSTYPE
+#      Want to update AppInfo.xml
+_update_appinfo_mount(){
+#<Summary>Filesystem: ext4 Size: 31.5GB</Summary>
+
+case $oneDRVNAME in
+fd[0-9]*|hd[a-d]|scd[0-9]*|sr[0-9]*) DISK=$oneDRVNAME;;
+*) DISK=`echo "$oneDRVNAME" | sed 's#[0-9]*$##'`;;
+esac
+
+if test -f /sys/block/$oneDRVNAME/size; then
+read SIZE </sys/block/$oneDRVNAME/size
+DESCR=`probedisk2 | grep "^/dev/${oneDRVNAME}|" | cut -f3 -d'|'`
+SUMMARY1="<Summary>$DESCR"
+
+elif test -f /sys/block/$DISK/$oneDRVNAME/size; then
+read SIZE </sys/block/$DISK/$oneDRVNAME/size
+FSTYPE=`probepart -d/dev/$oneDRVNAME |cut -f2 -d'|'`
+SUMMARY1="<Summary>Filesystem: $FSTYPE"
+
+else
+SIZE=0
+DESCR=`probedisk2 | grep "^/dev/${DISK}" | cut -f3 -d'|'`
+SUMMARY1="<Summary>$DESCR"
+
+fi
+
+SIZE=$((SIZE/2))
+_format_size $SIZE
+
+echo "<?xml version=\"1.0\"?>
+<AppInfo>
+ $SUMMARY1 Size: $SIZE</Summary>
+" >/tmp/AppInfo.xml
+
+sed -n '/<About>/,/<\/AppInfo>/ p' $PUP_EVENT_DIR/drive_${oneDRVNAME}/AppInfo.xml >>/tmp/AppInfo.xml
+test $? = 0 && cp $VERB -f /tmp/AppInfo.xml $PUP_EVENT_DIR/drive_${oneDRVNAME}/
+#if test -f $PUP_EVENT_DIR/drive_${oneDRVNAME}/AppInfo.xml; then
+#sed -i "s%<Summary>.*</Summary>%<Summary>Filesystem: $FSTYPE Size: $SIZE</Summary>%" $PUP_EVENT_DIR/drive_${oneDRVNAME}/AppInfo.xml
+#else
+#false
+#fi
+}
 
 _debug "FSTYPE=$FSTYPE"
 #if dropped down here, it is likely to be a data partition...
@@ -556,6 +640,8 @@ if [ "$FSTYPE" ];then
     #       else unset FSTYPE and try without FSTYPE
     #       mount-FULL is quite capable to detect fs automatically
     #        and load fs-driver if not inside kernel (already loaded)
+    #        but busybox mount is also good but fails sometimes
+    #        autodetecting the fstype and always falls back to ocfs2
     grep $Q -w "$FSTYPE" /proc/filesystems || unset FSTYPE
     [ "$FSTYPE" ] && {
     /bin/mount $VERB $MOUNT_OPTS -t $FSTYPE /dev/$oneDRVNAME /mnt/$oneDRVNAME || false
@@ -569,6 +655,7 @@ if [ "$FSTYPE" ];then
   WARN_MSG=`dmesg | tail -n5 | grep -w "($oneDRVNAME)" | grep $Q -E 'emerg|alert|crit|error|warning'`
   [ "$WARN_MSG" ] && xmessage -title "DRIVE_ALL MOUNT WARNING" "$WARN_MSG" &
   /bin/ps -p $yPID >>$OUT && kill $yPID
+  _update_appinfo_mount
   [ "$RETVAL1" = 0 ] && exit $RETVAL1
  else
   #mounted...
@@ -615,9 +702,53 @@ if [ "`pidof gtkdialog_pmount`" ];then #if pmount running, kill it.
 fi
 }
 
+_update_appinfo_no_media(){
+#<Summary>Filesystem: ext4 Size: 31.5GB</Summary>
+case $oneDRVNAME in
+fd[0-9]*|hd[a-d]|scd[0-9]*|sr[0-9]*) DISK=$oneDRVNAME;;
+*) DISK=`echo "$oneDRVNAME" | sed 's#[0-9]*$##'`;;
+esac
+
+if test -f /sys/block/$oneDRVNAME/size; then
+read SIZE </sys/block/$oneDRVNAME/size
+DESCR=`probedisk2 | grep "^/dev/${oneDRVNAME}|" | cut -f3 -d'|'`
+SUMMARY1="<Summary>$DESCR"
+
+elif test -f /sys/block/$DISK/$oneDRVNAME/size; then
+read SIZE </sys/block/$DISK/$oneDRVNAME/size
+FSTYPE=`probepart -d/dev/$oneDRVNAME |cut -f2 -d'|'`
+SUMMARY1="<Summary>Filesystem: $FSTYPE"
+
+else
+SIZE=0
+DESCR=`probedisk2 | grep "^/dev/${DISK}" | cut -f3 -d'|'`
+SUMMARY1="<Summary>$DESCR"
+
+fi
+    #TODO: if no media inseted, the files inside do not get updated at k3.9.9
+    #SIZE should be 0 but stays at last known size.
+SIZE=$((SIZE/2))
+_format_size $SIZE
+
+echo "<?xml version=\"1.0\"?>
+<AppInfo>
+ $SUMMARY1 Size: $SIZE</Summary>
+" >/tmp/AppInfo.xml
+sed -n '/<About>/,/<\/AppInfo>/ p' $PUP_EVENT_DIR/drive_${oneDRVNAME}/AppInfo.xml >>/tmp/AppInfo.xml
+test $? = 0 && cp $VERB -f /tmp/AppInfo.xml $PUP_EVENT_DIR/drive_${oneDRVNAME}/
+
+#if test -f $PUP_EVENT_DIR/drive_${oneDRVNAME}/AppInfo.xml; then
+#sed -i "s%<Summary>.*</Summary>%<Summary>Filesystem: $FSTYPE Size: $SIZE</Summary>%" $PUP_EVENT_DIR/drive_${oneDRVNAME}/AppInfo.xml
+#else
+#false
+#fi
+}
+
 if test  "$DRV_CATEGORY" = optical; then
+ _update_appinfo_no_media
 xmessage -title "$MY_SELF" "Please insert a CD/DVD first."
 elif test "$DRV_CATEGORY" = floppy; then
+ _update_appinfo_no_media
 xmessage -title "$MY_SELF" "Please insert a floppy first."
 else
 xmessage -title "PMOUNT LAST FALLBACK" -buttons "Pmount:100,Quit:101" "NOTICE : Encountered unknown situation..
