drive_all : Bulk Maintanance Replacement of today.

diff --git a/woof-code/rootfs-skeleton/usr/local/bin/drive_all b/woof-code/rootfs-skeleton/usr/local/bin/drive_all
--- a/woof-code/rootfs-skeleton/usr/local/bin/drive_all
+++ b/woof-code/rootfs-skeleton/usr/local/bin/drive_all
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/ash
 #(c) Copyright 2008 Barry Kauler, puppylinux.com
 #2008 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #/sbin/pup_event_frontend_d creates a desktop icon and copy of this script for each drive, ex:
@@ -12,162 +12,84 @@
 #v411 added 'quiet' option for vfat, suppresses error msg when file attribs not preserved on copy.
 #w002 left click to unmount a partition.
 #w476 fix codepage for vfat f.s.
-# 13jun09 by Masaki Shinomiya <shino@pos.to> vfat and so9660 - utf8 option as the default
-# 15jun09 : look up /etc/codepage only for vfat utf8 option
-# 27jun09 : vfat mount options by Masaki Shinomiya <shino@pos.to>
-# 30jun09 I18N
-# 08jul09 looking up ONDRVNAME, ask to remove CD
-# 16jul09 not ask to remove CD, only open tray
-#v424 have added right-click menu item to unmount all partitions (see pup_event_frontend_d)...
-#v424 have removed this dlg box. maybe make it optional in the future...
-#091223 extra check for invalid desktop drive icon.
-#100118 optional defaultcdplayer, defaultdvdplayer.
-#100127 codepage fixes. 100131 iso9660 fix.
-#100706 BK: bug fixes, introduced with i81n support.
-#100719 BK: correct detection of DVD vidoe and launching mediaplayer.
 
-### use pmount.mo
-### also used in /usr/local/bin/drive_all
-m_30="FAILURE! In the case of removable media, the most
-common reason is the media is not currently inserted.
-If so, please remedy."
-m_31="KILL"
-m_32="EXIT"
-m_33="FAILURE!"
-m_34="One or more processes (programs) are currently
-using the partition. Here they are:"
-m_35="If you press the \"${m_31}\" button, Puppy will attempt to
-kill the offending programs for you. Only do this as a
-last resort. "
-m_36="Firstly you should try to close the programs
-manually, so do not press \"${m_31}\"."
-m_37="PLEASE PRESS THE \"${m_32}\" BUTTON!"
-m_38="OK"
-m_39="Remove medium, then press '$m_38'"
-### 50- used only in drive_all
-m_50="Puppy drive manager"
-m_51="/dev/\${ONEDRVNAME} mounted on \${MNTPT}
-is in use by Puppy. You cannot unmount it."
-m_52="NO"
-m_53="Unmount \${ONEDRVNAME}"
-m_54="Unmount all"
-m_55="Do you want to unmount \${ONEDRVNAME}?"
-m_56="It is currently mounted on \${MNTPT}"
-###
-
-# I18N
-LOCALEFILE="pmount.mo"
-# set locale
-# myLOCALE=$LANG # is enough for puppy. but this code is more general.
-for myLOCALE in C $(echo $LANGUAGE|cut -d':' -f1) $LC_ALL $LANG;do :;done   # ex.   ja_JP.UTF-8
-# search locale file
-myLOCALE1=$(echo $myLOCALE|cut -d'.' -f1)       # ex.   ja_JP
-myLOCALE2=$(echo $myLOCALE|cut -d'_' -f1)   # ex.   ja
-LOCALEDIR=/usr/share/locale
-#LOCALEFILE=$(basename $0).mo
-for D in C $myLOCALE2 $myLOCALE1 $myLOCALE
-do
-    F="$LOCALEDIR/$D/LC_MESSAGES/$LOCALEFILE"
-    [ -f "$F" ] && . "$F"
-done
-# end of I18N
-export LANG # need to restart pmount with correct locale
+test -f /etc/rc.d/f4puppy5 && source /etc/rc.d/f4puppy5
 
 #w002 extracted as a func...
 unmount_func() {
- rox -D $MNTPT
+ rox -D "$MNTPT"
  sync
  while [ 1 ];do
-  #unmount nested mounts
-   #LOOPS=`mount | grep -v '/initrd' | grep '^/dev/loop'`
-   #LOOPFILES=`echo "$LOOPS" |rev |cut -f1 -d '+' |rev`
-    #LOOPFILES=`echo "$LOOPS" |sed 's%.* on \(.*\) type [[:alnum:]]* (.*)$%\1%'`
-    LOOPS=`losetup |rev |awk '{print $1}' |rev`
-    LOOPFILES="$LOOPS"
-   for loopfile in $LOOPFILES; do
-    [ "$loopfile" ] || continue
-   loopfile="${loopfile##*/}"
-   LOOPMNTPT="$LOOPMNTPT
-`find $MNTPT -maxdepth 2 -type f -name "$loopfile"`"
-   done
-   for loopmount in $LOOPMNTPT; do
-   [ "$loopmount" ] || continue
-   grepP="${loopmount##*/}"
-   #loopdevice=`mount | grep -m1 -w "${grepP} " |awk '{print $1}'`
-   mountpoint=`busybox mount | grep -m1 -o "${grepP} " |sed 's% $%%'` #|awk '{print $1}'`
-   #[ "$loopdevice" -a -b "$loopdevice" ] && umount $loopdevice
-   [ "$mountpoint" -a -d /mnt/"$mountpoint" ] && umount /mnt/"$mountpoint"
-  done
-  #
-  umount $MNTPT ; umVAL=$?
+  /bin/umount "$MNTPT" ; umVAL=$?
   #fix zombie process prevents partition unmount, invisible to fuser...
   if [ $umVAL -ne 0 ];then
-   ZOMBIES="`ps -H -A | grep '<defunct>' | sed -e 's/  /|/g' | grep -v '|||' | cut -f 1 -d ' ' | tr '\n' ' '`"
-   for ONEZOMBIE in $ZOMBIES
+   ZOMBIES="`/bin/ps -H -A | grep '<defunct>' | sed -e 's/  /|/g' | grep -v '|||' | cut -f 1 -d ' ' | tr '\n' ' '`"
+   for oneZOMBIE in $ZOMBIES
    do
-    echo "Killing parentless zombie process $ONEZOMBIE"
-    kill $ONEZOMBIE
+    echo "Killing parentless zombie process $oneZOMBIE"
+    kill $oneZOMBIE
    done
-   umount $MNTPT 2>/tmp/umount.err; umVAL=$?
+   [ -n "`busybox mount | grep "$MNTPT"`" ] && /bin/umount "$MNTPT" ; umVAL=$?
   fi
   #rare ocassion, partition got unmounted before umount runs above...
   umPATTERN="${MNTPT} "
   [ "`busybox mount | grep "$umPATTERN"`" = "" ] && umVAL=0
   if [ $umVAL -ne 0 ];then
-   ERRORMSG=`cat /tmp/umount.err`
-   rm /tmp/umount.err
-   EXTRAMSG0="`fuser -v -m $MNTPT 2>&1`"
-   #LOOPS=`mount | grep -v '/initrd' | grep '^/dev/loop'`
-   LOOPS=`losetup |rev |awk '{print $1}' |rev`
-   #LOOPFILES=`echo "$LOOPS" |rev |cut -f1 -d '+' |rev`
-   LOOPFILES="$LOOPS"
-   for loopfile in $LOOPFILES; do
-   LOOPMNTPT="$LOOPMNTPT
-`find $MNTPT -maxdepth 2 -type f -name "$loopfile"`"
-   done
+   #EXTRAMSG0="`_command fuser -v -m $MNTPT 2>&1`"
+   fsUSERS=`fuser -m "$MNTPT"`
+   EXTRAMSG0=`for i in $fsUSERS; do ps | grep -w $i | grep -v grep;done`
    if [ "$EXTRAMSG0" = "" ];then
-    gxmessage -bg "#ff8080" -title "$m_50: ERROR" -center "$m_30"
+    xmessage -bg "#ff8080" -title "Puppy drive manager: ERROR" -center "FAILURE! In the case of removable media, the most
+common reason is the media is not currently inserted.
+If so, please remedy."
    else
-    gxmessage -bg "#ff99ff" -title "$m_01" -center -buttons "$m_31":10,"$m_32":20 "$m_33
-$m_34
-$ERRORMSG
+    xmessage -bg "#ff00ff" -title "KILL, KILL..." -center -buttons KILL:10,EXIT:20 "FAILURE! One or more processes (programs) are currently
+using /dev/${oneDRVNAME}. Here they are:
 $EXTRAMSG0
-$LOOPS
 
-$m_35
-$m_36
-$m_37"
-
+If you press the \"KILL\" button, Puppy will attempt to
+kill the offending programs for you. Only do this as a
+last resort. Firstly you should try to close the programs
+manually, so do not press \"KILL\".
+PLEASE PRESS THE \"EXIT\" BUTTON!"
     if [ $? -eq 10 ];then
-     fuser -k -m $MNTPT
+     fuser -k -m "$MNTPT"
      continue
     fi
    fi
   else
-   [ "$DRV_CATEGORY" = "optical" ]  && eject_cd /dev/$ONEDRVNAME
+   [ "`echo "$oneDRVNAME" | grep 'sr[0-9]'`" ] && eject /dev/$oneDRVNAME
   fi
   break
  done
 }
 
-eject_cd ()
-{
-    eject $1 # && gxmessage  -title "$m_50" -center -buttons "$m_38":0 "$m_39" && eject -t $1
-}
 FSTYPE=""
 [ $2 ] && FSTYPE="$2" #see pup_eventd
 
 #extract drive name from end of the script name...
-#note, when click on desktop icon, /root/.pup_event/drive_<ONEDRVNAME> is executed,
-#however a script may run /root/.pup_event/drive_<ONEDRVNAME>/AppRun ...
-#ONEDRVNAME="`echo "${0}" | sed -e 's%/AppRun%%' | rev | cut -f 1 -d '_' | rev`"
-ONEDRVNAME=$(dirname $0|sed -e 's/^.*_//')
+#note, when click on desktop icon, /root/.pup_event/drive_<oneDRVNAME> is executed,
+#however a script may run /root/.pup_event/drive_<oneDRVNAME>/AppRun ...
+
+#oneDRVNAME="`echo "${0}" | sed -e 's%/AppRun%%' | rev | cut -f 1 -d '_' | rev`"
+#echo "oneDRVNAME='$oneDRVNAME'" >&2
+test "`echo "$0" | grep '^/'`" && {
+    _debug "Absolute PATH"
+oneDRVNAME="`echo "${0}" | sed -e 's%/AppRun%%' | rev | cut -f 1 -d '_' | rev`"
+} || {
+    _notice "no absolute PATH"
+    MY_SELF=`realpath "$0"`
+oneDRVNAME="`echo "${MY_SELF}" | sed -e 's%/AppRun%%' | rev | cut -f 1 -d '_' | rev`"
+}
+test "$oneDRVNAME" || _exit 2 "ERROR -- no oneDRVNAME"
+
 if [ "`echo "${1}" | grep 'pmount_'`" != "" ];then #v403 chose pmount from drive icon menu.
  DRV_CATEGORY="`echo -n "${1}" | cut -f 2 -d '_'`"
  if [ "`pidof gtkdialog_pmount`" != "" ];then #if pmount running, kill it.
   killall gtkdialog_pmount 2>/dev/null
   sleep 0.1
  fi
+ echo 79 >&2
  exec pmount ${DRV_CATEGORY}
 fi
 
@@ -177,33 +99,27 @@ if [ "$1" = "eventmanager" ];then #v403 chosen from drive icon menu.
 fi
 
 if [ "$1" = "unmount" ];then #v403 chose unmount from drive icon menu.
- mPATTERN='^/dev/'"$ONEDRVNAME"' '
+ mPATTERN='^/dev/'"$oneDRVNAME"' '
  #MNTPT="`mount | grep "$mPATTERN" | cut -f 3 -d ' '`"
- MNTPT="`df | grep "$mPATTERN" | tr -s ' ' | cut -f 6 -d ' '`"
- #DRV_CATEGORY=$(grep '<Item.option=.pmount_'  "/root/.pup_event/drive_$ONEDRVNAME/AppInfo.xml"| sed -e 's/^.*Item.option=.pmount_//' -e 's/.[ ].*$//')
- DRV_CATEGORY=""
- PROBEDISK="probedisk2"
- which $PROBEDISK >/dev/null || PROBEDISK="probedisk"
- which $PROBEDISK >/dev/null &&  DRV_CATEGORY=$($PROBEDISK|grep "^/dev/$ONEDRVNAME|" | cut -d'|' -f 2)
- echo "$DRV_CATEGORY" | grep '^cd' && DRV_CATEGORY="optical"
- [ "$MNTPT" = "" ] && [ "$DRV_CATEGORY" = "optical" ] && eject_cd /dev/$ONEDRVNAME
+ MNTPT="`/bin/df | grep "$mPATTERN" | tr -s ' ' | cut -f 6 -d ' '`"
  [ "$MNTPT" = "" ] && exit #precaution.
  if [ "$MNTPT" = "/" -o "`echo "$MNTPT" | grep '/initrd/'`" != "" ];then
-  eval m_51=\"$m_51\"
-  gxmessage -bg "#ff8080" -title "$m_50" -center "$m_51"
-  exit
+  xmessage -bg "#ff8080" -title "Puppy drive manager" -center "/dev/${oneDRVNAME} mounted on ${MNTPT}
+is in use by Puppy. You cannot unmount it."
+  exit 1
  fi
  unmount_func
- exit
+ exit $?
 fi
 
 #v424 have added right-click menu item to unmount all partitions (see pup_event_frontend_d)...
 if [ "$1" = "unmountall" ];then
- for MNTPT in `mount | grep '^/dev/' | grep -vE '^/dev/loop|^/dev/ram' | cut -f 3 -d ' ' | grep -v '^/initrd/' | grep -v '^/$' | tr '\n' ' '`
+ for MNTPT in `mount | grep '^/dev/' | grep -vE '^/dev/loop|^/dev/ram|^/dev/nbd|^/dev/md|^/dev/mtd' | cut -f 3 -d ' ' | grep -vE '^/initrd/|^/$'`
  do
   unmount_func
+  STATUS=$((STATUS+$?))
  done
- exit
+ exit $STATUS
 fi
 
 #w002 left-mouse-click to unmount...
@@ -217,23 +133,23 @@ fi
 #v424 have removed this dlg box. maybe make it optional in the future...
 #if [ $2 ];then
 # #if partition already mounted, offer to unmount it...
-# mPATTERN='^/dev/'"$ONEDRVNAME"' '
+# mPATTERN='^/dev/'"$oneDRVNAME"' '
 # MNTPT="`df | grep "$mPATTERN" | tr -s ' ' | cut -f 6 -d ' '`"
 # if [ "$MNTPT" != "" ];then
 #  if [ "$MNTPT" != "/" -a "`echo "$MNTPT" | grep '/initrd/'`" = "" ];then
 #   #it is allowed to be unmounted (not in use by woof)...
-#   xmessage -bg "orange" -title "Puppy drive manager" -center -buttons " NO :11,Unmount ${ONEDRVNAME}:10,Unmount all:12" "Do you want to unmount ${ONEDRVNAME}?
+#   xmessage -bg "orange" -title "Puppy drive manager" -center -buttons " NO :11,Unmount ${oneDRVNAME}:10,Unmount all:12" "Do you want to unmount ${oneDRVNAME}?
 #It is currently mounted on ${MNTPT}"
 #   UMNTFLG=$?
 #   if [ $UMNTFLG -eq 10 ];then
 #    unmount_func
-#   exit
+#       exit
 #   fi
 #   if [ $UMNTFLG -eq 12 ];then
 #    for MNTPT in `mount | grep '^/dev/' | grep -vE '^/dev/loop|^/dev/ram' | cut -f 3 -d ' ' | grep -v '^/initrd/' | grep -v '^/$' | tr '\n' ' '`
-#   do
-#    unmount_func
-#   done
+#       do
+#        unmount_func
+#       done
 #    exit
 #   fi
 #  fi
@@ -253,11 +169,12 @@ DRV_CATEGORY="${1}"
 
 #if ICONDESK=false (see /etc/eventmanager and /sbin/pup_eventd) then there will only
 #be one icon on the desktop, labelled 'drives' and handler script is /usr/local/bin/drive_drives
-if [ "$ONEDRVNAME" = "drives" ];then
+if [ "$oneDRVNAME" = "drives" ];then
  if [ "`pidof gtkdialog_pmount`" != "" ];then #if pmount running, kill it.
   killall gtkdialog_pmount 2>/dev/null
   sleep 0.1
  fi
+ echo 164 >&2
  exec pmount $DRV_CATEGORY
 fi
 
@@ -270,123 +187,89 @@ if [ "$AUTOTARGET" = "false" ];then
   killall gtkdialog_pmount 2>/dev/null
   sleep 0.1
  fi
+ echo 177 >&2
  exec pmount $DRV_CATEGORY
 fi
 
 #oh, now have to analyse the media, decide what app to run...
-dPATTERN='^/dev/'"$ONEDRVNAME"' '
-if [ "$ONEDRVNAME" = "sr0" -o "$ONEDRVNAME" = "sr1" ];then
- srPATTERN='^/dev/'"$ONEDRVNAME"' '
+if [ "`echo "$oneDRVNAME" | grep 'sr[0-9]'`" ];then
+ srPATTERN='^/dev/'"$oneDRVNAME"' '
  if [ "`busybox mount | grep "$srPATTERN"`" = "" ];then
-  cddetect -q -d/dev/${ONEDRVNAME}
+  cddetect -q -d/dev/${oneDRVNAME}
   RETVAL=$?
   case $RETVAL in
   3) #iso file: normal data cd.
    true
    ;;
   1) #audio
-   ln -snf /dev/${ONEDRVNAME} /dev/cdrom
-   if [ -f /usr/local/bin/defaultcdplayer ];then #100118
-    exec defaultcdplayer
-   else
-    exec defaultmediaplayer cdda://
-   fi
+   ln -snf /dev/${oneDRVNAME} /dev/cdrom
+   exec defaultmediaplayer cdda://dev/cdrom
    ;;
   5) #video dvd
-   ln -snf /dev/${ONEDRVNAME} /dev/dvd
-   [ -f /usr/local/bin/defaultdvdplayer ] && exec defaultdvdplayer
-   [ "`grep 'mplayer' /usr/local/bin/defaultmediaplayer`" != "" ] && exec defaultmediaplayer dvdnav:// #100719
-   exec defaultmediaplayer dvd://
+   ln -snf /dev/${oneDRVNAME} /dev/dvd
+   exec defaultmediaplayer dvd://dev/dvd
    ;;
   0) #failed to detect type.
    #cddetect does not work properly for dvd's, try something else...
-   #100719 properly detect dvd video...
-   if [ "`df | grep "$dPATTERN"`" == "" ];then #only test if not mounted.
-    FLAGDVDVIDEO="`dvd+rw-mediainfo /dev/${ONEDRVNAME} | grep 'Mounted Media: .* DVD-ROM'`"
-    if "$FLAGDVDVIDEO" == "" ];then
-     #mount and look for 'video_ts' directory (dir should contain file video_ts.ifo)...
-     mkdir -p /mnt/${ONEDRVNAME}
-     mount -t iso9660 /dev/${ONEDRVNAME} /mnt/${ONEDRVNAME}
-     if [ $? -eq 0 ];then
-      [ -d /mnt/${ONEDRVNAME}/video_ts -o -d /mnt/${ONEDRVNAME}/VIDEO_TS ] && FLAGDVDVIDEO="yes"
-      umount /mnt/${ONEDRVNAME}
-     fi
-    fi
-    if [ "$FLAGDVDVIDEO" != "" ];then
-     ln -snf /dev/${ONEDRVNAME} /dev/dvd
-     [ -f /usr/local/bin/defaultdvdplayer ] && exec defaultdvdplayer
-     [ "`grep 'mplayer' /usr/local/bin/defaultmediaplayer`" != "" ] && exec defaultmediaplayer dvdnav://
-     exec defaultmediaplayer dvd://
-    fi
+   if [ "`dvd+rw-mediainfo /dev/sr0 | grep 'Mounted Media: .* DVD-ROM'`" != "" ];then
+    ln -snf /dev/${oneDRVNAME} /dev/dvd
+    exec defaultmediaplayer dvd://dev/dvd
    fi
    ;;
   esac
  fi
- FSTYPE="iso9660"
+ FSTYPE=`guess_fstype /dev/$oneDRVNAME`
+ test "$FSTYPE" || FSTYPE=iso9660
+ test "$FSTYPE" = "unknown" && FSTYPE=iso9660
 fi
-
+echo 212 >&2
 #if dropped down here, it is likely to be a data partition...
 #if it is a mountable partition then mount and open with rox. If already mntd then open in rox...
 #if [ "$ICONPARTITIONS" = "true" ];then
 if [ "$FSTYPE" != "" ];then
- if [ "`df | grep "$dPATTERN"`" = "" ];then
+ dPATTERN='^/dev/'"$oneDRVNAME"' '
+ if [ "`/bin/df | grep "$dPATTERN"`" = "" ];then
   #not mounted...
-  mkdir -p /mnt/$ONEDRVNAME
+  #test -d /mnt/$oneDRVNAME || mkdir -p /mnt/$oneDRVNAME
   case $FSTYPE in
    ntfs)
     #'mount' is a script that takes care of mounting ntfs...
-    mount -t ntfs /dev/$ONEDRVNAME /mnt/$ONEDRVNAME
+    /bin/mount -t ntfs "/dev/$oneDRVNAME" "/mnt/$oneDRVNAME"
     RETVAL1=$?
     ;;
-   vfat|FAT*|Fat*|fat*)
+   vfat)
     #w476 modify codepage and iocharset (note: this code also in /usr/sbin/pmount)...
     #note, could also set iocharset=iso8859-2 (default: codepage=437, iocharset=iso8859-1)
-    # 27jul09 lookup /etc/codepage and LANG by Masaki Shinomiya <shino@pos.to>
-    NLS_PARAM=""
-    if [ -f /etc/codepage ]; then #100127...
-     grep -q -i '850' /etc/codepage && [ "$(echo $LANG|cut -d'.' -f1)" != "en_US" ] && NLS_PARAM=",codepage=850"
-     grep -q -i '852' /etc/codepage && NLS_PARAM=",codepage=852,iocharset=iso8859-2"
+    NLS_PARAM=''
+    if [ -f /etc/keymap ];then #set in /etc/rc.d/rc.country
+     KEYMAP="`cat /etc/keymap | cut -f 1 -d '.'`"
+     case $KEYMAP in
+      de|be|br|dk|es|fi|fr|it|no|se|pt)
+       NLS_PARAM=',codepage=850'
+      ;;
+      slovene|croat|hu101|hu|cz-lat2|pl|ro_win)
+       NLS_PARAM=',codepage=852,iocharset=iso8859-2'
+      ;;
+     esac
     fi
-    echo $LANG | grep -q -i '\.utf' && NLS_PARAM="$NLS_PARAM,utf8"
-    mount -t vfat -o shortname=mixed,quiet${NLS_PARAM} /dev/$ONEDRVNAME /mnt/$ONEDRVNAME #v411
-    RETVAL1=$?
-    ;;
-   #100127 not certain about this (inserted by shinobar)... 100131 shinobar informs needed for cds created in windows...
-   iso9660)
-    mount -t $FSTYPE -o iocharset=utf8 /dev/$ONEDRVNAME /mnt/$ONEDRVNAME
+    /bin/mount -t vfat -o shortname=mixed,quiet${NLS_PARAM} "/dev/$oneDRVNAME" "/mnt/$oneDRVNAME" #v411
     RETVAL1=$?
     ;;
    *)
-    mount -t $FSTYPE /dev/$ONEDRVNAME /mnt/$ONEDRVNAME
+    /bin/mount -t $FSTYPE "/dev/$oneDRVNAME" "/mnt/$oneDRVNAME"
     RETVAL1=$?
     ;;
   esac
-  if [ $RETVAL1 -eq 0 ];then
-   exec rox -x /mnt/$ONEDRVNAME -d /mnt/$ONEDRVNAME
-  else
-   #091223 why did it fail?
-   dd if=/dev/$ONEDRVNAME of=/dev/null bs=512 count=1 > /dev/null 2>&1
-   if [ $? -ne 0 ];then
-    #/tmp/pup_event_frontend_block_request is used in /sbin/pup_event_frontend_d to refresh drv...
-    case $ONEDRVNAME in
-     mmcblk*)
-      yONEDRV="`echo -n "$ONEDRVNAME" | cut -c 1-7`"
-     ;;
-     *)
-      yONEDRV="`echo -n "$ONEDRVNAME" | cut -c 1-3`"
-     ;;
-    esac
-    echo "$yONEDRV" > /tmp/pup_event_frontend_block_request
-   fi
-  fi
+  #[ $RETVAL1 -eq 0 ] && exec rox -x "/mnt/$oneDRVNAME" -d "/mnt/$oneDRVNAME"
+  [ $RETVAL1 -eq 0 ] && exit $RETVAL1
  else
   #mounted...
-  MNTPT="`df | grep "$dPATTERN" | tr -s ' ' | cut -f 6 -d ' '`"
+  MNTPT="`/bin/df | grep "$dPATTERN" | tr -s ' ' | cut -f 6 -d ' '`"
   if [ -h /mnt/home ];then
    [ "`readlink /mnt/home`" = "$MNTPT" ] && MNTPT="/mnt/home"
   fi
-  #exec rox -x /mnt/$ONEDRVNAME -d /mnt/$ONEDRVNAME
-  exec rox -x $MNTPT -d $MNTPT
+  #exec rox -x /mnt/$oneDRVNAME -d /mnt/$oneDRVNAME
+  exec rox -x "$MNTPT" -x "${MNTPT%/*}" -d "$MNTPT"
  fi
 fi
 
@@ -398,7 +281,7 @@ if [ "`pidof gtkdialog_pmount`" != "" ];then #if pmount running, kill it.
  killall gtkdialog_pmount 2>/dev/null
  sleep 0.1
 fi
-
+echo 271 >&2
 exec pmount ${DRV_CATEGORY}
 
 ###END###
