/usr/sbin/,/usr/local/bin/: Add VERB switch to mkdir et al. Change source /file to . /file .

diff --git a/woof-code/rootfs-skeleton/usr/local/bin/Pudd b/woof-code/rootfs-skeleton/usr/local/bin/Pudd
--- a/woof-code/rootfs-skeleton/usr/local/bin/Pudd
+++ b/woof-code/rootfs-skeleton/usr/local/bin/Pudd
@@ -19,9 +19,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -115,7 +115,7 @@ FOUNDZIP=""
 # #load ide-floppy.o to access atapi zip drive...
 # ZIPMODULE="`lsmod | grep "ide-floppy"`"
 # if [ "$ZIPMODULE" = "" ];then
-#  modprobe ide-floppy
+#  modprobe $Q $VERB ide-floppy
 # fi
 #fi
 
@@ -161,7 +161,7 @@ while [ 1 ];do #first loop.
     sync
     umount -r $ONEUSBMNT 2> /tmp/umounterr.txt
    done
-   modprobe -r usb-storage
+   modprobe $Q $VERB -r usb-storage
    BLURB2="...HOWEVER, Puppy detects an error probing the USB partitions!!!"
   fi
   BKCOLOR='#ffc0c0'
@@ -265,9 +265,9 @@ case ${RETVAL} in
       sync
       umount $ONEUSBMNT 2> /tmp/umounterr.txt
      done
-     modprobe -r usb-storage
+     modprobe $Q $VERB -r usb-storage
      xmessage -bg "#ff00ff" -title "Puppy universal dd: probe USB" -center -buttons "" "Wait awhile for the usb-storage driver to reload..." &
-     modprobe usb-storage
+     modprobe $Q $VERB usb-storage
      killall xmessage
      ;;
    15)# probe ZIP
@@ -284,17 +284,17 @@ case ${RETVAL} in
     xmessage -bg "#ffe0e0" -center -name "Pudd" -title "Puppy universal dd: probe ZIP" -buttons "Parallel port ZIP":14,"IDE (internal) ZIP":15,"none of these:10" "Please choose what type of ZIP drive you have..."
     RETVAL=$?
     if [ $RETVAL -eq 14 ];then
-     modprobe -r imm #won't be loaded first time probably.
+     modprobe $Q $VERB -r imm #won't be loaded first time probably.
      sleep 1
-     modprobe imm
+     modprobe $Q $VERB imm
      if [ $? -eq 0 ];then
       ZIPLOADED="imm"
      fi
     fi
     if [ $RETVAL -eq 15 ];then
-     modprobe -r ide-floppy
+     modprobe $Q $VERB -r ide-floppy
      sleep 1
-     modprobe ide-floppy
+     modprobe $Q $VERB ide-floppy
      if [ $? -eq 0 ];then
       ZIPLOADED="ide-floppy"
      fi
@@ -435,7 +435,7 @@ if [ "$SOURCECHOICE" = "file" ];then
    gunzip -c $SOURCEPART > $UNCOMPRPATHNAME
    if [ ! $? -eq 0 ];then
     xmessage -bg "#ff0000" -center "Error uncompressing $SOURCEPART. Click button to quit..."
-    rm -f $UNCOMPRPATHNAME
+    rm $VERB -f $UNCOMPRPATHNAME
     exit
    fi
    WARNING1="${WARNING1}WARNING2: $SOURCEPART file has been uncompressed as $UNCOMPRPATHNAME.
@@ -525,7 +525,7 @@ case ${RETVAL} in
      defaulthtmlviewer file:///usr/share/doc/Pudd.htm &
      ;;
    13)# EXIT
-     rm -f $UNCOMPRPATHNAME
+     rm $VERB -f $UNCOMPRPATHNAME
      exit
      ;;
    16)# fdisk
@@ -537,7 +537,7 @@ case ${RETVAL} in
      fi
      ;;
    *)
-    rm -f $UNCOMPRPATHNAME
+    rm $VERB -f $UNCOMPRPATHNAME
     exit
     ;;
 esac
@@ -690,7 +690,7 @@ is zeroised. This involves temporarily mounting it on /mnt/tmp,
 writing zeroes to the unused areas, then unmounting it.
 Would you like to do this size optimisation?" 0 0
         if [ $? -eq 0 ];then
-         mkdir -p /mnt/tmp 2>$ERR
+         mkdir $VERB -p /mnt/tmp 2>$ERR
          if [ ! "`echo "$SOURCEFS" | grep -Ei "ext[2-4]"`" = "" ];then
           APPLYFS="`echo -n "$SOURCEFS" | tr "E" "e"`"
          else
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/bones b/woof-code/rootfs-skeleton/usr/local/bin/bones
--- a/woof-code/rootfs-skeleton/usr/local/bin/bones
+++ b/woof-code/rootfs-skeleton/usr/local/bin/bones
@@ -25,9 +25,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -76,9 +76,9 @@ if [ -s ../${PROJECTNAME}-bones/commits ];then
  NEWDELTAS="`find ./ -maxdepth 1 -type f -name "${PROJECTNAME}-2*-2*.delta"`"
  OLDDELTAS="`find ./ -maxdepth 1 -type f -name "${PROJECTNAME}-2[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].delta"`"
  if [ "$OLDDELTAS" != "" ];then
-  rm -f "${PROJECTNAME}-2*.delta" 2>/dev/null
-  rm -f "${PROJECTNAME}-LATEST.tar.gz" 2>/dev/null
-  rm -f "${PROJECTNAME}-PREVIOUS.tar.gz" 2>/dev/null
+  rm $VERB -f "${PROJECTNAME}-2*.delta" 2>/dev/null
+  rm $VERB -f "${PROJECTNAME}-LATEST.tar.gz" 2>/dev/null
+  rm $VERB -f "${PROJECTNAME}-PREVIOUS.tar.gz" 2>/dev/null
   grep -v 'delta|' commits > /tmp/bones-commits
   grep -v 'LATEST' /tmp/bones-commits > /tmp/bones-commits2
   grep -v 'PREVIOUS' /tmp/bones-commits2 > commits
@@ -129,7 +129,7 @@ check_func() { #091210
     echo -n "Press ENTER only to delete it (any other key to keep): "
     read keepit
     if [ "$keepit" = "" ];then
-     rm -f $ONEDELTA
+     rm $VERB -f $ONEDELTA
      echo "...deleted $ONEDELTA"
     fi
     CHECKFLAG=1
@@ -162,7 +162,7 @@ check_func() { #091210
    echo -n "Press ENTER only to delete it (any other key to keep): "
    read keepit
    if [ "$keepit" = "" ];then
-    rm -f $REFERENCETARBALL
+    rm $VERB -f $REFERENCETARBALL
     echo "...deleted $REFERENCETARBALL"
    fi
    CHECKFLAG=1
@@ -234,7 +234,7 @@ rebuild_func() {
  #091210 ALLDATES now has two dates in it ex: 200912345678-2009124567890
  ALLDATES="`find ./ -maxdepth 1 -type f -name "${PROJECTNAME}-2*.delta" | rev | cut -f 2-9 -d '.' | cut -f 1,2 -d '-' | rev | sort --numeric-sort --key=1,1 --field-separator='-'`"
  REFERENCETARBALL="`find ./ -maxdepth 1 -type f -name "${PROJECTNAME}-2*REFERENCE.tar.gz"`"
- cp -f $REFERENCETARBALL PREVIOUS.tar.gz
+ cp $VERB -f $REFERENCETARBALL PREVIOUS.tar.gz
  PREVFIRST="";PREVSECOND=""
  for ONEDATE in $ALLDATES
  do
@@ -244,28 +244,28 @@ rebuild_func() {
   if [ "$PREVSECOND" ];then
    if [ "$PREVSECOND" != "$FIRSTDATE" ];then
     echo "ERROR! There seems to be a missing .delta file."
-    [ -f LATEST.tar.gz ] && rm -f LATEST.tar.gz
-    [ -f PREVIOUS.tar.gz ] && rm -f PREVIOUS.tar.gz
+    [ -f LATEST.tar.gz ] && rm $VERB -f LATEST.tar.gz
+    [ -f PREVIOUS.tar.gz ] && rm $VERB -f PREVIOUS.tar.gz
     return 1
    fi
   fi
-  [ -f LATEST.tar.gz ] && mv -f LATEST.tar.gz PREVIOUS.tar.gz
+  [ -f LATEST.tar.gz ] && mv $VERB -f LATEST.tar.gz PREVIOUS.tar.gz
   xdelta3 -d -s PREVIOUS.tar.gz $DELTAFILE LATEST.tar.gz
   sync
   PREVFIRST="$FIRSTDATE"
   PREVSECOND="$SECONDDATE"
  done
  echo
- mv -f PREVIOUS.tar.gz ${PROJECTNAME}-PREVIOUS.tar.gz
- mv -f LATEST.tar.gz ${PROJECTNAME}-LATEST.tar.gz
+ mv $VERB -f PREVIOUS.tar.gz ${PROJECTNAME}-PREVIOUS.tar.gz
+ mv $VERB -f LATEST.tar.gz ${PROJECTNAME}-LATEST.tar.gz
 } #end rebuild_func
 
 rebuild_date_func() { #called from diff_func.
  #passed param is a date. create a tarball for this date.
  #current dir must be ${PROJECTNAME}-bones
  echo "Building tarball for ${1}..."
- rm -f PREVIOUS.tar.gz 2>/dev/null
- rm -f LATEST.tar.gz 2>/dev/null
+ rm $VERB -f PREVIOUS.tar.gz 2>/dev/null
+ rm $VERB -f LATEST.tar.gz 2>/dev/null
  DATENUMERIC=`echo -n "${1}" | cut -c 1-14` #may have $branch on end.
  #ALLDATES has two dates in it ex: 200912345678-2009124567890
  ALLDATES="`find ./ -maxdepth 1 -type f -name "${PROJECTNAME}-2*.delta" | rev | cut -f 2-9 -d '.' | cut -f 1,2 -d '-' | rev | sort --numeric-sort --key=1,1 --field-separator='-'`"
@@ -277,7 +277,7 @@ rebuild_date_func() { #called from diff_func.
   echo "$ALLDATES" | grep "^${ONEDATE}" >> /tmp/bones-zzz
   if [ ${DATENUMERIC} -gt ${ONEDATE} ];then
    if [ -f archive/${PROJECTNAME}-${ONEDATE}.tar.gz ];then
-    cp -f archive/${PROJECTNAME}-${ONEDATE}.tar.gz PREVIOUS.tar.gz
+    cp $VERB -f archive/${PROJECTNAME}-${ONEDATE}.tar.gz PREVIOUS.tar.gz
     ALLDATES="`cat /tmp/bones-zzz | sort --numeric-sort --key=1,1 --field-separator='-'`"
     break
    fi
@@ -285,7 +285,7 @@ rebuild_date_func() { #called from diff_func.
  done
  if [ ! -f PREVIOUS.tar.gz ];then #start at the beginning...
   REFERENCETARBALL="`find ./ -maxdepth 1 -type f -name "${PROJECTNAME}-2*REFERENCE.tar.gz"`"
-  cp -f $REFERENCETARBALL PREVIOUS.tar.gz
+  cp $VERB -f $REFERENCETARBALL PREVIOUS.tar.gz
  fi
  PREVFIRST="";PREVSECOND=""
  for ONEDATE in $ALLDATES
@@ -297,25 +297,25 @@ rebuild_date_func() { #called from diff_func.
   if [ "$PREVSECOND" ];then
    if [ "$PREVSECOND" != "$FIRSTDATE" ];then
     echo "ERROR! There seems to be a missing .delta file."
-    [ -f LATEST.tar.gz ] && rm -f LATEST.tar.gz
-    [ -f PREVIOUS.tar.gz ] && rm -f PREVIOUS.tar.gz
+    [ -f LATEST.tar.gz ] && rm $VERB -f LATEST.tar.gz
+    [ -f PREVIOUS.tar.gz ] && rm $VERB -f PREVIOUS.tar.gz
     return 1
    fi
   fi
-  [ -f LATEST.tar.gz ] && mv -f LATEST.tar.gz PREVIOUS.tar.gz
+  [ -f LATEST.tar.gz ] && mv $VERB -f LATEST.tar.gz PREVIOUS.tar.gz
   xdelta3 -d -s PREVIOUS.tar.gz $DELTAFILE LATEST.tar.gz
   sync
   PREVFIRST="$FIRSTDATE"
   PREVSECOND="$SECONDDATE"
   if [ "$SECONDDATEFULL" = "${1}" ];then
-   rm -f PREVIOUS.tar.gz
-   mkdir -p archive
-   mv -f LATEST.tar.gz archive/${PROJECTNAME}-${1}.tar.gz
+   rm $VERB -f PREVIOUS.tar.gz
+   mkdir $VERB -p archive
+   mv $VERB -f LATEST.tar.gz archive/${PROJECTNAME}-${1}.tar.gz
    return 0 #have reached required date.
   fi
  done
- rm -f PREVIOUS.tar.gz
- rm -f LATEST.tar.gz
+ rm $VERB -f PREVIOUS.tar.gz
+ rm $VERB -f LATEST.tar.gz
  echo "...error."
  return 1
 } #end rebuild_date_func
@@ -332,7 +332,7 @@ save_func() {
  read COMMENT
  CURRDATE="`date +%Y%m%d%H%M%S`"
  #create a tarball of project...
- mkdir ../${PROJECTNAME}-bones/${PROJECTNAME}-LATEST${branch}
+ mkdir $VERB ../${PROJECTNAME}-bones/${PROJECTNAME}-LATEST${branch}
  echo "Checking in..."
  for ONEFILE in `cat ../${PROJECTNAME}-bones/filelist`
  do
@@ -341,10 +341,10 @@ save_func() {
   echo -n "$ONEFILE "
   ONEDIR="`dirname ${ONEFILE}`"
   if [ "$ONEDIR" != "." ];then
-   mkdir -p ../${PROJECTNAME}-bones/${PROJECTNAME}-LATEST${branch}/${ONEDIR}
-   cp -a ${ONEFILE} ../${PROJECTNAME}-bones/${PROJECTNAME}-LATEST${branch}/${ONEDIR}/ 2>/dev/null
+   mkdir $VERB -p ../${PROJECTNAME}-bones/${PROJECTNAME}-LATEST${branch}/${ONEDIR}
+   cp $VERB -a ${ONEFILE} ../${PROJECTNAME}-bones/${PROJECTNAME}-LATEST${branch}/${ONEDIR}/ 2>/dev/null
   else
-   cp -a ${ONEFILE} ../${PROJECTNAME}-bones/${PROJECTNAME}-LATEST${branch}/ 2>/dev/null
+   cp $VERB -a ${ONEFILE} ../${PROJECTNAME}-bones/${PROJECTNAME}-LATEST${branch}/ 2>/dev/null
   fi
  done
  echo
@@ -353,14 +353,14 @@ save_func() {
  #get date of last save... note, ALLDATES ex line: 20091234567890-20091234567890$branch
  ALLDATES="`find ./ -maxdepth 1 -type f -name "${PROJECTNAME}-2*.delta" | rev | cut -f 2-9 -d '.' | cut -f 1,2 -d '-' | rev | sort --numeric-sort --key=1,1 --field-separator='-'`"
  PREVSAVEDATE="`echo -n "$ALLDATES" | tail -n 1 | cut -f 2 -d '-' | cut -c 1-14`"
- [ -f ${PROJECTNAME}-LATEST${branch}.tar.gz ] && mv -f ${PROJECTNAME}-LATEST${branch}.tar.gz ${PROJECTNAME}-PREVIOUS${branch}.tar.gz
- tar -c -f ${PROJECTNAME}-LATEST${branch}.tar ${PROJECTNAME}-LATEST${branch}/
+ [ -f ${PROJECTNAME}-LATEST${branch}.tar.gz ] && mv $VERB -f ${PROJECTNAME}-LATEST${branch}.tar.gz ${PROJECTNAME}-PREVIOUS${branch}.tar.gz
+ tar $VERB -c -f ${PROJECTNAME}-LATEST${branch}.tar ${PROJECTNAME}-LATEST${branch}/
  gzip ${PROJECTNAME}-LATEST${branch}.tar
  sync
- rm -rf ${PROJECTNAME}-LATEST${branch}
+ rm $VERB -rf ${PROJECTNAME}-LATEST${branch}
  #now create a delta (unless its the first save)...
  if [ ! -f ${PROJECTNAME}-PREVIOUS${branch}.tar.gz ];then
-  cp -f ${PROJECTNAME}-LATEST${branch}.tar.gz ${PROJECTNAME}-${CURRDATE}REFERENCE${branch}.tar.gz
+  cp $VERB -f ${PROJECTNAME}-LATEST${branch}.tar.gz ${PROJECTNAME}-${CURRDATE}REFERENCE${branch}.tar.gz
   MD5SUM="`md5sum ${PROJECTNAME}-${CURRDATE}REFERENCE${branch}.tar.gz | cut -f 1 -d ' '`"
   REFERENCETARBALL="`find ./ -maxdepth 1 -type f -name "${PROJECTNAME}-2*REFERENCE.tar.gz"`"
   if [ "$REFERENCETARBALL" ];then
@@ -409,7 +409,7 @@ add_func() {
  if [ "$NEWFLAG" = "good" ];then
   echo "$NEWFILE" >> ../${PROJECTNAME}-bones/filelist
   sort -u ../${PROJECTNAME}-bones/filelist > /tmp/bones-filelist
-  mv -f /tmp/bones-filelist ../${PROJECTNAME}-bones/filelist
+  mv $VERB -f /tmp/bones-filelist ../${PROJECTNAME}-bones/filelist
   echo "OK: '$NEWFILE' added to ../${PROJECTNAME}-bones/filelist"
  else
   echo
@@ -458,9 +458,9 @@ upload_func() {
 download_func() {
  cd ../${PROJECTNAME}-bones
  touch /tmp/bones-commits-previous
- [ -f commits ] && cp -f commits /tmp/bones-commits-previous
+ [ -f commits ] && cp $VERB -f commits /tmp/bones-commits-previous
  touch /tmp/bones-filelist-previous
- [ -f filelist ] && cp -f filelist /tmp/bones-filelist-previous
+ [ -f filelist ] && cp $VERB -f filelist /tmp/bones-filelist-previous
  #download everything...
  download_url="`echo -n "$download_url" | sed -e 's%$%/%' -e 's%//$%/%'`"
  #wildcard only works for ftp download...
@@ -472,9 +472,9 @@ download_func() {
  wget --no-clobber ${SECURITY} ${download_url}setup
  #if these already exist, they get saved with .1 extension...
  #but, move them aside first...
- mkdir -p archive
- mv -f commits archive/commits 2>/dev/null
- mv -f filelist archive/filelist 2>/dev/null
+ mkdir $VERB -p archive
+ mv $VERB -f commits archive/commits 2>/dev/null
+ mv $VERB -f filelist archive/filelist 2>/dev/null
  wget ${SECURITY} ${download_url}commits
  wget ${SECURITY} ${download_url}filelist
 
@@ -496,7 +496,7 @@ download_func() {
     echo -n "Press ENTER to try again: "
     read tryagain
     [ "$tryagain" != "" ] && break 2
-    rm -f $ONEFILE 2>/dev/null
+    rm $VERB -f $ONEFILE 2>/dev/null
     wget ${SECURITY} ${download_url}${ONEFILE}
    fi
   done
@@ -507,21 +507,21 @@ download_func() {
   echo "You need to run 'bones download' again sometime."
   echo "Restoring repository to before download attempted..."
   #echo restore previous files...
-  cp -f /tmp/bones-commits-previous commits
-  cp -f /tmp/bones-filelist-previous filelist
+  cp $VERB -f /tmp/bones-commits-previous commits
+  cp $VERB -f /tmp/bones-filelist-previous filelist
   for ONECOMMIT in $NEWCOMMITS
   do
    ONEFILE="`echo -n "$ONECOMMIT" | cut -f 1 -d '|'`"
-   [ -f $ONEFILE ] && rm -f $ONEFILE
+   [ -f $ONEFILE ] && rm $VERB -f $ONEFILE
   done
   return 1
  fi
 
  #move aside any user work... note, do not put $branch in here...
- cp -a -f ${PROJECTNAME}-2*${local_username}.delta archive/ 2>/dev/null
- rm -f ${PROJECTNAME}-2*${local_username}.delta 2>/dev/null
- cp -a -f ${PROJECTNAME}-2*${local_username}.tar.gz archive/ 2>/dev/null
- rm -f ${PROJECTNAME}-2*${local_username}.tar.gz 2>/dev/null
+ cp $VERB -a -f ${PROJECTNAME}-2*${local_username}.delta archive/ 2>/dev/null
+ rm $VERB -f ${PROJECTNAME}-2*${local_username}.delta 2>/dev/null
+ cp $VERB -a -f ${PROJECTNAME}-2*${local_username}.tar.gz archive/ 2>/dev/null
+ rm $VERB -f ${PROJECTNAME}-2*${local_username}.tar.gz 2>/dev/null
 
  #need to post-process...
  rebuild_func #create tarball of LATEST and PREVIOUS tarballs
@@ -532,7 +532,7 @@ download_func() {
  fi
  #now update the user's working dir...
  echo "Updating working directory ${CURRDIR}..."
- tar -z -x --strip=1 --directory=${CURRDIR}/ -f ${PROJECTNAME}-LATEST.tar.gz
+ tar $VERB -z -x --strip=1 --directory=${CURRDIR}/ -f ${PROJECTNAME}-LATEST.tar.gz
  sync
  echo "...done"
 
@@ -581,10 +581,10 @@ diff_func() {
   return 1
  fi
  if [ ! -f /var/local/bones/bones-differences-${PROJECTNAME}-${COMBO_STARTDATE}-${COMBO_ENDDATE} ];then
-  mkdir -p archive
+  mkdir $VERB -p archive
   if [ ! -f archive/${PROJECTNAME}-${COMBO_STARTDATE}.tar.gz ];then
    if [ -f ${PROJECTNAME}-${COMBO_STARTDATE}REFERENCE.tar.gz ];then
-    cp ${PROJECTNAME}-${COMBO_STARTDATE}REFERENCE.tar.gz archive/${PROJECTNAME}-${COMBO_STARTDATE}.tar.gz
+    cp $VERB ${PROJECTNAME}-${COMBO_STARTDATE}REFERENCE.tar.gz archive/${PROJECTNAME}-${COMBO_STARTDATE}.tar.gz
    fi
   fi
   if [ ! -f archive/${PROJECTNAME}-${COMBO_STARTDATE}.tar.gz ];then
@@ -597,7 +597,7 @@ diff_func() {
   fi
   #have two tarballs, extract difference data, using ecube's perl script...
   echo "Extracting difference information, using ecube's perl script..."
-  mkdir -p /var/local/bones
+  mkdir $VERB -p /var/local/bones
   cd archive
   bones_diff.pl $PROJECTNAME $COMBO_STARTDATE $COMBO_ENDDATE > /var/local/bones/bones-differences-${PROJECTNAME}-${COMBO_STARTDATE}-${COMBO_ENDDATE}
   cd ..
@@ -687,18 +687,18 @@ user_mod_files_func() { #100322
  echo "Examining project directory to see if you have modified any files"
  echo "since the previous download, please wait..."
  echo -n "" > /var/local/bones/user-different-files
- rm -rf ../${PROJECTNAME}-user-modified-${TODAYDATE} 2>/dev/null
- mkdir ../${PROJECTNAME}-user-modified-${TODAYDATE}
+ rm $VERB -rf ../${PROJECTNAME}-user-modified-${TODAYDATE} 2>/dev/null
+ mkdir $VERB ../${PROJECTNAME}-user-modified-${TODAYDATE}
  #first, copy all project files...
  for ONEOLD in `cat ../${PROJECTNAME}-bones/filelist | tr '\n' ' '`
  do
   [ ! -e $ONEOLD ] && continue
   ONEDIR="`dirname ${ONEOLD}`"
   if [ "$ONEDIR" != "." ];then
-   mkdir -p ../${PROJECTNAME}-user-modified-${TODAYDATE}/${ONEDIR}
-   cp -a ${ONEOLD} ../${PROJECTNAME}-user-modified-${TODAYDATE}/${ONEDIR}/ 2>/dev/null
+   mkdir $VERB -p ../${PROJECTNAME}-user-modified-${TODAYDATE}/${ONEDIR}
+   cp $VERB -a ${ONEOLD} ../${PROJECTNAME}-user-modified-${TODAYDATE}/${ONEDIR}/ 2>/dev/null
   else
-   cp -a ${ONEOLD} ../${PROJECTNAME}-user-modified-${TODAYDATE}/ 2>/dev/null
+   cp $VERB -a ${ONEOLD} ../${PROJECTNAME}-user-modified-${TODAYDATE}/ 2>/dev/null
   fi
  done
  #now compare each file with that in latest archive...
@@ -712,17 +712,17 @@ user_mod_files_func() { #100322
   [ $BKUPFILEDATE -gt $LASTARCHIVEDATE ] && echo "$ONEFILE" >> /var/local/bones/user-different-files
  done
  #now extract only the user-modified files...
- rm -rf ../${PROJECTNAME}-user-modified-${TODAYDATE}
- mkdir ../${PROJECTNAME}-user-modified-${TODAYDATE}
+ rm $VERB -rf ../${PROJECTNAME}-user-modified-${TODAYDATE}
+ mkdir $VERB ../${PROJECTNAME}-user-modified-${TODAYDATE}
  if [ -s /var/local/bones/user-different-files ];then
   for ONEFILE in `cat /var/local/bones/user-different-files | tr '\n' ' '`
   do
   ONEDIR="`dirname ${ONEFILE}`"
   if [ "$ONEDIR" != "." ];then
-   mkdir -p ../${PROJECTNAME}-user-modified-${TODAYDATE}/${ONEDIR}
-   cp -a ${ONEFILE} ../${PROJECTNAME}-user-modified-${TODAYDATE}/${ONEDIR}/ 2>/dev/null
+   mkdir $VERB -p ../${PROJECTNAME}-user-modified-${TODAYDATE}/${ONEDIR}
+   cp $VERB -a ${ONEFILE} ../${PROJECTNAME}-user-modified-${TODAYDATE}/${ONEDIR}/ 2>/dev/null
   else
-   cp -a ${ONEFILE} ../${PROJECTNAME}-user-modified-${TODAYDATE}/ 2>/dev/null
+   cp $VERB -a ${ONEFILE} ../${PROJECTNAME}-user-modified-${TODAYDATE}/ 2>/dev/null
   fi
   done
   echo
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/bootmanager b/woof-code/rootfs-skeleton/usr/local/bin/bootmanager
--- a/woof-code/rootfs-skeleton/usr/local/bin/bootmanager
+++ b/woof-code/rootfs-skeleton/usr/local/bin/bootmanager
@@ -39,9 +39,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -141,7 +141,7 @@ extrasfs_func() {
  #if [ "$PUPMODE" = "77" ];then
  # if [ "$EXTRASFSMNTPT" = "" ];then
  #  xmessage "Make sure Puppy CD inserted in drive /dev/$PDEV1 RIGHT NOW!"
- #  mkdir -p /mnt/$PDEV1
+ #  mkdir $VERB -p /mnt/$PDEV1
  #  mount -t $DEV1FS /dev/$PDEV1 /mnt/$PDEV1 #DEV1FS, PDEV1 are in PUPSTATE.
  #  [ ! $? -eq 0 ] && return 1
  #  EXTRASFSMNTPT="/mnt/$PDEV1"
@@ -159,7 +159,7 @@ extrasfs_func() {
 
  #eliminate other versions from list...
  BASEFIXEDSFSLIST=""
- rm -f /tmp/bootmanager_wrong_sfs_version 2>/dev/null #v423
+ rm $VERB -f /tmp/bootmanager_wrong_sfs_version 2>/dev/null #v423
  for ONESFS in $ALLSFSLIST
  do
   BASEONESFS="`basename $ONESFS`" #100711
@@ -293,7 +293,7 @@ run PupScan (look in the System menu)\" 0 0 8 $MODLIST >/tmp/skiprettags.txt"
  SKIPLIST=" `cat /tmp/skiprettags.txt | tr '\n' ' '`"
  #now update /etc/rc.d/MODULESCONFIG...
  grep -v '^SKIPLIST' /etc/rc.d/MODULESCONFIG > /tmp/MODULESCONFIG
- mv -f /tmp/MODULESCONFIG /etc/rc.d/MODULESCONFIG
+ mv $VERB -f /tmp/MODULESCONFIG /etc/rc.d/MODULESCONFIG
  echo "SKIPLIST='${SKIPLIST}'" >> /etc/rc.d/MODULESCONFIG
 } #end blacklist_func
 
@@ -385,7 +385,7 @@ addlist_func() {
  #ADDLIST=" `cat /tmp/yesrettags.txt | tr '\n' ' '`"
  #now update /etc/rc.d/MODULESCONFIG...
  grep -v '^ADDLIST' /etc/rc.d/MODULESCONFIG > /tmp/MODULESCONFIG
- mv -f /tmp/MODULESCONFIG /etc/rc.d/MODULESCONFIG
+ mv $VERB -f /tmp/MODULESCONFIG /etc/rc.d/MODULESCONFIG
  echo "ADDLIST='${ADDLIST}'" >> /etc/rc.d/MODULESCONFIG
 } #end addlist_func
 
@@ -437,7 +437,7 @@ yeslist_func() {
  #ADDLIST=" `cat /tmp/yesrettags.txt | tr '\n' ' '`"
  #now update /etc/rc.d/MODULESCONFIG...
  grep -v '^ADDLIST' /etc/rc.d/MODULESCONFIG > /tmp/MODULESCONFIG
- mv -f /tmp/MODULESCONFIG /etc/rc.d/MODULESCONFIG
+ mv $VERB -f /tmp/MODULESCONFIG /etc/rc.d/MODULESCONFIG
  echo "ADDLIST='${ADDLIST}'" >> /etc/rc.d/MODULESCONFIG
 } #end yeslist_func
 
@@ -451,7 +451,7 @@ and you need to choose one of them. Create a line here,\nof format module1:modul
  if [ $? -eq 0 ];then
   NEWPREFLIST="`echo "$xxPREFLIST" | tr '\n' ' ' | sed -e 's/^/ /' | tr -s ' '`"
   grep -v '^PREFLIST' /etc/rc.d/MODULESCONFIG > /tmp/MODULESCONFIG
-  mv -f /tmp/MODULESCONFIG /etc/rc.d/MODULESCONFIG
+  mv $VERB -f /tmp/MODULESCONFIG /etc/rc.d/MODULESCONFIG
   echo "PREFLIST='${NEWPREFLIST}'" >> /etc/rc.d/MODULESCONFIG
  fi
 } #end preflist_func
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/cdburner-wizard b/woof-code/rootfs-skeleton/usr/local/bin/cdburner-wizard
--- a/woof-code/rootfs-skeleton/usr/local/bin/cdburner-wizard
+++ b/woof-code/rootfs-skeleton/usr/local/bin/cdburner-wizard
@@ -15,9 +15,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -90,8 +90,8 @@ if [ $XREPLY -eq 11 ];then #choose cdrom
    CDROMLINK="$CDROMD0"
    #strip off the leading "/dev/"...
    echo -n $CDROMLINK | cut -f 3 -d '/' > /etc/cdromdevice
-   rm -f /dev/cdrom
-   ln -s $CDROMLINK /dev/cdrom
+   rm $VERB -f /dev/cdrom
+   ln $VERB -s $CDROMLINK /dev/cdrom
  fi
 fi
 
@@ -107,8 +107,8 @@ if [ $XREPLY -eq 20 ];then #choose dvd
   DVDLINK="$DVDD0"
    #strip off the leading "/dev/"...
    echo -n $DVDLINK | cut -f 3 -d '/' > /etc/dvddevice
-   rm -f /dev/dvd
-   ln -s $DVDLINK /dev/dvd
+   rm $VERB -f /dev/dvd
+   ln $VERB -s $DVDLINK /dev/dvd
  fi
 fi
 
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/chooselocale b/woof-code/rootfs-skeleton/usr/local/bin/chooselocale
--- a/woof-code/rootfs-skeleton/usr/local/bin/chooselocale
+++ b/woof-code/rootfs-skeleton/usr/local/bin/chooselocale
@@ -18,9 +18,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -188,7 +188,7 @@ echo 'if 1'
  if [ "$OLDLANG" != "$NEWLANG" ];then
   langPATTERN="s/${OLDLANG}/${NEWLANG}/"
   sed -e "$langPATTERN" "$mainFile" > /tmp/profile
-  cp -f /tmp/profile "$mainFile"
+  cp $VERB -f /tmp/profile "$mainFile"
  fi
 
  [ "$XSTATUS" != "x" ] && exit
@@ -196,7 +196,7 @@ echo 'if 1'
  Xdialog --left --wrap --title "Country setup" --ok-label "Restart X now" --cancel-label "Finished"  --yesno "Ok, the change has been made and will take effect at next boot. However, if you click the 'Restart X now' button X will exit then restart and the new locale will immediately take effect -- however make sure that all other applications are closed first as restarting X will rudely kill them! Otherwise, just click 'Finished' for the new locale to take effect at next boot.\n\nTechnical details:\nLocale files have been generated in /usr/lib/locale (if not already) and LANG variable set to ${LANGCHOICE}${UTF8} in '$mainFile'." 0 100
 
  if [ $? -eq 0 ];then
-  rm -rf /tmp/.X0-lock
+  rm $VERB -rf /tmp/.X0-lock
   sync
   exec restartwm $CURRENTWM
  fi
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/download_file b/woof-code/rootfs-skeleton/usr/local/bin/download_file
--- a/woof-code/rootfs-skeleton/usr/local/bin/download_file
+++ b/woof-code/rootfs-skeleton/usr/local/bin/download_file
@@ -39,9 +39,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=URLSPEC
 ADD_PARAMETERS="URL: fullpath ie. 'http://www.server.org/folder/file.pet'"
@@ -204,7 +204,7 @@ or erase it and download entire file again?\"`" 0 0
    if [ $? -eq 0 ];then
     CONTPARAM='-c'
    else
-    rm -f "$FILENAME"
+    rm $VERB -f "$FILENAME"
    fi
   else
    if [ $SIZEB_LOCAL -gt $SIZEB_ONLINE ];then #101117
@@ -214,7 +214,7 @@ file is a more recent version, so it is recommended that you erase
 the local file and download it again...
 Do you want to erase it and download entire file again?\"`" 0 0
     if [ $? -eq 0 ];then
-     rm -f "$FILENAME"
+     rm $VERB -f "$FILENAME"
     else
      exit 0
     fi
@@ -223,7 +223,7 @@ Do you want to erase it and download entire file again?\"`" 0 0
 no guarantee it is uncorrupted), do you want to erase it and download
 entire file again?\"`" 0 0
     if [ $? -eq 0 ];then
-     rm -f "$FILENAME"
+     rm $VERB -f "$FILENAME"
     else
      exit 0
     fi
@@ -248,7 +248,7 @@ Do you want to try again, or give up?')" 0 0
   REPLY1=$?
   kill $PID1
   [ $REPLY1 -eq 0 ] && continue
-  rm -f "$FILENAME"
+  rm $VERB -f "$FILENAME"
   exit 2
  fi
  kill $PID1
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/edit-initramfs b/woof-code/rootfs-skeleton/usr/local/bin/edit-initramfs
--- a/woof-code/rootfs-skeleton/usr/local/bin/edit-initramfs
+++ b/woof-code/rootfs-skeleton/usr/local/bin/edit-initramfs
@@ -37,9 +37,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=FILENAME
 ADD_PARAMETERS="File-name: /path/to/initrd.gz"
@@ -78,9 +78,9 @@ return 0
 }
 
 cd /root
-[ -f initrd ] && rm -f initrd
-[ -f /tmp/initrd.gz ] && rm -f /tmp/initrd.gz
-[ "$1" = "$HOME/initrd.gz" ] && cp -f $HOME/initrd.gz /tmp/
+[ -f initrd ] && rm $VERB -f initrd
+[ -f /tmp/initrd.gz ] && rm $VERB -f /tmp/initrd.gz
+[ "$1" = "$HOME/initrd.gz" ] && cp $VERB -f $HOME/initrd.gz /tmp/
 
 if [ -d initrd-expanded ];then
 
@@ -97,7 +97,7 @@ if [ -d initrd-expanded ];then
    cd ..
    ${COMPREXE} initrd
    sync
-   mv -f initrd.${EXT} "$1"
+   mv $VERB -f initrd.${EXT} "$1"
    pupdialog --background '#80FF80' --backtitle "initrd.gz: success" --msgbox "File ${1} has been updated with the contents of $HOME/initrd-expanded." 0 0
   fi
 
@@ -105,7 +105,7 @@ if [ -d initrd-expanded ];then
  pupdialog --background "yellow" --backtitle "initrd.gz: finished" --yesno "Do you want to delete $HOME/initrd-expanded? If in doubt, please choose Yes" 0 0
  if [ $? -eq 0 ];then
   rox -D $HOME/initrd-expanded 2>$ERR
-  rm -rf $HOME/initrd-expanded
+  rm $VERB -rf $HOME/initrd-expanded
  fi
 
 else
@@ -116,15 +116,15 @@ else
   if [ $? -ne 0 ];then
    pupdialog --background '#FF8080' --backtitle "initrd.gz: fail" --msgbox "Sorry, could not recognise compression type of ${1}, unable to expand it." 0 0
   else
-   [ "$1" != "$HOME/initrd.gz" ] && cp -f "$1" $HOME/
-   mv -f initrd.gz initrd.${EXT}
+   [ "$1" != "$HOME/initrd.gz" ] && cp $VERB -f "$1" $HOME/
+   mv $VERB -f initrd.gz initrd.${EXT}
    ${UNCOMPREXE} initrd.${EXT}
-   [ -f /tmp/initrd.gz ] && mv -f /tmp/initrd.gz $HOME/
-   mkdir initrd-expanded
+   [ -f /tmp/initrd.gz ] && mv $VERB -f /tmp/initrd.gz $HOME/
+   mkdir $VERB initrd-expanded
    cd initrd-expanded
    cat ../initrd | cpio -i -d -m
    sync
-   rm -f ../initrd
+   rm $VERB -f ../initrd
    cd ..
    pupdialog --colors --background '#80FF80' --backtitle "initrd.gz: expanded" --msgbox "File initrd.gz has been expanded at \Zb$HOME/initrd-expanded\ZB. You may edit the contents if you wish. \Zb\Z1\n\nAfterward, if you click on ${1} again\Zn\ZB, it will be updated with the contents of $HOME/initrd-expanded." 0 0
    rox -d $HOME/initrd-expanded -x $HOME/initrd-expanded
@@ -133,5 +133,5 @@ else
 
 fi
 
-[ -f /tmp/initrd.gz ] && rm -f /tmp/initrd.gz
+[ -f /tmp/initrd.gz ] && rm $VERB -f /tmp/initrd.gz
 ###END###
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/fixPuppyPin b/woof-code/rootfs-skeleton/usr/local/bin/fixPuppyPin
--- a/woof-code/rootfs-skeleton/usr/local/bin/fixPuppyPin
+++ b/woof-code/rootfs-skeleton/usr/local/bin/fixPuppyPin
@@ -38,9 +38,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=PUPPYPIN
 ADD_PARAMETERS="PUPPYPIN: /path/to/PuppyPin"
@@ -71,7 +71,7 @@ if [ $SCREENX ];then
   aPATTERN="s/x=\"${RIGHTX}\"/x=\"${NEWRIGHTX}\"/"
   cat $PUPPYPIN | sed -e "$aPATTERN" > /tmp/PuppyPin
   sync
-  cp -f /tmp/PuppyPin $PUPPYPIN
+  cp $VERB -f /tmp/PuppyPin $PUPPYPIN
  fi
 
 fi
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/fixdesk b/woof-code/rootfs-skeleton/usr/local/bin/fixdesk
--- a/woof-code/rootfs-skeleton/usr/local/bin/fixdesk
+++ b/woof-code/rootfs-skeleton/usr/local/bin/fixdesk
@@ -52,9 +52,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=LANG
 ADD_PARAMETERS="Language : short ie. de, fr .."
@@ -108,8 +108,8 @@ do
  echo " ${TARGETFILE}" #useful info when running this script in a terminal.
  TARGETPATH="`dirname "$TARGETFILE"`"
  if [ ! -f  /var/local/sss"${TARGETFILE}" ];then
-  mkdir -p /var/local/sss"${TARGETPATH}"
-  cp -a -f "$TARGETFILE" /var/local/sss"${TARGETPATH}"/ #should only happen once.
+  mkdir $VERB -p /var/local/sss"${TARGETPATH}"
+  cp $VERB -a -f "$TARGETFILE" /var/local/sss"${TARGETPATH}"/ #should only happen once.
  fi
 done
 
@@ -122,7 +122,7 @@ do
  TARGETFILE="`echo -n "$aSECTIONID" | tr "${MARKERCHAR}" '/'`" #ex: $HOME/Choices/ROX-Filer/PuppyPin
  TARGETPATH="`dirname "$TARGETFILE"`"
  if [ -f  /var/local/sss"${TARGETFILE}" ];then #precaution.
-  cp -a -f /var/local/sss"${TARGETFILE}" "${TARGETPATH}"/ #restore en file.
+  cp $VERB -a -f /var/local/sss"${TARGETFILE}" "${TARGETPATH}"/ #restore en file.
  fi
 done
 
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/hackfontsize b/woof-code/rootfs-skeleton/usr/local/bin/hackfontsize
--- a/woof-code/rootfs-skeleton/usr/local/bin/hackfontsize
+++ b/woof-code/rootfs-skeleton/usr/local/bin/hackfontsize
@@ -39,9 +39,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=RUNNINGIN
 ADD_PARAMETERS="Running in : any parameter, to set 'single'"
@@ -107,7 +107,7 @@ if [ $XFTDPI -ge 96 ];then
      echo "$aLINEx" >> /tmp/agtkthemefixed
     done
     sync
-    cp -f /tmp/agtkthemefixed ${aGTKRC}
+    cp $VERB -f /tmp/agtkthemefixed ${aGTKRC}
    fi
   done
  fi
@@ -128,7 +128,7 @@ if [ $XFTDPI -ge 96 ];then
      echo "$aLINEx" >> /tmp/ajwmthemefixed
     done
     sync
-    cp -f /tmp/ajwmthemefixed $aJWMTHEME
+    cp $VERB -f /tmp/ajwmthemefixed $aJWMTHEME
    fi
   done
  fi
@@ -147,7 +147,7 @@ if [ $XFTDPI -ge 96 ];then
      echo "$aLINEx" >> /tmp/jwmrctemplatefixed
     done
     sync
-    cp -f /tmp/jwmrctemplatefixed ${JWMPREFIX}etc/xdg/templates/_root_.jwmrc
+    cp $VERB -f /tmp/jwmrctemplatefixed ${JWMPREFIX}etc/xdg/templates/_root_.jwmrc
     if [ "$RUNNINGIN" = "standalone" ];then
      fixmenus
      #jwm -restart
@@ -171,7 +171,7 @@ if [ $XFTDPI -ge 96 ];then
      echo "$aLINEx" >> /tmp/aroxthemefixed
     done
     sync
-    cp -f /tmp/aroxthemefixed ${ROXPREFIX}root/.config/rox.sourceforge.net/ROX-Filer/Options
+    cp $VERB -f /tmp/aroxthemefixed ${ROXPREFIX}root/.config/rox.sourceforge.net/ROX-Filer/Options
    fi
   fi
  fi
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/importfrompuppy1 b/woof-code/rootfs-skeleton/usr/local/bin/importfrompuppy1
--- a/woof-code/rootfs-skeleton/usr/local/bin/importfrompuppy1
+++ b/woof-code/rootfs-skeleton/usr/local/bin/importfrompuppy1
@@ -10,9 +10,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -97,14 +97,14 @@ do
   do
    echo "Copying ${oneFILE}..."
    oneDIR="`dirname $oneFILE`"
-   mkdir -p $oneDIR
-   cp -a --remove-destination /tmp/chosenpupmntpt${oneFILE} ${oneDIR}/
+   mkdir $VERB -p $oneDIR
+   cp $VERB -a --remove-destination /tmp/chosenpupmntpt${oneFILE} ${oneDIR}/
   done
   PKGFILES="`ls -1 /tmp/chosenpupmntpt/root/.packages/${aPACKAGE}.* 2>/dev/null`"
   for onePKGFILE in $PKGFILES
   do
    echo "Copying ${onePKGFILE}..."
-   cp -af $onePKGFILE /root/.packages/
+   cp $VERB -af $onePKGFILE /root/.packages/
   done
   if [ -f /root/.packages/${aPACKAGE}.keyword ];then
    echo "Updating $KEYWORD in w.m. menus..."
@@ -126,8 +126,8 @@ if [ -s /root/.events ];then
  read nnnn
  if [ "$nnnn" = "y" ];then
   echo "Importing /root/.events, .events.log..."
-  cp -af /tmp/chosenpupmntpt/root/.events /root/
-  cp -af /tmp/chosenpupmntpt/root/.events.log /root/
+  cp $VERB -af /tmp/chosenpupmntpt/root/.events /root/
+  cp $VERB -af /tmp/chosenpupmntpt/root/.events.log /root/
  fi
 fi
 
@@ -137,7 +137,7 @@ if [ -d /root/.gaim ];then
  read nnnn
  if [ "$nnnn" = "y" ];then
   echo "Copying /tmp/chosenpupmntpt/root/.gaim..."
-  cp -af /tmp/chosenpupmntpt/root/.gaim /root/
+  cp $VERB -af /tmp/chosenpupmntpt/root/.gaim /root/
  fi
 fi
 
@@ -147,7 +147,7 @@ if [ -d /root/.LinNeighborhood ];then
  read nnnn
  if [ "$nnnn" = "y" ];then
   echo "Copying /tmp/chosenpupmntpt/root/.LinNeighborhood..."
-  cp -af /tmp/chosenpupmntpt/root/.LinNeighborhood /root/
+  cp $VERB -af /tmp/chosenpupmntpt/root/.LinNeighborhood /root/
  fi
 fi
 
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/input-wizard b/woof-code/rootfs-skeleton/usr/local/bin/input-wizard
--- a/woof-code/rootfs-skeleton/usr/local/bin/input-wizard
+++ b/woof-code/rootfs-skeleton/usr/local/bin/input-wizard
@@ -46,9 +46,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -198,12 +198,12 @@ askkbdlayout () #091122
  case $KEYBOARD in #note, same code in /etc/rc.d/rc.country and init.
   de*|be*|br*|dk*|es*|fi*|fr*|it*|no*|se*|sv*|pt*) #100127 added sv
    FONTMAP="lat1-12.psfu"
-   modprobe nls_cp850
+   modprobe $Q $VERB nls_cp850
    CODEPAGE="850"
   ;;
   cz*|hu*|pl*|ro*|sk*|croat*|slovene*)
-   modprobe nls_cp852
-   modprobe nls_iso8859-2
+   modprobe $Q $VERB nls_cp852
+   modprobe $Q $VERB nls_iso8859-2
    FONTMAP="lat2-12.psfu"
    CODEPAGE="852"
   ;;
@@ -264,7 +264,7 @@ fi
    if [ ! "`echo "$RETPARAMS" | grep "EXIT" | grep "OK"`" = "" ];then
     if [ "`echo "$RETPARAMS" | grep "CHECKBOX002" | grep "true"`" != "" ];then
      echo -n "usb" > /etc/keyboardtype
-     modprobe usbhid 2>$ERR #maybe then just need to restart X.
+     modprobe $Q $VERB usbhid 2>$ERR #maybe then just need to restart X.
     else
      echo -n "ps/2" > /etc/keyboardtype
     fi
@@ -414,40 +414,40 @@ fi
    echo "$RETPARAMS"
    if [ ! "`echo "$RETPARAMS" | grep "EXIT" | grep "OK"`" = "" ];then
     if [ -e /lib/modules/2.6 ];then #v1.0.2 k2.6...
-     modprobe -r psmouse 2>$ERR #v1.0.2 k2.6
-     modprobe -r sermouse 2>$ERR #v1.0.2 k2.6
+     modprobe $Q $VERB -r psmouse 2>$ERR #v1.0.2 k2.6
+     modprobe $Q $VERB -r sermouse 2>$ERR #v1.0.2 k2.6
     else
      #modprobe -r usbmouse 2>$ERR #v1.0.2
-     modprobe -r mousedev #v2.0.0
+     modprobe $Q $VERB -r mousedev #v2.0.0
     fi
     if [ ! "`echo "$RETPARAMS" | grep "RADIO001" | grep "true"`" = "" ];then
      MOUSEDEV="psaux" #ps/2 mouse.
-     ln -snf psaux /dev/mouse #v411
+     ln $VERB -snf psaux /dev/mouse #v411
      #k2.4 has ps/2 mouse support inbuilt.
      if [ -e /lib/modules/2.6 ];then #v1.0.2 k2.6...
-      modprobe psmouse 2>$ERR #v1.0.2 k2.6
+      modprobe $Q $VERB psmouse 2>$ERR #v1.0.2 k2.6
      fi
     fi
     if [ ! "`echo "$RETPARAMS" | grep "RADIO002" | grep "true"`" = "" ];then
      eval `echo "$RETPARAMS" | grep "COMPORT"`
      MOUSEDEV="$COMPORT" #ttyS0,1,2,3
-     ln -snf $COMPORT /dev/mouse #v411
+     ln $VERB -snf $COMPORT /dev/mouse #v411
      #2.4 kernel has serial mouse support inbuilt.
      if [ -e /lib/modules/2.6 ];then #v1.0.2 k2.6...
-      modprobe 8250_pci
-      modprobe sermouse
+      modprobe $Q $VERB 8250_pci
+      modprobe $Q $VERB sermouse
      fi
     fi
     if [ ! "`echo "$RETPARAMS" | grep "RADIO003" | grep "true"`" = "" ];then
      MOUSEDEV="input/mice" #usb mouse
      if [ -e /lib/modules/2.6 ];then #v1.0.2 k2.6...
-      modprobe usbhid 2>$ERR
+      modprobe $Q $VERB usbhid 2>$ERR
      else
       #modprobe usbmouse
-      modprobe hid #v2.0.0
-      modprobe mousedev #v2.0.0
+      modprobe $Q $VERB hid #v2.0.0
+      modprobe $Q $VERB mousedev #v2.0.0
      fi
-     ln -snf input/mice /dev/mouse #v411
+     ln $VERB -snf input/mice /dev/mouse #v411
     fi
     echo -n "$MOUSEDEV" > /etc/mousedevice
 
@@ -483,7 +483,7 @@ fi
     fi
     xmodmap -e "${XMODMAP_CMD}"
     grep -v "^pointer" $HOME//.Xmodmap > /tmp/Xmodmap.tmp
-    cp /tmp/Xmodmap.tmp $HOME//.Xmodmap
+    cp $VERB /tmp/Xmodmap.tmp $HOME//.Xmodmap
     echo "${XMODMAP_CMD}" >> $HOME//.Xmodmap
     #
 
@@ -524,7 +524,7 @@ fi
     fi
     sync
     if [ -f /tmp/xorg.conf.tmp ];then
-     cp -f /tmp/xorg.conf.tmp /etc/X11/xorg.conf
+     cp $VERB -f /tmp/xorg.conf.tmp /etc/X11/xorg.conf
     fi
 
     if [ ! "`echo "$RETPARAMS" | grep "CHECKBOX009" | grep "true"`" = "" ];then
@@ -539,7 +539,7 @@ fi
      fi
     fi
     if [ -f /etc/X11/xorg.conf ];then
-     cp -f /tmp/xorg.conf.tmp /etc/X11/xorg.conf
+     cp $VERB -f /tmp/xorg.conf.tmp /etc/X11/xorg.conf
     fi
     sync
 
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/modem-wizard b/woof-code/rootfs-skeleton/usr/local/bin/modem-wizard
--- a/woof-code/rootfs-skeleton/usr/local/bin/modem-wizard
+++ b/woof-code/rootfs-skeleton/usr/local/bin/modem-wizard
@@ -12,9 +12,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -38,7 +38,7 @@ countryfunc() {
  MYCOUNTRY="`Xdialog --wmclass "smartlinkwizard" --title "Smart-Link Modem Wizard" --stdout --no-tags --menubox "Please choose your country:"  0 0 0 0 'MODEM DEFAULT' 1 USA 2 France 3 Germany 4 Italy 5 Sweden 6 UK 7 Japan 8 Australia 9 Spain 10 Taiwan 11 Singapore 12 Korea 13 Switzerland 14 Norway 15 Netherlands 16 Belgium 17 Canada 18 Ireland 19 Portugal 20 Poland 21 Hungary 22 Finland 23 Denmark 24 Austria 25 'South Africa' 26 'CTRL21 countries' 27 China 28 Malaysia 29 Luxumburg 30 Greece 31 Iceland 32 'New Zealand' 33 Brazil 2>/dev/null`"
  [ ! "$MYCOUNTRY" = "" ] && echo "$MYCOUNTRY" > /etc/countrycode
  [ "$MYCOUNTRY" = "" ] && MYCOUNTRY=0
- [ "$MYCOUNTRY" = "0" ] && rm -f /etc/countrycode
+ [ "$MYCOUNTRY" = "0" ] && rm $VERB -f /etc/countrycode
 }
 
 # return the IRQ that respond to a given device
@@ -59,7 +59,7 @@ kill_users()
 
 #talk to modem, wait for response
 chat_with() {
- rm -f /tmp/answer.txt
+ rm $VERB -f /tmp/answer.txt
  #hangs if modem unplugged or turned off (contrary to what docs say)...
  modem-stats -c "ATZ" $1 > /tmp/answer.txt &
  sleep 3
@@ -174,8 +174,8 @@ so nothing to save.
 MSG1
      else
       echo -n "$DEVM" >/etc/modemdevice
-      rm -f /dev/modem
-      ln -s $DEVM /dev/modem
+      rm $VERB -f /dev/modem
+      ln $VERB -s $DEVM /dev/modem
       wavplay -q /usr/share/audio/ok.wav &
       echo "You have configured Puppy for $DEVM (and irq=$IRQM)" >/tmp/modemtest.txt
       echo "Note, there is a 'connect' icon on the desktop." >>/tmp/modemtest.txt
@@ -188,11 +188,11 @@ MSG1
    16)# = erase
      echo "All configuration of the modem, if any, has been erased" >/tmp/modemtest.txt
      echo -n -e "Press \"EXIT\" to get out..." >>/tmp/modemtest.txt
-     rm -f /dev/modem
-     rm -f /etc/modemdevice
+     rm $VERB -f /dev/modem
+     rm $VERB -f /etc/modemdevice
      grep -v --extended-regexp "ltserial|slamr|slusb" /etc/modprobe.conf > /tmp/modprobe.conf
      sync
-     mv -f /tmp/modprobe.conf /etc/modprobe.conf
+     mv $VERB -f /tmp/modprobe.conf /etc/modprobe.conf
      BUTTONS="EXIT:18"
      ;;
    17)# HELP
@@ -212,8 +212,8 @@ MSG1
         echo "alias /dev/ttyLT0 ltserial" >> /etc/modprobe.conf
         echo "alias /dev/modem ltserial" >> /etc/modprobe.conf
        fi
-       modprobe ltmodem
-       modprobe ltserial
+       modprobe $Q $VERB ltmodem
+       modprobe $Q $VERB ltserial
        sleep 1
       fi
       testmodem /dev/ttyLT0
@@ -301,16 +301,16 @@ MSG1
        #v2.02 rerwin, code block moved down...
        if [ "`cat /etc/modprobe.conf | grep "slamr"`" = "" ];then
         echo "alias char-major-242 slamr" >> /etc/modprobe.conf
-        echo 'install slamr modprobe --ignore-install ungrab-winmodem ; modprobe --ignore-install slamr' >> /etc/modprobe.conf
+        echo 'install slamr modprobe $Q $VERB --ignore-install ungrab-winmodem ; modprobe $Q $VERB --ignore-install slamr' >> /etc/modprobe.conf
         echo "alias char-major-243 slusb" >> /etc/modprobe.conf
        fi
        #v2.01 bug, rerwin found needs ungrab-winmodem before load slamr...
        rmmod slamr #unload for ungrab, in case slamr misloaded as serial driver.
-       modprobe ungrab-winmodem
-       modprobe slamr
+       modprobe $Q $VERB ungrab-winmodem
+       modprobe $Q $VERB slamr
        [ ! $? -eq 0 ] && xmessage -center "Failed to load slamr module."
        if [ ! "`lsmod | grep '^usbcore'`" = "" ];then #v2.01
-        modprobe slusb
+        modprobe $Q $VERB slusb
         [ ! $? -eq 0 ] && xmessage -center "Failed to load slusb module."
        fi
        #choose usb or pci modem...
@@ -350,11 +350,11 @@ MSG1
       [ ! $MYCOUNTRY ] && countryfunc #choose country code
       cat /etc/modprobe.conf | grep -v 'options esscom ' > /tmp/modprobeconf.tmp
       sync
-      cp -f /tmp/modprobeconf.tmp /etc/modprobe.conf
+      cp $VERB -f /tmp/modprobeconf.tmp /etc/modprobe.conf
       if [ ! "$MYCOUNTRY" = "0" ];then
        echo "options esscom country_code=$MYCOUNTRY" >> /etc/modprobe.conf
       fi
-      modprobe esscom #$CNTRYPARAM #will also load esscom_hw.
+      modprobe $Q $VERB esscom #$CNTRYPARAM #will also load esscom_hw.
       sleep 1
       testmodem /dev/ttyS_ESS0
      ;;
@@ -375,7 +375,7 @@ MSG1
       [ ! $MYCOUNTRY ] && countryfunc #choose country code
       cat /etc/modprobe.conf | grep -v 'options pctel ' > /tmp/modprobeconf.tmp
       sync
-      cp -f /tmp/modprobeconf.tmp /etc/modprobe.conf
+      cp $VERB -f /tmp/modprobeconf.tmp /etc/modprobe.conf
       if [ ! "$MYCOUNTRY" = "0" ];then
        echo "options pctel country_code=$MYCOUNTRY" >> /etc/modprobe.conf
       fi
@@ -384,9 +384,9 @@ MSG1
       if [ $? -eq 0 ];then #0=found.
        cat /etc/modprobe.conf | grep -v '^install linmodem ' > /tmp/modprobeconf.tmp
        sync
-       cp -f /tmp/modprobeconf.tmp /etc/modprobe.conf
+       cp $VERB -f /tmp/modprobeconf.tmp /etc/modprobe.conf
       fi
-      modprobe pctel #$CNTRYPARAM #also loads linmodem,pctel_hw.
+      modprobe $Q $VERB pctel #$CNTRYPARAM #also loads linmodem,pctel_hw.
       sleep 1
       testmodem /dev/ttyS_PCTEL0
      ;;
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/modemprobe b/woof-code/rootfs-skeleton/usr/local/bin/modemprobe
--- a/woof-code/rootfs-skeleton/usr/local/bin/modemprobe
+++ b/woof-code/rootfs-skeleton/usr/local/bin/modemprobe
@@ -15,9 +15,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -45,7 +45,7 @@ else
    DUNRFCLIST="`rfcomm -a | grep ' connected' | sed -e 's/ channel//' | grep -F "$DUNPATTERN" | cut -f 1 -d :`"
    if [ "$DUNRFCLIST" != "" ];then
     DUNRFCOMM="`echo "$DUNRFCLIST" | head -n 1`"
-    ln -snf $DUNRFCOMM /dev/modem
+    ln $VERB -snf $DUNRFCOMM /dev/modem
    fi
   fi
 #  echo "Modemprobe: DUNPATTERN: $DUNPATTERN  DUNRFCLIST: $DUNRFCLIST  DUNRFCOMM: $DUNRFCOMM" >> /tmp/udevtrace-modem.log #debug
@@ -220,7 +220,7 @@ if [ $RETVAL -eq 0 ];then #found a modem and set it in wvdial.conf
   && aPATTERN="s%^Modem = .*%&\n#Modem = /dev/${DEVMALT}%" \
   && sed -i -e "$aPATTERN" /$CONFDIR/wvdial.conf #v432 end
 else #v433
- [ "$MODEMDEV" = "" ] && rm -f /dev/modem #v433
+ [ "$MODEMDEV" = "" ] && rm $VERB -f /dev/modem #v433
 fi
 #v4.06 end
 
@@ -228,12 +228,12 @@ kill $X1PID
 
 if [ "$DEVM" != "" ];then #4.06 probe found a modem (and not /dev/modem)
  xDEVM="`echo -n "$DEVM" | cut -f 3,4 -d '/'`"
- ln -snf $xDEVM /dev/modem #v4.06
+ ln $VERB -snf $xDEVM /dev/modem #v4.06
  touch /tmp/.pupdial-modem_detected #v433
 
  if [ -f /tmp/wvdial.conf ];then
   grep -v '^;' /tmp/wvdial.conf > /etc/wvdial.conf
-  rm -f /tmp/wvdial.conf
+  rm $VERB -f /tmp/wvdial.conf
   echo 'Carrier Check = no
 Dial Command = ATDT
 
@@ -264,7 +264,7 @@ Init1 = AT+CPIN=
 #Init9 = AT+COPS?' >> /etc/wvdial.conf
  fi
 else #v433
- rm -f /tmp/.pupdial-modem_detected #v433
+ rm $VERB -f /tmp/.pupdial-modem_detected #v433
 fi
 
 sync
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/modemprobe_erase b/woof-code/rootfs-skeleton/usr/local/bin/modemprobe_erase
--- a/woof-code/rootfs-skeleton/usr/local/bin/modemprobe_erase
+++ b/woof-code/rootfs-skeleton/usr/local/bin/modemprobe_erase
@@ -13,9 +13,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -35,7 +35,7 @@ rm -f /dev/modem
 #v432 If no modem currently "detected", reset ALSA override of HSF driver (and vice versa).
 if [ ! -e /etc/wvdial.conf ] \
   || grep -q -E '^Modem = (/dev/MYDEVM|MYDEVM)' /etc/wvdial.conf;then
- [ -d /etc/hsfmodem ] && rm -f /etc/hsfmodem/.substitute_alternate_module
+ [ -d /etc/hsfmodem ] && rm $VERB -f /etc/hsfmodem/.substitute_alternate_module
 fi #v432 end
 
 [ -e /etc/wvdial.conf ] && sed -i -e 's%^Modem = .*%Modem = MYDEVM%' /etc/wvdial.conf #424
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/modemtest b/woof-code/rootfs-skeleton/usr/local/bin/modemtest
--- a/woof-code/rootfs-skeleton/usr/local/bin/modemtest
+++ b/woof-code/rootfs-skeleton/usr/local/bin/modemtest
@@ -15,9 +15,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -72,7 +72,7 @@ irq_from_device_func() { #device passed in, ex: /dev/ttyS0
 
 #talk to modem, wait for response...
 chat_with_func() { #device passed in.
- rm -f /tmp/answer.txt
+ rm $VERB -f /tmp/answer.txt
  #TODO maybe send +++ to return modem to command-mode.
  #hangs if modem unplugged or turned off (contrary to what docs say)...
  modem-stats -c "ATZ" $1 > /tmp/answer.txt &
@@ -126,7 +126,7 @@ modem_test_func() {
     if [ $? -eq 0 ];then
      yaf-splash -font "8x16" -outline 0 -margin 4 -bg orange -text "Please wait, updating settings..." &
      X9PID=$!
-     ln -snf $DEVM /dev/modem
+     ln $VERB -snf $DEVM /dev/modem
 
      waitmax 29 gen_modem_init_string > /dev/null #writes to /tmp/mymodeminitstring
      if [ -s /tmp/mymodeminitstring ];then
@@ -136,15 +136,15 @@ modem_test_func() {
      fi
      kill $X9PID
     fi
-    rm -f /tmp/.pupdial_pin_sent #v433
+    rm $VERB -f /tmp/.pupdial_pin_sent #v433
    fi
    touch /tmp/.pupdial-modem_detected #v433
   else
    kill $X8PID #v413
    modem_device_to_conf_func $MODEMDEV #v433 set current dev
    Xdialog --left --wmclass "pupdial" --title "PupDial: modem test" --no-cancel --msgbox "Sorry, the modem was not detected as $DEVM." 0 0
-   rm -f /tmp/.pupdial_pin_sent #v433
-   rm -f /tmp/.pupdial-modem_detected #v433
+   rm $VERB -f /tmp/.pupdial_pin_sent #v433
+   rm $VERB -f /tmp/.pupdial-modem_detected #v433
   fi
  # ;;
  #*)
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/mousecheck b/woof-code/rootfs-skeleton/usr/local/bin/mousecheck
--- a/woof-code/rootfs-skeleton/usr/local/bin/mousecheck
+++ b/woof-code/rootfs-skeleton/usr/local/bin/mousecheck
@@ -14,9 +14,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -73,14 +73,14 @@ choosemousefunc() { #based on code in /etc/rc.d/functions4puppy4; 2013-11-16 now
   [ $? -ne 0 ] && return 1
   [ ! -s /tmp/testmsx ] && return 1
   MOUSEDEV="`cat /tmp/testmsx`"
-  modprobe sermouse
-  ln -snf $MOUSEDEV /dev/mouse
+  modprobe $Q $VERB sermouse
+  ln $VERB -snf $MOUSEDEV /dev/mouse
   echo -n "$MOUSEDEV" > /etc/mousedevice
   sed -i -e 's/\W\+Option\W\+"Protocol"\W\+"\(\(\w\+\/\w\+\)\|\(\w\+\)\)\W\+#mouse0protocol/    Option      "Protocol" "Microsoft" #mouse0protocol/' /etc/X11/xorg.conf
  ;;
  *)
   echo -n "input/mice" > /etc/mousedevice
-  ln -snf input/mice /dev/mouse
+  ln $VERB -snf input/mice /dev/mouse
   sed -i -e 's/\W\+Option\W\+"Protocol"\W\+"\(\(\w\+\/\w\+\)\|\(\w\+\)\)\W\+#mouse0protocol/    Option      "Protocol" "IMPS\/2" #mouse0protocol/' /etc/X11/xorg.conf
  ;;
  esac
@@ -121,7 +121,7 @@ fi
 choosemousefunc
 if [ $? -eq 0 ];then
  echo -n '' > /tmp/delayedrun_quicksetup_count #111026 hack for 'delayedrun', so quicksetup will re-run.
- rm -rf /tmp/.X0-lock
+ rm $VERB -rf /tmp/.X0-lock
  sync
  exec restartwm
 fi
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/partviewOLD b/woof-code/rootfs-skeleton/usr/local/bin/partviewOLD
--- a/woof-code/rootfs-skeleton/usr/local/bin/partviewOLD
+++ b/woof-code/rootfs-skeleton/usr/local/bin/partviewOLD
@@ -11,9 +11,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -66,7 +66,7 @@ do
  AUSED=`df -k | grep "$AFPATTERN" | tr -s " " | cut -f 3 -d " "`
  if [ ! "$AUSED" ];then
   MNTSTATUS='(not mounted)'
-  mkdir -p /mnt/$ATAG
+  mkdir $VERB -p /mnt/$ATAG
   mount -t $AFS /dev/$ATAG /mnt/$ATAG > /dev/null 2>&1
   if [ $? -eq 0 ];then
    AUSED=`df -k | grep "$AFPATTERN" | tr -s " " | cut -f 3 -d " "`
@@ -94,7 +94,7 @@ do
   echo "$ONESIZE" > /tmp/partview_used_${ATAG}_old
   echo "$ONESIZE" > /tmp/partview_used_${ATAG}
  else
-  cp -f /tmp/partview_used_${ATAG} /tmp/partview_used_${ATAG}_old
+  cp $VERB -f /tmp/partview_used_${ATAG} /tmp/partview_used_${ATAG}_old
   echo "$ONESIZE" > /tmp/partview_used_${ATAG}
  fi
  pvDIFFER="`diff -q /tmp/partview_used_${ATAG} /tmp/partview_used_${ATAG}_old`"
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pcdripper b/woof-code/rootfs-skeleton/usr/local/bin/pcdripper
--- a/woof-code/rootfs-skeleton/usr/local/bin/pcdripper
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pcdripper
@@ -31,9 +31,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -2031,14 +2031,14 @@ fi
 if [ "$NOSTDIN" = yes ]; then
 if [ "$CDRIPPER" = cdparanoia ]; then
 echo cdparanoia "$OPTIONS" "$TRACKS"-"$TRACKS2" -d "$DEVICE" \"$LINE\".wav >> /tmp/$WHOAMI-pcdripper-ripcli
-echo mv "track\"$NUM\".\"$LINE\".wav" "\"$LINE\".wav" >> /tmp/$WHOAMI-pcdripper-ripcli
+echo mv $VERB "track\"$NUM\".\"$LINE\".wav" "\"$LINE\".wav" >> /tmp/$WHOAMI-pcdripper-ripcli
 else
 echo $CDRIPPER dev="$DEVICE" -t "$TRACKS" \"$LINE\".wav >> /tmp/$WHOAMI-pcdripper-ripcli
-echo rm -f \"$LINE\".inf >> /tmp/$WHOAMI-pcdripper-ripcli
+echo rm $VERB -f \"$LINE\".inf >> /tmp/$WHOAMI-pcdripper-ripcli
 fi
 if [ "$WORD" != wav ]; then
 echo "$ENCODELINE" >> /tmp/$WHOAMI-pcdripper-ripcli
-echo rm -f \"$LINE\".wav >> /tmp/$WHOAMI-pcdripper-ripcli
+echo rm $VERB -f \"$LINE\".wav >> /tmp/$WHOAMI-pcdripper-ripcli
 fi
 else
 ##incase any other format besides wav was chosen here is where the rip/encode script is built
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pctorrent b/woof-code/rootfs-skeleton/usr/local/bin/pctorrent
--- a/woof-code/rootfs-skeleton/usr/local/bin/pctorrent
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pctorrent
@@ -11,9 +11,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -440,7 +440,7 @@ FILE="`cat $HOME/.pctorrent/torrfile`"
         PROG=`cat /tmp/$WHOAMI-pctorrent-progcombo | cut -f 2 -d '-'`
         PROG2="-P -"$PROG"-"
         if [ -f /tmp/$WHOAMI-pctorrent-seed ]; then
-        rm -f /tmp/$WHOAMI-pctorrent-seed
+        rm $VERB -f /tmp/$WHOAMI-pctorrent-seed
         echo ctorrent "$DOWN" "$UP" "$EXITHR" "$EXITRATIO" "$PORT" "$CACHE""$NUM2""$SIZE" "$PROG2" -f \'"$FILE"\' | tr -s ' ' > /tmp/$WHOAMI-pctorrentexec
         else
         echo ctorrent "$DOWN" "$UP" "$EXITHR" "$EXITRATIO" "$PORT" "$CACHE""$NUM2""$SIZE" "$PROG2" \'"$FILE"\' | tr -s ' ' > /tmp/$WHOAMI-pctorrentexec
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pcur b/woof-code/rootfs-skeleton/usr/local/bin/pcur
--- a/woof-code/rootfs-skeleton/usr/local/bin/pcur
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pcur
@@ -33,9 +33,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -68,8 +68,8 @@ do
  if [ ! -f /usr/share/icons/${oneITEM}.png ];then
   cd $HOME/.icons/${oneITEM}/cursors
   xcur2png -d /tmp/xcur2png left_ptr
-  mv -f /tmp/xcur2png/left_ptr_000.png /usr/share/icons/${oneITEM}.png
-  rm -f /tmp/xcur2png/left_ptr_*.png
+  mv $VERB -f /tmp/xcur2png/left_ptr_000.png /usr/share/icons/${oneITEM}.png
+  rm $VERB -f /tmp/xcur2png/left_ptr_*.png
  fi
 
  if [ "$oneITEM" = "$PREVTHEME" ];then
@@ -124,7 +124,7 @@ eval "${RETVARS}"
 [ "`echo "$CHOOSECUR" | grep 'CURRENT THEME'`" != "" ] && exit #already current.
 
 if [ "$CHOOSECUR" = "ORIGINAL THEME" ];then
- rm -f $HOME/.icons/default
+ rm $VERB -f $HOME/.icons/default
  exit
 fi
 
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pmodemdiag b/woof-code/rootfs-skeleton/usr/local/bin/pmodemdiag
--- a/woof-code/rootfs-skeleton/usr/local/bin/pmodemdiag
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pmodemdiag
@@ -10,9 +10,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -101,7 +101,7 @@ touch /tmp/pmodemdiag-$NAMEDATE/kernel-`uname -r`
 cp -f /tmp/xerrs.log /tmp/pmodemdiag-$NAMEDATE/ 2> /dev/null
 cp -f /tmp/.usbserial_dependents /tmp/pmodemdiag-$NAMEDATE/ 2> /dev/null
 if [ "`which hciconfig`" != "" ];then
- cp -f /etc/bluetooth/*.conf /tmp/pmodemdiag-$NAMEDATE/ 2> /dev/null
+ cp $VERB -f /etc/bluetooth/*.conf /tmp/pmodemdiag-$NAMEDATE/ 2> /dev/null
  hciconfig -a 2>&1 > /tmp/pmodemdiag-$NAMEDATE/hciconfig.txt
  if [ "`which hcitool`" != "" ];then
   hcitool dev 2>&1 > /tmp/pmodemdiag-$NAMEDATE/hcitool.txt
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pupdial b/woof-code/rootfs-skeleton/usr/local/bin/pupdial
--- a/woof-code/rootfs-skeleton/usr/local/bin/pupdial
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pupdial
@@ -52,9 +52,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -191,7 +191,7 @@ DEVMALT="`cat /etc/wvdial.conf | grep '^#Modem = ' | tail -n 1 | cut -f 3 -d ' '
 [ ! -f /tmp/pupdial.log ] && touch /tmp/pupdial.log #v408 rerwin, moved up.
 if [ "${DEVM}" != "MYDEVM" ];then
  [ -f /tmp/.pupdial-modem_detected ] \
-  && rm -f /tmp/.pupdial-modem_detected \
+  && rm $VERB -f /tmp/.pupdial-modem_detected \
   && MSG1="Modem detected! Device interface: /dev/$DEVM" \
   || MSG1="Selected modem device interface: /dev/$DEVM" #v433
  [ "`pidof pppd`" = "" ] && STATECONa="enabled" #dialout button.
@@ -564,7 +564,7 @@ eval "$xRETSTRING"
 
 [ ! -f /etc/wvdial.conf ] && exit
 if [ "$EXIT" = "abort" -o "$EXIT" = "" ];then
- rm -f /tmp/pupdial.log #v3.91
+ rm $VERB -f /tmp/pupdial.log #v3.91
  exit
 fi
 
@@ -695,34 +695,34 @@ if [ "$EXIT" = "CONNECT1" -o "$EXIT" = "CONNECT2" ];then
    fi
   fi
  fi
- rm -f /tmp/pupdial.log
+ rm $VERB -f /tmp/pupdial.log
 
 #v3.98 put this in, now remove...
  #v3.98 /etc/ppp/options can cause conflict for wvdial.
  #(i think 'options' is used by roaring penguin) hide it...
-# mv -f /etc/ppp/options /etc/ppp/optionsHIDE
+# mv $VERB -f /etc/ppp/options /etc/ppp/optionsHIDE
 
  #/etc/ppp/peers/wvdial and wvdial-pipe are part of wvdial pkg, but these files
  #conflict with Gkdial. Therefore, in the Unleashed wvdial pkg these files are
  #kept in /etc/ppp/ and moved into peers/ as needed...
- cp -f /etc/ppp/wvdial /etc/ppp/peers/
+ cp $VERB -f /etc/ppp/wvdial /etc/ppp/peers/
  #v433 Substitute bluetooth wvdial options...
  if which rfcomm >$OUT && which hcitool >$OUT \
    && [ "`echo "$DEVM" | grep '^rfcomm[0-9]'`" != "" ];then
   [ -f /etc/wvdial_options/BT-wvdial ] \
-   && cp -f /etc/wvdial_options/BT-wvdial /etc/ppp/peers/wvdial
+   && cp $VERB -f /etc/wvdial_options/BT-wvdial /etc/ppp/peers/wvdial
   BDADDR="`rfcomm show $DEVM | grep 'connected' | cut -f 2 -d > | cut -f 2 -d ' '`"
   if [ "$BDADDR" != "" ];then
    BDNAME="`hcitool name $BDADDR | tr -s ' ' | tr ' ' _ | tr / _ | tr '$' _`"
    if [ "$BDNAME" != "" ];then
     [ -f /etc/wvdial_options/BT-$BDNAME ] \
-     && cp -f /etc/wvdial_options/BT-$BDNAME /etc/ppp/peers/wvdial \
-     || cp -f /etc/ppp/peers/wvdial /etc/wvdial_options/BT-$BDNAME
+     && cp $VERB -f /etc/wvdial_options/BT-$BDNAME /etc/ppp/peers/wvdial \
+     || cp $VERB -f /etc/ppp/peers/wvdial /etc/wvdial_options/BT-$BDNAME
    fi
   fi
  fi #433 end
  [ "${WVAPN}" != "" ] && [ -f /etc/wvdial_options/APN-${APNSTRING} ] && echo "`cat /etc/wvdial_options/APN-${APNSTRING}`" >> /etc/ppp/peers/wvdial #431
- [ -f /etc/ppp/wvdial-pipe ] && cp -f /etc/ppp/wvdial-pipe /etc/ppp/peers/ #v3.98
+ [ -f /etc/ppp/wvdial-pipe ] && cp $VERB -f /etc/ppp/wvdial-pipe /etc/ppp/peers/ #v3.98
 
  Q_PIN=`modem-stats -c AT+CPIN? /dev/$DEVM`
  echo "$Q_PIN"
@@ -735,11 +735,11 @@ if [ "$EXIT" = "CONNECT1" -o "$EXIT" = "CONNECT2" ];then
  [ ! -f /tmp/pupdial.log ] && sleep 1
  Xdialog --center --wmclass "pupdial" --backtitle "NOTICE: If the log shows a failure to connect, please click left button" --title "PupDial: WvDial connection log" --ok-label "DISCONNECT or stop trying" --cancel-label "CLOSE window but stay online" --fixed-font --tailbox /tmp/pupdial.log 20 80
  if [ $? -eq 0 ];then
-  rm -f /etc/ppp/peers/wvdial
-  rm -f /etc/ppp/peers/wvdial-pipe 2>$ERR #432
+  rm $VERB -f /etc/ppp/peers/wvdial
+  rm $VERB -f /etc/ppp/peers/wvdial-pipe 2>$ERR #432
 
 #v3.98 put this in, now remove...
-#  mv -f /etc/ppp/optionsHIDE /etc/ppp/options
+#  mv $VERB -f /etc/ppp/optionsHIDE /etc/ppp/options
 
   killall wvdial
   killall pppd
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pupdial_init_hotpluggable b/woof-code/rootfs-skeleton/usr/local/bin/pupdial_init_hotpluggable
--- a/woof-code/rootfs-skeleton/usr/local/bin/pupdial_init_hotpluggable
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pupdial_init_hotpluggable
@@ -23,9 +23,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -55,11 +55,11 @@ _trap
 prevMODEM=''
 if [ -h /dev/modem ];then #maybe set by internal modem detected at bootup, or previous run of pupdial this session.
  prevMODEM="`readlink /dev/modem | sed -e 's%/dev/%%'`"
- rm -f /dev/modem
+ rm $VERB -f /dev/modem
 fi
 
 chat_with_func() { #device passed in, ex: ttyUSB0
- rm -f /tmp/pupdial_port_test 2> /dev/null
+ rm $VERB -f /tmp/pupdial_port_test 2> /dev/null
  #TODO maybe send +++ to return modem to command-mode.
  #hangs if modem unplugged or turned off (contrary to what docs say)...
  modem-stats -c "ATZ" $1 > /tmp/pupdial_port_test &
@@ -98,11 +98,11 @@ done
 if [ -h /dev/gsmmodem ];then
  gMODEM="`readlink /dev/gsmmodem`"
  if [ -e /dev/${gMODEM} ];then
-  ln -snf $gMODEM /dev/modem
+  ln $VERB -snf $gMODEM /dev/modem
   [ $hPID -ne 0 ] && kill $hPID
   exit
  else
-  rm -f /dev/gsmmodem
+  rm $VERB -f /dev/gsmmodem
  fi
 fi
 
@@ -148,10 +148,10 @@ if [ "$HSO" ];then
    done
    if [ $WAITCNT -le $WAITMAX ];then
     #Even if /dev/modem already set, ensure it matches detected modem.
-    [ -h /dev/modem ] && rm /dev/modem
-    ln -snf $MODEM /dev/modem
-    [ -h /dev/ttyS_HS ] && rm /dev/ttyS_HS
-    ln -snf $MODEM /dev/ttyS_HS #for pupdial probe
+    [ -h /dev/modem ] && rm $VERB /dev/modem
+    ln $VERB -snf $MODEM /dev/modem
+    [ -h /dev/ttyS_HS ] && rm $VERB /dev/ttyS_HS
+    ln $VERB -snf $MODEM /dev/ttyS_HS #for pupdial probe
    fi
   fi
  fi
@@ -174,7 +174,7 @@ if [ "$USBSERIAL" ];then
     #101206 avoid unecessary modem probing...
     prevUSBMODEM=''
     [ -f /var/local/pupdial/usb_modem_port ] && prevUSBMODEM="`cat /var/local/pupdial/usb_modem_port`"
-    [ "$USBIDS" = "$prevUSBIDS" ] && [ "$prevUSBMODEM" ] && [ "`echo "$MODEMS" | grep "$prevUSBMODEM"`" != "" ] && ln -snf $prevUSBMODEM /dev/modem
+    [ "$USBIDS" = "$prevUSBIDS" ] && [ "$prevUSBMODEM" ] && [ "`echo "$MODEMS" | grep "$prevUSBMODEM"`" != "" ] && ln $VERB -snf $prevUSBMODEM /dev/modem
     if [ ! -h /dev/modem ];then
      for MODEM in $MODEMS
      do
@@ -183,7 +183,7 @@ if [ "$USBSERIAL" ];then
       MODEM=''
      done
      if [ "$MODEM" != "" ];then
-      ln -snf $MODEM /dev/modem
+      ln $VERB -snf $MODEM /dev/modem
       echo -n "$MODEM" > /var/local/pupdial/usb_modem_port
      fi
     fi
@@ -206,8 +206,8 @@ if [ "$CDC_ACM" ];then
     MODEM="`echo "$DEVMLIST" | head -n 1`"
    fi
    if [ "$MODEM" != "" ];then
-    [ ! -e /dev/$MODEM ] && [ -e /dev/input/$MODEM ] && ln -snf input/$MODEM /dev/$MODEM  #device name for pupdial
-    ln -snf $MODEM /dev/modem
+    [ ! -e /dev/$MODEM ] && [ -e /dev/input/$MODEM ] && ln $VERB -snf input/$MODEM /dev/$MODEM  #device name for pupdial
+    ln $VERB -snf $MODEM /dev/modem
    fi
   fi
  fi
@@ -217,8 +217,8 @@ fi #120908 end
 if [ "$IPWIRELESS" ];then
  if [ ! -h /dev/modem ];then #If a different modem selected, quit.
   if lsmod | grep '^ipwireless ' >/dev/null ;then
-   ln -snf ttyIPWp0 ttyS_ttyIPWp0
-   ln -snf ttyS_IPWp0 /dev/modem
+   ln $VERB -snf ttyIPWp0 ttyS_ttyIPWp0
+   ln $VERB -snf ttyS_IPWp0 /dev/modem
   fi
  fi
 fi
@@ -227,8 +227,8 @@ fi
 if [ "$NOZOMI" ];then
  if [ ! -h /dev/modem ];then #If a different modem selected, quit.
   if lsmod | grep '^nozomi ' >/dev/null ;then
-   ln -snf noz0 /dev/modem
-   ln -snf noz0 /dev/ttyS_NOZ0 #for pupdial probe
+   ln $VERB -snf noz0 /dev/modem
+   ln $VERB -snf noz0 /dev/ttyS_NOZ0 #for pupdial probe
   fi
  fi
 fi
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/puppyinstaller b/woof-code/rootfs-skeleton/usr/local/bin/puppyinstaller
--- a/woof-code/rootfs-skeleton/usr/local/bin/puppyinstaller
+++ b/woof-code/rootfs-skeleton/usr/local/bin/puppyinstaller
@@ -42,9 +42,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -92,7 +92,7 @@ ispupfunc() { #two params: fstype partition
  PUPSFS=""
  PUPVEROLD=0
  [ ! $2 ] && return 0
- mkdir -p /mnt/$2
+ mkdir $VERB -p /mnt/$2
  ISPUPMNTPT="`mount | grep "^/dev/$2" | tr -s " " | cut -f 3 -d " "`"
  if [ "$ISPUPMNTPT" = "" ];then
   ISPUPMNTPT="/mnt/$2"
@@ -253,7 +253,7 @@ if [ "$SRCPATH" = "" ];then
   CDDRIVE="`basename $CDDRIVE`"
   CDDRVINFO="`probedisk2 | grep "/dev/$CDDRIVE" | cut -f 3 -d '|'`"
   Xdialog --wmclass "gtkdialog2" --left --title "Puppy universal installer" --msgbox "Please insert the Puppy live-CD (if not already) into the drive.\nNote, in case your PC has two CD/DVD drives, Puppy is expecting\nthe live-CD to be inserted into $CDDRIVE, which is described as:\n $CDDRVINFO \n\nAfter inserting live-CD, click OK button..." 0 0
-  mkdir /mnt/$CDDRIVE 2> /dev/null
+  mkdir $VERB /mnt/$CDDRIVE 2> /dev/null
   mount -t iso9660 /dev/$CDDRIVE /mnt/$CDDRIVE
   if [ -f /mnt/$CDDRIVE/initrd.gz ];then
    SRCPATH="/mnt/$CDDRIVE"
@@ -735,7 +735,7 @@ case $FINALPMEDIA in
    else
     MBRCHOICE="`Xdialog --wmclass "gtkdialog2" --left --title "Puppy Universal Installer" --no-cancel --stdout --menubox "The MBR (Master Boot Record) in the USB drive is probably okay as-is, so choose\nthe first option. However, if you cannot get the drive to boot, and you are\nsure that the BIOS settings are not to blame and the PC is capable of booting\nfrom USB, then try one of these alternative MBRs.\nNote, if you choose to change the MBR, the old first 446 bytes (the\nbootstrap loader part) of the MBR will be backed up to /tmp/oldmbr.bin\nNote, you can install these MBRs directly, without running this\nInstaller program again: they are located in /usr/lib/syslinux,\nand you can use the dd program to copy them.\nExample: dd if=spb2_mbr.bin of=/dev/${DESTDRV}\nNote, personally I have had success with mbr.bin." 0 0 5 default "DO NOTHING, leave current MBR alone" sys-nopart.mbr "Bootstrap loader code, created by JustGreg" mbr.bin "From the Syslinux package" mbrfat.bin "From the makebootfat package" spb2_mbr.bin "From spblinux, created by Christian Ostheimer" `"
    fi
-   rm /tmp/mbr446.bin
+   rm $VERB /tmp/mbr446.bin
    if [ ! "$MBRCHOICE" = "" ];then
     if [ ! "$MBRCHOICE" = "default" ];then
      dd if=/dev/$DESTDRV of=/tmp/oldmbr.bin bs=446 count=1
@@ -800,16 +800,16 @@ read WIPEALL
 if [ "$WIPEALL" != "" ];then
  echo
  echo "Deleting everything in /mnt/data..."
- rm -rf /mnt/data/*
+ rm $VERB -rf /mnt/data/*
 else
  #well, minimum to get rid of...
- rm -f /mnt/data/image.gz 2> /dev/null
- rm -f /mnt/data/usr_cram.fs 2> /dev/null #old name.
- rm -f /mnt/data/pup_[0-9]*.sfs 2>/dev/null #old name.
- rm -f /mnt/data/${DISTRO_FILE_PREFIX}-*.sfs 2>/dev/null
- rm -f /mnt/data/devx_*.sfs 2>/dev/null
- rm -f /mnt/data/${DISTRO_FILE_PREFIX}z*.sfs 2>/dev/null #old name.
- rm -f /mnt/data/z${PREFIX1CHAR}*.sfs 2>/dev/null
+ rm $VERB -f /mnt/data/image.gz 2> /dev/null
+ rm $VERB -f /mnt/data/usr_cram.fs 2> /dev/null #old name.
+ rm $VERB -f /mnt/data/pup_[0-9]*.sfs 2>/dev/null #old name.
+ rm $VERB -f /mnt/data/${DISTRO_FILE_PREFIX}-*.sfs 2>/dev/null
+ rm $VERB -f /mnt/data/devx_*.sfs 2>/dev/null
+ rm $VERB -f /mnt/data/${DISTRO_FILE_PREFIX}z*.sfs 2>/dev/null #old name.
+ rm $VERB -f /mnt/data/z${PREFIX1CHAR}*.sfs 2>/dev/null
 fi
 sync
 umount /mnt/data
@@ -876,9 +876,9 @@ label puppy
 kernel vmlinuz
 append initrd=initrd.gz pmedia=${FINALPMEDIA}${FCOPY}" > /mnt/data/syslinux.cfg
  fi
- cp -f $SRCPATH/boot.msg /mnt/data/
- cp -f $SRCPATH/help.msg /mnt/data/
- cp -f $SRCPATH/logo.16 /mnt/data/
+ cp $VERB -f $SRCPATH/boot.msg /mnt/data/
+ cp $VERB -f $SRCPATH/help.msg /mnt/data/
+ cp $VERB -f $SRCPATH/logo.16 /mnt/data/
  sync
 fi
 
@@ -963,15 +963,15 @@ read WIPEALL
 if [ "$WIPEALL" != "" ];then
  echo
  echo "Deleting everything in /mnt/data..."
- rm -rf /mnt/data/*
+ rm $VERB -rf /mnt/data/*
 else
  #well, minimum to get rid of...
- rm -f /mnt/data/image.gz 2> /dev/null
- rm -f /mnt/data/usr_cram.fs 2> /dev/null
- rm -f /mnt/data/pup_[0-9]*.sfs 2>/dev/null
- rm -f /mnt/data/${DISTRO_FILE_PREFIX}-*.sfs 2>/dev/null
- rm -f /mnt/data/devx_*.sfs 2>/dev/null
- rm -f /mnt/data/z${PREFIX1CHAR}*.sfs 2>/dev/null
+ rm $VERB -f /mnt/data/image.gz 2> /dev/null
+ rm $VERB -f /mnt/data/usr_cram.fs 2> /dev/null
+ rm $VERB -f /mnt/data/pup_[0-9]*.sfs 2>/dev/null
+ rm $VERB -f /mnt/data/${DISTRO_FILE_PREFIX}-*.sfs 2>/dev/null
+ rm $VERB -f /mnt/data/devx_*.sfs 2>/dev/null
+ rm $VERB -f /mnt/data/z${PREFIX1CHAR}*.sfs 2>/dev/null
 fi
 sync
 echo
@@ -1037,9 +1037,9 @@ label puppy
 kernel vmlinuz
 append initrd=initrd.gz pmedia=${FINALPMEDIA}${FCOPY}" > /mnt/data/extlinux.conf
  fi
- cp -f $SRCPATH/boot.msg /mnt/data/
- cp -f $SRCPATH/help.msg /mnt/data/
- cp -f $SRCPATH/logo.16 /mnt/data/
+ cp $VERB -f $SRCPATH/boot.msg /mnt/data/
+ cp $VERB -f $SRCPATH/help.msg /mnt/data/
+ cp $VERB -f $SRCPATH/logo.16 /mnt/data/
  sync
 fi
 
@@ -1078,7 +1078,7 @@ Click OK to quit..."
    [ "$DESTMNTPT" = "" ] && DESTMNTPT="`ps -e | grep -o 'ntfs\-3g.*' | grep "/dev/$DESTPART" | tr '\t' ' ' | tr -s ' ' | tr ' ' "\n" | grep '^/mnt/'`"
 
   if [ "$DESTMNTPT" = "" ];then
-   mkdir /mnt/$DESTPART 2> /dev/null
+   mkdir $VERB /mnt/$DESTPART 2> /dev/null
    mount -t $DESTFS /dev/$DESTPART /mnt/$DESTPART
    DESTMNTPT="/mnt/$DESTPART"
   fi
@@ -1182,14 +1182,14 @@ digits only, or leave blank if you want to install Puppy at '/'..." 0 0 "puppy${
 
    yaf-splash -font "8x16" -outline 0 -margin 4 -bg orange -text "Please wait, copying files to $DESTPART, in folder $NEWPSUBDIR..." &
    XPID=$!
-   mkdir -p $DESTMNTPT/$NEWPSUBDIR
-   cp -f $SRCPATH/vmlinuz $DESTMNTPT/$NEWPSUBDIR/
+   mkdir $VERB -p $DESTMNTPT/$NEWPSUBDIR
+   cp $VERB -f $SRCPATH/vmlinuz $DESTMNTPT/$NEWPSUBDIR/
    sync
-   cp -f $SRCPATH/initrd.gz $DESTMNTPT/$NEWPSUBDIR/
+   cp $VERB -f $SRCPATH/initrd.gz $DESTMNTPT/$NEWPSUBDIR/
    sync
-   cp -f ${SRCPATH}/${DISTRO_FILE_PREFIX}-${NEWVER}.sfs $DESTMNTPT/$NEWPSUBDIR/ #v424
+   cp $VERB -f ${SRCPATH}/${DISTRO_FILE_PREFIX}-${NEWVER}.sfs $DESTMNTPT/$NEWPSUBDIR/ #v424
    sync
-   [ -f $SRCPATH/${ZDRVSFS} ] && cp -f $SRCPATH/${ZDRVSFS} $DESTMNTPT/$NEWPSUBDIR/
+   [ -f $SRCPATH/${ZDRVSFS} ] && cp $VERB -f $SRCPATH/${ZDRVSFS} $DESTMNTPT/$NEWPSUBDIR/
    sync
    FPCAPS="`echo -n "$FINALPMEDIA" | tr [a-z] [A-Z]`"
    touch $DESTMNTPT/$NEWPSUBDIR/$FPCAPS #needed by WakePup
@@ -1284,7 +1284,7 @@ ${grubEXTRAMSG}" 0 0
      Xdialog --wmclass "gtkdialog2" --title "Puppy Universal Installer" --no-buttons --infobox "Please wait, wiping all files in $DESTPART..." 0 0 200000 &
      XPID=$!
      sleep 3
-     rm -rf $DESTMNTPT/*
+     rm $VERB -rf $DESTMNTPT/*
      sync
      kill $XPID
      PUPVEROLD=`expr $DISTRO_VERSION - 1` #v430
@@ -1298,38 +1298,38 @@ ${grubEXTRAMSG}" 0 0
    xSFSNAME="`ls -1 $SRCPATH/ | grep "$SFSPATTERN" | head -n 1`" #v3.01
    #losetup-FULL /dev/loop2 $SRCPATH/${DISTRO_FILE_PREFIX}-$NEWVER.sfs
    losetup-FULL /dev/loop2 $SRCPATH/$xSFSNAME #v3.01
-   mkdir $DESTMNTPT/srcmntpt
+   mkdir $VERB $DESTMNTPT/srcmntpt
    mount -r -t squashfs /dev/loop2 $DESTMNTPT/srcmntpt
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/bin $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/dev $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/etc $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/lib $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/mnt $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/proc $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/root $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/sbin $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/tmp $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/usr $DESTMNTPT/
-   cp -a -u --remove-destination $DESTMNTPT/srcmntpt/var $DESTMNTPT/
-   [ -d $DESTMNTPT/srcmntpt/opt ] && cp -a -u --remove-destination $DESTMNTPT/srcmntpt/opt $DESTMNTPT/ #v2.11
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/bin $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/dev $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/etc $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/lib $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/mnt $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/proc $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/root $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/sbin $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/tmp $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/usr $DESTMNTPT/
+   cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/var $DESTMNTPT/
+   [ -d $DESTMNTPT/srcmntpt/opt ] && cp $VERB -a -u --remove-destination $DESTMNTPT/srcmntpt/opt $DESTMNTPT/ #v2.11
 
    #v2.12 external modules file...
    #w482 fix handling if separate zdrv file...
-   [ -f $SRCPATH/${ZDRVSFS} ] && cp -af $SRCPATH/${ZDRVSFS} $DESTMNTPT/
-   [ -f /${ZDRVSFS} ] && cp -af /${ZDRVSFS} $DESTMNTPT/
+   [ -f $SRCPATH/${ZDRVSFS} ] && cp $VERB -af $SRCPATH/${ZDRVSFS} $DESTMNTPT/
+   [ -f /${ZDRVSFS} ] && cp $VERB -af /${ZDRVSFS} $DESTMNTPT/
    if [ -f $DESTMNTPT/${ZDRVSFS} ];then #w482
-    mkdir -p $DESTMNTPT/data
+    mkdir $VERB -p $DESTMNTPT/data
     mount -t squashfs -o loop $DESTMNTPT/${ZDRVSFS} $DESTMNTPT/data
-    cp -a -f --remove-destination $DESTMNTPT/data/* $DESTMNTPT/
+    cp $VERB -a -f --remove-destination $DESTMNTPT/data/* $DESTMNTPT/
     depmod -b $DESTMNTPT
     sync
     umount $DESTMNTPT/data
-    rm -f $DESTMNTPT/${ZDRVSFS}
+    rm $VERB -f $DESTMNTPT/${ZDRVSFS}
    fi
    #w482 put these modules back into the normal places...
    if [ -d /lib/modules/$KERNELVER/initrd ];then
     #note, important to not have 'initrd' folder in full hd installation, messes up rc.sysinit.
-    cp -af /lib/modules/$KERNELVER/initrd/* $DESTMNTPT/lib/modules/$KERNELVER/
+    cp $VERB -af /lib/modules/$KERNELVER/initrd/* $DESTMNTPT/lib/modules/$KERNELVER/
     depmod -b $DESTMNTPT
    fi
 
@@ -1338,20 +1338,20 @@ ${grubEXTRAMSG}" 0 0
     for ONEEXE in `cat /bin/TARGETEXES` #ex: sbin/e2fsck
     do
      DIREXE="`dirname $ONEEXE`"
-     cp -a -f --remove-destination /${ONEEXE} ${DESTMNTPT}/${DIREXE}/
+     cp $VERB -a -f --remove-destination /${ONEEXE} ${DESTMNTPT}/${DIREXE}/
     done
    fi
    #same thing here...
    if [ -d /lib/keymaps ];then
-    mkdir -p ${DESTMNTPT}/lib/keymaps
-    cp -a -f /lib/keymaps/* ${DESTMNTPT}/lib/keymaps/
-    mkdir -p ${DESTMNTPT}/lib/consolefonts
-    cp -a -f /lib/consolefonts/* ${DESTMNTPT}/lib/consolefonts/
+    mkdir $VERB -p ${DESTMNTPT}/lib/keymaps
+    cp $VERB -a -f /lib/keymaps/* ${DESTMNTPT}/lib/keymaps/
+    mkdir $VERB -p ${DESTMNTPT}/lib/consolefonts
+    cp $VERB -a -f /lib/consolefonts/* ${DESTMNTPT}/lib/consolefonts/
    fi
 
 
-   mkdir $DESTMNTPT/sys 2>/dev/null
-   rm -f $DESTMNTPT/var/log/modprobes.log 2>/dev/null #v2.13 see /sbin/modprobe script.
+   mkdir $VERB $DESTMNTPT/sys 2>/dev/null
+   rm $VERB -f $DESTMNTPT/var/log/modprobes.log 2>/dev/null #v2.13 see /sbin/modprobe script.
    #...not necessary, not using this any more.
    #v3.96 /etc/rc.d/PUPSTATE only has 'PUPMODE=2', add this...
    if [ -e /proc/ide ];then
@@ -1375,7 +1375,7 @@ ${grubEXTRAMSG}" 0 0
    if [ -f $DESTMNTPT/etc/DISTRO_SPECS ];then
     vPATTERN="s%^DISTRO_VERSION=.*%DISTRO_VERSION=${PUPVEROLD}%"
     sed -e "$vPATTERN" $DESTMNTPT/etc/DISTRO_SPECS > /tmp/distro_specs_old
-    cp -f /tmp/distro_specs_old $DESTMNTPT/etc/DISTRO_SPECS #set DISTRO_VERSION back to what it was.
+    cp $VERB -f /tmp/distro_specs_old $DESTMNTPT/etc/DISTRO_SPECS #set DISTRO_VERSION back to what it was.
    fi
 
    #chroot $DESTMNTPT -c /etc/rc.d/rc.update option2hdinstall
@@ -1383,7 +1383,7 @@ ${grubEXTRAMSG}" 0 0
    chroot $DESTMNTPT /etc/rc.d/rc.update option2hdinstall
    #(need to tell rc.update where src files are, as passed param)
    sync
-    mv -f $DESTMNTPT/etc/fstab $DESTMNTPT/etc/fstab.bak
+    mv $VERB -f $DESTMNTPT/etc/fstab $DESTMNTPT/etc/fstab.bak
     echo "/dev/$DESTPART     /            $DESTFS     defaults               0 1" > $DESTMNTPT/etc/fstab
     echo "none          /proc        proc     defaults               0 0" >> $DESTMNTPT/etc/fstab
     echo "none          /sys         sysfs    defaults               0 0" >> $DESTMNTPT/etc/fstab
@@ -1393,7 +1393,7 @@ ${grubEXTRAMSG}" 0 0
     sync
    kill $XPID
    umount $DESTMNTPT/srcmntpt
-   rmdir $DESTMNTPT/srcmntpt
+   rmdir $VERB $DESTMNTPT/srcmntpt
   fi
 
   #make bootable...
@@ -1403,8 +1403,8 @@ ${grubEXTRAMSG}" 0 0
 
    #091210 simpler stuff for grub4dos...
    if [ -f /usr/sbin/grub4dosconfig ];then
-    mkdir -p /mnt/$DESTPART/boot/grub
-    cp -af $SRCPATH/vmlinuz /mnt/$DESTPART/boot/
+    mkdir $VERB -p /mnt/$DESTPART/boot/grub
+    cp $VERB -af $SRCPATH/vmlinuz /mnt/$DESTPART/boot/
     sync
     umount /mnt/$DESTPART
     unmountcdfunc
@@ -1486,7 +1486,7 @@ FOR USB BOOT DISK CHOICE, PLEASE INSERT IT RIGHT NOW BEFORE PROCEEDING!\n\
      [ ! $? -eq 0 ] && continue
     fi
     if [ ! "$BOOTPART" = "" ];then
-     cp -af $SRCPATH/vmlinuz /mnt/$DESTPART/
+     cp $VERB -af $SRCPATH/vmlinuz /mnt/$DESTPART/
      sync
      Xdialog --wmclass "gtkdialog2" --title "Puppy Universal Installer" --msgbox "Creating $BOOTPART boot disk..." 0 0 &
      XPID=$!
@@ -1496,16 +1496,16 @@ FOR USB BOOT DISK CHOICE, PLEASE INSERT IT RIGHT NOW BEFORE PROCEEDING!\n\
      DESTPART="$2"
      SRCPATH="$3"
      FINALPMEDIA="$4"
-      mkdir /tmp/bootdiskmntpt 2> /dev/null
+      mkdir $VERB /tmp/bootdiskmntpt 2> /dev/null
       mount -t msdos /dev/$BOOTPART /tmp/bootdiskmntpt
-      rm -rf /tmp/bootdiskmntpt/*
+      rm $VERB -rf /tmp/bootdiskmntpt/*
       echo "Creating syslinux.cfg on /dev/$BOOTPART..."
       echo "default vmlinuz root=/dev/$DESTPART pmedia=$FINALPMEDIA" > /tmp/bootdiskmntpt/syslinux.cfg
       echo "Writing the Linux kernel, vmlinuz, to /dev/$BOOTPART..."
-      cp -f $SRCPATH/vmlinuz /tmp/bootdiskmntpt/
+      cp $VERB -f $SRCPATH/vmlinuz /tmp/bootdiskmntpt/
       sync
       umount /dev/$BOOTPART
-      rmdir /tmp/bootdiskmntpt
+      rmdir $VERB /tmp/bootdiskmntpt
       echo "Making the /dev/$BOOTPART bootable using Syslinux..."
       syslinux /dev/$BOOTPART
      sync
@@ -1518,8 +1518,8 @@ FOR USB BOOT DISK CHOICE, PLEASE INSERT IT RIGHT NOW BEFORE PROCEEDING!\n\
      kill $XPID
     fi
    else #Grub
-    mkdir -p /mnt/$DESTPART/boot/grub
-    cp -af $SRCPATH/vmlinuz /mnt/$DESTPART/boot/
+    mkdir $VERB -p /mnt/$DESTPART/boot/grub
+    cp $VERB -af $SRCPATH/vmlinuz /mnt/$DESTPART/boot/
     sync
     umount /mnt/$DESTPART
     unmountcdfunc
@@ -1589,7 +1589,7 @@ Click 'Yes' to rerun grubconfig...\n\
 Click 'No' if installation finished..." 0 0
       [ ! $? -eq 0 ] && break
      done
-     rm -f /tmp/loopbrk.txt
+     rm $VERB -f /tmp/loopbrk.txt
      exit
     fi
    fi
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/puppypdf b/woof-code/rootfs-skeleton/usr/local/bin/puppypdf
--- a/woof-code/rootfs-skeleton/usr/local/bin/puppypdf
+++ b/woof-code/rootfs-skeleton/usr/local/bin/puppypdf
@@ -21,9 +21,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -78,7 +78,7 @@ function checkArgs
 
 
         if [ "$test" = "" ]; then
-           rm -f /tmp/type #not a pdf file
+           rm $VERB -f /tmp/type #not a pdf file
 
         else
            #--- if gui is running... --->
@@ -101,7 +101,7 @@ function checkArgs
                 exit 0
           fi
         fi
-        rm -f /tmp/type
+        rm $VERB -f /tmp/type
 
    else
 
@@ -249,7 +249,7 @@ function convert
        if [ "$res2" = "" ]; then
 
           #--- cleanup --->
-          rm -f "$TEMP"
+          rm $VERB -f "$TEMP"
 
           echo -e "done!\n"
 
@@ -259,7 +259,7 @@ function convert
           Xdialog --title "File Conversion error!"\
                   --infobox "There was an error in the file conversion process!\n\nCheck that your input file format is supported.\n\n\
 Press OK to exit.\n\n" 0 0 20000
-          rm -f "$OUTPUT"
+          rm $VERB -f "$OUTPUT"
           exit 1
        fi
    else
@@ -268,7 +268,7 @@ Press OK to exit.\n\n" 0 0 20000
       Xdialog --title "File Conversion error!"\
                   --infobox "There was an error in the file conversion process!\n\nCheck that your input file format is supported.\n\n\
 Press OK to exit.\n\n" 0 0 20000
-      rm -f "$OUTPUT"
+      rm $VERB -f "$OUTPUT"
       exit 1
    fi
 }
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pupscan b/woof-code/rootfs-skeleton/usr/local/bin/pupscan
--- a/woof-code/rootfs-skeleton/usr/local/bin/pupscan
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pupscan
@@ -39,9 +39,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -215,7 +215,7 @@ USBMODINFO="`cat /lib/modules/$KERNVER/modules.alias | tr -s " " | grep '^alias 
 
    YESPARA=no
    USBMODULE=""
-   rm -f /tmp/usbmodulexxx
+   rm $VERB -f /tmp/usbmodulexxx
    echo -n "" > /tmp/usbdevdescr
    cat /proc/bus/usb/devices | tr -s ' ' |
    while read oneLINE
@@ -230,7 +230,7 @@ USBMODINFO="`cat /lib/modules/$KERNVER/modules.alias | tr -s " " | grep '^alias 
      [ "$oneLINE" = "" ] && break
     fi
    done
-   [ ! -s /tmp/usbdevdescr ] && [ "`grep ' ' /tmp/usbmodulexxx`" != "" ] && echo "Product=`cat /tmp/usbmodulexxx`" > /tmp/usbdevdescr && rm /tmp/usbmodulexxx #v425
+   [ ! -s /tmp/usbdevdescr ] && [ "`grep ' ' /tmp/usbmodulexxx`" != "" ] && echo "Product=`cat /tmp/usbmodulexxx`" > /tmp/usbdevdescr && rm $VERB /tmp/usbmodulexxx #v425
    [ -f /tmp/usbmodulexxx ] && USBMODULE="`cat /tmp/usbmodulexxx`"
 
    [ "$USBMODULE" = "" ] && USBMODULE="`echo "$USBMODINFO" | grep "$oneUSB" | cut -f 3 -d ' ' | tail -n 1`" #v425
@@ -360,14 +360,14 @@ chmod 755 /tmp/hwprobemodinfo
 
 #v3.98 improved...
 ##i don't know enough about themes to do this any better...
-#[ -f /etc/gtk-2.0/gtkrc ] && cp -f /etc/gtk-2.0/gtkrc /tmp/gtkrc-pupscan
+#[ -f /etc/gtk-2.0/gtkrc ] && cp $VERB -f /etc/gtk-2.0/gtkrc /tmp/gtkrc-pupscan
 #cp -f /etc/gtk-2.0/gtkrcMONOSPACED-APPEND /etc/gtk-2.0/gtkrc
 #echo '#!/bin/sh
 # sleep 2
 # if [ -f /tmp/gtkrc-pupscan ];then
-#  cp -f /tmp/gtkrc-pupscan /etc/gtk-2.0/gtkrc
+#  cp $VERB -f /tmp/gtkrc-pupscan /etc/gtk-2.0/gtkrc
 # else
-#  rm /etc/gtk-2.0/gtkrc
+#  rm $VERB /etc/gtk-2.0/gtkrc
 # fi
 #' > /tmp/delaygtkrc.sh
 #chmod 755 /tmp/delaygtkrc.sh
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pusbmodeswitch_adapt b/woof-code/rootfs-skeleton/usr/local/bin/pusbmodeswitch_adapt
--- a/woof-code/rootfs-skeleton/usr/local/bin/pusbmodeswitch_adapt
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pusbmodeswitch_adapt
@@ -12,9 +12,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -53,7 +53,7 @@ fi
 mkdir -p /lib/udev
 [ -e ./usb_modeswitch.c ] \
  && echo "Compiling and installing to new package directory." \
- && mkdir -p /usr/share/man/man1
+ && mkdir $VERB -p /usr/share/man/man1
 [ -d ./usb_modeswitch.d ] \
  && echo "Installing configuration data base to new package directory."
 grep -q '^files-install:' ./Makefile \
@@ -70,9 +70,9 @@ echo; echo
 
 if [ -f ${PETDIR}/lib/udev/rules.d/40-usb_modeswitch.rules ];then
  echo "Editing 40-usb_modeswitch.rules to use Puppy modeswitch script."
- mkdir -p ${PETDIR}/etc/udev/rules.d
- cp -f ${PETDIR}/lib/udev/rules.d/40-usb_modeswitch.rules ${PETDIR}/etc/udev/rules.d/40-usb_modeswitch-adapted.rules
- mv -f ${PETDIR}/lib/udev/rules.d/40-usb_modeswitch.rules ${PETDIR}/lib/udev/rules.d/40-usb_modeswitch.rules-tcl
+ mkdir $VERB -p ${PETDIR}/etc/udev/rules.d
+ cp $VERB -f ${PETDIR}/lib/udev/rules.d/40-usb_modeswitch.rules ${PETDIR}/etc/udev/rules.d/40-usb_modeswitch-adapted.rules
+ mv $VERB -f ${PETDIR}/lib/udev/rules.d/40-usb_modeswitch.rules ${PETDIR}/lib/udev/rules.d/40-usb_modeswitch.rules-tcl
  sed -i \
   -e '1 a\
 ### Edited to use only the Puppy Linux port-determination scheme and modeswitch wrapper substitute...' \
@@ -83,9 +83,9 @@ fi
 
 if [ -f ${PETDIR}/usr/share/man/man1/usb_modeswitch.1 ];then
  echo "Converting man page to html as puppy man page."
- mkdir -p ${PETDIR}/usr/share/doc
+ mkdir $VERB -p ${PETDIR}/usr/share/doc
  man2html ${PETDIR}/usr/share/man/man1/usb_modeswitch.1 > ${PETDIR}/usr/share/doc/usb_modeswitch.htm
- rm -f -r ${PETDIR}/usr/share/man
+ rm $VERB -f -r ${PETDIR}/usr/share/man
 fi
 
 echo -e "Now verify the contents of the new package directory,\n${PETDIR}:"
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/quicksetup b/woof-code/rootfs-skeleton/usr/local/bin/quicksetup
--- a/woof-code/rootfs-skeleton/usr/local/bin/quicksetup
+++ b/woof-code/rootfs-skeleton/usr/local/bin/quicksetup
@@ -96,9 +96,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -331,7 +331,7 @@ Basically, if your language is not a <b>Latin</b> derivative, such as all Asian 
   [ ! "$CURRLANG" ] && CURRLANG="en_US" #precaution
   UTF8=''
   if [ "`echo -n "$CURRLANG" | grep 'utf8'`" != "" ];then #111022 get rid of old name.
-   rm -rf /usr/lib/locale/$CURRLANG
+   rm $VERB -rf /usr/lib/locale/$CURRLANG
    UTF8='.UTF-8'
   fi
   [ "`echo -n "$CURRLANG" | grep 'UTF\-8'`" != "" ] && UTF8='.UTF-8'
@@ -351,7 +351,7 @@ Basically, if your language is not a <b>Latin</b> derivative, such as all Asian 
     RAMK=`free | tr -s ' ' | grep -o 'Mem:.*' | cut -f 2 -d ' '`
     if [ $RAMK -gt 100000 ];then
      #111022 no, i seem to have been lead up the garden path, the dir must remain as 'en_US.utf8'...
-     #[ -d /usr/lib/locale/en_US.utf8 ] && rm -rf /usr/lib/locale/en_US.utf8
+     #[ -d /usr/lib/locale/en_US.utf8 ] && rm $VERB -rf /usr/lib/locale/en_US.utf8
      [ ! -d /usr/lib/locale/en_US.utf8 ] && localedef -f UTF-8 -i en_US --no-archive en_US.utf8 >$OUT #110409 111022
     else
      [ ! -d /usr/lib/locale/en_US ] && localedef -f ISO-8859-1 -i en_US --no-archive en_US >$OUT
@@ -581,7 +581,7 @@ Basically, if your language is not a <b>Latin</b> derivative, such as all Asian 
   [ -s /usr/share/i18n/dialog_table_x ] && [ `cat /usr/share/i18n/dialog_table_x | wc -l` -le 1 ] && SANITYFLAG='fail'
   if [ "$PARAM1" = "composeonly" -o "$SANITYFLAG" = "fail" ];then
    #CHOICES_CLI=""; ON=""; OFF=""; CHOICES_X="" #120717 remove XPID="";
-   rm -f /tmp/quicksetup_language_x;rm -f /tmp/quicksetup_language_cli
+   rm $VERB -f /tmp/quicksetup_language_x;rm -f /tmp/quicksetup_language_cli
    for oneLOCALE in `ls -1 /usr/share/i18n/locales | grep -v -E 'i18n|iso|translit|POSIX'`
    do
     STATUS="off"
@@ -624,13 +624,13 @@ Basically, if your language is not a <b>Latin</b> derivative, such as all Asian 
    done
    #echo "$CHOICES_X" > /usr/share/i18n/dialog_table_x
    cat /tmp/quicksetup_language_x >/usr/share/i18n/dialog_table_x
-   [ $? = 0 ] && rm /tmp/quicksetup_language_x
+   [ $? = 0 ] && rm $VERB /tmp/quicksetup_language_x
    #rm /tmp/quicksetup_language_x
    #CHOICES_CLI="${FIRSTLINE_CLI}
 #${CHOICES_CLI}"
    #echo "$CHOICES_CLI" > /usr/share/i18n/dialog_table_cli
    cat /tmp/quicksetup_language_cli >/usr/share/i18n/dialog_table_cli
-   [ $? = 0 ] && rm /tmp/quicksetup_language_cli
+   [ $? = 0 ] && rm $VERB /tmp/quicksetup_language_cli
    [ "$PARAM1" = "composeonly" ] && exit
   fi
 
@@ -704,7 +704,7 @@ By default, Puppy Linux assumes that the hardware clock is set to local time, as
 
   if [ -e /etc/localtime ];then
    CZONE="`readlink /etc/localtime 2>$ERR`"
-   [ "$CZONE" = "" ] && rm -f /etc/localtime
+   [ "$CZONE" = "" ] && rm $VERB -f /etc/localtime
   fi
   if [ -e /etc/localtime ];then
    CZONE="`readlink /etc/localtime`"
@@ -727,8 +727,8 @@ By default, Puppy Linux assumes that the hardware clock is set to local time, as
   if [ ! -f /var/local/quicksetup-timezone-table-x -o ! -f /var/local/quicksetup-timezone-table-cli ];then
    #echo -n "" > /var/local/quicksetup-timezone-table-x
    #echo -n "" > /var/local/quicksetup-timezone-table-cli
-   rm -f /var/local/quicksetup-timezone-table-x
-   rm -f /var/local/quicksetup-timezone-table-cli
+   rm $VERB -f /var/local/quicksetup-timezone-table-x
+   rm $VERB -f /var/local/quicksetup-timezone-table-cli
    ZONECHOICES_CLI=""
    for oneZONE in $ZONEINFO
    do
@@ -1229,7 +1229,7 @@ if [ $DISPLAY ];then
  #    pdMNTPT="$(cat /proc/mounts | grep "${aDEV} " | cut -f 2 -d ' ')"
  #    if [ "$pdMNTPT" = "" ];then
  #     ABASE="`basename $aDEV`"
- #     mkdir -p /mnt/$aBASE
+ #     mkdir $VERB -p /mnt/$aBASE
  #     mount -t $aFS $aDEV /mnt/$aBASE
  #     pdFLG=1
  #     pdMNTPT="/mnt/${aBASE}"
@@ -1253,7 +1253,7 @@ if [ $DISPLAY ];then
   pdFS="$(cat /initrd/tmp/RWPART | cut -f 2 -d '|')"
   pdMNTPT="$(cat /proc/mounts | grep "/dev/${pdDEV} " | cut -f 2 -d ' ')"
   if [ ! "$pdMNTPT" ];then
-   mkdir -p /mnt/$pdDEV
+   mkdir $VERB -p /mnt/$pdDEV
    mount -t $pdFS /dev/$pdDEV /mnt/$pdDEV
    pdFLG=1
    pdMNTPT="/mnt/${pdDEV}"
@@ -1278,7 +1278,7 @@ if [ $DISPLAY ];then
  #130501 have successfully started the desktop, remove pupdesk.flg (see /etc/rc.d/rc.sysinit)...
  ##130509 see code above.
  #if [ "$xpdMNTPT" ];then
- # rm -f ${xpdMNTPT}/pupdesk.flg
+ # rm $VERB -f ${xpdMNTPT}/pupdesk.flg
  # if [ $pdFLG -eq 1 ];then
  #  sync
  #  umount $pdMNTPT
@@ -1290,19 +1290,19 @@ if [ $DISPLAY ];then
   pdFS="$(cat /initrd/tmp/RWPART | cut -f 2 -d '|')"
   pdMNTPT="$(cat /proc/mounts | grep "/dev/${pdDEV} " | cut -f 2 -d ' ')"
   if [ ! "$pdMNTPT" ];then
-   mkdir -p /mnt/$pdDEV
+   mkdir $VERB -p /mnt/$pdDEV
    mount -t $pdFS /dev/$pdDEV /mnt/$pdDEV
    pdFLG=1
    pdMNTPT="/mnt/${pdDEV}"
   fi
-  [ -f ${pdMNTPT}/pupdesk.flg ] && rm -f ${pdMNTPT}/pupdesk.flg
+  [ -f ${pdMNTPT}/pupdesk.flg ] && rm $VERB -f ${pdMNTPT}/pupdesk.flg
   if [ $pdFLG -eq 1 ];then
    sync
    umount $pdMNTPT
   fi
  fi
  #get rid of this, as causes xorgwizard to run at next boot (see $HOME/.profile)...
- [ -f $HOME/.xorgwizard-reenter ] && rm -f $HOME/.xorgwizard-reenter
+ [ -f $HOME/.xorgwizard-reenter ] && rm $VERB -f $HOME/.xorgwizard-reenter
 
  yaf-splash -bg orange -close never -fontsize large -text "$(gettext 'Processing, please wait...')" & #120524
  wPID=$!
@@ -1353,12 +1353,12 @@ if [ "$SET_KEYBOARD" ];then
   case $NEW_KMAP in #note, same code in /etc/rc.d/rc.country, init, and input-wizard.
    de*|be*|br*|dk*|es*|fi*|fr*|it*|no*|se*|sv*|pt*)
     #FONTMAP="lat1-12.psfu"
-    modprobe nls_cp850
+    modprobe $Q $VERB nls_cp850
     CODEPAGE="850"
    ;;
    cz*|hu*|pl*|ro*|sk*|croat*|slovene*)
-    modprobe nls_cp852
-    modprobe nls_iso8859-2
+    modprobe $Q $VERB nls_cp852
+    modprobe $Q $VERB nls_iso8859-2
     #FONTMAP="lat2-12.psfu"
     CODEPAGE="852"
    ;;
@@ -1643,10 +1643,10 @@ if [ "$SET_TIMEZONE" ];then
   [ "$ZONERETVAL" = "Universal" ] && ZONERETVAL="Etc/$ZONERETVAL"
   [ "$ZONERETVAL" = "UTC" ] && ZONERETVAL="Etc/$ZONERETVAL"
   [ "$ZONERETVAL" = "Zulu" ] && ZONERETVAL="Etc/$ZONERETVAL"
-  ln -snf /usr/share/zoneinfo/$ZONERETVAL /etc/localtime
+  ln $VERB -snf /usr/share/zoneinfo/$ZONERETVAL /etc/localtime
   which xset &>$OUT && xset s noblank s noexpose -dpms  #shinobar 30jan11: avoid the screen go to blank
 
-  [ -f /etc/TZ ] && rm -f /etc/TZ #don't think need this anymore. also removed from /etc/profile.
+  [ -f /etc/TZ ] && rm $VERB -f /etc/TZ #don't think need this anymore. also removed from /etc/profile.
   #.../etc/profile now reads /etc/localtime and exports TZ variable.
 
   #need to set Linux system time/date, from hardware clock...
@@ -1712,10 +1712,10 @@ It is NOT recommended to choose <b>Permanent</b> here, as the default resolution
      echo -n "${TESTX}x${TESTY}@${TESTVR}" > /etc/xrandrindex #so will be set in .xinitrc at next X start. #130202 added freq.
     ;;
     session)
-     rm -f /etc/xrandrindex
+     rm $VERB -f /etc/xrandrindex
     ;;
     *)
-     rm -f /etc/xrandrindex
+     rm $VERB -f /etc/xrandrindex
      xrandr -s $DEF_XYRES -r $DEF_VFREQ #restore to what it was before. #130202 added freq.
     ;;
    esac
@@ -1734,7 +1734,7 @@ if [ "$SET_XWIZARD" ];then
  if [ "$CHECK_XORGWIZARD" = "true" ];then
   FLAG_CHANGED="${FLAG_CHANGED}${TT_xorg2}:restart|" #"Xorg Video Wizard"
   sed -i -e "s%^DISTRO_XORG_AUTO.*%DISTRO_XORG_AUTO='no'%" /etc/DISTRO_SPECS #/usr/bin/xwin reads this when X starts.
-  mv -f /etc/X11/xorg.conf /etc/X11/xorg.conf.prev 2>$ERR #/usr/bin/xwin will then run xorgwizard.
+  mv $VERB -f /etc/X11/xorg.conf /etc/X11/xorg.conf.prev 2>$ERR #/usr/bin/xwin will then run xorgwizard.
   echo "ICONWIPE" > /var/local/pup_event_icon_change_flag #120226 .xinitrc -> clean_desk_icons will read this, and redraw drive icons. ...actually, redundant, as xorgwizard does this.
  fi
 
@@ -1858,7 +1858,7 @@ if [ "`echo -n "$FLAG_CHANGED" | grep "restart"`" != "" ];then
  RETVALS="`${GTKDIALOGEXE} --program=FC_DIALOG`"
  eval "$RETVALS"
  if [ "$EXIT" = "OK" ];then
-  rm -rf /tmp/.X0-lock
+  rm $VERB -rf /tmp/.X0-lock
   sync
   exec restartwm `cat /etc/windowmanager`
  fi
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/remasterpup2 b/woof-code/rootfs-skeleton/usr/local/bin/remasterpup2
--- a/woof-code/rootfs-skeleton/usr/local/bin/remasterpup2
+++ b/woof-code/rootfs-skeleton/usr/local/bin/remasterpup2
@@ -40,9 +40,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -328,7 +328,7 @@ PARTSLIST="`probepart -m 2>/dev/null | grep '^/dev/' | grep -Ei 'ext[2-4]|reiser
   FLAG_RO='no' #v431
   if [ ! "$AFREE" ];then
    MNTSTATUS="($m_08)"
-   mkdir -p /mnt/$aTAG
+   mkdir $VERB -p /mnt/$aTAG
    mount -t $aFS /dev/$aTAG /mnt/$aTAG >$OUT 2>&1
    if [ $? -eq 0 ];then
     if [ "$aTAG" = "fd0" ];then
@@ -390,7 +390,7 @@ if [ "$WKGMNTPT" = "" ];then
  PPATTERN="^$WKGPART "
  WKGFS="`echo "$SCHOICES" | grep "$PPATTERN" | cut -f 2 -d ':' | cut -f 2 -d " "`"
  [ "$WKGFS" = "msdos" ] && WKGFS="vfat"
- mkdir -p /mnt/$WKGPART
+ mkdir $VERB -p /mnt/$WKGPART
  mount -t $WKGFS /dev/$WKGPART /mnt/$WKGPART
  [ $? -ne 0 ] && exit #precaution.
  WKGMNTPT="/mnt/$WKGPART"
@@ -436,7 +436,7 @@ if [ "$CDMNTPT" = "" ];then
  [ $? -eq 0  ] || exit  # 22jun09
  #now mount it...
  CDMNTPT="/mnt/$BURNERDRV"
- mkdir -p /mnt/$BURNERDRV
+ mkdir $VERB -p /mnt/$BURNERDRV
  mount -t iso9660 /dev/$BURNERDRV /mnt/$BURNERDRV
  [ $? -eq 0 ] && break
  done
@@ -456,7 +456,7 @@ if [ "$WKGMNTPT" = "" ];then
  PPATTERN="^$WKGPART "
  WKGFS="`echo "$SCHOICES" | grep "$PPATTERN" | cut -f 2 -d ':' | cut -f 2 -d " "`"
  [ "$WKGFS" = "msdos" ] && WKGFS="vfat"
- mkdir -p /mnt/$WKGPART
+ mkdir $VERB -p /mnt/$WKGPART
  mount -t $WKGFS /dev/$WKGPART /mnt/$WKGPART
  [ $? -ne 0 ] && exit #precaution.
  WKGMNTPT="/mnt/$WKGPART"
@@ -472,7 +472,7 @@ mkdir $WKGMNTPT/puppylivecdbuild
    sync
    for F in vmlinuz initrd.gz ${ZDRVSFS} grldr menu.lst '*.xpm' isolinux.bin isolinux.cfg '*.msg' '*.16' '*.HTM*' '*.ICO' '*.INF'
    do
-        cp $CDMNTPT/$F $WKGMNTPT/puppylivecdbuild/ 2>$ERR
+        cp $VERB $CDMNTPT/$F $WKGMNTPT/puppylivecdbuild/ 2>$ERR
         sync
    done
 umount /dev/$BURNERDRV 2>$ERR
@@ -500,7 +500,7 @@ sync
 # modules copied from initrd
 ANOTHER_REMOVE="/lib/modules/$KERNELVER/initrd /lib/modules/*/modules.*"        # 28dec09 modules.*
 if [ "$MKZDRV" = "yes" ]; then
-  rm -f $WKGMNTPT/puppylivecdbuild/$ZDRVSFS
+  rm $VERB -f $WKGMNTPT/puppylivecdbuild/$ZDRVSFS
   mksquashfs /lib $WKGMNTPT/puppylivecdbuild/$ZDRVSFS -keep-as-directory -e /lib/[^m]* $ANOTHER_REMOVE
   ANOTHER_REMOVE="/lib/modules"
 fi
@@ -536,13 +536,13 @@ cp -af /root/Choices/ROX-Filer/PuppyPin /tmp/root/Choices/ROX-Filer/
 cp -af /root/Choices/ROX-Filer/globicons /tmp/root/Choices/ROX-Filer/
 #100117 user changes get saved here, which overrides original...
 if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/globicons ];then
- mkdir -p /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
- cp -af /root/.config/rox.sourceforge.net/ROX-Filer/globicons /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
+ mkdir $VERB -p /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
+ cp $VERB -af /root/.config/rox.sourceforge.net/ROX-Filer/globicons /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
 fi
 #100117 i think also save user settings...
 if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/Options ];then
- mkdir -p /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
- cp -af /root/.config/rox.sourceforge.net/ROX-Filer/Options /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
+ mkdir $VERB -p /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
+ cp $VERB -af /root/.config/rox.sourceforge.net/ROX-Filer/Options /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
 fi
 #v411 tidy up, remove desktop drive icons...
 grep -v '/root/.pup_event/drive_' /tmp/root/Choices/ROX-Filer/PuppyPin > /tmp/remaster-PuppyPin
@@ -550,7 +550,7 @@ mv -f /tmp/remaster-PuppyPin /tmp/root/Choices/ROX-Filer/PuppyPin
 #this may have been modified for a different w.m...
 cp -af /root/.xinitrc /tmp/root/
 #also this...
-[ -f /root/.xset.sh ] && cp -af /root/.xset.sh /tmp/root/
+[ -f /root/.xset.sh ] && cp $VERB -af /root/.xset.sh /tmp/root/
 
 #v411 gtk theme may have been changed...
 cp -af /root/.gtkrc-2.0 /tmp/root/
@@ -576,12 +576,12 @@ do
  for oneFILE in `cat $onePKG | grep '^/root/'`
  do
   if [ -d $oneFILE ];then #w018
-   mkdir -p /tmp$oneFILE
+   mkdir $VERB -p /tmp$oneFILE
   fi
   if [ -f $oneFILE ];then #w018
    DIRNAME="`dirname $oneFILE`"
-   mkdir -p /tmp$DIRNAME
-   cp -a -f $oneFILE /tmp$DIRNAME/
+   mkdir $VERB -p /tmp$DIRNAME
+   cp $VERB -a -f $oneFILE /tmp$DIRNAME/
   fi
  done
 done
@@ -619,12 +619,12 @@ do
  for oneFILE in `cat $onePKG | grep '^/etc/'`
  do
   if [ -d $oneFILE ];then #w018
-   mkdir -p /tmp$oneFILE
+   mkdir $VERB -p /tmp$oneFILE
   fi
   if [ -f $oneFILE ];then #w018
    DIRNAME="`dirname $oneFILE`"
-   mkdir -p /tmp$DIRNAME
-   cp -a -f $oneFILE /tmp$DIRNAME/
+   mkdir $VERB -p /tmp$DIRNAME
+   cp $VERB -a -f $oneFILE /tmp$DIRNAME/
   fi
  done
 done
@@ -637,34 +637,34 @@ MSG1="$m_20"
 eval m_21=\"$m_21\"
 Xdialog --wrap --left --title "$m_01" --default-no --yesno "$m_21" 0 0
 if [ $? -eq 0 ];then
- cp -af /etc/codepage /tmp/etc/
- cp -af /etc/fontmap /tmp/etc/
- cp -af /etc/keyboardtype /tmp/etc/
- cp -af /etc/keymap /tmp/etc/
- cp -af /etc/mousebuttons /tmp/etc/
- cp -af /etc/mousedevice /tmp/etc/
- cp -af /etc/videomode /tmp/etc/
- cp -af /etc/eth0mode /tmp/etc/
- cp -af /etc/eth1mode /tmp/etc/
- cp -af /etc/resolv.conf /tmp/etc/
- rm -f /tmp/etc/localtime #a symlink
- cp -af /etc/localtime /tmp/etc/
- cp -af /etc/TZ /tmp/etc/
- cp -af /etc/cdburnerdevice /tmp/etc/
- cp -af /etc/dvddevice /tmp/etc/
- cp -af /etc/modemdevice /tmp/etc/
- cp -af /etc/securetelnetrc /tmp/etc/
- cp -af /etc/modules.conf /tmp/etc/
- cp -af /etc/modprobe.conf /tmp/etc/
- cp -af /etc/rdesktoprc /tmp/etc/
- cp -af /etc/windowmanager /tmp/etc/
- cp -af /etc/xextraoptions /tmp/etc/
- cp -af /etc/X11/xorg.conf /tmp/etc/X11
- cp -af /etc/network-wizard /tmp/etc/
+ cp $VERB -af /etc/codepage /tmp/etc/
+ cp $VERB -af /etc/fontmap /tmp/etc/
+ cp $VERB -af /etc/keyboardtype /tmp/etc/
+ cp $VERB -af /etc/keymap /tmp/etc/
+ cp $VERB -af /etc/mousebuttons /tmp/etc/
+ cp $VERB -af /etc/mousedevice /tmp/etc/
+ cp $VERB -af /etc/videomode /tmp/etc/
+ cp $VERB -af /etc/eth0mode /tmp/etc/
+ cp $VERB -af /etc/eth1mode /tmp/etc/
+ cp $VERB -af /etc/resolv.conf /tmp/etc/
+ rm $VERB -f /tmp/etc/localtime #a symlink
+ cp $VERB -af /etc/localtime /tmp/etc/
+ cp $VERB -af /etc/TZ /tmp/etc/
+ cp $VERB -af /etc/cdburnerdevice /tmp/etc/
+ cp $VERB -af /etc/dvddevice /tmp/etc/
+ cp $VERB -af /etc/modemdevice /tmp/etc/
+ cp $VERB -af /etc/securetelnetrc /tmp/etc/
+ cp $VERB -af /etc/modules.conf /tmp/etc/
+ cp $VERB -af /etc/modprobe.conf /tmp/etc/
+ cp $VERB -af /etc/rdesktoprc /tmp/etc/
+ cp $VERB -af /etc/windowmanager /tmp/etc/
+ cp $VERB -af /etc/xextraoptions /tmp/etc/
+ cp $VERB -af /etc/X11/xorg.conf /tmp/etc/X11
+ cp $VERB -af /etc/network-wizard /tmp/etc/
  MSG1="$m_22"
 else
  #v431JP remove slmodems
- rm -f /tmp/etc/init.d/*slmodem*
+ rm $VERB -f /tmp/etc/init.d/*slmodem*
 fi
 
 #some files to always copy...
@@ -692,12 +692,12 @@ do
  for oneFILE in `cat $onePKG | grep '^/var/'`
  do
   if [ -d $oneFILE ];then #w018
-   mkdir -p /tmp$oneFILE
+   mkdir $VERB -p /tmp$oneFILE
   fi
   if [ -f $oneFILE ];then #w018
    DIRNAME="`dirname $oneFILE`"
-   mkdir -p /tmp$DIRNAME
-   cp -a -f $oneFILE /tmp$DIRNAME/
+   mkdir $VERB -p /tmp$DIRNAME
+   cp $VERB -a -f $oneFILE /tmp$DIRNAME/
   fi
  done
 done
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/set-xftdpi b/woof-code/rootfs-skeleton/usr/local/bin/set-xftdpi
--- a/woof-code/rootfs-skeleton/usr/local/bin/set-xftdpi
+++ b/woof-code/rootfs-skeleton/usr/local/bin/set-xftdpi
@@ -33,9 +33,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -99,15 +99,15 @@ sync
 if [ -d /usr/share/fonts/X11/75dpi ];then
  if [ -d /usr/share/fonts/X11/100dpi ];then
   if [ "$NEWDPI" -le 75 -o "$NEWDPI" -le  87 ];then
-  ln -sf /usr/share/fonts/X11/75dpi /usr/share/fonts/X11/${NEWDPI}dpi
+  ln $VERB -sf /usr/share/fonts/X11/75dpi /usr/share/fonts/X11/${NEWDPI}dpi
   else
-  ln -sf /usr/share/fonts/X11/100dpi /usr/share/fonts/X11/${NEWDPI}dpi
+  ln $VERB -sf /usr/share/fonts/X11/100dpi /usr/share/fonts/X11/${NEWDPI}dpi
   fi
  else
- ln -sf /usr/share/fonts/X11/75dpi /usr/share/fonts/X11/${NEWDPI}dpi
+ ln $VERB -sf /usr/share/fonts/X11/75dpi /usr/share/fonts/X11/${NEWDPI}dpi
  fi
 elif [ -d /usr/share/fonts/X11/100dpi ];then
- ln -sf /usr/share/fonts/X11/100dpi /usr/share/fonts/X11/${NEWDPI}dpi
+ ln $VERB -sf /usr/share/fonts/X11/100dpi /usr/share/fonts/X11/${NEWDPI}dpi
 else
 echo -e "\\033[1;31mNOTICE : /usr/share/fonts/X11/[75&100]dpi missing.\\033;[0;39m"
 fi
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/set_bg b/woof-code/rootfs-skeleton/usr/local/bin/set_bg
--- a/woof-code/rootfs-skeleton/usr/local/bin/set_bg
+++ b/woof-code/rootfs-skeleton/usr/local/bin/set_bg
@@ -11,9 +11,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -37,7 +37,7 @@ cd "${CURDIR}"
 
 if [ "$1" = "-clear" ];then
  cat $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_default | grep -v '<backdrop' > $HOME/.config/wallpaper/pb
- mv -f $HOME/.config/wallpaper/pb $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_default
+ mv $VERB -f $HOME/.config/wallpaper/pb $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_default
  rox -p=default
  echo "[none]" > $HOME/.config/wallpaper/bg_img
  exit
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/shutdownconfig b/woof-code/rootfs-skeleton/usr/local/bin/shutdownconfig
--- a/woof-code/rootfs-skeleton/usr/local/bin/shutdownconfig
+++ b/woof-code/rootfs-skeleton/usr/local/bin/shutdownconfig
@@ -65,9 +65,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -238,8 +238,8 @@ ${FIDOMSG2}"
  yaf-splash -bg orange -close never -fontsize large -text "$T_waitprobing" &
  ppPID=$!
  SCHOICES=""; DEFTAG=""
- rm -f /tmp/schoices.txt
- rm -f /tmp/shutdownconfig_deftag
+ rm $VERB -f /tmp/schoices.txt
+ rm $VERB -f /tmp/shutdownconfig_deftag
  echo "$PARTSLIST" |
  while read aPART
  do
@@ -271,7 +271,7 @@ $(gettext "Instead, you should first run Microsoft Windows -- most often this pr
      fi
     fi
    fi
-   [ -f /tmp/ntfsmnterr.txt ] && rm -f /tmp/ntfsmnterr.txt
+   [ -f /tmp/ntfsmnterr.txt ] && rm $VERB -f /tmp/ntfsmnterr.txt
    if [ $RETMNTVAL -eq 0 ];then
     if [ "$aTAG" = "fd0" ];then
      FFREE=`df -k | grep "/dev/$aTAG" | tr -s " " | cut -f 4 -d " "`
@@ -398,7 +398,7 @@ pupsavefunc() {
  [ "$SMNTPT" = "" ] && SMNTPT="`ps -e | grep -o 'ntfs\-3g.*' | grep "$sPTN" | tr '\t' ' ' | tr -s ' ' | tr ' ' "\n" | grep '^/mnt/'`"
 
  if [ "$SMNTPT" = "" ];then
-  mkdir /mnt/$SAVEPART 2>$ERR
+  mkdir $VERB /mnt/$SAVEPART 2>$ERR
   mount -t $SAVEFS /dev/$SAVEPART /mnt/$SAVEPART
   SMNTPT="/mnt/$SAVEPART"
  fi
@@ -472,14 +472,14 @@ entered at every bootup.')"
   MYPASSWORD="`${DIALOGEXE} ${BACKGROUNDYELLOW} ${TITLEPARAM} "$T_passtitle" --screen-center --stdout --no-cancel --inputbox "$T_passtext" 0 0 "puppyisgreat"`" #110926
    [ "$MYPASSWORD" ] && break
   done
-  modprobe cryptoloop
+  modprobe $Q $VERB cryptoloop
   if [ $RETVAL -eq 1 ];then
    DENSITY="a" #heavy aes encryption
    CRYPTO='-e aes'
-   modprobe aes_generic 2>$ERR #builtin my recent kernels.
+   modprobe $Q $VERB aes_generic 2>$ERR #builtin my recent kernels.
    #did not explicitly load these two before, but do so in init script...
-   modprobe crypto_blkcipher 2>$ERR #builtin my recent kernels.
-   modprobe cbc 2>$ERR #110926 builtin in my 2.6.32-smp-45 kernel.
+   modprobe $Q $VERB crypto_blkcipher 2>$ERR #builtin my recent kernels.
+   modprobe $Q $VERB cbc 2>$ERR #110926 builtin in my 2.6.32-smp-45 kernel.
   else
    DENSITY="x" #light xor encryption.
    CRYPTO='-E 1' #'-e xor' --bug, loads xor.ko which is something else.
@@ -526,7 +526,7 @@ $(eval_gettext 'To quit without saving, select \Zb${T_no}\ZB button...')"
  fi
 
  SAVEPATH="`dirname $SAVEFILE`"
- [ ! -d ${SMNTPT}${SAVEPATH} ] && mkdir -p ${SMNTPT}${SAVEPATH}
+ [ ! -d ${SMNTPT}${SAVEPATH} ] && mkdir $VERB -p ${SMNTPT}${SAVEPATH}
 
  #final sanity check...
  aAAMB=`expr $SIZEPFILE \/ 1024`
@@ -571,7 +571,7 @@ If uncertain, just click OK button.')"
   fi
  done
  [ -f ${SMNTPT}${SAVEPATH} ] && return 1 #abort. must be a directory.
- [ ! -d ${SMNTPT}${SAVEPATH} ] && mkdir ${SMNTPT}${SAVEPATH}
+ [ ! -d ${SMNTPT}${SAVEPATH} ] && mkdir $VERB ${SMNTPT}${SAVEPATH}
  [ ! -d ${SMNTPT}${SAVEPATH} ] && return 1 #some kind of error, abort.
 
  #JOPT=""
@@ -817,7 +817,7 @@ If you answer \Zb\\\${T_copy}\ZB here, please \Zb\Z1FIRST, RIGHT NOW\Zn\ZB, put 
 
     aPATTERN="/dev/$PDEV1 "
     CDMNTPT="`mount | grep "$aPATTERN" | cut -f 3 -d ' '`"
-    mkdir -p /mnt/$PDEV1
+    mkdir $VERB -p /mnt/$PDEV1
     if [ "$CDMNTPT" = "" ];then
      mount -t iso9660 /dev/$PDEV1 /mnt/$PDEV1
      CDMNTPT="/mnt/$PDEV1"
@@ -831,7 +831,7 @@ If you answer \Zb\\\${T_copy}\ZB here, please \Zb\Z1FIRST, RIGHT NOW\Zn\ZB, put 
      DRVFREEK=`df -k | tr -s ' ' | grep "$BPATTERN" | cut -f 4 -d ' '`
      if [ $DRVFREEK -gt $FILESIZEK ];then
       echo "`eval_gettext \"Copying \\\${BASESFS}...\"`" >/dev/console
-      cp -f $oneSFS $SMNTPT/
+      cp $VERB -f $oneSFS $SMNTPT/
       sync
      else
       T_cantcopy="`eval_gettext \"Insufficient space! Cannot copy \\\${BASESFS}\"`"
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/snapmergepuppy b/woof-code/rootfs-skeleton/usr/local/bin/snapmergepuppy
--- a/woof-code/rootfs-skeleton/usr/local/bin/snapmergepuppy
+++ b/woof-code/rootfs-skeleton/usr/local/bin/snapmergepuppy
@@ -49,9 +49,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -114,14 +114,14 @@ do
  [ "$DN" = "." ] && continue
  if [ "$BN" = "__dir_opaque" ];then #w003
   #'.wh.__dir_opaque' marks ignore all contents in lower layers...
-  rm -rf "${BASE}/${DN}/*" 2>$ERR #wipe anything in save layer.
+  rm $VERB -rf "${BASE}/${DN}/*" 2>$ERR #wipe anything in save layer.
   #also need to save the whiteout file to block all lower layers (may be readonly)...
   touch "${BASE}/${DN}/.wh.__dir_opaque" 2>$ERR
-  rm -f "$SNAP/$DN/.wh.__dir_opaque" #should force aufs layer "reval".
+  rm $VERB -f "$SNAP/$DN/.wh.__dir_opaque" #should force aufs layer "reval".
   continue
  fi
  #comes in here with the '.wh.' prefix stripped off, leaving actual filename...
- rm -rf "$BASE/$N"
+ rm $VERB -rf "$BASE/$N"
  #if file exists on a lower layer, have to save the whiteout file...
  BLOCKFILE=""
  for R in `seq 1 1 9`; do [ -e "/initrd/pup_ro$R/$N" ] && BLOCKFILE=yes; done
@@ -135,7 +135,7 @@ do
  #[ -e "/initrd/pup_ro8/$N" ] && BLOCKFILE="yes" #v424
  #[ -e "/initrd/pup_ro9/$N" ] && BLOCKFILE="yes" #v424
  [ "$BLOCKFILE" = "yes" ] && touch "${BASE}/${DN}/.wh.${BN}"
- rm -f "$SNAP/$DN/.wh.$BN" #remove whiteout file. should force aufs layer "reval".
+ rm $VERB -f "$SNAP/$DN/.wh.$BN" #remove whiteout file. should force aufs layer "reval".
 done
 
 #Directories... v409 remove '^var'. w003 remove aufs .wh. dirs.
@@ -147,7 +147,7 @@ while read N
 do
  #v4.01 graceful exit if shutdown X (see /usr/X11R7/bin/restartwm,wmreboot,wmpoweroff)...
  [ "$XRUNNING" = "yes" ] && [ -f /tmp/wmexitmode.txt ] && exit
- [ -d "$BASE/$N" ] || mkdir -p "$BASE/$N"
+ [ -d "$BASE/$N" ] || mkdir $VERB -p "$BASE/$N"
  chmod "$BASE/$N" --reference="$N"
  OWNER=`stat -c %U "$N"`
  chown $OWNER "$BASE/$N"
@@ -202,23 +202,23 @@ Unable to save all files. You need to delete some." &
  FREEBASEB=$((FREEBASEB-FILESIZEB))
 
  ##v2.21 -u causes trouble if timezone malconfigured...
- ##[ -L "$BASE/$N" ] && rm -f "$BASE/$N"
+ ##[ -L "$BASE/$N" ] && rm $VERB -f "$BASE/$N"
  ##cp -a -u -f "$N" "$BASE/$N"
  #cp -a --remove-destination "$N" "$BASE/$N"
- [ -L "$BASE/$N" ] && rm -f "$BASE/$N"
+ [ -L "$BASE/$N" ] && rm $VERB -f "$BASE/$N"
  if [ -L "$N" -o "$NEXTPASSTHRU" = "" ];then
   #link, or first run of snapmergepuppy. no '-u' (update) option.
-  cp -a -f "$N" "$BASE/$N"
+  cp $VERB -a -f "$N" "$BASE/$N"
  else
-  cp -a -u -f "$N" "$BASE/$N" #v3.02
+  cp $VERB -a -u -f "$N" "$BASE/$N" #v3.02
  fi
 
  #if [ "$NEXTPASSTHRU" != "" ];then
- # cp -a -u -f "$N" "$BASE/$N"
+ # cp $VERB -a -u -f "$N" "$BASE/$N"
  #else
- # cp -a -f "$N" "$BASE/$N" #no update option.
+ # cp $VERB -a -f "$N" "$BASE/$N" #no update option.
  #fi
- #flock -x -n "$N" -c rm -f "$N" #remove if file not in use
+ #flock -x -n "$N" -c rm $VERB -f "$N" #remove if file not in use
 
 done</tmp/snap_dirs.lst
 
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/timezone-set b/woof-code/rootfs-skeleton/usr/local/bin/timezone-set
--- a/woof-code/rootfs-skeleton/usr/local/bin/timezone-set
+++ b/woof-code/rootfs-skeleton/usr/local/bin/timezone-set
@@ -16,9 +16,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -41,7 +41,7 @@ XSTATUS="no"
 
 if [ -e /etc/localtime ];then
  CZONE="`readlink /etc/localtime`"
- [ "$CZONE" = "" ] && rm -f /etc/localtime
+ [ "$CZONE" = "" ] && rm $VERB -f /etc/localtime
 fi
 
 if [ -e /etc/localtime ];then
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/usb_modeswitch_status b/woof-code/rootfs-skeleton/usr/local/bin/usb_modeswitch_status
--- a/woof-code/rootfs-skeleton/usr/local/bin/usb_modeswitch_status
+++ b/woof-code/rootfs-skeleton/usr/local/bin/usb_modeswitch_status
@@ -23,9 +23,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -66,7 +66,7 @@ do
   do
    [ $ONEPID -eq ${$} ] && continue
    [ -f /tmp/usb_modeswitch_status_lockregion_${ONEPID}_ ] && kill $ONEPID #other process within lock region.
-   [ $? -eq 0 ] && rm -f /tmp/usb_modeswitch_status_lockregion_${ONEPID}_
+   [ $? -eq 0 ] && rm $VERB -f /tmp/usb_modeswitch_status_lockregion_${ONEPID}_
   done
  fi
 done
@@ -106,8 +106,8 @@ if [ $BRKCNT -lt 30 ];then
     if ! ls /dev/ttyUSB* 2>/dev/null;then
      rmmod $UPMOD
      rmmod usbserial
-     modprobe usbserial vendor=0x${VENDOR} product=0x${CHIPNO}
-     modprobe $UPMOD
+     modprobe $Q $VERB usbserial vendor=0x${VENDOR} product=0x${CHIPNO}
+     modprobe $Q $VERB $UPMOD
     fi
    fi
   fi
@@ -119,7 +119,7 @@ if [ $BRKCNT -lt 30 ];then
     if [ ! -h /dev/gsmmodem  ];then
      #looks for ep_8[0-9]/type with "Interrupt" in it then follows up path looking for a "ttyUSB[0-9]" dir...
      GSMMODEM="`find /sys/devices -regex '/sys/devices/.*/ep_[8][0-9]/type' | grep '/usb[0-9]' | xargs grep 'Interrupt' | sed -e 's%/ep_[8].*%%' | xargs -I ABCDEF find ABCDEF -maxdepth 1 -name 'ttyUSB*' | rev | cut -f 1 -d '/' | rev | sort -u | head -n 1`"
-     [ "$GSMMODEM" ] && ln -s ${GSMMODEM} /dev/gsmmodem
+     [ "$GSMMODEM" ] && ln $VERB -s ${GSMMODEM} /dev/gsmmodem
     fi
    fi
    #...er, but problem, not removed when modem unplugged.
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/wmswitcher b/woof-code/rootfs-skeleton/usr/local/bin/wmswitcher
--- a/woof-code/rootfs-skeleton/usr/local/bin/wmswitcher
+++ b/woof-code/rootfs-skeleton/usr/local/bin/wmswitcher
@@ -39,9 +39,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -85,7 +85,7 @@ function ICEWM(){
         FUTUREWM=`grep -we '^NEXTWM=' /usr/bin/restartwm` 2>$ERR
  echo "rpl -v '$FUTUREWM' 'NEXTWM=\"icewm\"' /usr/bin/restartwm" >/tmp/wmswitcher
         . /tmp/wmswitcher
-        rm -f /tmp/wmswitcher
+        rm $VERB -f /tmp/wmswitcher
         }
  #echo icewm >/etc/windowmanager
  exec restartwm icewm
@@ -98,7 +98,7 @@ function JWM(){
         FUTUREWM=`grep -we '^NEXTWM=' /usr/bin/restartwm` 2>$ERR
    echo "rpl -v '$FUTUREWM' 'NEXTWM=\"jwm\"' /usr/bin/restartwm" >/tmp/wmswitcher
         . /tmp/wmswitcher
-        rm -f /tmp/wmswitcher
+        rm $VERB -f /tmp/wmswitcher
         }
  #echo jwm >/etc/windowmanager
  exec restartwm jwm
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/xgamma-gui b/woof-code/rootfs-skeleton/usr/local/bin/xgamma-gui
--- a/woof-code/rootfs-skeleton/usr/local/bin/xgamma-gui
+++ b/woof-code/rootfs-skeleton/usr/local/bin/xgamma-gui
@@ -34,9 +34,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -87,7 +87,7 @@ if [ ! -z ${sGAMMA} ]; then
    #...xgamma is executed in /root/.xinitrc
    echo "Saved"
    #ummm, but if defaults, don't need xgamma...
-   [ "$sGAMMA" = "100/100/100" ] && rm -f $HOME/.xgamma-gamma #saves time in .xinitrc
+   [ "$sGAMMA" = "100/100/100" ] && rm $VERB -f $HOME/.xgamma-gamma #saves time in .xinitrc
   fi
 fi
 
diff --git a/woof-code/rootfs-skeleton/usr/local/bin/xrandrshell b/woof-code/rootfs-skeleton/usr/local/bin/xrandrshell
--- a/woof-code/rootfs-skeleton/usr/local/bin/xrandrshell
+++ b/woof-code/rootfs-skeleton/usr/local/bin/xrandrshell
@@ -36,9 +36,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -114,12 +114,12 @@ IF YOU DO NOT CHOOSE IN 60 SECONDS, X WILL RESTORE TO DEFAULT RESOLUTION"
 
 RETVAL=$?
 if [ $RETVAL -lt 11 ];then
- rm -f /etc/xrandrindex
+ rm $VERB -f /etc/xrandrindex
  xrandr -s $XYCURRENT #restore to what it was before.
  exit
 fi
 if [ $RETVAL -eq 11 ];then #keep current session only.
- rm -f /etc/xrandrindex
+ rm $VERB -f /etc/xrandrindex
  exit
 fi
 
diff --git a/woof-code/rootfs-skeleton/usr/sbin/alsaconf b/woof-code/rootfs-skeleton/usr/sbin/alsaconf
--- a/woof-code/rootfs-skeleton/usr/sbin/alsaconf
+++ b/woof-code/rootfs-skeleton/usr/sbin/alsaconf
@@ -28,9 +28,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -533,7 +533,7 @@ cleanup () {
     killall -9 aplay arecord >/dev/null 2>&1
     /sbin/modprobe -r isapnp >/dev/null 2>&1
     /sbin/modprobe -r isa-pnp >/dev/null 2>&1
-    rm -f "$TMP" "$addcfg" "$FOUND" "$DUMP"
+    rm $VERB -f "$TMP" "$addcfg" "$FOUND" "$DUMP"
 }
 trap cleanup 0
 
@@ -802,7 +802,7 @@ get_hwcfg_type () {
 # alsaconf sets up exclusively
 cleanup_hwcfg () {
     for i in /etc/sysconfig/hardware/hwcfg-*; do
-        grep -q "MODULE='snd-" $i && rm -f $i
+        grep -q "MODULE='snd-" $i && rm $VERB -f $i
     done
 }
 
@@ -907,7 +907,7 @@ BEGIN { in_sound=0; }
 /^\[.+\]$/ { print; in_sound=0; next; }
 { if (in_sound == 0) { print; } }
 ' < /var/lib/YaST/unique.inf > $TMP
-        cp -f $TMP /var/lib/YaST/unique.inf
+        cp $VERB -f $TMP /var/lib/YaST/unique.inf
     fi
 
     # set up /etc/sysconfig/hardware/*
diff --git a/woof-code/rootfs-skeleton/usr/sbin/cups_shell b/woof-code/rootfs-skeleton/usr/sbin/cups_shell
--- a/woof-code/rootfs-skeleton/usr/sbin/cups_shell
+++ b/woof-code/rootfs-skeleton/usr/sbin/cups_shell
@@ -18,9 +18,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -131,10 +131,10 @@ done
 
 #rm -rf /usr/share/cups/model/gutenprint/5.0/C
 if [ "$CUPSVERSION" = "1.1.23" ];then #w480
- rm -rf /usr/share/cups/model/gutenprint/5.0/* 2>/dev/null #old gutenprint pkg.
- rm -rf /usr/share/ppd/gutenprint/5.0/* 2>/dev/null #old gutenprint pkg.
- rm -rf /usr/share/cups/model/gutenprint/5.2/* 2>/dev/null
- rm -rf /usr/share/ppd/gutenprint/5.2/* 2>/dev/null
+ rm $VERB -rf /usr/share/cups/model/gutenprint/5.0/* 2>/dev/null #old gutenprint pkg.
+ rm $VERB -rf /usr/share/ppd/gutenprint/5.0/* 2>/dev/null #old gutenprint pkg.
+ rm $VERB -rf /usr/share/cups/model/gutenprint/5.2/* 2>/dev/null
+ rm $VERB -rf /usr/share/ppd/gutenprint/5.2/* 2>/dev/null
 fi
 
 ###END###
diff --git a/woof-code/rootfs-skeleton/usr/sbin/framebufferwizard b/woof-code/rootfs-skeleton/usr/sbin/framebufferwizard
--- a/woof-code/rootfs-skeleton/usr/sbin/framebufferwizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/framebufferwizard
@@ -13,9 +13,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -39,7 +39,7 @@ than links for $FINDX .
 Please make sure X can become a link towards the Xserver you want to use"
 exit
 ##else
-[ -z "$DISPLAY" ] && rm -f $i
+[ -z "$DISPLAY" ] && rm $VERB -f $i
 fi
 done
 FBSERVERS=`find /usr/bin /usr/X11/bin -type f -name "X*" | grep -v 'Xorg'`
@@ -66,9 +66,9 @@ WMREBOOT=`which fvwmreboot wmreboot | head -n 1`
 ###<<<<KRG
 rm_unneeded_func(){  ###KRG made to function
 rm -rf /lib/modules/2.4/video/*/*fb.* 2>$ERR
-  rm -rf /lib/modules/2.4/video/*fb.* 2>$ERR
+  rm $VERB -rf /lib/modules/2.4/video/*fb.* 2>$ERR
 rm -rf /lib/modules/2.6/video/*/*fb.* 2>$ERR
-  rm -rf /lib/modules/2.6/video/*fb.* 2>$ERR
+  rm $VERB -rf /lib/modules/2.6/video/*fb.* 2>$ERR
 }
 
 PSFND="`ps`"
@@ -141,27 +141,27 @@ loadfbfunc() {
  case $VIDEOMODULE in
   sisfb)
    MODEXEC="modprobe sisfb mode=$RESXYB rate=$FBRATE"
-   modprobe sisfb mode=$RESXYB rate=$FBRATE 2>/tmp/fbmnterr.txt
+   modprobe $Q $VERB sisfb mode=$RESXYB rate=$FBRATE 2>/tmp/fbmnterr.txt
    RETVAL=$?
    ;;
   tridentfb)
    MODEXEC="modprobe tridentfb mode=$RESXYN bpp=$RESBPP"
-   modprobe tridentfb mode=$RESXYN bpp=$RESBPP 2>/tmp/fbmnterr.txt
+   modprobe $Q $VERB tridentfb mode=$RESXYN bpp=$RESBPP 2>/tmp/fbmnterr.txt
    RETVAL=$?
    ;;
   intelfb)
    MODEXEC="modprobe intelfb mode=${RESXYN}-${RESBPP}@${FBRATE} accel=1 mtrr=1"
-   modprobe intelfb mode=${RESXYN}\-${RESBPP}@${FBRATE} accel=1 mtrr=1 2>/tmp/fbmnterr.txt
+   modprobe $Q $VERB intelfb mode=${RESXYN}\-${RESBPP}@${FBRATE} accel=1 mtrr=1 2>/tmp/fbmnterr.txt
    RETVAL=$?
    ;;
   neofb)
    MODEXEC='modprobe neofb #note, no params.'
-   modprobe neofb  2>/tmp/fbmnterr.txt #note, no params?
+   modprobe $Q $VERB neofb  2>/tmp/fbmnterr.txt #note, no params?
    RETVAL=$?
    ;;
   rivafb)
    MODEXEC='modprobe rivafb #note, no params.'
-   modprobe rivafb 2>/tmp/fbmnterr.txt #note, no params?
+   modprobe $Q $VERB rivafb 2>/tmp/fbmnterr.txt #note, no params?
    RETVAL=$?
    ;;
  esac
@@ -184,10 +184,10 @@ if [ "`cat /root/.fbbootflag`" = "0" ];then
    loadfbfunc
    sleep 1
    if [ ! $RETVAL -eq 0 ];then
-    ln -sf `which Xvesa` /usr/X11R7/bin/X
+    ln $VERB -sf `which Xvesa` /usr/X11R7/bin/X
    fi
   else #precaution
-   ln -sf `which Xvesa` /usr/X11R7/bin/X
+   ln $VERB -sf `which Xvesa` /usr/X11R7/bin/X
   fi
  else
   #well, do not need the fb modules...
@@ -319,9 +319,9 @@ So, defaulting to:
 $MSGXVESA
 
 Press ENTER key to continue..." 0 0
- rm -f /etc/videofb
+ rm $VERB -f /etc/videofb
  if [ -x "`which Xvesa`" ];then
-  ln -sf `which Xvesa` /usr/X11R7/bin/X #precaution.
+  ln $VERB -sf `which Xvesa` /usr/X11R7/bin/X #precaution.
  fi
  #to prevent wizard from running in setup mode at next entry...
  echo -n "0" >/root/.fbbootflag #precaution.
@@ -334,7 +334,7 @@ dialog --title "Xfbdev Video Wizard" --yes-label "$DEFLABEL" --no-label "Framebu
 if [ $? -eq 0 ];then
  #rm -f /etc/videofb
  if [ -x "`which Xvesa`" ];then
-  ln -sf `which Xvesa` /usr/X11R7/bin/X
+  ln $VERB -sf `which Xvesa` /usr/X11R7/bin/X
  fi
  #to prevent wizard from running in setup mode at next entry...
  echo -n "0" >/root/.fbbootflag
@@ -447,7 +447,7 @@ RESXYB="`echo -n "$FBMODE" | cut -f 2 -d " "`"
 RESXYN="`echo -n "$RESXYB" | cut -f 1-2 -d 'x'`"
 RESBPP="`echo -n "$RESXYB" | cut -f 3 -d 'x'`"
 if [ -f /etc/videofb ];then
- cp -f /etc/videofb /etc/videofb.old
+ cp $VERB -f /etc/videofb /etc/videofb.old
 fi
 echo "module=$VIDEOMODULE mode=$RESXYB rate=$FBRATE mem=" >/etc/videofb
 
@@ -485,11 +485,11 @@ OTHERWISE FAILURE WILL BE ASSUMED!
 Press the ENTER key to continue..." 0 0
  if [ $? -eq 0 ];then
   #works.
-  ln -sf `which Xfbdev` /usr/X11R7/bin/X
+  ln $VERB -sf `which Xfbdev` /usr/X11R7/bin/X
  else
   #failure
   if [ -x "`which Xvesa`" ];then
-   ln -sf `which Xvesa` /usr/X11R7/bin/X #precaution.
+   ln $VERB -sf `which Xvesa` /usr/X11R7/bin/X #precaution.
   fi
   sync
   exec reboot
@@ -516,10 +516,10 @@ NOTE: framebufferwizard can run from the console if X not work." 0 0
   #...exits from script.
  else
   if [ -f /etc/videofb.old ];then
-   cp -f /etc/videofb.old /etc/videofb
+   cp $VERB -f /etc/videofb.old /etc/videofb
   fi
   if [ -x "`which Xvesa`" ];then
-   ln -sf `which Xvesa` /usr/X11R7/bin/X #precaution.
+   ln $VERB -sf `which Xvesa` /usr/X11R7/bin/X #precaution.
   fi
  fi
 fi
diff --git a/woof-code/rootfs-skeleton/usr/sbin/kernel-helper b/woof-code/rootfs-skeleton/usr/sbin/kernel-helper
--- a/woof-code/rootfs-skeleton/usr/sbin/kernel-helper
+++ b/woof-code/rootfs-skeleton/usr/sbin/kernel-helper
@@ -14,9 +14,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -93,11 +93,11 @@ rm -rf "${lastkdir}.tmp" "${lastmdir}.tmp"
 install -d "${lastkdir}.tmp" "${lastmdir}.tmp"
 
 if [ -e "/boot/$kver/vmlinuz" ]; then
-        ln -t "${lastkdir}.tmp" /boot/$kver/{vmlinuz,initrd.img,System.map}
+        ln $VERB -t "${lastkdir}.tmp" /boot/$kver/{vmlinuz,initrd.img,System.map}
 else
-        ln /boot/vmlinuz-$kver "${lastkdir}.tmp/vmlinuz"
-        ln /boot/initrd.img-$kver "${lastkdir}.tmp/initrd.img"
-        ln /boot/System.map-$kver "${lastkdir}.tmp/System.map"
+        ln $VERB /boot/vmlinuz-$kver "${lastkdir}.tmp/vmlinuz"
+        ln $VERB /boot/initrd.img-$kver "${lastkdir}.tmp/initrd.img"
+        ln $VERB /boot/System.map-$kver "${lastkdir}.tmp/System.map"
 fi
 
 cat /proc/cmdline > "${lastkdir}.tmp/cmdline"
diff --git a/woof-code/rootfs-skeleton/usr/sbin/keyboard-layout b/woof-code/rootfs-skeleton/usr/sbin/keyboard-layout
--- a/woof-code/rootfs-skeleton/usr/sbin/keyboard-layout
+++ b/woof-code/rootfs-skeleton/usr/sbin/keyboard-layout
@@ -23,9 +23,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -116,12 +116,12 @@ askkbdlayout () #091122
  case $KEYBOARD in #note, same code in /etc/rc.d/rc.country and init.
   de*|be*|br*|dk*|es*|fi*|fr*|it*|no*|se*|sv*|pt*) #100127 added sv
    FONTMAP="lat1-12.psfu"
-   modprobe nls_cp850
+   modprobe $Q $VERB nls_cp850
    CODEPAGE="850"
   ;;
   cz*|hu*|pl*|ro*|sk*|croat*|slovene*)
-   modprobe nls_cp852
-   modprobe nls_iso8859-2
+   modprobe $Q $VERB nls_cp852
+   modprobe $Q $VERB nls_iso8859-2
    FONTMAP="lat2-12.psfu"
    CODEPAGE="852"
   ;;
@@ -145,7 +145,7 @@ askkbdlayout () #091122
   Xdialog --left --wrap --title "Country setup" --ok-label "Restart X now" --cancel-label "Finished"  --yesno "Ok, the change has been made and will take effect at next boot. However, if you click the 'Restart X now' button X will exit then restart and the new keyboard layout will immediately take effect--however make sure that all other applications are closed first as restarting X will rudely kill them!" 0 100
 
  if [ $? -eq 0 ];then
-  rm -rf /tmp/.X0-lock
+  rm $VERB -rf /tmp/.X0-lock
   sync
   exec restartwm $CURRENTWM
  fi
diff --git a/woof-code/rootfs-skeleton/usr/sbin/paperconfig b/woof-code/rootfs-skeleton/usr/sbin/paperconfig
--- a/woof-code/rootfs-skeleton/usr/sbin/paperconfig
+++ b/woof-code/rootfs-skeleton/usr/sbin/paperconfig
@@ -14,9 +14,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -140,7 +140,7 @@ setpaper() {
 
     if 2>/dev/null echo "$paperright" >${PAPERCONF}.new
     then
-        if 2>/dev/null mv -f ${PAPERCONF}.new $PAPERCONF
+        if 2>/dev/null mv $VERB -f ${PAPERCONF}.new $PAPERCONF
         then
             if 2>/dev/null chmod 644 $PAPERCONF
             then
diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect b/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-connect
@@ -31,9 +31,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -143,12 +143,12 @@ fi
 if test `uname -s` = Linux ; then
     $IFCONFIG $ETH up mtu 1500
     # For 2.4 kernels.  Will fail on 2.2.x, but who cares?
-    modprobe ppp_generic > /dev/null 2>&1
-    modprobe ppp_async > /dev/null 2>&1
-    modprobe ppp_synctty > /dev/null 2>&1
+    modprobe $Q $VERB ppp_generic > /dev/null 2>&1
+    modprobe $Q $VERB ppp_async > /dev/null 2>&1
+    modprobe $Q $VERB ppp_synctty > /dev/null 2>&1
     if test -n "$LINUX_PLUGIN" ; then
-        modprobe pppox > /dev/null 2>&1
-        modprobe pppoe > /dev/null 2>&1
+        modprobe $Q $VERB pppox > /dev/null 2>&1
+        modprobe $Q $VERB pppoe > /dev/null 2>&1
     fi
 fi
 
@@ -157,7 +157,7 @@ if test "$SYNCHRONOUS" = "yes" ; then
     PPPD_SYNC=sync
         # Increase the chances of it working on Linux...
     if test `uname -s` = Linux ; then
-        modprobe n_hdlc > /dev/null 2>&1
+        modprobe $Q $VERB n_hdlc > /dev/null 2>&1
     fi
 else
     PPPOE_SYNC=""
@@ -230,7 +230,7 @@ if test "$LINUX_PLUGIN" != "" ; then
 
     # Interface name MUST BE LAST!!
     PLUGIN_OPTS="$PLUGIN_OPTS $ETH"
-    modprobe pppoe > /dev/null 2>&1
+    modprobe $Q $VERB pppoe > /dev/null 2>&1
 fi
 
 if test "$DEFAULTROUTE" != "no" ; then
@@ -245,11 +245,11 @@ PPP_STD_OPTIONS="$PLUGIN_OPTS noipdefault noauth default-asyncmap $DEFAULTROUTE 
 # Jigger DNS if required...
 if test "$DNSTYPE" = "SERVER" ; then
     # Sorry, dude...
-    rm -f /etc/resolv.conf
-    ln -s /etc/ppp/resolv.conf /etc/resolv.conf
+    rm $VERB -f /etc/resolv.conf
+    ln $VERB -s /etc/ppp/resolv.conf /etc/resolv.conf
 elif test "$DNSTYPE" = "SPECIFY" ; then
     # Sorry, dude...
-    rm -f /etc/resolv.conf
+    rm $VERB -f /etc/resolv.conf
     echo "nameserver $DNS1" > /etc/resolv.conf
     if test -n "$DNS2" ; then
         echo "nameserver $DNS2" >> /etc/resolv.conf
@@ -297,7 +297,7 @@ if test "$DEBUG" != "" ; then
     echo "* try using pppoe-sniff." >> $DEBUG
     echo "rp-pppoe debugging dump" >> $DEBUG
     cat $DEBUG-0 >> $DEBUG
-    rm -f $DEBUG-0
+    rm $VERB -f $DEBUG-0
     for i in 1 2 3 4 5 6 7 8 9 10 ; do
         echo ""
         echo ""
diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-setup b/woof-code/rootfs-skeleton/usr/sbin/pppoe-setup
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-setup
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-setup
@@ -24,9 +24,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -62,7 +62,7 @@ CONFIG=/etc/ppp/pppoe.conf
 umask 077
 
 copy() {
-    cp $1 $2
+    cp $VERB $1 $2
     if [ "$?" != 0 ] ; then
         $ECHO "*** Error copying $1 to $2"
         $ECHO "*** Quitting."
@@ -367,13 +367,13 @@ if [ -r /etc/ppp/pap-secrets ] ; then
     $ECHO "  (But first backing it up to /etc/ppp/pap-secrets-bak)"
     copy /etc/ppp/pap-secrets /etc/ppp/pap-secrets-bak
 else
-    cp /dev/null /etc/ppp/pap-secrets-bak
+    cp $VERB /dev/null /etc/ppp/pap-secrets-bak
 fi
 if [ -r /etc/ppp/chap-secrets ] ; then
     $ECHO "  (But first backing it up to /etc/ppp/chap-secrets-bak)"
     copy /etc/ppp/chap-secrets /etc/ppp/chap-secrets-bak
 else
-    cp /dev/null /etc/ppp/chap-secrets-bak
+    cp $VERB /dev/null /etc/ppp/chap-secrets-bak
 fi
 
 egrep -v "^$U|^\"$U\"" /etc/ppp/pap-secrets-bak > /etc/ppp/pap-secrets
diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-start b/woof-code/rootfs-skeleton/usr/sbin/pppoe-start
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-start
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-start
@@ -31,9 +31,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -77,7 +77,7 @@ if [ "$DEBUG" = "1" ] ; then
     $ECHO "*** Running in debug mode... please be patient..."
     DEBUG=/tmp/pppoe-debug-$$
     export DEBUG
-    mkdir $DEBUG
+    mkdir $VERB $DEBUG
     if [ "$?" != 0 ] ; then
         $ECHO "Could not create directory $DEBUG... exiting"
         exit 1
@@ -164,7 +164,7 @@ if [ -r "$PIDFILE" ] ; then
         exit 1
     fi
     # Delete bogus PIDFILE
-    rm -f "$PIDFILE" "$PIDFILE.pppd" "$PIDFILE.pppoe" "$PIDFILE.start"
+    rm $VERB -f "$PIDFILE" "$PIDFILE.pppd" "$PIDFILE.pppoe" "$PIDFILE.start"
 fi
 
 echo $$ > $PIDFILE.start
diff --git a/woof-code/rootfs-skeleton/usr/sbin/pppoe-stop b/woof-code/rootfs-skeleton/usr/sbin/pppoe-stop
--- a/woof-code/rootfs-skeleton/usr/sbin/pppoe-stop
+++ b/woof-code/rootfs-skeleton/usr/sbin/pppoe-stop
@@ -29,9 +29,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -113,7 +113,7 @@ if [ -r "$PIDFILE" ] ; then
         kill -9 $PPPD_PID > /dev/null 2>&1 || exit 1
     fi
 
-    rm -f "$PIDFILE" "$PPPD_PIDFILE" "$PPPOE_PIDFILE" "$STARTPID"
+    rm $VERB -f "$PIDFILE" "$PPPD_PIDFILE" "$PPPOE_PIDFILE" "$STARTPID"
 else
     echo "$ME: No PPPoE connection appears to be running" >&2
     exit 1
diff --git a/woof-code/rootfs-skeleton/usr/sbin/run-as-spot b/woof-code/rootfs-skeleton/usr/sbin/run-as-spot
--- a/woof-code/rootfs-skeleton/usr/sbin/run-as-spot
+++ b/woof-code/rootfs-skeleton/usr/sbin/run-as-spot
@@ -13,9 +13,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -36,7 +36,7 @@ APP="$1"; shift
 ARGS=""
 [ $1 ] && while [ "$1" ]; do ARGS="$ARGS \"$1\""; shift; done
 if [ $(id -u) -eq 0 ]; then
- [ $XAUTHORITY ] && cp $XAUTHORITY /root/spot/.Xauthority 2>/dev/null
+ [ $XAUTHORITY ] && cp $VERB $XAUTHORITY /root/spot/.Xauthority 2>/dev/null
  touch /root/spot/.Xauthority
  #following line is mostly there to catch any root:root files that may have got copied in...
  chown -R spot:spot /root/spot &
diff --git a/woof-code/rootfs-skeleton/usr/sbin/t12s b/woof-code/rootfs-skeleton/usr/sbin/t12s
--- a/woof-code/rootfs-skeleton/usr/sbin/t12s
+++ b/woof-code/rootfs-skeleton/usr/sbin/t12s
@@ -30,9 +30,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -63,10 +63,10 @@ if [ "${LANG#*.}" = "$LANG" ]; then
  then restart X server and start again please</big>"
  [[ $? -eq 1 || $? -eq 252 ]] && exit 0
  /usr/sbin/chooselocale
- ln -s "`pwd`/$RESTART" ${HOME}/Startup/t12s
+ ln $VERB -s "`pwd`/$RESTART" ${HOME}/Startup/t12s
  exit 0
 else
- rm ${HOME}/Startup/t12s 2>/dev/null
+ rm $VERB ${HOME}/Startup/t12s 2>/dev/null
 fi
 
 # the following texts will hopefully give you the idea of this script
@@ -206,7 +206,7 @@ if [ "`grep -E '^[^#].*_M_:-' $myfile`" ]; then # id numbering of messages
   will be made as
     ${myfile}_bak."
  #read x
- cp ${myfile} ${myfile}_bak
+ cp $VERB ${myfile} ${myfile}_bak
 
  # put id numbers into myfile
  while read LINE ; do # just 1 second, sed ///g needed for multiple use, example: please wait...
@@ -221,7 +221,7 @@ if [ "`grep -E '^[^#].*_M_:-' $myfile`" ]; then # id numbering of messages
   sed -e "s${delim}_M_:-${LINE}${delim}_M_${i}:-${LINE}${delim}g" ${myfile} > ${myfile}_$i
   # need to test file sizes, success if different
   if [[ `ls -l ${myfile}_$i | cut -d ' ' -f 5` -gt `ls -l ${myfile} | cut -d ' ' -f 5` ]]; then
-   mv ${myfile}_$i ${myfile}
+   mv $VERB ${myfile}_$i ${myfile}
   else #always if \" was used
    chmod +x ${myfile}
    yad --text="Sorry, could not write number $i for
@@ -273,7 +273,7 @@ while [ 1=1 ]; do
   esac
  done
  echo $this_LANG
- [ ! -d "${T}/${this_LANG}" ] && mkdir ${T}/${this_LANG}
+ [ ! -d "${T}/${this_LANG}" ] && mkdir $VERB ${T}/${this_LANG}
 
  # extract English messages from script: create temporary English language file
   grep _M_ $myfile | cut -d "{" -f 2- | rev | cut -d "}" -f 2- | rev \
@@ -281,20 +281,20 @@ while [ 1=1 ]; do
 
  # dialect starts with copy of base language, ex: fr_CA copied from fr
  if [ ${#this_LANG} -gt 4 -a ! -f ${T}/${this_LANG}/${app} ]; then
-    cp ${T}/${this_LANG%_*}/${app} ${T}/${this_LANG}
+    cp $VERB ${T}/${this_LANG%_*}/${app} ${T}/${this_LANG}
     [ $! ] || existing_translations="$existing_translations ${this_LANG}"
  fi
 
  # merge existing translation
  #if [[ $existing_translations =~ "$this_LANG" ]]; then # merge # no: pt =~ pt_BR
  if [[ `grep -E "^${this_LANG}$" $available_lang_list` ]]; then # merge
-  mv ${T}/${this_LANG}/${app} ${T}/${this_LANG}/${app}_tmp
+  mv $VERB ${T}/${this_LANG}/${app} ${T}/${this_LANG}/${app}_tmp
   while read LINE; do #comment for no more existing ones, but once only
    [ "`grep -E ${LINE%=*} /dev/shm/t12s_${app}_en`" ] && comment="" || comment="#"
    [[ "${LINE:0:1}" = "#" ]] && comment=""
    echo ${comment}${LINE} >> ${T}/${this_LANG}/${app}
   done < ${T}/${this_LANG}/${app}_tmp
-  rm ${T}/${this_LANG}/${app}_tmp
+  rm $VERB ${T}/${this_LANG}/${app}_tmp
   while read LINE; do #append new ones
    [ "`grep -E ${LINE%=*} ${T}/${this_LANG}/${app}`" ] \
    || echo $LINE >> ${T}/${this_LANG}/${app}
@@ -311,7 +311,7 @@ while [ 1=1 ]; do
   elif [ 1 = 2 ] ; then #automated translation available...
 
   FROM=/C/
- [ ! -d /usr/share/locales/C/ ] && mkdir /usr/share/locales/C/
+ [ ! -d /usr/share/locales/C/ ] && mkdir $VERB /usr/share/locales/C/
  #for x in $@ ; do
  for x in $myfile ; do
  #   TEMPLATE=/usr/share/locales/C/${x##*/}.txt
@@ -321,11 +321,11 @@ while [ 1=1 ]; do
         *{_M_*)B=_M${A##*_M};B=${B%%\}*};echo ${B//:-/=};;
      esac
   done < $x >${TEMPLATE}
-  mv ${TEMPLATE} ${TEMPLATE}m; sort -u ${TEMPLATE}m>${TEMPLATE}; rm ${TEMPLATE}m
+  mv $VERB ${TEMPLATE} ${TEMPLATE}m; sort -u ${TEMPLATE}m>${TEMPLATE}; rm $VERB ${TEMPLATE}m
   #for x in es nl pt ru ; do
   for x in $this_LANG ; do
    TO=/${x//-/_}/
-   [ ! -d ${TEMPLATE%%/C/*}/${x//-/_} ] && mkdir ${TEMPLATE%%/C/*}/${x//-/_}
+   [ ! -d ${TEMPLATE%%/C/*}/${x//-/_} ] && mkdir $VERB ${TEMPLATE%%/C/*}/${x//-/_}
    curl -A firefox \
     -F "file=@$TEMPLATE;type=text/plain" \
     -F "sl=en" \
@@ -339,18 +339,18 @@ while [ 1=1 ]; do
       esac
       [ "$A" ] && echo ${A// = /=\"}\"
     done > ${TEMPLATE//$FROM/$TO}
-    mv ${T}/${x}/${app}.txt  ${T}/${x}/${app}
+    mv $VERB ${T}/${x}/${app}.txt  ${T}/${x}/${app}
     #
     #curl: (6) Couldn't resolve host 'translate.googleusercontent.com' : empty file
     #
     # file is not utf-8 but iso-8859
     #
    done
-   rm $TEMPLATE
+   rm $VERB $TEMPLATE
   done  #automated translation available...
 
   else # copy English to this_LANG
-   cp /dev/shm/t12s_${app}_en ${T}/${this_LANG}/${app}
+   cp $VERB /dev/shm/t12s_${app}_en ${T}/${this_LANG}/${app}
   fi
  fi
 
@@ -394,7 +394,7 @@ while [ 1=1 ]; do
                    --button="gtk-ok:0" )
             [ "$new_msgtr" = "$msgtr" ] && continue
             # update translation file
-            mv ${T}/${this_LANG}/${app} ${T}/${this_LANG}/${app}_old
+            mv $VERB ${T}/${this_LANG}/${app} ${T}/${this_LANG}/${app}_old
             while read LINE; do
              [ "${LINE%=*}" != "$msgID" ] && out="$LINE" || out="${msgID}=\"${new_msgtr}\""
              echo $out >> ${T}/${this_LANG}/${app}
@@ -405,7 +405,7 @@ while [ 1=1 ]; do
                --text="Select a line before OK button please" \
                --button="gtk-ok:0"
           fi ;;
-       9) cp ${T}/${this_LANG}/${app}_old ${T}/${this_LANG}/${app} ;;
+       9) cp $VERB ${T}/${this_LANG}/${app}_old ${T}/${this_LANG}/${app} ;;
   esac
 
  done # /loop translate item --------------------------------------------------
diff --git a/woof-code/rootfs-skeleton/usr/sbin/video-wizard b/woof-code/rootfs-skeleton/usr/sbin/video-wizard
--- a/woof-code/rootfs-skeleton/usr/sbin/video-wizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/video-wizard
@@ -15,9 +15,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -160,14 +160,14 @@ echo -n "$CHOSENXOPTIONS" >/etc/xextraoptions
 
 if [ "$CHOSENBUTTON" = "TESTBUTTON" ];then
  touch /tmp/pup_event_icon_change_flag #v404 see /sbin/clean_desk_icons (called from .xinitrc).
- rm -f /tmp/Xflag #prevent endless restarts. see /usr/bin/xwin.
+ rm $VERB -f /tmp/Xflag #prevent endless restarts. see /usr/bin/xwin.
  exec killall X #restart X in new test mode.
 fi
 
 if [ "$CHOSENBUTTON" = "OKAYBUTTON" ];then
  echo -n "$CHOSENMODE" >/etc/videomode
- rm -f /tmp/videomode
- rm -f /tmp/Xflag #prevent endless restarts. see xwin*.
+ rm $VERB -f /tmp/videomode
+ rm $VERB -f /tmp/Xflag #prevent endless restarts. see xwin*.
 fi
 
 if [ $PUPMODE -eq 5 ];then
diff --git a/woof-code/rootfs-skeleton/usr/sbin/xf86svga336wizard b/woof-code/rootfs-skeleton/usr/sbin/xf86svga336wizard
--- a/woof-code/rootfs-skeleton/usr/sbin/xf86svga336wizard
+++ b/woof-code/rootfs-skeleton/usr/sbin/xf86svga336wizard
@@ -36,9 +36,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -179,7 +179,7 @@ Change that to \"24\" if you need greater color depth.
 
 WHAT TO DO IF XF86_SVGA WILL NOT WORK!
 You can drop back to the Xvesa Kdrive X server by typing this:
-# ln -sf Xvesa /usr/X11R6/bin/X
+# ln $VERB -sf Xvesa /usr/X11R6/bin/X
 # xwin
 
 Note also that the $pupPKGMgr package has \"xvidtune\", and docs are in
@@ -200,12 +200,12 @@ if [ $RETVAL -eq 11 ];then #run xf86config
  exec restartwm #no w.m. param, defaults to current.
 fi
 if [ $RETVAL -eq 12 ];then #change to Xvesa
- ln -sf Xvesa /usr/X11R6/bin/X
+ ln $VERB -sf Xvesa /usr/X11R6/bin/X
  _sync
  exec restartwm
 fi
 if [ $RETVAL -eq 13 ];then #change to XF86_SVGA
- ln -s XF86_SVGA /usr/X11R6/bin/X
+ ln $VERB -s XF86_SVGA /usr/X11R6/bin/X
  xmessage -center -bg orange "X is now going to die. Please close all APPs. At the commandline, type \"xf86config\""
  _sync
  #exec killall X
diff --git a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard-automatic b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard-automatic
--- a/woof-code/rootfs-skeleton/usr/sbin/xorgwizard-automatic
+++ b/woof-code/rootfs-skeleton/usr/sbin/xorgwizard-automatic
@@ -21,9 +21,9 @@ MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
  set +e
- source /etc/rc.d/f4puppy5 && {
+ . /etc/rc.d/f4puppy5 && {
  set +n
- source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+ . /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
 
 ADD_PARAMETER_LIST=
 ADD_PARAMETERS=
@@ -43,10 +43,10 @@ _trap
 #120517
 if [ "`which ddcprobe`" = "" ];then
  #running on an arm board...
- cp -f /etc/X11/xorg.conf-auto-pc /etc/X11/xorg.conf
+ cp $VERB -f /etc/X11/xorg.conf-auto-pc /etc/X11/xorg.conf
  echo "#PuppyHardwareProfile=armsystem" >> /etc/X11/xorg.conf
  #create a copy of xorg.conf with the profile in the filename...
- cp -af /etc/X11/xorg.conf /etc/X11/xorg.conf.armsystem
+ cp $VERB -af /etc/X11/xorg.conf /etc/X11/xorg.conf.armsystem
  echo
  echo "Xorg Wizard Automatic has just run."
  echo "If you are reading this, then you are at the console without X running."
@@ -131,7 +131,7 @@ if [ -s /tmp/ddcprobe.txt ];then #110727 ddcprobe segfaults on my new laptop.
    fi
   else
    #in case plug usb or multisession-cd into different pc...
-   [ -f /etc/resolutionfix ] && rm -f /etc/resolutionfix
+   [ -f /etc/resolutionfix ] && rm $VERB -f /etc/resolutionfix
   fi
  fi
 fi
@@ -179,7 +179,7 @@ if [ "$TOUCHPAD" ];then
  if [ "`lsmod | grep '^evdev'`" = "" ];then
   REGEXt0="s%^ADDLIST=.*%ADDLIST='${ADDLIST} evdev '%"
   sed -i -e "$REGEXt0" /etc/rc.d/MODULESCONFIG #so evdev module will load next bootup.
-  modprobe evdev
+  modprobe $Q $VERB evdev
  fi
 
  if vercmp $XORGVER lt 1.9.0; then #110701
