/usr/local/bin/pupzip : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pupzip b/woof-code/rootfs-skeleton/usr/local/bin/pupzip
--- a/woof-code/rootfs-skeleton/usr/local/bin/pupzip
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pupzip
@@ -250,22 +250,27 @@ RPM extraction program, that PupZip will automatically use if present."
    cd $CDIR
    exit
    ;;
+
+   *)
+__unpack_debian__(){
 #v4.00 remove...
-#  deb|DEB)
-#   mkdir /tmp/temprpm
-#   cd /tmp/temprpm
-#   $DPKGDEB -x "$FULLSPEC"
-#   if [ ! $? -eq 0 ];then
-#    exec xmessage -bg "orange red" -center -title "PupZip: ERROR" "An error has occurred opening the DEB file."
-#   fi
-#   tar -c -f /tmp/temprpm.tar .
-#   rm -rf /tmp/temprpm
-#   cd /
-#   $XARCHIVE /tmp/temprpm.tar
-#   rm -f /tmp/temprpm.tar
-#   cd $CDIR
-#   exit
-#   ;;
+  deb|DEB)
+   mkdir /tmp/temprpm
+   cd /tmp/temprpm
+   $DPKGDEB -x "$FULLSPEC"
+   if [ ! $? -eq 0 ];then
+    exec xmessage -bg "orange red" -center -title "PupZip: ERROR" "An error has occurred opening the DEB file."
+   fi
+   tar -c -f /tmp/temprpm.tar .
+   rm -rf /tmp/temprpm
+   cd /
+   $XARCHIVE /tmp/temprpm.tar
+   rm -f /tmp/temprpm.tar
+   cd $CDIR
+   exit
+}
+   ;;
+
  esac
 
  echo "NOW ABOUT TO EXEC XARCHIVE $XARCHIVE \"$PARAMIN\""
