woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns: Added Header.

diff --git a/woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns b/woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns
--- a/woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns
+++ b/woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns
@@ -36,6 +36,29 @@
 # exit
 #fi
 
+  _TITLE_=
+_COMMENT_=""
+
+MY_SELF="$0"
+
+test -f /etc/rc.d/f4puppy5 && {
+ set +e
+ source /etc/rc.d/f4puppy5 && {
+ set +n
+ source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."
+
+ADD_PARAMETER_LIST=
+ADD_PARAMETERS=
+_provide_basic_parameters
+
+ADD_HELP_MSG="$_COMMENT_"
+_parse_basic_parameters "$@"
+[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
+for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+} || echo "Warning : No /etc/rc.d/f4puppy5 installed."
+
 BIGGESTCNT=0
 echo -n '' > /tmp/sns_interfaces
 INTERFACES="`ifconfig -a | grep -F 'Link encap:Ethernet' | cut -f1 -d' ' | tr '\n' ' '`"
@@ -85,7 +108,7 @@ do
  ALL_IF_DRIVER="${ALL_IF_DRIVER}|${IF_DRIVER}"
  ALL_IF_BUS="${ALL_IF_BUS}|${IF_BUS}"
  ALL_IF_INFO="${ALL_IF_INFO}|${IF_INFO}"
- INTERFACEBUTTONS="${INTERFACEBUTTONS} 
+ INTERFACEBUTTONS="${INTERFACEBUTTONS}
   <button><label>${INTERFACE}</label><action type=\"exit\">Interface_${INTERFACE}</action></button>"
  #save all data about each interface on one line...
  #ex: wlan1|Wireless|ath5k|pci|Support for 5xxx series of Atheros 802.11 wireless LAN cards
@@ -139,7 +162,7 @@ CLICKMSG="<text><label>Puppy has identified these network interfaces on your com
 #100313 add a button for loading a Windows driver...
 if [ "`echo "$ALL_IF_DRIVER" | grep 'ndiswrapper'`" == "" ];then
  CLICKMSG="<text><label>Puppy has identified these network interfaces on your computer. Click a button to configure the interface for use, or click 'Windows' button if you want to install and use a MS Windows driver:</label></text>"
- INTERFACEBUTTONS="${INTERFACEBUTTONS} 
+ INTERFACEBUTTONS="${INTERFACEBUTTONS}
   <button><label>Windows</label><action type=\"exit\">Interface_Windows</action></button>"
 fi
 
@@ -213,7 +236,7 @@ if [ "$INTERFACE" == "Windows" ];then #100313
  if [ "`echo "$RETSTRND" | grep '^EXIT' | grep 'OK'`" != "" ];then
   INFFILE="`echo "$RETSTRND" | grep '^INF_FILE_NAME' | cut -f 2 -d '"'`" #'geany
   case "$INFFILE" in
-   *.[iI][nN][fF]) 
+   *.[iI][nN][fF])
     FLAGND=""
     ndiswrapper -i "$INFFILE" #installs driver at /etc/ndiswrapper.
     if [ $? -eq 0 ];then
@@ -228,7 +251,7 @@ if [ "$INTERFACE" == "Windows" ];then #100313
     [ "$FLAGND" != "ok" ] && xmessage -center -bg red "ERROR: Windows driver does not seem to work, it has been uninstalled"
     [ "$FLAGND" == "ok" ] && sleep 1
    ;;
-   *) 
+   *)
     xmessage -center -bg red "ERROR, ${INFFILE} is not a .inf file"
    ;;
   esac
@@ -308,14 +331,14 @@ if [ "$IF_INTTYPE" == "Wireless" ];then
    echo "$ONELINE" >> /tmp/sns_scan_rawoneline
    echo "${CELL_NUMBER}|${CELL_ADDRESS}|${CELL_CHANNEL}|${CELL_QUALITY}|${CELL_ENCRYPTIONKEY}|${CELL_ESSID}" >> /tmp/sns_scan_oneline
   done
- 
+
   #my wpa_supplicant only supports: wext hostap atmel wired ralink roboswitch
   case $IF_DRIVER in
    hostap*)   WPA_DRIVER="hostap" ;;
    rt61|rt73) WPA_DRIVER="ralink" ;;
    *)         WPA_DRIVER="wext" ;;
   esac
- 
+
   if [ ! -f /tmp/sns_scan_radiobuttons ];then
    FRAME1="<frame Wireless networks><text><label>\" \"</label></text><text><label>No wireless networks found</label></text></frame><text><label>\" \"</label></text>"
    FRAME2=""
@@ -355,7 +378,7 @@ if [ "$IF_INTTYPE" == "Wireless" ];then
    </hbox>
   </vbox>
   </window>"
-  RETSTRING="`gtkdialog3 --program=WIN2_DLG --center`" 
+  RETSTRING="`gtkdialog3 --program=WIN2_DLG --center`"
   [ "`echo "$RETSTRING" | grep '^EXIT' | grep 'BUT_GOBACK'`" != "" ] && exec sns
   [ "`echo "$RETSTRING" | grep '^EXIT' | grep 'BUT_CONNECT'`" == "" ] && exit
 
@@ -369,8 +392,8 @@ if [ "$IF_INTTYPE" == "Wireless" ];then
    WPAPSKAES)  SEC_MGMT="WPA-PSK"; WPA_ENC="AES" ;;
    WPA2PSKAES) SEC_MGMT="WPA2-PSK"; WPA_ENC="AES"  ;;
    *)          SEC_KEY="" ;; #no encryption.
-  esac 
- 
+  esac
+
   CELL_NUMBER="`echo "$RETSTRING" | grep '^RADIO' | grep 'true' | cut -f1 -d'=' | cut -f2 -d'_'`" #ex: 01
   cnPATTERN='^'"$CELL_NUMBER"'|'
   CELLDATA="`grep "$cnPATTERN" /tmp/sns_scan_oneline`"
@@ -379,13 +402,13 @@ if [ "$IF_INTTYPE" == "Wireless" ];then
   CELL_QUALITY="`echo -n "$CELLDATA" | cut -f4 -d'|'`"
   CELL_ENCRYPTIONKEY="`echo -n "$CELLDATA" | cut -f5 -d'|'`"
   CELL_ESSID="`echo -n "$CELLDATA" | cut -f6 -d'|'`"
- 
+
   if [ "$CELL_ENCRYPTIONKEY" == "on" ];then
    [ "$SEC_KEY" == "" ] && FLAGERR=2
    [ "$SEC_MGMT" == "" ] && FLAGERR=3
   fi
   if [ ! $FLAGERR ];then
- 
+
    #xmessage -center -bg orange -buttons "" "Please wait, attempting to connect to '${CELL_ESSID}'..." &
    yaf-splash -placement center -bg orange -text "Please wait, attempting to connect to '${CELL_ESSID}'..." &
    PIDX=$!
@@ -400,7 +423,7 @@ if [ "$IF_INTTYPE" == "Wireless" ];then
    if [ $? -ne 0 ];then
     FLAGERR=4
    else
-   
+
     RUNWPASUPP='no'
     [ -f "/etc/simple_network_setup/wpa_supplicant.conf-${CELL_ESSID}-${MACADDRESS}" ] && rm -f "/etc/simple_network_setup/wpa_supplicant.conf-${CELL_ESSID}-${MACADDRESS}"
     FIXUP='1 1 2 0'
@@ -435,7 +458,7 @@ network={
          killall wpa_supplicant
         fi
        ;;
-       WPA*)  
+       WPA*)
         #it works psk="passphrase" (with quotes), but for security encode psk into hex string...
         hexSEC_KEY=`wpa_passphrase "$CELL_ESSID" $SEC_KEY | grep '[^#]psk=' | cut -f 2 -d '='`
         echo "ctrl_interface=/var/run/wpa_supplicant
@@ -458,10 +481,10 @@ network={
        ;;
       esac
      fi
- 
+
      echo "STEP5a: ifconfig $INTERFACE up" >> /tmp/sns_wireless_log
      ifconfig $INTERFACE up
-  
+
      if [ "$RUNWPASUPP" = "yes" ];then
       echo "STEP5b: wpa_supplicant -B -D${WPA_DRIVER} -i${INTERFACE} -c\"/etc/simple_network_setup/wpa_supplicant.conf-${CELL_ESSID}-${MACADDRESS}\"" >> /tmp/sns_wireless_log
       wpa_supplicant -B -D${WPA_DRIVER} -i${INTERFACE} -c"/etc/simple_network_setup/wpa_supplicant.conf-${CELL_ESSID}-${MACADDRESS}" >> /tmp/sns_wireless_log 2>&1
@@ -505,7 +528,7 @@ network={
       [ "`iwconfig $INTERFACE | grep "$INTERFACE" | grep "ESSID"`" != "" ] && iwconfig $INTERFACE essid off
       ifconfig $INTERFACE down
      else
- 
+
       #wait until access point becomes available...
       sCNT=0
       while [ 1 ];do
@@ -541,7 +564,7 @@ network={
        [ "`iwconfig $INTERFACE | grep "$INTERFACE" | grep "ESSID"`" != "" ] && iwconfig $INTERFACE essid off
        ifconfig $INTERFACE down
       else
-    
+
        #finally, run dhcpcd...
        MODTIME1="`stat --format=%Y /etc/resolv.conf`"
        for iterDHCPCD in a b #100320
@@ -564,7 +587,7 @@ network={
        done
        [ "$MODTIME2" == "$MODTIME1" ] && FLAGERR=6
        [ "`grep -v '^#' /etc/resolv.conf`" == "" ] && FLAGERR=6
-        
+
        if [ $FLAGERR ];then
         if [ "`pidof wpa_supplicant`" != "" ];then
          wpa_cli terminate
@@ -678,7 +701,7 @@ if [ "$IF_INTTYPE" == "Wired" ];then
  Interface: $INTERFACE  Driver: $IF_DRIVER  Bus: $IF_BUS  MacAddress: $MACADDRESS
  Description: $IF_INFO
  " > /tmp/sns_wired_log
- 
+
  MODTIME1="1"; MODTIME2="1"
  ifconfig $INTERFACE up >> /tmp/sns_wired_log 2>&1
  [ $? -eq 0 ] && MODTIME2="0"
