/etc/init.d/02_hal: Break correctly . Minor code cleanup . Use bash instaed sh since it uses arrays.

diff --git a/woof-code/rootfs-skeleton/etc/init.d/02_hal b/woof-code/rootfs-skeleton/etc/init.d/02_hal
--- a/woof-code/rootfs-skeleton/etc/init.d/02_hal
+++ b/woof-code/rootfs-skeleton/etc/init.d/02_hal
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # Start/stop/restart the hal daemon:
 # slackware script, modified for woof/puppy dec 2008, BK.
 
@@ -44,9 +44,11 @@ esac
 
 #PIDFILE=/var/run/hald/hald.pid
 PIDFILE=/var/run/hald/pid
-mkdir -p /var/run/hald/
+mkdir $VERB -p ${PIDFILE%/*}
 
 hal_start() {
+
+	# REM: Bash array of options
     CUSTOM_[431]='--use-syslog --retain-privileges --verbose=yes'
     CUSTOM_[421]='--use-syslog --drop-privileges --verbose=yes'
     CUSTOM_[41]='--use-syslog --verbose=yes'
@@ -80,7 +82,7 @@ hal_start() {
       $daemon --daemon=yes ${CUSTOM_[$a]}
       sleep 5s
       DAEMON=$daemon;CUSTOM="${CUSTOM_[$a]}";
-      [ "`pidof hald`" ] && { break;break;break;break; }
+      [ "`pidof hald`" ] && { break 2; }
       fi
 
        for b in 1 2 3 4;do
@@ -89,7 +91,7 @@ hal_start() {
          $daemon --daemon=yes ${CUSTOM_[$a$b]}
          sleep 7.5s
          DAEMON=$daemon;CUSTOM="${CUSTOM_[$a]}";
-         [ "`pidof hald`" ] && { break;break;break; }
+         [ "`pidof hald`" ] && { break 3; }
         fi
 
          for c in 1 2 3 4;do
@@ -98,7 +100,7 @@ hal_start() {
           $daemon --daemon=yes ${CUSTOM_[$a$b$c]}
           sleep 10s
           DAEMON=$daemon;CUSTOM="${CUSTOM_[$a]}";
-          [ "`pidof hald`" ] && { break;break; }
+          [ "`pidof hald`" ] && { break 4; }
           fi
          done
        done
@@ -129,15 +131,15 @@ hal_start() {
 }
 
 hal_stop() {
- pidof hald || echo "Notice: Hald not running ."
-  if [ -e "$PIDFILE" ]; then
+ pidof hald || echo "Notice: Hal daemon not running ."
+  if [ -s "$PIDFILE" ]; then
     kill $(cat $PIDFILE)
-    rm -f $PIDFILE
+    rm $VERB -f $PIDFILE
   fi
   # Just in case:
- pidof hald && killall hald 1>$OUT 2>$ERR
+ pidof hald >>$OUT && killall hald 1>>$OUT 2>>$ERR
  sleep 2
- pidof hald && echo "Error: Hald still running ." || echo "Stopped Hal daemon ."
+ pidof hald >>$OUT && echo "Error: Hald still running ." || echo "Stopped Hal daemon ."
 }
 
 # See how we were called.
