/etc/init.d/cups: Create /dev/lp0 and symlink /dev/unknoen-parallel0 -> lp0 . Space Clean Up.

diff --git a/woof-code/rootfs-skeleton/etc/init.d/cups b/woof-code/rootfs-skeleton/etc/init.d/cups
--- a/woof-code/rootfs-skeleton/etc/init.d/cups
+++ b/woof-code/rootfs-skeleton/etc/init.d/cups
@@ -1,10 +1,10 @@
 #!/bin/sh
 #
-# "$Id: cups.sh.in 6649 2007-07-11 21:46:42Z mike $"
+# "$Id: cups.sh.in 3940 2012-10-15 21:02:10Z msweet $"
 #
-#   Startup/shutdown script for the Common UNIX Printing System (CUPS).
+#   Startup/shutdown script for CUPS.
 #
-#   Copyright 2007 by Apple Inc.
+#   Copyright 2007-2012 by Apple Inc.
 #   Copyright 1997-2007 by Easy Software Products, all rights reserved.
 #
 #   These coded instructions, statements, and computer programs are the
@@ -20,8 +20,7 @@
 #   Linux chkconfig stuff:
 #
 #   chkconfig: 235 99 00
-#   description: Startup/shutdown script for the Common UNIX \
-#                Printing System (CUPS).
+#   description: Startup/shutdown script for CUPS.
 #
 
 #
@@ -32,66 +31,50 @@
 # REQUIRE: DAEMON
 #
 
-case $2 in
-[0-9]*) safeBOOT=$2;;
-""|*) :;;
-esac
 
 #### OS-Dependent Configuration
 
 case "`uname`" in
-	IRIX*)
-		IS_ON=/sbin/chkconfig
+    *BSD*)
+            IS_ON=:
+        ECHO=echo
+        ECHO_OK=:
+        ECHO_ERROR=:
+        ;;
 
-		if $IS_ON verbose; then
-			ECHO=echo
-		else
-			ECHO=:
-		fi
-		ECHO_OK=:
-		ECHO_ERROR=:
-		;;
+    Darwin*)
+        . /etc/rc.common
 
-	*BSD*)
-        	IS_ON=:
-		ECHO=echo
-		ECHO_OK=:
-		ECHO_ERROR=:
-		;;
+        if test "${CUPS:=-YES-}" = "-NO-"; then
+            exit 0
+        fi
 
-	Darwin*)
-		. /etc/rc.common
+            IS_ON=:
+        ECHO=ConsoleMessage
+        ECHO_OK=:
+        ECHO_ERROR=:
+        ;;
 
-		if test "${CUPS:=-YES-}" = "-NO-"; then
-			exit 0
-		fi
+    Linux*)
+        IS_ON=/bin/true
+        if test -f /etc/init.d/functions; then
+            . /etc/init.d/functions
+            ECHO=echo
+            ECHO_OK="echo_success"
+            ECHO_ERROR="echo_failure"
+        else
+            ECHO=echo
+            ECHO_OK=:
+            ECHO_ERROR=:
+        fi
+        ;;
 
-        	IS_ON=:
-		ECHO=ConsoleMessage
-		ECHO_OK=:
-		ECHO_ERROR=:
-		;;
-
-	Linux*)
-		IS_ON=/bin/true
-		if test -f /etc/init.d/functions; then
-			. /etc/init.d/functions
-			ECHO=echo
-			ECHO_OK="echo_success"
-			ECHO_ERROR="echo_failure"
-		else
-			ECHO=echo
-			ECHO_OK=:
-			ECHO_ERROR=:
-		fi
-		;;
-
-	*)
-		IS_ON=/bin/true
-		ECHO=echo
-		ECHO_OK=:
-		ECHO_ERROR=:
-		;;
+    *)
+        IS_ON=/bin/true
+        ECHO=echo
+        ECHO_OK=:
+        ECHO_ERROR=:
+        ;;
 esac
 
 #### OS-Independent Stuff
@@ -104,21 +87,21 @@ esac
 #
 
 for file in /etc/TIMEZONE /etc/rc.config /etc/sysconfig/clock; do
-	if test -f $file; then
-	        . $file
-	fi
+    if test -f $file; then
+            . $file
+    fi
 done
 
 if test "x$ZONE" != x; then
-	TZ="$ZONE"
+    TZ="$ZONE"
 fi
 
 if test "x$TIMEZONE" != x; then
-	TZ="$TIMEZONE"
+    TZ="$TIMEZONE"
 fi
 
 if test "x$TZ" != x; then
-	export TZ
+    export TZ
 fi
 
 #
@@ -137,9 +120,9 @@ unset TMPDIR
 #
 
 if test "x$PATH" = x; then
-	PATH="/bin:/usr/bin:/sbin:/usr/sbin"
+    PATH="/bin:/usr/bin:/sbin:/usr/sbin"
 else
-	PATH="/bin:/usr/bin:/sbin:/usr/sbin:$PATH"
+    PATH="/bin:/usr/bin:/sbin:/usr/sbin:$PATH"
 fi
 
 export PATH
@@ -149,25 +132,25 @@ export PATH
 #
 
 case "`uname`" in
-	HP-UX* | AIX* | SINIX*)
-		pid=`ps -e | awk '{if (match($4, ".*/cupsd$") || $4 == "cupsd") print $1}'`
-		;;
-	IRIX* | SunOS*)
-		pid=`ps -e | nawk '{if (match($4, ".*/cupsd$") || $4 == "cupsd") print $1}'`
-		;;
-	UnixWare*)
-		pid=`ps -e | awk '{if (match($6, ".*/cupsd$") || $6 == "cupsd") print $1}'`
-		. /etc/TIMEZONE
-		;;
-	OSF1*)
-		pid=`ps -e | awk '{if (match($5, ".*/cupsd$") || $5 == "cupsd") print $1}'`
-		;;
-	Linux* | *BSD* | Darwin*)
-		pid=`ps ax | awk '{if (match($5, ".*/cupsd$") || $5 == "cupsd") print $1}'`
-		;;
-	*)
-		pid=""
-		;;
+    HP-UX* | AIX* | SINIX*)
+        pid=`ps -e | awk '{if (match($4, ".*/cupsd$") || $4 == "cupsd") print $1}'`
+        ;;
+    SunOS*)
+        pid=`ps -e | nawk '{if (match($4, ".*/cupsd$") || $4 == "cupsd") print $1}'`
+        ;;
+    UnixWare*)
+        pid=`ps -e | awk '{if (match($6, ".*/cupsd$") || $6 == "cupsd") print $1}'`
+        . /etc/TIMEZONE
+        ;;
+    OSF1*)
+        pid=`ps -e | awk '{if (match($5, ".*/cupsd$") || $5 == "cupsd") print $1}'`
+        ;;
+    Linux* | *BSD* | Darwin*)
+        pid=`ps ax | awk '{if (match($5, ".*/cupsd$") || $5 == "cupsd") print $1}'`
+        ;;
+    *)
+        pid=""
+        ;;
 esac
 
 #
@@ -175,55 +158,64 @@ esac
 #
 
 case $1 in
-	start | restart | reload)
-		if $IS_ON cups; then
-			if test "$pid" != ""; then
-				kill -HUP $pid
-			else
-				prefix=/
-				exec_prefix=/usr
-				/usr/sbin/cupsd
-				if test $? != 0; then
-					$ECHO_FAIL
-					$ECHO "cups: unable to $1 scheduler."
-					exit 1
-				fi
-			fi
-			$ECHO_OK
-			$ECHO "cups: ${1}ed scheduler."
-		fi
-		;;
+    start | restart | reload)
 
-	stop)
-		if test "$pid" != ""; then
-			kill $pid
-			$ECHO_OK
-			$ECHO "cups: stopped scheduler."
-		fi
-		;;
+    # make device nodes
+    test -c /dev/lp0 || { rm -rf /dev/lp0; mknod /dev/lp0 c 6 0; }
+    test -L /dev/unknown-parallel0 || { rm -rf /dev/unknown-parallel0; ln -sf lp0 /dev/unknown-parallel0; }
 
-	status)
-		if test "$pid" != ""; then
-			echo "cups: scheduler is running."
-		else
-			echo "cups: scheduler is not running."
-		fi
-		;;
+        if $IS_ON cups; then
+            if test -x /sbin/portrelease; then
+                /sbin/portrelease cups
+            fi
 
-	start_msg)
-		# HP-UX non-standard...
-		echo "Starting CUPS Server"
-		;;
+            if test "$pid" != ""; then
+                kill -HUP $pid
+            else
+                prefix=/usr/print
+                exec_prefix=/usr/print
+                /usr/print/sbin/cupsd
+                if test $? != 0; then
+                    $ECHO_FAIL
+                    $ECHO "cups: unable to $1 scheduler."
+                    exit 1
+                fi
+            fi
+            $ECHO_OK
+            $ECHO "cups: ${1}ed scheduler."
+        fi
+        ;;
 
-	stop_msg)
-		# HP-UX non-standard...
-		echo "Starting CUPS Server"
-		;;
+    stop)
+        if test "$pid" != ""; then
+            kill $pid
+            $ECHO_OK
+            $ECHO "cups: stopped scheduler."
+        fi
+        ;;
 
-	*)
-		echo "Usage: cups {reload|restart|start|status|stop}"
-		exit 1
-		;;
+    status)
+        if test "$pid" != ""; then
+            echo "cups: scheduler is running."
+        else
+            echo "cups: scheduler is not running."
+        fi
+        ;;
+
+    start_msg)
+        # HP-UX non-standard...
+        echo "Starting CUPS Server"
+        ;;
+
+    stop_msg)
+        # HP-UX non-standard...
+        echo "Starting CUPS Server"
+        ;;
+
+    *)
+        echo "Usage: cups {reload|restart|start|status|stop}"
+        exit 1
+        ;;
 esac
 
 #
@@ -234,5 +226,5 @@ exit 0
 
 
 #
-# End of "$Id: cups.sh.in 6649 2007-07-11 21:46:42Z mike $".
+# End of "$Id: cups.sh.in 3940 2012-10-15 21:02:10Z msweet $".
 #
