/etc/rc.d/rc.sysinit and /etc/init.d/ : Code cleanups.

diff --git a/woof-code/rootfs-skeleton/etc/init.d/cups b/woof-code/rootfs-skeleton/etc/init.d/cups
--- a/woof-code/rootfs-skeleton/etc/init.d/cups
+++ b/woof-code/rootfs-skeleton/etc/init.d/cups
@@ -45,58 +45,58 @@
 #### OS-Dependent Configuration
 
 case "`uname`" in
-	IRIX*)
-		IS_ON=/sbin/chkconfig
+    IRIX*)
+        IS_ON=/sbin/chkconfig
 
-		if $IS_ON verbose; then
-			ECHO=echo
-		else
-			ECHO=:
-		fi
-		ECHO_OK=:
-		ECHO_ERROR=:
-		;;
+        if $IS_ON verbose; then
+            ECHO=echo
+        else
+            ECHO=:
+        fi
+        ECHO_OK=:
+        ECHO_ERROR=:
+        ;;
 
-	*BSD*)
-        	IS_ON=:
-		ECHO=echo
-		ECHO_OK=:
-		ECHO_ERROR=:
-		;;
+    *BSD*)
+            IS_ON=:
+        ECHO=echo
+        ECHO_OK=:
+        ECHO_ERROR=:
+        ;;
 
-	Darwin*)
-		. /etc/rc.common
+    Darwin*)
+        . /etc/rc.common
 
-		if test "${CUPS:=-YES-}" = "-NO-"; then
-			exit 0
-		fi
+        if test "${CUPS:=-YES-}" = "-NO-"; then
+            exit 0
+        fi
 
-        	IS_ON=:
-		ECHO=ConsoleMessage
-		ECHO_OK=:
-		ECHO_ERROR=:
-		;;
+            IS_ON=:
+        ECHO=ConsoleMessage
+        ECHO_OK=:
+        ECHO_ERROR=:
+        ;;
 
-	Linux*)
-		IS_ON=/bin/true
-		if test -f /etc/init.d/functions; then
-			. /etc/init.d/functions
-			ECHO=echo
-			ECHO_OK="echo_success"
-			ECHO_ERROR="echo_failure"
-		else
-			ECHO=echo
-			ECHO_OK=:
-			ECHO_ERROR=:
-		fi
-		;;
+    Linux*)
+        IS_ON=/bin/true
+        if test -f /etc/init.d/functions; then
+            . /etc/init.d/functions
+            ECHO=echo
+            ECHO_OK="echo_success"
+            ECHO_ERROR="echo_failure"
+        else
+            ECHO=echo
+            ECHO_OK=:
+            ECHO_ERROR=:
+        fi
+        ;;
 
-	*)
-		IS_ON=/bin/true
-		ECHO=echo
-		ECHO_OK=:
-		ECHO_ERROR=:
-		;;
+    *)
+        IS_ON=/bin/true
+        ECHO=echo
+        ECHO_OK=:
+        ECHO_ERROR=:
+        ;;
 esac
 
 #### OS-Independent Stuff
@@ -104,27 +104,27 @@ esac
 #
 # Set the timezone, if possible...  This allows the
 # scheduler and all child processes to know the local
-# timezone when reporting dates and times to the user. 
+# timezone when reporting dates and times to the user.
 # If no timezone information is found, then Greenwich
 # Mean Time (GMT) will probably be used.
 #
 
 for file in /etc/TIMEZONE /etc/rc.config /etc/sysconfig/clock; do
-	if test -f $file; then
-	        . $file
-	fi
+    if test -f $file; then
+            . $file
+    fi
 done
 
 if test "x$ZONE" != x; then
-	TZ="$ZONE"
+    TZ="$ZONE"
 fi
 
 if test "x$TIMEZONE" != x; then
-	TZ="$TIMEZONE"
+    TZ="$TIMEZONE"
 fi
 
 if test "x$TZ" != x; then
-	export TZ
+    export TZ
 fi
 
 #
@@ -132,25 +132,25 @@ fi
 #
 
 case "`uname`" in
-	HP-UX* | AIX* | SINIX*)
-		pid=`ps -e | awk '{if (match($4, ".*/cupsd$") || $4 == "cupsd") print $1}'`
-		;;
-	IRIX* | SunOS*)
-		pid=`ps -e | nawk '{if (match($4, ".*/cupsd$") || $4 == "cupsd") print $1}'`
-		;;
-	UnixWare*)
-		pid=`ps -e | awk '{if (match($6, ".*/cupsd$") || $6 == "cupsd") print $1}'`
-		. /etc/TIMEZONE
-		;;
-	OSF1*)
-		pid=`ps -e | awk '{if (match($5, ".*/cupsd$") || $5 == "cupsd") print $1}'`
-		;;
-	Linux* | *BSD* | Darwin*)
-		pid=`ps ax | awk '{if (match($5, ".*/cupsd$") || $5 == "cupsd") print $1}'`
-		;;
-	*)
-		pid=""
-		;;
+    HP-UX* | AIX* | SINIX*)
+        pid=`/bin/ps -e | awk '{if (match($4, ".*/cupsd$") || $4 == "cupsd") print $1}'`
+        ;;
+    IRIX* | SunOS*)
+        pid=`/bin/ps -e | nawk '{if (match($4, ".*/cupsd$") || $4 == "cupsd") print $1}'`
+        ;;
+    UnixWare*)
+        pid=`/bin/ps -e | awk '{if (match($6, ".*/cupsd$") || $6 == "cupsd") print $1}'`
+        . /etc/TIMEZONE
+        ;;
+    OSF1*)
+        pid=`/bin/ps -e | awk '{if (match($5, ".*/cupsd$") || $5 == "cupsd") print $1}'`
+        ;;
+    Linux* | *BSD* | Darwin*)
+        pid=`/bin/ps ax | awk '{if (match($5, ".*/cupsd$") || $5 == "cupsd") print $1}'`
+        ;;
+    *)
+        pid=""
+        ;;
 esac
 
 #
@@ -158,45 +158,45 @@ esac
 #
 
 case $1 in
-	start | restart | reload)
-		if $IS_ON cups; then
-			if test "$pid" != ""; then
-				kill -HUP $pid
-			else
-				prefix=/
-				exec_prefix=/usr
-				${exec_prefix}/sbin/cupsd
-				if test $? != 0; then
-					$ECHO_FAIL
-					$ECHO "cups: unable to $1 scheduler."
-					exit 1
-				fi
-			fi
-			$ECHO_OK
-			$ECHO "cups: ${1}ed scheduler."
-		fi
-		;;
+    start | restart | reload)
+        if $IS_ON cups; then
+            if test "$pid" != ""; then
+                kill -HUP $pid
+            else
+                prefix=/
+                exec_prefix=/usr
+                ${exec_prefix}/sbin/cupsd
+                if test $? != 0; then
+                    $ECHO_FAIL
+                    $ECHO "cups: unable to $1 scheduler."
+                    exit 1
+                fi
+            fi
+            $ECHO_OK
+            $ECHO "cups: ${1}ed scheduler."
+        fi
+        ;;
 
-	stop)
-		if test "$pid" != ""; then
-			kill $pid
-			$ECHO_OK
-			$ECHO "cups: stopped scheduler."
-		fi
-		;;
+    stop)
+        if test "$pid" != ""; then
+            kill $pid
+            $ECHO_OK
+            $ECHO "cups: stopped scheduler."
+        fi
+        ;;
 
-	status)
-		if test "$pid" != ""; then
-			echo "cups: scheduler is running."
-		else
-			echo "cups: scheduler is not running."
-		fi
-		;;
+    status)
+        if test "$pid" != ""; then
+            echo "cups: scheduler is running."
+        else
+            echo "cups: scheduler is not running."
+        fi
+        ;;
 
-	*)
-		echo "Usage: cups {reload|restart|start|status|stop}"
-		exit 1
-		;;
+    *)
+        echo "Usage: cups {reload|restart|start|status|stop}"
+        exit 1
+        ;;
 esac
 
 #
