/etc/init.d/gdomap : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/etc/init.d/gdomap b/woof-code/rootfs-skeleton/etc/init.d/gdomap
--- a/woof-code/rootfs-skeleton/etc/init.d/gdomap
+++ b/woof-code/rootfs-skeleton/etc/init.d/gdomap
@@ -37,33 +37,46 @@ echo "$DAEMON executable"
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
-	start-stop-daemon --start --quiet --exec $DAEMON \
-		-- -I $PIDFILE $GDOMAP_ARGS
-	echo "$NAME."
-	;;
+    test -e $PIDFILE && {
+    echo "$PIDFILE exists."
+    pidof -o %PPID -o $$ $NAME && {
+        echo "$NAME already running. Use restart."
+     } || {
+        echo "Removing $PIDFILE"
+        rm -f $PIDFILE
+     }
+    }
+
+    test -e $PIDFILE || {
+    echo -n "Starting $DESC: "
+    start-stop-daemon --start --quiet --exec $DAEMON \
+        -- -I $PIDFILE $GDOMAP_ARGS \
+    && echo "$NAME." \
+    || echo "failed to start '$NAME' ."
+    }
+    ;;
   stop)
-	echo -n "Stopping $DESC: "
-	start-stop-daemon --stop --quiet --exec $DAEMON \
-		-- -I $PIDFILE $GDOMAP_ARGS
-	rm -f $PIDFILE
-	echo "$NAME."
-	;;
+    echo -n "Stopping $DESC: "
+    start-stop-daemon --stop --quiet --exec $DAEMON \
+        -- -I $PIDFILE $GDOMAP_ARGS
+    rm -f $PIDFILE
+    echo "$NAME."
+    ;;
   restart|force-reload)
-	echo -n "Restarting $DESC: "
-	start-stop-daemon --stop --quiet --exec $DAEMON \
-		-- -I $PIDFILE $GDOMAP_ARGS
-	rm -f $PIDFILE
-	sleep 1
-	start-stop-daemon --start --quiet --exec $DAEMON \
-		-- -I $PIDFILE $GDOMAP_ARGS
-	echo "$NAME."
-	;;
+    echo -n "Restarting $DESC: "
+    start-stop-daemon --stop --quiet --exec $DAEMON \
+        -- -I $PIDFILE $GDOMAP_ARGS
+    rm -f $PIDFILE
+    sleep 1
+    start-stop-daemon --start --quiet --exec $DAEMON \
+        -- -I $PIDFILE $GDOMAP_ARGS
+    echo "$NAME."
+    ;;
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|restart|force-reload}" >&2
-	exit 1
-	;;
+    N=/etc/init.d/$NAME
+    echo "Usage: $N {start|stop|restart|force-reload}" >&2
+    exit 1
+    ;;
 esac
 
 exit 0
