/usr/local/psip/: Fix ###END### add for missing newline.

diff --git a/woof-code/rootfs-skeleton/usr/local/psip/func_shutdownpjsua b/woof-code/rootfs-skeleton/usr/local/psip/func_shutdownpjsua
--- a/woof-code/rootfs-skeleton/usr/local/psip/func_shutdownpjsua
+++ b/woof-code/rootfs-skeleton/usr/local/psip/func_shutdownpjsua
@@ -36,19 +36,18 @@ echo -e "\n\n" >> $PJSIGNAL
 usleep 500000
 #try kills and report errors
 for PID in $(ps | grep 'pjsua' | grep -v 'grep' | cut -f 1-2 -d ' ') ;do
-	if [ ! "$PID" = "$$" -a ! "$PID" = "root" ]; then
-		NAG=1
-		echo "killing pjsua process $PID"
-		kill $PID
-		[ $? = 1 -a "$(ps | grep $PID)" ] && echo "I am $$, I failed to kill pjsua process: $PID" && ps | grep '$PID' | grep -v 'grep' 
-	fi
+        if [ ! "$PID" = "$$" -a ! "$PID" = "root" ]; then
+                NAG=1
+                echo "killing pjsua process $PID"
+                kill $PID
+                [ $? = 1 -a "$(ps | grep $PID)" ] && echo "I am $$, I failed to kill pjsua process: $PID" && ps | grep '$PID' | grep -v 'grep'
+        fi
 done
 if [ -f "$PJTMP/buddy-list" ]; then
-	gxmessage -center -timeout 2 -buttons "" "failed to shutdown pjsua, try again"
+        gxmessage -center -timeout 2 -buttons "" "failed to shutdown pjsua, try again"
 else
-	gxmessage -center -timeout 2 -buttons "" "pjsua shutdown complete"
+        gxmessage -center -timeout 2 -buttons "" "pjsua shutdown complete"
 fi
-
 
 # Very End of this file 'usr/local/psip/func_shutdownpjsua' #
 ###END###
