/usr/local/psip/func_shutdownpjsua: Fixes and readability.

diff --git a/woof-code/rootfs-skeleton/usr/local/psip/func_shutdownpjsua b/woof-code/rootfs-skeleton/usr/local/psip/func_shutdownpjsua
--- a/woof-code/rootfs-skeleton/usr/local/psip/func_shutdownpjsua
+++ b/woof-code/rootfs-skeleton/usr/local/psip/func_shutdownpjsua
@@ -1,26 +1,25 @@
 #!/bin/sh
 
 echo -e "\nq\n" >> $PJSIGNAL
-gxmessage -center -timeout 5 -buttons "" "shutting down pjsua"
-sleep 4
+gxmessage -center -timeout 5 -buttons "" "shutting down pjsua..."
+sleep 2
 rm "$PJTMP/buddy-list"
 #hopefully this will be ignored because pjsua is already shutdown
 #if pjsua is still running the buddy-list will be rebuilt
 echo -e "\n\n" >> $PJSIGNAL
-usleep 500000
+usleep 100000
 #try kills and report errors
-for PID in $(ps | grep 'pjsua' | grep -v 'grep' | cut -f 1-2 -d ' ') ;do
-	if [ ! "$PID" = "$$" -a ! "$PID" = "root" ]; then
-		NAG=1
-		echo "killing pjsua process $PID"
-		kill $PID
-		[ $? = 1 -a "$(ps | grep $PID)" ] && echo "I am $$, I failed to kill pjsua process: $PID" && ps | grep '$PID' | grep -v 'grep' 
-	fi
+for aPID in $(ps | grep 'pjsua' | grep -v 'grep' | cut -f 1-2 -d ' ');
+do
+    if [ ! "$aPID" = "$$" -a ! "$aPID" = "root" ]; then
+        NAG=1
+        echo "killing pjsua process $aPID"
+        kill $aPID
+        [ $? = 1 -a "$(ps | awk '{print $1}' | grep -w $aPID)" ] && { echo "I am $$, I failed to kill pjsua process: $aPID" && ps | grep -w "$aPID" | grep -v 'grep'; }
+    fi
 done
 if [ -f "$PJTMP/buddy-list" ]; then
-	gxmessage -center -timeout 2 -buttons "" "failed to shutdown pjsua, try again"
+    gxmessage -center -timeout 2 -buttons "" "failed to shutdown pjsua, try again"
 else
-	gxmessage -center -timeout 2 -buttons "" "pjsua shutdown complete"
+    gxmessage -center -timeout 2 -buttons "" "pjsua shutdown complete"
 fi
-
-
