woof-code/rootfs-skeleton/usr/local/apps/XkbConfigurationManager/XkbOptionsGrp_led: Added some # REM: Xdialog lines to be able to grep Xdialog examples in woof source files.

diff --git a/woof-code/rootfs-skeleton/usr/local/apps/XkbConfigurationManager/XkbOptionsGrp_led b/woof-code/rootfs-skeleton/usr/local/apps/XkbConfigurationManager/XkbOptionsGrp_led
--- a/woof-code/rootfs-skeleton/usr/local/apps/XkbConfigurationManager/XkbOptionsGrp_led
+++ b/woof-code/rootfs-skeleton/usr/local/apps/XkbConfigurationManager/XkbOptionsGrp_led
@@ -7,8 +7,9 @@ INFILE='/etc/X11/xorg.conf'
 OUTFILE='/etc/X11/xorg.conf.tmp7'
 OPTION='grp_led'
 LIST="/etc/X11/xkb/rules/xorg.lst"
+
 # exported the following from main
-#ERRMSG='Xdialog --title "ERROR" --msgbox "An Error has occured! Try again." 0 0'
+# ERRMSG='Xdialog --title "ERROR" --msgbox "An Error has occured! Try again." 0 0'
 #SUCCESS='Xdialog --title "Success!" --no-buttons --infobox "Changes applied successfuly!" 0 0 2000'
 
 # the full line containing XkbOptions:
@@ -21,52 +22,53 @@ CURRENT=`echo "$ORIGINAL" | cut -d'"' -f4`
 EXIST=`echo -n "$CURRENT" | tr ',' '\n' | fgrep "$OPTION:"`
 
 if [ ! "$EXIST" = "" ]; then
-	INFO=`fgrep -w "$EXIST" $LIST`
-	MESSAGE="You are currently using the following LED setting:
-	"$INFO"
+    INFO=`fgrep -w "$EXIST" $LIST`
+    MESSAGE="You are currently using the following LED setting:
+    "$INFO"
 
 To change it, select a new one below, then press OK.
 To remove it, select it below and press OK.
 To abort press cancel."
 else
-	MESSAGE="Please select the setting you would like to use,
+    MESSAGE="Please select the setting you would like to use,
  then press OK.
 To abort, press cancel."
 fi
 
 # give choice dialog
+# REM: Xdialog menubox pre-defined tag "item"
 CHOICE=`Xdialog --stdout --title "Configure Xkb Option" --left --menubox "$MESSAGE" 17 60 15 grp_led:num "NumLock LED shows alternative group." grp_led:caps "CapsLock LED shows alternative group." grp_led:scroll "ScrollLock LED shows alternative group."`
-[ ! $? -eq 0 ] && echo "cancelled" && exit 
+[ ! $? -eq 0 ] && echo "cancelled" && exit
 echo "$CHOICE"
 
 if [ ! "$EXIST" = "" ]; then # if there's one already
-	if [ "$CHOICE" = "$EXIST" ]; then # the same -> remove
-		NEW=`echo -n $CURRENT | tr ',' '\n' | fgrep -v $CHOICE | tr '\n' ',' | tr -s ',' | sed 's/^,//;s/,$//'`
-	else # change
-		NEW=`echo "$CURRENT" | sed "s/$EXIST/$CHOICE/"`
-	fi
+    if [ "$CHOICE" = "$EXIST" ]; then # the same -> remove
+        NEW=`echo -n $CURRENT | tr ',' '\n' | fgrep -v $CHOICE | tr '\n' ',' | tr -s ',' | sed 's/^,//;s/,$//'`
+    else # change
+        NEW=`echo "$CURRENT" | sed "s/$EXIST/$CHOICE/"`
+    fi
 else
-	NEW="$CURRENT,$CHOICE"
-	[ "$CURRENT" = "" ] && NEW="$CHOICE"
+    NEW="$CURRENT,$CHOICE"
+    [ "$CURRENT" = "" ] && NEW="$CHOICE"
 fi
 
 # add new variant to line, or entire line, if it doesn't exist:
 if [ "$ORIGINAL" = "" ] ;then
-	ORIGINAL=`fgrep '"XkbVariant"' $INFILE | grep -v '^#'`
-	[ "$ORIGINAL" = "" ] && ORIGINAL=`fgrep '"XkbLayout"' $INFILE | grep -v '^#'`
-	MODIFIED="$ORIGINAL\n	Option 		\"XkbOptions\"   \"$NEW\""
+    ORIGINAL=`fgrep '"XkbVariant"' $INFILE | grep -v '^#'`
+    [ "$ORIGINAL" = "" ] && ORIGINAL=`fgrep '"XkbLayout"' $INFILE | grep -v '^#'`
+    MODIFIED="$ORIGINAL\n   Option      \"XkbOptions\"   \"$NEW\""
 else
-	MODIFIED=`echo "$ORIGINAL" | sed "s%\"$CURRENT\"%\"$NEW\"%"`
+    MODIFIED=`echo "$ORIGINAL" | sed "s%\"$CURRENT\"%\"$NEW\"%"`
 fi
 
 # add to file
 cat $INFILE | sed "s%$ORIGINAL%$MODIFIED%" >$OUTFILE
 
 if ! fgrep -q '"XkbOptions"' $OUTFILE ;then
-	eval $ERRMSG
-	rm -f $OUTFILE
+    eval $ERRMSG
+    rm -f $OUTFILE
 else
-	mv -f $OUTFILE $INFILE
-	eval $SUCCESS
+    mv -f $OUTFILE $INFILE
+    eval $SUCCESS
 fi
 exit
