/usr/bin/filemnt2: Added crypt save_file support. Tests turned out that omitting the f.s. type made mount testing for the right one with a buggy LogFS driver build into the kernel causing mount failures. So get the f.s. type by extension again. Added a few more file systems by the way. Further note, that different compiled losetup binaries with patches or other differences seem to fail to setup crypt files originally setup with another losetup binary. They return 0, but mount chokes.
Added _kernel_fs_support() function to check if crypt driver available.

Added cleanup at the end to detach loop in case of mount failure.

Added _losetup_a() function, since very old losetup has no -a option
and busybox since at least v1.14.y prints the list of setup loops.

Added _ask_to_run_sfs_load() function in case sfs_load found in PATH.

Use gettext for help and version message.

Added missing _debugx and _err functions from f4puppy5.

------
/etc/rc.d/f4puppy5: Little cleanups.
Added _losetup_a() function to mimic losetup -a option.
Added support for '\134' entries in /proc/mounts .

------
/usr/bin/pupdialog: Bugfix: One aVAR had been missed at
changing variable names from AVAR to aVAR. Made --inputbox
unusable in filemnt2 to send password to stdout.

While at it, repaired the --countdown option.
The code did not pass some STRING to COUNTDOWN variable.
It also was missing BODYSTRING for the main gui.
Added cancel button to COUNTDOWN main gui and give correct
exit value of '0' when timed out. Without --countdown, the
--timeout exit value is still 254 .

Use gettext for --help message.

diff --git a/woof-code/rootfs-skeleton/usr/bin/filemnt2 b/woof-code/rootfs-skeleton/usr/bin/filemnt2
--- a/woof-code/rootfs-skeleton/usr/bin/filemnt2
+++ b/woof-code/rootfs-skeleton/usr/bin/filemnt2
@@ -4,9 +4,12 @@ MY_SELF=`realpath "$0"`
 test "$0" = "$MY_SELF" && MY_SELF_MSG="$MY_SELF" || MY_SELF_MSG="$0 -> $MY_SELF"
 ERR=/dev/null # /dev/stderr or errlogfile
 OUT=/dev/null # /dev/stdout
-INFO=
+ERROR=1
+INFO=1
 DEBUG=1
+DEBUGX=1
 VERSION=0.0 #2016-08-26
+VERSION=0.5 #2016-08-27
 TWO_DEBUG=1
 TWO_VERSION=1
 TWO_HELP=1
@@ -26,6 +29,10 @@ ash*|bash*|sh*) return $RV;; #likely sourced. sourced files crash scripts if exi
 esac
 }
 
+_err(){
+test "$ERROR" || return 0
+echo -e "$0:ERROR:$*"  >&2
+}
 _info(){
 test "$INFO" || return 0
 echo -e "$0:INFO:$*"  >&2
@@ -34,7 +41,10 @@ _debug(){
 test "$DEBUG" || return 0
 echo "$0:DEBUG:$*"  >&2
 }
-
+_debugx(){
+test "$DEBUGX" || return 0
+echo "$0:DEBUGX:$@"  >&2
+}
 _info "$*"
 MAYBE_FILE=`echo -e "$*"`
 MAYBE_DIR="$MAYBE_FILE"
@@ -81,7 +91,7 @@ _tell_help(){
 
 MSG_HELP="$MY_SELF_MSG:
  Usage:
-  filemnt [ -h|-V|-v|-d ] <filename.ext> [ <mountpoint> ]
+  ${0##*/} [ -h|-V|-v|-d ] <filename.ext> [ <mountpoint> ]
  Options:
  --help|-h)    say this message and exit.
  --version|-V) say version and exit.
@@ -90,11 +100,11 @@ MSG_HELP="$MY_SELF_MSG:
 "
 [ "$*" ] && MSG_HELP="$$MSG_HELP
 $*"
-echo "$MSG_HELP"
+gettext "$MSG_HELP"
 }
 
 _tell_version(){
-echo "$MY_SELF_MSG: $VERSION"
+gettext "$MY_SELF_MSG: $VERSION"
 }
 _check_params(){
 PARAMS="$@"
@@ -126,8 +136,27 @@ _debug "FILE_MOUNT_LOOP='$FILE_MOUNT_LOOP'"
 
 # /mnt/home fix ?
 
+_losetup_a(){
+# old losetup-FULL has no -a options,
+# busybox since at least v1.14.4 prints all set up loop devices if no parameters given
+(
+for l in `ls /dev/loop[0-9]*`
+do
+losetup $l
+done
+) 2>>$ERR
+
+(
+for l in `ls /dev/loop/[0-9]*`
+do
+losetup $l
+done
+) 2>>$ERR
+}
+
 _ensure_loop_cont(){
-    usedLOOPS=`losetup 2>>$ERR || losetup -a 2>>$ERR | wc -l`
+    (
+    usedLOOPS=`_losetup_a | wc -l`
     c=0
     while read loop; do
     NR=${loop##*/}
@@ -144,13 +173,15 @@ _ensure_loop_cont(){
     done << EoI
 `ls -1d /dev/loop[0-9]* | sed 's!.*loop!!;s!/!!' | sort -n`
 EoI
+) 2>>$ERR
 unset c NR
 }
 _ensure_loop_cont
 
 _mk_free_loop()
 {
-    usedLOOPS=`losetup 2>>$ERR || losetup -a 2>>$ERR | wc -l`
+    (
+    usedLOOPS=`_losetup_a | wc -l`
     read NR <<EoI
 `ls /dev/loop[0-9]* | wc -w`
 EoI
@@ -163,7 +194,116 @@ EoI
     test -b /dev/loop$((NR+2)) || mknod /dev/loop$((NR+2)) b 7 $((NR+2))
     test -d /dev/loop && { ln -sf ../loop$((NR+0)) /dev/loop/$((NR+0)); ln -sf ../loop$((NR+1)) /dev/loop/$((NR+1)); ln -sf ../loop$((NR+2)) /dev/loop/$((NR+2)); }
     fi
+    ) 2>>$ERR
 unset NR usedLOOPS
+}
+
+_encrypted()
+{
+  #111110 handle encrypted save-files...
+  CRYPTO=""; Err=0
+
+     _init_crypt_save_file()
+     {
+      local fCRYPT=$1 Err=1
+      test "$fCRYPT" || return 7
+
+      freeLOOP="`losetup-FULL -f`" #next free loop device.
+      test $? = 0 || return 8
+
+      MYPASS="`pupdialog --title "$(gettext 'Enter Password')" --stdout --inputbox "$(gettext 'Password required to open') ${FILE_MOUNT_LOOP##*/} :" 0 0`"
+      Err=$?
+
+      _debugx "MYPASS='$MYPASS' fCRYPT=$fCRYPT"
+
+      if [ $Err -eq 0 ];then
+       echo "$MYPASS" | losetup-FULL $VERB -p 0 -e $fCRYPT $freeLOOP "$FILE_MOUNT_LOOP"
+       #echo "$MYPASS" | /usr/local/sbin/losetup $VERB -p 0 $L_OP $freeLOOP "$FILE_MOUNT_LOOP"
+       #echo "$MYPASS" | /sbin/losetup $VERB $VERB -p 0 $L_OP $freeLOOP "$FILE_MOUNT_LOOP"
+# -N | --nohashpass        Do not hash the given password (Debian hashes)
+# -k | --keybits <num>     specify number of bits in the hashed key given
+#                          to the cipher.  Some ciphers support several key
+#                          sizes and might be more efficient with a smaller
+#                          key size.  Key sizes < 128 are generally not
+#                          recommended
+       Err=$?
+      fi
+      return $Err
+     }
+
+    case $FILE_MOUNT_LOOP  in
+
+     *_cryptx*) #light encryption.
+      CRYPTO='light'
+      modprobe $Q $VERB cryptoloop
+      rxvt -geometry 25x3 -title "$(gettext 'Enter password')" -bg orange -e losetup-FULL -E 1 $freeLOOP
+      #losetup-FULL -E 1 $freeLOOP $imgFile
+      Err=$?
+     ;;
+
+     *_cryptanubis*|*_cryptan*) CRYPTO=anubis
+      _init_crypt_save_file $CRYPTO; Err=$?
+     ;;
+
+     *_cryptarc4*|*_cryptarc*) CRYPTO=arc4 #does not mount
+      _init_crypt_save_file $CRYPTO; Err=$?
+     ;;
+
+     *_crypta*) #heavy encryption.
+      CRYPTO='aes'
+
+      for mod in cryptoloop aes_generic aes crypto_blkcipher blkcipher cbc
+      do
+      modprobe $Q $VERB -l | grep $Q "/${mod}.ko$" || continue
+      modprobe $Q $VERB $mod
+      done
+
+# <linux/loop.h>
+#/*
+# * Loop filter types
+# */
+
+#define LO_CRYPT_NONE           0
+#define LO_CRYPT_XOR            1
+#define LO_CRYPT_DES            2
+#define LO_CRYPT_FISH2          3    /* Twofish encryption */
+#define LO_CRYPT_BLOW           4
+#define LO_CRYPT_CAST128        5
+#define LO_CRYPT_IDEA           6
+#define LO_CRYPT_DUMMY          9
+#define LO_CRYPT_SKIPJACK       10
+#define LO_CRYPT_CRYPTOAPI      18
+#define MAX_LO_CRYPT            20
+
+      _init_crypt_save_file $CRYPTO; Err=$?
+     ;;
+
+     *_cryptblowfish*|*_cryptbf*) CRYPTO=blowfish
+      _init_crypt_save_file $CRYPTO; Err=$?
+     ;;
+
+     *_cryptcamellia*|*_cryptcam*) CRYPTO=camellia
+      _init_crypt_save_file $CRYPTO; Err=$?
+     ;;
+
+     *_cryptcast6*|*_cryptcast*) CRYPTO=cast6
+      _init_crypt_save_file $CRYPTO; Err=$?
+     ;;
+
+     *_cryptserpent*|*_cryptser*) CRYPTO=serpent
+      _init_crypt_save_file $CRYPTO; Err=$?
+     ;;
+
+     *_crypttwofish*|*_crypttf*) CRYPTO=twofish
+      _init_crypt_save_file $CRYPTO; Err=$?
+     ;;
+
+     *) Err=9  #[ -b "$freeLOOP" ] && losetup $freeLOOP "$FILE_MOUNT_LOOP"; Err=$?
+     ;;
+    esac
+   # [ -b "$freeLOOP" ] && losetup $freeLOOP "$FILE_MOUNT_LOOP"; Err=$?
+
+return $Err
 }
 
 _mount_it(){
@@ -180,19 +320,106 @@ test -f "$FILE_MOUNT_LOOP" || _exit 2 "'$ORIG_PARAMS' : No such file or director
    _mk_free_loop
   fi
 
- disktype "$FILE_MOUNT_LOOP" | grep $Q -iE 'file system|squashfs' || _exit 3 "File seems not to contain a filesystem.
- Is it encrypted ?"
+_encrypted
+Err=$?
+_debug Err=$Err
+ #disktype "$FILE_MOUNT_LOOP" | grep $Q -iE 'file system|squashfs' || _exit 3 "File seems not to contain a filesystem.
+ #Is it encrypted ?"
 
  # mount chokes today on missing -t FS_TYPE in case of ext2 fs,
  # but does not need -t FS_TYPE for squashfs.
  FS_TYPE=`guess_fstype "$FILE_MOUNT_LOOP"` || unset FS_TYPE
- test "$FS_TYPE" && T_OP="-t $FS_TYPE"
+ test "$FS_TYPE" = 'unknown' && unset FS_TYPE #old guess_fstype does return 0 on unknown...
+ #test "$FS_TYPE" && T_OP="-t $FS_TYPE"
+
+ # encrypted files do not reveal anything for disktype, blkid, guess_fstype.
+ # file command says for 'aes' : DBase 3 data file
+ # mount-FULL is pretty good  at finding the correct f.s. , but tests all available
+ # and testing them could cause kernel panics or taints in case of buggy drivers like LogFS
+ # OK: [11885.733013] FAT-fs (loop22): invalid media value (0x06)
+ # OK: [11885.733019] FAT-fs (loop22): Can't find a valid FAT filesystem
+ # OK: [11885.738075] VFS: could not find a valid V7 on loop22.
+ # [11885.750056] LogFS: Start mount 16
+ # [11885.750207] LogFS: Start unmounting
+ # [11885.750276] BUG: unable to handle kernel NULL pointer dereference at   (null)
+ # [11885.750280] IP: [<c1c20a7e>] __mutex_lock_common+0x10a/0x28e
+ # [11885.750287] *pdpt = 00000000271d2001 *pde = 0000000000000000
+ # [11885.750290] Oops: 0002 [#23] SMP
+ # [11885.750336] Pid: 9270, comm: mount-FULL Tainted: G      D      3.5.0-KRG-iCore2-smp-pae-srv1000gz #2 Dell Inc. OptiPlex 755                 /0GM819
+ # [11885.750340] EIP: 0060:[<c1c20a7e>] EFLAGS: 00010086 CPU: 1
+ # [11885.750356] Process mount-FULL (pid: 9270, ti=e72f2000 task=e732cb60 task.ti=e72f2000)
+ # [11885.750379] Call Trace:
+ # [11885.750385]  [<c12bdba5>] ? logfs_get_wblocks+0x2a/0x36
+
+ test "$FS_TYPE" || {
+ case `echo ${FILE_MOUNT_LOOP} | tr '[:upper:]' '[:lower:]'` in
+ *.2fs*|*.ext2*)  FS_TYPE='ext2';;
+ *.3fs*|*.ext3*)  FS_TYPE='ext3';;
+ *.4fs*|*.ext4*)  FS_TYPE='ext4';;
+ *.btr*|*.btrfs*) FS_TYPE='btrfs';;
+ *.cramfs*)       FS_TYPE='cramfs';;
+ *.f2f*)          FS_TYPE='f2fs';;
+ *.fat*)          FS_TYPE='vfat';;
+ *.hpfs*)         FS_TYPE='hpfs';;
+ *.hfsplus*)      FS_TYPE='hfsplus';;
+ *.hfs*)          FS_TYPE='hfs';;
+ *.jfs*)          FS_TYPE='jfs';;
+ *.mnx*|*.minix*) FS_TYPE='minix';;
+ *.ntfs*)         FS_TYPE='ntfs-3g';;
+ *.ofs*|*.ocfs2*) FS_TYPE='ocfs2';;
+ *.rfs*|*.rfs3*)  FS_TYPE='reiserfs';;
+ *.reiser4*)      FS_TYPE='reiser4';;
+ *.sfs*|*.sqfs*|*.squashfs*) FS_TYPE='squashfs';;
+ *.udf*)          FS_TYPE='udf';;
+ *.ufs*)          FS_TYPE='ufs';;
+ *.xfs*)          FS_TYPE='xfs';;
+ *.iso*|*.cdfs*)  ###+++2013-03-02 Fatdog: fat16 first and iso9660 second
+   TYPES=`disktype "$FILE_MOUNT_LOOP" |grep 'file system'`
+   if [ "`echo "$TYPES" |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]' | grep -i 'UDF'`" ]; then
+    FS_TYPE=udf
+   else
+    FS_TYPE=iso9660
+   fi
+  ;;
+  *) ##+++2012-06-04
+   FS_TYPE=`disktype "$FILE_MOUNT_LOOP" |grep 'file system' |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]'`
+  ;;
+  esac
+ }
+
+ _kernel_fs_support(){
+     grep -v nodev /proc/filesystems | grep $Q "$*" && return 0
+     ( modinfo "$*" && modprobe $Q $VERB "$*" ) >>$OUT 2>>$ERR
+ }
+ test "$FS_TYPE" && _kernel_fs_support "$FS_TYPE" && T_OP="-t $FS_TYPE"
 
  mkdir -p "$FILE_MOUNT_POINT"
- mount $T_OP -o loop "$FILE_MOUNT_LOOP" "$FILE_MOUNT_POINT"
+ #mount $T_OP -o loop "$FILE_MOUNT_LOOP" "$FILE_MOUNT_POINT"
  #Doing mount-FULL -o loop /mnt/sda3/tmp/test file with spaces.2fs /mnt/123 456
  #mount: you must specify the filesystem type
- exit $?
+ #exit $?
+
+ if test $Err = 0; then
+ _info "About to mount $T_OP "$freeLOOP" "$FILE_MOUNT_POINT""
+ /bin/mount $T_OP "$freeLOOP" "$FILE_MOUNT_POINT"
+
+ elif test $Err = 9; then
+
+ _info "About to mount $T_OP -o loop "$FILE_MOUNT_LOOP" "$FILE_MOUNT_POINT""
+ /bin/mount $T_OP -o loop "$FILE_MOUNT_LOOP" "$FILE_MOUNT_POINT"
+
+ elif test $Err = 8; then
+ _err "No free loop device available"
+ false
+ elif test $Err = 7; then
+ _err "Unknown encryption"
+ false
+ else
+ _err "Unable to setup loop device"
+ false
+ fi
+
+return $?
 }
 
 _convert_nl_tab_sp_esc()
@@ -208,24 +435,21 @@ unset xR xQ xP xS
 
 _format_grep_pattern(){
 gP="$*"
-echo "gP='$gP'"
-for c in "\\\\" '$' '^' '*' '[' '.'          # '[' ']' "\\\\"
-      #for c in '$' '^' '*' '[' ']' '.'      # grep -E: '+'   #sed & ( )
+_debugx "gP='$gP'"
+for c in "\\\\" '$' '^' '*' '[' '.' # ']' "\\\\"
 do
-echo "c='$c'"
+_debugx "c='$c'"
 case "$c" in
-'*'|'[') echo have wildcard or square
+'*'|'[') #echo have wildcard or square
 gP=${gP//"$c"/\\$c};;
-'\\') echo have backslash
+'\\')    #echo have backslash
 gP=${gP//\\/\\\\};;
-#'['|']') echo have square
-#gP=${gP//"$c"/\\$c};;
 *) #gP=${gP//"$c"/\\\\"$c"};;
-   gP=${gP//"$c"/\\"$c"};;
+    gP=${gP//"$c"/\\"$c"};;
 esac
-echo "gP='$gP'"
+_debugx "gP='$gP'"
 done
-echo "gP='$gP'"
+_debug "gP='$gP'"
 }
 
 _check_dir_mounted(){
@@ -236,32 +460,95 @@ _debug "gP='$gP'"
 cut -f2 -d' ' /proc/mounts | grep $Q "^${gP}$";
 }
 
+# REM: 2015-11-27 add sfs_load switch
+_ask_to_run_sfs_load(){
+
+ which sfs_load >>$OUT || return 1
+
+test "$PUPMODE" || { [ -f /etc/rc.d/PUPSTATE ] && . /etc/rc.d/PUPSTATE || PUPMODE=2; }
+
+case $PUPMODE in 2) return 1;; esac
+
+ MSG_TEXT="This is a squashfs file.
+Do you want to load it into the current running Puppy
+as merged part of the Operating System ?
+Most .sfs files are made to be loaded this way.
+
+Or, it may be just a normal archive.sfs like any .iso file
+or even a .sfs made for another linux and not for Puppy.
+In that case you may want to mount it just simply
+as any other partition mount.
+"
+
+GMSG_TEXT=`gettext "$MSG_TEXT"`
+test "${GMSG_TEXT// /}" && MSG_TEXT=$GMSG_TEXT
+
+BUTTON_LOD=`gettext 'OS Load'`
+BUTTON_MNT=`gettext 'Just Mount'`
+BUTTON_EXT=`gettext 'Quit'`
+
+xmessage -buttons "$BUTTON_LOD:100,$BUTTON_MNT:101,$BUTTON_EXT:1" -bg "light blue" -title "filmnt" "$MSG_TEXT"
+case $? in
+100) return 0;;
+101) return 1;;
+1)   return 2;;
+*)   return 3;;
+esac
+}
+
+_ask_to_run_sfs_load
+  case $? in 0) exec sfs_load "$imgFILE";;
+  1) :;; 2) exit 0;; *) _warn "Unhandled return value from _ask_to_run_sfs_load";;
+  esac
+
+
 if [ "$FILE_MOUNT_POINT" ]; then
  # toggle if already mounted
 
  if _check_dir_mounted; then
+  rox -D "$FILE_MOUNT_POINT"
   /bin/umount -d "$FILE_MOUNT_POINT"
   exit $?
  else
   _mount_it
  fi
+ RV=$?
 
 else
 
  FILE_MOUNT_POINT=/mnt/"${FILE_MOUNT_LOOP##*/}"
  if _check_dir_mounted; then
+  rox -D "$FILE_MOUNT_POINT"
   /bin/umount -d "$FILE_MOUNT_POINT"
   exit $?
  else
  _mount_it
  fi
+ RV=$?
 
+fi
+
+_debug RV=$RV
+if test "$RV" = 0; then
+ :
+ #[ -d "$FILE_MOUNT_POINT" ] && rox "$FILE_MOUNT_POINT"
+else # clean up
+ [ -d "$FILE_MOUNT_POINT" ] && rmdir $VERB "$FILE_MOUNT_POINT"
+  if test "$freeLOOP"; then
+   _losetup_a | grep $Q -w "^$freeLOOP" && losetup $VERB -d "$freeLOOP"
+  fi
+  if test "$FILE_MOUNT_LOOP"; then
+   LOOP_ASS=`losetup -j "$FILE_MOUNT_LOOP"`
+   for l in $LOOP_ASS; do
+   losetup -d $l
+   done
+  fi
 fi
 
 #TODO:
 #/initrd/ support in use by puppy
-#encryption support
+#DONE:encryption support
 #squashfs version support
 #squashfs compression
 #xmessages for success/failure
-#dialog to load or mount
+#DONE:dialog to load or mount
diff --git a/woof-code/rootfs-skeleton/usr/bin/pupdialog b/woof-code/rootfs-skeleton/usr/bin/pupdialog
--- a/woof-code/rootfs-skeleton/usr/bin/pupdialog
+++ b/woof-code/rootfs-skeleton/usr/bin/pupdialog
@@ -21,13 +21,13 @@ MY_SELF="$0"
 MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
-[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5
+[ "$HAVE_F4PUPPY5" ] || . /etc/rc.d/f4puppy5
 
 ADD_PARAMETER_LIST=""
 ADD_PARAMETERS=""
 _provide_basic_parameters
 
-TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
+TWO_HELP='1'; TWO_VERSION='1'; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
 ADD_HELP_MSG="$_COMMENT_"
 _parse_basic_parameters "$@"
 #[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
@@ -40,48 +40,64 @@ _trap
 # --timeout 90 --extra-button --ok-label "SAVE TO A FILE"  --extra-label "SAVE TO ${xPDEV}" --cancel-label "DO NOT SAVE" --yesno "etetetete" 0 0
 #accept these, not available in dialog: --background --foreground --countdown "text"
 
-[ ! "$1" ] && HELPFLG='yes'
-[ "$1" == "--help" ] && HELPFLG='yes'
-if [ "$HELPFLG" == "yes" ];then
- echo "pupdialog is a simple replacement for 'dialog' when X is running.
-pupdialog only implements these dialogs: --msgbox --yesno --menu --inputbox --checklist
+[ "$*" ] || HELPFLG='yes'
+[ "$1" = "--help" ] && HELPFLG='yes'
+if [ "$HELPFLG" = "yes" ];then
+MSG_HELP="pupdialog is a simple replacement for 'dialog' when X is running.
+pupdialog only implements these dialogs:
+ --checklist --inputbox --menu --msgbox --yesno
 These parameters are supported:
---extra-button --ok-label --extra-label --cancel-label --colors --yes-label --no-label --title --backtitle --stdout --default-item
+ --title --backtitle
+ --extra-button --extra-label --ok-label --yes-label --cancel-label --no-label
+ --colors --default-item --stdout
+
 ex: pupdialog --timeout 90 --extra-button --ok-label \"SAVE TO A FILE\"  --extra-label \"SAVE TO PARTITION\" --cancel-label \"DO NOT SAVE\" --yesno \"example text\" 0 0
 ex: pupdialog --backtitle \"backtitle here\" --default-item tag2  --menu \"this is blurb for menu dlg\" 0 0 0 tag1 item1 tag2 item2 tag3 item3
+
 The height and width parameters are ignored.
+
 If no --title <string>, then window is not decorated.
+
 Ansi text markup is supported with --colors ex: \Zbbold\ZB \Z1red\Zn
  -- but basic parsing, always pair them as shown in example (nesting allowed).
+
 The following are extras in pupdialog not in dialog:
 --background <value>      #background color of window
 --foreground <value>      #color of text
 --countdown <string>      #countdown message, time substituted for TIME (requires --timeout)
 --helpwindow <executable> #run another application, typically help window. does not exit.
+
 ex: pupdialog --background yellow --foreground black --timeout 90 --countdown \"Shutdown in TIME seconds\" ...
-Note: use 'pupkill $!' to kill a pupdialog window."
- exit
+Note: use 'pupkill $!' to kill a pupdialog window.
+"
+ gettext "$MSG_HELP"
+ exit 0
 fi
 
 GTKDIALOG="`which gtkdialog4`"
-[ ! "$GTKDIALOG" ] && GTKDIALOG="`which gtkdialog`"
-[ ! "$GTKDIALOG" ] && exit 255
-[ ! -e /tmp/pupdialog_exec ] && ln -s $GTKDIALOG /tmp/pupdialog_exec
+[ "$GTKDIALOG" ] || GTKDIALOG="`which gtkdialog`"
+[ "$GTKDIALOG" ] || exit 255
+[ -e /tmp/pupdialog_exec ] || ln $VERB -sf "$GTKDIALOG" /tmp/pupdialog_exec
 
-TIMEOUT=0 #means never timeout.
 FONTSTYLE='Mono 14'
 TABCHAR="`echo -n -e '\t'`"
 
+unset EXTRABUTTON EXTRALABEL OKLABEL YESLABEL CANCELLABEL NOLABEL
+unset CHECKLIST COUNTDOWN INPUTBOX MENU MSGBOX YESNO DEFAULTITEM MENUHEIGHT HEIGHT WIDTH
+unset COLORS BACKGROUND FOREGROUND
+unset NOCOLLAPSE HELPWINDOW STDOUT TITLE
+
+aVAR='START'; aVAL=''; ENDCNT=0; MENUCNT=0; SUBCNT=0; TOGGLE=0; INITVAL=''; INPUTXML=''; MENUITEMS='';
+TIMEOUT=0 #means never timeout.
+
 #evaluate the passed parameters...
-unset EXTRABUTTON OKLABEL EXTRALABEL BACKGROUND CANCELLABEL COLORS FOREGROUND YESLABEL MSGBOX NOLABEL YESNO TITLE NOCOLLAPSE COUNTDOWN MENU STDOUT DEFAULTITEM INPUTBOX HEIGHT WIDTH MENUHEIGHT CHECKLIST HELPWINDOW
-AVAR='START'; aVAL=''; ENDCNT=0; TOGGLE=0; MENUITEMS=''; INITVAL=''; INPUTXML=''; MENUCNT=0; SUBCNT=0
 for aFIELD in "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}" "${33}" "${34}" "${35}" "${36}" "${37}" "${38}" "${39}" "${40}" "${41}" "${42}" "${43}" "${44}" "${45}" "${46}" "${47}" "${48}" "${49}" "${50}" "${51}" "${52}" "${53}" "${54}" "${55}" "${56}" "${57}" "${58}" "${59}" "${60}" "${61}" "${62}" "${63}" "${64}" "${65}" "${66}" "${67}" "${68}" "${69}" "${70}" "${71}" "${72}" "${73}" "${74}" "${75}" "${76}" "${77}" "${78}" "${79}" "${80}" "${81}" "${82}" "${83}" "${84}" "${85}" "${86}" "${87}" "${88}" "${89}" "${90}" "${91}" "${92}" "${93}" "${94}" "${95}" "${96}" "${97}" "${98}" "${99}" "${100}" "${101}" "${102}" TOOLONG
 do
- if [ "$aFIELD" == "TOOLONG" ];then
+ if [ "$aFIELD" = "TOOLONG" ];then
   xmessage -center -bg red "ERROR: There are too many menu items for pupdialog to handle. Aborting."
   exit 255
  fi
- [ "$aFIELD" == "" ] && break #end.
+ if [ "$aFIELD" ]; then
  case $aVAR in
   MSGBOX|YESNO|MENU|INPUTBOX|CHECKLIST)
    DLGTYPE="$aVAR"
@@ -103,10 +119,10 @@ do
      case $aVAR in
       MENU)
        if [ $TOGGLE -eq 0 ];then #menu items are format "tag description" for each item, where description displays.
-        MENUCNT=$(($MENUCNT + 1))
+        MENUCNT=$((MENUCNT + 1))
         TAG="$aFIELD"
         MENUITEMS="${MENUITEMS} <radiobutton draw_indicator=\"false\" xalign=\"0\"><variable>${aFIELD}</variable>"
-        [ "$DEFAULTITEM" == "$aFIELD" ] && MENUITEMS="${MENUITEMS}<default>true</default>"
+        [ "$DEFAULTITEM" = "$aFIELD" ] && MENUITEMS="${MENUITEMS}<default>true</default>"
         TOGGLE=1
        else
         MENUITEMS="${MENUITEMS}<label>${TAG}${TABCHAR}${aFIELD}</label></radiobutton>"
@@ -114,10 +130,10 @@ do
        fi
       ;;
       CHECKLIST) #111011
-       SUBCNT=$(($SUBCNT + 1))
+       SUBCNT=$((SUBCNT + 1))
        case $SUBCNT in
         1)
-         MENUCNT=$(($MENUCNT + 1))
+         MENUCNT=$((MENUCNT + 1))
          TAG="$aFIELD"
          MENUITEMS="${MENUITEMS} <checkbox draw_indicator=\"false\" xalign=\"0\"><variable>${aFIELD}</variable>"
         ;;
@@ -126,8 +142,8 @@ do
         ;;
         3)
          [ "$aFIELD" = "yes" ] && aFIELD='true'
-         [ "$aFIELD" = "no" ] && aFIELD='false'
-         [ "$aFIELD" = "on" ] && aFIELD='true'
+         [ "$aFIELD" = "no" ]  && aFIELD='false'
+         [ "$aFIELD" = "on" ]  && aFIELD='true'
          [ "$aFIELD" = "off" ] && aFIELD='false'
          MENUITEMS="${MENUITEMS}<default>${aFIELD}</default></checkbox>"
          SUBCNT=0
@@ -137,48 +153,60 @@ do
      esac
     ;;
    esac
-   ENDCNT=$(($ENDCNT + 1))
+   ENDCNT=$((ENDCNT + 1))
    continue
   ;;
  esac
  case $aFIELD in
   --[a-z]*)
-   [ "$aVAL" == "" ] && aVAL="true" #so as not empty.
-   eval "${aVAR}='${aVAL}'"         #evaluate previous param.
-   aVAR="`echo -n "$aFIELD"| tr -d '-' | tr '[a-z]' '[A-Z]'`"
+   [ "$aVAL" ] || aVAL="true" #so as not empty.
+   eval "${aVAR}='${aVAL}'"   #evaluate previous param.
+   aVAR=`echo -n "$aFIELD"| tr -d '-' | tr '[a-z]' '[A-Z]'`
    aVAL=''
   ;;
   *)
-   aVAL="`echo "$aFIELD" | tr '"' "'" | tr '\t' ' ' | tr -s ' ' | sed -e 's% $%%'`" #cleanup text.
+   aVAL=`echo "$aFIELD" | tr '"' "'" | tr '\t' ' ' | tr -s ' ' | sed -e 's% $%%'` #cleanup text.
   ;;
  esac
+else
+test "$aVAR" || aVAR=ENDDUMMY
+test "$aVAL" || aVAL=enddummycontent
+eval "${aVAR}='${aVAL}'"
+break
+fi
 done
 
-#if [ "$YESNO" -o "$MSGBOX" ];then
- BODYSTR="`echo "$BODYSTR" | sed -e 's%<%\&lt;%g' -e 's%>%\&gt;%g' -e 's%\\\n%\\n%g'`"
+ if test "$COUNTDOWN"; then
+  [ "$BODYSTR" ] || BODYSTR="$COUNTDOWN"
+  #yBODYSTR="$BODYSTR"
+  BODYSTR=`echo "$BODYSTR" | sed 's%<%\&lt;%g; s%>%\&gt;%g; s%\\\n%\\n%g' | sed "s% TIME % $TIMEOUT %"`
+ else
+  BODYSTR=`echo "$BODYSTR" | sed 's%<%\&lt;%g; s%>%\&gt;%g; s%\\\n%\\n%g'`
+ fi
+
  if [ "$COLORS" ];then
   #Interpret embedded "\Z" sequences in the dialog text by the following character, which tells dialog to set colors or video attributes: 0 through 7 are the ANSI used in curses: black, red, green, yellow, blue, magenta, cyan and white respectively. Bold is set by 'b', reset by 'B'. Reverse is set by 'r', reset by 'R'. Underline is set by 'u', reset by 'U'. The settings are cumulative, e.g., "\Zb\Z1" makes the following text bold (perhaps bright) red. Restore normal settings with "\Zn".
   #\Z0 - \Z7 = black, red, green, yellow, blue, magenta, cyan and white
-  BODYSTR="`echo "$BODYSTR" | sed -e 's%\\\Zb%<b>%g' -e 's%\\\ZB%</b>%g' -e 's%\\\Z0%<span color='"'black'"'>%g' -e 's%\\\Z1%<span color='"'red'"'>%g' -e 's%\\\Z2%<span color='"'green'"'>%g' -e 's%\\\Z3%<span color='"'yellow'"'>%g' -e 's%\\\Z4%<span color='"'blue'"'>%g' -e 's%\\\Z5%<span color='"'magenta'"'>%g' -e 's%\\\Z6%<span color='"'cyan'"'>%g' -e 's%\\\Z7%<span color='"'white'"'>%g' -e 's%\\\Zn%</span>%'`"
+  BODYSTR=`echo "$BODYSTR" | sed -e 's%\\\Zb%<b>%g' -e 's%\\\ZB%</b>%g' -e 's%\\\Z0%<span color='"'black'"'>%g' -e 's%\\\Z1%<span color='"'red'"'>%g' -e 's%\\\Z2%<span color='"'green'"'>%g' -e 's%\\\Z3%<span color='"'yellow'"'>%g' -e 's%\\\Z4%<span color='"'blue'"'>%g' -e 's%\\\Z5%<span color='"'magenta'"'>%g' -e 's%\\\Z6%<span color='"'cyan'"'>%g' -e 's%\\\Z7%<span color='"'white'"'>%g' -e 's%\\\Zn%</span>%'`
  fi
  BODYTEXT="<text use-markup=\"true\"><label>\"${BODYSTR}\"</label></text>"
 
- YESBUTTON="<button><label>OK</label><action>EXIT:okbutton</action></button>"
+ YESBUTTON="<button><label>\"   OK   \"</label><action>EXIT:okbutton</action></button>"
  [ "$OKLABEL" ] && YESBUTTON="<button><label>${OKLABEL}</label><action>EXIT:okbutton</action></button>"
  #hmmm, different from dialog, default is no cancel button, unless label specified...
  [ "$CANCELLABEL" ] && NOBUTTON="<button><label>${CANCELLABEL}</label><action>EXIT:cancelbutton</action></button>"
 
  case $DLGTYPE in
   YESNO)
-   YESBUTTON="<button><label>Yes</label><action>EXIT:yesbutton</action></button>"
-   [ "$OKLABEL" ] && YESBUTTON="<button><label>${OKLABEL}</label><action>EXIT:yesbutton</action></button>"
+                      YESBUTTON="<button><label>\"  Yes  \"</label><action>EXIT:yesbutton</action></button>"
+   [ "$OKLABEL" ]  && YESBUTTON="<button><label>${OKLABEL}</label><action>EXIT:yesbutton</action></button>"
    [ "$YESLABEL" ] && YESBUTTON="<button><label>${YESLABEL}</label><action>EXIT:yesbutton</action></button>"
    if [ "$EXTRABUTTON" ];then
-    EXTRABUTTON="<button><label>Extra</label><action>EXIT:extrabutton</action></button>"
+                         EXTRABUTTON="<button><label>Extra</label><action>EXIT:extrabutton</action></button>"
     [ "$EXTRALABEL" ] && EXTRABUTTON="<button><label>${EXTRALABEL}</label><action>EXIT:extrabutton</action></button>"
    fi
-   NOBUTTON="<button><label>No</label><action>EXIT:nobutton</action></button>"
-   [ "$NOLABEL" ] && NOBUTTON="<button><label>${NOLABEL}</label><action>EXIT:nobutton</action></button>"
+                         NOBUTTON="<button><label>No</label><action>EXIT:nobutton</action></button>"
+   [ "$NOLABEL" ]     && NOBUTTON="<button><label>${NOLABEL}</label><action>EXIT:nobutton</action></button>"
    [ "$CANCELLABEL" ] && NOBUTTON="<button><label>${CANCELLABEL}</label><action>EXIT:nobutton</action></button>"
   ;;
   MENU|CHECKLIST)
@@ -196,6 +224,9 @@ done
   ;;
  esac
 
+ if [ "$COUNTDOWN" ]; then
+  NOBUTTON="<button><label>Cancel</label><action>EXIT:nobutton</action></button>"
+ fi
  if [ "$TITLE" ];then
   TITLEPARAMS="title=\"${TITLE}\""
  else
@@ -218,20 +249,23 @@ done
   </hbox>
  </vbox>
  </window>"
-#fi
 
-#dumpdlg="<window ${TITLEPARAMS}>
-# <vbox>
-#  ${BTTEXT}
-#  ${BODYTEXT}
-#  ${MENUXML}
-#  ${INPUTXML}
-#  <hbox>
-#   ${YESBUTTON}${EXTRABUTTON}${NOBUTTON}
-#  </hbox>
-# </vbox>
-# </window>"
-#echo "${dumpdlg}" > /tmp/pupdialog_debug_dumpdlg #for debugging.
+
+_make_debug_file(){
+dumpdlg="<window ${TITLEPARAMS}>
+ <vbox>
+  ${BTTEXT}
+  ${BODYTEXT}
+  ${MENUXML}
+  ${INPUTXML}
+  <hbox>
+   ${YESBUTTON}${EXTRABUTTON}${NOBUTTON}
+  </hbox>
+ </vbox>
+ </window>"
+echo "${dumpdlg}" > /tmp/pupdialog_debug_dumpdlg #for debugging.
+}
+[ "$DEBUG" ] && _make_debug_file
 
 #setup gtk styles...
 #foreground/background colours, not supported by dialog...
@@ -252,47 +286,52 @@ class \"*\" style \"windowstuff\"
 ${insertFS}
 "
 echo "$gtkrc" > /tmp/pupdialog_gtkrc${$}
-export GTK2_RC_FILES=/tmp/pupdialog_gtkrc${$}:$HOME/.gtkrc-2.0
+export GTK2_RC_FILES=/tmp/pupdialog_gtkrc${$}:"$HOME"/.gtkrc-2.0
 
 nTIMEOUT=$TIMEOUT #convert string to numeric.
-if [ $nTIMEOUT -a $nTIMEOUT -ne 0  ];then #assume 0 means never timeout.
+if [ $nTIMEOUT -a $nTIMEOUT -gt 0  ];then #assume 0 means never timeout.
  #note, jwm will use module16.xpm as the window icon...
- /tmp/pupdialog_exec --center --class="module16" --program=PUP${$}DLG > /tmp/pupdialog_retvals${$} &
- dlgPID=$!
+ /tmp/pupdialog_exec --center --class="module16" --program=PUP${$}DLG > /tmp/pupdialog_retvals${$} & dlgPID=$!
  pidPATTERN="^${dlgPID} "
- while [ $nTIMEOUT -ne 0 ];do
-  sleep 1
+ while [ $nTIMEOUT -gt 0 ];do
+  echo $nTIMEOUT >&2
+  sleep 0.9
   ALLPS="`ps`"
-  [ "`echo "$ALLPS" | sed -e 's%^ *%%' | grep "$pidPATTERN"`" == "" ] && break #already killed.
-  nTIMEOUT=$(($nTIMEOUT - 1))
+  [ "`echo "$ALLPS" | sed -e 's%^ *%%' | grep "$pidPATTERN"`" ] || break #already killed.
+  nTIMEOUT=$((nTIMEOUT - 1))
   if [ "$COUNTDOWN" ];then
    BKCOL="yellow"
    [ $nTIMEOUT -lt 31 ] && BKCOL="orange"
    [ $nTIMEOUT -lt 11 ] && BKCOL="red"
    SPLASHSTR="`echo -n "$COUNTDOWN" | sed -e "s%TIME%${nTIMEOUT}%"`"
-   yaf-splash -timeout 2 -bg ${BKCOL} -placement top -close never -fontsize large -fg black -text " ${SPLASHSTR} " >/dev/null &
+   #yaf-splash -timeout 2 -bg ${BKCOL} -placement top -close never -fontsize large -fg black -text " ${SPLASHSTR} " >/dev/null &
+   echo $BKCOL >&2
+   yaf-splash -timeout 1 -bg ${BKCOL} -placement top -fg black -text " ${SPLASHSTR} " & #>/dev/null &
   fi
  done
- if [ $nTIMEOUT -eq 0 ];then #has timed out.
+ if [ $nTIMEOUT -le 0 ];then #has timed out.
   kill $dlgPID
-  rm -f /tmp/pupdialog_gtkrc${$}
-  rm -f /tmp/pupdialog_retvals${$}
-  exit 254 #255 #as per dialog. 130221 change to 254.
+  ( rm $VERB -f /tmp/pupdialog_gtkrc${$} /tmp/pupdialog_retvals${$} ) >&2
+  if [ "$COUNTDOWN" ]; then
+   exit 0
+  else
+   exit 254 #255 #as per dialog. 130221 change to 254.
+  fi
  fi
 else
  #note, jwm will use module16.xpm as the window icon...
  /tmp/pupdialog_exec --center --class="module16" --program=PUP${$}DLG > /tmp/pupdialog_retvals${$}
 fi
 RETVALS="`cat /tmp/pupdialog_retvals${$}`"
-rm -f /tmp/pupdialog_gtkrc${$}
-rm -f /tmp/pupdialog_retvals${$}
+( rm $VERB -f /tmp/pupdialog_gtkrc${$} /tmp/pupdialog_retvals${$} ) >&2
 
 #111011 problem if tags are just numbers, ex 2=true
-xRETVALS="`echo "$RETVALS" | sed -e 's%^%TAGPREFIXFIX_%'`"
+xRETVALS=`echo "$RETVALS" | sed -e 's%^%TAGPREFIXFIX_%'`
 eval "$xRETVALS"
 
 ECHODEST='/dev/stderr'
 [ "$STDOUT" ] && ECHODEST='/dev/stdout'
+( file "$ECHODEST" | grep $Q -i 'text' && echo "$0:WARNING:$ECHODEST is not link to stdin." ) >&2
 if [ "$MENU" ];then
  echo "$RETVALS" | grep '"true"' | head -n 1 | cut -f 1 -d '=' > ${ECHODEST} #echo tag
 fi
