new2dir : Bulk Maintanance Replacement of today.

diff --git a/woof-code/rootfs-skeleton/usr/bin/new2dir b/woof-code/rootfs-skeleton/usr/bin/new2dir
--- a/woof-code/rootfs-skeleton/usr/bin/new2dir
+++ b/woof-code/rootfs-skeleton/usr/bin/new2dir
@@ -341,27 +341,31 @@ read nextphase
 
 cd ${RELPATH}
 if [ -d ${xNAMEONLY}-${VERONLY}-${CPUTYPE} ];then
- dir2pet ${xNAMEONLY}-${VERONLY}-${CPUTYPE}
+ dir2pet ${xNAMEONLY}-${VERONLY}-${CPUTYPE} && {
  echo -n "${xNAMEONLY}-${VERONLY}-${CPUTYPE}.pet created. Press ENTER to continue: "
  read domore
+} || { echo "Some error occured"; exit 1; }
 fi
 
 if [ -d ${xNAMEONLY}_DEV-${VERONLY}-${CPUTYPE} ];then
- dir2pet ${xNAMEONLY}_DEV-${VERONLY}-${CPUTYPE}
+ dir2pet ${xNAMEONLY}_DEV-${VERONLY}-${CPUTYPE} && {
  echo -n "${xNAMEONLY}_DEV-${VERONLY}-${CPUTYPE}.pet created. Press ENTER to continue: "
  read domore
+} || { echo "Some error occured"; exit 1; }
 fi
 
 if [ -d ${xNAMEONLY}_DOC-${VERONLY}-${CPUTYPE} ];then
- dir2pet ${xNAMEONLY}_DOC-${VERONLY}-${CPUTYPE}
+ dir2pet ${xNAMEONLY}_DOC-${VERONLY}-${CPUTYPE} && {
  echo -n "${xNAMEONLY}_DOC-${VERONLY}-${CPUTYPE}.pet created. Press ENTER to continue: "
  read domore
+} || { echo "Some error occured"; exit 1; }
 fi
 
 if [ -d ${xNAMEONLY}_NLS-${VERONLY}-${CPUTYPE} ];then
- dir2pet ${xNAMEONLY}_NLS-${VERONLY}-${CPUTYPE}
+ dir2pet ${xNAMEONLY}_NLS-${VERONLY}-${CPUTYPE} && {
  echo -n "${xNAMEONLY}_NLS-${VERONLY}-${CPUTYPE}.pet created. Press ENTER to continue: "
  read domore
+} || { echo "Some error occured"; exit 1; }
 fi
 
 echo "All done."
