/usr/bin/pet2tgz tgz2pet pup2pet : Code cleanups.

diff --git a/woof-code/rootfs-skeleton/usr/bin/tgz2pet b/woof-code/rootfs-skeleton/usr/bin/tgz2pet
--- a/woof-code/rootfs-skeleton/usr/bin/tgz2pet
+++ b/woof-code/rootfs-skeleton/usr/bin/tgz2pet
@@ -3,19 +3,19 @@
 # New header by Karl Reimer Godt, September 2014
   _TITLE_="Puppy_tgz2pet"
 _VERSION_=1.0omega
-_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"
+_COMMENT_="$_TITLE_: Create a .pet from a .tar file"
 
 MY_SELF="/usr/bin/tgz2pet"
 MY_PID=$$
 
 test -f /etc/rc.d/f4puppy5 && {
-[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5
+[ "$HAVE_F4PUPPY5" ] || . /etc/rc.d/f4puppy5
 
 ADD_PARAMETER_LIST=""
 ADD_PARAMETERS=""
 _provide_basic_parameters
 
-TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
+TWO_HELP='1'; TWO_VERSION='1'; TWO_VERBOSE='1'; TWO_DEBUG='1'; ## Set to anything if code requires further down (ie. custom usage or version message)
 ADD_HELP_MSG="$_COMMENT_"
 _parse_basic_parameters "$@"
 [ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
@@ -92,7 +92,7 @@ OUT=/dev/null;ERR=$OUT
 [ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
 [ "$DEBUG" = "2" ] && set -x
 
-usage (){
+_usage (){
     echo "
 $0 [-g|-b|-l|-h|-s|-S|-X|-x|-Z|-z] TARFILE.tar.EXT
     -g) gzip (default) '`which gzip`'
@@ -119,36 +119,36 @@ while getopts gbhlLsSXxZzdv opt;do
 case $opt in
 g) COMPRESS_BIN='gzip'; OPT='-g';EXT='.gz'; PET_EXT='.pet';;
 b) COMPRESS_BIN='bzip2';OPT='-b';EXT='.bz2';PET_EXT='.b2pet';;
-h) usage 0;;
+h) _usage 0;;
 l) COMPRESS_BIN='lzop';OPT='-l';EXT='.lzo'; PET_EXT='.lopet';;
 L) COMPRESS_BIN='lzma';OPT='-L';EXT='.lzma';PET_EXT='.lapet';;
 s) COMPRESS_BIN='mksquashfs3';PET_EXT='.s3pet';;
 S) COMPRESS_BIN='mksquashfs4';PET_EXT='.s4pet';;
 X) COMPRESS_BIN='mksquashfs4';COMPRESS_OPT='xz';PET_EXT='.s4xpet';;
 x) COMPRESS_BIN='xz';OPT='-x';EXT='.xz';PET_EXT='.xzpet'
-if [ ! "`which $COMPRESS_BIN`" ];then
-COMPRESS_BIN='tar'
-["`$COMPRESS_BIN --help |grep -w '\-J'`" ] || COMPRESS_BIN='';fi
+   if [ ! "`which $COMPRESS_BIN`" ];then
+   COMPRESS_BIN='tar'
+   ["`$COMPRESS_BIN --help |grep -w '\-J'`" ] || COMPRESS_BIN='';fi
 ;;
 z) COMPRESS_BIN='zip';OPT='-z';EXT='.zip';PET_EXT='.zipet';;
 Z) COMPRESS_BIN='compress';OPT='-Z';EXT='.Z';PET_EXT='.Zpet'
-if [ ! "`which $COMPRESS_BIN`" ];then
-COMPRESS_BIN='tar'
-["`$COMPRESS_BIN --help |grep -w '\-Z'`" ] || COMPRESS_BIN='';fi
+   if [ ! "`which $COMPRESS_BIN`" ];then
+   COMPRESS_BIN='tar'
+   ["`$COMPRESS_BIN --help |grep -w '\-Z'`" ] || COMPRESS_BIN='';fi
 ;;
 d) set -x;;
-v) VERBOSE='-v';LONG_VERBOSE='--verbose';OUTPUT=/dev/stderr;;
-*) usage 1;;
+v) VERBOSE='-v';L_VERBOSE='--verbose';OUT=/dev/stderr;;
+*) _usage 1;;
 esac;done
 
 while [ "$2" ];do shift;done #leave only the last argument
 
 if [ ! "$COMPRESS_BIN" ];then
 #automatic detection
-AEXT="${1##*\.}";echo "AEXT='$AEXT'"
-case $AEXT in
+aEXT="${1##*\.}";echo "aEXT='$aEXT'"
+case $aEXT in
 gz|tgz|tar) COMPRESS_BIN='gzip'; OPT='-g';EXT='.gz'; PET_EXT='.pet';;
-bz2)        COMPRESS_BIN='bzip2';OPT='-b';EXT='.bz2';PET_EXT='.b2pet';;
+bz2|tbz)    COMPRESS_BIN='bzip2';OPT='-b';EXT='.bz2';PET_EXT='.b2pet';;
 
 lzo|tzo|lzop)           COMPRESS_BIN='lzop';OPT='-l';EXT='.lzo'; PET_EXT='.lopet';;
 lzx|lza|lzm|lzma|lzma2) COMPRESS_BIN='lzma';OPT='-L';EXT='.lzma';PET_EXT='.lapet';;
@@ -156,115 +156,155 @@ lzw)        COMPRESS_BIN=compress-4.2;; ##like .Z (?)
 lha|lza)    COMPRESS_BIN=lha;;
 lz|lzp|lzip)COMPRESS_BIN=lzip;;
 
-xz)  COMPRESS_BIN='xz';      OPT='-x';EXT='.xz'; PET_EXT='.xzpet'
-if [ ! "`which $COMPRESS_BIN`" ];then
-COMPRESS_BIN='tar'
-[ "`$COMPRESS_BIN --help |grep -w '\-J'`" ] || COMPRESS_BIN='';fi
+txz|xz) COMPRESS_BIN='xz';      OPT='-x';EXT='.xz'; PET_EXT='.xzpet'
+    if [ ! "`which $COMPRESS_BIN`" ];then
+    COMPRESS_BIN='tar'
+    [ "`$COMPRESS_BIN --help |grep -w '\-J'`" ] || COMPRESS_BIN='';fi
 ;;
 z|Z) COMPRESS_BIN='compress';OPT='-Z';EXT='.Z';  PET_EXT='.Zpet';;
 zip) COMPRESS_BIN='zip';     OPT='-z';EXT='.zip';PET_EXT='.zipet'
-if [ ! "`which $COMPRESS_BIN`" ];then
-COMPRESS_BIN='tar'
-[ "`$COMPRESS_BIN --help |grep -w '\-Z'`" ] || COMPRESS_BIN='';fi
+     if [ ! "`which $COMPRESS_BIN`" ];then
+     COMPRESS_BIN='tar'
+     [ "`$COMPRESS_BIN --help |grep -w '\-Z'`" ] || COMPRESS_BIN='';fi
 ;;
 esac
 fi
 
 [ "$COMPRESS_BIN" ] || { COMPRESS_BIN='gzip';EXT='.gz';PET_EXT='.pet'; }
 [ "`which $COMPRESS_BIN`" ] || { echo "'$COMPRESS_BIN' apparenty not installed (in the PATH)";exit 1; }
-[ -e "$1" ] || { echo "'$1' seems not to exist";exit 1; }
-[ -f "$1" ] || { echo "'$1' not a regular file ?";exit 1; }
+[ -e "$1" ] || { echo "'$1' seems not to exist";   exit 1; }
+[ -f "$1" ] || { echo "'$1' not a regular file ?"; exit 1; }
 [ -s "$1" ] || { echo "'$1' appears to be empty ?";exit 1; }
-sync
-TARBALL=$1
-chmod +w $TARBALL #make it writable.
+_sync
+
+STATUS=0
+TARBALL="$1"
+
+[ -e "$TARBALL" ] _exit 2 "$TARBALL seems not to be a regular file'"
+
+chmod +w "$TARBALL" #make it writable.
+STATUS=$((STATUS+$?))
 
 #only accept .tgz or .tar.gz files...
 #EXT=''
 case $COMPRESS_BIN in
 gzip)
-[ "`echo -n "$TARBALL" | grep '\\.tar\\.gz$'`" ] && TEXT='.tar.gz'
-[ "`echo -n "$TARBALL" | grep '\\.tgz$'`" ] && TEXT='.tgz'
-[ "`echo -n "$TARBALL" | grep '\\.tar$'`" ] && TEXT='.tar'
-[ "$TEXT" ] || usage 1
+[ "`echo "$TARBALL" | grep '\.tar\\.gz$'`" ] && TEXT='.tar.gz'
+[ "`echo "$TARBALL" | grep '\.tgz$'`" ]      && TEXT='.tgz'
+[ "`echo "$TARBALL" | grep '\.tar$'`" ]      && TEXT='.tar'
+[ "$TEXT" ] || _usage 1
 ;;
 bzip2)
-[ ! "`echo -n "$TARBALL" | grep '\\.tar\\.bz2$'`" = "" ] && TEXT='.tar.bz2'
-[ "$TEXT" ] || usage 1
+[ "`echo "$TARBALL" | grep '\.tar\.bz2$'`" ] && TEXT='.tar.bz2'
+[ "$TEXT" ] || _usage 1
 ;;
 lzop)
-[ "`echo -n "$TARBALL" | grep '\\.tar\\.lzo$'`" ] && TEXT='.tar.lzo'
-[ "`echo -n "$TARBALL" | grep '\\.tzo$'`"] && TEXT='.tzo'
-[ "$TEXT" ] || usage 1
+[ "`echo "$TARBALL" | grep '\.tar\.lzo$'`" ] && TEXT='.tar.lzo'
+[ "`echo "$TARBALL" | grep '\.tzo$'`"]       && TEXT='.tzo'
+[ "$TEXT" ] || _usage 1
 ;;
 lzma)
-[ "`echo -n "$TARBALL" | grep '\\.tar\\.lzma$'`" ] && TEXT='.tar.lzma'
-[ "$TEXT" ] || usage 1
+[ "`echo "$TARBALL" | grep '\.tar\.lzma$'`" ] && TEXT='.tar.lzma'
+[ "$TEXT" ] || _usage 1
 ;;
 mksquashfs3)
-[ "`echo -n "$TARBALL" | grep '\\.tar\\.gz$'`" ] && TEXT='.tar.gz'
-[ "$TEXT" ] || usage 1
+[ "`echo "$TARBALL" | grep '\.tar\.gz$'`" ] && TEXT='.tar.gz'
+[ "$TEXT" ] || _usage 1
 ;;
 mksquashfs4)
  case $COMPRESS_OPT in
   xz)
-   [ "`echo -n "$TARBALL" | grep '\\.tar\\.gz$'`" ] && TEXT='.tar.gz'
-   [ "$TEXT" ] || usage 1;;
+   [ "`echo "$TARBALL" | grep '\.tar\.gz$'`" ] && TEXT='.tar.gz'
+   [ "$TEXT" ] || _usage 1;;
   ""|*)
-   [ "`echo -n "$TARBALL" | grep '\\.tar\\.gz$'`" ] && TEXT='.tar.gz'
-   [ "$TEXT" ] || usage 1;;
+   [ "`echo "$TARBALL" | grep '\.tar\.gz$'`" ] && TEXT='.tar.gz'
+   [ "$TEXT" ] || _usage 1;;
  esac
 ;;
 xz)
-[ "`echo -n "$TARBALL" | grep '\\.tar\\.xz$'`" ] && TEXT='.tar.xz'
-[ "$TEXT" ] || usage 1
+[ "`echo "$TARBALL" | grep '\.tar\.xz$'`" ] && TEXT='.tar.xz'
+[ "$TEXT" ] || _usage 1
 ;;
 esac
 
 
 
 #split TARBALL path/filename into components...
-BASEPKG="`basename $TARBALL $TEXT`"
-DIRPKG="`dirname $TARBALL`"
-[ "$DIRPKG" = "/" ] && DIRPKG=""
+pkgBAS="`basename "$TARBALL" $TEXT`"
+pkgDIR="`dirname  "$TARBALL"`"
+[ "$pkgDIR" = "/" ] && pkgDIR=""
 
 #perhaps makes following code easier if do this...
 if [ "$TEXT" = ".tgz" ];then
- mv -f $TARBALL $DIRPKG/${BASEPKG}.tar.gz
- TARBALL="$DIRPKG/${BASEPKG}.tar.gz"
+ mv -f "$TARBALL" $pkgDIR/${pkgBAS}.tar.gz
+ STATUS=$((STATUS+$?))
+ TARBALL="$pkgDIR/${pkgBAS}.tar.gz"
  TEXT='.tar.gz'
-fi
-if [ "$TEXT" = ".tzo" ];then
- mv -f $TARBALL $DIRPKG/${BASEPKG}.tar.lzo
- TARBALL="$DIRPKG/${BASEPKG}.tar.lzo"
+
+elif [ "$TEXT" = ".tzo" ];then
+ mv -f "$TARBALL" $pkgDIR/${pkgBAS}.tar.lzo
+ STATUS=$((STATUS+$?))
+ TARBALL="$pkgDIR/${pkgBAS}.tar.lzo"
  TEXT='.tar.lzo'
-fi
-if [ "$TEXT" = ".tar" ];then
- $COMPRESS_BIN $TARBALL
- TARBALL="$DIRPKG/${BASEPKG}.tar${EXT}"
+
+elif [ "$TEXT" = ".tar" ];then
+ $COMPRESS_BIN "$TARBALL"
+ STATUS=$((STATUS+$?))
+ TARBALL="$pkgDIR/${pkgBAS}.tar${EXT}"
  TEXT=".tar${EXT}"
 fi
-echo "TARBALL='$TARBALL' TEXT='$TEXT' EXT='$EXT' PET_EXT='$PET_EXT'"
+_debug "TARBALL='$TARBALL' TEXT='$TEXT' EXT='$EXT' PET_EXT='$PET_EXT'"
+
 #if tarball expands direct to '/' want to wrap around it (slackware pkg)...
 if [ "`tar --list -f $TARBALL | head -n 1`" = "./" ];then
- [ -d $DIRPKG/$BASEPKG ] && rm -rf $DIRPKG/$BASEPKG #a bit radical
- #[ -d $DIRPKG/$BASEPKG ] && exit 1
- mkdir $DIRPKG/$BASEPKG
- mv $DIRPKG/${BASEPKG}${TEXT} $DIRPKG/$BASEPKG/
+
+ [ -d $pkgDIR/$pkgBAS ] && rm $VERB -rf $pkgDIR/$pkgBAS #a bit radical
+ #[ -d $pkgDIR/$pkgBAS ] && exit 1
+
+ mkdir $VERB -p "$pkgDIR"/"$pkgBAS"
+ mv $VERB -f "$pkgDIR"/"${pkgBAS}${TEXT}" "$pkgDIR"/"$pkgBAS"/
+
+
  #can put other files in here if want...
 
- tar --remove-files -c -f $DIRPKG/${BASEPKG}.tar $DIRPKG/$BASEPKG/
- $COMPRESS_BIN $DIRPKG/${BASEPKG}.tar
- rmdir $DIRPKG/$BASEPKG
+ tar --remove-files -c -f "$pkgDIR"/"${pkgBAS}".tar "$pkgDIR"/"$pkgBAS"/
+ STATUS=$((STATUS+$?))
+
+ $COMPRESS_BIN "$pkgDIR"/"${pkgBAS}".tar
+ STATUS=$((STATUS+$?))
+
+ rmdir $VERB "$pkgDIR"/"$pkgBAS"
 fi
 
-FULLSIZE="`stat -c %s ${TARBALL}`"
-MD5SUM="`md5sum $TARBALL | cut -f 1 -d ' '`"
-echo -n "$MD5SUM" >> $TARBALL
-sync
+[ -e "$TARBALL" ] || _exit 10 "Could not create '$TARBALL' ."
+
+FULLSIZE="`stat -c %s "${TARBALL}"`"
+STATUS=$((STATUS+$?))
+
+MD5SUM="`md5sum "$TARBALL" | cut -f 1 -d ' '`"
+STATUS=$((STATUS+$?))
+
+echo -n "$MD5SUM" >> "$TARBALL"
+STATUS=$((STATUS+$?))
+
+_sync
 #NEWNAME="`echo -n "${TARBALL}" | sed -e 's/\\.tar\\.gz$/\\.pet/g'`"
 #mv -f $TARBALL $NEWNAME
-mv -f $TARBALL $DIRPKG/${BASEPKG}${PET_EXT}
-sync
-exit $?
+
+if [ "$DEBUG" ]; then
+cp $VERB -f "$TARBALL" "$pkgDIR"/"${pkgBAS}${PET_EXT}"
+else
+mv $VERB -f "$TARBALL" "$pkgDIR"/"${pkgBAS}${PET_EXT}"
+fi
+STATUS=$((STATUS+$?))
+
+_sync
+
+if [ "$STATUS" = 0 ]; then
+ echo "Successfully created ${pkgBAS}${PET_EXT} ."
+else
+ echo "Creating ${pkgBAS}${PET_EXT} collected $STATUS errors.."
+fi
+
+exit $STATUS
 ###END###
