xwin : Cleanups.

diff --git a/woof-code/rootfs-skeleton/usr/bin/xwin b/woof-code/rootfs-skeleton/usr/bin/xwin
--- a/woof-code/rootfs-skeleton/usr/bin/xwin
+++ b/woof-code/rootfs-skeleton/usr/bin/xwin
@@ -145,11 +145,11 @@ if [ "$HAVEXvesa" ];then
    rm -f /etc/.XLOADED 2> /dev/null #not necessary, precaution.
    #1st dialog offers to use Xvesa...
    /usr/sbin/xorgwizard
-   HAVEX="`readlink /usr/bin/X`"
+   HAVEX=`readlink /usr/bin/X`
     ##if test "`echo $HAVEX | grep '/'`" != ""; then
     HAVEX=`basename $HAVEX`
     ##fi
-   [ "$HAVEX" != "Xorg" ] && exit   #go to command line if not Xorg
+   [ "$HAVEX" = "Xorg" ] || exit   #go to command line if not Xorg
   fi
  fi
 fi
@@ -173,7 +173,7 @@ if [ "$HAVEXvesa" ] ; then
   # fi
   #fi
   #v3.97 improved method: CM=Classmate, 915=chip 10=generation#...
-  [ "`dmidecode -s bios-version | grep '^CM91510'`" != "" ] && echo 'timing: 800x480@60' >> /tmp/ddcprobe.txt
+  [ "`dmidecode -s bios-version | grep '^CM91510'`" ] && echo 'timing: 800x480@60' >> /tmp/ddcprobe.txt
   #v3.95 recognise more special screens...
   DMIDECODE="`dmidecode`"
   #recognise EeePC Asus laptop...
@@ -184,12 +184,12 @@ if [ "$HAVEXvesa" ] ; then
 
   #get too many weird resolutions, maybe better just only allow these...
   #want widescreen/non-vesa resolutions only...
-  VESAMODES="`$HAVEXvesa -listmodes 2>&1 | grep '^0x' | tr ':' ' ' | tr -s ' ' | cut -f 1,2 -d ' '`"
+  VESAMODES=`$HAVEXvesa -listmodes 2>&1 | grep '^0x' | tr ':' ' ' | tr -s ' ' | cut -f 1,2 -d ' '`
   rm /tmp/ddcprobeoem.txt  #v3.99 didn't hang in Xvesa, so delete signature
   MONCHOICES="`grep -F 'timing:' /tmp/ddcprobe.txt | grep -E -v 'Apple|8514A|Mac II|\(XGA2\)' | grep -E ' 800x480@| 1024x600@| 1280x768@| 1280x800@| 1280x1024@| 1360x768@| 1400x1050@| 1440x900@| 1600x1200@| 1680x1050@| 1920x1080@| 1920x1200@' | cut -f 2 -d ' ' | sort -u`"
 
   if [ "$MONCHOICES" != "" ];then  #1
-   MONCUTXY="`echo "$MONCHOICES" | cut -f 1 -d '@' | tr '\n' ' '`"
+   MONCUTXY=`echo "$MONCHOICES" | cut -f 1 -d '@' | tr '\n' ' '`
 
    #v2.21 code to handle widescreen with intel video chips...
    if [ ! -f /etc/resolutionfix ];then ##2
@@ -198,16 +198,16 @@ if [ "$HAVEXvesa" ] ; then
      for ONECUTXY in $MONCUTXY #ex: each field 1024x768
      do
       OPATTERN=" ${ONECUTXY}x"
-      [ "`echo "$VESAMODES" | grep "$ONECUTXY"`" = "" ] && MISSINGXY="$ONECUTXY"
+      [ "`echo "$VESAMODES" | grep "$ONECUTXY"`" ] || MISSINGXY="$ONECUTXY"
      done
      if [ "$MISSINGXY" != "" ];then  #4
       MYXRES="`echo -n "$MISSINGXY" | cut -f 1 -d 'x'`"
-      MYYRES="`echo -n "$MISSINGXY" | cut -f 2 -d 'x'`"
+      MYYRES=`echo -n "$MISSINGXY" | cut -f 2 -d 'x'`
       915resolution 38 $MYXRES $MYYRES
       #...replaces mode 38 (1024x768).
       #create something for /etc/profile to execute at bootup...
       echo "915resolution 38 $MYXRES $MYYRES" > /etc/resolutionfix
-      VESAMODES="`$HAVEXvesa -listmodes 2>&1 | grep '^0x' | tr ':' ' ' | tr -s ' ' | cut -f 1,2 -d ' '`"
+      VESAMODES=`$HAVEXvesa -listmodes 2>&1 | grep '^0x' | tr ':' ' ' | tr -s ' ' | cut -f 1,2 -d ' '`
       PPATTERN=" ${MYXRES}x${MYYRES}x"
       #BASEMOD is res that we are going to start X with...
       BASEMODE="`echo "$VESAMODES" | grep "$PPATTERN" | grep -E 'x16$|x24$|x32$' | head -n 1`"
@@ -219,11 +219,11 @@ if [ "$HAVEXvesa" ] ; then
    if [ "$BASEMODE" = "" ];then
     #if [ "`echo "$MONCUTXY" | wc -l`" = "1" ];then
      QPATTERN=`echo "$MONCHOICES" | cut -f 1 -d '@' | tr '\n' '|'`
-     BASEMODE="`echo "$VESAMODES" | grep -E "$QPATTERN" | grep -E 'x16$|x24$|x32$' | head -n 1`"
+     BASEMODE=`echo "$VESAMODES" | grep -E "$QPATTERN" | grep -E 'x16$|x24$|x32$' | head -n 1`
     #fi
    fi
 
-   if [ "$BASEMODE" != "" ];then
+   if [ "$BASEMODE" ];then
     echo "$BASEMODE" > /etc/videomode #no need for wizard after startup!
     rm -f /tmp/videomode 2>/dev/null #w460 make sure can exit from X.
    fi
@@ -231,7 +231,7 @@ if [ "$HAVEXvesa" ] ; then
   ###end of MONCHOICES !not empty part
   ##Final Fallback :
   if [ "$BASEMODE" = "" ];then
-   BASEMODE="`echo "$VESAMODES" | grep ' 800x600x16' | head -n 1`"
+   BASEMODE=`echo "$VESAMODES" | grep ' 800x600x16' | head -n 1`
    if [ "$BASEMODE" != "" ];then
     echo "$BASEMODE" > /tmp/videomode
    else
@@ -247,14 +247,15 @@ if [ "$HAVEXvesa" ] ; then
  fi
 
 fi
-echo `date` "2: finished checking for HAVEXvesa"
+echo "`date` 2: finished checking for HAVEXvesa"
 #note, mouse and keyboard types are autodetected in /etc/rc.d/rc.local0 at every bootup,
 #so /etc/mousedevice and /etc/keyboardtype have autodetected values in them
 #(changeable by Mouse/Keyboard Wizard, but rc.local0 will override if interface not found).
 
 #v411 restored after removal in v407...
 #update xorg.conf if mouse has changed...
-MOUSEDEV="`cat /etc/mousedevice`" #autodetected in rc.sysinit
+#MOUSEDEV="`cat /etc/mousedevice`" #autodetected in rc.sysinit
+read MOUSEDEV </etc/mousedevice
 OLDMOUSEDEV="`cat /etc/oldmousedevice`" #set in rc.sysinit
 if [ ! "$OLDMOUSEDEV" = "$MOUSEDEV" ];then
  if [ ! "$OLDMOUSEDEV" = "nothing" ];then #"nothing" on first boot.
@@ -281,7 +282,7 @@ if [ ! "$OLDMOUSEDEV" = "$MOUSEDEV" ];then
 fi
 
 #v408 k2.6.25.16 has serial driver as a module...
-[ "`grep 'ttyS' /etc/mousedevice`" != "" ] && modprobe sermouse
+[ "`grep 'ttyS' /etc/mousedevice`" ] && modprobe sermouse
 #v411 precaution...
 [ "`grep 'input/mice' /etc/mousedevice`" != "" ] && modprobe usbhid
 
@@ -308,7 +309,7 @@ if [ ! -f /etc/mousebuttons ];then
  #fi
 fi
 
-echo `date` "3: finished checking for mouse"
+echo "`date` 3: finished checking for mouse"
 #now done in /etc/rc.d/rc.modules...
 ##alsa sound setup...
 #if [ "`cat /etc/modprobe.conf | grep 'snd\-card\-0'`" = "" ];then
@@ -329,11 +330,11 @@ echo `date` "3: finished checking for mouse"
 if [ -f /usr/bin/Xorg ];then
  if [ -f /etc/X11/xorg.conf ];then
   #find location of video chip drivers...
-  SPECVESA="`find -L /usr/lib -noleaf -mount -type f -name vesa_drv.so`"
+  SPECVESA=`find -L /usr/lib -noleaf -xdev -type f -name vesa_drv.so`
   if [ "$SPECVESA" ];then
    DRVRSPATH="`dirname $SPECVESA`"
    #get current driver...
-   DRVRCURR="`cat /etc/X11/xorg.conf | grep '#card0driver' | cut -f 2 -d '"'`" #'
+   DRVRCURR=`cat /etc/X11/xorg.conf | grep '#card0driver' | cut -f 2 -d '"'`
    if [ "$DRVRCURR" ];then
     #if [ ! -f $DRVRSPATH/${DRVRCURR}_drv.so ];then
     #one driver is mtx_drv.o hmmm, okay do it this way (pakt)...
@@ -359,7 +360,7 @@ if [ -f /usr/bin/Xorg ];then
   if [ "$RLX" = "Xorg" ];then
 
    #v2.13 video hardware profile (must be same as in xorgwizard)...
-   DDCPROBE="`ddcprobe`"
+   DDCPROBE=`ddcprobe`
    #v2.17 patch from Nightflyer... as in xwin, may have to run ddcprobe twice...
    case "`echo "$DDCPROBE"`" in
     *edidfail*)
@@ -367,19 +368,19 @@ if [ -f /usr/bin/Xorg ];then
      DDCPROBE="`ddcprobe`"
     ;;
    esac
-   PROFILECHIP="`echo "$DDCPROBE" | grep '^oem: ' | head -n 1 | cut -f 2-4 -d ' ' | tr ' ' '_' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
+   PROFILECHIP=`echo "$DDCPROBE" | grep '^oem: ' | head -n 1 | cut -f 2-4 -d ' ' | tr ' ' '_' | sed -e 's/[^0-9a-zA-Z]/_/g'`
    #PROFILEMONITOR="`echo "$DDCPROBE" | grep --extended-regexp '^monitorrange: |^monitorid: |^eisa: ' | head -n 1 | cut -f 2 -d ':' | sed -e 's/ //g' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
 #v3.95 'eisa:' and 'id:' return fluctuating values on some PCs, so search in this order...
 PROFILEMONITOR="`echo "$DDCPROBE" | grep '^monitorid: ' | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
 [ "$PROFILEMONITOR" = "" ] && PROFILEMONITOR="`echo "$DDCPROBE" | grep '^monitorname: ' | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
 [ "$PROFILEMONITOR" = "" ] && PROFILEMONITOR="`echo "$DDCPROBE" | grep '^monitorrange: ' | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
 #[ "$PROFILEMONITOR" = "" ] && PROFILEMONITOR="`echo "$DDCPROBE" | grep '^dtiming: ' | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
-[ "$PROFILEMONITOR" = "" ] && PROFILEMONITOR="`echo "$DDCPROBE" | grep '^manufacture: ' | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
+[ "$PROFILEMONITOR" ] || PROFILEMONITOR=`echo "$DDCPROBE" | grep '^manufacture: ' | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`
 #[ "$PROFILEMONITOR" = "" ] && PROFILEMONITOR="`echo "$DDCPROBE" | grep '^eisa: ' | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g'`"
 
    HARDWAREPROFILE="${PROFILECHIP}${PROFILEMONITOR}"
    #find out if current xorg.conf matches this profile...
-   CURRENTPROFILE="`cat /etc/X11/xorg.conf | grep '^#PuppyHardwareProfile' | cut -f 2 -d '=' | cut -f 1 -d ' '`"
+   CURRENTPROFILE=`cat /etc/X11/xorg.conf | grep '^#PuppyHardwareProfile' | cut -f 2 -d '=' | cut -f 1 -d ' '`
    if [ ! "$CURRENTPROFILE" = "$HARDWAREPROFILE" ];then
     #video hardware has changed. either changed monitor or booting different PC.
     #same current xorg.conf as a profiled filename...
@@ -394,7 +395,7 @@ PROFILEMONITOR="`echo "$DDCPROBE" | grep '^monitorid: ' | head -n 1 | cut -f 2 -
   #1st dialog offers to use Xvesa...
   /usr/sbin/xorgwizard
 
-  HAVEX="`readlink /usr/bin/X`"
+  HAVEX=`readlink /usr/bin/X`
   #if test "`echo $HAVEX | grep '/'`" != ""; then
     HAVEX=`basename $HAVEX`
     #fi
@@ -402,7 +403,7 @@ PROFILEMONITOR="`echo "$DDCPROBE" | grep '^monitorid: ' | head -n 1 | cut -f 2 -
   [ "$HAVEXvesa" ] && exec xwin
  fi
 fi
-echo `date` "4: finished checking for Xorg"
+echo "`date` 4: finished checking for Xorg"
 #v1.0.7 J_Reys idea (see note further down)...
 if [ -f /etc/.XLOADED ];then
  #v3.98 improved handling by pizzasgood...
@@ -443,7 +444,7 @@ Video Wizard, type "xorgwizard", and after configuring /etc/X11/xorg.conf
  fi
 
 fi
-echo `date` "5: finished checking for XLOADED"
+echo "`date` 5: finished checking for XLOADED"
 
 ##if [ "$HAVEX" = "Xvesa" ];then #0.9.9
 if [ "$HAVEXvesa" ] ; then
@@ -474,7 +475,7 @@ if [ "$HAVEXvesa" ] ; then
  #/tmp/videomode exists if starting X with new video test mode...
  if [ -e /tmp/videomode ];then
   #stored in format "0x0111 640x480x16"
-  VIDMODE="`cat /tmp/videomode | cut -f 1 -d ' '`"
+  VIDMODE=`cat /tmp/videomode | cut -f 1 -d ' '`
   VIDSCRN="`cat /tmp/videomode | tr -s ' ' | cut -f 2 -d ' '`"
  else
   #stored in format "0x0111 640x480x16"
@@ -482,7 +483,7 @@ if [ "$HAVEXvesa" ] ; then
   VIDSCRN="`cat /etc/videomode | tr -s ' ' | cut -f 2 -d ' '`"
  fi
 fi
-echo `date` "6: finished checking for HAVEXvesa"
+echo "`date` 6: finished checking for HAVEXvesa"
 
 
 MOUSEBUTTONS=3
@@ -494,7 +495,7 @@ if [ $MOUSEBUTTONS -eq 2 ];then
  #the problem is, if /etc/xextraoptions has '-2button' which turns on middle-button
  #emulation, if leave MOUSEBUTTONS=2 then the right button does not work.
  #have to pass '3' to Xvesa, meaning effectively 3 buttons available...
- [ ! "`cat /etc/xextraoptions | grep ' \-2button'`" = "" ] && MOUSEBUTTONS=3
+ [ "`cat /etc/xextraoptions | grep ' \-2button'`" != "" ] && MOUSEBUTTONS=3
 fi
 
 #0.9.8
@@ -514,17 +515,17 @@ fi
 #v424 bad hack, i somehow get /dev/mouse pointing to psaux when chose a serial mouse, don't know why...
 [ "`grep 'ttyS' /etc/mousedevice`" != "" ] && ln -snf $MOUSEDEV /dev/mouse
 
-echo `date` "7: finally start X"
+echo "`date` 7: finally start X"
 #finally, start X...
 #J_Rey had a good idea, flag XLOADED... and set to false on exit.
 #but if PC hangs, XLOADED will still be true, so will know it is broken.
 echo -n "true" > /etc/.XLOADED
-echo 'HAVEX='"$HAVEX"'_EOS'
+echo "HAVEX='$HAVEX'"
 case $HAVEX in
  #Xvesa|Xvesa*|Xnvidia|Xnvidia*|Xchips|Xephyr|Xepson|Xfake|Xfbdev|Xi810|Xmach64|Xmga|Xneomagic|Xnest|Xpm2|Xrt28|Xsdl|Xsmi|Xvfb|Xvia)
  Xvesa|Xvesa*|Xchips)
 
-  echo "Starting X with video mode $VIDMODE and mouse $MOUSEDEV..."
+  echo "Starting X with video mode '$VIDMODE' and mouse '$MOUSEDEV' ..."
   #w479 older Xvesa server may not recognise the '-sp' option...
   if [ "`$HAVEXvesa -help 2>&1 | grep '^\-sp '`" = "" ];then
    SPOPTION=''
@@ -533,7 +534,7 @@ case $HAVEX in
   fi
   #startx $VIDMODE $MOUSEDEV > /tmp/xerrs.txt 2>&1
   #Puppy 0.8.4 no need for startx script...
-  VIDFREQ="`echo -n "$VIDSCRN" | cut -f 4 -d "x"`"
+  VIDFREQ=`echo -n "$VIDSCRN" | cut -f 4 -d "x"`
   if [ ! "$VIDFREQ" ];then
    echo "$VIDMODE" > /tmp/currentvideomode
    #w460 added -fp and -sp options...
@@ -548,23 +549,23 @@ case $HAVEX in
   ;;
  Xfbdev)  ##no -mode option : Fatal server error:no screens found XIO:  fatal IO error 104 (Connection reset by peer) on X server ":0.0" after 0 requests (0 known processed) with 0 events remaining.
 
-  echo "Starting X with Xfbdev Kdrive X server, mouse $MOUSEDEV..."
+  echo "Starting X with Xfbdev Kdrive X server, mouse '$MOUSEDEV' ..."
   /usr/bin/xinit /root/.xinitrc -- -mouse /dev/mouse,$MOUSEBUTTONS > /tmp/xerrs.$HAVEX.log 2>&1
   RETval1=$?
   ;;
  Xi810) #v1.0.7
-  echo "Starting X with Xi810 Kdrive X server, mouse $MOUSEDEV..."
+  echo "Starting X with Xi810 Kdrive X server, mouse '$MOUSEDEV' ..."
   #echo "(experimental, currently fixed to 1024x768x16x72 in /usr/bin/xwin)"
    /usr/bin/xinit /root/.xinitrc -- -screen $VIDSCRN -mouse /dev/mouse,$MOUSEBUTTONS > /tmp/xerrs.$HAVEX.log 2>&1
   RETval1=$?
   ;;
  XF86_SVGA)
-  echo "Starting X, specs in /etc/X11/XF86Config, startup apps /root/.xinitrc..."
+  echo "Starting XF86_SVGA, specs in /etc/X11/XF86Config, startup apps /root/.xinitrc..."
   /usr/bin/xinit /root/.xinitrc -- -bpp 16 > /tmp/xerrs.$HAVEX.log 2>&1
   RETval1=$?
   ;;
  Xorg)
-  echo "Starting X, specs in /etc/X11/xorg.conf, startup apps /root/.xinitrc..."
+  echo "Starting Xorg, specs in /etc/X11/xorg.conf, startup apps /root/.xinitrc..."
   #v2.11 G2 suggested -br for black background instead of checked...
   #w479 ***AWFUL HACK*** running pup 218, retro k2.6.18.8, my laptop, Xorg hangs
   #     if have '-nolisten tcp'. until find out why, this workaround...
@@ -594,13 +595,13 @@ case $HAVEX in
   ;;
 esac
 RETval2=$?
-echo 'RETval1='"$RETval1"'_EOV'
+echo "RETval1='$RETval1'"
 echo 'RETval2='"$RETval2"'_EOV'
 
 echo -n "false" > /etc/.XLOADED #see note above.
 #...if PC hung, run xorgwizard at next bootup (see further up).
 
-echo '$@='"$@"'_EOA'
+echo "\$@='$@'"
 if [ -n "`echo "$@" | grep -E -e '\-v|\-*verbose'`" ] ; then
  echo -e "\e[1;33m"Dumping first and last 10 lines of /tmp/xerrs.$HAVEX.log:"\e[0;39m"
  head -n 10 /tmp/xerrs.$HAVEX.log
@@ -661,7 +662,8 @@ card_error_func(){
 
 #Shutdown menu calls wmreboot, wmpoweroff, wmexit or restartwm, which create this file...
 if [ -f /tmp/wmexitmode.txt ];then
- WMEXITMODE="`cat /tmp/wmexitmode.txt`"
+ #WMEXITMODE="`cat /tmp/wmexitmode.txt`"
+ read WMEXITMODE </tmp/wmexitmode.txt
  if [ "$WMEXITMODE" = "exit" ];then #see /usr/bin/wmexit.
   #[ $NUMXWINS -eq 1 ] && rm -f /tmp/wmexitmode.txt #w477 hack, see above.
   rm -f /tmp/wmexitmode.txt #w478
@@ -704,7 +706,7 @@ if [ -f /tmp/wmexitmode.txt ];then
 
  #v1.0.5 thanks GuestToo for advice on this, works with chooselocale script...
   #NEWLANG="`cat /etc/profile | grep "LANG=" | cut -f 2 -d '='`"
-  NEWLANG="`cat /etc/profile | grep '^[[:blank:]]*LANG=' | tail -n 1| cut -f 2 -d '='`" #w482 shinobar bugfix.
+  NEWLANG=`cat /etc/profile | grep '^[[:blank:]]*LANG=' | tail -n 1| cut -f 2 -d '='` #w482 shinobar bugfix.
   if [ "$NEWLANG" ];then #precaution
    if [ ! "$NEWLANG" = "$LANG" ];then
     export LANG=$NEWLANG
