/usr/bin/xwin: Clean ups.

diff --git a/woof-code/rootfs-skeleton/usr/bin/xwin b/woof-code/rootfs-skeleton/usr/bin/xwin
--- a/woof-code/rootfs-skeleton/usr/bin/xwin
+++ b/woof-code/rootfs-skeleton/usr/bin/xwin
@@ -1,9 +1,4 @@
 #!/bin/bash --login
-
-echo "Executing '$0' ..."
-#ps |grep -v '\[' | tr '\n' '·'
-#uptime
-
 #(c) Copyright Barry Kauler 2003,2004,2005,2006,2007 www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #v3.90 rawpup, update for Xvesa.
@@ -20,6 +15,10 @@ echo "Executing '$0' ..."
 #w479 older Xvesa server may not recognise '-sp' option.
 #w479 k2.6.18.8 need awful hack, Xorg, '-nolisten tcp' causes hang!
 #v424 bad hack to fix serial mouse.
+
+echo "Executing '$0' with options '$*' ..."
+#ps |grep -v '\[' | tr '\n' '·'
+#uptime
 
 Version='1.1-getopts Puppy-Linux-4.3.1 KRG'
 
@@ -50,9 +49,15 @@ NEW :
 BUGS: Likely .
 Note: The getopts bash builtin needs to have -options before
 simple nodash options like 'jwm' . Furter It does not recognize
---long-options . 'xwin jwm -S Xorg' should not work to respect the
--S option. 'xwin -S Xorg jwm' should work ok. Also note, that
-getopts works with -SXorg or -wjwm same as -S Xorg and -w jwm .
+--long-options .
+'xwin jwm -S Xorg'
+should not work to respect the -S option.
+'xwin -S Xorg jwm'
+should work ok.
+Also note, that getopts works with
+-SXorg or -wjwm
+same as
+-S Xorg and -w jwm .
 "
 exit $1
 }
@@ -61,10 +66,10 @@ out=/dev/null; err=/dev/null; Q=-q
 while getopts hHdD:ovVw:W:s:S: opt;do
 case $opt in
 h|H) usage 0;;
-d) set -x;;
+d)    set -x;;
 D) Xorg_driver="$OPTARG"
- Xorg_driver="${Xorg_driver//_drv/}"
- Xorg_driver="${Xorg_driver//.so/}"
+   Xorg_driver="${Xorg_driver//_drv/}"
+   Xorg_driver="${Xorg_driver//.so/}"
  if [ "$Xorg_driver" ];then
   echo "Changing the '#card0driver' entry to '$Xorg_driver'"
   sed -i "/#card0driver/ s/\".*\"/\"$Xorg_driver\"/" /etc/X11/xorg.conf
@@ -121,7 +126,7 @@ set -- `echo ${PARAMS[@]}`
 
 ERR=$err;OUT=$out  ##+++2013-04-11
 
-deprecatedNUMXWINS(){
+__deprecatedNUMXWINS__(){
 #NUMXWINS=`pidof xwin | wc -w` #w478
 #[ $NUMXWINS -gt 1 ] && exit   #w478
 ##echo '$DISPLAY : '"$DISPLAY" > /dev/tty3 #DBG
@@ -217,6 +222,14 @@ XORG_CONF='/etc/X11/xorg.conf'
 echo "HOME    : '$HOME'" #> /dev/tty3 #DBG
 echo "pwd     : '`pwd`'" #> /dev/tty3 #DBG
 echo "USER    : '$USER'"
+###+++2012-02-10 #both login -f root and autologinroot dont work , would stop/leave script
+if [ "$HOME" = '/' ];then
+#autologinroot  ##no job control in this shell
+export HOME=/root
+fi
+###+++2012-02-10
+
+#echo `pwd` > /dev/tty3 #DBG
 XINIT_RC="$HOME/.xinitrc"
 test "$HOME" = '/' && XINIT_RC=/root/.xinitrc
 test -f "$XINIT_RC" || XINIT_RC=''
@@ -232,25 +245,19 @@ cp -u $XORG_CONF /etc/X11/xorg.conf.$USER #had /usr/X11 major BUG 2012-01-31
 XORG_CONF="xorg.conf.$USER"
 fi #KRG
 
-###+++2012-02-10 #both login /f root and autologinroot dont work , would stop/leave script
-if [ "$HOME" = '/' ];then
-#autologinroot  ##no job control in this shell
-export HOME=/root
-fi
-###+++2012-02-10
-
-#echo `pwd` > /dev/tty3 #DBG
 #variables created at bootup by init script in initrd...
 . /etc/rc.d/PUPSTATE #v2.02
 #PUPMODE=current operating configuration,
-#PDEV1=the partition have booted off, DEV1FS=f.s. of PDEV1,
-#PUPSFS=pup_201.sfs versioned name, stored on PDEV1, PUPSAVE=vfat,sda1,/pup_save.3fs
+#PDEV1=the partition have booted off,
+#DEV1FS=file-system of PDEV1,
+#PUPSFS=pup_201.sfs versioned name, stored on PDEV1,
+#PUPSAVE=vfat,sda1,/pup_save.3fs
 #PMEDIA is a broad description of the boot media, ex "usbflash" or "idehd".
 
 KERNEL_RELEASE=`uname -r` #w479
 
 #0.9.9 enables to start a specific w.m. from commandline...
-old_parameter_part(){
+__old_parameter_part__(){
 #if [ "$@" ] && [ "`echo "$@" | tr ' ' '\n' | grep -v '^\-'`" = "" ];then
 params0="$@"
 params=`echo "$params0" | sed 's#-S[[:blank:]]*\(.*\)#-S=\1#g'`
@@ -345,8 +352,8 @@ if [ "$haveXVESA" ];then
   get_edid_func
 
 #v3.99 begin
-  if [ -f /etc/xorgoverrides ] && grep -q -f /etc/xorgoverrides /tmp/ddcprobe.txt;then
-   rm -f /var/lock/XLOADED 2> /dev/null #not necessary, precaution.
+  if [ -f /etc/xorgoverrides ] && grep $Q -f /etc/xorgoverrides /tmp/ddcprobe.txt;then
+   rm -f /var/lock/XLOADED 2>$ERR #not necessary, precaution.
    #1st dialog offers to use Xvesa...
    /usr/sbin/xorgwizard; [ $? = 250 ] && exit
    haveX=`readlink /usr/bin/X`
@@ -393,16 +400,16 @@ if [ "$haveXVESA" ] ; then
   MONCHOICES=`grep -F 'timing:' /tmp/ddcprobe.txt | grep -E -v 'Apple|8514A|Mac II|\(XGA2\)' | grep -E ' 800x480@| 1024x600@| 1280x768@| 1280x800@| 1280x1024@| 1360x768@| 1400x1050@| 1440x900@| 1600x1200@| 1680x1050@| 1920x1080@| 1920x1200@' | cut -f 2 -d ' ' | sort -u`
 
   if [ "$MONCHOICES" != "" ];then  #1
-   MONCUTXY=`echo "$MONCHOICES" | cut -f 1 -d '@' | tr '\n' ' '`
+   MONCUTXY=`echo "$MONCHOICES" | cut -f 1 -d '@'`
 
    #v2.21 code to handle widescreen with intel video chips...
    if [ ! -f /etc/resolutionfix ];then ##2
-    if grep -F 'oem:' /tmp/ddcprobe.txt | grep -F -q 'Intel' ;then  #3
+    if grep -F 'oem:' /tmp/ddcprobe.txt | grep -F $Q 'Intel' ;then  #3
      MISSINGXY=""
-     for ONECUTXY in $MONCUTXY #ex: each field 1024x768
+     for oneCUTXY in $MONCUTXY #ex: each field 1024x768
      do
-      OPATTERN=" ${ONECUTXY}x"
-      [ "`echo "$VESAMODES" | grep "$ONECUTXY"`" = "" ] && MISSINGXY="$ONECUTXY"
+      OPATTERN=" ${oneCUTXY}x"
+      [ "`echo "$VESAMODES" | grep "$oneCUTXY"`" = "" ] && MISSINGXY="$oneCUTXY"
      done
      if [ "$MISSINGXY" != "" ];then  #4
       MYXRES=`echo -n "$MISSINGXY" | cut -f 1 -d 'x'`
@@ -429,7 +436,7 @@ if [ "$haveXVESA" ] ; then
 
    if [ "$BASEMODE" != "" ];then
     echo "$BASEMODE" > /etc/videomode #no need for wizard after startup!
-    rm -f /tmp/videomode 2>/dev/null #w460 make sure can exit from X.
+    rm -f /tmp/videomode 2>$ERR #w460 make sure can exit from X.
    fi
   fi  ##1
   ###end of MONCHOICES !not empty part
@@ -485,9 +492,9 @@ if [ ! "$OLDMOUSEDEV" = "$MOUSEDEV" ];then
 fi
 
 #v408 k2.6.25.16 has serial driver as a module...
-[ "`grep 'ttyS' /etc/mousedevice`" != "" ] && modprobe sermouse
+[ "`grep 'ttyS' /etc/mousedevice`" != "" ] && modprobe $VERB sermouse
 #v411 precaution...
-[ "`grep 'input/mice' /etc/mousedevice`" != "" ] && modprobe usbhid
+[ "`grep 'input/mice' /etc/mousedevice`" != "" ] && modprobe $VERB usbhid
 
 #ask about scrollwheel... DO NOT ASK, ASSUME YES...
 if [ ! -f /etc/mousebuttons ];then
@@ -533,7 +540,7 @@ echo `date` "3: finished checking for mouse"
 if [ -f /usr/bin/Xorg ];then
  if [ -f /etc/X11/xorg.conf ];then
   #find location of video chip drivers...
-  SPECVESA=`find -L /usr/lib -noleaf -mount -type f -name vesa_drv.so`
+  SPECVESA=`find -L /usr/lib -xdev -type f -name vesa_drv.so`
   if [ "$SPECVESA" ];then
    DRVRSPATH=`dirname $SPECVESA`
    #get current driver...
@@ -541,7 +548,7 @@ if [ -f /usr/bin/Xorg ];then
    if [ "$DRVRCURR" ];then
     #if [ ! -f $DRVRSPATH/${DRVRCURR}_drv.so ];then
     #one driver is mtx_drv.o hmmm, okay do it this way (pakt)...
-    ls -1 $DRVRSPATH/* | grep $DRVRCURR >/dev/null
+    ls -1 $DRVRSPATH/* | grep $DRVRCURR >$OUT
     if [ $? -ne 0 ];then
      APATTERN="s/.*#card0driver/    Driver      \"vesa\" #card0driver/g"
      cat /etc/X11/xorg.conf | sed -e "$APATTERN" > /tmp/xorg.conf.tmp2
@@ -594,7 +601,7 @@ PROFILEMONITOR=`echo "$DDCPROBE" | grep '^monitorid: ' | head -n 1 | cut -f 2 -d
   fi
  fi
  if [ ! -f /etc/X11/xorg.conf ];then
-  rm -f /var/lock/XLOADED 2> /dev/null #not necessary, precaution.
+  rm -f /var/lock/XLOADED 2>$ERR #not necessary, precaution.
   #1st dialog offers to use Xvesa...
   /usr/sbin/xorgwizard; [ $? = 250 ] && exit
 
@@ -827,31 +834,31 @@ case $haveX in
 
      case $VENDOR_ in
          8086) # Intel
-         grep -q '^i915 ' /proc/modules && {
+         grep $Q '^i915 ' /proc/modules && {
          grep '^i915 ' /proc/modules | while read drivr vmsize users rest; do
          [ "$drivr" ] || break
          case $users in
          0)
-         modprobe -vr i915
+         modprobe $VERB -r i915
          sleep 1
-         modprobe -v i915 modeset=1
+         modprobe $VERB i915 modeset=1
          ;;
          *) [ "$VERBOSE" ] && echo "users of i915 not 0";;
          esac
          done
-         modprobe -v intel-agp
-         } || { modprobe -v i915 modeset=1; modprobe -v intel-agp; }
+         modprobe $VERB intel-agp
+         } || { modprobe $VERB i915 modeset=1; modprobe $VERB intel-agp; }
         ;;
 
          1002) # ATI / AMD
-         grep -q '^glrfx ' /proc/modules && {
+         grep $Q '^glrfx ' /proc/modules && {
          grep '^glrfx ' /proc/modules | while read drivr vmsize users rest; do
          [ "$drivr" ] || break
          case $users in
          0)
-         modprobe -vr glrfx
+         modprobe $VERB -r glrfx
          sleep 1
-         modprobe -v glrfx modeset=1
+         modprobe $VERB glrfx modeset=1
 
          ;;
          esac
@@ -860,28 +867,28 @@ case $haveX in
         ;;
 
          10de) # nVidia
-         grep -q '^nouveau ' /proc/modules && {
+         grep $Q '^nouveau ' /proc/modules && {
          grep '^nouveau ' /proc/modules | while read drivr vmsize users rest; do
          [ "$drivr" ] || break
          case $users in
          0)
-         modprobe -vr nouveau
+         modprobe $VERB -r nouveau
          sleep 1
-         modprobe -v nouveau modeset=1
+         modprobe $VERB nouveau modeset=1
 
          ;;
          esac
          done
          }
 
-         grep -q '^nvidea ' /proc/modules && {
+         grep $Q '^nvidia ' /proc/modules && {
          grep '^nvidia ' /proc/modules | while read drivr vmsize users rest; do
          [ "$drivr" ] || break
          case $users in
          0)
-         modprobe -vr nvidea
+         modprobe $VERB -r nvidia
          sleep 1
-         modprobe -v nvidea modeset=1
+         modprobe $VERB nvidia modeset=1
 
          ;;
          esac
@@ -893,7 +900,7 @@ case $haveX in
       esac
      done
 
-   modprobe -v -b fbcon
+   modprobe $VERB -b fbcon
    ;;
   esac
 
