/etc/rc.d/f4puppy5 : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -1,9 +1,9 @@
 #!/bin/ash
 
-test "$_VERSION_" || _VERSION_=0.0.1b
-test "$VERSION"   ||   VERSION=0.0.1b
-test "$Version"   ||   Version=0.0.1b
-test "$version"   ||   version=0.0.1b
+test "$_VERSION_" || _VERSION_=0.0.1c
+test "$VERSION"   ||   VERSION=0.0.1c
+test "$Version"   ||   Version=0.0.1c
+test "$version"   ||   version=0.0.1c
 SCRIPT_NAME=f4puppy5 # short for functions for puppy 5
 test "$MY_SELF" || MY_SELF="$0"
 
@@ -1932,3 +1932,96 @@ EoI
 fi
 
 }
+
+_add_header()
+{
+local _AUTHOR_ _MONTH_ _YEAR_ file PERM
+_AUTHOR_="Karl Reimer Godt"
+_MONTH_="September"
+_YEAR_="2014"
+
+pwd
+
+cd `pwd`/woof-code/rootfs-skeleton/ || { echo "Could not change into `pwd`/woof-code/rootfs-skeleton/"; exit 1; }
+
+for file in bin/* sbin/* usr/bin/* usr/sbin/* usr/local/*/*
+do
+   [ -L "$file" ] && continue
+   [ -f "$file" ] || continue
+   file "$file" | grep -i text | grep -viE 'perl|python' || continue
+
+   grep 'f4puppy5' "$file" && continue
+
+   PERM=`stat -c %a "$file"`
+   [ "${PERM//[0-6]/}" ] || continue
+   echo "$file"
+
+   cat >/tmp/${file##*/} <<EoI
+#!/bin/sh
+#
+# New header by $_AUTHOR_, $_MONTH_ $_YEAR_
+  _TITLE_="Puppy_${file##*/}"
+_VERSION_=1.0omega
+_COMMENT_="\$_TITLE_:Puppy Linux shell script [to TODO here]"
+
+MY_SELF="/$file"
+MY_PID=\$\$
+
+test -f /etc/rc.d/f4puppy5 && {
+source /etc/rc.d/f4puppy5
+
+ADD_PARAMETER_LIST=""
+ADD_PARAMETERS=""
+_provide_basic_parameters
+
+ADD_HELP_MSG="\$_COMMENT_"
+_parse_basic_parameters "\$@"
+[ "\$DO_SHIFT" ] && [ ! "\${DO_SHIFT//[[:digit:]]/}" ] && {
+  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
+
+_trap
+
+}
+# End new header
+#
+EoI
+   cat "$file" | sed '1d' >>/tmp/${file##*/}
+   rm "$file"
+   mv /tmp/${file##*/} "$file"
+   chmod $PERM "$file"
+
+done
+}
+
+_remove_header()
+{
+ local _AUTHOR_ _MONTH_ _YEAR_ file PERM
+_AUTHOR_="Karl Reimer Godt"
+_MONTH_="September"
+_YEAR_="2014"
+
+ pwd
+
+cd `pwd`/woof-code/rootfs-skeleton/ || { echo "Could not change into `pwd`/woof-code/rootfs-skeleton/"; exit 1; }
+
+for file in bin/* sbin/* usr/bin/* usr/sbin/* usr/local/*/*
+do
+   [ -L "$file" ] && continue
+   [ -f "$file" ] || continue
+   file "$file" | grep -i text | grep -viE 'perl|python' || continue
+
+   grep "# New header by $_AUTHOR_, $_MONTH_ $_YEAR_" "$file" || continue
+
+   PERM=`stat -c %a "$file"`
+   [ "${PERM//[0-6]/}" ] || continue
+   echo "$file"
+
+   sed '/# New header by Karl Reimer Godt, September 2014/,/# End new header/ d' "$file" >/tmp/${file##*/}
+   sed -i '2,3 d' /tmp/${file##*/}
+
+   mv /tmp/${file##*/} "$file"
+   chmod $PERM "$file"
+done
+}
+
+
