/etc/rc.d/f4puppy5: Use QUIET=--quiet; busybox grep does not like --quiet . Add _get_srceen* functions to receive screen dimensions using xwininfo, xrandr, xdpyinfo . Add two (u)mount functions from acpi powerbutton script. Add _*dt() functions _emergdt() .. _debugxdt() . Few minor clean-ups.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -298,12 +298,12 @@ PARAMETERS="
 $ADD_PARAMETERS"
 }
 
-                  OUT=/dev/null;  ERR=$OUT;       Q=-q;QUIET=$Q;DBG='';L_DBG='';     A_DBG=''
-[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr;Q='';QUIET=$Q;DBG=-d;L_DBG=--debug;A_DBG=-debug; }
+                  OUT=/dev/null;  ERR=$OUT;       Q=-q;QUIET=--quiet;DBG='';L_DBG='';     A_DBG=''
+[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr;Q='';QUIET=$Q;     DBG=-d;L_DBG=--debug;A_DBG=-debug; }
 [ "$DEBUG" = "2" ] && set -x
 _parse_basic_parameters()
 {
-OUT=/dev/null;ERR=$OUT;Q=-q;QUIET=$Q;DBG='';L_DBG='';A_DBG='';DO_SHIFT=0
+OUT=/dev/null;ERR=$OUT;Q=-q;QUIET=--quiet;DBG='';L_DBG='';A_DBG='';DO_SHIFT=0
 case $1 in
 -h|-H|*help) _usage 0 "$ADD_HELP_MSG";;
 -V|*version) _version;;
@@ -764,11 +764,11 @@ shift
 #echo "$*" | grep -q -E "$gPATTERN" && return 0 || return $EWRONGCONTENT
 #echo "`eval echo \\$$*`"
 
-#QUIET=-q
+#Q=-q
 if test "$gOPT" = '-v'; then
-echo "`eval echo \\$$*`" | grep $QUIET $gOPT -E "$gPATTERN" && { _warn "$*:Other than '$gPATTERN' content."; return $EWRONGCONTENT; } || return 0
+echo "`eval echo \\$$*`" | grep $Q $gOPT -E "$gPATTERN" && { _warn "$*:Other than '$gPATTERN' content."; return $EWRONGCONTENT; } || return 0
 else
-echo "`eval echo \\$$*`" | grep $QUIET $gOPT -E "$gPATTERN" && return 0 || { _warn "$*:No '$gPATTERN' content."; return $EWRONGCONTENT; }
+echo "`eval echo \\$$*`" | grep $Q $gOPT -E "$gPATTERN" && return 0 || { _warn "$*:No '$gPATTERN' content."; return $EWRONGCONTENT; }
 fi
 }
 
@@ -857,65 +857,208 @@ fi
 }
 
 _get_screen_resolution(){
-xwininfo -root | tac | grep -vE '^[#!;]|^[[:blank:]]*[#!;]|^[/\*][/\*]|^[[:blank:]]*[/\*][/\*]' | grep -m1 '\-geometry' | awk '{print $2}'
-return $?
+ local RV
+_ROOT_SCREEN_DIM_=`xwininfo -root | tac | grep -vE '^[#!;]|^[[:blank:]]*[#!;]|^[/\*][/\*]|^[[:blank:]]*[/\*][/\*]' | grep -m1 '\-geometry' | awk '{print $2}'`
+ RV=$?
+echo ${_ROOT_SCREEN_DIM_}
+ return $RV
 }
+
+_get_screen_resolution2(){
+ local RV
+_ROOT_SCREEN_XY_=`xrandr | grep -o -m 1 'current [0-9]* x [0-9]*,' | grep -oe '[0-9]*'`
+ RV=$?
+echo ${_ROOT_SCREEN_XY_}
+ return $RV
+}
+
+_get_screen_resolution3(){
+ local RV
+_ROOT_SCREEN_XY_=`xrandr | grep -o -m 1 'current [0-9]* x [0-9]*,' | sed 's%[^0-9x]%%g'`
+ RV=$?
+echo ${_ROOT_SCREEN_XY_}
+ return $RV
+}
+
+_get_screen_resolution4(){
+ local RV
+_ROOT_SCREEN_XY_=`xrandr | sed -n '/current/ s%.*current \(.*\), maximum.*%\1%p'`
+ RV=$?
+echo ${_ROOT_SCREEN_XY_}
+ return $RV
+}
+
+_get_screen_resolution7(){
+ local RV
+#_ROOT_SCREEN_XY_=`xdpyinfo | grep -A1 -m 1 '^screen #0:' | tail -n1 | awk '{print $2}'`
+ _ROOT_SCREEN_XY_=`xdpyinfo | grep -m 1 'dimensions:' | awk '{print $2}'`
+ RV=$?
+echo ${_ROOT_SCREEN_XY_}
+ return $RV
+}
+
+_get_screen_resolution8(){
+ local RV
+_ROOT_SCREEN_XY_=`xdpyinfo | awk '/dimensions:/ {print $2}'`
+ RV=$?
+echo ${_ROOT_SCREEN_XY_}
+ return $RV
+}
+
+_get_screen_resolution9(){
+ local RV
+_ROOT_SCREEN_XY_=`xdpyinfo | sed -n '/dimensions:/ s%.*dimensions:[[:blank:]]*\([0-9x]*\) pixels.*%\1%p'`
+ RV=$?
+echo ${_ROOT_SCREEN_XY_}
+ return $RV
+}
+
+_get_screen_x(){
+ local RV
+_ROOT_SCREEN_X_=`xwininfo -root | tac | grep -vE '^[#!;]|^[[:blank:]]*[#!;]|^[/\*][/\*]|^[[:blank:]]*[/\*][/\*]' | grep -m1 '\-geometry' | awk '{print $2}' | awk -F'x' '{print $1}'`
+ RV=$?
+echo ${_ROOT_SCREEN_X_}
+ return $RV
+}
+
+_get_screen_x2(){
+ local RV
+_ROOT_SCREEN_X_=`xrandr | grep -o -m 1 'current [0-9]* x [0-9]*,' | cut -f2 -d' '`
+ RV=$?
+echo ${_ROOT_SCREEN_X_}
+ return $RV
+}
+
+_get_screen_x8(){
+ local RV
+_ROOT_SCREEN_X_=`xdpyinfo | awk -F'[ x]' '/dimensions:/ {print $7}'`
+ RV=$?
+echo ${_ROOT_SCREEN_X_}
+ return $RV
+}
+
+_get_screen_x8(){
+ local RV
+_ROOT_SCREEN_X_=`xdpyinfo | awk -F'[ x]' '/dimensions:/ {print $7}'`
+ RV=$?
+echo ${_ROOT_SCREEN_X_}
+ return $RV
+}
+
+_get_screen_x81(){
+ local RV
+_ROOT_SCREEN_Y_=`xdpyinfo | awk '/dimensions:/ {print $2}' | cut -f1 -dx`
+ RV=$?
+echo ${_ROOT_SCREEN_Y_}
+ return $RV
+}
+
+_get_screen_y(){
+ local RV
+_ROOT_SCREEN_Y_=`xwininfo -root | tac | grep -vE '^[#!;]|^[[:blank:]]*[#!;]|^[/\*][/\*]|^[[:blank:]]*[/\*][/\*]' | grep -m1 '\-geometry' | awk '{print $2}' | awk -F'[x+]' '{print $2}'`
+ RV=$?
+echo ${_ROOT_SCREEN_Y_}
+ return $RV
+}
+
+_get_screen_y2(){
+ local RV
+_ROOT_SCREEN_Y_=`xrandr | grep -o -m 1 'current [0-9]* x [0-9]*,' | awk -F' ' '{print $NF}'`
+ RV=$?
+echo ${_ROOT_SCREEN_Y_/,/}
+ return $RV
+}
+
+_get_screen_y3(){
+ local RV
+_ROOT_SCREEN_Y_=`xrandr | grep -o -m 1 'current [0-9]* x [0-9]*,' | sed -r 's%(.*) x ([0-9]*),%\2%'`
+ RV=$?
+echo ${_ROOT_SCREEN_Y_}
+ return $RV
+}
+
+_get_screen_y8(){
+ local RV
+_ROOT_SCREEN_Y_=`xdpyinfo | awk -F'[ x]' '/dimensions:/ {print $8}'`
+ RV=$?
+echo ${_ROOT_SCREEN_Y_}
+ return $RV
+}
+
+_get_screen_y81(){
+ local RV
+_ROOT_SCREEN_Y_=`xdpyinfo | awk '/dimensions:/ {print $2}' | cut -f2 -dx`
+ RV=$?
+echo ${_ROOT_SCREEN_Y_}
+ return $RV
+}
+
 #=
 
 #=============== LOGLEVEL / DEBUG MESSAGES ==================================
-EMERGENCY=1
+[ "$ERMERGENCY" ] || EMERGENCY=1
 _emerg(){
 test "$EMERGENCY" || return 1
-echo -e "EMERGENGY:$*"
+echo -e "$0:EMERGENGY:$*"
 }
 
-ALERT=1
+[ "$ALERT" ] || ALERT=1
 _alert(){
 test "$ALERT" || return 1
 echo -e "$0:ALERT:$*"
 }
 
-CRIT=1
+[ "$CRIT" ] || CRIT=1
 _crit(){
 test "$CRIT" || return 1
 echo -e "$0:CRITICAL:$*"
 }
 
-ERROR=1
+[ "$ERROR" ] || ERROR=1
 _err(){
 test "$ERROR" || return 1
 echo -e "$0:ERROR:$*"
 }
 
-WARN=1
+[ "$WARN" ] || WARN=1
 _warn(){
 test "$WARN" || return 1
 echo -e "$0:WARNING:$*"
 }
 
-NOTICE=1
+[ "$NOTICE" ] || NOTICE=1
 _notice(){
 test "$NOTICE" || return 1
 echo -e "$0:NOTICE:$*"
 }
 
-INFO=1
+[ "$INFO" ] || INFO=1
 _info(){
 test "$INFO" || return 1
 echo -e "$0:INFO:$*"
 }
 
-DEBUG=
+[ "$DEBUG" ] || DEBUG=
 _debug(){
 test "$DEBUG" || return 1
 echo -e "$0:DEBUG:$*"
 }
 
-DEBUGX=
+[ "$DEBUGX" ] || DEBUGX=
 _debugx(){
 test "$DEBUGX" || return 1
 echo -e "$0:DEBUGX:$@"
 }
+
+ _emergdt(){ test "$EMERGENCY" || return 1; echo -e "`date +%F-%T`:$0:EMERGENGY:$*"; }
+ _alertdt(){ test "$ALERT"     || return 1; echo -e "`date +%F-%T`:$0:ALERT:$*";     }
+  _critdt(){ test "$CRIT"      || return 1; echo -e "`date +%F-%T`:$0:CRITICAL:$*";  }
+   _errdt(){ test "$ERROR"     || return 1; echo -e "`date +%F-%T`:$0:ERROR:$*";     }
+  _warndt(){ test "$WARN"      || return 1; echo -e "`date +%F-%T`:$0:WARNING:$*";   }
+_noticedt(){ test "$NOTICE"    || return 1; echo -e "`date +%F-%T`:$0:NOTICE:$*";    }
+  _infodt(){ test "$INFO"      || return 1; echo -e "`date +%F-%T`:$0:INFO:$*";      }
+ _debugdt(){ test "$DEBUG"     || return 1; echo -e "`date +%F-%T`:$0:DEBUG:$*";     }
+
 
 DEBUGT=
 _debugt(){  #$1 label #$2 time
@@ -1754,8 +1897,8 @@ unset SFSSTR SFS_STR SFS_MAJOR SFSMAJOR squashXZ
 
 if test ! "$*"; then
 SFS_STR=`dmesg | grep -i squash | grep -o -i 'version.*' | cut -f1,2 -d' '`
-test "$SFS_STR" || { ( busybox modprobe -l | grep $QUIET '/squashfs.ko' ) && {
-grep $QUIET 'squashfs' /proc/modules || { modprobe $VERB squashfs; sleep 1; } ; }
+test "$SFS_STR" || { ( busybox modprobe -l | grep $Q '/squashfs.ko' ) && {
+grep $Q 'squashfs' /proc/modules || { modprobe $VERB squashfs; sleep 1; } ; }
 SFS_STR=`dmesg | grep -i squash | grep -o -i 'version.*' | cut -f1,2 -d' '`
 }
 test "$SFS_STR" || { _warn "Could not determine squashfs in dmesg, assuming \"version 4.0\""; SFS_STR='version 4.0'; }
@@ -2542,6 +2685,199 @@ do
    chmod $PERM "$file"
    fi
 
+done
+}
+
+_part_umount_func(){
+
+rootSCREEN_XY=`_get_screen_resolution`     || rootSCREEN_XY=800x600+0+0
+ rootCENTER_X=$((${rootSCREEN_XY%%x*}/2))
+ rootCENTER_Y=`expr $(echo "$rootSCREEN_XY" | awk -F'[x+]' '{print $2}') / 2`
+
+                    local M_POI M_OPS mpart_ yPID
+
+ MOUNTED=`tac /proc/mounts |grep -E "^/dev/[fhms][dmr][[:alnum:]][^ ]*[0-9]? "`
+
+ M_POI=`echo "$MOUNTED" | awk '{print $2}'`
+ M_POI=`echo -e "$M_POI"`
+
+ M_OPS=`echo "$MOUNTED" | awk '{print $4}'`
+ M_OPS=`echo -e "$M_OPS"`
+
+ M_DEV=`echo "$MOUNTED" | awk '{print $1}'`
+ M_DEV=`echo -e "$M_DEV"`
+
+for mpart_ in $M_POI;
+do
+
+    ## BIG PROBLEM un-mounting slow devices like CD drives and Floppy drives!
+    ## Puppy's /bin/umount may run probedisk2
+    ## with guess_fstype and disktype to determine the file-system type
+    ## and both spin-up the CD drive, disktype really heavily.
+    ## My old worn out CD drive takes up to two minutes before stopping spinning.
+    ## Un-mounting works, but re-mounting after waking up leads to kernel driver errors.
+    ## 5 Solutions, I could think of:
+    ## S1 : Demanding the USER to un-mount manually and try again and exit.
+    ## S2 : Unmount the drives with a reasonable sleep of 30 seconds, and omitting them to re-mount after wake-up.
+    ## S3 : Omitting un- and remounting the drives completely
+    ## S4 : BIG sleep of 150 seconds after un-mounting and re-mounting.
+    ## S5 : Use hdparm and sdparm
+
+    ## Solution Nr. 1 Exit :
+    #case $mpart_ in
+    #*/sr[0-9]*|*/fd[0-9]*|*/scd[0-9]*|*/hd[a-d])
+    # xmessage -bg orange "Slow drive '$mpart_' is mounted ..!
+    # Please un-mount it manually,
+    # and try to put the machine to sleep again !!"
+    # exit 1
+    #;;
+    #esac
+
+    ## Solution Nr. 3 Omit :
+    #case $mpart_ in
+    #*/sr[0-9]*|*/fd[0-9]*|*/scd[0-9]*|*/hd[a-d]) sleep 1; continue;;
+    #esac
+
+    yaf-splash -bg pink -geometry +${rootCENTER_X}+${rootCENTER_Y} -text "Unmounting $mpart_ ..." & yPID=$!
+
+    ##Solution Nr. 2 and 4 Reasonable or BIG sleep :
+    case $mpart_ in
+    */sr[0-9]*|*/fd[0-9]*|*/scd[0-9]*|*/hd[a-d]) sleep 15;;
+    esac
+
+    /bin/umount $VERB -r "$mpart_"
+[ $? -ne 0 ] && { xmessage -bg red2 "Please umount '$mpart_' manually and try again";exit 0; }
+
+    ## Solution Nr. 2 Reasonable sleep :
+    #case $mpart_ in
+    #*/sr[0-9]*|*/fd[0-9]*|*/scd[0-9]*|*/hd[a-d])
+    # yaf-splash -timeout 15 -bg pink3 -geometry +$((rootCENTER_X-100))+$((rootCENTER_Y-25)) -text "Floppy disk or CD drive, please wait 15 seconds.." &
+    # sleep 15;;
+    #esac
+
+    ## Solution Nr. 4 BIG sleep :
+    #case $mpart_ in
+    #*/sr[0-9]*|*/fd[0-9]*|*/scd[0-9]*|*/hd[a-d])
+    # yaf-splash -timeout 150 -bg pink3 -text "Floppy disk or CD drive, please wait 150 seconds.." &
+    # sleep 150;;
+    #esac
+
+    ## Solution Nr. 5 use hdparm and or sdparm to stop the drive
+    case $mpart_ in
+     */sr[0-9]*|*/scd[0-9]*)
+      hdparm $L_VERB -C /dev/${mpart_##*/} | grep $Q 'active' && {
+           MSG="ERROR: Drive '/dev/${mpart_##*/}' still recognized as active.
+           Exiting $PWD/$0."
+           MSG=`echo "$MSG" | sed 's%^[[:blank:]]*%%'`
+           xmessage -bg red -title "$MY_SELF" "$MSG"
+           exit 5
+      }
+      yaf-splash -timeout 25 -bg pink3 -geometry +$((rootCENTER_X-100))+$((rootCENTER_Y-25)) -text "Floppy disk or CD drive, please wait 25 seconds.." &
+      sleep 8
+      sdparm $VERB -C stop /dev/${mpart_##*/}
+      sleep 17
+     ;;
+
+     */hd[a-d])
+      yaf-splash -timeout 25 -bg pink3 -geometry +$((rootCENTER_X-100))+$((rootCENTER_Y-25)) -text "Floppy disk or CD drive, please wait 25 seconds.." &
+      sleep 8
+      hdparm $L_VERB -Y /dev/${mpart_##*/}
+      sleep 17
+     ;;
+
+     */fd[0-9]*)
+      yaf-splash -timeout 25 -bg pink3 -geometry +$((rootCENTER_X-100))+$((rootCENTER_Y-25)) -text "Floppy disk or CD drive, please wait 25 seconds.." &
+      sleep 25
+     ;;
+    esac
+
+    sleep 1
+    kill $yPID
+done
+}
+
+_restore_mounts(){
+
+rootSCREEN_XY=`_get_screen_resolution`     || rootSCREEN_XY=800x600+0+0
+ rootCENTER_X=$((${rootSCREEN_XY%%x*}/2))
+ rootCENTER_Y=`expr $(echo "$rootSCREEN_XY" | awk -F'[x+]' '{print $2}') / 2`
+
+                    local part_ basn FS_TYPE reMOUNT mntOPS yPID
+
+for part_ in $M_DEV;
+do
+
+    ## BIG PROBLEM re-mounting slow devices like CD drives and Floppy drives!
+    ## Puppy's /bin/mount may run probedisk2
+    ## with guess_fstype and disktype to determine the file-system type
+    ## and both spin-up the CD drive, disktype really heavily.
+    ## My old worn out CD drive takes up to two minutes before stopping spinning.
+    ## Un-mounting works, but re-mounting after waking up leads to kernel driver errors.
+    ## 4 Solutions, I could think of:
+    ## S1 : Demanding the USER to un-mount manually and try again and exit.
+    ## S2 : Unmount the drives with a reasonable sleep of 30 seconds, and omitting them to re-mount after wake-up.
+    ## S3 : Omitting un- and remounting the drives completely
+    ## S4 : BIG sleep of 150 seconds after un-mounting and re-mounting.
+    ## S5 : Use hdparm and sdparm
+
+    ## Solution Nr. 2 and 3 Omit to un- and or re-mount :
+    #case $part_ in
+    #*/sr[0-9]*|*/fd[0-9]*|*/scd[0-9]*|*/hd[a-d]) sleep 1; continue;;
+    #esac
+
+    yaf-splash -bg purple -geometry +${rootCENTER_X}+${rootCENTER_Y} -text "Restoring mount of $part_ ..." & yPID=$!
+
+        grep $Q -w "$part_" /proc/mounts && reMOUNT='remount,'
+        mntOPS=`echo "$MOUNTED" | grep -m1 -w "^$part_" | awk '{print $4}'`
+            [ "$mntOPS" ] || mntOPS=rw
+        FS_TYPE=`guess_fstype $part_`
+
+    ## Solution Nr. 4 BIG sleep :
+    #case $part_ in
+    #*/sr[0-9]*|*/fd[0-9]*|*/scd[0-9]*|*/hd[a-d]) sleep 15;;
+    #esac
+
+    ## Solution Nr. 5 use hdparm and or sdparm to wake-up the drive
+    case $part_ in
+     */sr[0-9]*|*/scd[0-9]*)
+      yaf-splash -timeout 25 -bg pink3 -geometry +$((rootCENTER_X-100))+$((rootCENTER_Y-25)) -text "Floppy disk or CD drive, please wait 25 seconds.." &
+      sleep 8
+      sdparm $VERB -C start $part_
+      sleep 17
+     ;;
+
+     */hd[a-d])
+      yaf-splash -timeout 25 -bg pink3 -geometry +$((rootCENTER_X-100))+$((rootCENTER_Y-25)) -text "Floppy disk or CD drive, please wait 25 seconds.." &
+      sleep 8
+      hdparm $L_VERB --idle-immediate $part_
+      sleep 17
+     ;;
+
+     */fd[0-9]*)
+      yaf-splash -timeout 25 -bg pink3 -geometry +$((rootCENTER_X-100))+$((rootCENTER_Y-25)) -text "Floppy disk or CD drive, please wait 25 seconds.." &
+      sleep 25
+     ;;
+    esac
+
+        basn=${part_##*/}
+        mkdir -p /mnt/$basn
+
+[ "$FS_TYPE" = unknown -o "$FS_TYPE" = "" ] && {
+  /bin/mount $VERB -o ${reMOUNT}$mntOPS             $part_ /mnt/$basn || true
+} || {
+  /bin/mount $VERB -o ${reMOUNT}$mntOPS -t $FS_TYPE $part_ /mnt/$basn || false
+}
+
+    ## Solution Nr. 4 BIG sleep :
+    #case $part_ in
+    #*/sr[0-9]*|*/fd[0-9]*|*/scd[0-9]*|*/hd[a-d])
+    # yaf-splash -timeout 150 -bg purple3 -text "Floppy disk or CD drive, please wait 150 seconds.." &
+    # sleep 150;;
+    #esac
+
+    sleep 1
+    kill $yPID
+    unset reMOUNT mntOPS FS_TYPE
 done
 }
 
