/etc/rc.d/f4puppy5: Maintanance update through replace_commit.sh .

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -3,10 +3,17 @@
 # source only once
 [ "$_HAVE_F4PUYYP5_" ] && return 0
 
-Q=-q;QUIET=--quiet;S=-s;SILENT=--silent
-OUT=/dev/null;ERR=/dev/null
+: Q=-q;QUIET=--quiet;S=-s;SILENT=--silent
+: OUT=/dev/null;ERR=/dev/null
 
-VERSION=0.0.1.1
+test "$Q" || Q=-q
+test "QUIET" || QUIET=--quiet
+test "$S" || S=-s
+test "$SILENT" || SILENT=--silent
+test "$OUT" || OUT=/dev/null
+test "$ERR" || ERR=/dev/null
+
+VERSION=0.0.1.1.1
 SCRIPT_NAME=f4puppy5 # short for functions for puppy 5
 
 # Handle $0 :
@@ -85,6 +92,33 @@ test -L "$*" && return 1
 test -f "$*" -a -r "$*" -a -w "$*"
 }
 
+_test_fx()
+{
+
+test -L "$*" && return 1
+test -f "$*" -a -x "$*"
+}
+
+
+_test_frx()
+{
+
+test -L "$*" && return 1
+test -f "$*" -a -r "$*" -a -x "$*"
+}
+
+_test_fwx()
+{
+test -L "$*" && return 1
+test -f "$*" -a -w "$*" -a -x "$*"
+}
+
+_test_frwx()
+{
+test -L "$*" && return 1
+test -f "$*" -a -r "$*" -a -w "$*" -a -x "$*"
+}
+
 _test_d()
 {
 test -L "$*" && return 1
@@ -104,6 +138,12 @@ test -L "$*" && return 1
 test -d "$*" -a -w "$*"
 }
 
+_test_dx()
+{
+test -L "$*" && return 1
+test -d "$*" -a -x "$*"
+}
+
 _test_drw()
 {
 test -L "$*" && return 1
@@ -114,6 +154,18 @@ _test_drx()
 {
 test -L "$*" && return 1
 test -d "$*" -a -r "$*" -a -x "$*"
+}
+
+_test_dwx()
+{
+test -L "$*" && return 1
+test -d "$*" -a -w "$*" -a -x "$*"
+}
+
+_test_drwx()
+{
+test -L "$*" && return 1
+test -d "$*" -a -r "$*" -a -w "$*" -a -x "$*"
 }
 
 _test_p()
@@ -456,68 +508,68 @@ pidof sync >>$OUT || sync
 }
 
 #=============== LOGLEVEL / DEBUG MESSAGES ==================================
-EMERGENCY=1
+test "$EMERGENCY" || EMERGENCY=1
 _emerg(){
 test "$EMERGENCY" || return 0
-echo "EMERGENGY:$*"
+echo "EMERGENGY:$*" >&2
 }
 
-ALERT=1
+test "$ALERT" || ALERT=1
 _alert(){
 test "$ALERT" || return 0
-echo "$0:ALERT:$*"
+echo "$0:ALERT:$*" >&2
 }
 
-CRIT=1
+test "$CRIT" || CRIT=1
 _crit(){
 test "$CRIT" || return 0
-echo "$0:CRITICAL:$*"
+echo "$0:CRITICAL:$*" >&2
 }
 
-ERROR=1
+test "$ERROR" || ERROR=1
 _err(){
 test "$ERROR" || return 0
-echo "$0:ERROR:$*"
+echo "$0:ERROR:$*" >&2
 }
 
-WARN=1
+test "$WARN" || WARN=1
 _warn(){
 test "$WARN" || return 0
-echo "$0:WARNING:$*"
+echo "$0:WARNING:$*" >&2
 }
 
-NOTICE=1
+test "$NOTICE" || NOTICE=1
 _notice(){
 test "$NOTICE" || return 0
-echo "$0:NOTICE:$*"
+echo "$0:NOTICE:$*" >&2
 }
 
-INFO=1
+test "$INFO" || INFO=1
 _info(){
 test "$INFO" || return 0
-echo "$0:INFO:$*"
+echo "$0:INFO:$*" >&2
 }
 
-VERBOSE=
+test "$VERBOSE" || VERBOSE=
 _verbose()
 {
 test "$VERBOSE" || return 0
-echo "$0:$*"
+echo "$0:$*" >&2
 }
 
-DEBUG=
+test "$DEBUG" || DEBUG=
 _debug(){
 test "$DEBUG" || return 0
-echo "$0:DEBUG:$*"
+echo "$0:DEBUG:$*" >&2
 }
 
-DEBUGX=
+test "$DEBUGX" || DEBUGX=
 _debugx(){
 test "$DEBUGX" || return 0
-echo "$0:DEBUGX:$@"
+echo "$0:DEBUGX:$@" >&2
 }
 
-DEBUGT=
+test "$DEBUGT" || DEBUGT=
 _debugt(){  #$1 label #$2 time
 
 test "$DEBUGT" || return 0
@@ -525,6 +577,7 @@ test "$DEBUGT" || return 0
 local _TIME_ LC_NUMERIC=C LANG= LC_ALL=
 _DATE_=`date +%s.%N | sed 's:.*\(..\..*\):\1:'`
 #_DATE_=`date +%s,%N | sed 's:.*\(..\,.*\):\1:'`
+(
 if test "$2"; then
 _TIME_=`dc $_DATE_ $2 \- p`
 echo "$0:TIME:$1:$_TIME_"
@@ -532,6 +585,7 @@ else
 #echo "$0:TIME:$*:`date +%s.%N | sed 's:.*\(..\..*\):\1:'`"
 echo "$0:TIME:$*:$_DATE_"
 fi
+) >&2
 }
 
 #=================== Prefer Busybox applets ==================================
@@ -1489,7 +1543,8 @@ case $1 in
 pidof $* >>$OUT; return $?
 ;;
 *)
-pidof $*;return $?
+echo -n "PID of $*:"
+pidof $* && return || { RV=$? ; echo; return $RV; }
 ;;
 esac
 }
