/etc/rc.d/f4puppy5 : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -12,13 +12,17 @@ version) _VERSION_=$version; VERSION=$version; Version=$version;;
 esac
 }
 
-test "$_VERSION_" && _assign_version _VERSION_ || _VERSION_=0.0.3a
-test "$VERSION"   && _assign_version VERSION   ||   VERSION=0.0.3a
-test "$Version"   && _assign_version Version   ||   Version=0.0.3a
-test "$version"   && _assign_version version   ||   version=0.0.3a
-SCRIPT_NAME=f4puppy5 # short for functions for puppy 5
-test "$MY_SELF" || MY_SELF="$0"
+test "$_VERSION_" && _assign_version _VERSION_ || _VERSION_=0.0.4
+test "$VERSION"   && _assign_version VERSION   ||   VERSION=0.0.4
+test "$Version"   && _assign_version Version   ||   Version=0.0.4
+test "$version"   && _assign_version version   ||   version=0.0.4
 
+SCRIPT_NAME=f4puppy5 # short for functions for puppy 5
+
+test "$MY_SELF" || MY_SELF="$0"
+case "$MY_SELF" in
+./*) MY_SELF=`pwd`/"$MY_SELF";;
+esac
 case ${MY_SELF##*/} in
 ash|bash|sh) EXIT=return;;
 *)           EXIT=exit;;
@@ -673,6 +677,29 @@ done
 return $?
 }
 
+_lineno(){
+## Usage like :
+#LINEP=D001
+#[ "$VERBOSE" ] && echo "$DBG line `[ $LINENO ] && echo $LINENO || _lineno $LINEP`"
+## Or
+#LINEP=D001;[ "$VERBOSE" ] && echo "$DBG line `[ $LINENO ] && echo $LINENO || _lineno $LINEP`"
+    if [ "$1" ]; then
+    echo `grep -h -n -w -m1 "$1" "$MY_SELF" |cut -f1 -d':'`" (tag '$*')"
+    else
+    echo 'UNKNOWN -- missing $1'
+    fi
+}
+
+_lineno2(){
+## Usage like :
+#[ "$VERBOSE" ] && echo "$DBG line `[ $LINENO ] && echo $LINENO || LINEP=D001 _lineno`"
+    if [ "$LINEP" ]; then
+    echo `grep -h -n -w -m1 "$LINEP" "$MY_SELF" |cut -f1 -d':'`" (tag '$LINEP')"
+    else
+    echo 'UNKNOWN -- missing env LINEP variable'
+    fi
+}
+
 _logger()
 {
 local MESSAGE PRIORITY TAG
@@ -870,32 +897,46 @@ fi
 
 _get_screen_resolution(){
  local RV
-_ROOT_SCREEN_DIM_=`xwininfo -root | tac | grep -vE '^[#!;]|^[[:blank:]]*[#!;]|^[/\*][/\*]|^[[:blank:]]*[/\*][/\*]' | grep -m1 '\-geometry' | awk '{print $2}'`
+ ROOT_SCREEN_DIM_=`xwininfo -root`
  RV=$?
+ ROOT_SCREEN_DIM_=`echo "$ROOT_SCREEN_DIM_" | tac | grep -vE '^[#!;]|^[[:blank:]]*[#!;]|^[/\*][/\*]|^[[:blank:]]*[/\*][/\*]' | grep -m1 '\-geometry'`
+ RV=$((RV+$?))
+_ROOT_SCREEN_DIM_=`echo "$ROOT_SCREEN_DIM_" | awk '{print $2}'`
+ RV=$((RV+$?))
 echo ${_ROOT_SCREEN_DIM_}
  return $RV
 }
 
 _get_screen_resolution2(){
  local RV
-_ROOT_SCREEN_XY_=`xrandr | grep -o -m 1 'current [0-9]* x [0-9]*,' | grep -oe '[0-9]*'`
+ ROOT_SCREEN_XY_=`xrandr`
  RV=$?
+ ROOT_SCREEN_XY_=`echo "$ROOT_SCREEN_XY_" | grep -o -m 1 'current [0-9]* x [0-9]*,'`
+ RV=$((RV+$?))
+_ROOT_SCREEN_XY_=`echo "$ROOT_SCREEN_XY_" | grep -oe '[0-9]*'`
+ RV=$((RV+$?))
 echo ${_ROOT_SCREEN_XY_}
  return $RV
 }
 
 _get_screen_resolution3(){
  local RV
-_ROOT_SCREEN_XY_=`xrandr | grep -o -m 1 'current [0-9]* x [0-9]*,' | sed 's%[^0-9x]%%g'`
+ ROOT_SCREEN_XY_=`xrandr`
  RV=$?
+ ROOT_SCREEN_XY_=`echo "$ROOT_SCREEN_XY_" | grep -o -m 1 'current [0-9]* x [0-9]*,'`
+ RV=$((RV+$?))
+_ROOT_SCREEN_XY_=`echo "$ROOT_SCREEN_XY_" | sed 's%[^0-9x]%%g'`
+ RV=$((RV+$?))
 echo ${_ROOT_SCREEN_XY_}
  return $RV
 }
 
 _get_screen_resolution4(){
  local RV
-_ROOT_SCREEN_XY_=`xrandr | sed -n '/current/ s%.*current \(.*\), maximum.*%\1%p'`
+ ROOT_SCREEN_XY_=`xrandr`
  RV=$?
+_ROOT_SCREEN_XY_=`echo "$ROOT_SCREEN_XY_" | sed -n '/current/ s%.*current \(.*\), maximum.*%\1%p'`
+ RV=$((RV+$?))
 echo ${_ROOT_SCREEN_XY_}
  return $RV
 }
@@ -903,8 +944,12 @@ echo ${_ROOT_SCREEN_XY_}
 _get_screen_resolution7(){
  local RV
 #_ROOT_SCREEN_XY_=`xdpyinfo | grep -A1 -m 1 '^screen #0:' | tail -n1 | awk '{print $2}'`
- _ROOT_SCREEN_XY_=`xdpyinfo | grep -m 1 'dimensions:' | awk '{print $2}'`
+ ROOT_SCREEN_XY_=`xdpyinfo`
  RV=$?
+ ROOT_SCREEN_XY_=`echo "$ROOT_SCREEN_XY_" | grep -m 1 'dimensions:'`
+ RV=$((RV+$?))
+_ROOT_SCREEN_XY_=`echo "$ROOT_SCREEN_XY_" | awk '{print $2}'`
+ RV=$((RV+$?))
 echo ${_ROOT_SCREEN_XY_}
  return $RV
 }
@@ -1365,7 +1410,7 @@ _info "moving $* --> ${*}.1"
 mv $VERB "$*" "${*}.1"
 }
 
-_set_bool_right(){
+__set_bool_right(){
 test "$#" = 3 || { _return 4 "_set_bool_right:Usage:_set_bool_right VARIABLE VAR_VALUE WANTED_VALUE -- got '$*'"; return $?; }
 
 local VARIABLE VAR_VALUE WANTED_VALUE RV
@@ -1386,7 +1431,7 @@ FALSE|False|false|OFF|Off|off|NO|No|no|N|n|0)
    case $WANTED_VALUE in
     TRUE|True|true|ON|On|on|YES|Yes|yes|Y|y|1)
     _err "_set_bool_right: WANTED_VALUE should be one of these:
-TRUE|True|true|ON|On|on|YES|Yes|yes|Y|y|1"
+FALSE|False|false|OFF|Off|off|NO|No|no|N|n|0"
     return 6;;
    esac
 eval "$VARIABLE=\"$WANTED_VALUE\"";;
@@ -1397,53 +1442,42 @@ esac
 return $RV
 }
 
+_set_bool_right(){
+test "$#" = 3 || { _return 4 "_set_bool_right:Usage:_set_bool_right VARIABLE VAR_VALUE WANTED_VALUE -- got '$*'"; return $?; }
 
+local VARIABLE VAR_VALUE WANTED_VALUE RV
+VARIABLE="$1"
+VAR_VALUE="$2"
+WANTED_VALUE="$3"
 
+YES_STRING='TRUE|True|true|ON|On|on|YES|Yes|yes|Y|y|1'
+NOT_STRING='FALSE|False|false|OFF|Off|off|NO|No|no|N|n|0'
+RV=0
+case $VAR_VALUE in
+[$YES_STRING])
+  case $WANTED_VALUE in
+   "$NOT_STRING")
+   _err "_set_bool_right: WANTED_VALUE should be one of these:
+$YES_STRING"
+   return 5;;
+  esac
+eval "$VARIABLE=\"$WANTED_VALUE\""
+;;
 
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
+[$NOT_STRING])
+   case $WANTED_VALUE in
+    "$YES_STRING")
+    _err "_set_bool_right: WANTED_VALUE should be one of these:
+$NOT_STRING"
+    return 6;;
+   esac
+eval "$VARIABLE=\"$WANTED_VALUE\"";;
+*) _err "_set_bool_right:Unhandled '$VAR_VALUE' -- Needs to be one of these:
+$YES_STRING $NOT_STRING"
+RV=7
+esac
+return $RV
+}
 
 #================= KERNEL VERSION and SFS VERSION ============================
 
@@ -1529,38 +1563,6 @@ _notice "_kernel_version:squashXZ='$squashXZ'"
 INFO=$oldINFO
 DEBUG=$oldDEBUG
 }
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
 
 
 
@@ -1669,12 +1671,6 @@ DEBUG=$oldDEBUG
 
 
 
-
-
-
-
-
-
 _kernel_version3()
 {
 oldINFO=$INFO oldDEBUG=$DEBUG
@@ -1772,7 +1768,6 @@ return 0
 INFO=$oldINFO
 DEBUG=$oldDEBUG
 }
-
 
 
 
@@ -1910,53 +1905,6 @@ _notice "_kernel_version4:squashXZ='$squashXZ'"
 INFO=$oldINFO
 DEBUG=$oldDEBUG
 }
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
 
 
 
@@ -2375,8 +2323,8 @@ case $1 in
 pidof ${*##*/} >/dev/null; return $?
 ;;
 *)
-echo -n "pids of $* ( ${*##*/} ) :"
-pidof ${*##*}; RV=$?
+echo -n "Pids of '$*' ( ${*##*/} ) :"
+pidof ${*##*/}; RV=$?
 test "$RV" = 0 || echo
 return $RV
 ;;
@@ -2816,7 +2764,9 @@ _part_umount_func(){
 
 rootSCREEN_XY=`_get_screen_resolution`     || rootSCREEN_XY=800x600+0+0
  rootCENTER_X=$((${rootSCREEN_XY%%x*}/2))
- rootCENTER_Y=`expr $(echo "$rootSCREEN_XY" | awk -F'[x+]' '{print $2}') / 2`
+ #rootCENTER_Y=`expr $(echo "$rootSCREEN_XY" | awk -F'[x+]' '{print $2}') / 2`
+ _Y_=$(echo "$rootSCREEN_XY" | awk -F'[x+]' '{print $2}')
+ rootCENTER_Y=$((_Y_ / 2))
 
                     local M_POI M_OPS mpart_ yPID
 
@@ -2924,7 +2874,9 @@ _restore_mounts(){
 
 rootSCREEN_XY=`_get_screen_resolution`     || rootSCREEN_XY=800x600+0+0
  rootCENTER_X=$((${rootSCREEN_XY%%x*}/2))
- rootCENTER_Y=`expr $(echo "$rootSCREEN_XY" | awk -F'[x+]' '{print $2}') / 2`
+ #rootCENTER_Y=`expr $(echo "$rootSCREEN_XY" | awk -F'[x+]' '{print $2}') / 2`
+ _Y_=$(echo "$rootSCREEN_XY" | awk -F'[x+]' '{print $2}')
+ rootCENTER_Y=$((_Y_ / 2))
 
                     local part_ basn FS_TYPE reMOUNT mntOPS yPID
 
