/etc/rc.d/f4puppy5 : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -35,7 +35,7 @@ MY_SELF0="$0"
 [ "$WARNING" ] || WARNING=1
 _warn(){
 test "$WARN" || return 1
-echo -e "$0:WARNING:$*"
+echo -e "$0:WARNING:$*"  >&2
 }
 
 if test "$MY_SELFR" -a "$MY_SELF0"; then
@@ -283,7 +283,7 @@ local RV
 test "$*" || { _err "Usage:_exit EXITCODE MESSAGE"; }
 RV=$1
 [ "${RV//[[:digit:]]/}" ] && { _err "\$1 must be a digit number."; RV=255; } || shift
-echo "$*"
+echo "$*" >&2
 case ${MY_SELF##*/} in
 ash|bash|sh) return $RV;;
 *) exit $RV;;
@@ -1401,11 +1401,11 @@ _say_jwm_taskbar_y(){
 [ "$ERMERG" ]     || EMERG=1
 _emerg(){
 test "$EMERGENCY" || return 1
-echo -e "$0:EMERGENGY:$*"
+echo -e "$0:EMERGENGY:$*"   >&2
 }
 _emergency(){
 test "$EMERGENCY" || return 1
-echo -e "$0:EMERGENGY:$*"
+echo -e "$0:EMERGENGY:$*"   >&2
 }
 
 [ "$ALERT" ] || ALERT=1
@@ -1413,11 +1413,11 @@ echo -e "$0:EMERGENGY:$*"
 [ "$ALARM" ] || ALARM=1
 _alert(){
 test "$ALERT" || return 1
-echo -e "$0:ALERT:$*"
+echo -e "$0:ALERT:$*"  >&2
 }
 _alarm(){
 test "$ALERT" || return 1
-echo -e "$0:ALERT:$*"
+echo -e "$0:ALERT:$*"  >&2
 }
 
 [ "$CRIT" ]     || CRIT=1
@@ -1425,11 +1425,11 @@ echo -e "$0:ALERT:$*"
 [ "$CRITICAL" ] || CRITICAL=1
 _crit(){
 test "$CRIT" || return 1
-echo -e "$0:CRITICAL:$*"
+echo -e "$0:CRITICAL:$*" >&2
 }
 _critical(){
 test "$CRIT" || return 1
-echo -e "$0:CRITICAL:$*"
+echo -e "$0:CRITICAL:$*" >&2
 }
 
 [ "$ERROR" ] || ERROR=1
@@ -1437,11 +1437,11 @@ echo -e "$0:CRITICAL:$*"
 #[ "$ERR" ]   || ERR=/dev/stderr
 _err(){
 test "$ERROR" || return 1
-echo -e "$0:ERROR:$*"
+echo -e "$0:ERROR:$*"  >&2
 }
 _error(){
 test "$ERROR" || return 1
-echo -e "$0:ERROR:$*"
+echo -e "$0:ERROR:$*"  >&2
 }
 
 [ "$WARN" ]    || WARN=1
@@ -1449,11 +1449,11 @@ echo -e "$0:ERROR:$*"
 [ "$WARNING" ] || WARNING=1
 _warn(){
 test "$WARN" || return 1
-echo -e "$0:WARNING:$*"
+echo -e "$0:WARNING:$*"  >&2
 }
 _warning(){
 test "$WARN" || return 1
-echo -e "$0:WARNING:$*"
+echo -e "$0:WARNING:$*"  >&2
 }
 
 [ "$NOTICE" ] || NOTICE=1
@@ -1461,11 +1461,11 @@ echo -e "$0:WARNING:$*"
 [ "$NOTE" ]   || NOTE=1
 _notice(){
 test "$NOTICE" || return 1
-echo -e "$0:NOTICE:$*"
+echo -e "$0:NOTICE:$*"   >&2
 }
 _note(){
 test "$NOTICE" || return 1
-echo -e "$0:NOTICE:$*"
+echo -e "$0:NOTICE:$*"   >&2
 }
 
 [ "$INFO" ]        || INFO=1
@@ -1473,23 +1473,23 @@ echo -e "$0:NOTICE:$*"
 [ "$INFORMATION" ] || INFORMATION=1
 _info(){
 test "$INFO" || return 1
-echo -e "$0:INFO:$*"
+echo -e "$0:INFO:$*"  >&2
 }
 _information(){
 test "$INFO" || return 1
-echo -e "$0:INFO:$*"
+echo -e "$0:INFO:$*"  >&2
 }
 
 [ "$DEBUG" ] || DEBUG=
 _debug(){
 test "$DEBUG" || return 1
-echo -e "$0:DEBUG:$*"
+echo -e "$0:DEBUG:$*"  >&2
 }
 
 [ "$DEBUGX" ] || DEBUGX=
 _debugx(){
 test "$DEBUGX" || return 1
-echo -e "$0:DEBUGX:$@"
+echo -e "$0:DEBUGX:$@"  >&2
 }
 
  _emergdt(){ test "$EMERGENCY" || return 1; echo -e "`date +%F-%T`:$0:EMERGENGY:$*"; }
@@ -1512,10 +1512,10 @@ _DATE_=`date +%s.%N | sed 's:.*\(..\..*\):\1:'`
 #_DATE_=`date +%s,%N | sed 's:.*\(..\,.*\):\1:'`
 if test "$2"; then
 _TIME_=`dc $_DATE_ $2 \- p`
-echo "$0:TIME:$1:$_TIME_"
+echo "$0:TIME:$1:$_TIME_"    >&2
 else
 #echo "$0:TIME:$*:`date +%s.%N | sed 's:.*\(..\..*\):\1:'`"
-echo "$0:TIME:$*:$_DATE_"
+echo "$0:TIME:$*:$_DATE_"    >&2
 fi
 }
 
@@ -1853,8 +1853,8 @@ done
 ## start at last number (max) and rotate down
 for n in `seq $max -1 0` ; do
 #[ -e "$*".$n ] && mv $VERB "$*".$n "$*".$((n+1))
- [ -e "$errlog".$n ] || continue
- #grep -q -Ei 'warning|error|warnung|fehler' "$*".$n || { rm "$*".$n; continue; }
+ [ -e "$*".$n ] || continue
+
  mv $VERB "$*".$n "$*".$((n+1))
 done
 
