/etc/rc.d/f4puppy5: Complete colors, few clean-ups, use EXIT instead of exit, some code enhancements. Version now 0.0.3 .

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -12,13 +12,17 @@ version) _VERSION_=$version; VERSION=$version; Version=$version;;
 esac
 }
 
-test "$_VERSION_" && _assign_version _VERSION_ || _VERSION_=0.0.2
-test "$VERSION"   && _assign_version VERSION   ||   VERSION=0.0.2
-test "$Version"   && _assign_version Version   ||   Version=0.0.2
-test "$version"   && _assign_version version   ||   version=0.0.2
+test "$_VERSION_" && _assign_version _VERSION_ || _VERSION_=0.0.3
+test "$VERSION"   && _assign_version VERSION   ||   VERSION=0.0.3
+test "$Version"   && _assign_version Version   ||   Version=0.0.3
+test "$version"   && _assign_version version   ||   version=0.0.3
 SCRIPT_NAME=f4puppy5 # short for functions for puppy 5
 test "$MY_SELF" || MY_SELF="$0"
 
+case ${MY_SELF##*/} in
+ash|bash|sh) EXIT=return;;
+*)           EXIT=exit;;
+esac
 
 # colours
  Black0='\033[0;30m'
@@ -37,8 +41,80 @@ Yellow1='\033[1;33m'
   Cyan1='\033[1;36m'
  White0='\033[0;37m'
  White1='\033[1;37m'
+
+  Back0='\033[0;39m'
+ Reset0='\033[0;39m'
 Normal0='\033[0;39m'
 
+ BackBlack0='\033[0;40m'
+ BackBlack1='\033[1;30m'
+   BackRed0='\033[0;41m'
+   BackRed1='\033[1;41m'
+ BackGreen0='\033[0;42m'
+ BackGreen1='\033[1;42m'
+BackYellow0='\033[0;43m'
+BackYellow1='\033[1;43m'
+  BackBlue0='\033[0;44m'
+  BackBlue1='\033[1;44m'
+  BackPink0='\033[0;45m'
+  BackPink1='\033[1;45m'
+  BackCyan0='\033[0;46m'
+  BackCyan1='\033[1;46m'
+ BackWhite0='\033[0;47m'
+ BackWhite1='\033[1;47m'
+
+  BackBack0='\033[0;49m'
+ BackReset0='\033[0;49m'
+BackNormal0='\033[0;49m'
+
+ UsBlack0='\033[4;30m'
+ UsBlack1='\033[4;1;30m'
+   UsRed0='\033[4;31m'
+   UsRed1='\033[4;1;31m'
+ UsGreen0='\033[4;32m'
+ UsGreen1='\033[4;1;32m'
+UsYellow0='\033[4;33m'
+UsYellow1='\033[4;1;33m'
+  UsBlue0='\033[4;34m'
+  UsBlue1='\033[4;1;34m'
+  UsPink0='\033[4;35m'
+  UsPink1='\033[4;1;35m'
+  UsCyan0='\033[4;36m'
+  UsCyan1='\033[4;1;36m'
+ UsWhite0='\033[4;37m'
+ UsWhite1='\033[4;1;37m'
+
+ BoldBlack0='\033[5;30m'
+ BoldBlack1='\033[5;1;30m'
+   BoldRed0='\033[5;31m'
+   BoldRed1='\033[5;1;31m'
+ BoldGreen0='\033[5;32m'
+ BoldGreen1='\033[5;1;32m'
+BoldYellow0='\033[5;33m'
+BoldYellow1='\033[5;1;33m'
+  BoldBlue0='\033[5;34m'
+  BoldBlue1='\033[5;1;34m'
+  BoldPink0='\033[5;35m'
+  BoldPink1='\033[5;1;35m'
+  BoldCyan0='\033[5;36m'
+  BoldCyan1='\033[5;1;36m'
+ BoldWhite0='\033[5;37m'
+ BoldWhite1='\033[5;1;37m'
+
+ InvBlack0='\033[7;30m'
+ InvBlack1='\033[7;5;30m'
+   InvRed0='\033[7;31m'
+   InvRed1='\033[7;5;31m'
+ InvGreen0='\033[7;32m'
+ InvGreen1='\033[7;5;32m'
+InvYellow0='\033[7;33m'
+InvYellow1='\033[7;5;33m'
+  InvBlue0='\033[7;34m'
+  InvBlue1='\033[7;5;34m'
+  InvPink0='\033[7;35m'
+  InvPink1='\033[7;5;35m'
+  InvCyan0='\033[7;36m'
+  InvCyan1='\033[7;5;36m'
 Inv_White0='\033[0;47m'
 Inv_White1='\033[1;47m'
 # /colours
@@ -69,38 +145,75 @@ test $? = 0 || _exit 1 "Could not change into directory '$ME_DIR'"
 return 0
 }
 
+__check_if_already_running()
+{
+local PROGRAM
+test "$*" && PROGRAM="$*" || PROGRAM=$MY_SELF
+#pidof -o $$ -o %PPID "${0##*/}" >$OUT && {
+echo;echo
+pidof -o $$ -o %PPID "${PROGRAM##*/}" >$OUT && {
+    case $OUT in
+    /dev/null) echo -e "\\033[2F""Program '$PROGRAM' already running.\n"   ;;
+            *) echo -e "\\033[2F""Program '$PROGRAM' already running:\n"   ;;
+    esac
+        #$EXIT 1
+        $EXIT 0
+ }
+return $?
+}
+
 _check_if_already_running()
 {
-pidof -o $$ -o %PPID "${0##*/}" && {
-        echo "Already running."
-        exit 1
+local PROGRAM
+test "$*" && PROGRAM="$*" || PROGRAM=$MY_SELF
+#pidof -o $$ -o %PPID "${0##*/}" >$OUT && {
+pidof -o $$ -o %PPID "${PROGRAM##*/}" >$OUT && {
+        echo -e "\\033[1F\\033[7G""Program '$PROGRAM' already running."
+        return 1
+ }
+return 0
+}
+
+_exit_if_already_running()
+{
+local PROGRAM
+test "$*" && PROGRAM="$*" || PROGRAM=$MY_SELF
+#pidof -o $$ -o %PPID "${0##*/}" >$OUT && {
+pidof -o $$ -o %PPID "${PROGRAM##*/}" >$OUT && {
+        echo -e "\\033[1F\\033[7G""Program '$PROGRAM' already running."
+        $EXIT 1
  }
 return $?
 }
 
 _run_status()
 {
-test "$*" || { _return 2 "_run_status: Usage: _run_status BASENAMEPROGRAM"; return $?; }
-pidof "$*" >$OUT && { _info " '$*' running."; return 0; } || { _info " '$*' not running."; return 1; }
+test "$*"  || { _return 2 "_run_status: Usage: _run_status BASENAMEPROGRAM"; return $?; }
+pidof "${*##*/}" >$OUT && { _info " '$*' running."; return 0; } || { _info " '$*' not running."; return 1; }
 }
 
 _check_for_terminal()
 {
 local MSG
 MSG="Need a contolling terminal"
-tty >/dev/null || {
-echo -n "Pid of X server:"
-pidof X && xmessage -br red "$MSG"; exit 2; } || {
-echo "$MSG"; exit 2; }
+tty >$OUT || {
+[ "$OUT" = 'dev/null' ] || echo -n "Pid of X server:"
+pidof X >$OUT && xmessage -br red "$MSG"; $EXIT 2; } || {
+echo "$MSG"; $EXIT 2; }
 return $?
 }
 
 _exit()
 {
+local RV
+test "$*" || { _err "Usage:_exit EXITCODE MESSAGE"; }
 RV=$1
-shift
+[ "${RV//[[:digit:]]/}" ] && { _err "\$1 must be a digit number."; RV=255; } || shift
 echo "$*"
-exit $RV
+case ${MY_SELF##*/} in
+ash|bash|sh) return $RV;;
+*) exit $RV;;
+esac
 }
 
 _trap()
@@ -115,7 +228,7 @@ echo "$0:Version:$VERSION"
 if [ "$TWO_VERSION" ]; then
  return 0
 else
- exit 0
+ $EXIT 0
 fi
 }
 
@@ -167,7 +280,7 @@ else
  if test "$RV" != 0; then
   _exit $RV "Try again. Good Luck!"
  else
-  exit $RV
+  $EXIT $RV
  fi
 fi
 return $?
@@ -185,19 +298,22 @@ PARAMETERS="
 $ADD_PARAMETERS"
 }
 
-OUT=/dev/null;ERR=$OUT;Q=-q;QUIET=$Q;DBG=''
-[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr;Q='';QUIET=$Q;DBG=-d; }
+                  OUT=/dev/null;  ERR=$OUT;       Q=-q;QUIET=$Q;DBG='';L_DBG='';     A_DBG=''
+[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr;Q='';QUIET=$Q;DBG=-d;L_DBG=--debug;A_DBG=-debug; }
 [ "$DEBUG" = "2" ] && set -x
 _parse_basic_parameters()
 {
-OUT=/dev/null;ERR=$OUT;Q=-q;QUIET=$Q;DBG='';DO_SHIFT=0
+OUT=/dev/null;ERR=$OUT;Q=-q;QUIET=$Q;DBG='';L_DBG='';A_DBG='';DO_SHIFT=0
 case $1 in
--h|-H|-*help) _usage 0 "$ADD_HELP_MSG";;
--V|-*version) _version;;
--v|-*verbose) VERBOSE=1;VERB=-v;A_VERB=-verbose;L_VERB=--verbose;Q='';QUIET=$Q;DBG=-d;
-              OUT=/proc/self/fd/1;ERR=/proc/self/fd/2; [ "$TWO_VERBOSE" ] || DO_SHIFT=$((DO_SHIFT+1));;
--d|-*debug)   set -x; [ "$TWO_DEBUG" ] || DO_SHIFT=$((DO_SHIFT+1));;
+-h|-H|*help) _usage 0 "$ADD_HELP_MSG";;
+-V|*version) _version;;
+-v|*verbose) VERBOSE=1;VERB=-v;A_VERB=-verbose;L_VERB=--verbose;
+             Q='';QUIET=$Q;
+             DEBUG=1;DBG=-d;L_DBG=--debug;A_DBG=-debug;
+             OUT=/proc/self/fd/1;ERR=/proc/self/fd/2; [ "$TWO_VERBOSE" ] || DO_SHIFT=$((DO_SHIFT+1));;
+-d|*debug)   set -x; [ "$TWO_DEBUG" ] || DO_SHIFT=$((DO_SHIFT+1));;
 esac
+export VERBOSE VERB L_VERB A_VERB Q QUIET DEBUG DBG L_DBG A_DBG OUT ERR
 }
 
 _parse_options()
@@ -1938,7 +2054,7 @@ fi
 
 case $RV in
 0) return 0;;
-*) exit $RV;;
+*) $EXIT $RV;;
 esac
 }
 
@@ -1980,7 +2096,7 @@ fi
 
 case $RV in
 0) return 0;;
-*) exit $RV;;
+*) $EXIT $RV;;
 esac
 }
 
@@ -1989,11 +2105,11 @@ _pidof()
 local RV
 case $1 in
 -q) shift;
-pidof $* >/dev/null; return $?
+pidof ${*##*/} >/dev/null; return $?
 ;;
 *)
-echo -n "pids of $*:"
-pidof $*; RV=$?
+echo -n "pids of $* ( ${*##*/} ) :"
+pidof ${*##*}; RV=$?
 test "$RV" = 0 || echo
 return $RV
 ;;
@@ -2005,13 +2121,13 @@ _batch_diff1()
 local SIMPLE FILES1_ FILES1 FILES2_ FILES2 aF oneF1 oneF2
 _debug "_batch_diff1: '$*'" >&2
 
-test "$*" || { _err "Usage: _batch_diff [ -s ] DIR"; return 1 2>$ERR || exit 1; }
+test "$*" || { _err "Usage: _batch_diff [ -s ] DIR"; return 1 2>$ERR || $EXIT 1; }
 
 test "$1" = '-s' && { SIMPLE=YES; shift; }
 
-test -d "$@" || { _err "'$@' not a directory"; return 1 2>$ERR || exit 1; }
+test -d "$@" || { _err "'$@' not a directory"; return 1 2>$ERR || $EXIT 1; }
 
-cd "$@" || { _err "Could not change into '$@'"; return 1 2>$ERR || exit 1; }
+cd "$@" || { _err "Could not change into '$@'"; return 1 2>$ERR || $EXIT 1; }
 
 FILES1_=`ls -1dv *`
 
@@ -2077,16 +2193,16 @@ _batch_diff2()
 local SIMPLE INVERT FILES1_ FILES1 FILES2_ FILES2 aF oneF1 oneF2 alreadyDONE
 _debug "_batch_diff2: '$*'" >&2
 
-test "$*" || { _err "Usage: _batch_diff2 [ -s |& -i ] DIR"; return 1 2>$ERR || exit 1; }
+test "$*" || { _err "Usage: _batch_diff2 [ -s |& -i ] DIR"; return 1 2>$ERR || $EXIT 1; }
 
 
 test "$1" = '-s' && { SIMPLE=YES; shift; }
 test "$1" = '-i' && { INVERT=YES; shift; }
 test "$1" = '-s' && { SIMPLE=YES; shift; }
 
-test -d "$@" || { _err "'$@' not a directory"; return 1 2>$ERR || exit 1; }
+test -d "$@" || { _err "'$@' not a directory"; return 1 2>$ERR || $EXIT 1; }
 
-cd "$@" || { _err "Could not change into '$@'"; return 1 2>$ERR || exit 1; }
+cd "$@" || { _err "Could not change into '$@'"; return 1 2>$ERR || $EXIT 1; }
 
 FILES1_=`ls -1dv *`
 
@@ -2195,7 +2311,7 @@ DEBUG=1
 local SIMPLE INVERT REMOVE FILES1_ FILES1 FILES2_ FILES2 aF oneF1 oneF2 alreadyDONE
 _debug "_batch_diff2: '$*'" >&2
 
-test "$*" || { _err "Usage: _batch_diff3 [ -s -i | -r ] DIR"; return 1 2>$ERR || exit 1; }
+test "$*" || { _err "Usage: _batch_diff3 [ -s -i | -r ] DIR"; return 1 2>$ERR || $EXIT 1; }
 
 while [ "$2" ]; do
 case "$1" in
@@ -2206,9 +2322,9 @@ esac
 shift
 done
 
-test -d "$@" || { _err "'$@' not a directory"; return 1 2>$ERR || exit 1; }
+test -d "$@" || { _err "'$@' not a directory"; return 1 2>$ERR || $EXIT 1; }
 
-cd "$@" || { _err "Could not change into '$@'"; return 1 2>$ERR || exit 1; }
+cd "$@" || { _err "Could not change into '$@'"; return 1 2>$ERR || $EXIT 1; }
 
 FILES1_=`ls -1dv *`
 
@@ -2330,7 +2446,7 @@ test "$DRY" || DRY=  ##DRY RUN - don't change the original file
 
 pwd
 
-cd `pwd`/woof-code/rootfs-skeleton/ || { echo "Could not change into `pwd`/woof-code/rootfs-skeleton/"; exit 1; }
+cd `pwd`/woof-code/rootfs-skeleton/ || { echo "Could not change into `pwd`/woof-code/rootfs-skeleton/"; $EXIT 1; }
 
 for file in bin/* sbin/* usr/bin/* usr/sbin/* usr/local/*/*
 do
@@ -2404,7 +2520,7 @@ test "$DRY" || DRY=  ##DRY RUN - don't change the original file
 
  pwd
 
-cd `pwd`/woof-code/rootfs-skeleton/ || { echo "Could not change into `pwd`/woof-code/rootfs-skeleton/"; exit 1; }
+cd `pwd`/woof-code/rootfs-skeleton/ || { echo "Could not change into `pwd`/woof-code/rootfs-skeleton/"; $EXIT 1; }
 
 for file in bin/* sbin/* usr/bin/* usr/sbin/* usr/local/*/*
 do
