/etc/rc.d/f4puppy5 : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -12,10 +12,10 @@ version) _VERSION_=$version; VERSION=$version; Version=$version;;
 esac
 }
 
-test "$_VERSION_" && _assign_version _VERSION_ || _VERSION_=0.0.3
-test "$VERSION"   && _assign_version VERSION   ||   VERSION=0.0.3
-test "$Version"   && _assign_version Version   ||   Version=0.0.3
-test "$version"   && _assign_version version   ||   version=0.0.3
+test "$_VERSION_" && _assign_version _VERSION_ || _VERSION_=0.0.3a
+test "$VERSION"   && _assign_version VERSION   ||   VERSION=0.0.3a
+test "$Version"   && _assign_version Version   ||   Version=0.0.3a
+test "$version"   && _assign_version version   ||   version=0.0.3a
 SCRIPT_NAME=f4puppy5 # short for functions for puppy 5
 test "$MY_SELF" || MY_SELF="$0"
 
@@ -150,10 +150,10 @@ __check_if_already_running()
 local PROGRAM
 test "$*" && PROGRAM="$*" || PROGRAM=$MY_SELF
 #pidof -o $$ -o %PPID "${0##*/}" >$OUT && {
-echo;echo
+#echo;echo
 pidof -o $$ -o %PPID "${PROGRAM##*/}" >$OUT && {
     case $OUT in
-    /dev/null) echo -e "\\033[2F""Program '$PROGRAM' already running.\n"   ;;
+    /dev/null) echo -e "\\033[1F""Program '$PROGRAM' already running.\n"   ;;
             *) echo -e "\\033[2F""Program '$PROGRAM' already running:\n"   ;;
     esac
         #$EXIT 1
@@ -542,7 +542,7 @@ oCHAR=`printf %o \'"$oneCHAR"`
 
 oSTRING=$oSTRING"\\0$oCHAR"
 
-done<<EoI
+done <<EoI
 `echo "$STRING"`
 EoI
 
@@ -553,20 +553,20 @@ do
 #test "$oneLINE" || continue
  _debug "oneLINE='$oneLINE'" >&2
  STRING=`echo "$oneLINE" | sed 's!\(.\)!"\1"\n!g'`
- _debugx "STRING='$STRING'" >&2
+ _debugx "STRING='$STRING'"  >&2
  while read -r oneCHAR
  do
  _debugx "oneCHAR='$oneCHAR'" >&2
  oneCHAR=`echo "$oneCHAR" | sed 's!^"!!;s!"$!!'`
- _debug "oneCHAR='$oneCHAR'" >&2
+ _debug "oneCHAR='$oneCHAR'"  >&2
  oCHAR=`printf %o \'"$oneCHAR"`
- _debug "oCHAR='$oCHAR'" >&2
+ _debug "oCHAR='$oCHAR'"      >&2
  #test "$oCHAR" = 134 && oCHAR=0134
 
  oSTRING=$oSTRING"\\0$oCHAR"
  _debugx "oSTRING='$oSTRING'" >&2
 
- done<<EoI
+ done <<EoI
 `echo "$STRING"`
 EoI
 
@@ -596,14 +596,15 @@ set - "`echo "$GET_OPT" | sed "s^' '^'\n'^g"`"
 
 while read oneOPTION
 do
-test "$oneOPTION" || continue
-case $oneOPTION
-in
-*) :;;
-esac
-done<<EoI
+ test "$oneOPTION" || continue
+ case $oneOPTION
+ in
+ *) :;;
+ esac
+done <<EoI
 `set`
 EoI
+
 set -
 return $?
 }
@@ -707,8 +708,8 @@ _basic_error_check()
 local USAGE RV
 USAGE="Usage: _basic_error_check \$? \"MESSAGE\""
 RV=$1
-test "$RV" || { RV=127; set - $USAGE $*; echo "$USAGE -- got '$*'" >&2; }
-test "${RV//[0-9]/}" && { RV=127; set - $USAGE $*; echo "$USAGE -- got '$*'" >&2; }
+test "$RV"           || { RV=127; set - $USAGE $*; echo -n "$1"; shift; echo " -- got '$*'" >&2; }
+test "${RV//[0-9]/}" && { RV=127; set - $USAGE $*; echo -n "$1"; shift; echo " -- got '$*'" >&2; }
 shift
 if test "$RV" != "0"; then
 __ERRORS__="$__ERRORS__
@@ -775,10 +776,10 @@ fi
 #================= Check /tmp if read-write ==================================
 _check_proc()
 {
-  mountpoint -q /proc && return $? || {
-  busybox mount -o remount,rw /dev/root/ /
+  mountpoint $Q /proc && return $? || {
+  busybox mount $VERB $VERB -o remount,rw /dev/root/ /
   test -d /proc || mkdir -p /proc
-  busybox mount -t proc proc /proc
+  busybox mount $VERB $VERB -t proc proc /proc
   return $?
  }
 }
@@ -787,11 +788,11 @@ _check_tmp()
 {
  test -d /tmp && return $? || {
  local STATUS_
- busybox mount -o remount,rw /dev/root/ /
+ busybox mount $VERB $VERB -o remount,rw /dev/root/ /
  STATUS_=$((STATUS_+$?))
  mkdir -p /tmp
  STATUS_=$((STATUS_+$?))
- chmod 1777 /tmp
+ chmod $VERB 1777 /tmp
  STATUS_=$((STATUS_+$?))
  return $STATUS_
  }
@@ -803,9 +804,9 @@ _check_proc || _crit "Difficulties with /proc  .."
 _check_tmp  || _crit "Difficulties with /tmp  .."
 
 mountpoint $Q /tmp && {
-grep  ' /tmp ' /proc/mounts    | cut -f4 -d' ' | grep $Q -w 'rw' && return 0 || { busybox mount -o remount,rw tmpfs /tmp;   return $?; }
+grep  ' /tmp ' /proc/mounts    | cut -f4 -d' ' | grep $Q -w 'rw' && return 0 || { busybox mount $VERB $VERB -o remount,rw tmpfs /tmp;   return $?; }
  } || {
-grep '^/dev/root' /proc/mounts | cut -f4 -d' ' | grep $Q -w 'rw' && return 0 || { busybox mount -o remount,rw /dev/root/ /; return $?; }
+grep '^/dev/root' /proc/mounts | cut -f4 -d' ' | grep $Q -w 'rw' && return 0 || { busybox mount $VERB $VERB -o remount,rw /dev/root/ /; return $?; }
  }
 }
 
@@ -997,43 +998,85 @@ echo ${_ROOT_SCREEN_Y_}
 
 #=============== LOGLEVEL / DEBUG MESSAGES ==================================
 [ "$ERMERGENCY" ] || EMERGENCY=1
+[ "$ERMERGENCY" ] && EMERG="$EMERGENCY"
+[ "$ERMERG" ]     || EMERG=1
 _emerg(){
+test "$EMERGENCY" || return 1
+echo -e "$0:EMERGENGY:$*"
+}
+_emergency(){
 test "$EMERGENCY" || return 1
 echo -e "$0:EMERGENGY:$*"
 }
 
 [ "$ALERT" ] || ALERT=1
+[ "$ALERT" ] && ALARM="$ALERT"
+[ "$ALARM" ] || ALARM=1
 _alert(){
 test "$ALERT" || return 1
 echo -e "$0:ALERT:$*"
 }
+_alarm(){
+test "$ALERT" || return 1
+echo -e "$0:ALERT:$*"
+}
 
-[ "$CRIT" ] || CRIT=1
+[ "$CRIT" ]     || CRIT=1
+[ "$CRIT" ]     && CRITICAL="$CRIT"
+[ "$CRITICAL" ] || CRITICAL=1
 _crit(){
+test "$CRIT" || return 1
+echo -e "$0:CRITICAL:$*"
+}
+_critical(){
 test "$CRIT" || return 1
 echo -e "$0:CRITICAL:$*"
 }
 
 [ "$ERROR" ] || ERROR=1
+#[ "$ERROR" ] && ERR="$ERROR"
+#[ "$ERR" ]   || ERR=/dev/stderr
 _err(){
 test "$ERROR" || return 1
 echo -e "$0:ERROR:$*"
 }
+_error(){
+test "$ERROR" || return 1
+echo -e "$0:ERROR:$*"
+}
 
-[ "$WARN" ] || WARN=1
+[ "$WARN" ]    || WARN=1
+[ "$WARN" ]    && WARNING="$WARN"
+[ "$WARNING" ] || WARNING=1
 _warn(){
+test "$WARN" || return 1
+echo -e "$0:WARNING:$*"
+}
+_warning(){
 test "$WARN" || return 1
 echo -e "$0:WARNING:$*"
 }
 
 [ "$NOTICE" ] || NOTICE=1
+[ "$NOTICE" ] && NOTE="$NOTICE"
+[ "$NOTE" ]   || NOTE=1
 _notice(){
 test "$NOTICE" || return 1
 echo -e "$0:NOTICE:$*"
 }
+_note(){
+test "$NOTICE" || return 1
+echo -e "$0:NOTICE:$*"
+}
 
-[ "$INFO" ] || INFO=1
+[ "$INFO" ]        || INFO=1
+[ "$INFO" ]        && INFORMATION="$INFO"
+[ "$INFORMATION" ] || INFORMATION=1
 _info(){
+test "$INFO" || return 1
+echo -e "$0:INFO:$*"
+}
+_information(){
 test "$INFO" || return 1
 echo -e "$0:INFO:$*"
 }
@@ -1143,13 +1186,13 @@ test "$typeCOM" = "$whichCOM" && {
 #========= make nodes in /dev if /dev not mounted ============================
 _mkdevices()
 {
-mountpoint -q /dev && return 0
+mountpoint $Q /dev && return 0
 test "`type mdev`" && { mdev -s; return $?; }
  while read maj min siz dev ; do
   [ "${maj//[[:digit:]]/}" ] && continue
   [ "$maj" -a "$min" -a "$dev" ] || continue
   test -b /dev/$dev || mknod /dev/$dev b $maj $min
- done</proc/partitions
+ done </proc/partitions
 }
 
 #============ Test to filter out links =======================================
@@ -1287,23 +1330,28 @@ else { _warn "Unknown filetype '$@' - neither Link, pipe, Socket, file nor direc
 #=============== Rotate Logs =================================================
 _log_rotate()
 {
-test "$*" || { _err "_log_rotate:Need filename to rotate"; return 1; }
+test "$*"    || { _err "_log_rotate:Need filename to rotate";  return 1; }
 test -f "$*" || { _err "_log_rotate: '$*' not a regular file"; return 1; }
+
+local nrLOGS oneLOG
 nrLOGS=`ls -1v "$*".[0-9]* | wc -l`
 _debug "nrLOGS='$nrLOGS'"
 while read oneLOG
 do
-test "$oneLOG" || continue
+   test "$oneLOG" || continue
 test -f "$oneLOG" || continue
+
 _debug "oneLOG='$oneLOG' --> ${oneLOG%.[0-9]*}.$((nrLOGS+1))"
-mv "$oneLOG" "${oneLOG%.[0-9]*}".$((nrLOGS+1))
+mv $VERB "$oneLOG" "${oneLOG%.[0-9]*}".$((nrLOGS+1))
 nrLOGS=$((nrLOGS-1))
-done<<EoI
+
+done <<EoI
 `ls -1v "$*".[0-9]* | tac`
 EoI
+
 test -e "${*}.1" && { _err "Something went wrong"; return 1 ; }
 _info "moving $* --> ${*}.1"
-mv "$*" "${*}.1"
+mv $VERB "$*" "${*}.1"
 }
 
 
@@ -2645,8 +2693,8 @@ EoI
    [ "$?" = 0 ] || continue
    if test ! "$DRY"; then ## DRY RUN
     rm "$file"
-    mv /tmp/${file##*/} "$file"
-    chmod $PERM "$file"
+    mv $VERB /tmp/${file##*/} "$file"
+    chmod $VERB $PERM "$file"
    fi
 
 done
@@ -2669,9 +2717,9 @@ for file in bin/* sbin/* usr/bin/* usr/sbin/* usr/local/*/*
 do
    [ -L "$file" ] && continue
    [ -f "$file" ] || continue
-   file "$file" | grep -i text | grep -viE 'perl|python|murgaLua_Dynamic' || continue
+   file "$file" | grep -i text | grep $Q -viE 'perl|python|murgaLua_Dynamic' || continue
 
-   grep "# New header by $_AUTHOR_, $_MONTH_ $_YEAR_" "$file" || continue
+   grep $Q "# New header by $_AUTHOR_, $_MONTH_ $_YEAR_" "$file" || continue
 
    PERM=`stat -c %a "$file"`
    [ "${PERM//[0-6]/}" ] || continue
@@ -2681,8 +2729,8 @@ do
    sed -i '2,3 d' /tmp/${file##*/}
 
    if test ! "$DRY"; then
-   mv /tmp/${file##*/} "$file"
-   chmod $PERM "$file"
+   mv $VERB /tmp/${file##*/} "$file"
+   chmod $VERB $PERM "$file"
    fi
 
 done
