Several files changed. Mostly cleanups. Found a few bugs that showed with recent busybox ash.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -12,6 +12,78 @@ QUIET=${QUIET:-'--quiet'}
 VERB=${VERB:-''}
 DBG=${DBG:-''}
 
+#=============== LOGLEVEL / DEBUG MESSAGES ==================================
+EMERGENCY=${EMERGENCY:-1}
+_emerg(){
+test "$EMERGENCY" || return 0
+echo "EMERGENGY:$*" >&2
+}
+
+ALERT=${ALERT:-1}
+_alert(){
+test "$ALERT" || return 0
+echo "$0:ALERT:$*" >&2
+}
+
+CRIT=${CRIT:-1}
+_crit(){
+test "$CRIT" || return 0
+echo "$0:CRITICAL:$*" >&2
+}
+
+ERROR=${ERROR:-1}
+_err(){
+test "$ERROR" || return 0
+echo "$0:ERROR:$*"
+}
+
+WARN=${WARN:-1}
+_warn(){
+test "$WARN" || return 0
+echo "$0:WARNING:$*" >&2
+}
+
+NOTICE=${NOTICE:-1}
+_notice(){
+test "$NOTICE" || return 0
+echo "$0:NOTICE:$*" >&2
+}
+
+INFO=${INFO:-1}
+_info(){
+test "$INFO" || return 0
+echo "$0:INFO:$*" >&2
+}
+
+DEBUG=${DEBUG:-}
+_debug(){
+test "$DEBUG" || return 0
+echo "$0:DEBUG:$*" >&2
+}
+
+DEBUGX=${DEBUGX:-}
+_debugx(){
+test "$DEBUGX" || return 0
+echo "$0:DEBUGX:$@" >&2
+}
+
+DEBUGT=${DEBUGT:-}
+_debugt(){  #$1 label #$2 time
+
+test "$DEBUGT" || return 0
+#unset LANG LC_ALL
+local _TIME_ LC_NUMERIC=C LANG= LC_ALL=
+_DATE_=`date +%s.%N | sed 's:.*\(..\..*\):\1:'`
+#_DATE_=`date +%s,%N | sed 's:.*\(..\,.*\):\1:'`
+if test "$2"; then
+_TIME_=`dc $_DATE_ $2 \- p`
+echo "$0:TIME:$1:$_TIME_" >&2
+else
+#echo "$0:TIME:$*:`date +%s.%N | sed 's:.*\(..\..*\):\1:'`"
+echo "$0:TIME:$*:$_DATE_" >&2
+fi
+}
+
 alias >>$OUT
 unalias -a
 
@@ -33,6 +105,8 @@ alias chattr="chattr ${VERB:+'-V'}"
 #alias modprobe="modprobe $Q $VERB"
 #alias mount="mount ${VERB:+'-vv'}"
 }
+
+
 
 # Handle $0 :
 #test "$MY_SELF" || MY_SELF="$0"
@@ -432,76 +506,60 @@ _sync()
 pidof sync >>$OUT || sync
 }
 
-#=============== LOGLEVEL / DEBUG MESSAGES ==================================
-EMERGENCY=${EMERGENCY:-1}
-_emerg(){
-test "$EMERGENCY" || return 0
-echo "EMERGENGY:$*" >&2
+
+#============= networking ====================================================
+
+# ** busybox whois had until v1.25
+# ** "whois-servers.net" hardcoded fallback as host
+# ** that did never work and hung forever
+
+___whois(){
+test -s /etc/default/whois.cfg && . /etc/default/whois.cfg  # fantasy config file
+
+# see http://www.whoisservers.net/
+case $* in
+*.co.uk)           WHOIS_HOST=${WHOIS_HOST_COUK:-whois.nic.uk};;
+*.com|*.net|*.edu) WHOIS_HOST=${WHOIS_HOST_COM:-whois.crsnic.net};;
+*.de)              WHOIS_HOST=${WHOIS_HOST_DE:-whois.denic.de};;
+*.dk)              WHOIS_HOST=${WHOIS_HOST_DK:-whois.dk-hostmaster.dk};;
+*.eu)              WHOIS_HOST=${WHOIS_HOST_EU:-whois.eu};;
+*.gov)             WHOIS_HOST=${WHOIS_HOST_GOV:-whois.nic.gov};;
+*.info)            WHOIS_HOST=${WHOIS_HOST_INFO:-whois.afilias.net};;
+*.no)              WHOIS_HOST=${WHOIS_HOST_NO:-whois.norid.no};;
+*.nu)              WHOIS_HOST=${WHOIS_HOST_NU:-whois.nic.nu};;
+*.org)             WHOIS_HOST=${WHOIS_HOST_ORG:-whois.pir.org};;
+*.se)              WHOIS_HOST=${WHOIS_HOST_SE:-whois.iis.se};;
+*) :;;             # try fallback whois.nic.DOMAIN
+esac
+
+whois -h "$WHOIS_HOST" "$@"
 }
 
-ALERT=${ALERT:-1}
-_alert(){
-test "$ALERT" || return 0
-echo "$0:ALERT:$*" >&2
+__whois(){
+
+case $1 in -*) whois "$@";;
+*)
+ if test -s /etc/default/whois.cfg; then
+
+ while read DOMAIN HOST; do
+  case $DOMAIN in '#'*|'') continue;; esac
+  case $* in *.$DOMAIN) WHOIS_HOST=$HOST; break;; esac
+ done </etc/default/whois.cfg
+
+ fi
+
+ if test "$WHOIS_HOST"; then
+  whois -h "$WHOIS_HOST" "$@"
+ else
+  whois "$@"
+ fi
+;;
+esac
 }
 
-CRIT=${CRIT:-1}
-_crit(){
-test "$CRIT" || return 0
-echo "$0:CRITICAL:$*" >&2
-}
-
-ERROR=${ERROR:-1}
-_err(){
-test "$ERROR" || return 0
-echo "$0:ERROR:$*"
-}
-
-WARN=${WARN:-1}
-_warn(){
-test "$WARN" || return 0
-echo "$0:WARNING:$*" >&2
-}
-
-NOTICE=${NOTICE:-1}
-_notice(){
-test "$NOTICE" || return 0
-echo "$0:NOTICE:$*" >&2
-}
-
-INFO=${INFO:-1}
-_info(){
-test "$INFO" || return 0
-echo "$0:INFO:$*" >&2
-}
-
-DEBUG=${DEBUG:-}
-_debug(){
-test "$DEBUG" || return 0
-echo "$0:DEBUG:$*" >&2
-}
-
-DEBUGX=${DEBUGX:-}
-_debugx(){
-test "$DEBUGX" || return 0
-echo "$0:DEBUGX:$@" >&2
-}
-
-DEBUGT=${DEBUGT:-}
-_debugt(){  #$1 label #$2 time
-
-test "$DEBUGT" || return 0
-#unset LANG LC_ALL
-local _TIME_ LC_NUMERIC=C LANG= LC_ALL=
-_DATE_=`date +%s.%N | sed 's:.*\(..\..*\):\1:'`
-#_DATE_=`date +%s,%N | sed 's:.*\(..\,.*\):\1:'`
-if test "$2"; then
-_TIME_=`dc $_DATE_ $2 \- p`
-echo "$0:TIME:$1:$_TIME_" >&2
-else
-#echo "$0:TIME:$*:`date +%s.%N | sed 's:.*\(..\..*\):\1:'`"
-echo "$0:TIME:$*:$_DATE_" >&2
-fi
+# ** busybox v1.26 has whois.iana.org hardcoded as default fallback
+_whois(){
+whois -h "whois.iana.org" "$@"
 }
 
 #=================== Prefer Busybox applets ==================================
