/etc/rc.d/f4puppy5: Add COLOUR short names; add _status() function; care for TWO_HELP and TWO_VERSION variables; fix header code.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -18,6 +18,44 @@ SCRIPT_NAME=f4puppy5 # short for functions for puppy 5
 test "$MY_SELF" || MY_SELF="$0"
 
 
+# colours
+Red0='\033[0;31m'
+Red1='\033[1;31m'
+Green0='\033[0;32m'
+Green1='\033[1;32m'
+Yellow0='\033[0;33m'
+Yellow1='\033[1;33m'
+Blue0='\033[0;34m'
+Blue1='\033[1;34m'
+Pink0='\033[0;35m'
+Pink1='\033[1;35m'
+Cyan0='\033[0;36m'
+Cyan1='\033[1;36m'
+White0='\033[0;37m'
+White1='\033[1;37m'
+Black0='\033[0;39m'
+
+Inv_White0='\033[0;47m'
+Inv_White1='\033[1;47m'
+# /colours
+
+_status(){
+ _TTY_=`tty`
+ [ "$_TTY_" = 'not a tty' ] && _TTY_=/dev/console
+
+ _CHARS_=${1//[[:digit:]]/}
+ if [ "$_CHARS_" ];then echo -e "\\033[60G\\033[1;36m${_CHARS_}$Black0" >$_TTY_
+ set -- 0
+ elif [ "$1" = 0 ];then
+  /bin/echo -e "\\033[72G\\033[1;32mdone$Black0" >$_TTY_ #green [done] msg.
+ else
+  /bin/echo -e "\\033[70G\\033[1;31mfailed$Black0" >$_TTY_ #red [failed].
+  STATUS=0
+ fi
+
+ return $1 #return with same status as entry param.
+}
+
 _cd_program_dir()
 {
 ME_PROG=`readlink -f "$0"`
@@ -63,7 +101,12 @@ trap "_exit 99 \"Caught Signal\"" INT KILL TERM
 _version()
 {
 echo "$0:Version:$VERSION"
-exit 0
+
+if [ "$TWO_VERSION" ]; then
+ return 0
+else
+ exit 0
+fi
 }
 
 _have_all_commands()
@@ -108,10 +151,14 @@ $*
 "
 echo "$USAGE_MSG"
 
-if test "$RV" != 0; then
-_exit $RV "Try again. Good Luck!"
+if test "$TWO_HELP"; then
+ return $RV
 else
-exit $RV
+ if test "$RV" != 0; then
+  _exit $RV "Try again. Good Luck!"
+ else
+  exit $RV
+ fi
 fi
 return $?
 }
@@ -138,8 +185,8 @@ case $1 in
 -h|-H|-*help) _usage 0 "$ADD_HELP_MSG";;
 -V|-*version) _version;;
 -v|-*verbose) VERBOSE=1;VERB=-v;A_VERB=-verbose;L_VERB=--verbose;Q='';QUIET=$Q;DBG=-d;
-              OUT=/proc/self/fd/1;ERR=/proc/self/fd/2; DO_SHIFT=$((DO_SHIFT+1));;
--d|-*debug)   set -x; DO_SHIFT=$((DO_SHIFT+1));;
+              OUT=/proc/self/fd/1;ERR=/proc/self/fd/2; [ "$TWO_VERBOSE" ] || DO_SHIFT=$((DO_SHIFT+1));;
+-d|-*debug)   set -x; [ "$TWO_DEBUG" ] || DO_SHIFT=$((DO_SHIFT+1));;
 esac
 }
 
@@ -2209,16 +2256,17 @@ MY_SELF="/$file"
 MY_PID=\$\$
 
 test -f /etc/rc.d/f4puppy5 && {
-source /etc/rc.d/f4puppy5
+[ "\$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5
 
 ADD_PARAMETER_LIST=""
 ADD_PARAMETERS=""
 _provide_basic_parameters
 
+TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
 ADD_HELP_MSG="\$_COMMENT_"
 _parse_basic_parameters "\$@"
 [ "\$DO_SHIFT" ] && [ ! "\${DO_SHIFT//[[:digit:]]/}" ] && {
-  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }
+  for oneSHIFT in \`seq 1 1 \$DO_SHIFT\`; do shift; done; }
 
 _trap
 
@@ -2274,4 +2322,7 @@ do
 done
 }
 
-
+###END###
+_HAVE_F4PUPPY5_=1
+  HAVE_F4PUPPY5=1
+###END###
