f4puppy5 : Bulk Maintanance Replacement of today.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5 b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
--- a/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
+++ b/woof-code/rootfs-skeleton/etc/rc.d/f4puppy5
@@ -2,7 +2,7 @@
 
 [ "$_HAVE_F4PUPPY5_" ] && return 0
 
-VERSION=0.0.2
+VERSION=0.0.3
 SCRIPT_NAME=f4puppy5 # short for functions for puppy 5
 
 unalias -a
@@ -547,61 +547,61 @@ pidof sync || sync
 }
 
 #=============== LOGLEVEL / DEBUG MESSAGES ==================================
-EMERGENCY=1
+[ "$EMERGENCY" ] || EMERGENCY=1
 _emerg(){
 test "$EMERGENCY" || return 0
-echo "EMERGENGY:$*"
+echo "EMERGENGY:$*" >&2
 }
 
-ALERT=1
+[ "$ALERT" ] || ALERT=1
 _alert(){
 test "$ALERT" || return 0
-echo "$0:ALERT:$*"
+echo "$0:ALERT:$*" >&2
 }
 
-CRIT=1
+[ "$CRIT" ] || CRIT=1
 _crit(){
 test "$CRIT" || return 0
-echo "$0:CRITICAL:$*"
+echo "$0:CRITICAL:$*" >&2
 }
 
-ERROR=1
+[ "$ERROR" ] || ERROR=1
 _err(){
 test "$ERROR" || return 0
-echo "$0:ERROR:$*"
+echo "$0:ERROR:$*" >&2
 }
 
-WARN=1
+[ "$WARN" ] || WARN=1
 _warn(){
 test "$WARN" || return 0
-echo "$0:WARNING:$*"
+echo "$0:WARNING:$*" >&2
 }
 
-NOTICE=1
+[ "$NOTICE" ] || NOTICE=1
 _notice(){
 test "$NOTICE" || return 0
-echo "$0:NOTICE:$*"
+echo "$0:NOTICE:$*" >&2
 }
 
-INFO=1
+[ "$INFO" ] || INFO=1
 _info(){
 test "$INFO" || return 0
-echo "$0:INFO:$*"
+echo "$0:INFO:$*" >&2
 }
 
-DEBUG=
+[ "$DEBUG" ] || DEBUG=
 _debug(){
 test "$DEBUG" || return 0
-echo "$0:DEBUG:$*"
+echo "$0:DEBUG:$*" >&2
 }
 
-DEBUGX=
+[ "$DEBUGX" ] || DEBUGX=
 _debugx(){
 test "$DEBUGX" || return 0
-echo "$0:DEBUGX:$@"
+echo "$0:DEBUGX:$@" >&2
 }
 
-DEBUGT=1
+[ "$DEBUGT" ] || DEBUGT=1
 _debugt(){  #$1 label #$2 time
 
 test "$DEBUGT" || return 0
@@ -609,6 +609,7 @@ test "$DEBUGT" || return 0
 local _TIME_ LC_NUMERIC=C LANG= LC_ALL=
 _DATE_=`date +%s.%N | sed 's:.*\(..\..*\):\1:'`
 #_DATE_=`date +%s,%N | sed 's:.*\(..\,.*\):\1:'`
+(
 if test "$2"; then
 _TIME_=`dc $_DATE_ $2 \- p`
 echo "$0:TIME:$1:$_TIME_"
@@ -616,6 +617,7 @@ else
 #echo "$0:TIME:$*:`date +%s.%N | sed 's:.*\(..\..*\):\1:'`"
 echo "$0:TIME:$*:$_DATE_"
 fi
+) >&2
 }
 
 
@@ -1622,7 +1624,8 @@ case $1 in
 pidof $* >$OUT; return $?
 ;;
 *)
-pidof $*;return $?
+echo -n "Pids of $*:"
+pidof $* && { return $?; true; } || { RV=$?; echo; return $RV; }
 ;;
 esac
 }
