/etc/rc.d/functions4puppy : Replaced by the one found currently in the system.

diff --git a/woof-code/rootfs-skeleton/etc/rc.d/functions4puppy b/woof-code/rootfs-skeleton/etc/rc.d/functions4puppy
--- a/woof-code/rootfs-skeleton/etc/rc.d/functions4puppy
+++ b/woof-code/rootfs-skeleton/etc/rc.d/functions4puppy
@@ -1,43 +1,43 @@
-#!/bin/sh
 #Barry Kauler 2007 www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #created for v3.01, oct 2007.
 #v555 updated with DISTRO_FILE_PREFIX.
 #w478 update.
 #w482 use xorriso instead of cdrtools/cdrkit if installed,
-#w482 variables CDRECORD and MKISOFS are exported by
-# /etc/rc.d/rc.shutdown and /usr/sbin/savesession-dvd.
+#w482 variables CDRECORD and MKISOFS are exportedby rc.shutdown and savesessio-dvd.
 #w482 replace -pad in cdrecord with padsize=300k.
 
 
-###KRG Fr 31. Aug 23:34:58 GMT+1 2012
 
-trap "exit 1" HUP INT QUIT KILL TERM
+#************
+#KRG
+
 
 OUT=/dev/null;ERR=$OUT
 [ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
-[ "$DEBUG" = "2" ] && set -x
+[ "$DEBUG" = 2 ] && set -x
 
-Version='1.1'
+
+Version=1.1-KRG-MacPup_O2
 
 usage(){
-USAGE_MSG="
-$0 [ PARAMETERS ]
-
--V|--version : showing version information
--H|--help : show this usage information
-
-*******  *******  *******  *******  *******  *******  *******  *******  *******
-$2
+MSG="
+$0 [ help | version ]
 "
-echo "$USAGE_MSG"
+echo "$MSG
+$2"
 exit $1
 }
+[ "`echo "$1" | grep -Ei "help|\-h"`" ] && usage 0
+[ "`echo "$1" | grep -Ei "version|\-V"`" ] && { echo "$0: $Version";exit 0; }
 
-[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
-[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }
 
-###KRG Fr 31. Aug 23:34:58 GMT+1 2012
+trap "exit" HUP INT QUIT ABRT KILL TERM
+
+
+#KRG
+#************
+
 
 ########################################################################
 #
@@ -45,28 +45,24 @@ exit $1
 #
 #
 #
-# /dev/sda5:
-# LABEL="MacPup430_F3"
-# UUID="07443de5-1fab-4656-a3ab-7b1c14ccc8c8"
+# /dev/hda8:
+# LABEL="MacPup431_O2"
+# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
 # TYPE="ext3"
-# DISTRO_VERSION=430·#481·#416·#218·#478······#####change·this·as·required#####
-# DISTRO_BINARY_COMPAT="puppy"·#"ubuntu"·#"puppy"·#####change·this·as·required#####
-# case·$DISTRO_BINARY_COMPAT·in
-# puppy)·#built·entirely·from·Puppy·v2.x·or·v3.x·or·4.x·pet·pkgs.
-# DISTRO_NAME="Puppy"
-# DISTRO_FILE_PREFIX="pup"·#"ppa"·#"ppa4"·#"pup2"··#pup4··###CHANGE·AS·REQUIRED,·recommend·limit·four·characters###
-# DISTRO_COMPAT_VERSION="4"·#"2"··#4·····###CHANGE·AS·REQUIRED,·recommend·single·digit·5,·4,·3,·or·2###
-# ;;
-# esac
+# DISTRO_NAME='Puppy'
+# DISTRO_VERSION=431
+# DISTRO_BINARY_COMPAT='puppy'
+# DISTRO_FILE_PREFIX='pup'
+# DISTRO_COMPAT_VERSION='4'
 # PUPMODE=2
-# KERNVER=2.6.30.6-KRG-i486
-# ATADRIVES='·sda'
-# USB_SATAD=''
+# KERNVER=2.6.30.9-i586-dpup005-Celeron2G
 # PUP_HOME='/'
-# Linux·puppypc·2.6.30.6-KRG-i486·#1·SMP·Sun·Jan·2·20:32:12·GMT-1·2011·i686·GNU/Linux
-# Xserver=/usr/X11R7/bin/Xvesa_stripped_upx9
-# $LANG=en_US
-# today=Mon·Oct·24·22:42:47·CEST·2011
+# SATADRIVES='·'
+# USBDRIVES='·'
+# Linux·puppypc·2.6.30.9-i586-dpup005-Celeron2G·#6·SMP·Sat·Jan·15·13:35:51·GMT-8·2011·i686·GNU/Linux
+# Xserver=/usr/X11R7/bin/Xorg
+# $LANG=de_DE@euro
+# today=Do·27.·Okt·22:44:00·GMT-1·2011
 #
 #
 #
@@ -76,24 +72,26 @@ exit $1
 
 
 KERNELVER=`uname -r` #w478
-SP_CHARS='~!@#$%^&*()_+`-={}|[]:"<>?;,./\'"'"  #"geany
-substP1=`echo "$SP_CHARS" | sed -r 'sA\.AA;sA(.)A\\\\\1Ag'`
-KERNELSUBVER=`echo -n "${KERNELVER%%[$substP1]*}" |cut -f3 -d '.'`
 
 #w478 compose name of 'zdrv', to fit 8+3 filename...
 PREFIX1CHAR=`echo -n "$DISTRO_FILE_PREFIX" | cut -c 1`
-#KERNEL3CHARS=`echo -n "$KERNELVER" | tr -d '.' | tr -d '\-' | tr -d '[a-z]' | rev | cut -c 1,2,3 | rev`
-KERNEL3CHARS=`echo -n "${KERNELVER%%[$substP1]*}" | sed 's%[[:alpha:][:punct:]]%%g' |rev |cut -c 1-3|rev`
+KERNEL3CHARS=`echo -n "$KERNELVER" | tr -d '.' | tr -d '\-' | tr -d '[a-z]' | rev | cut -c 1,2,3 | rev`
 ZDRVSFS="z${PREFIX1CHAR}${DISTRO_VERSION}${KERNEL3CHARS}.sfs"
 
 DEVCONSOLE="/dev/console" #when X not running
 PSINFO=`ps`
 [ "`echo "$PSINFO" | grep ' X :0'`" != "" ] && DEVCONSOLE="/dev/tty" #running in rxvt.
 
-#**SUBFUNCTIONS
+#waittrayclosedfunc is used by /etc/rc.d/rc.shutdown and /usr/sbin/savesession-dvd.
+#v2.16...
 waittrayclosed_func() {
  CDDRV="$1"
-
+ #while [ "`dvd+rw-mediainfo $CDDRV 2>&1 | grep 'no media mounted'`" != "" ];do
+ # clear
+ # echo -e "\\033[1;31mThe media tray appears to be open, or media not inserted." >$DEVCONSOLE #31=red
+ # echo -en "Please insert media and/or close tray then press ENTER key:\\033[0;39m " >$DEVCONSOLE
+ # read waitaenter
+ #done
  if [ "`cddetect -d${CDDRV} | grep '^tray open!'`" != "" ];then #v2.22
   echo -e "\\033[1;31mThe media tray appears to be open." >$DEVCONSOLE #31=red
   echo -en "Please close tray then press ENTER key:\\033[0;39m " >$DEVCONSOLE
@@ -102,86 +100,69 @@ waittrayclosed_func() {
  echo -e "\\033[1;34mIF STOPPED LONG TIME AT THIS MSG, MAKE SURE TRAY IS CLOSED THEN PRESS ENTER KEY:\\033[0;39m " >$DEVCONSOLE #34=blue
 }
 
-f4pFN=/etc/rc.d/functions4puppy
-get_lineno_f4p(){
-    if [ "$1" ] ; then
-    echo `grep -n -w -m1 "$1" "$f4pFN" |cut -f1 -d':'`
-    else
-    echo 'UNKNOWN'
-    fi
-}
 
-continue_func_f4p(){
-echo -n "OK, just before
-$1
-Press any key to continue .." >$DEVCONSOLE
-read -t 30 -n1 CONT_KEY
-}
-#**SUBFUNCTIONS
-
-#**MAIN
+#multisavefunc is used by /etc/rc.d/rc.shutdown and /usr/sbin/savesession-dvd.
+#these variables must be preset before calling...
+#PUPSAVE=partition,filesystem,/${DISTRO_FILE_PREFIX}save.2fs where 1st 2 are the partition holding the file.
+#SAVEPART=filesystem which is same as above filesystem.
+#PUPPYVERSION=version example: 301.
 multisavefunc() {
-
- [ "$SAVEPART" ] || return 1
-
  #save session to folder on multisession CD/DVD.
  [ "$CDRECORD" = "" ] && CDRECORD='cdrecord' #w482 precaution.
  [ "$MKISOFS" = "" ] && MKISOFS='mkisofs' #w482 precaution.
  export MKISOFS
-
  touch -c /.badfolders #update modifytime, so will get saved. badlist, see init script.
-
  MSPATTERN="/dev/$SAVEPART " #v2.22
-
  if [ "`mount | grep "$MSPATTERN"`" != "" ];then
-  echo "'/dev/$SAVEPART' mounted, must unmount it..."
+  echo "/dev/$SAVEPART mounted, must unmount it..."
   fuser -k -m /dev/$SAVEPART
   sync
   umount /dev/$SAVEPART 2> /dev/null
  fi
  CDR="/dev/$SAVEPART"
 
- if [ "`mount | grep "${CDR} "`" != "" ];then #v3.01
-  [ "$VERBOSE" ] && continue_func_f4p "Mount failure"
-  dialog --msgbox "The drive '$CDR' could not be unmounted,
+ if [ "`mount | grep "$CDR"`" != "" ];then #v3.01
+  dialog --msgbox "The drive $CDR could not be unmounted,
 so current session cannot be saved to it.
 This can happen if PC has insufficient RAM to
-copy all files off the CD, or an X application
-is still using the CD and cannot be killed.
+copy all files off the CD, or an application
+is using the CD and cannot be killed.
 
 Press ENTER key..." 0 0 >$DEVCONSOLE
-  [ "$DEBUG" ] || clear >$DEVCONSOLE
+  clear >$DEVCONSOLE
   return
  fi
-
-
+  
+ ##v3.01 have restored this... 
+ #HDRCDR="ATAPI:$CDR" #v2.16
+ #[ "`echo -n "$CDR" | grep '/dev/hd'`" = "" ] && HDRCDR="$CDR" #v2.16
+ ##...no, sata cd (/dev/scd0) is still an atapi device? so don't implement this.
  HDRCDR="$CDR" #w482
- [ "$VERBOSE" ] && continue_func_f4p "Insert CD/DVD"
- dialog --yes-label "SAVE" --no-label "NO SAVE" --yesno "Please insert the Puppy live-CD/DVD media that you booted from, into the same CD/DVD drive that you booted from -- this is '/dev/$SAVEPART' and it must be a burner drive!
+  
+ dialog --yes-label "SAVE" --no-label "NO SAVE" --yesno "Please insert the Puppy live-CD/DVD media that you booted from, into the same CD/DVD drive that you booted from -- this is /dev/$SAVEPART and it must be a burner drive!
 
 Insert CD/DVD media now, then press ENTER key to save session...
 Or, press TAB then ENTER to not save session..." 0 0 >$DEVCONSOLE
  if [ ! $? -eq 0 ];then
   eject $CDR
-  [ "$VERBOSE" ] && continue_func_f4p "Wish not to save"
   dialog --msgbox "Have not saved session to live-CD/DVD.
 Remove CD/DVD media if you wish.
 Do not press close button on drive.
 Press ENTER key to close drive tray" 0 0 >$DEVCONSOLE
   eject -t $CDR
   sleep 1
-  [ "$DEBUG" ] || clear >$DEVCONSOLE
+  clear >$DEVCONSOLE
   waittrayclosed_func $CDR #v2.16
   return
  fi
-
- [ "$DEBUG" ] || clear >$DEVCONSOLE
+ 
+ clear >$DEVCONSOLE
  if [ "`cddetect -d${CDR} | grep '^no disc!'`" != "" ];then #v2.22
   echo -e "\\033[1;31mIt seems that the media is not inserted." >$DEVCONSOLE #31=red
   echo -en "Please insert media then press ENTER key:\\033[0;39m " >$DEVCONSOLE
   read waitaenter
  fi
-
+ 
  MEDIATYPE="CD"
  waittrayclosed_func $CDR #v2.16
  DVDRWMEDIAINFO=`dvd+rw-mediainfo $CDR 2>&1`
@@ -202,192 +183,185 @@ Press ENTER key to close drive tray" 0 0 >$DEVCONSOLE
   umount $CDR 2>$ERR
  fi
 
-
+ #want to copy contents of /initrd/pup_rw to a new folder on /dev/$SAVEPART...
  MYDATE=`date "+%Y-%m-%d-%H-%M"` #this will become the folder name on cd.
 
  SAVEABORT="" #v3.01
  while [ 1 ];do #WHILELOOP1
 
+  #if have new live-cd, need a 'full save', not just what is in pup_rw. Maybe easiest
+  #way is to save two tracks, pup_ro1, which has all prior saved folders read from cd
+  #at bootup, then save latest session, pup_rw...
   if [ "$NEWISO" = "yes" ];then
-   echo "Burning data from previous '$MEDIATYPE' to first track..." >$DEVCONSOLE
-
+   echo "Burning data from previous $MEDIATYPE to first track..." >$DEVCONSOLE
+   #use last folder name from previous cd, to avoid name conflict with next folder...
    FOLDEROLD=`echo -n "$PUPSAVE" | cut -f 2 -d '/'`
-
+   #minimal error checking here, errors reported when save current session (below)...
    if [ "$MEDIATYPE" = "CD" ];then
     waittrayclosed_func $CDR #v2.16 v3.01 now HDRCDR...
     SECT=`$CDRECORD -msinfo dev=${HDRCDR} 2>/tmp/cdrerr.txt | grep '^[0-9]*.[0-9]'` #v3.01
-
     if [ "$SECT" = "" ];then
      SAVEABORT="$CDR" #v3.01
-     break #NOT ok
-
+     break
     else
      waittrayclosed_func $CDR #v2.16
      #v2.02 added -pad ...  v3.01 now HDRCDR...
      #v2.16 removed -pad from cdrecord as mkisofs has -pad by default... no, leave for now...
      $MKISOFS -D -R -C $SECT -M $CDR -quiet -new-dir-mode 0755 -graft-points ${FOLDEROLD}=/initrd/pup_ro1 | $CDRECORD -multi -data -tao -eject -v speed=4 gracetime=2 padsize=300k dev=${HDRCDR} -
     fi
-
    else #dvd
     waittrayclosed_func $CDR #v2.16
+    #v2.16 removed '-speed=4' as got 'failed to change write speed' error on one drive...
     growisofs -M $CDR -D -R -quiet -new-dir-mode 0755 -graft-points ${FOLDEROLD}=/initrd/pup_ro1 2> /tmp/dvderr.txt
    fi
-  fi # "$NEWISO" = "yes"
+  fi
   #v2.22 NEWISO=""
 
+  #normal session save of new/changed files...
+  #exclude .sfs files... v3.97 no, allow to save...
   REMSFS=""
-
+  #for ONESFS in `ls -1 /initrd/pup_rw/*.sfs 2>/dev/null | tr "\n" " "`
+  #do
+  # REMSFS="$REMSFS -x $ONESFS"
+  #done
+  
+  #tack on this exclude as well... (samba network drives mount here)
   [ -d /initrd/pup_rw/root/mnt ] && REMSFS="$REMSFS -x /initrd/pup_rw/root/mnt"
-
+  #if a new iso, do not want to save /.badfolders file...
   if [ "$NEWISO" = "yes" ];then
    [ -f /initrd/pup_rw/.badfolders ] && REMSFS="$REMSFS -x /initrd/pup_rw/.badfolders"
   fi
+  #v2.02 removed, messes up some pkgs...
+  ##move some files to /archive, they will not get reloaded...
+  #MAXASIZE="99000k"
+  #ARCHIVEFILES=`find /initrd/pup_rw -type f -mount -name "*.tar*" -or -name "*.tgz" -or -name "*.gz" -or -name "*.bz2" -or -name "*.tbz2" -or -name "*.zip" -or -size +$MAXASIZE | grep -v "/root/\.etc/" | grep -v "/root/\.usr/" | grep -v "/root/my\-roxapps/" | grep -v '\.sfs' | sed -e 's/\/initrd\/pup_rw//g'`
+  #if [ ! "$ARCHIVEFILES" = "" ];then
+  # for ONEFILE in $ARCHIVEFILES
+  # do
+  #  echo "Moving $ONEFILE to $MYDATE/archive on CD, will not reload..."
+  #  mv -f $ONEFILE /archive/ 2>$ERR
+  # done
+  # sync
+  #fi
 
   if [ "$MEDIATYPE" = "CD" ];then
    waittrayclosed_func $CDR #v2.16 v3.01 now HDRCDR...
    SECT=`$CDRECORD -msinfo dev=${HDRCDR} 2>/tmp/cdrerr.txt | grep '^[0-9]*.[0-9]'`
-
    if [ "$SECT" = "" ];then
     SAVEABORT="$CDR" #v3.01
-    break #v3.01 #NOT ok
+    break #v3.01
    else
      waittrayclosed_func $CDR #v2.16
     TSIZE=`$MKISOFS -print-size -D -R -C $SECT -M $CDR -quiet -new-dir-mode 0755 -graft-points -x /initrd/pup_rw/tmp $REMSFS -x /initrd/pup_rw/proc -x /initrd/pup_rw/sys -x /initrd/pup_rw/var -x /initrd/pup_rw/initrd -x /initrd/pup_rw/mnt ${MYDATE}=/initrd/pup_rw`
-
+    #-J Joliet extension disabled, sometimes causes failure...
+    #v2.02 added -pad ...
     waittrayclosed_func $CDR #v2.16 v3.01 now HDRCDR...
+    #v2.16 removed -pad from cdrecord as mkisofs has -pad by default... no, leave for now...
     $MKISOFS -D -R -C $SECT -M $CDR -quiet -new-dir-mode 0755 -graft-points -x /initrd/pup_rw/tmp $REMSFS -x /initrd/pup_rw/proc -x /initrd/pup_rw/sys -x /initrd/pup_rw/var -x /initrd/pup_rw/initrd -x /initrd/pup_rw/mnt ${MYDATE}=/initrd/pup_rw | $CDRECORD -multi -data -tao -eject -v speed=4 gracetime=2 padsize=300k tsize=${TSIZE}s dev=${HDRCDR} -
-    [ $? -eq 0 ] && break #ok
+    [ $? -eq 0 ] && break
    fi
    echo "Cannot write to CD" > /tmp/dvderr.txt
-
   else #dvd
     waittrayclosed_func $CDR #v2.16
     #-J Joliet extension disabled, sometimes causes failure...
     #v2.16 removed '-speed=4' as got 'failed to change write speed' error on one drive...
     growisofs -M $CDR -D -R -quiet -new-dir-mode 0755 -graft-points -x /initrd/pup_rw/tmp $REMSFS -x /initrd/pup_rw/proc -x /initrd/pup_rw/sys -x /initrd/pup_rw/var -x /initrd/pup_rw/initrd -x /initrd/pup_rw/mnt ${MYDATE}=/initrd/pup_rw 2> /tmp/dvderr.txt
-    [ $? -eq 0 ] && break #ok
+    [ $? -eq 0 ] && break
   fi
-
-  [ "$VERBOSE" ] && continue_func_f4p "NEW burn or UPDATE/UPGADE to existing"
   dialog --yes-label "BLANK ${MEDIATYPE}-R" --no-label "UPGRADE ${MEDIATYPE}-R" --yesno "ERROR MESSAGE:
 `cat /tmp/dvderr.txt | head -n 1`
 
-It seems to be time to migrate to a new 'live-${MEDIATYPE}'.
-You can migrate to a new blank '${MEDIATYPE}-R' , or upgrade
+It seems to be time to migrate to a new live-${MEDIATYPE}.
+You can migrate to a new blank ${MEDIATYPE}-R, or upgrade
 to a new Puppy version iso file that has been previously
-burnt in multisession mode to a '${MEDIATYPE}-R' .
+burnt in multisession mode to a ${MEDIATYPE}-R.
 
 WARNING:
 If the PC shuts down without allowing the migration, try
-rebooting the current 'live-$MEDIATYPE' and shutdown again.
+rebooting the current live-$MEDIATYPE and shutdown again.
 
 Have the new media ready, but do not insert it yet.
 Just select the appropriate button..." 0 0 >$DEVCONSOLE
-  RV_NEWoADD=$?
-  if [ $RV_NEWoADD -eq 0 ];then #new blank cd/dvd.
+  if [ $? -eq 0 ];then #new blank cd/dvd.
    DVDMNTPT=`mount | grep "$CDR" | tr -s " " | cut -f 3 -d " "` #in case not unmounted.
    if [ "$DVDMNTPT" = "" ];then
     mkdir /tmp/dvdmntpt
     mount -t iso9660 $CDR /tmp/dvdmntpt
-    [ ! $? -eq 0 ] && break #NOT ok
+    [ ! $? -eq 0 ] && break
     DVDMNTPT="/tmp/dvdmntpt"
    fi
-
-   echo "Copying some files off '$CDR' ..." >$DEVCONSOLE
+   #get vmlinuz etc off current dvd...
+   echo "Copying some files off $CDR..." >$DEVCONSOLE
    mkdir /tmp/livecd
-   cp "$DVDMNTPT"/isolinux.bin /tmp/livecd/
-   cp "$DVDMNTPT"/isolinux.cfg /tmp/livecd/
-   cp "$DVDMNTPT"/vmlinuz /tmp/livecd/
-   cp "$DVDMNTPT"/initrd.gz /tmp/livecd/
-   cp "$DVDMNTPT"/boot.msg /tmp/livecd/ 2>$ERR
-   cp "$DVDMNTPT"/goofy.16 /tmp/livecd/ 2>$ERR
-   cp "$DVDMNTPT"/logo.16 /tmp/livecd/ 2>$ERR #w478
-   cp "$DVDMNTPT"/help*.msg /tmp/livecd/ 2>$ERR #w478
-
-   cp "$DVDMNTPT"/"${ZDRVSFS}" /tmp/livecd/ 2>$ERR #w478
+   cp $DVDMNTPT/isolinux.bin /tmp/livecd/
+   cp $DVDMNTPT/isolinux.cfg /tmp/livecd/
+   cp $DVDMNTPT/vmlinuz /tmp/livecd/
+   cp $DVDMNTPT/initrd.gz /tmp/livecd/
+   cp $DVDMNTPT/boot.msg /tmp/livecd/ 2> /dev/null
+   cp $DVDMNTPT/goofy.16 /tmp/livecd/ 2> /dev/null
+   cp $DVDMNTPT/logo.16 /tmp/livecd/ 2> /dev/null #w478
+   cp $DVDMNTPT/help.msg /tmp/livecd/ 2> /dev/null #w478
+   #cp $DVDMNTPT/${DISTRO_FILE_PREFIX}z${DISTRO_VERSION}.sfs /tmp/livecd/ 2> /dev/null
+   cp $DVDMNTPT/${ZDRVSFS} /tmp/livecd/ 2> /dev/null #w478
    sync
    umount $CDR
-   [ ! $? -eq 0 ] && break #NOT ok
+   [ ! $? -eq 0 ] && break
    eject $CDR
-
-   [ "$VERBOSE" ] && continue_func_f4p "Insert new CD/DVD"
    dialog --msgbox "Take out the old media and write completion date on it.
-NOTE: Do not press tray-close button on '$MEDIATYPE' drive.
+NOTE: Do not press tray-close button on $MEDIATYPE drive.
 Please insert new media in tray then press ENTER key..." 0 0 >$DEVCONSOLE
    eject -t $CDR
-
+   
+   ##echo "/$PUPSFS" > /tmp/dvdextras.txt
+   #echo "/initrd/mnt/tmpfs/${DISTRO_FILE_PREFIX}r${DISTRO_VERSION}.sfs" > /tmp/dvdextras.txt #v2.22
    echo -n "/initrd/mnt/tmpfs/" > /tmp/dvdextras.txt #v3.01
    #ls -1 /initrd/mnt/tmpfs | grep "${DISTRO_FILE_PREFIX}r" >> /tmp/dvdextras.txt
    ls -1 /initrd/mnt/tmpfs | grep "${DISTRO_FILE_PREFIX}\-" >> /tmp/dvdextras.txt
-
+   
    waittrayclosed_func $CDR #v2.16
-
    if [ "$MEDIATYPE" = "DVD" ];then
     #v2.16 removed '-speed=4' as got 'failed to change write speed' error on one drive...
     growisofs -Z $CDR -R -D -quiet -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -path-list /tmp/dvdextras.txt /tmp/livecd
-    [ ! $? -eq 0 ] && break #NOT ok
-
+    [ ! $? -eq 0 ] && break
    else
     #v2.02 added -pad ...
     #v2.16 removed -pad from cdrecord as mkisofs has -pad by default... no, leave for now...
     $MKISOFS -D -R -quiet -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -path-list /tmp/dvdextras.txt /tmp/livecd | $CDRECORD -multi -tao -data -v speed=4 gracetime=2 padsize=300k dev=$HDRCDR  -
-    [ ! $? -eq 0 ] && break #NOT ok
-   fi #new blank cd/dvd.
-
-  elif [ $RV_NEWoADD -eq 1 ];then
-   : #NEWISO="yes" #loop back up.
-  else
-   break #abort
-  fi #new blank cd/dvd.
-
+    [ ! $? -eq 0 ] && break
+   fi
+  fi
+  #have new live-cd, and loops back up to save session, but need a 'full save', not just
+  #what is in pup_rw. Maybe easiest way is to save two tracks, pup_ro1, which has all prior
+  #saved folders read from cd at bootup, then save latest session, pup_rw...
   NEWISO="yes" #loop back up.
  done #end WHILELOOP1
 
  sync
-
- [ "`mount | grep "$CDR"`" ] && STILLMNTD="yes" #v3.01
+ [ "`mount | grep "$CDR"`" != "" ] && STILLMNTD="yes" #v3.01
  if [ "$STILLMNTD" = "yes" ];then
   CLOSEMSG="Press ENTER key to complete the shutdown..."
  else
-  CLOSEMSG="Remove '$MEDIATYPE' media if you wish.
+  CLOSEMSG="Remove $MEDIATYPE media if you wish.
 Do not press close button on drive.
 Press ENTER key to close drive tray
 (laptop drive, have to manually close)"
   eject $CDR
  fi
-
  if [ "$SAVEABORT" = "" ];then #v3.01
-  [ "$VERBOSE" ] && continue_func_f4p "Final burn ok"
-  dialog --msgbox "Have saved session to 'live-$MEDIATYPE'
+  dialog --msgbox "Have saved session to live-$MEDIATYPE
 (unless it has not, which is an error).
 
 ${CLOSEMSG}" 0 0 >$DEVCONSOLE
  else
-  [ "$VERBOSE" ] && continue_func_f4p "Unable to write to new CD/DVD"
-  dialog --msgbox "A problem with the '${MEDIATYPE}' drive '${SAVEABORT}' ,
-unable to save to it. Sorry.
+  dialog --msgbox "A problem with the ${MEDIATYPE} drive ${SAVEABORT},
+unable to save to save to it. Sorry.
 
 ${CLOSEMSG}" 0 0 >$DEVCONSOLE
  fi
-
  [ "$STILLMNTD" != "yes" ] && eject -t $CDR #close tray.
  sleep 1
  #waittrayclosed_func $CDR #v2.16
 } #end multisavefunc
 
-#DIAGNOSTICS
-#       Exit  status  is  subject to being overridden by environment variables.
-#       Normally they are:
-#
-#       0    if dialog is exited by pressing the Yes or OK button.
-#
-#       1    if the No or Cancel button is pressed.
-#
-#       2    if the Help button is pressed.
-#
-#       3    if the Extra button is pressed.
-#
-#       -1   if errors occur inside dialog or dialog is exited by pressing  the
-#            ESC key.
 
 ###END###
